### PR TITLE
test(mempool): refactor test_tip_priority_over_tx_hash to use mempool…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
… state

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446#-:-O1WvoYL2pY40od7f1fD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1WvlKo8YE01QAm1aLN:-O1WvlKo8YE01QAm1aLO:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/85434e3f6951fb7df6758e86d545853eb4503ee0/crates/mempool/src/mempool_test.rs#L249)):*
> ```XML
>     let mempool_state = MempoolState::new(pool_txs, queue_txs);
> 
>     mempool_state.assert_eq_mempool_state(&mempool);
> ```





_Suggestion:_
```XML
    let pool_txs = [input_big_tip_small_hash.tx, input_small_tip_big_hash.tx];
    
    let mempool_state = MempoolState::new(pool_txs, queue_txs);
    mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1WvlKo8YE01QAm1aLN:-O1k_lM-1pQtZ5KiWm4-:b-b7rteh) ([raw file](https://github.com/starkware-libs/mempool/blob/85434e3f6951fb7df6758e86d545853eb4503ee0/crates/mempool/src/mempool_test.rs#L249)):*
> ```XML
>     let mempool_state = MempoolState::new(pool_txs, queue_txs);
> 
>     mempool_state.assert_eq_mempool_state(&mempool);
> ```

I think the first option is more readable

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 256 at r2](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1lVo56DyIcjhu7lnX5:-O1lVo56DyIcjhu7lnX6:bkubgrl) ([raw file](https://github.com/starkware-libs/mempool/blob/3d75e4f31dcfdc47077d43502eb904aa4964e6ef/crates/mempool/src/mempool_test.rs#L256)):*
> ```XML
> 
> #[rstest]
> fn test_tip_priority_over_tx_hash(mut mempool: Mempool) {
> ```

What we are testing here?
I don't see `get_txs` method.



_Code quote:_
```XML
n test_tip_priority_over_tx_hash(
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446#-:-O1lWMvdDAfzvIv-ayNQ:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 256 at r2](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1lVo56DyIcjhu7lnX5:-O1lWBWy9cRnH2vJumGB:bwcr56r) ([raw file](https://github.com/starkware-libs/mempool/blob/3d75e4f31dcfdc47077d43502eb904aa4964e6ef/crates/mempool/src/mempool_test.rs#L256)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What we are testing here?
I don't see `get_txs` method.
</blockquote></details>

Please ignore.
The test tests that in tx_queue there are two transactions, and not one, as they have different tx hash.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 273 at r3](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1qg7PZ6_WiUEn7qMDQ:-O1qg7PZ6_WiUEn7qMDR:bvargno) ([raw file](https://github.com/starkware-libs/mempool/blob/89971b88576c0e0e23c6001e6fd4ae5a5969205e/crates/mempool/src/mempool_test.rs#L273)):*
> ```XML
>         TransactionReference::new(&input_small_tip_big_hash.tx),
>     ];
>     let expected_pool_txs = [input_big_tip_small_hash.tx, input_small_tip_big_hash.tx];
> ```

Unnecessary in this test, there are only 2 txs and both are in the queue.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 273 at r3](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1qg7PZ6_WiUEn7qMDQ:-O1r0mBa6rUB9NoAgmpk:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/89971b88576c0e0e23c6001e6fd4ae5a5969205e/crates/mempool/src/mempool_test.rs#L273)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unnecessary in this test, there are only 2 txs and both are in the queue.
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1uZFwX9iXNyiNIZZa9:-O1uZFwX9iXNyiNIZZaA:bkmoxw4) ([raw file](https://github.com/starkware-libs/mempool/blob/47f70b395ff9f0f0f8361775390da36419582139/crates/mempool/src/mempool_test.rs#L44)):*
> ```XML
>         let tx_queue: TransactionQueue = queue_txs.into_iter().collect();
>         MempoolState { tx_pool: Default::default(), tx_queue }
>     }
> ```

This is a good attempt for what we have now, and i nearly LGTMed it for now, but this might be hard to debug when a test fails: one would typically print the mempool contents when debugging, which will have an empty pool, and that can be very confusing to anyone not intimately aware of this util.

So I think a more strongly typed approach is in order, even at this stage.
See if this works:

```rust
#[derive(Debug)]
struct MempoolState<T> {
    tx_pool: Option<TransactionPool>,
    tx_queue: Option<TransactionQueue>,
    _phantom: PhantomData<T>,
}

#[derive(Debug)]
struct FullState;
#[derive(Debug)]
struct PartialState;

impl MempoolState<FullState> {
    fn new<P, Q>(pool_txs: P, queue_txs: Q) -> Self
    where
        P: IntoIterator<Item = ThinTransaction>,
        Q: IntoIterator<Item = TransactionReference>,
    {
        Self {
            tx_pool: Some(pool_txs.into_iter().collect()),
            tx_queue: Some(queue_txs.into_iter().collect()),
            _phantom: PhantomData,
        }
    }
}

impl Default for MempoolState<PartialState> {
    fn default() -> Self {
        Self { tx_pool: None, tx_queue: None, _phantom: PhantomData }
    }
}

impl MempoolState<PartialState> {
    fn empty() -> Self {
        Default::default()
    }

    fn _with_pool<P>(mut self, pool_txs: P) -> Self
    where
        P: IntoIterator<Item = ThinTransaction>,
    {
        self.tx_pool = Some(pool_txs.into_iter().collect());
        self
    }

    fn with_queue<Q>(mut self, queue_txs: Q) -> Self
    where
        Q: IntoIterator<Item = TransactionReference>,
    {
        self.tx_queue = Some(queue_txs.into_iter().collect());
        self
    }
}

impl<T> MempoolState<T> {
    fn assert_eq_mempool_state(&self, mempool: &Mempool) {
        self.assert_eq_pool_state(mempool);
        self.assert_eq_queue_state(mempool);
    }

    fn assert_eq_pool_state(&self, mempool: &Mempool) {
        assert_eq!(self.tx_pool.as_ref().unwrap(), &mempool.tx_pool);
    }

    fn assert_eq_queue_state(&self, mempool: &Mempool) {
        assert_eq!(self.tx_queue.as_ref().unwrap(), &mempool.tx_queue);
    }
}
```

If it works, and it is clear how to use, use it instead, otherwise lets try to think of another solution that will print `None` when debugging these kinds of tests, but that doesn't incur boilerplate during the tests, and that can also scale to the remaining components we'll soon need here (like the so-called "staging area")



_Code quote:_
```XML
    fn new_with_queue_txs_default_queue<QueueTxs>(queue_txs: QueueTxs) -> Self
    where
        QueueTxs: IntoIterator<Item = TransactionReference>,
    {
        let tx_queue: TransactionQueue = queue_txs.into_iter().collect();
        MempoolState { tx_pool: Default::default(), tx_queue }
    }
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1uZFwX9iXNyiNIZZa9:-O1vd5wM8ex2Jkm9f8Lk:bfb3xgo) ([raw file](https://github.com/starkware-libs/mempool/blob/47f70b395ff9f0f0f8361775390da36419582139/crates/mempool/src/mempool_test.rs#L44)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is a good attempt for what we have now, and i nearly LGTMed it for now, but this might be hard to debug when a test fails: one would typically print the mempool contents when debugging, which will have an empty pool, and that can be very confusing to anyone not intimately aware of this util.

So I think a more strongly typed approach is in order, even at this stage.
See if this works:

```rust
#[derive(Debug)]
struct MempoolState<T> {
    tx_pool: Option<TransactionPool>,
    tx_queue: Option<TransactionQueue>,
    _phantom: PhantomData<T>,
}

#[derive(Debug)]
struct FullState;
#[derive(Debug)]
struct PartialState;

impl MempoolState<FullState> {
    fn new<P, Q>(pool_txs: P, queue_txs: Q) -> Self
    where
        P: IntoIterator<Item = ThinTransaction>,
        Q: IntoIterator<Item = TransactionReference>,
    {
        Self {
            tx_pool: Some(pool_txs.into_iter().collect()),
            tx_queue: Some(queue_txs.into_iter().collect()),
            _phantom: PhantomData,
        }
    }
}

impl Default for MempoolState<PartialState> {
    fn default() -> Self {
        Self { tx_pool: None, tx_queue: None, _phantom: PhantomData }
    }
}

impl MempoolState<PartialState> {
    fn empty() -> Self {
        Default::default()
    }

    fn _with_pool<P>(mut self, pool_txs: P) -> Self
    where
        P: IntoIterator<Item = ThinTransaction>,
    {
        self.tx_pool = Some(pool_txs.into_iter().collect());
        self
    }

    fn with_queue<Q>(mut self, queue_txs: Q) -> Self
    where
        Q: IntoIterator<Item = TransactionReference>,
    {
        self.tx_queue = Some(queue_txs.into_iter().collect());
        self
    }
}

impl<T> MempoolState<T> {
    fn assert_eq_mempool_state(&self, mempool: &Mempool) {
        self.assert_eq_pool_state(mempool);
        self.assert_eq_queue_state(mempool);
    }

    fn assert_eq_pool_state(&self, mempool: &Mempool) {
        assert_eq!(self.tx_pool.as_ref().unwrap(), &mempool.tx_pool);
    }

    fn assert_eq_queue_state(&self, mempool: &Mempool) {
        assert_eq!(self.tx_queue.as_ref().unwrap(), &mempool.tx_queue);
    }
}
```

If it works, and it is clear how to use, use it instead, otherwise lets try to think of another solution that will print `None` when debugging these kinds of tests, but that doesn't incur boilerplate during the tests, and that can also scale to the remaining components we'll soon need here (like the so-called "staging area")
</blockquote></details>

Nice! What's the use of `PhantomData`?

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1uZFwX9iXNyiNIZZa9:-O1wLQ8e9ixiFu89KgR2:b8y351e) ([raw file](https://github.com/starkware-libs/mempool/blob/47f70b395ff9f0f0f8361775390da36419582139/crates/mempool/src/mempool_test.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nice! What's the use of `PhantomData`?
</blockquote></details>

Because we don't really use `FullState` and `PartialState`, they are just "markers" which are just some type artifact that allows the compiler to treat `MempoolState<FullState>` and `MempoolState<PartialState>` as separate types.

Without the phantomdata field, the compiler would have whined about there being an unused generic `T` in the definition of Mempool. 
It is also optimized for this specific purpose, and in particular is called a "zero sized type", because it has 0 size on the stack. In other words, when a mempool instance is initialized and put on the stack, only the pool/queue fields take up space, whereas the phantomdata field doesn't appear.

However, if you `dbg!(mempool_state)`, you will see MempoolState<Full> or MempoolState<Partial> (depending on which one you printed), because the compiler treats these as separate types

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/mempool/446#-O1uZFwX9iXNyiNIZZa9:-O1yqe-X-et-dwx_llcv:br2lbi3) ([raw file](https://github.com/starkware-libs/mempool/blob/47f70b395ff9f0f0f8361775390da36419582139/crates/mempool/src/mempool_test.rs#L44)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Because we don't really use `FullState` and `PartialState`, they are just "markers" which are just some type artifact that allows the compiler to treat `MempoolState<FullState>` and `MempoolState<PartialState>` as separate types.

Without the phantomdata field, the compiler would have whined about there being an unused generic `T` in the definition of Mempool. 
It is also optimized for this specific purpose, and in particular is called a "zero sized type", because it has 0 size on the stack. In other words, when a mempool instance is initialized and put on the stack, only the pool/queue fields take up space, whereas the phantomdata field doesn't appear.

However, if you `dbg!(mempool_state)`, you will see MempoolState<Full> or MempoolState<Partial> (depending on which one you printed), because the compiler treats these as separate types
</blockquote></details>

Very cool, thanks. Let's try to imp. this in a separate PR.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 351 at r6](https://reviewable.io/reviews/starkware-libs/mempool/446#-O2TOEai9nKM1wdpiuzM:-O2TOEai9nKM1wdpiuzN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4fe1235ef04aecbf99bd9851bc7932ffe12cb7e5/crates/mempool/src/mempool_test.rs#L351)):*
> ```XML
>     add_tx(&mut mempool, &input_small_tip_big_hash);
> 
>     // Assert: ensure that the transaction with the higher tip is sequenced first.
> ```





_Suggestion:_
```XML
prioritized higher
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
