### PR TITLE
ci: force no_unwrap in clippy

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Happened to notice this PR so sorry for barging in.
Note that these options are already configured [here](https://github.com/starkware-libs/blockifier/blob/06596a7ecfe1c3a2c186dc0cc95b72d5eb2f19ef/Cargo.toml#L58).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30#-:-NuwtTzq1FO3IheJtYoH:bl87oah)* status: 0 of 3 files reviewed, all discussions resolved

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`.clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwwjU5AlgfzOhZwUvq:-NuwwjU5AlgfzOhZwUvr:b-1zlo3s) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/.clippy.toml#L2)):*
> ```TOML
> allow-unwrap-in-tests = true
> enum-variant-size-threshold = 500
> ```

This looks like a roundabout way of disabling `clippy::enum_variant_names`?
I don't think that lint should be disabled, it looks solid.



_Code quote:_
```TOML
enum-variant-size-threshold = 500
```
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwuHbw0KhNT5ZZdQNY:-NuwuHbw0KhNT5ZZdQNZ:b-o3yhq0) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> cargo clippy "$@" --all-targets --all-features -- -D warnings -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused -D clippy::unwrap_used -A clippy::blocks_in_conditions
> ```

I suggest removing this, there are too many non-test cases where it does make sense to use unwrap --- like retrieving something from a hashmap that you just inserted into.
Grep `#[allow(clippy::unwrap_used)]` in papyrus to see proof of this.

Also I think papini or lior also said that unwrap is Okay occasionally, but just that PR maintainers need to be very selective about it, and only allow it when `expect` makes no sense.



_Code quote:_
```Shell
 -D clippy::unwrap_used
```
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwvG6X8CZkSpAMtWwX:-NuwvG6X8CZkSpAMtWwY:b-wi0f2c) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> cargo clippy "$@" --all-targets --all-features -- -D warnings -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused -D clippy::unwrap_used -A clippy::blocks_in_conditions
> ```

I think [papyrus only added this due to a bug](https://github.com/starkware-libs/papyrus/blob/01a2252ff8a8fc86f65d8b75fd9ff3ba737a5ca0/.github/workflows/ci.yml#L178) in `tracing`, which we don't currently use, so let's remove this plz.
(We do plan on using `tracing` _at some point_, but by then the bug fix will probably be released according to the github issue.)



_Code quote:_
```Shell
 -A clippy::blocks_in_conditions
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`.clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwwjU5AlgfzOhZwUvq:-Nux3j5g0m495_NeaM2z:b2rlq64) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/.clippy.toml#L2)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This looks like a roundabout way of disabling `clippy::enum_variant_names`?
I don't think that lint should be disabled, it looks solid.
</blockquote></details>

That's the setting in the papyrus repo, I really don't mind about it at all. I just prefer to be consistent.
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwuHbw0KhNT5ZZdQNY:-Nux40ff53O03gaI4LRQ:b-sevvy8) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I suggest removing this, there are too many non-test cases where it does make sense to use unwrap --- like retrieving something from a hashmap that you just inserted into.
Grep `#[allow(clippy::unwrap_used)]` in papyrus to see proof of this.

Also I think papini or lior also said that unwrap is Okay occasionally, but just that PR maintainers need to be very selective about it, and only allow it when `expect` makes no sense.
</blockquote></details>

1. I moved the definitions to the `Cargo.toml` file.
2. I prefer to be consistent with papyrus.
3. Having this enforcement on and turning it off is much simpler than having it off and turning it on later.
4. Having default strict settings and explicitly relaxing them is preferred imo than the other way around.
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwvG6X8CZkSpAMtWwX:-Nux5S4ZEEwH2IXimE1P:b-hn1ppj) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think [papyrus only added this due to a bug](https://github.com/starkware-libs/papyrus/blob/01a2252ff8a8fc86f65d8b75fd9ff3ba737a5ca0/.github/workflows/ci.yml#L178) in `tracing`, which we don't currently use, so let's remove this plz.
(We do plan on using `tracing` _at some point_, but by then the bug fix will probably be released according to the github issue.)
</blockquote></details>

Right, removed.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`.clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwwjU5AlgfzOhZwUvq:-Nux62LhEUc44yvSlFi0:b-satjke) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/.clippy.toml#L2)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

That's the setting in the papyrus repo, I really don't mind about it at all. I just prefer to be consistent.
</blockquote></details>

Also, these lints address different aspects. Chat-gpt'ed:

  
The `clippy::enum_variant_names` lint is a lint provided by Clippy, the Rust linter, which checks if the names of the enum variants follow a consistent naming convention.

  
The `clippy::enum-variant-size-threshold` lint is provided by Clippy, the Rust linter. It checks whether the size of an enum variant (in terms of the number of fields it contains) exceeds a specified threshold. This lint can help you identify enum variants that are becoming overly large, which may indicate a design issue or suggest that you might want to refactor your code for clarity or efficiency.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`.clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwwjU5AlgfzOhZwUvq:-NuxOR1e1yHMC4AP_NoH:b-g2z0ca) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/.clippy.toml#L2)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>I just prefer to be consistent

There is also consistency with SN API and Blockifier to consider.

>Chat-gpt'ed:

The [official docs](https://doc.rust-lang.org/clippy/lint_configuration.html#enum-variant-name-threshold) are better here. 
Specicially, note that `enum-variant-size-threshold` only affects `enum-variant-names` lint.
So setting the former to 500 effectively means disabling the latter for all sensibly sized enums.
If you want to disable enum_variant_names, you can turn it off explicitly, but that also needs explaining, since the lint looks like it bans an relatively unreadable use of unpacking.
</blockquote></details>

Ack, removed.
___
*[`crates/gateway/src/gateway.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuxBck7Bvg2Tyy9ufXx:-NuxOaHe8qlrB1JD4dnn:bvst6cy) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/crates/gateway/src/gateway.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this `expect` doesn't add any new information, `unwrap` is more appropriate.
Note: the library authors themselves [use unwrap](https://docs.rs/axum-server/latest/axum_server/fn.bind.html) for this usage, both in this link and throughout their entire codebase.
</blockquote></details>

I prefer not having `unwrap`s; the use (or misuse) of linters in this package are orhtogonal to that.
I updated the error message according to the referenced styling guide.
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwuHbw0KhNT5ZZdQNY:-NuxPga5B68SgpyYFa8u:b9yf8w9) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

1. tnx

2. What about Starknet API and blockifier, which don't have this setting? 

3/4. If we follow that logic, we should enable all lints.
However, considering that the only project using this lint (papyrus) has overridden it 11 times in production code suggests it's too strict.
Plus, it promotes unnecessary `expect` usage, which should [document assumptions](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style), rather than boilerplate strings.
</blockquote></details>

My main concern is that we'll move around code across the different code bases, each with its own linter, and will face incompatibility issues. Therefore, I suggest we stick to the strictest version each of the current projects use, which seems to be the papyrus version, before we standartize this. Prehaps we can relax the linter in papyrus, I'm not arguing against that.

I'll set a meeting. In the mean time, I humbly ask we stick to the stricter version.

RE other linters: If there are other usesful ones please lmk.

RE papyrus usage and overrides: It's a huge code base, I see this as *only* 11 times. 

Generaly, I'm strongly in favor of `expect` (not sure why you refer to that as unnecessary) -- following the commenting style you mentioned in a different message.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/30)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuxBck7Bvg2Tyy9ufXx:-NuyFgjJ6BHz84SJM42D:b-7ukeha) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/crates/gateway/src/gateway.rs#L35)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I prefer not having `unwrap`s; the use (or misuse) of linters in this package are orhtogonal to that.
I updated the error message according to the referenced styling guide.
</blockquote></details>

"Server should run forever" is not the assumption, it is the requirement.

If you don't want to follow the docs, then you'll have to go into `serve` and see why this invocation will never fail.
This is probably not the way to go, as this will soon be replaced by a central error handling enum.
If you insist on banning unwrap, you'll have to add clippy ignore here.
___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/30#-NuwuHbw0KhNT5ZZdQNY:-NuyDHgx08lhLyRPa_OG:bjc8o7g) ([raw file](https://github.com/starkware-libs/mempool/blob/64005f2d6b82e19226d419c4d573b85f716e02b4/scripts/clippy.sh#L3)):*
> My main concern is that we'll move around code across the different code bases, each with its own linter, and will face incompatibility issues. Therefore, I suggest we stick to the strictest version each of the current projects use, which seems to be the papyrus version, before we standartize this. Prehaps we can relax the linter in papyrus, I'm not arguing against that.

Do you have a use case in mind in which we move code from the mempool to papyrus? 

>RE other linters: If there are other usesful ones please lmk.

There's a disconnect. I claim that by your points 3 and 4, all linters should be on by default, because adding them later will be hard.
The reason why some of them are of is because they were deemed pedantic by the writers, or are too obtrusive.
For example, if you ban unwrap, then even if you're playing around locally while developing, you won't be able to compile any code the unwraps; you'll have to add a bunch of `.expect("ASDF")` things, just to get things to compile in order to check something.

>RE papyrus usage and overrides: It's a huge code base, I see this as _only_ 11 times.

There is also incorrect usage of `expect`, which we cannot grep for easily.

>Generaly, I'm strongly in favor of `expect` (not sure why you refer to that as unnecessary) -- following the commenting style you mentioned in a different message.

I didn't say that all `expect` is unnecessary, I said that banning unwraps promotes unnecessary _usage_ of expects, which is what that link hinted at: if you don't have anything meaningful to say in an expect, you should not use expect. This is a very rare occurrence, therefore valid unwraps are relatively rare.

**Comment by Itay-Tsabary-Starkware** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
