### PR TITLE
chore: clean component server client tests

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 13 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-18XlD6ZMr4Y5r0V2b:-O-18XlD6ZMr4Y5r0V2c:bmada7j) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L54)):*
> ```XML
>         };
> 
>         Ok(response.get_ref().value)
> ```

IIUC `get_ref` can be `into_inner`.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 14 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1B4ma0hgVlqYUITu0:-O-1B4ma0hgVlqYUITu1:b1zgfhf) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L41)):*
> ```XML
>         Self { dst: construct_url(ip_address, port) }
>     }
> }
> ```

As a first step, please define the client once, and then define types for A and B clients. The `construct_url` function can be defined in the scope of ithe client implementation.



_Code quote:_
```XML
struct ComponentAClientRpc {
    dst: String,
}

impl ComponentAClientRpc {
    fn new(ip_address: IpAddr, port: u16) -> Self {
        Self { dst: construct_url(ip_address, port) }
    }
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 14 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1B4ma0hgVlqYUITu0:-O-1BOwx6Otl7bCeWYdZ:b-hh5rem) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

As a first step, please define the client once, and then define types for A and B clients. The `construct_url` function can be defined in the scope of ithe client implementation.
</blockquote></details>

This will allow to delete the duplicated A and B clients

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 14 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1B4ma0hgVlqYUITu0:-O-1C4Mg5hRVH4pHQ4P4:b-i1mx14) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This will allow to delete the duplicated A and B clients
</blockquote></details>

Also, move this definition to the `src` dir in a relevant module.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 15 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1CEc_AXrVvJYwQwDn:-O-1CEc_AXrVvJYwQwDo:b54ogv4) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L124)):*
> ```XML
> }
> 
> impl ComponentBServerRpc {
> ```

These can be generic in the component and the server.
See for example the channels definition:
```
impl<Component, Request, Response> ComponentServer<Component, Request, Response>
```

Also make sure to move these to a relevant module under `src`



_Code quote:_
```XML
struct ComponentBServerRpc {
    b: Option<ComponentB>,
    address: SocketAddr,
}

impl ComponentBServerRpc {
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 10 files reviewed, 15 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1CEc_AXrVvJYwQwDn:-O-1C_-N4ruZ448BBzDx:bq02s6b) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L124)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These can be generic in the component and the server.
See for example the channels definition:
```
impl<Component, Request, Response> ComponentServer<Component, Request, Response>
```

Also make sure to move these to a relevant module under `src`
</blockquote></details>

And, wrap with a suitable type for A and B :-)

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 11 files reviewed, 15 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14JsoAALpzqJZXhzO:-O-17tms47hQmoG7DuFh:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/src/component_client.rs#L39)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to "Failed to connect to the server".
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14dsZBPHVQC_JaqFG:-O-17uA98gMCgsxuLMXD:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/src/component_client.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to "Failed to get a response from the server".
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1B4ma0hgVlqYUITu0:-O-1GEkTCv6CzENSuXhu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Also, move this definition to the `src` dir in a relevant module.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-13oKC8KZTBFxyGqTt:-O-18s9V7tvbz2HTiPcF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please stick to the naming convention defined in the mempool: the trait name is `XClient` (X being the component name, in our case, A).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14xtpCymNUNBmK5KK:-O-1DekkBH3IYA40YOmu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Tonic `Result`'s captures information that is foregone by this; please propagate the error.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-155JK1rzMs_Cyk5iS:-O-1DfDc30eDW7P5Z0Jv:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-18XlD6ZMr4Y5r0V2b:-O-19PCU9-isjKN_K-Tf:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC `get_ref` can be `into_inner`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1CEc_AXrVvJYwQwDn:-O-1UvPn8uC1lHGzV6UB:b-k8asj2) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L124)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

And, wrap with a suitable type for A and B :-)
</blockquote></details>

My slack message is addressing this
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-15IwK2IwKxc-7Mrzn:-O-1A-nK0CKqhq7wLhQM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L140)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert and use `expect`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_test.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-1640E9y8-s-DHOtV3:-O-1GQ9RBl_lvrkRxXu8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_test.rs#L82)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16Lh9E2PaAu8QY_Pf:-O-1A2ph2oSUpLN-X1WH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L10)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Rename according to the convention (mentioned in a different comment as well)
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16I6LDtm2NnVr1XjY:-O-1WqRf7p4z4WoeSUc6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L11)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please wrap in a type.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16QZQ2xaRXrfz9JD3:-O-1VStfDOSvYsZ_3e0o:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L17)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto on both changes.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16X4u-i38M7gtaK8d:-O-1GWrQBbWEtMi2nzXi:b-d7bhn0) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L20)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Change to arc (in a different pr), for B as well. See how the gateway uses the mempool client for inspiration.
</blockquote></details>

will do
___
*[`crates/mempool_infra/src/component_definitions.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14iagANPtQUST6cKW:-O-17w-vD3mAJR_9hPMN:bvt6kjm) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/src/component_definitions.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. This should be in a different pr.
2. Why do you prefer this name?
</blockquote></details>

Ok. I think this name is more concise and is shorter

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 13 files reviewed, 10 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-13oKC8KZTBFxyGqTt:-O-ZrJF77OrzCVF8RpVW:b-u8klh1) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L44)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The trait name should be `AClient`.
You can define a type alias for ` ComponentClientRpc<ComponentA>`, e.g., `ARpcClientImpl`.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14xtpCymNUNBmK5KK:-O-ZsC4C27IaCFOEW22x:b8eriu5) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L47)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IIUC this can be simplified using the `map_err` syntax, along with a `?`
There's an example in the `gateway.rs`.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-155JK1rzMs_Cyk5iS:-O-ZsCvwBeIhhJ4tXXID:b-siokhv) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L51)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ditto ^ 
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-ZsQtxBxQkAWuYQgbE:-O-ZsQtxBxQkAWuYQgbF:b-3axs2j) ([raw file](https://github.com/starkware-libs/mempool/blob/acf2df0b9a3abb8e61f7afc7168670c1dec26b1e/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L51)):*
> ```XML
>             Ok(client) => client,
>             Err(e) => return Err(ClientError::ConnectionFailure(e)),
>         };
> ```

`map_err` + `?`



_Code quote:_
```XML
        let mut client = match RemoteBClient::connect(self.dst.clone()).await {
            Ok(client) => client,
            Err(e) => return Err(ClientError::ConnectionFailure(e)),
        };
```
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-ZsUDA6o8NiUbyiTpf:-O-ZsUDA6o8NiUbyiTpg:b-3axs2j) ([raw file](https://github.com/starkware-libs/mempool/blob/acf2df0b9a3abb8e61f7afc7168670c1dec26b1e/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L54)):*
> ```XML
> 
>         let response = match client.remote_b_get_value(BGetValueMessage {}).await {
>             Ok(response) => response,
> ```

`map_err` + `?`
___
*[`crates/mempool_infra/tests/common/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16Lh9E2PaAu8QY_Pf:-O-ZtCr93TDQm8theN0u:b-1omkro) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L10)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unblocking here, please change accoring to the other comment.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16I6LDtm2NnVr1XjY:-O-ZsqE28yml5kinjGQJ:b-6qeewt) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L11)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great. Also please type alias `AClientResult`. Ditto for B.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 13 files reviewed, 11 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server_rpc.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-Zv9ioA7pxK2U1DfKh:-O-Zv9ioA7pxK2U1DfKi:b-v7m4ro) ([raw file](https://github.com/starkware-libs/mempool/blob/acf2df0b9a3abb8e61f7afc7168670c1dec26b1e/crates/mempool_infra/src/component_server_rpc.rs#L23)):*
> ```XML
>         self.component.take().unwrap().start_server(self.address).await;
>     }
> }
> ```

Let's break this down:

1. There can be a `start_component` fn in a designated trait for components to impl, that enable them to run whatever functionality they want on start up. I don't think this is relevant for our case.

2. There should be a `start_server` fn in a designated trait for servers to implement, in which they start their operation. This function can also call the inner component's `start_component` fn. In the rpc use case, the impl can be to start listening to messages (when the service is created at the server constructor).

3. The service and the component should be separated -- a component is not a service. That is, a component should not implement service/server functions.

4. The service/server should find a way to invoke the component. Check this trait from our code base for inspiration


```
#[async_trait]
pub trait ComponentRequestHandler<Request, Response> {
    async fn handle_request(&mut self, request: Request) -> Response;
}
```



_Code quote:_
```XML
#[async_trait]
pub trait ServerStart {
    async fn start_server(self, address: SocketAddr);
}

pub struct ComponentServerRpc<Component> {
    component: Option<Component>,
    address: SocketAddr,
}

impl<Component: ServerStart> ComponentServerRpc<Component> {
    pub fn new(component: Component, ip_address: IpAddr, port: u16) -> Self {
        Self { component: Some(component), address: SocketAddr::new(ip_address, port) }
    }

    pub async fn start(&mut self) {
        self.component.take().unwrap().start_server(self.address).await;
    }
}
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/233)* status: 2 of 13 files reviewed, 11 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-13oKC8KZTBFxyGqTt:-O-_DCFw0aeA5xvrYmH1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The trait name should be `AClient`.
You can define a type alias for ` ComponentClientRpc<ComponentA>`, e.g., `ARpcClientImpl`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-14xtpCymNUNBmK5KK:-O-ZzLGL0Fk1zJU5opuQ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC this can be simplified using the `map_err` syntax, along with a `?`
There's an example in the `gateway.rs`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-155JK1rzMs_Cyk5iS:-O-ZzMY57BnFSpFLTxNH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto ^
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-ZsQtxBxQkAWuYQgbE:-O-ZzQ-M-jCfd6LNroRT:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/acf2df0b9a3abb8e61f7afc7168670c1dec26b1e/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`map_err` + `?`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-ZsUDA6o8NiUbyiTpf:-O-ZzQFh98hDKBuBkI-4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/acf2df0b9a3abb8e61f7afc7168670c1dec26b1e/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`map_err` + `?`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/mempool/233#-O-16I6LDtm2NnVr1XjY:-O-_EDix9invO-TkkVUf:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4402ee0e1c885e0e957acdf863de856f0ae046f0/crates/mempool_infra/tests/common/mod.rs#L11)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Great. Also please type alias `AClientResult`. Ditto for B.
</blockquote></details>

Done.

**Pull request closed without merging**
