### PR TITLE
chore: split communication-related functionality from mempool and mem…

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
…pool-types modules

commit-id:8c4b0394

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/224#-NzwdakA1Tqe7BeHCcOX:-NzwdakA1Tqe7BeHCcOY:b-afjrej) ([raw file](https://github.com/starkware-libs/mempool/blob/3d2cf33160e782788ad31d9d76ed5cc8b187a790/crates/mempool/src/lib.rs#L2)):*
> ```XML
> pub mod mempool;
> pub mod mempool_communication;
> ```

Similar to the other comment, maybe just `communication.rs`?



_Code quote:_
```XML
mempool_communication
```
___
*[`crates/mempool_types/src/lib.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/224#-NzwcC-c3OidTuVGseFl:-NzwcC-c3OidTuVGseFm:b-q5iyr8) ([raw file](https://github.com/starkware-libs/mempool/blob/3d2cf33160e782788ad31d9d76ed5cc8b187a790/crates/mempool_types/src/lib.rs#L3)):*
> ```XML
> pub mod errors;
> pub mod mempool_communication_types;
> pub mod mempool_types;
> ```

Since the crate name already specifies `mempool_types` I think it's enough to name the files `communication.rs` and `common.rs`(or any other name you see fit).



_Code quote:_
```XML
pub mod mempool_communication_types;
pub mod mempool_types;
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224#-:-O-0vcrzA2zysqSgxYvq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224)* status: all files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V3w2bAb3H7Rfoqg9U:-O-V3w2bAb3H7Rfoqg9V:bt7kfkk) (no related file):*
Pasting here the file structure convention we used in Blockifier, which I think you complied to (feel free to make sure).
One thing I _did_ notice is aliases should be moved up - note you don't have to define them after the definition of the objects they're aliasing. Also, please make sure that aliases that are only used inside the file they're defined in, are private. 

**File Structure**  
Organize each file in the following order  
1. All public aliases.
2. All public Enums.
3. All Public Structs, with public fields appearing before private ones, where after each struct there are:
- a single non-trait `impl` block (if it is nonempty), ordered by: public associated functions, public methods, private associated functions, private methods.
-   trait `impl`s (if it has any)
-   <The same as the above, but for private Enums and Structs>

Each of the above items is internally sorted by importance
That is, **think about the likely reader** of the file and move up (inside each category) items you think they are more likely to be looking for when viewing the file.

___
___
*[`crates/mempool_types/src/communication.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V39qY3SmGbIjhhwKw:-O-V39qZ7BR2m-tjUIju:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/1f37dd97102e08a850bf8e16b27b67095caa4132/crates/mempool_types/src/communication.rs#L16)):*
> ```XML
>     MempoolError(#[from] MempoolError),
>     #[error(transparent)]
>     ClientError(#[from] ClientError),
> ```





_Suggestion:_
```XML
    #[error(transparent)]
    ClientError(#[from] ClientError),
    #[error(transparent)]
    MempoolError(#[from] MempoolError),
```
___
*[`crates/mempool_types/src/communication.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V5as69vnvbaBpQHQQ:-O-V5as69vnvbaBpQHQR:b-g84kzq) ([raw file](https://github.com/starkware-libs/mempool/blob/1f37dd97102e08a850bf8e16b27b67095caa4132/crates/mempool_types/src/communication.rs#L48)):*
> ```XML
>     async fn add_tx(&self, mempool_input: MempoolInput) -> MempoolClientResult<()> {
>         let request = MempoolRequest::AddTransaction(mempool_input);
>         let res = self.send(request).await;
> ```

I think this variable is redundant, x2.
If you choose to keep it, please give it a name that better represents the flow, such as: `mempool_response`.



_Code quote:_
```XML
res
```
___
*[`crates/mempool_types/src/communication.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V6FyP67JGPY2nBnsF:-O-V6FyP67JGPY2nBnsG:b32wzj) ([raw file](https://github.com/starkware-libs/mempool/blob/1f37dd97102e08a850bf8e16b27b67095caa4132/crates/mempool_types/src/communication.rs#L60)):*
> ```XML
>         let res = self.send(request).await;
>         match res {
>             MempoolResponse::GetTransactions(Ok(res)) => Ok(res),
> ```

x2



_Suggestion:_
```XML
Ok(txs)
```
___
*[`crates/mempool_types/src/communication.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V6H_N2RfKm2ccUwS4:-O-V6H_N2RfKm2ccUwS5:b32wzj) ([raw file](https://github.com/starkware-libs/mempool/blob/1f37dd97102e08a850bf8e16b27b67095caa4132/crates/mempool_types/src/communication.rs#L61)):*
> ```XML
>         match res {
>             MempoolResponse::GetTransactions(Ok(res)) => Ok(res),
>             MempoolResponse::GetTransactions(Err(res)) => {
> ```

x2



_Suggestion:_
```XML
Err(error)
```
___
*[`crates/mempool_types/src/communication.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/mempool/224#-O-V6JUO9BYA3hUjgXq3:-O-V6JUO9BYA3hUjgXq4:b32wzj) ([raw file](https://github.com/starkware-libs/mempool/blob/1f37dd97102e08a850bf8e16b27b67095caa4132/crates/mempool_types/src/communication.rs#L62)):*
> ```XML
>             MempoolResponse::GetTransactions(Ok(res)) => Ok(res),
>             MempoolResponse::GetTransactions(Err(res)) => {
>                 Err(MempoolClientError::MempoolError(res))
> ```

x2



_Suggestion:_
```XML
MempoolError(error)
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224)* status: all files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224)* status: all files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/224)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
