### PR TITLE
test: add deploy_account to integration test

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0bupl4Bd_lsD9Lui-U:-O0bupl4Bd_lsD9Lui-V:bhcodit) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L60)):*
> ```XML
>             ContractAddress::default(),
>         )
>         .unwrap()
> ```

What do you think about wrapping this into a function as a test util?



_Suggestion:_
```XML
        let deploy_account_tx = assert_matches!(
            deploy_tx,
            RPCTransaction::DeployAccount(deploy_account_tx) => deploy_account_tx
        );
        return deployed_account_contract_address(deploy_account_tx);
        
        
        fn deployed_account_contract_address(deploy_account_tx: RPCDeployAccountTransaction) -> ContractAddress {
            let RPCDeployAccountTransaction::V3(tx) = deploy_account_tx;
            calculate_contract_address(
            tx.contract_address_salt,
            tx.class_hash,
            &tx.constructor_calldata,
            ContractAddress::default(),
        )
        .unwrap()
            }
```
___
*[`crates/tests-integration/src/state_reader.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0buC6b0l15_qI2g6jf:-O0buC6b0l15_qI2g6jg:b7weoa8) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L62)):*
> ```XML
>         .unwrap()
>     };
> }
> ```

Do we have other examples for this? Is there something I can look for a reference? 
(Nice!)



_Code quote:_
```XML
lazy_static! {
    static ref DEPLOY_ACCCOUNT_TX_CONTRACT_ADDRESS: ContractAddress = {
        let deploy_tx = deploy_account_tx();
        let tx = assert_matches!(
            deploy_tx,
            RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(tx)) => tx
        );
        calculate_contract_address(
            tx.contract_address_salt,
            tx.class_hash,
            &tx.constructor_calldata,
            ContractAddress::default(),
        )
        .unwrap()
    };
}
```
___
*[`crates/tests-integration/src/state_reader.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0c-coGEdT-jCk652ev:-O0c-coGEdT-jCk652ew:b-8749et) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L295)):*
> ```XML
>             .extend(key_value.clone());
>     }
> }
> ```

IIUC.



_Suggestion:_
```XML
fn fund_feature_account_contract(
    storage_diffs: &mut IndexMap<ContractAddress, IndexMap<StorageKey, StarkFelt>>,
    contract: &FeatureContract,
    instance: u16,
    initial_balances: u128,
    chain_info: &ChainInfo,
) {
    match contract {
        FeatureContract::AccountWithLongValidate(_)
        | FeatureContract::AccountWithoutValidations(_)
        | FeatureContract::FaultyAccount(_) => {
            fund_account(
                storage_diffs,
                &contract.get_instance_address(instance),
                initial_balances,
                chain_info,
            );
        }
        _ => (),
    }
}

fn fund_account(
    storage_diffs: &mut IndexMap<ContractAddress, IndexMap<StorageKey, StarkFelt>>,
    account_address: &ContractAddress,
    initial_balances: u128,
    chain_info: &ChainInfo,
) {
    let key_value = indexmap! {
        get_fee_token_var_address(*account_address) => stark_felt!(initial_balances),
    };
    for fee_type in FeeType::iter() {
        storage_diffs
            .entry(chain_info.fee_token_address(&fee_type))
            .or_default()
            .extend(key_value.clone());
    }
}
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0cL9Il5bSAbgdLMJO9:-O0cL9Im3r_aj19XKha8:bqasp3c) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L173)):*
> ```XML
>     let erc20 = FeatureContract::ERC20;
>     let mut cairo0_contract_classes: Vec<(ClassHash, DeprecatedContractClass)> =
>         vec![(erc20.get_class_hash(), serde_json::from_str(&erc20.get_raw_class()).unwrap())];
> ```

Maybe pass the erc20 contract as an input as part of `contract_instances`?



_Code quote:_
```XML
    let erc20 = FeatureContract::ERC20;
    let mut cairo0_contract_classes: Vec<(ClassHash, DeprecatedContractClass)> =
        vec![(erc20.get_class_hash(), serde_json::from_str(&erc20.get_raw_class()).unwrap())];
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/tests-integration/src/state_reader.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0bupl4Bd_lsD9Lui-U:-O0cn8t_CumPus-vd9hh:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L60)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What do you think about wrapping this into a function as a test util?
</blockquote></details>

done.
___
*[`crates/tests-integration/src/state_reader.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0buC6b0l15_qI2g6jf:-O0cPgUd79Vz_y28V5SR:b-laz6nx) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we have other examples for this? Is there something I can look for a reference? 
(Nice!)
</blockquote></details>

Papyrus is using it:
https://github.com/starkware-libs/papyrus/blob/c4d829c978d45a6d49be50da76ebde68e019ccd5/crates/papyrus_rpc/src/v0_7/transaction_test.rs#L35
___
*[`crates/tests-integration/src/state_reader.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0cL9Il5bSAbgdLMJO9:-O0cpnbe42fckJexMtSo:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L173)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe pass the erc20 contract as an input as part of `contract_instances`?
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/state_reader.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0c-coGEdT-jCk652ev:-O0cq9Ds4T4-gdapa-LK:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/94e90141c03bace3b142f64beafc4214422bfb38/crates/tests-integration/src/state_reader.rs#L295)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

IIUC.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0dRaei-HNLqWuV27bR:-O0dRaei-HNLqWuV27bS:b886pb2) ([raw file](https://github.com/starkware-libs/mempool/blob/8b4d2926ed1fac0277efb637841e2867f99e826f/crates/gateway/Cargo.toml#L16)):*
> ```TOML
> [dependencies]
> axum.workspace = true
> assert_matches.workspace = true
> ```

I think there is a way to define the `starknet_api_test_utils.rs` for tests? and then keep this as dev-dependency. 

Take a look at `#[cfg(test)]` in `lib.rs`.



_Code quote:_
```TOML
assert_matches.workspace = true
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0dRaei-HNLqWuV27bR:-O0gnC2k5tZueuGRSJXA:b6keesr) ([raw file](https://github.com/starkware-libs/mempool/blob/8b4d2926ed1fac0277efb637841e2867f99e826f/crates/gateway/Cargo.toml#L16)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think there is a way to define the `starknet_api_test_utils.rs` for tests? and then keep this as dev-dependency. 

Take a look at `#[cfg(test)]` in `lib.rs`.
</blockquote></details>

yes, I was thinking the same thing exactly and was planning to fix in a the next PR. There is one function in this file that is being used by the gateway so I couldn't make it a test file instantly, will open a separate PR to move the function and then solve this.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/302#-O0dRaei-HNLqWuV27bR:-O0gsutV8sFrwuaKC3dv:b-bevcfw) ([raw file](https://github.com/starkware-libs/mempool/blob/8b4d2926ed1fac0277efb637841e2867f99e826f/crates/gateway/Cargo.toml#L16)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yes, I was thinking the same thing exactly and was planning to fix in a the next PR. There is one function in this file that is being used by the gateway so I couldn't make it a test file instantly, will open a separate PR to move the function and then solve this.
</blockquote></details>

here is the PR: https://reviewable.io/reviews/starkware-libs/mempool/329

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/302#-:-O0he82X88_lgNJcWWyl:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

**Pull request merged**
