### PR TITLE
test: organize tests for maintainability

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/61)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/61)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/mempool/61#-Nvzm7eH2-Xee9ruidmQ:-Nvzm7eH2-Xee9ruidmR:b-j59itt) ([raw file](https://github.com/starkware-libs/mempool/blob/f7ea974e97d1319e299650d1e793b25c6fb71014/crates/gateway/src/stateless_transaction_validator_test.rs#L91)):*
> ```XML
>         ..DEFAULT_VALIDATOR_CONFIG_FOR_TESTING
>     },
>         ResourceBoundsMapping::default(),
> ```

Indentation? 
Also in the rest of the tests...

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/mempool/61#-Nvzm7eH2-Xee9ruidmQ:-NvzppZkBO1lvf-yBISI:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f7ea974e97d1319e299650d1e793b25c6fb71014/crates/gateway/src/stateless_transaction_validator_test.rs#L91)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Indentation? 
Also in the rest of the tests...
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/61#-:-Nw-9O2wC7BMQo4T5BqT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/61)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
