### PR TITLE
fix: fix tx generator instance ids

### PR DESCRIPTION
**Pull request by giladchase**
The tx generator was identifying the contract instance id with the number of _total_ accounts in the system, which was incorrect, since instance_id in a `FeatureContract` is the the index of the contract without the sequence of all contracts _of the same type_ created in the system.

This fix retains the original meaning of `AccountId` for better UX, so they can refer to accounts by their index given in the constructor, but adds an internal mapping between this id and the "correct" instance_id that FeatureContract expects.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1XHSZB-iTZyE97jYK-:-O1XHSZB-iTZyE97jYK0:bv5k3x5) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
> ```XML
>             account_contracts.insert(account_id, contract);
> 
>             let n_current_contract = variant_counters.entry(contract).or_insert(0);
> ```

Will pass CI once [this Blockifier PR](https://reviewable.io/reviews/starkware-libs/blockifier/2077) is merged.



_Code quote:_
```XML
            let n_current_contract = variant_counters.entry(contract).or_insert(0);
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jvHVmCTuRBz0CV-hM):*
iiuc, you mean "of different types" ?



_Code quote:_
```
_of the same type_
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx8F09R0ikCOmiTJN:-O1jx8F09R0ikCOmiTJO:b-rlpei5) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L154)):*
> ```XML
>     // the initialization array.
>     // Invariant: should have the same keys as account_contracts
>     // TODO: consider merging the maps, but that might over-complicate things.
> ```

I'm in favor of merging



_Code quote:_
```XML
consider merging the maps
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx1y21CGptZRmjSwY:-O1jx1y34nzB7PyIq6W_:b10fuac) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L187)):*
> ```XML
> 
>     fn contract_instance_id(&self, account_id: AccountId) -> ContractInstanceId {
>         *self.account_variant_indices.get(&account_id).unwrap_or(&0)
> ```

I think it's a bug if the key doesn't exist in the hashmap



_Code quote:_
```XML
*self.account_variant_indices.get(&account_id).unwrap_or(&0)
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jyJIA9i4BkK_KVg3v:-O1jyJIA9i4BkK_KVg3w:b-x76xok) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
> ```XML
> pub struct AccountTransactionGenerator<'a> {
>     account_id: AccountId,
>     contract_instance_id: ContractInstanceId,
> ```

it's a duplicate of the info inside the generator. Why not take it from there?

Why not store the AccountTransactionGenerator object as part of the HashMap of accounts inside MultiAccountTransactionGenerator? it contains the same info : account_id, contract_instance_is and the required FeatureContract. 

would be even nicer if the nonce was a part of it, but more complicated since it's a part of the blockifier infrastructure.



_Code quote:_
```XML
contract_instance_id: ContractInstanceId,
```

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1g8VOE3cwKlqSySKnV:-O1g8VOE3cwKlqSySKnW:b5bf0b0) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L125)):*
> ```XML
> // into the module alongside MultiAcconutTransactionGenerator.
> type AccountId = usize;
> type ContractInstanceId = u16;
> ```

Not sure I understand the meaning of this number from its name alone. What contracts does it enumerate exactly?



_Code quote:_
```XML
type ContractInstanceId = u16;
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1g8oye0_NxN2OLhS7n:-O1g8oyf7cD9js0Hb56H:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L147)):*
> ```XML
> // [blockifier::transaction::test_utils::FaultyAccountTxCreatorArgs] can be made to use this.
> pub struct MultiAccountTransactionGenerator {
>     // Invariant: coupled with nonce_manager.
> ```





_Suggestion:_
```XML
the nonce manager.
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1g8rJh2Wyb-NJsZ95P:-O1g8rJiDIDmU9O3jHCg:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L153)):*
> ```XML
>     // Maps account IDs to their ordinal position within their contract type group in
>     // the initialization array.
>     // Invariant: should have the same keys as account_contracts
> ```





_Suggestion:_
```XML
account contracts mapping.
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1k79SY1hdaMIgmOiOy:-O1k79SY1hdaMIgmOiOz:b-xt8ixl) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L166)):*
> ```XML
>     }
> 
>     pub fn new_for_account_contracts(accounts: impl IntoIterator<Item = FeatureContract>) -> Self {
> ```

Are those not necessarily only account contracts?
Not sure what are "the variants" you're referring to.



_Code quote:_
```XML
accounts: impl IntoIterator<Item = FeatureContract>
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jvHVmCTuRBz0CV-hM):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

iiuc, you mean "of different types" ?
</blockquote></details>

Nope but it was confusing because i wrote "without" when I meant "within" :sweat_smile: 
Rewrote it.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1g8VOE3cwKlqSySKnV:-O1kEIRy3wLNrbGg1VAJ:bpt9e5d) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L125)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand the meaning of this number from its name alone. What contracts does it enumerate exactly?
</blockquote></details>

It's an internal concept of FeatureContract, explaining offline.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx8F09R0ikCOmiTJN:-O1piOQq0ZPLgqLG4LHt:b-reg6p6) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L154)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I'm in favor of merging
</blockquote></details>

Will be merged as a result of the resolution of: https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jyJIA9i4BkK_KVg3v
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1k79SY1hdaMIgmOiOy:-O1p5BcG6ulbMqJRMyBf:bgr9g5g) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are those not necessarily only account contracts?
Not sure what are "the variants" you're referring to.
</blockquote></details>

They are necessary account contracts, but `FeatureContract` can't differentiate between the two unfortunately.

enum variants of the FeatureContract enum, which correspond to account types here.

Renamed.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx1y21CGptZRmjSwY:-O1p8ov0DGzmfiXoBFWZ:b-ecwbqq) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L187)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it's a bug if the key doesn't exist in the hashmap
</blockquote></details>

Right, tnx

I ended up panicking, even though it is a user error technically, but since this is a test util it's probably overkill to return an error?

Also killed this method completely, it has only one use inside a constructor, which was a bit awkward anyway.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jyJIA9i4BkK_KVg3v:-O1piJ5ZEiYeKiMxtyS5:b-y5smaw) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it's a duplicate of the info inside the generator. Why not take it from there?

Why not store the AccountTransactionGenerator object as part of the HashMap of accounts inside MultiAccountTransactionGenerator? it contains the same info : account_id, contract_instance_is and the required FeatureContract. 

would be even nicer if the nonce was a part of it, but more complicated since it's a part of the blockifier infrastructure.
</blockquote></details>

Good idea, but this is too many changes at this point so I'm splitting this PR further and extracting some substeps into: [1](https://github.com/starkware-libs/mempool/pull/476) then [2](https://github.com/starkware-libs/mempool/pull/477)

Once those are merged I'll rebase here and continue.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jvHVmCTuRBz0CV-hM):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nope but it was confusing because i wrote "without" when I meant "within" :sweat_smile: 
Rewrote it.
</blockquote></details>

oh wait i can't push yet, i'm waiting for previous PRs to be merged, will ping here once I actually make the change
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1k79SY1hdaMIgmOiOy:-O1q25upDwzVz-W653fL:b-qrt35e) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L166)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

They are necessary account contracts, but `FeatureContract` can't differentiate between the two unfortunately.

enum variants of the FeatureContract enum, which correspond to account types here.

Renamed.
</blockquote></details>

haven't pushed yet, sorry ,waiting on previous pr to merge :pray: 
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx1y21CGptZRmjSwY:-O1q29WC2mW7KC_PQZHh:bovckzm) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L187)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Right, tnx

I ended up panicking, even though it is a user error technically, but since this is a test util it's probably overkill to return an error?

Also killed this method completely, it has only one use inside a constructor, which was a bit awkward anyway.
</blockquote></details>

Didn't push yet, extracted to other PR

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1uW79fCg5fjQ1OL10Y:-O1uW79g6fFZaBHjdeSh:bg7uxru) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
> ```XML
> pub struct AccountTransactionGenerator<'a> {
>     account_id: AccountId,
>     contract_instance_id: ContractInstanceId,
> ```

Maybe add `[inner_/Inner]` prefix to member name/alias?



_Code quote:_
```XML
    account_id: AccountId,
    contract_instance_id: ContractInstanceId,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jvHVmCTuRBz0CV-hM):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

oh wait i can't push yet, i'm waiting for previous PRs to be merged, will ping here once I actually make the change
</blockquote></details>

Pushed.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1g8rJh2Wyb-NJsZ95P:-O1uv5jMAu29jqVSwRFo:b-i95jpb) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L153)):*
> ```XML
>     // Maps account IDs to their ordinal position within their contract type group in
>     // the initialization array.
>     // Invariant: should have the same keys as account_contracts
> ```

Stale, maps merged.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jx1y21CGptZRmjSwY:-O1uv9MX0QmWzZ8TO7J9:b-nowgvx) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L187)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Didn't push yet, extracted to other PR
</blockquote></details>

Stale, now this value is strongly typed, and is part of the AccountTransactionGenerator
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1jyJIA9i4BkK_KVg3v:-O1uvKr30Yn-xZuKL44a:bcrq9hj) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good idea, but this is too many changes at this point so I'm splitting this PR further and extracting some substeps into: [1](https://github.com/starkware-libs/mempool/pull/476) then [2](https://github.com/starkware-libs/mempool/pull/477)

Once those are merged I'll rebase here and continue.
</blockquote></details>

Merged, rebased here, now this PR is only the instance_id change.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1uW79fCg5fjQ1OL10Y:-O1uvuPrD9mlsfZ97f_d:bqeur0b) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe add `[inner_/Inner]` prefix to member name/alias?
</blockquote></details>

Can you explain more please? is this what you meant BTW?
```rust
pub struct AccountTransactionGenerator {
    inner_account: FeatureContract,
    inner_contract_instance_id: ContractInstanceId,
    nonce_manager: Rc<RefCell<NonceManager>>,
}
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459#-:-O1uxX4Y3vZtyMbGvPLp:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1uW79fCg5fjQ1OL10Y:-O1uxMln2CZcuc04bSEB:bgpe0of) ([raw file](https://github.com/starkware-libs/mempool/blob/6ebd62267e788ae560252f2273d07e31ad13057e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L200)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you explain more please? is this what you meant BTW?
```rust
pub struct AccountTransactionGenerator {
    inner_account: FeatureContract,
    inner_contract_instance_id: ContractInstanceId,
    nonce_manager: Rc<RefCell<NonceManager>>,
}
```
</blockquote></details>

Nevermind, you only have one ID now.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1vM2xWEgnkwFoRbovc:-O1vM2xWEgnkwFoRbovd:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/3bdc6dc4cb59a596b337ddc373cf3d55dc3b4b86/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L217)):*
> ```XML
>     account: FeatureContract,
>     contract_instance_id: ContractInstanceId,
>     nonce_manager: Rc<RefCell<NonceManager>>,
> ```





_Suggestion:_
```XML
SharedNonceManager
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/mempool/459#-O1vM2xWEgnkwFoRbovc:-O1viw-dA6er5L-uQMLU:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3bdc6dc4cb59a596b337ddc373cf3d55dc3b4b86/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L217)):*
> ```XML
>     account: FeatureContract,
>     contract_instance_id: ContractInstanceId,
>     nonce_manager: Rc<RefCell<NonceManager>>,
> ```

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by giladchase — COMMENTED** [review]
> Dismissed @Yael-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
