### PR TITLE
feat(mempool): insert eligible tx to tx queue in commit-block accordi…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…ng to state changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/464#-O1kyQsdB_ZN4kP3J8Lw:-O1kyQseCSq7BlADSyea:b-qde3bc) (no related file):*
This PR adds an eligible transaction to the `tx_queue` based on the state changes.
It inserts new transactions in `commit_block` from another leader, provided the transaction is already present in the `tx_pool`.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O1vlnCO8tfd0gfsIdeE:-O1vlnCO8tfd0gfsIdeF:b6oa1cv) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L92)):*
> ```XML
>                 if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, nonce) {
>                     self.tx_queue.insert(*tx);
>                 }
> ```

Can this be moved into the scope of removing from the Q?



_Code quote:_
```XML
                if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, nonce) {
                    self.tx_queue.insert(*tx);
                }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O1vlnCO8tfd0gfsIdeE:-O1zsJu-0HkHneOG9Iho:b-u0qn2u) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be moved into the scope of removing from the Q?
</blockquote></details>

Not sure I get it :)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O1vlnCO8tfd0gfsIdeE:-O2Pe04h-n85rk_p9rjN:b-c6lls2) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I get it :)
</blockquote></details>

```rs
        for (address, AccountState { nonce }) in state_changes {
            if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != nonce) {
                self.tx_queue.remove(address);

                if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, nonce) {
                    self.tx_queue.insert(*tx);
                }
            }
        }
```
What am I missing?
Maybe we should add a `get_next_eligible_tx(account)` API?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O2TTnzc1VLoIgs9onOT:-O2TTnzc1VLoIgs9onOU:b5ha1jq) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L80)):*
> ```XML
>             //    block, applicable when the block is from the same leader.
>             // 2. Remove a transaction from queue with nonce greater than those committed to the
>             //    block, applicable when the block is from a different leader.
> ```

I think this doc. is too extensive, not sure I want to reference consensus (it's our of scope). Perhaps saying `// Align the queue with the committed nonces.`. 
I also think it can appear in one paragraph:

```rs
// Align the queue with the committed nonces.
if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != next_nonce) {
    self.tx_queue.remove(address);
}

if self.tx_queue.get_nonce(address).is_none() {
    if let Some(next_eligible_tx) = self.tx_pool.get_by_address_and_nonce(address, next_nonce) {
        self.tx_queue.insert(*next_eligible_tx);
    }
}
```
Where do we have `get_next_eligible_tx` API? It can be used here, right?



_Code quote:_
```XML
            // Dequeue transactions from the queue in the following cases:
            // 1. Remove a transaction from queue with nonce lower than those committed to the
            //    block, applicable when the block is from the same leader.
            // 2. Remove a transaction from queue with nonce greater than those committed to the
            //    block, applicable when the block is from a different leader.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O2TTnzc1VLoIgs9onOT:-O2TnY0x6Ow6TGlAa39A:b-pzx66j) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L80)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think this doc. is too extensive, not sure I want to reference consensus (it's our of scope). Perhaps saying `// Align the queue with the committed nonces.`. 
I also think it can appear in one paragraph:

```rs
// Align the queue with the committed nonces.
if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != next_nonce) {
    self.tx_queue.remove(address);
}

if self.tx_queue.get_nonce(address).is_none() {
    if let Some(next_eligible_tx) = self.tx_pool.get_by_address_and_nonce(address, next_nonce) {
        self.tx_queue.insert(*next_eligible_tx);
    }
}
```
Where do we have `get_next_eligible_tx` API? It can be used here, right?
</blockquote></details>

Thanks, updated.

This my my next_elegible method:
`self.tx_pool.get_by_address_and_nonce(address, nonce)`.
___
*[`crates/mempool/src/mempool.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O1vlnCO8tfd0gfsIdeE:-O2ToPlfA55GcMPbSePF:bqttogc) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

```rs
        for (address, AccountState { nonce }) in state_changes {
            if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != nonce) {
                self.tx_queue.remove(address);

                if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, nonce) {
                    self.tx_queue.insert(*tx);
                }
            }
        }
```
What am I missing?
Maybe we should add a `get_next_eligible_tx(account)` API?
</blockquote></details>

The code has been updated. See the above comment.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O2TTnzc1VLoIgs9onOT:-O2TWpBG2wOtzYw4CKzT:b-tiwxni) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L80)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Thanks, updated.

This my my next_elegible method:
`self.tx_pool.get_by_address_and_nonce(address, nonce)`.
</blockquote></details>

I think it can be a method (can be done in a separated PR), and also shared with replenishing logic.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464#-:-O2TvZm79ypT4xBagZGv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/mempool/464#-O2UADmQCN-XLlr0YKaP:-O2UADmR-N6yuIhQ1jbm:b-jbw8ec) ([raw file](https://github.com/starkware-libs/mempool/blob/a26b2347c73fc48f14bc9850f658d6ff565f89dc/crates/mempool/src/mempool.rs#L86)):*
> ```XML
>             }
> 
>             // TODO: remove the transactions from the tx_pool.
> ```

Can be in another PR.



_Suggestion:_
```XML
            }
            
            if self.tx_queue.get_nonce(address).is_none() {
                if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, nonce) {
                    self.tx_queue.insert(*tx);
                }
            }

            // TODO: remove the transactions from the tx_pool.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/464#-O2TTnzc1VLoIgs9onOT:-O2UPDO35_lNQ0EH5F__:bz42p6d) ([raw file](https://github.com/starkware-libs/mempool/blob/554b01fa64bfccada13da04579fd85d3aa498a25/crates/mempool/src/mempool.rs#L80)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it can be a method (can be done in a separated PR), and also shared with replenishing logic.
</blockquote></details>

Okay, we'll do in another PR.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/464)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
