### PR TITLE
feat: remove deprecated network component from gateway and batcher

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:4e0d8a62

---

**Stack**:
- #167 ⬅
- #166

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/167)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/mempool/167#-Nyxif_t9nSPBd7MDUAv):*




_Suggestion:_
```
chore
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/mempool/167#-NyxjnJL1Df8tid5PVl6:-NyxjnJL1Df8tid5PVl7:b-83qk8d) ([raw file](https://github.com/starkware-libs/mempool/blob/c5631b17ca42e130bec7df9384d1ac5edbb70a40/crates/gateway/tests/end_to_end_test.rs#L27)):*
> ```XML
> 
> #[tokio::test]
> async fn test_send_and_receive() {
> ```

Shall we add another test for the Server-Client communication?



_Code quote:_
```XML
test_send_and_receive()
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/167)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/mempool/167#-Nyxif_t9nSPBd7MDUAv):*
next time :-)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/167)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/mempool/167#-NyxjnJL1Df8tid5PVl6:-NyzNi0XA4s-AvnurvTT:b-7r8h8p) ([raw file](https://github.com/starkware-libs/mempool/blob/c5631b17ca42e130bec7df9384d1ac5edbb70a40/crates/gateway/tests/end_to_end_test.rs#L27)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Shall we add another test for the Server-Client communication?
</blockquote></details>

We have tests for that at the infra crate, so IMO no.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 2 of 7 files at r4, 1 of 4 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/167)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/167)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
