### PR TITLE
feat: add component runner

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:79839d8f

### CODE REVIEW

**Review by uriel-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/93)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt47Hd7lpJoL_RGNwa:-Nwt47Hd7lpJoL_RGNwb:b-m27nif) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/Cargo.toml#L22)):*
> ```TOML
> 
> [workspace.dependencies]
> anyhow = "1.0.44"
> ```

is this needed?
___
*[`crates/mempool_infra/Cargo.toml` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt4N7XE3vb7ccgW3yo:-Nwt4N7XE3vb7ccgW3yp:b-3zg1lv) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/crates/mempool_infra/Cargo.toml#L21)):*
> ```TOML
> [dev-dependencies]
> assert_matches.workspace = true
> pretty_assertions.workspace = true
> ```

is this needed as well?



_Code quote:_
```TOML
[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
```
___
*[`crates/mempool_infra/src/component_runner.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt3occB6kiaVq8CsVD:-Nwt3occB6kiaVq8CsVE:b-wml95f) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/crates/mempool_infra/src/component_runner.rs#L16)):*
> ```XML
> pub trait ComponentRunner {
>     /// Start the component. Normally this function should never return.
>     async fn start_component(&self) -> Result<(), ComponentStartError>;
> ```

why not cal the function just start (the component is implied)?



_Suggestion:_
```XML
    async fn start(&self) -> Result<(), ComponentStartError>;
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/93)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt47Hd7lpJoL_RGNwa:-NwtFzBW8rF7qUa8-fXw:b-kj8xw8) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/Cargo.toml#L22)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

No, removed.
___
*[`crates/mempool_infra/Cargo.toml` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt4N7XE3vb7ccgW3yo:-NwtG7RFESa7MdOZmDVZ:b-kj8xw8) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/crates/mempool_infra/Cargo.toml#L21)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

is this needed as well?
</blockquote></details>

No, removed.
___
*[`crates/mempool_infra/src/component_runner.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt3occB6kiaVq8CsVD:-NwtGCzj8mvx7U_025mA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/crates/mempool_infra/src/component_runner.rs#L16)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

why not cal the function just start (the component is implied)?
</blockquote></details>

Done.

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/93#-:-NwtHde12KIZNK0I3HoF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/93)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`crates/mempool_infra/src/component_runner.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/93#-Nwt3occB6kiaVq8CsVD:-NwtWhclBX8iUxCMk-ms:bzi0tse) ([raw file](https://github.com/starkware-libs/mempool/blob/e65f415ac60a125f580a112922d0cac786d42ff5/crates/mempool_infra/src/component_runner.rs#L16)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think the name start_component was the right one. The component runner could have (in the future) start_db and start_network, so in my opinion, the start_component is better than the plain start.

**Pull request merged**
