### PR TITLE
chore: add minimal README including codecov and build

### PR DESCRIPTION
**Pull request by giladchase**
**Stack**:
- #11
- #10
- #9
- #8 ⬅
- #7

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/8)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/8#-:-NtQ2DwaA-hJiviDBDas:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/8#-NtQ37w620cO8UAmLfc8:-NtQ37w620cO8UAmLfc9:b-3dsrzw) (no related file):*
Are you planning on adding a README file for each crate?

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/8#-NtQ37w620cO8UAmLfc8:-NtQ5cBU1cFkZlBqt1NY:bz5rpx2) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Are you planning on adding a README file for each crate?
</blockquote></details>

That's more a product thing, i only messed with the README to add the button thingies, which is a technical thing.
We'll add it once things gain more traction.

___

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
