### PR TITLE
feat: adding component start(initialization) to the server start

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:77f186d4

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WVuGt7y_9cf1XwbUy:-O1WVuGt7y_9cf1XwbUz:bvvpfce) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_runner.rs#L18)):*
> ```XML
>         Ok(())
>     }
> }
> ```

The naming here slightly confuses me: a `runner` has a `start` function; wouldn't it be clearer if the function's name would be `run`?



_Code quote:_
```XML
pub trait ComponentRunner {
    /// Start the component. By default do nothing.
    async fn start(&mut self) -> Result<(), ComponentStartError> {
        Ok(())
    }
}
```
___
*[`crates/mempool_infra/tests/common/mod.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WUbfO6S5gDK2QpFMf:-O1WUbfPCCffMTUHUmHM:b9dmrpj) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/tests/common/mod.rs#L4)):*
> ```XML
> use serde::{Deserialize, Serialize};
> use starknet_mempool_infra::component_client::ClientResult;
> use starknet_mempool_infra::component_runner::ComponentRunner;
> ```

Please add an empty line between the last `use` and the first `type` def.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WWMLo7YBenEklMZ6D:-O1WWMLo7YBenEklMZ6E:bb663cf) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_server.rs#L66)):*
> ```XML
>                 return;
>             }
>         }
> ```

Can we unify some of this logic with the impl in the `empty server`?



_Code quote:_
```XML
        match self.component.start().await {
            Ok(_) => info!("ComponentServer::start() completed."),
            Err(err) => {
                error!("ComponentServer::start() failed: {:?}", err);
                return;
            }
        }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WWw5L-tzESXKWVrXZ:-O1WWw5L-tzESXKWVrX_:b-mhrcji) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_runner.rs#L18)):*
> ```XML
>         Ok(())
>     }
> }
> ```

I'm also in favor of having better consistency with the `ComponentServerStarter` : here the `start` function returns `Result`, in the server starter it doesn't return anything.

Is there a way to address that (can be in a different pr)?



_Code quote:_
```XML
pub trait ComponentRunner {
    /// Start the component. By default do nothing.
    async fn start(&mut self) -> Result<(), ComponentStartError> {
        Ok(())
    }
}
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WWw5L-tzESXKWVrXZ:-O1WaWH1DjwNSUr-kLQC:bnpslxk) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_runner.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'm also in favor of having better consistency with the `ComponentServerStarter` : here the `start` function returns `Result`, in the server starter it doesn't return anything.

Is there a way to address that (can be in a different pr)?
</blockquote></details>

I agree, but let's address it in a different PR. 
___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WVuGt7y_9cf1XwbUy:-O1WzLwp8f_hqMN3qhaD:b-8grxoi) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_runner.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The naming here slightly confuses me: a `runner` has a `start` function; wouldn't it be clearer if the function's name would be `run`?
</blockquote></details>

Changed to `ComponentStarter`.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WUbfO6S5gDK2QpFMf:-O1WzcLn1IiSauJAzMe_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/tests/common/mod.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add an empty line between the last `use` and the first `type` def.
</blockquote></details>

Done.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1WWMLo7YBenEklMZ6D:-O1XE0M12TKMaAWr3WfN:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2385f67f3c9d85f6676d4188a8960d97879282e8/crates/mempool_infra/src/component_server.rs#L66)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we unify some of this logic with the impl in the `empty server`?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/447#-O1kKqDi9piD0Myubzjg:-O1kKqDi9piD0Myubzjh:by0umek) ([raw file](https://github.com/starkware-libs/mempool/blob/a35a991836c9e9155c984fe3b1f77a22b43acf4a/crates/mempool_infra/src/component_server.rs#L73)):*
> ```XML
> }
> 
> pub async fn start_component<Component>(component: &mut Component) -> bool
> ```

Please return `Result`.



_Code quote:_
```XML
bool
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/447#-:-O1kQMImCeYBh4UqJ8Qm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
