### PR TITLE
refactor(mempool): refactor get_nonce method for transaction queue

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/433#-O1QrClp2UIwStMXYLd-:-O1QrClp2UIwStMXYLd0:b-1y8q4h) ([raw file](https://github.com/starkware-libs/mempool/blob/ad082c41e8d77a9f872d1ed24aa967ffedbc092f/crates/mempool/src/transaction_queue.rs#L50)):*
> ```XML
>     pub fn _get_nonce(&self, address: ContractAddress) -> Option<&Nonce> {
>         self.address_to_tx.get(&address).map(|tx| &tx.nonce)
>     }
> ```

Can do in this PR, it's the same change.



_Suggestion:_
```XML
    pub fn _get_nonce(&self, address: ContractAddress) -> Option<Nonce> {
        self.address_to_tx.get(&address).map(|tx| tx.nonce)
    }
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433#-:-O1RVR6i7WYWJzZPwbAJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/433#-O1QrClp2UIwStMXYLd-:-O1R_lsg0IQT3NqSm7W_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ad082c41e8d77a9f872d1ed24aa967ffedbc092f/crates/mempool/src/transaction_queue.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can do in this PR, it's the same change.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/433)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
