### PR TITLE
feat: add transaction hash calculation

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Rebase?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13#-:-Nu2PpV50sYFMJfNQ90E:b9x2p2u)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
On hold.
Since we've moved to using `ExternalTransaction` instead of `starknet_api::transaction`, I need to implement support for calculating the transaction hash in `ExternalTransaction` first.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13#-:-Nu4158d4nLWod9M551L:b-9he51h)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
Updated.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13#-:-Nuximu0De_EsQqwyylD:b-bw8e14)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1w1oW7PHCmhtzU4VV:-Nv1w1oW7PHCmhtzU4VW:bp96t6p) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L36)):*
> ```XML
>             post(move |request_body: Json<ExternalTransaction>| {
>                 Self::add_transaction(gateway, request_body)
>             }),
> ```

Hmm what happened here? :thinking: 
If this is because you moved add_tx to be a method, then I think it might not be worth it, if it requires "fighting" with axum.
(BUt I totally get why you moved it into a method, and in general you were definitely correct in doing so!)



_Code quote:_
```XML
            post(move |request_body: Json<ExternalTransaction>| {
                Self::add_transaction(gateway, request_body)
            }),
```
___
*[`crates/gateway/src/gateway.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1q-Ao7XnFlLD2f6S2:-Nv1q-ApD-2qQBGoq79X:b-hv7k1a) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L56)):*
> ```XML
>             ExternalTransaction::DeployAccount(_) => "DEPLOY_ACCOUNT",
>             ExternalTransaction::Invoke(_) => "INVOKE",
>         };
> ```

You can delete this and the return value, it was just a placeholder.



_Code quote:_
```XML
        let tx_type = match transaction_json {
            ExternalTransaction::Declare(_) => "DECLARE",
            ExternalTransaction::DeployAccount(_) => "DEPLOY_ACCOUNT",
            ExternalTransaction::Invoke(_) => "INVOKE",
        };
```
___
*[`crates/gateway/src/gateway.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1qF7qAAhUHdfuwurT:-Nv1qF7qAAhUHdfuwurU:b-4ik1tb) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L59)):*
> ```XML
> 
>         let transaction_clone = transaction_json.clone();
>         let config_clone = self.config.clone();
> ```

Is the clone necessary? chain_id is Copy



_Code quote:_
```XML
        let config_clone = self.config.clone();
```
___
*[`crates/gateway/src/gateway.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1tutC2iTDN3aK8xi-:-Nv1tutC2iTDN3aK8xi0:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L65)):*
> ```XML
>         });
> 
>         tx_type
> ```





_Suggestion:_
```XML
        internal_tx.tx_hash
```
___
*[`crates/gateway/src/gateway_test.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1prSB1aW_RkCw4PAg:-Nv1prSCCCd_9DhtsjSG:b-ijzewm) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway_test.rs#L31)):*
> ```XML
>         config: gateway::GatewayConfig {
>             bind_address: "0.0.0.0:8080".to_string(),
>             chain_id: ChainId("SN_MAIN".to_string()),
> ```

Should this be `main` inside a test?



_Code quote:_
```XML
            chain_id: ChainId("SN_MAIN".to_string()),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1w1oW7PHCmhtzU4VV:-Nv2Rz0F8b5buIcakXXZ:b-scow9y) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Hmm what happened here? :thinking: 
If this is because you moved add_tx to be a method, then I think it might not be worth it, if it requires "fighting" with axum.
(BUt I totally get why you moved it into a method, and in general you were definitely correct in doing so!)
</blockquote></details>

WDYM by "not worth it"?
___
*[`crates/gateway/src/gateway.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1q-Ao7XnFlLD2f6S2:-Nv2RjGL9sJOTj9V8Z7V:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L56)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You can delete this and the return value, it was just a placeholder.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1qF7qAAhUHdfuwurT:-Nv2OPZ_1_SoejDmmf7R:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is the clone necessary? chain_id is Copy
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1tutC2iTDN3aK8xi-:-Nv2Ri319xnyxcW4pKvW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L65)):*
> ```XML
>         });
> 
>         tx_type
> ```

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1prSB1aW_RkCw4PAg:-Nv2OeKo5s3MNAZR-NRL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway_test.rs#L31)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be `main` inside a test?
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1w1oW7PHCmhtzU4VV:-Nv5kOpJ5Vf9LBfoOB_K:b-5klqor) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

WDYM by "not worth it"?
</blockquote></details>

Ya i wasn't clear :sweat_smile: 

I meant that if i end up having to call a method and pass `self` manually into it (because axum really wants it to be a function), it's not worth making it a method, despite it relying on gateway's `self`.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, 3 of 5 files at r5, 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 41 at r6](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvRire55J-RylOjGanV:-NvRire55J-RylOjGanW:b-ivjlcb) ([raw file](https://github.com/starkware-libs/mempool/blob/d5f1fedef287205d3e2226e46b46bb8b483e52ec/crates/gateway/src/gateway.rs#L41)):*
> ```XML
>     /// Sets up the router with the specified routes for the server.
>     pub fn app(self) -> Router {
>         let gateway = self.clone();
> ```

is clone a must here? 
___
*[`crates/gateway/src/gateway.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvRmttEE_ZUgBcPbMBV:-NvRmttEE_ZUgBcPbMBW:b1wth06) ([raw file](https://github.com/starkware-libs/mempool/blob/d5f1fedef287205d3e2226e46b46bb8b483e52ec/crates/gateway/src/gateway.rs#L52)):*
> ```XML
>     }
> 
>     async fn add_transaction(
> ```

I've seen some examples where the gateway's functions are not implemented inside the gateway struct.

https://github.com/tokio-rs/axum/blob/b85bdc1be9081f40878c8fe79aeb50b19fc49957/axum/src/docs/extract.md?plain=1#L47](https://github.com/tokio-rs/axum/blob/b85bdc1be9081f40878c8fe79aeb50b19fc49957/axum/src/docs/extract.md?plain=1#L47)
___
*[`crates/gateway/src/gateway_test.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvCBDkw3VTL9i3Sz8oz:-NvCBDkx37WqYuhxsvE7:b-eck2rk) ([raw file](https://github.com/starkware-libs/mempool/blob/d41677fb28e0bb364d290239c33ef8c376ed92fc/crates/gateway/src/gateway_test.rs#L29)):*
> ```XML
> #[tokio::test]
> async fn test_add_transaction(#[case] json_file_path: &str, #[case] expected_response: &str) {
>     use starknet_api::core::ChainId;
> ```

why not at the beginning of the file?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/gateway/src/gateway.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv1w1oW7PHCmhtzU4VV:-NvS-4Xq8yIYUt43igJf:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/aba753a9677f1c4e7fabaeb44f030422f23314e0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya i wasn't clear :sweat_smile: 

I meant that if i end up having to call a method and pass `self` manually into it (because axum really wants it to be a function), it's not worth making it a method, despite it relying on gateway's `self`.
</blockquote></details>

Done
___
*[`crates/gateway/src/gateway.rs` line 41 at r6](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvRire55J-RylOjGanV:-NvS-6gr9vwYdzzG4dre:b-80ul4c) ([raw file](https://github.com/starkware-libs/mempool/blob/d5f1fedef287205d3e2226e46b46bb8b483e52ec/crates/gateway/src/gateway.rs#L41)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is clone a must here?
</blockquote></details>

Stale
___
*[`crates/gateway/src/gateway.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvRmttEE_ZUgBcPbMBV:-NvS--kr8Je0rDbfHYIZ:bwbw24m) ([raw file](https://github.com/starkware-libs/mempool/blob/d5f1fedef287205d3e2226e46b46bb8b483e52ec/crates/gateway/src/gateway.rs#L52)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I've seen some examples where the gateway's functions are not implemented inside the gateway struct.

https://github.com/tokio-rs/axum/blob/b85bdc1be9081f40878c8fe79aeb50b19fc49957/axum/src/docs/extract.md?plain=1#L47](https://github.com/tokio-rs/axum/blob/b85bdc1be9081f40878c8fe79aeb50b19fc49957/axum/src/docs/extract.md?plain=1#L47)
</blockquote></details>

Merci!
___
*[`crates/gateway/src/gateway_test.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvCBDkw3VTL9i3Sz8oz:-NvS-3dM3SfA7ZRf_Fuq:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d41677fb28e0bb364d290239c33ef8c376ed92fc/crates/gateway/src/gateway_test.rs#L29)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not at the beginning of the file?
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/gateway/src/gateway_test.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvWT7s_EkWNB8-rE8uN:-NvWZTDO8SlGvn9PFTC1:b-84847m) ([raw file](https://github.com/starkware-libs/mempool/blob/d1f7a490a06de55345fda3fcdfa05164a66e6815/crates/gateway/src/gateway_test.rs#L26)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not at the beginning of the file?
</blockquote></details>

Moved
___
*[`crates/gateway/tests/routing_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/13#-NvWTri54ki9o2G0AyMy:-NvWZgOf0o8_RZXy4ukb:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d1f7a490a06de55345fda3fcdfa05164a66e6815/crates/gateway/tests/routing_test.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
Due to our discussion with Yael and Dafna yesterday, plz talk to one of them to make sure there isn't double work being done here.
The decision was (I think) to use external tx, but not internal tx just yet.

External will be cast into some NonExecutableInternalTransaction which has tip and tx hash only.

> Reviewed 1 of 6 files at r3, 3 of 6 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13#-:-Nv_dYZe6hnIXRvCMKij:bouzj1k)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/Cargo.toml` line 22 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_cVVB-Yp6-JEWlKW2:-Nv_cVVB-Yp6-JEWlKW3:b-10o17o) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/Cargo.toml#L22)):*
> ```TOML
> tower.workspace = true
> validator.workspace = true
> tokio.workspace = true
> ```

alphabetize



_Code quote:_
```TOML
tower.workspace = true
validator.workspace = true
tokio.workspace = true
```
___
*[`crates/gateway/src/gateway.rs` line 66 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_esf71n0IDCmQBZ-W:-Nv_esf71n0IDCmQBZ-X:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/src/gateway.rs#L66)):*
> ```XML
>         InternalTransaction::DeployAccount(tx) => tx.tx_hash.to_string().into_response(),
>         InternalTransaction::Invoke(tx) => tx.tx_hash.to_string().into_response(),
>     }
> ```





_Suggestion:_
```XML
    let internal_tx = match internal_tx {
        InternalTransaction::Declare(tx) => tx.tx_hash,
        InternalTransaction::DeployAccount(tx) => tx.tx_hash,
        InternalTransaction::Invoke(tx) => tx.tx_hash,
    }
    internal_tx.to_string().into_response()
```
___
*[`crates/gateway/src/gateway.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_cnNt67QbC85s3cBp:-Nv_cnNt67QbC85s3cBq:bumvzss) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/src/gateway.rs#L85)):*
> ```XML
>     chain_id: ChainId,
>     tx: ExternalTransaction,
> }
> ```

Should chain_id be part of ExternalTransaction? is it the case in papyrus?



_Code quote:_
```XML
#[derive(Deserialize)]
pub struct GatewayTransactionInput {
    chain_id: ChainId,
    tx: ExternalTransaction,
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
Checking with them...

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/13#-:-NvaF6w_0gnRf22DAW4l:b-4xowzr)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/Cargo.toml` line 22 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_cVVB-Yp6-JEWlKW2:-NvaEa4J8TS3eIchvmXu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/Cargo.toml#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 66 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_esf71n0IDCmQBZ-W:-NvaEqWWEf1k-t4kcmNA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/src/gateway.rs#L66)):*
> ```XML
>         InternalTransaction::DeployAccount(tx) => tx.tx_hash.to_string().into_response(),
>         InternalTransaction::Invoke(tx) => tx.tx_hash.to_string().into_response(),
>     }
> ```

Done.
___
*[`crates/gateway/src/gateway.rs` line 85 at r8](https://reviewable.io/reviews/starkware-libs/mempool/13#-Nv_cnNt67QbC85s3cBp:-NvaEx2_2XK-90PUtyTi:b-3adtfs) ([raw file](https://github.com/starkware-libs/mempool/blob/27cde79ba2c0cd5f11d37effd04bf887b71944b7/crates/gateway/src/gateway.rs#L85)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should chain_id be part of ExternalTransaction? is it the case in papyrus?
</blockquote></details>

No, it's not.
It's a gateway field.

**Comment by MohammadNassar1** [comment]
Yael has implemented it.

**Pull request closed without merging**
