### PR TITLE
test: add deploy_account test to gateway_test and stateful test

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VFVuP2ZrcMBfF3A3Y:-O-VFVuP2ZrcMBfF3A3Z:bd7hm7z) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L366)):*
> ```XML
>     pub state_reader_factory: TestStateReaderFactory,
>     pub external_tx: ExternalTransaction,
> }
> ```

It doesn't seem logical to attach the state reader factory to a single transaction. The factory is a single instance that serves the GW throughout all transactions, and not a parameter of a single transaction.

I would suggest creating them separately, and make the `account_contract` and `test_contract` constants to be used for both of them, or pass them as arguments. WDYT?



_Code quote:_
```XML
pub struct TestTxParams {
    pub state_reader_factory: TestStateReaderFactory,
    pub external_tx: ExternalTransaction,
}
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VcHfi8ZZcngVrwYKd:-O-VcHfi8ZZcngVrwYKe:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L368)):*
> ```XML
> }
> 
> pub fn test_invoke_tx_params(invalid_balance: bool) -> TestTxParams {
> ```





_Suggestion:_
```XML
test_invoke_tx_params(zero_balance: bool)
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VdPOn71D_1JN-_0Uq:-O-VdPOn71D_1JN-_0Ur:b-wta4e4) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L385)):*
> ```XML
>         sender_address,
>         calldata
>     ));
> ```

(same for the other function)



_Suggestion:_
```XML
    let account_balance = if invalid_balance { 0 } else { BALANCE };
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
    let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
    let sender_address = account_contract.get_instance_address(0);
    let mut nonce_manager = NonceManager::default();

    let block_context = &BlockContext::create_for_testing();
    let external_tx = external_invoke_tx(invoke_tx_args!(
        resource_bounds: executable_resource_bounds_mapping(),
        nonce_manager.next(sender_address),
        sender_address,
        create_trivial_calldata(test_contract.get_instance_address(0))
    ));
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 438 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VuYZS5MBuDOacS3-H:-O-VuYZS5MBuDOacS3-I:b-hxrcfn) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L438)):*
> ```XML
>     chain_info: &ChainInfo,
>     account_balance: u128,
> ) {
> ```

Consider making it a general `fund_account` function for all tx types.



_Code quote:_
```XML
pub fn fund_account_for_deploy(
    deploy_tx: &ExternalDeployAccountTransactionV3,
    state_reader: &mut DictStateReader,
    chain_info: &ChainInfo,
    account_balance: u128,
) {
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VFVuP2ZrcMBfF3A3Y:-O-esbp01fOpSiBB6d5Z:bux61q6) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L366)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It doesn't seem logical to attach the state reader factory to a single transaction. The factory is a single instance that serves the GW throughout all transactions, and not a parameter of a single transaction.

I would suggest creating them separately, and make the `account_contract` and `test_contract` constants to be used for both of them, or pass them as arguments. WDYT?
</blockquote></details>

refactored everything, let me know what you think now
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VcHfi8ZZcngVrwYKd:-O-_jvJB7jYYlmDUnskW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L368)):*
> ```XML
> }
> 
> pub fn test_invoke_tx_params(invalid_balance: bool) -> TestTxParams {
> ```

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VdPOn71D_1JN-_0Uq:-O-_l1g7AmTV9pxiTEXL:b-s1auni) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L385)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

(same for the other function)
</blockquote></details>

Done.

I am now  passing  the cairo_version as an input, to prepare for supporting invoke of cairo0 contracts.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 438 at r1](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-VuYZS5MBuDOacS3-H:-O-_ljb8A-IHuSDpd-rB:b-rnraql) ([raw file](https://github.com/starkware-libs/mempool/blob/49f72c4e1a470402f0cc7788c6e52e3c68f80843/crates/gateway/src/starknet_api_test_utils.rs#L438)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider making it a general `fund_account` function for all tx types.
</blockquote></details>

done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-pQmlD3Mnhg_XCXSbn:-O-pQmlD3Mnhg_XCXSbo:bib287a) ([raw file](https://github.com/starkware-libs/mempool/blob/1c8c38e1cb4942842413f1073db8eedd41f3ea09/crates/gateway/src/state_reader_test_utils.rs#L98)):*
> ```XML
> }
> 
> pub fn local_test_state_reader_factory_for_deploy_account(
> ```

I'm confused. When you call the other method with `zero_balance=false`, doesn't it already fund the account?



_Code quote:_
```XML
local_test_state_reader_factory_for_deploy_account
```
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-pPby9AWj1QLuMnqm4:-O-pPbyA3Aahal14rtSb:b3kpx) ([raw file](https://github.com/starkware-libs/mempool/blob/1c8c38e1cb4942842413f1073db8eedd41f3ea09/crates/gateway/src/state_reader_test_utils.rs#L104)):*
> ```XML
> 
>     // Fund the deployed_account_address.
>     if let RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(deploy_tx)) = &deploy_tx {
> ```





_Suggestion:_
```XML
let tx =  assert_matches!(
    deploy_tx,
    RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(tx)) => tx
);
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-pQmlD3Mnhg_XCXSbn:-O02ba_M7MBp19qITWWX:bkbrzfw) ([raw file](https://github.com/starkware-libs/mempool/blob/1c8c38e1cb4942842413f1073db8eedd41f3ea09/crates/gateway/src/state_reader_test_utils.rs#L98)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I'm confused. When you call the other method with `zero_balance=false`, doesn't it already fund the account?
</blockquote></details>

it doesn't fund the account to be deployed,
it funds the FeatureContract::AccountWithoutValidation address, which is a constant address set by the blockifier testing library.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/239#-O-pPby9AWj1QLuMnqm4:-O02eeo5AMyeKQs86-wQ:b-z099sv) ([raw file](https://github.com/starkware-libs/mempool/blob/1c8c38e1cb4942842413f1073db8eedd41f3ea09/crates/gateway/src/state_reader_test_utils.rs#L104)):*
> ```XML
> 
>     // Fund the deployed_account_address.
>     if let RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(deploy_tx)) = &deploy_tx {
> ```

Nice!
Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/239#-:-O03EWpG-komV8kalxc1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
