### PR TITLE
chore: make starknet_api_test_utils enabled in test mode

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/329#-O0h7lHK3PZvtsTywsRS:-O0h7lHK3PZvtsTywsRT:b8ip220) ([raw file](https://github.com/starkware-libs/mempool/blob/ee32b961a5d5c816ac838578f61158a383cb85e6/crates/gateway/Cargo.toml#L12)):*
> ```TOML
> 
> [features]
> testing = ["dep:assert_matches"]
> ```

assert_matches is supposed to be enabled only when in testing feature, but it doesnt seem to work properly, need to consult with rust people



_Code quote:_
```TOML
testing = ["dep:assert_matches"]
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329#-:-O0htH32DASQa1etPcad:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/mempool/329#-O0ht6DQ1Zovye5MTpwE:-O0ht6DQ1Zovye5MTpwF:b-8tg8yu) ([raw file](https://github.com/starkware-libs/mempool/blob/ee32b961a5d5c816ac838578f61158a383cb85e6/crates/gateway/src/utils.rs#L63)):*
> ```XML
>         RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(_)) => {
>             ContractAddress::default()
>         }
> ```

Didn't you just write this function in the context of another PR?

Non-blocking at all. 



_Code quote:_
```XML
        // TODO(Mohammad): Add support for deploy account.
        RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(_)) => {
            ContractAddress::default()
        }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/mempool/329#-O0ht6DQ1Zovye5MTpwE:-O0hxM1M5gzKNFGAEFjD:b-jos07o) ([raw file](https://github.com/starkware-libs/mempool/blob/ee32b961a5d5c816ac838578f61158a383cb85e6/crates/gateway/src/utils.rs#L63)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Didn't you just write this function in the context of another PR?

Non-blocking at all.
</blockquote></details>

hmmm not that I recall

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329#-:-O0lp8be6UaxGC0ola6g:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/test_utils/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/mempool/329#-O0mP3oc-Qkdj9M-3Yr_:-O0mP3oc-Qkdj9M-3Yra:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3f97e294ce5e6219cae0183a88683523f72fa6e0/crates/test_utils/src/lib.rs#L3)):*
> ```XML
> pub mod starknet_api_test_utils;
> use std::env;
> use std::path::{Path, PathBuf};
> ```





_Suggestion:_
```XML
use std::env;
use std::path::{Path, PathBuf};

pub mod starknet_api_test_utils;
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/329#-O0h7lHK3PZvtsTywsRS:-O0mPsE9C1LCEaipVKca:b-7rl0kd) ([raw file](https://github.com/starkware-libs/mempool/blob/ee32b961a5d5c816ac838578f61158a383cb85e6/crates/gateway/Cargo.toml#L12)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

assert_matches is supposed to be enabled only when in testing feature, but it doesnt seem to work properly, need to consult with rust people
</blockquote></details>

done

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
