### PR TITLE
refactor(mempool): remove redandunt pub from account transaction inde…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…s struct of tx pool

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/423)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/423)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/423#-O1NamiV48j7l_Y5YlpE:-O1NamiW9GU79g26kpoI:bvc92l1) (no related file):*
A suggestion for a more succinct commit message: "make AccountTransactionIndex API private". 

___
___
*[`crates/mempool/src/transaction_pool.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/423#-O1NbMXe-JuqhpsH-ccB:-O1NbMXe-JuqhpsH-ccC:b-ubzm3p) ([raw file](https://github.com/starkware-libs/mempool/blob/cf15439e4112a51e3dc413160997650b020bb6d5/crates/mempool/src/transaction_pool.rs#L76)):*
> ```XML
> 
> #[derive(Debug, Default)]
> struct AccountTransactionIndex(HashMap<ContractAddress, BTreeMap<Nonce, TransactionReference>>);
> ```

No invariants on this mapping, it can be `pub`lic.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/423)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/423#-O1NbMXe-JuqhpsH-ccB:-O1QJMwQ568yZTc2RAuL:b1pwai5) ([raw file](https://github.com/starkware-libs/mempool/blob/cf15439e4112a51e3dc413160997650b020bb6d5/crates/mempool/src/transaction_pool.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No invariants on this mapping, it can be `pub`lic.
</blockquote></details>

The struct is private, so its methods cannot be accessed publicly.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/423)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/423#-O1NamiV48j7l_Y5YlpE:-O1QKgPE4jaz7QiKBuKg:b6b5iwe) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A suggestion for a more succinct commit message: "make AccountTransactionIndex API private".
</blockquote></details>

Actually, I wanted to emphasize that it's redundant.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/423#-:-O1R3ISF3kKzIpBQeajF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
