### PR TITLE
chore: code to compilation file from gateway

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/344)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#344** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/344?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
+reviewer:@Yael-Starkware

**Comment by ArniStarkware** [comment]
This PR is (almost only) copy-past of code from one file to another.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
