### PR TITLE
fix(mempool): update nonce calculation

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/482#-O1uyE887uHlvGcRo8_C:-O1uyE887uHlvGcRo8_D:b-o1tv5y) (no related file):*
This PR fixes the removal of nonces. 
The state of the commit_block is the state after executing the block's transactions, so the nonces in the state should be removed from the mempool.

___

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/mempool/482#-O1vm0om5JvY5v1NMS2l:-O1vm0om5JvY5v1NMS2m:bujv7v0) ([raw file](https://github.com/starkware-libs/mempool/blob/c860c2b2853e96044c88d8004006c29c9913f030/crates/mempool/src/mempool.rs#L73)):*
> ```XML
>     // push back.
>     // state_changes: a map that associates each account address with the state of the committed
>     // block.
> ```

Not sure this adds information, I think `state_changes` of a function called `commit_block` is clear enough.



_Code quote:_
```XML
    // state_changes: a map that associates each account address with the state of the committed
    // block.
```
___
*[`crates/mempool/src/mempool.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/mempool/482#-O1vmCHT0LlqpP4ZrzWt:-O1vmCHT0LlqpP4ZrzWu:bx0vnhu) ([raw file](https://github.com/starkware-libs/mempool/blob/c860c2b2853e96044c88d8004006c29c9913f030/crates/mempool/src/mempool.rs#L84)):*
> ```XML
>             //    the block, applicable when the block is from the same leader.
>             // 2. Remove a transaction from queue with nonce greater than the next nonce block,
>             //    applicable when the block is from a different leader.
> ```

I want to suggest different phrasing here. Let's continue discussing this case.



_Code quote:_
```XML
            // Dequeue transactions from the queue in the following cases:
            // 1. Remove a transaction from queue with nonce lower and eq than those committed to
            //    the block, applicable when the block is from the same leader.
            // 2. Remove a transaction from queue with nonce greater than the next nonce block,
            //    applicable when the block is from a different leader.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/mempool/482#-O1vm0om5JvY5v1NMS2l:-O1zrofi2rGCU-DT_OjG:bnp8xv) ([raw file](https://github.com/starkware-libs/mempool/blob/c860c2b2853e96044c88d8004006c29c9913f030/crates/mempool/src/mempool.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure this adds information, I think `state_changes` of a function called `commit_block` is clear enough.
</blockquote></details>

Actually, I wanted to emphasize that it includes the current nonce and not the next_nonce.
___
*[`crates/mempool/src/mempool.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/mempool/482#-O1vmCHT0LlqpP4ZrzWt:-O1zrJ0m-_iodI0mz7Ve:b4szhsq) ([raw file](https://github.com/starkware-libs/mempool/blob/c860c2b2853e96044c88d8004006c29c9913f030/crates/mempool/src/mempool.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want to suggest different phrasing here. Let's continue discussing this case.
</blockquote></details>

What do you suggest?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/482#-:-O24USN3ERjkPo5WALaJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
