### PR TITLE
feat(mempool): implement iter method for mempool

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/322#-O0cXG6g3laDv33r8NLx:-O0cXG6g3laDv33r8NLy:bqrbhax) (no related file):*
Add a comment to this PR for future readers, saying that this is a public API of the mempool and not currently used.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/322#-O0cbdjoBrFwm5ZoxYO0:-O0cbdjoBrFwm5ZoxYO1:b-ssw6zh) ([raw file](https://github.com/starkware-libs/mempool/blob/21f29bf2b4fc370b961614a403a84e23f687e63a/crates/mempool/src/mempool.rs#L39)):*
> ```XML
>     }
> 
>     // This function is part of the public API of the mempool, but it is currently not in use.
> ```

The second part might become oudated, note I asked for a comment _in the PR_.
You can also add a docstring, following conventions: `/// Returns an iterator of the transactions in the mempool, ordered by their current priotity.`.



_Code quote:_
```XML
// This function is part of the public API of the mempool, but it is currently not in use.
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/322#-O0cbdjoBrFwm5ZoxYO0:-O0cehzx9AzAhtfwa2yC:bs08bzj) ([raw file](https://github.com/starkware-libs/mempool/blob/21f29bf2b4fc370b961614a403a84e23f687e63a/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The second part might become oudated, note I asked for a comment _in the PR_.
You can also add a docstring, following conventions: `/// Returns an iterator of the transactions in the mempool, ordered by their current priotity.`.
</blockquote></details>

"of the current eligible transactions for sequencing, ordered by their priority"

**Review by MohammadNassar1 — COMMENTED** [review]
Note that`iter` is a public API of the mempool and not currently used.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322#-:-O0cfOFE0Lcnr43o4-Fm:b-uqnwpi)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/322#-O0cbdjoBrFwm5ZoxYO0:-O0cfHcq-M792BxwdA9Y:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/21f29bf2b4fc370b961614a403a84e23f687e63a/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

"of the current eligible transactions for sequencing, ordered by their priority"
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/322#-:-O0cjASY5ai4RcXQuPgI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
