### PR TITLE
feat: create skelaton of transaction validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/transaction_validator_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFkAjHCll2koXVWzit:-NtFkAjIDXM0AXGHmfAi:bomk6yi) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator_test.rs#L114)):*
> ```XML
>     let result = tx_validator.validate(tx);
> 
>     assert_eq!(result.unwrap_err(), expected_error);
> ```

Should we use assert_matches?
If so, this step becomes somewhat more complicated when dealing with different error structures.



_Code quote:_
```XML
assert_eq!(result.unwrap_err(), expected_error);
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFx4LrA1RlHVCoE4yp:-NtFx4LrA1RlHVCoE4yq:b-drt36t) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L17)):*
> ```XML
>     pub min_allowed_tx_version: usize,
>     pub max_allowed_tx_version: usize,
>     pub current_tx_version: usize, // Should this constant be a part of the config?
> ```

Can you use `TransactionVersion` as the type here?



_Code quote:_
```XML
    pub min_allowed_tx_version: usize,
    pub max_allowed_tx_version: usize,
    pub current_tx_version: usize, // Should this constant be a part of the config?
```
___
*[`crates/gateway/src/transaction_validator.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtGfOMc5NRi-ovPGeSN:-NtGfOMc5NRi-ovPGeSO:bewv7jt) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L17)):*
> ```XML
>     pub min_allowed_tx_version: usize,
>     pub max_allowed_tx_version: usize,
>     pub current_tx_version: usize, // Should this constant be a part of the config?
> ```

Do we need both `current_tx_version` and `max_allowed_tx_version`?
___
*[`crates/gateway/src/transaction_validator.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtGCA2o5PALLk6cVyKb:-NtGCA2o5PALLk6cVyKc:bpacj5k) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L25)):*
> ```XML
> 
> impl TransactionValidator {
>     pub fn validate(&self, tx: Transaction) -> Result<(), GatewayError> {
> ```

I think it would be better to return `TransactionValidatorError` here
___
*[`crates/gateway/src/transaction_validator.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFag8vETwKqy_P7eJ2:-NtFag8vETwKqy_P7eJ3:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L26)):*
> ```XML
> impl TransactionValidator {
>     pub fn validate(&self, tx: Transaction) -> Result<(), GatewayError> {
>         // Deploy and L1Handler transactions are not supported in the gateway.
> ```





_Suggestion:_
```XML
// Deploy transactions are deprecated.
// L1Handler transactions are not supported in the gateway.
```
___
*[`crates/gateway/src/transaction_validator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFandr52H1Ev_exSPF:-NtFandr52H1Ev_exSPG:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L34)):*
> ```XML
>             }
>             _ => {}
>         }
> ```





_Suggestion:_
```XML
        if matches!(tx, Transaction::Deploy(_) | Transaction::L1Handler(_)) {
            return Err(TransactionValidatorError::InvalidTransactionType.into());
        }
```
___
*[`crates/gateway/src/transaction_validator.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFxBW7EwoSoMzGRWC7:-NtFxBW7EwoSoMzGRWC8:b-a4fpvq) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L37)):*
> ```XML
> 
>         // Check if the declaration of Cairo / Cairo-0 contracts are blocked.
>         if let Transaction::Declare(tx) = &tx {
> ```

Instead if match consider:

```
if tx.version() < TransactionVersion::TWO && self.config.block_declare_cairo0 {
  ...
}
if tx.version() >= TransactionVersion::TWO && self.config.block_declare_cairo1 {
  ...
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFx4LrA1RlHVCoE4yp:-NtGlLRI9uS9eZ4Gompw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L17)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you use `TransactionVersion` as the type here?
</blockquote></details>

Done.
___
*[`crates/gateway/src/transaction_validator.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtGCA2o5PALLk6cVyKb:-NtGi6kX6zHq-NZ6254o:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L25)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think it would be better to return `TransactionValidatorError` here
</blockquote></details>

Done.
___
*[`crates/gateway/src/transaction_validator.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFag8vETwKqy_P7eJ2:-NtGih3H8I66rZq9auLh:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L26)):*
> ```XML
> impl TransactionValidator {
>     pub fn validate(&self, tx: Transaction) -> Result<(), GatewayError> {
>         // Deploy and L1Handler transactions are not supported in the gateway.
> ```

Done.
___
*[`crates/gateway/src/transaction_validator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFandr52H1Ev_exSPF:-NtGiEc7-Nz2q7aazb9d:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L34)):*
> ```XML
>             }
>             _ => {}
>         }
> ```

Done.
___
*[`crates/gateway/src/transaction_validator.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFxBW7EwoSoMzGRWC7:-NtGieDzALo25wlh6KJx:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L37)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Instead if match consider:

```
if tx.version() < TransactionVersion::TWO && self.config.block_declare_cairo0 {
  ...
}
if tx.version() >= TransactionVersion::TWO && self.config.block_declare_cairo1 {
  ...
}
```
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtGfOMc5NRi-ovPGeSN:-NtGvChQ3zm94qFeWHrD:b-kkw91y) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L17)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we need both `current_tx_version` and `max_allowed_tx_version`?
</blockquote></details>

If we would need it, let us add it later.

Removing it for now.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFag8vETwKqy_P7eJ2:-NtH5zkA1yzTdgkTmwic:bt3b8ji) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator.rs#L26)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm just a bit confused, not related to this PR.
when have we stopped supporting deploy? and shouldn't we be backward compatible?
___
*[`crates/gateway/src/transaction_validator.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtH2Sd04WYmvugHfU6E:-NtH2Sd04WYmvugHfU6F:b-5opdzl) ([raw file](https://github.com/starkware-libs/mempool/blob/6386553df28cd5d9cb72967be1c5e1a7c6f64e08/crates/gateway/src/transaction_validator.rs#L23)):*
> ```XML
> 
> impl TransactionValidator {
>     pub fn validate(&self, tx: Transaction) -> Result<(), TransactionValidatorError> {
> ```

Should we define a TransactionValidatorResult? I think that's the common practice we usually use.
___
*[`crates/gateway/src/transaction_validator.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtH6vNQBvO4wfdvADIj:-NtH6vNQBvO4wfdvADIk:b-3vvk1g) ([raw file](https://github.com/starkware-libs/mempool/blob/6386553df28cd5d9cb72967be1c5e1a7c6f64e08/crates/gateway/src/transaction_validator.rs#L45)):*
> ```XML
>             }
>         }
> ```

again just asking:
declare cairo 0 can be blocked only for version 0/1 tx?  what happens for version 2 and 3?
declare cairo 1 is not relevant for version 0/1 I suppose?
Or does declare v0/1 always mean cairo0 and declare v2/3 always mean cairo1?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtFkAjHCll2koXVWzit:-NtKkJNiCtwy51V-9DQV:b-ru8mf) ([raw file](https://github.com/starkware-libs/mempool/blob/c07449daac512cddd7193c4aed8e56d87d156c43/crates/gateway/src/transaction_validator_test.rs#L114)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Not sure I understand what is your stand on the matter :)
</blockquote></details>

:)
Generally, I support this implementation.
We just may need to change it in the future, when we add more errors to  TransactionValidatorError.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5#-:-NtLOBWMDJZXZEtCJIQB:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLOapJ3XCnI-DBbRyM:-NtLOapJ3XCnI-DBbRyN:b-fkftaj) ([raw file](https://github.com/starkware-libs/mempool/blob/0a99424d64a71dc9d905818bc729c15a83beb2ab/crates/gateway/src/transaction_validator.rs#L86)):*
> ```XML
> }
> 
> fn get_tx_version(tx: &Transaction) -> TransactionVersion {
> ```

Not for this PR. Would be nice to have `version()` implemented in the Transaction struct...
___
*[`crates/gateway/src/transaction_validator_test.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLPAOQ5AJFQkUfPEGG:-NtLPAOQ5AJFQkUfPEGH:b7yg5sf) ([raw file](https://github.com/starkware-libs/mempool/blob/0a99424d64a71dc9d905818bc729c15a83beb2ab/crates/gateway/src/transaction_validator_test.rs#L86)):*
> ```XML
> 
>     assert_eq!(result.unwrap_err(), expected_error);
> }
> ```

Can you add a happy flow test?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator_test.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLPAOQ5AJFQkUfPEGG:-NtLct_57WZ_NA0M-Gg8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0a99424d64a71dc9d905818bc729c15a83beb2ab/crates/gateway/src/transaction_validator_test.rs#L86)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you add a happy flow test?
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLOapJ3XCnI-DBbRyM:-NtLeyTUAhLGN3j0ya2n:b-69s988) ([raw file](https://github.com/starkware-libs/mempool/blob/0a99424d64a71dc9d905818bc729c15a83beb2ab/crates/gateway/src/transaction_validator.rs#L86)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not for this PR. Would be nice to have `version()` implemented in the Transaction struct...
</blockquote></details>

Opened a PR: https://github.com/starkware-libs/starknet-api/pull/195

**Review by dafnamatsry — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5#-:-NtLgXNV0gpWNdSDTBwh:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/Cargo.toml` line 13 at r5](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtMa9SX7Dquke_Ft-qM:-NtMa9SX7Dquke_Ft-qN:b-ojw0sv) ([raw file](https://github.com/starkware-libs/mempool/blob/c05d80685ecf8755faf5e082439c8e5712f4670c/crates/gateway/Cargo.toml#L13)):*
> ```TOML
> 
> [lib]
> name = "gateway_lib"
> ```

See how dependencies are handled: #3  



_Code quote:_
```TOML
[dependencies]
thiserror = "1.0"
starknet_api = "0.8.0"
assert_matches = "1.5.0"
rstest = "0.17.0"

[lib]
name = "gateway_lib"
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/transaction_validator_test.rs` line 101 at r11](https://reviewable.io/reviews/starkware-libs/mempool/5#-Ntoel7VCn0R2mVPMQ6b:-Ntoel7VCn0R2mVPMQ6c:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f450b07f3bc9037f5baae219f0229f631bec80f2/crates/gateway/src/transaction_validator_test.rs#L101)):*
> ```XML
>     Ok(())
> )]
> fn test_transaction_version(
> ```





_Suggestion:_
```XML
fn test_transaction_validator(
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/gateway/src/errors.rs` line 9 at r12](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtomFD5-Fnbbkc6vcim:-NtomFD60-_Lcr_BYYVd:b-l5iuby) ([raw file](https://github.com/starkware-libs/mempool/blob/33aa4afa50a9419f683c37438e08d6d177024c70/crates/gateway/src/errors.rs#L9)):*
> ```XML
> pub enum StarknetApiTransactionError {
>     #[error("This transaction type is not supported by the mempool")]
>     TransactionTypeNotSupported,
> ```

Why did you move it out to a separate enum? 



_Code quote:_
```XML
TransactionTypeNotSupported,
```
___
*[`crates/gateway/src/starknet_api_utils.rs` line 16 at r11](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtokRy4BEC2srfs10oD:-NtokRy4BEC2srfs10oE:b-bvjuht) ([raw file](https://github.com/starkware-libs/mempool/blob/f450b07f3bc9037f5baae219f0229f631bec80f2/crates/gateway/src/starknet_api_utils.rs#L16)):*
> ```XML
> }
> 
> pub trait TransactionParametersExt {
> ```

Maybe TransactionTesteingUtilsExt?



_Code quote:_
```XML
TransactionParametersExt
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/errors.rs` line 9 at r12](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtomFD5-Fnbbkc6vcim:-NtowVgR9RByC3OUm2Gx:b1d2rs) ([raw file](https://github.com/starkware-libs/mempool/blob/33aa4afa50a9419f683c37438e08d6d177024c70/crates/gateway/src/errors.rs#L9)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did you move it out to a separate enum?
</blockquote></details>

It made some sense in the context of the next next PR. Let us cross this bridge when we get to it.
Reverting.
___
*[`crates/gateway/src/starknet_api_utils.rs` line 16 at r11](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtokRy4BEC2srfs10oD:-Ntowjq86wbNPnPCUAVH:bj1cl4c) ([raw file](https://github.com/starkware-libs/mempool/blob/f450b07f3bc9037f5baae219f0229f631bec80f2/crates/gateway/src/starknet_api_utils.rs#L16)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe TransactionTesteingUtilsExt?
</blockquote></details>

In the following PR, this trait will be used for the Validator.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/5)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLOapJ3XCnI-DBbRyM:-Ntyl-kE7XNwj4Z1JVaN:b-su469u) ([raw file](https://github.com/starkware-libs/mempool/blob/0a99424d64a71dc9d905818bc729c15a83beb2ab/crates/gateway/src/transaction_validator.rs#L86)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Opened a PR: https://github.com/starkware-libs/starknet-api/pull/195
</blockquote></details>

PR approved.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_utils.rs` line 16 at r11](https://reviewable.io/reviews/starkware-libs/mempool/5#-NtokRy4BEC2srfs10oD:-Nu4s7G26KVutWkzJlc4:b9gpqd2) ([raw file](https://github.com/starkware-libs/mempool/blob/f450b07f3bc9037f5baae219f0229f631bec80f2/crates/gateway/src/starknet_api_utils.rs#L16)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In the following PR, this trait will be used for the Validator.
</blockquote></details>

It will be used for the validator - and not for testing.

**Comment by ArniStarkware** [comment]
Replaced with #22

**Pull request closed without merging**
