### PR TITLE
feat(gateway): create error type that matches the spec

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/resources/starknet_write_api.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zgm9xDrTA8lT9jwUH:-O1zgm9xDrTA8lT9jwUI:b-x0lfxr) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L0)):*
Move this file to `crates/mempool_test_utils/test_files`
___
*[`crates/gateway/resources/starknet_write_api.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O1zhPTMES6I3GitBaAA:buqmwo6) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L0)):*
What is this file? Is this an external resource? Can/ Should we document is somewhere?

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2-bL-c94dsi4iChfDr:-O2-bL-c94dsi4iChfDs:b-8rxyo4) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/src/gateway_test.rs#L144)):*
> ```XML
> 
>         assert_eq!(err_schema.get("data").is_some(), err.data().is_some());
>     }
> ```

what about checking if all json errors appear in the enum?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zgm9xDrTA8lT9jwUH:-O2OD4DZ3doXKLnwvjAQ:b-bhhnr3) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Move this file to `crates/mempool_test_utils/test_files`
</blockquote></details>

Not sure I agree - it is the spec of the gateway, not just for tests
___
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O2ODDf10z-wuxUYqV0M:b73cgzs) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What is this file? Is this an external resource? Can/ Should we document is somewhere?
</blockquote></details>

Starknet RPC has a repo for the specs: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json
___
*[`crates/gateway/src/gateway_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2-bL-c94dsi4iChfDr:-O2OEF6E4WCwc01ALD4e:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/src/gateway_test.rs#L144)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what about checking if all json errors appear in the enum?
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O2OH4si5klxolWzTPEb:b-r787am) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Starknet RPC has a repo for the specs: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json
</blockquote></details>

How do we make sure the copy we have is up to date?
___
*[`crates/gateway/src/gateway_test.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2OItM2D2j5TaC0ETwr:-O2OItM2D2j5TaC0ETws:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c39696d3f3e457ffba1db53564bc8a02dd87dfba/crates/gateway/src/gateway_test.rs#L127)):*
> ```XML
>         // Use the error serialization to get the error name, and then use it to get the error
>         // schema.
>         let err_schema = match serde_json::to_value(&err).unwrap() {
> ```





_Suggestion:_
```XML
spec_err_schema
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O2OkfHd55ybH5torbyM:b-3z40ov) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

How do we make sure the copy we have is up to date?
</blockquote></details>

Is it necessary? It doesn't change often, and when it does, it is published in a public Slack channel.
We can use a git submodule, but I don't think it is worth it.
Another option is using the Papyrus RPC method`specVersion` and asserting that it matches the file, but it brings more complications.
___
*[`crates/gateway/src/gateway_test.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2OItM2D2j5TaC0ETwr:-O2Om1bG8SALJXdeeFmA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c39696d3f3e457ffba1db53564bc8a02dd87dfba/crates/gateway/src/gateway_test.rs#L127)):*
> ```XML
>         // Use the error serialization to get the error name, and then use it to get the error
>         // schema.
>         let err_schema = match serde_json::to_value(&err).unwrap() {
> ```

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487#-:-O2TAtFjEKxUWgV8Rbk5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O2TA9xa-EH_mLBYiuRq:bchaxuk) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is it necessary? It doesn't change often, and when it does, it is published in a public Slack channel.
We can use a git submodule, but I don't think it is worth it.
Another option is using the Papyrus RPC method`specVersion` and asserting that it matches the file, but it brings more complications.
</blockquote></details>

Ok, let's keep it like that for now.
Can you add a TODO to think about a way to automatically keep track of changes to this file?

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
*[`crates/gateway/resources/starknet_write_api.json` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/487#-O1zhPTMES6I3GitBaA9:-O2UQ2IJ1M68Gfx-f_IY:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/7fb4fcc511c58ed35147b452859b8ce5ed93bad6/crates/gateway/resources/starknet_write_api.json#L)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Ok, let's keep it like that for now.
Can you add a TODO to think about a way to automatically keep track of changes to this file?
</blockquote></details>

Done

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/src/lib.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2Yq8GA0pzcPNdCuLga:-O2Yq8GA0pzcPNdCuLgb:bsoiyzo) ([raw file](https://github.com/starkware-libs/mempool/blob/b5e1f78f2a4a05cde0b0bc63dbc70fbc3754288c/crates/gateway/src/lib.rs#L22)):*
> ```XML
> // TODO(yair): Find a way to detect changes in the RPC spec
> // (https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json).
> // Currently, the spec file is copied manually.
> ```

Why is this TODO here and not somewhere else?
Not that I have a better suggestion for its location.



_Code quote:_
```XML
// TODO(yair): Find a way to detect changes in the RPC spec
// (https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json).
// Currently, the spec file is copied manually.
```

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/lib.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/487#-O2Yq8GA0pzcPNdCuLga:-O2cbGHA2Ba_Ye0BUBJj:b-y30fn9) ([raw file](https://github.com/starkware-libs/mempool/blob/b5e1f78f2a4a05cde0b0bc63dbc70fbc3754288c/crates/gateway/src/lib.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why is this TODO here and not somewhere else?
Not that I have a better suggestion for its location.
</blockquote></details>

Where else can I put it?
It's about a crate level resource

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/487)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
Opened a PR in the sequencer repo: https://github.com/starkware-libs/sequencer/pull/120

**Pull request closed without merging**
