### PR TITLE
refactor: move papyrus state reader

### PR DESCRIPTION
**Pull request by giladchase**
Move papyrus state reader into integration tests, since that is its only
use case.

** Strictly a move operation, no internal changes. **

---

**Stack**:
- #251
- #250
- #249 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249#-:-O-_9afXCI625xIDObcm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/249#-O-_9K6yCNeeSdOyWdUa:-O-_9K6yCNeeSdOyWdUb:b-1oirx6) ([raw file](https://github.com/starkware-libs/mempool/blob/dfde5b0a363d6ab6bc011dfc688ea7be880cdf17/crates/tests-integration/src/state_reader.rs#L41)):*
> ```XML
> pub async fn rpc_test_state_reader_factory() -> RpcStateReaderFactory {
>     const RPC_SPEC_VERION: &str = "V0_7";
>     const JSON_RPC_VERSION: &str = "2.0";
> ```

@Yael-Starkware The code is the same except for these consts.

Do you have any objection for them being inside the function?



_Code quote:_
```XML
    const RPC_SPEC_VERION: &str = "V0_7";
    const JSON_RPC_VERSION: &str = "2.0";
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/249#-O-_9K6yCNeeSdOyWdUa:-O-_gXYJEcbGwOW_Zc8B:bwqh93j) ([raw file](https://github.com/starkware-libs/mempool/blob/dfde5b0a363d6ab6bc011dfc688ea7be880cdf17/crates/tests-integration/src/state_reader.rs#L41)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@Yael-Starkware The code is the same except for these consts.

Do you have any objection for them being inside the function?
</blockquote></details>

no objection

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/tests-integration/src/state_reader.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/249#-O-_9K6yCNeeSdOyWdUa:-O-_oh2T9rV6bYhxn8tV:bp0ujhp) ([raw file](https://github.com/starkware-libs/mempool/blob/dfde5b0a363d6ab6bc011dfc688ea7be880cdf17/crates/tests-integration/src/state_reader.rs#L41)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

no objection
</blockquote></details>

Oh whoops forgot to write about that, so no logical changes except that const move :grimacing:

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by giladchase** [comment]
✓ Commit merged in pull request [#250](https://github.com/starkware-libs/mempool/pull/250)

**Pull request closed without merging**
