### PR TITLE
feat: use gateway config in the gateway

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/138?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#138** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/138?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/138#-Ny-iQ6P12v7NLSg1USZ:-Ny-iQ6P12v7NLSg1US_:b-eq8sb7) (no related file):*
Q - Why the `gatewayConfig` is not defined in `gateway.rs` file?

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/138#-Ny-iQ6P12v7NLSg1USZ:-Ny0BzjnD9uVg52aCjp3:bfravm3) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Q - Why the `gatewayConfig` is not defined in `gateway.rs` file?
</blockquote></details>

All config structs are now defined in a file called `config.rs`.

___

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138#-:-Ny0jOwa1rgUv0fXfHhs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138#-:-NyV0v9r7mjFUvvtN724:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by ArniStarkware** [comment]
### Merge activity

* **May 22, 8:46 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/138).

**Pull request merged**
