### PR TITLE
feat(gateway): add fee non zero validation

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/12)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/12)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/transaction_validator.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/12#-Ntkav1WCuG47lz2WVBL:-Ntkav1WCuG47lz2WVBM:bttxeph) ([raw file](https://github.com/starkware-libs/mempool/blob/952c4dd200b27526495c620940fdb40dd566f204/crates/gateway/src/transaction_validator.rs#L35)):*
> ```XML
>     pub max_allowed_tx_version: TransactionVersion,
> 
>     pub enforce_fee: bool,
> ```

I think in Python we only use this flag for testing.



_Code quote:_
```XML
enforce_fee
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/12)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/transaction_validator.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/12#-Ntkav1WCuG47lz2WVBL:-NtlOTqV2qz1b9Lb44Ug:b4qstoy) ([raw file](https://github.com/starkware-libs/mempool/blob/952c4dd200b27526495c620940fdb40dd566f204/crates/gateway/src/transaction_validator.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think in Python we only use this flag for testing.
</blockquote></details>

Removed. If it is required, we will add it later.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/12)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/gateway/src/starknet_api_utils.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/12#-Nu43Q1_0NDUMUlov00Z:-Nu43Q1_0NDUMUlov00_:b-bn6ejs) ([raw file](https://github.com/starkware-libs/mempool/blob/f7972ff81bef57f9112048f32bf664fc0008f271/crates/gateway/src/starknet_api_utils.rs#L57)):*
> ```XML
> 
> impl TransactionParametersExt for Transaction {
>     fn max_fee(&self) -> StarknetApiTransactionResult<Fee> {
> ```

I think it is getting too complicated with macros and many trait extensions.

Consider the following:

```
let resource_bounds = match self {
  StarknetApiTransaction::Declare(
                starknet_api::transaction::DeclareTransaction::V0(_)
                | starknet_api::transaction::DeclareTransaction::V1(_)
                | starknet_api::transaction::DeclareTransaction::V2(_),
            ) => unimplemented!(),
  Transaction::Declare(DeclareTransaction::V3(tx)) => tx.resource_bounds,
  ...
}

... compute max_fee from resource_bounds ...

Ok(max_fee)
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/12)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/starknet_api_utils.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/12#-Nu43Q1_0NDUMUlov00Z:-NuIoqMb0zaEuTgLf08j:b7mnd0y) ([raw file](https://github.com/starkware-libs/mempool/blob/f7972ff81bef57f9112048f32bf664fc0008f271/crates/gateway/src/starknet_api_utils.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think it is getting too complicated with macros and many trait extensions.

Consider the following:

```
let resource_bounds = match self {
  StarknetApiTransaction::Declare(
                starknet_api::transaction::DeclareTransaction::V0(_)
                | starknet_api::transaction::DeclareTransaction::V1(_)
                | starknet_api::transaction::DeclareTransaction::V2(_),
            ) => unimplemented!(),
  Transaction::Declare(DeclareTransaction::V3(tx)) => tx.resource_bounds,
  ...
}

... compute max_fee from resource_bounds ...

Ok(max_fee)
```
</blockquote></details>

I reordered the PRs.
(This PR sitis on top of #15 now).

Now, the macro infrastructure is cleaner, smaller and clearer.

**Comment by ArniStarkware** [comment]
replaced with: #29

**Pull request closed without merging**
