### PR TITLE
feat: add compile sierra to casm util

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/24)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/build.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/mempool/24#-NurZpvf7rfe37e5n2H8:-NurZpvg3kZzSlDArwLY:br774q7) ([raw file](https://github.com/starkware-libs/mempool/blob/682b35fd2d2e7a296433d87ace55bf0ce8ccb70e/crates/gateway/build.rs#L13)):*
> ```XML
>     command.arg("--root");
>     command.arg("tmp/cargo"); // TODO: DOn't dup the path.
>     command.arg("starknet-sierra-compile");
> ```

This causes the following files to be created:

The compiler exe: `crates/gateway/tmp/cargo/bin/starknet-sierra-compile`
Files related to cargo: `crates/gateway/tmp/cargo/.crates.toml`, `crates/gateway/tmp/cargo/.crates2.json`



_Code quote:_
```XML
    let mut command = Command::new("cargo");
    command.arg("install");
    command.arg("--root");
    command.arg("tmp/cargo"); // TODO: DOn't dup the path.
    command.arg("starknet-sierra-compile");
```

**Comment by ArniStarkware** [comment]
This replaces: https://github.com/starkware-libs/mempool/pull/16

**Review by giladchase — COMMENTED** [review]
Great! Some thoughts for future reference:

1) **Git Submodule Alternative**: Using git submodule, which is basically "cloning cairo repo in a specific commit hash/tag and putting it in some directory inside the mempool repo". This is less hackish, and will make versioning and caching simpler (see comments below).
This will change the build.rs file into "`cargo build` in the submodule dir", which will generate the executable inside a dedicated `target/` directory, inside the submodule dir. Changing the version will be just changing the tag that the submodule is checked-out in.
However, this solution might be overkill.

2) **Binary dependencies** is an [unstable feature in nightly rust](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies) ATM, and from looking at the [tracking issue](https://github.com/rust-lang/cargo/issues/9096), it has a bunch of stabilization issues and won't be stabilized anytime soon. So this PR's workaround approach will stay relevant for the foreseeable future.
If we want to find better workarounds, we can always scrape the mentions of the tracking issue for other repos that mention it while merging their own workarounds.

3)  **Separate Crate for Logic**: Ideally, moving this build logic to a separate crate would be preferable for organization. However, this complicates access to the generated executable, making the current module-based approach more practical for now.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/24#-:-NuwU3t656ivLDTzEjaX:boaxrml)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/build.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/mempool/24#-NuwKsiGCotupQ6AwdYd:-NuwKsiH-R8Zrdy39xbk:b-y3jx1s) ([raw file](https://github.com/starkware-libs/mempool/blob/682b35fd2d2e7a296433d87ace55bf0ce8ccb70e/crates/gateway/build.rs#L12)):*
> ```XML
>     command.arg("install");
>     command.arg("--root");
>     command.arg("tmp/cargo"); // TODO: DOn't dup the path.
> ```

Suggestion uses the location that build.rs output is expected to be, see first sentence [here](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script).

The main benefit of this (other than being the canonical location) is that it caches the result since it places it inside the `target` directory.

However, now we need to deal with cache invalidation.
I naive way of doing this that won't bug us too much is to add:
```rust
println!("cargo:rerun-if-changed=path/to/Cargo.lock");
// Add more of these as desired, like maybe one for changes in build.rs itself.
```
[as the first line](https://doc.rust-lang.org/cargo/reference/build-scripts.html#build-scripts) in the `main` function.
This is cargo magic that will re-trigger build.rs whenever Cargo.lock changes, with the logic being that this is kind of a dependency, so let's compile it along with the rest of the dependency changes when they appear.



_Suggestion:_
```XML
    let out_dir = env::var("OUT_DIR").unwrap();
    let mut command = Command::new("cargo");
    command.arg("install");
    command.arg("--root");
    command.arg(&out_dir); // TODO: DOn't dup the path.
```
___
*[`crates/gateway/build.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/mempool/24#-NuwPnO65JaZTwUSziIt:-NuwPnO7-XhBhg5gsUYr:bhiecxq) ([raw file](https://github.com/starkware-libs/mempool/blob/682b35fd2d2e7a296433d87ace55bf0ce8ccb70e/crates/gateway/build.rs#L13)):*
> ```XML
>     command.arg("--root");
>     command.arg("tmp/cargo"); // TODO: DOn't dup the path.
>     command.arg("starknet-sierra-compile");
> ```

There is still the issue of versioning.

This currently installs the latest version, and it isn't clear what version that is, and when should it be updated.

The obvious naive solution is to track a hardcoded version in this file, but that introduces coupling with the version in the Cargo.toml which __will__ break at some point.

However, an even *uglier* hack that eliminates this coupling is to parse the cargo.toml and look for the version there :smiling_face_with_tear:.
rustc-perf [used a variation of this hack](https://github.com/rust-lang/rustc-perf/blob/master/site/build.rs#L53) (but not for version tracking I think) so you can use that for reference.

If we go along with this hack, we might be able to tweak our cache invalidation of this file (see previous comments) to be version sensitive.

The place in cargo.toml that will list the dependedcy can be [[build-dependencies]](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#build-dependencies), which are deps available solely for bjuild.rs.



_Code quote:_
```XML
command.arg("starknet-sierra-compile")
```
___
*[`crates/gateway/src/compiler/account_faulty.sierra.json` line 1 at r2](https://reviewable.io/reviews/starkware-libs/mempool/24#-NuwsP5Q7R3OhaYPkumQ:-NuwsP5Q7R3OhaYPkumR:bfualqk) ([raw file](https://github.com/starkware-libs/mempool/blob/682b35fd2d2e7a296433d87ace55bf0ce8ccb70e/crates/gateway/src/compiler/account_faulty.sierra.json#L1)):*
> ```JSON
> {
> ```

Move to `crates/gateway/tests/fixtures/`.
This is where cargo expects [test things to be](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html), specifically integration tests, but the main point is that it detaches it from the source code of the crate, and is compiled in as a separate anonymous crate.X

**Comment by ArniStarkware** [comment]
This is replaced by: #35

**Pull request closed without merging**
