### PR TITLE
chore: mark rpc state reader config create for testing for cfg

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/141#-NyErTlY8MuTbxfDZvzD:-NyErTlY8MuTbxfDZvzE:b-5cc9ja) ([raw file](https://github.com/starkware-libs/mempool/blob/f139c3fdc202c2d5ca98ada5426d86cb2fdcbc10/crates/gateway/src/config.rs#L85)):*
> ```XML
> }
> 
> #[cfg(any(feature = "testing", test))]
> ```

Need to also define the feature itself, plz add to Cargo.toml:
```rust
[features]
testing = []
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/src/config.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/141#-NyErTlY8MuTbxfDZvzD:-NyFQ1xAE6HeP_u__hQO:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f139c3fdc202c2d5ca98ada5426d86cb2fdcbc10/crates/gateway/src/config.rs#L85)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Need to also define the feature itself, plz add to Cargo.toml:
```rust
[features]
testing = []
```
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/src/config.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/141#-NyErTlY8MuTbxfDZvzD:-NyFQ5Rq1qllu1tBzbdS:b-i9m8mg) ([raw file](https://github.com/starkware-libs/mempool/blob/f139c3fdc202c2d5ca98ada5426d86cb2fdcbc10/crates/gateway/src/config.rs#L85)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Or did you mean the crate's `toml`?

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141#-:-NyFVIrb6X--ZNWCmZbe:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`crates/gateway/src/config.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/141#-NyErTlY8MuTbxfDZvzD:-NyFVE--4yHxYvQQ9Dev:bm2cdor) ([raw file](https://github.com/starkware-libs/mempool/blob/f139c3fdc202c2d5ca98ada5426d86cb2fdcbc10/crates/gateway/src/config.rs#L85)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Or did you mean the crate's `toml`?
</blockquote></details>

Nope what you did is good :muscle:

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
