### PR TITLE
chore: add the gateway compiler to appstate

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/391?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#384** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/384?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#298** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#391** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/391?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/383?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#392](https://github.com/starkware-libs/mempool/pull/392) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/392?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391#-:-O1GEQVy-l19V_aLkgEE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/391#-O1Vmuqi53FcBYAE9wYn:-O1Vmuqi53FcBYAE9wYo:bnh6k0y) ([raw file](https://github.com/starkware-libs/mempool/blob/9152413c94c53629bee4d46da0ee4e59eb8ce0dc/crates/gateway/src/gateway.rs#L57)):*
> ```XML
>             }),
>             state_reader_factory,
>             gateway_compiler: GatewayCompiler { config: config.compiler_config.clone() },
> ```

Please accept the compiler as an argument to `new`.
(as discussed before, we also want to do this for the stateless/stateful validators).



_Code quote:_
```XML
gateway_compiler: GatewayCompiler { config: config.compiler_config.clone() },
```
___
*[`crates/gateway/src/gateway_test.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/mempool/391#-O1Vo-tvD9-xeEUTyyTf:-O1Vo-tw6JeLhRnsvIbx:bf7du60) ([raw file](https://github.com/starkware-libs/mempool/blob/9152413c94c53629bee4d46da0ee4e59eb8ce0dc/crates/gateway/src/gateway_test.rs#L117)):*
> ```XML
>     let optional_class_info = match &external_tx {
>         RPCTransaction::Declare(declare_tx) => Some(
>             GatewayCompiler { config: GatewayCompilerConfig {} }
> ```

Use the AppState's compiler.



_Code quote:_
```XML
GatewayCompiler { config: GatewayCompilerConfig {} }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/391#-O1Vmuqi53FcBYAE9wYn:-O1VuWp61dVdNKEbCdoW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6265f8739a47721a27757689a09f9d409e912890/crates/gateway/src/gateway.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please accept the compiler as an argument to `new`.
(as discussed before, we also want to do this for the stateless/stateful validators).
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/mempool/391#-O1Vo-tvD9-xeEUTyyTf:-O1VxSYmAHtXC1-0wYmS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6265f8739a47721a27757689a09f9d409e912890/crates/gateway/src/gateway_test.rs#L117)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Use the AppState's compiler.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391#-:-O1k9QmN9mFkHtXRzmGu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Jul 14, 7:12 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/391).

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
