### PR TITLE
feat: check that the compiled class hash matches the supplied class

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/246?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#246** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/246?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/234?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#235](https://github.com/starkware-libs/mempool/pull/235) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: 0 of 6 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/246#-O-l-57e9mZCSOvxb5cE:-O-l-57e9mZCSOvxb5cF:b-pd2d7q) (no related file):*
Add unit test for this part. 

___

**Review by ArniStarkware — COMMENTED** [review]
In this PR, we enforce the compiled class hash supplied by the transaction matchs the computed compiled class hash.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246#-:-O0Ef2oD1EMaL0LLrewJ:bw6hf0r)* status: 0 of 9 files reviewed, all discussions resolved

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0Nthm4BHM0OeP325p9:-O0Nthm4BHM0OeP325pA:b-10gzge) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L133)):*
> ```XML
>         _ => panic!("Invalid transaction type"),
>     };
>     let RPCDeclareTransaction::V3(declare_tx_v3) = &declare_tx;
> ```

Can you match the downcast code to the previous function? 



_Code quote:_
```XML
    let declare_tx = match declare_tx() {
        RPCTransaction::Declare(declare_tx) => declare_tx,
        _ => panic!("Invalid transaction type"),
    };
    let RPCDeclareTransaction::V3(declare_tx_v3) = &declare_tx;
```
___
*[`crates/gateway/src/gateway_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0NuR475Ujf4OBgIIQv:-O0NuR475Ujf4OBgIIQw:b-rcw332) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L141)):*
> ```XML
>         Ok(class_info)
>         if (
>             matches!(class_info.contract_class(), ContractClass::V1(_))
> ```

I guess there is no easy way to verify the result of the compilation, 
but what do you check here? only the cairo version?
___
*[`crates/gateway/src/gateway_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0NuFfT9aQFHDSRTDOJ:-O0NuFfT9aQFHDSRTDOK:bpwb5vl) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L144)):*
> ```XML
>             && class_info.sierra_program_length() == contract_class.sierra_program.len()
>             && class_info.abi_length() == contract_class.abi.len()
>         )
> ```

Can you also check that the supplied compiled class hash matches the computed compiled class hash?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0Nthm4BHM0OeP325p9:-O0O0z-D1DzWUJZbz4wi:b-5jk2k9) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L133)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you match the downcast code to the previous function?
</blockquote></details>

The difference is that here, we want to use `declare_tx` as the input of the function `compile_contract_class`.

It is more direct here. Otherwise, I will unwrap a `RPCDeclareTransaction` and then wrap the same value again. 

If anything - I would change the previous test to get a mutable `RPCDeclareTransaction` - mutate it and use it in the test - but I am unsure how.
___
*[`crates/gateway/src/gateway_test.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0NuR475Ujf4OBgIIQv:-O0O-LcJ0zGB5h1R3fQc:b-lj9igp) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L141)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I guess there is no easy way to verify the result of the compilation, 
but what do you check here? only the cairo version?
</blockquote></details>

First, we check that the compilation was successful. Other than that, yes, we check the Cairo version. 
___
*[`crates/gateway/src/gateway_test.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0NuFfT9aQFHDSRTDOJ:-O0O0X9S7NI7XB8S7xrO:b-esc811) ([raw file](https://github.com/starkware-libs/mempool/blob/bad16441093c9d9f3c838c3a34b6dce0f7ae8962/crates/gateway/src/gateway_test.rs#L144)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you also check that the supplied compiled class hash matches the computed compiled class hash?
</blockquote></details>

It is checked inside the function `compile_contract_class`. Testing it here is will just repeat this logic. This subject is being tested in `test_compile_contract_class_failure`.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 112 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0ORF7Q77nYwolzl3E_:-O0ORF7Q77nYwolzl3Ea:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L112)):*
> ```XML
>         RPCTransaction::Declare(RPCDeclareTransaction::V3(declare_tx)) => declare_tx,
>         _ => panic!("Invalid transaction type"),
>     };
> ```





_Suggestion:_
```XML
    let tx = assert_matches!(
        declare_tx(),
        RPCTransaction::Declare(RPCDeclareTransaction::V3(tx)) => tx
    );
 
```
___
*[`crates/gateway/src/gateway_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OSH1N6r3oYKbpjLEN:-O0OSH1OBFLoZlNqdKP-:b2nreh6) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L132)):*
> ```XML
>         RPCTransaction::Declare(declare_tx) => declare_tx,
>         _ => panic!("Invalid transaction type"),
>     };
> ```

Same as above.



_Code quote:_
```XML
    let declare_tx = match declare_tx() {
        RPCTransaction::Declare(declare_tx) => declare_tx,
        _ => panic!("Invalid transaction type"),
    };
```
___
*[`crates/gateway/src/gateway_test.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OSVyc9q1arz7bvawR:-O0OSVyc9q1arz7bvawS:bu3ybjx) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L144)):*
> ```XML
>             && class_info.sierra_program_length() == contract_class.sierra_program.len()
>             && class_info.abi_length() == contract_class.abi.len()
>         )
> ```

Please separate to 3 different assert statements.



_Code quote:_
```XML
    assert_matches!(
        result,
        Ok(class_info)
        if (
            matches!(class_info.contract_class(), ContractClass::V1(_))
            && class_info.sierra_program_length() == contract_class.sierra_program.len()
            && class_info.abi_length() == contract_class.abi.len()
        )
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OTUB26UzfGASd7iKO:-O0OTUB39rfJsZqF7gR3:b-qn2ns8) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/stateful_transaction_validator_test.rs#L49)):*
> ```XML
>     local_test_state_reader_factory(CairoVersion::Cairo1, false),
>     Ok(TransactionHash(StarkFelt::try_from(
>         "0x02da54b89e00d2e201f8e3ed2bcc715a69e89aefdce88aff2d2facb8dec55c0a"
> ```

Why did it change?



_Code quote:_
```XML
0x02da54b89e00d2e201f8e3ed2bcc715a69e89aefdce88aff2d2facb8dec55c0a
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 112 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0ORF7Q77nYwolzl3E_:-O0OwoCR5eOQpGrKdrAx:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L112)):*
> ```XML
>         RPCTransaction::Declare(RPCDeclareTransaction::V3(declare_tx)) => declare_tx,
>         _ => panic!("Invalid transaction type"),
>     };
> ```

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OSH1N6r3oYKbpjLEN:-O0OwoiZ2NSDJis42yoz:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L132)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OSVyc9q1arz7bvawR:-O0OxSqF8OzMyOjYqS_C:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/gateway_test.rs#L144)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please separate to 3 different assert statements.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0OTUB26UzfGASd7iKO:-O0OrDP99uJVZANhVJVl:b-xx6nzh) ([raw file](https://github.com/starkware-libs/mempool/blob/4e760dfbf89f227dccbdbe5e556ea1f9674005f9/crates/gateway/src/stateful_transaction_validator_test.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did it change?
</blockquote></details>

compiled_class_hash changed from `CompiledClassHash::Default()`.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 3 of 8 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 165 at r6](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0cEx0bCkRLW6TgWAaC:-O0cEx0bCkRLW6TgWAaD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f8db27cf4d1053e07e1f8dc5e11253910fd04a3f/crates/gateway/src/gateway_test.rs#L165)):*
> ```XML
>         result,
>         Ok(class_info) => class_info
>     );
> ```





_Suggestion:_
```XML
    let class_info = compile_contract_class(&declare_tx).unwrap();
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 165 at r6](https://reviewable.io/reviews/starkware-libs/mempool/246#-O0cEx0bCkRLW6TgWAaC:-O0cSXfY6CwRMr90VZEJ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/dffdc5af51d85c9103c8492f4da6f37d042f0cdc/crates/gateway/src/gateway_test.rs#L165)):*
> ```XML
>         result,
>         Ok(class_info) => class_info
>     );
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246#-:-O0dPyp2B_q54rnVsACY:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/246)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
