### PR TITLE
feat: declare post compilation prime validation

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/297)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/297?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#297** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/297?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#296** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/296?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#246** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/246?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#235** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/234?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/297)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/mempool/297#-O0NxbK76Xh3FHC3NNjD:-O0NxbK76Xh3FHC3NNjE:bvkcvyx) ([raw file](https://github.com/starkware-libs/mempool/blob/9ee212a50d065dadb40fe339459c7cd671199e9d/crates/gateway/src/gateway.rs#L227)):*
> ```XML
>         return Err(GatewayError::InvalidPrime { prime, expected_prime });
>     }
> ```

Can you explain what this check is? what is the meaning of prime here?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/297)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/mempool/297#-O0NzU0r001lQHvc0Nov:-O0ON1Dh2mIHDKTBQff8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9ee212a50d065dadb40fe339459c7cd671199e9d/crates/gateway/src/gateway.rs#L212)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/mempool/297#-O0NxbK76Xh3FHC3NNjD:-O0n_H-UCcovptmho4UF:bs4qdor) ([raw file](https://github.com/starkware-libs/mempool/blob/9ee212a50d065dadb40fe339459c7cd671199e9d/crates/gateway/src/gateway.rs#L227)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you explain what this check is? what is the meaning of prime here?
</blockquote></details>

This was first referenced here: https://github.com/starkware-industries/starkware/pull/17777

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/mempool/297#-O0NxbK76Xh3FHC3NNjD:-O0ndOoZDT2lBYC69GmT:bt06fo0) ([raw file](https://github.com/starkware-libs/mempool/blob/9ee212a50d065dadb40fe339459c7cd671199e9d/crates/gateway/src/gateway.rs#L227)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This was first referenced here: https://github.com/starkware-industries/starkware/pull/17777
</blockquote></details>

One step back. This validation was copied from the Python code.

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/297)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compilation.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/mempool/297#-O1BTPse5zbguOMTti-y:-O1BTPse5zbguOMTti-z:b-8ch0no) ([raw file](https://github.com/starkware-libs/mempool/blob/151c4c5df1b4f90bb51dc7be73720d19ea5b2669/crates/gateway/src/compilation.rs#L96)):*
> ```XML
>     let prime = contract_class.prime.clone();
>     let expected_prime =
>         BigUint::from_str_radix(&PRIME_STR[2..], 16).expect("Error parsing field prime.");
> ```

Can this be a constant?



_Code quote:_
```XML
BigUint::from_str_radix(&PRIME_STR[2..], 16).expect("Error parsing field prime.");
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/297)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/mempool/297#-O0NxbK76Xh3FHC3NNjD:-O1vFhEe8iQpvzUkRfzP:bvfc4y6) ([raw file](https://github.com/starkware-libs/mempool/blob/9ee212a50d065dadb40fe339459c7cd671199e9d/crates/gateway/src/gateway.rs#L227)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

One step back. This validation was copied from the Python code.
</blockquote></details>

@Yoni-Starkware agrees this validation is no longer needed. See: https://starkwareindustries.slack.com/archives/C03D7FDE1EZ/p1721116020563769

**Comment by ArniStarkware** [comment]
This validation is not needed for Cairo 1 contracts.

The prime used during the compilation into CASM is independent of the transaction.

**Pull request closed without merging**
