### PR TITLE
test: add cairo0 to integration test

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/273)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/273)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0EEgRHAXRoIU0Flov5:-O0EEgRHAXRoIU0Flov6:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L9)):*
> ```XML
>     let mut mock_running_system = IntegrationTestSetup::new().await;
> 
>     let mut expected_tx_hash = Vec::new();
> ```





_Suggestion:_
```XML
expected_tx_hashes
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0ECy9z7G_cnc_tPMVa:-O0ECy9z7G_cnc_tPMVb:b-xx1c54) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L15)):*
> ```XML
>         .push(mock_running_system.assert_add_tx_success(&invoke_tx(CairoVersion::Cairo1)).await);
>  
>     let mempool_txs = mock_running_system.get_txs(4).await;
> ```

Why 4?



_Code quote:_
```XML
4
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0EDfCNApdW7bjCFN7w:-O0EDfCNApdW7bjCFN7x:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L19)):*
> ```XML
>     expected_tx_hash.iter().for_each(|tx_hash| {
>         assert!(mempool_txs.iter().any(|tx| tx.tx_hash == *tx_hash), "Did not get tx_hash: {:?} from mempool", tx_hash);
>     });
> ```





_Suggestion:_
```XML
    actual_tx_hashes = mempool_txs.iter().map(|tx| tx.tx_hash).collect();
    assert_eq!(actual_tx_hashes, expected_tx_hashes);
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/273)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0EEgRHAXRoIU0Flov5:-O0EYsIM4b-O-yh5AJsr:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L9)):*
> ```XML
>     let mut mock_running_system = IntegrationTestSetup::new().await;
> 
>     let mut expected_tx_hash = Vec::new();
> ```

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0ECy9z7G_cnc_tPMVa:-O0E_t_E1X42WC9H-MS2:b-9f22vm) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L15)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why 4?
</blockquote></details>

reduced to 3 to be consistent with the previous logic this test had.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/273#-O0EDfCNApdW7bjCFN7w:-O0E_dlkBxa_wzxlBe9N:bqnroh8) ([raw file](https://github.com/starkware-libs/mempool/blob/e2adcf5ea77dd7512f878d809c9cc425a43d0f55/crates/tests-integration/tests/end_to_end_test.rs#L19)):*
> ```XML
>     expected_tx_hash.iter().for_each(|tx_hash| {
>         assert!(mempool_txs.iter().any(|tx| tx.tx_hash == *tx_hash), "Did not get tx_hash: {:?} from mempool", tx_hash);
>     });
> ```

Done.
also added sorting of the Vectors in case that the mempool txs are received in different order.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/273#-:-O0NzcJr5rNVc_SP7g09:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/273#-:-O0O3lNS9qkg1Chdj_h9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
