### PR TITLE
feat: implementing ComponentRunner for the gateway

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #339
- #311
- #355 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355#-:-O0x_sut2ioqZWRszflq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/355#-O0xj6zt6LNiyu7ZTPiU:-O0xoT5R2DaVlEbfsXwe:b-kkb01d) ([raw file](https://github.com/starkware-libs/mempool/blob/fefc808f76e5d3a3fba256fb0a1875b91aacb42e/crates/gateway/src/gateway.rs#L74)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If you think it is an issue, add a to-do (for someone on my team, say myself) to fix it.
</blockquote></details>

from F2f. Please add a todo on my name.
___
*[`crates/gateway/src/gateway.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/mempool/355#-O0xjssu6nC9r_F-4yD5:-O0xoCC06_6uXPHPIT6z:b-vx2kb) ([raw file](https://github.com/starkware-libs/mempool/blob/fefc808f76e5d3a3fba256fb0a1875b91aacb42e/crates/gateway/src/gateway.rs#L148)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

A question about `Rust` / design (probably out of scope for this PR).

Does the fact that `start` gets a reference to `mut self` means a single `ComponentRunner` may run many instances of the component?
</blockquote></details>

From F2F:

The important thing here is the `mut`, not the `ref` (`&`).
It is only logical that a runner would like to mutate itself.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/355#-O0xw7oJ8tHub-oMqb7S:-O0xw7oJ8tHub-oMqb7T:beorx7d) ([raw file](https://github.com/starkware-libs/mempool/blob/fefc808f76e5d3a3fba256fb0a1875b91aacb42e/crates/gateway/src/gateway.rs#L74)):*
> ```XML
>             .route("/is_alive", get(is_alive))
>             .route("/add_tx", post(add_tx))
>             .with_state(self.app_state.clone())
> ```

I think dereferencing should work here.



_Suggestion:_
```XML
*self.app_state
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355#-:-O1BQgXVBSM7MHWMUxKu:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/355#-O0xw7oJ8tHub-oMqb7S:-O0y4WZ00ZYnU1Wu2jiV:b-bv4nm) ([raw file](https://github.com/starkware-libs/mempool/blob/fefc808f76e5d3a3fba256fb0a1875b91aacb42e/crates/gateway/src/gateway.rs#L74)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think dereferencing should work here.
</blockquote></details>

I tried it not compiling.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Dismissed @dafnamatsry from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355#-:-O1BwoMs3FTHfITewNEc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#339](https://github.com/starkware-libs/mempool/pull/339)

**Pull request closed without merging**
