### PR TITLE
chore: add blockifier feature testing to main toml

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/484)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/484)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`Cargo.toml` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/484#-O1vHmHQ8wUHiPlXf07y:-O1vHmHR6XQ6yVNR0fKV:b-5xleiz) ([raw file](https://github.com/starkware-libs/mempool/blob/712f49854bd4bb92d274039be3f052737e041d26/Cargo.toml#L38)):*
> ```TOML
> axum = "0.6.12"
> bincode = "1.3.3"
> blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "32191d41", features = ["testing"]}
> ```

WDYT about reverting this change, and adding the `features = ["testing"]` flag to the requiring package? 

IIUC this avoids including the `testing` feature for the entire project, and only adds it for the whichever package needs it. If so, please also revert the change for `gateway`.



_Code quote:_
```TOML
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "32191d41", features = ["testing"]}
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/484#-:-O1vJ7Ki2IokA-gZywKQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/484)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/484#-O1vHmHQ8wUHiPlXf07y:-O1vIn5i5yD_PfYcLLBc:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/712f49854bd4bb92d274039be3f052737e041d26/Cargo.toml#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYT about reverting this change, and adding the `features = ["testing"]` flag to the requiring package? 

IIUC this avoids including the `testing` feature for the entire project, and only adds it for the whichever package needs it. If so, please also revert the change for `gateway`.
</blockquote></details>

done

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
