### PR TITLE
feat: stateless validator add signature len validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/mempool/53#-Nvfty-e1Bu4Vigr-1Fx:-Nvfty-e1Bu4Vigr-1Fy:b2mngun) ([raw file](https://github.com/starkware-libs/mempool/blob/709839004a45e5e9bb7d573729a5538f294337a2/crates/gateway/src/stateless_transaction_validator.rs#L101)):*
> ```XML
>             }
>             ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => &tx.signature,
>         };
> ```

consider extracting this logic to a function in utils.rs in order to hide the messy ExternalTransaction structure.
and then replacing by tx.signature()



_Code quote:_
```XML
        let signature = match tx {
            ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => &tx.signature,

            ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(tx)) => {
                &tx.signature
            }
            ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => &tx.signature,
        };
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/mempool/53#-Nvfty-e1Bu4Vigr-1Fx:-Nvfvbj44DuzldXJ1dnx:bdrsm82) ([raw file](https://github.com/starkware-libs/mempool/blob/709839004a45e5e9bb7d573729a5538f294337a2/crates/gateway/src/stateless_transaction_validator.rs#L101)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

consider extracting this logic to a function in utils.rs in order to hide the messy ExternalTransaction structure.
and then replacing by tx.signature()
</blockquote></details>

The same is true for `calldata` and `resource_bounds` (Maybe only for `resource_bounds`, as the `calldata` option differs in at least two ways).
In any case, I think this should not be blocking.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/mempool/53#-Nvfty-e1Bu4Vigr-1Fx:-NvfzzR62QNnqpsRd6jn:bq91ew4) ([raw file](https://github.com/starkware-libs/mempool/blob/709839004a45e5e9bb7d573729a5538f294337a2/crates/gateway/src/stateless_transaction_validator.rs#L101)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The same is true for `calldata` and `resource_bounds` (Maybe only for `resource_bounds`, as the `calldata` option differs in at least two ways).
In any case, I think this should not be blocking.
</blockquote></details>

Here is the PR: #58

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)* status: 3 of 4 files reviewed, all discussions resolved

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/mempool/53#-NvkefkcCy3pqY0lOPL0:-NvkefkcCy3pqY0lOPL1:bb7kry6) ([raw file](https://github.com/starkware-libs/mempool/blob/ff45a6f19ead276c210492f47886910c4f8b600b/crates/gateway/src/stateless_transaction_validator.rs#L102)):*
> ```XML
>         let signature = match tx {
>             ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => &tx.signature,
> ```

Remove empty line
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/mempool/53#-NvkfukE3PXJxjGX4Ezj:-NvkfukE3PXJxjGX4Ezk:b-4o8z1u) ([raw file](https://github.com/starkware-libs/mempool/blob/ff45a6f19ead276c210492f47886910c4f8b600b/crates/gateway/src/stateless_transaction_validator_test.rs#L133)):*
> ```XML
>     Err(StatelessTransactionValidatorError::SignatureTooLong { signature_length: 2, max_signature_length: 1 })
> 
> )]
> ```

A suggestion to maybe organize the tests a bit better (it doesn't have to be in this PR).

There are several tests that repeat themselves for the different types of transactions, I think it would be better if we extract each to its own test. For example:

``` 
fn test_signature_too_long(
    #[case] tx: ExternalTransaction,
) {
    let tx_validator = StatelessTransactionValidator { DEFAULT_VALIDATOR_CONFIG_FOR_TESTING };

    tx.signature = TransactionSignature(vec![StarkFelt::from_u128(1), StarkFelt::from_u128(2)];
    let result = tx_validator.validate(&tx);

    assert_eq!(result, Err(StatelessTransactionValidatorError::SignatureTooLong { signature_length: 2, max_signature_length: 1 }));
}
```




_Code quote:_
```XML
#[case::declare_signature_too_long(
    DEFAULT_VALIDATOR_CONFIG_FOR_TESTING,
    external_declare_tx_for_testing(
        non_zero_resource_bounds_mapping(),
        TransactionSignature(vec![StarkFelt::from_u128(1), StarkFelt::from_u128(2)]),
    ),
    Err(StatelessTransactionValidatorError::SignatureTooLong { signature_length: 2, max_signature_length: 1 })

)]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/mempool/53#-NvkefkcCy3pqY0lOPL0:-Nvl3IsBBFgXLrTojwYL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ff45a6f19ead276c210492f47886910c4f8b600b/crates/gateway/src/stateless_transaction_validator.rs#L102)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Remove empty line
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/mempool/53#-NvkfukE3PXJxjGX4Ezj:-NvlG39SEx8y49_bCRpc:bpckf24) ([raw file](https://github.com/starkware-libs/mempool/blob/ff45a6f19ead276c210492f47886910c4f8b600b/crates/gateway/src/stateless_transaction_validator_test.rs#L133)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

A suggestion to maybe organize the tests a bit better (it doesn't have to be in this PR).

There are several tests that repeat themselves for the different types of transactions, I think it would be better if we extract each to its own test. For example:

``` 
fn test_signature_too_long(
    #[case] tx: ExternalTransaction,
) {
    let tx_validator = StatelessTransactionValidator { DEFAULT_VALIDATOR_CONFIG_FOR_TESTING };

    tx.signature = TransactionSignature(vec![StarkFelt::from_u128(1), StarkFelt::from_u128(2)];
    let result = tx_validator.validate(&tx);

    assert_eq!(result, Err(StatelessTransactionValidatorError::SignatureTooLong { signature_length: 2, max_signature_length: 1 }));
}
```

</blockquote></details>

See PR: #61

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/53#-:-NvzbygiEIwRP5fXf_x7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
