### PR TITLE
feat: add config with papyrus_config

### PR DESCRIPTION
**Pull request by lev-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucbVsr3G-fD-Yb1Sd_:-NucbVsr3G-fD-Yb1Sda:byb8kk) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L38)):*
> ```XML
> const DEFAULT_BAD_CONFIG_PATH: &str = "./src/json_files_for_testing/bad_gateway_config.json";
> const DEFAULT_BAD_ADDRESS_CONFIG_PATH: &str =
>     "./src/json_files_for_testing/bad_gateway_address_config.json";
> ```

Please:
1. Define the path to the directory as a constant; use it to define the path to the specific files.
2. I personally don't like the names "good" and "bad". I prefer the "good" files will be just the file name, and the "bad" ones will be "erroneous". If you disagree let's discuss. If not, please reflect that in the constant names as well.
3. 



_Code quote:_
```XML
const DEFAULT_GOOD_CONFIG_PATH: &str = "./src/json_files_for_testing/good_gateway_config.json";
const DEFAULT_BAD_CONFIG_PATH: &str = "./src/json_files_for_testing/bad_gateway_config.json";
const DEFAULT_BAD_ADDRESS_CONFIG_PATH: &str =
    "./src/json_files_for_testing/bad_gateway_address_config.json";
```
___
*[`crates/gateway/src/gateway_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nuccb7J1HPay_5pFrEd:-Nuccb7J1HPay_5pFrEe:bmp7up4) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L69)):*
> ```XML
>     let config_file = std::fs::File::open(Path::new(DEFAULT_BAD_ADDRESS_CONFIG_PATH)).unwrap();
>     let load_config =
>         load_and_process_config::<GatewayConfig>(config_file, Command::new(""), vec![]).unwrap();
> ```

Can these two be unified into a single function that takes the config name and returns its loaded value, that is, as a test utils func?
Furthermore, do we want such a config-name-to-loaded-config function as an actual (not test) util?



_Code quote:_
```XML
    let config_file = std::fs::File::open(Path::new(DEFAULT_BAD_ADDRESS_CONFIG_PATH)).unwrap();
    let load_config =
        load_and_process_config::<GatewayConfig>(config_file, Command::new(""), vec![]).unwrap();
```
___
*[`crates/gateway/src/gateway_test.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nucb6Fe3uNYdq6picdO:-Nucb6Ff-dehjQk--NyF:b-xkvk2d) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L77)):*
> ```XML
>         ),
>     }
> }
> ```

Please put these in a different test file, i.e., "gateway_config_test.rs".



_Code quote:_
```XML
#[test]
fn good_config_test() {
    // Read the good config file and validate it.
    let config = GatewayConfig::default();

    let config_file = File::open(Path::new(DEFAULT_GOOD_CONFIG_PATH)).unwrap();
    let load_config =
        load_and_process_config::<GatewayConfig>(config_file, Command::new(""), vec![]).unwrap();
    assert!(load_config.validate().is_ok());
    assert_eq!(load_config.bind_address, config.bind_address);
}

#[test]
fn bad_config_test() {
    // Read the config file with the bad field path and validate it.
    let config_file = std::fs::File::open(Path::new(DEFAULT_BAD_CONFIG_PATH)).unwrap();
    let load_config =
        load_and_process_config::<GatewayConfig>(config_file, Command::new(""), vec![]);
    match load_config {
        Ok(_) => panic!("Expected an error, but got a config."),
        Err(e) => assert_eq!(e.to_string(), "missing field `bind_address`".to_owned()),
    }
}

#[test]
fn bad_config_address_test() {
    // Read the config file with the bad bind_address values and validate it
    let config_file = std::fs::File::open(Path::new(DEFAULT_BAD_ADDRESS_CONFIG_PATH)).unwrap();
    let load_config =
        load_and_process_config::<GatewayConfig>(config_file, Command::new(""), vec![]).unwrap();
    match load_config.validate() {
        Ok(_) => panic!("Expected an error, but got a config."),
        Err(e) => assert_eq!(
            e.field_errors()["bind_address"][0].code,
            "Invalid Socket address.".to_owned()
        ),
    }
}
```
___
*[`crates/gateway/src/lib.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdP7Y1vjFhiUa8tw4:-NucdP7Y1vjFhiUa8tw5:bwhauqh) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L4)):*
> ```XML
> pub mod gateway;
> 
> use serde::{Deserialize, Serialize};
> ```

Is this needed?
___
*[`crates/gateway/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdBRR9WJFqwjbc3xO:-NucdBRR9WJFqwjbc3xP:b-qnb0fg) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L13)):*
> ```XML
> use validator::{Validate, ValidationError};
> 
> /// Configuration for a gateway.
> ```

Rephrase to "Gateway configuration"

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucbVsr3G-fD-Yb1Sd_:-NudBqwa-81WJwIUBFxV:b-c7nnt3) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please:
1. Define the path to the directory as a constant; use it to define the path to the specific files.
2. I personally don't like the names "good" and "bad". I prefer the "good" files will be just the file name, and the "bad" ones will be "erroneous". If you disagree let's discuss. If not, please reflect that in the constant names as well.
3.
</blockquote></details>

1. OK
2. Let's talk
___
*[`crates/gateway/src/gateway_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nuccb7J1HPay_5pFrEd:-NudBwJV5HPNW99z_Ncn:b2nhksp) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can these two be unified into a single function that takes the config name and returns its loaded value, that is, as a test utils func?
Furthermore, do we want such a config-name-to-loaded-config function as an actual (not test) util?
</blockquote></details>

OK
___
*[`crates/gateway/src/gateway_test.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nucb6Fe3uNYdq6picdO:-NudC0Mh7EYihbHhMnjB:b2nhksp) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L77)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please put these in a different test file, i.e., "gateway_config_test.rs".
</blockquote></details>

OK
___
*[`crates/gateway/src/lib.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdP7Y1vjFhiUa8tw4:-Nud2OQoCjDJDYUZ4wfK:b2glzsq) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Yes, it's needed. Look at the "#derive" for GatewayConfig.
___
*[`crates/gateway/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdBRR9WJFqwjbc3xO:-Nud35lZEY62OGLhl3ql:b-wv398e) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Rephrase to "Gateway configuration"
</blockquote></details>

In papyrus: 
"/// Configuration for a memory mapped file."

If it's good for them why it's not good for us?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/23#-NusT0dO-PgKnOzWXLpc:-NusT0dO-PgKnOzWXLpd:b-4u4k5y) ([raw file](https://github.com/starkware-libs/mempool/blob/731ecb76ae16f148d80d35a0ef11537cbb645180/crates/gateway/src/config_test.rs#L21)):*
> ```XML
> fn good_config_test() {
>     // Read the good config file and validate it.
>     let config = GatewayConfig::default();
> ```

Required? Can/should this be in a different "validate_default_config_test"?



_Code quote:_
```XML
let config = GatewayConfig::default();
```
___
*[`crates/gateway/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdBRR9WJFqwjbc3xO:-NusQBaY5_d4mYNGlC1K:b-bxmc5m) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L13)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

In papyrus: 
"/// Configuration for a memory mapped file."

If it's good for them why it's not good for us?
</blockquote></details>

Writing concisely is a virtue.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/23#-NusT0dO-PgKnOzWXLpc:-NusmrQW4LEFdP3zJQDl:b-a2ujgl) ([raw file](https://github.com/starkware-libs/mempool/blob/731ecb76ae16f148d80d35a0ef11537cbb645180/crates/gateway/src/config_test.rs#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Required? Can/should this be in a different "validate_default_config_test"?
</blockquote></details>

Changed
___
*[`crates/gateway/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucdBRR9WJFqwjbc3xO:-Nusn6o94gdpuZ5c6X5X:b-bz5ctj) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/lib.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Writing concisely is a virtue.
</blockquote></details>

Changed to " // The gateway configuration."
___
*[`crates/gateway/src/gateway_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/23#-NucbVsr3G-fD-Yb1Sd_:-NusnLSb61I2NA1IyZj4:b-yrwgwv) ([raw file](https://github.com/starkware-libs/mempool/blob/655c5c8b01d6abf4ca99a0bd88aafdb81731e0bd/crates/gateway/src/gateway_test.rs#L38)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

1. OK
2. Let's talk
</blockquote></details>

2. Done

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: all files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwsPmm40sTwS_VIc9L:-NuwsPmm40sTwS_VIc9M:b-2viqpw) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L21)):*
> ```XML
> fn test_valid_config() {
>     // Read the valid config file and validate its content.
>     let expected_config = GatewayConfig {
> ```

What is the purpose of having the valid config duplicated here and in the test file? 
___
*[`crates/gateway/src/config_test.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwrVcq8SgJBHGA5NbC:-NuwrVcq8SgJBHGA5NbD:b-s4suwp) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L24)):*
> ```XML
>         bind_address: String::from("0.0.0.0:8080"),
>     };
>     let load_config = get_config_file(VALID_CONFIG_FILE).unwrap();
> ```

config



_Code quote:_
```XML
load_config
```
___
*[`crates/gateway/src/config_test.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwqrsI17LXuFSP1WeW:-NuwqrsJ1ARrsk0Swkel:b-5xn30r) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L40)):*
> ```XML
> 
> #[test]
> fn test_config_with_invalid_address() {
> ```

I think all the invalid test cases should programmatically create an invalid GatewayConfig, instead of having a bad config file for each case.
Something like:
```
let mut config = get_config_file(VALID_CONFIG_FILE).unwrap();
config.bind_address = "bad_address"

...
```
___
*[`crates/gateway/src/lib.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwZrgQ68Jnwn9b0WiP:-NuwZrgQ68Jnwn9b0WiQ:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/lib.rs#L19)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct GatewayConfig {
>     /// The gateway bind address.
> ```





_Suggestion:_
```XML
/// The gateway socket address, in the form of "IP:port".
```
___
*[`crates/gateway/src/json_files_for_testing/gateway_config.json` line 1 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nuweqg556uoOCWSwQQ-:-Nuweqg556uoOCWSwQQ0:b-2tlxwh) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/json_files_for_testing/gateway_config.json#L1)):*
> ```JSON
> {
> ```

Maybe rename the folder to test_config_files?

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/config_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwsPmm40sTwS_VIc9L:-Nv0tNMk9PfcRLi6-0_i:bfr21yb) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L21)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What is the purpose of having the valid config duplicated here and in the test file?
</blockquote></details>

The purpose is to compare the whole structures. I changed the assert_eq line.
___
*[`crates/gateway/src/config_test.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwrVcq8SgJBHGA5NbC:-Nv0tCu5E0L111S3g9F-:b-vso24a) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

config
</blockquote></details>

Changed to loaded_config.
___
*[`crates/gateway/src/config_test.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwqrsI17LXuFSP1WeW:-Nv0tAu1DWqMtfKoO7dD:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/config_test.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think all the invalid test cases should programmatically create an invalid GatewayConfig, instead of having a bad config file for each case.
Something like:
```
let mut config = get_config_file(VALID_CONFIG_FILE).unwrap();
config.bind_address = "bad_address"

...
```
</blockquote></details>

Done
___
*[`crates/gateway/src/lib.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-NuwZrgQ68Jnwn9b0WiP:-Nv0t6yx168PlpwGoXmL:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/lib.rs#L19)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct GatewayConfig {
>     /// The gateway bind address.
> ```

Done
___
*[`crates/gateway/src/json_files_for_testing/gateway_config.json` line 1 at r3](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nuweqg556uoOCWSwQQ-:-Nuy3WLn9iqa5j1oqysM:by0ickl) ([raw file](https://github.com/starkware-libs/mempool/blob/54a8c9ea31e8781fb80297747bf7468654347cd8/crates/gateway/src/json_files_for_testing/gateway_config.json#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe rename the folder to test_config_files?
</blockquote></details>

I used the already existing folder. Only added file to it.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 5 of 10 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1-qxQ7_Vm3AVtGA0q:-Nv1-qxQ7_Vm3AVtGA0r:bb7phvt) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L30)):*
> ```XML
> #[test]
> fn test_address_validator() {
>     // Read the vqalid config file and check that the validator finds no errors.
> ```

typo



_Code quote:_
```XML
vqalid
```
___
*[`crates/gateway/src/config_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1-wKx69M6vUMBJnad:-Nv1-wKx69M6vUMBJnae:b-1c6qsk) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L35)):*
> ```XML
>     if let Err(e) = config.validate() {
>         panic!("Unexpected error {e}.");
>     }
> ```

Please add a comment that this validates the loaded config.



_Code quote:_
```XML
    if let Err(e) = config.validate() {
        panic!("Unexpected error {e}.");
    }
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1-qxQ7_Vm3AVtGA0q:-Nv1S7VqDSdUyVzfNkOo:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L30)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`crates/gateway/src/config_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1-wKx69M6vUMBJnad:-Nv1SAuS7OUoSm2wsi7C:bafu2yu) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L35)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a comment that this validates the loaded config.
</blockquote></details>

Already in the comment, But removed the empty line  between 'let mut' and 'if'.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23#-:-Nv1T3Kv9QfKsiyI0PcC:bnfp4nl)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1T4fxBEJ0x59dPbt_:-Nv1T4fxBEJ0x59dPbta:b-5739o1) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L35)):*
> ```XML
>     if let Err(e) = config.validate() {
>         panic!("Unexpected error {e}.");
>     }
> ```

`assert!(config.validate().is_ok());`



_Code quote:_
```XML
    if let Err(e) = config.validate() {
        panic!("Unexpected error {e}.");
    }
```
___
*[`crates/gateway/src/config_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1TpoJ1us03DJ7vi7Y:-Nv1TpoJ1us03DJ7vi7Z:b6c0idl) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L46)):*
> ```XML
>             "Invalid Socket address.".to_owned()
>         ),
>     }
> ```

`assert_matches!(config.validate(), Err(ValidationError(...))`



_Code quote:_
```XML
    match config.validate() {
        Ok(_) => panic!("Expected an error, but got a config."),
        Err(e) => assert_eq!(
            e.field_errors()["bind_address"][0].code,
            "Invalid Socket address.".to_owned()
        ),
    }
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1T4fxBEJ0x59dPbt_:-Nv1f6Kl8NvE2eyPD7J8:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L35)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`assert!(config.validate().is_ok());`
</blockquote></details>

Done
___
*[`crates/gateway/src/config_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/mempool/23#-Nv1TpoJ1us03DJ7vi7Y:-Nv1f8O--thLVMF9K_ko:b-95txdl) ([raw file](https://github.com/starkware-libs/mempool/blob/422162323bc6d8a0ebee9b18344b14024dc81e98/crates/gateway/src/config_test.rs#L46)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`assert_matches!(config.validate(), Err(ValidationError(...))`
</blockquote></details>


Done

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/23)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
