### PR TITLE
feat: create serialize config for stateful transaction validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/132?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#132** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/132?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#130** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/130?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#129** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/129?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#126** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#127](https://github.com/starkware-libs/mempool/pull/127) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#114](https://github.com/starkware-libs/mempool/pull/114) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/132#-NyLJEIFEyklban8yZss:-NyLJEIFEyklban8yZst:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/302d5f9f1e0cbe476af4b1139eee57a8de5be1ec/crates/gateway/src/config.rs#L187)):*
> ```XML
>                 "validate_max_n_steps",
>                 &self.validate_max_n_steps,
>                 "The maximum number of steps that can be executed in a transaction.",
> ```





_Suggestion:_
```XML
validated
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/config.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/132#-NyLJEIFEyklban8yZss:-NyLmRbb4TpYeaRHygZY:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3c5aae5ac10673c20e25784a76ffd99f35ce38a8/crates/gateway/src/config.rs#L187)):*
> ```XML
>                 "validate_max_n_steps",
>                 &self.validate_max_n_steps,
>                 "The maximum number of steps that can be executed in a transaction.",
> ```

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/mempool/132#-NyUsSsI3zbP_eFLm7Kh:-NyUsSsI3zbP_eFLm7Ki:b-wsytgq) ([raw file](https://github.com/starkware-libs/mempool/blob/3c5aae5ac10673c20e25784a76ffd99f35ce38a8/crates/gateway/src/config_test.rs#L0)):*
This file will be deleted soon.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/132#-:-NyZOmqe9cInxQdeomC4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
