### PR TITLE
test(mempool): get txs requested chunk in queue validate replenishin…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…g queue

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2NwEDv3cJ9dYaU6yA4:-O2NwEDv3cJ9dYaU6yA5:b-ek6v1s) (no related file):*
I think [this](https://reviewable.io/reviews/starkware-libs/mempool/502) test covers the below scenario.

___
___
*[`crates/mempool/src/mempool_test.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2NwTpE87Vmmlos5H_F:-O2NwTpE87Vmmlos5H_G:bf3e77g) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L215)):*
> ```XML
>         add_tx_input!(tip: 20, tx_hash: 5, sender_address: "0x1", tx_nonce: 1_u8, account_nonce: 0_u8).tx;
>     let tx_address_2_nonce_1 =
>         add_tx_input!(tip: 10, tx_hash: 6, sender_address: "0x2", tx_nonce: 1_u8, account_nonce: 0_u8).tx;
> ```

Is multi-account needed here?



_Code quote:_
```XML
    let tx_address_0_nonce_0 =
        add_tx_input!(tip: 30, tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8).tx;
    let tx_address_1_nonce_0 =
        add_tx_input!(tip: 20, tx_hash: 2, sender_address: "0x1", tx_nonce: 0_u8, account_nonce: 0_u8).tx;
    let tx_address_2_nonce_0 =
        add_tx_input!(tip: 10, tx_hash: 3, sender_address: "0x2", tx_nonce: 0_u8, account_nonce: 0_u8).tx;
    let tx_address_0_nonce_1 =
        add_tx_input!(tip: 30, tx_hash: 4, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8).tx;
    let tx_address_1_nonce_1 =
        add_tx_input!(tip: 20, tx_hash: 5, sender_address: "0x1", tx_nonce: 1_u8, account_nonce: 0_u8).tx;
    let tx_address_2_nonce_1 =
        add_tx_input!(tip: 10, tx_hash: 6, sender_address: "0x2", tx_nonce: 1_u8, account_nonce: 0_u8).tx;
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2UXkxP3wCQHass7cV5:-O2UXkxP3wCQHass7cV6:b-6n4ozg) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L221)):*
> ```XML
>         TransactionReference::new(&tx_address_1_nonce_0),
>         TransactionReference::new(&tx_address_2_nonce_0),
>     ];
> ```

Can a `map` be used here? 
Note we want to move this into `MempoolState`'s c-tor.



_Code quote:_
```XML
    let queue_txs = [
        TransactionReference::new(&tx_address_0_nonce_0),
        TransactionReference::new(&tx_address_1_nonce_0),
        TransactionReference::new(&tx_address_2_nonce_0),
    ];
```
___
*[`crates/mempool/src/mempool_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2UY5zEDJ3q5XsXSwmC:-O2UY5zEDJ3q5XsXSwmD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L235)):*
> ```XML
>     let txs = mempool.get_txs(3).unwrap();
> 
>     // Assert: queue is replenished with the next transactions from each account.
> ```





_Suggestion:_
```XML
transaction of
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2NwTpE87Vmmlos5H_F:-O2Zv2Pf5crTMblTlo4e:b-z0jzs9) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L215)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

@elintul suggested adding a test with a greater number of accounts and transactions to identify potential issues that might arise in more complex scenarios.
</blockquote></details>

Whatever you agree on, no strong opinion.
___
*[`crates/mempool/src/mempool_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2UXkxP3wCQHass7cV5:-O2Zv66D4kP1CzhXI5VO:b-ugd108) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L221)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

i don't see a way to do so without cloning.
</blockquote></details>

I think Mohammad succeeded in one of his PRs, looping over references.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 221 at r3](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2_1pJE87VJqk51bFtk:-O2_1pJF4RhXQxvfq5ef:b-k2pcyy) ([raw file](https://github.com/starkware-libs/mempool/blob/20fb560d3d6cbf2f028ce2a3d880deb6d7228f72/crates/mempool/src/mempool_test.rs#L221)):*
> ```XML
>         TransactionReference::new(&tx_address_1_nonce_0),
>         TransactionReference::new(&tx_address_2_nonce_0),
>     ];
> ```

Here too?



_Code quote:_
```XML
    let queue_txs = [
        TransactionReference::new(&tx_address_0_nonce_0),
        TransactionReference::new(&tx_address_1_nonce_0),
        TransactionReference::new(&tx_address_2_nonce_0),
    ];
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504#-:-O2cnpu2CftxYXz1oZdj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 188 at r5](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2cwY3e5v6Tz23_ePZh:-O2cwY3e5v6Tz23_ePZi:bbxoxze) ([raw file](https://github.com/starkware-libs/mempool/blob/17bf43742eed3aba8c0a43b6464c57a481f123ab/crates/mempool/src/mempool_test.rs#L188)):*
> ```XML
> 
>     let queue_txs = [TransactionReference::new(&tx_nonce_0)];
>     let pool_txs = [tx_nonce_0.clone(), tx_nonce_1.clone(), tx_nonce_2.clone()];
> ```

Would `map` here be more elegant? 
In all tests.



_Code quote:_
```XML
[tx_nonce_0.clone(), tx_nonce_1.clone(), tx_nonce_2.clone()];
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/mempool/504#-O2NwTpE87Vmmlos5H_F:-O2d54SB-ZJO3UL7wMjB:bjn8sg1) ([raw file](https://github.com/starkware-libs/mempool/blob/bb9a6f62367d972414af77816b0743a1c34a9981/crates/mempool/src/mempool_test.rs#L215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Whatever you agree on, no strong opinion.
</blockquote></details>

Let's use fewer tx, as the flow can be done with fewer tx, and the test would be more readable.
It can be done in a separate PR.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/504)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request closed without merging**
