### PR TITLE
feat: stateless validator add calldata len validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-Nv6y0UPA-nx_RAAeNbf:-Nv6y0UPA-nx_RAAeNbg:bgq8udc) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L38)):*
> ```XML
>         validate_non_zero_l1_gas_fee: true,
>         ..VALIDATOR_CONFIG_FOR_TESTING
>     },
> ```

I tried explicitly adding the resource bounds configuration to each test that deals with it. Do you consider it readable?



_Code quote:_
```XML
    TransactionValidatorConfig{
        validate_non_zero_l1_gas_fee: true,
        ..VALIDATOR_CONFIG_FOR_TESTING
    },
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBC8UmAJ6Aca5lAiDI:-NvBC8UmAJ6Aca5lAiDJ:bujw3df) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator.rs#L50)):*
> ```XML
>         };
> 
>         fn validate_reousrce_bounds(
> ```

resource



_Code quote:_
```XML
reousrce
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBD8OSENvpwlDRhkc7:-NvBD8OSENvpwlDRhkc8:b-44u12r) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator.rs#L50)):*
> ```XML
>         };
> 
>         fn validate_reousrce_bounds(
> ```

is it common practice to put a function inside a function? never seen it and it was a bit confusing to me.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBBg025Vuk_uwCqxNI:-NvBBg025Vuk_uwCqxNJ:b-c4vfyr) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L18)):*
> ```XML
> };
> 
> const VALIDATOR_CONFIG_FOR_TESTING: TransactionValidatorConfig = TransactionValidatorConfig {
> ```

VALIDATOR_DEFAULT_CONFIG_FOR_TESTING



_Code quote:_
```XML
VALIDATOR_CONFIG_FOR_TESTING
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-Nv6y0UPA-nx_RAAeNbf:-NvBDaQtAH-fCWbkNThU:bux7cu0) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L38)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I tried explicitly adding the resource bounds configuration to each test that deals with it. Do you consider it readable?
</blockquote></details>

it is not clear to me why this is the default behaviour? would expect it to be both true or both false. 
validate_non_zero_l1_gas_fee: true,
validate_non_zero_l2_gas_fee: false,

I think it would be clearer if the default will be false for both and then you will override it with true when needed.
but maybe there is something I don't understand
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBBGQS-YqEnwEMa54N:-NvBBGQS-YqEnwEMa54O:b-myuet6) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L87)):*
> ```XML
>     ),
>     Err(TransactionValidatorError::CalldataTooLong { calldata_length: 2, max_calldata_length: 1 })
> )]
> ```

add another case checking the good flow with non-empty calldata that does not exceed the maximum length

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBC8UmAJ6Aca5lAiDI:-NvBX5Ff8fFYVnx5qmGl:b-9bonyp) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator.rs#L50)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

resource
</blockquote></details>

Done. addressed in #45
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBD8OSENvpwlDRhkc7:-NvBYBt219CTj9-zGcn1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator.rs#L50)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

is it common practice to put a function inside a function? never seen it and it was a bit confusing to me.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBBg025Vuk_uwCqxNI:-NvBWdUw-8iYTAinlTjM:b-9bonyp) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L18)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

VALIDATOR_DEFAULT_CONFIG_FOR_TESTING
</blockquote></details>

Done. addressed in #45
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-Nv6y0UPA-nx_RAAeNbf:-NvBgbV74DmeDgfxE1_-:bf3ifzm) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L38)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is not clear to me why this is the default behaviour? would expect it to be both true or both false. 
validate_non_zero_l1_gas_fee: true,
validate_non_zero_l2_gas_fee: false,

I think it would be clearer if the default will be false for both and then you will override it with true when needed.
but maybe there is something I don't understand
</blockquote></details>

Good point. Addressed in Pre-PR. #45.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/38#-NvBBGQS-YqEnwEMa54N:-NvBZlKbD8s6okPCNMNB:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d6853a55294b8cc9b3ee08495e42a25d88f2dcac/crates/gateway/src/stateless_transaction_validator_test.rs#L87)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

add another case checking the good flow with non-empty calldata that does not exceed the maximum length
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38#-:-NvVmDdr1vmwxA5IZuZo:bnfp4nl)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38#-:-Nv_pLrH5w3qT3viy_6N:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by Yael-Starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38#-:-Nva5slz0-M96857aj8t:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38#-:-Nva6GWD-yPv7XW1ZR5O:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/38)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
