### PR TITLE
feat: adding empty server and refactoring ComponentServer

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:689882a6

---

**Stack**:
- #339
- #311
- #310
- #309 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i6i-l2HnybVsZQ0Um:-O0i6i-l2HnybVsZQ0Un:b-mav4wp) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/mempool_infra/src/component_server.rs#L56)):*
> ```XML
> {
>     async fn start(&mut self) {
>         self.start_main_loop().await;
> ```

What do you think about moving the implementation of `start_main_loop` to be here? 

Currently we have `ComponentServer` with this level of indirection and `EmptyServer` without it.
Personally, I prefer the direct approach, but regardless, these should be consistent.



_Code quote:_
```XML
self.start_main_loop().await;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i7IjSBxXMwDWMwqeK:-O0i7IjSBxXMwDWMwqeL:bsdsa4a) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/gateway/src/gateway.rs#L195)):*
> ```XML
> }
> 
> pub type GatewayCommunicationServer = EmptyServer<Gateway>;
> ```

IIUC this should be something that implements the `ComponentServerStarter` trait, no?
If so, please change to `Arc<dyn ComponentServerStarter>` or `Box<dyn ComponentServerStarter>`, whatever is more suitable.



_Code quote:_
```XML
EmptyServer<Gateway>;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i7fqLEzYl0fwPTFA0:-O0i7fqLEzYl0fwPTFA1:bvytey) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/gateway/src/gateway.rs#L199)):*
> ```XML
> pub fn create_gateway_server(gateway: Gateway) -> GatewayCommunicationServer {
>     create_empty_server(gateway)
> }
> ```

These two should be part of the mempool_node crate.



_Code quote:_
```XML
pub type GatewayCommunicationServer = EmptyServer<Gateway>;

pub fn create_gateway_server(gateway: Gateway) -> GatewayCommunicationServer {
    create_empty_server(gateway)
}
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i7IjSBxXMwDWMwqeK:-O0is__U0y8s00pptXgl:b-wboh78) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/gateway/src/gateway.rs#L195)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC this should be something that implements the `ComponentServerStarter` trait, no?
If so, please change to `Arc<dyn ComponentServerStarter>` or `Box<dyn ComponentServerStarter>`, whatever is more suitable.
</blockquote></details>

Moved to communication.rs
___
*[`crates/gateway/src/gateway.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i7fqLEzYl0fwPTFA0:-O0isjGJAkaC-PI_HlDS:b-wboh78) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/gateway/src/gateway.rs#L199)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These two should be part of the mempool_node crate.
</blockquote></details>

Moved to communication.rs
___
*[`crates/mempool_infra/src/component_server.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/mempool/309#-O0i6i-l2HnybVsZQ0Um:-O0iszxVA2aIbXedPB59:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1f9c023113e1bed7c956b48387c6f57ed18f06a5/crates/mempool_infra/src/component_server.rs#L56)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What do you think about moving the implementation of `start_main_loop` to be here? 

Currently we have `ComponentServer` with this level of indirection and `EmptyServer` without it.
Personally, I prefer the direct approach, but regardless, these should be consistent.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309#-:-O0miuHw7y-IOZQf084Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 4 of 8 files at r3, 2 of 8 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/309)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
