### PR TITLE
test(mempool): refactor test_add_tx_with_identical_tip to use mempool…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
… state

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445#-:-O1WjvbH3VVGGLcoxjW3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/445#-O1Wk7z_-I2jetN3rvvn:-O1Wk7z_-I2jetN3rvvo:b-75fyvi) ([raw file](https://github.com/starkware-libs/mempool/blob/23b394768725def30c037a5ad16076112b535bc9/crates/mempool/src/mempool_test.rs#L226)):*
> ```XML
>     add_tx(&mut mempool, &input2);
> 
>     let queue_txs = [TransactionReference::new(&input1.tx), TransactionReference::new(&input2.tx)];
> ```

Can you push the Tx Ref initialization transformation into MempoolState? less test boilerplate



_Code quote:_
```XML
 let queue_txs = [TransactionReference::new(&input1.tx), TransactionReference::new(&input2.tx)];
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/445#-O1Wk7z_-I2jetN3rvvn:-O1WqpEK4_0U2EEAH0OV:b-9k7g1d) ([raw file](https://github.com/starkware-libs/mempool/blob/23b394768725def30c037a5ad16076112b535bc9/crates/mempool/src/mempool_test.rs#L226)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you push the Tx Ref initialization transformation into MempoolState? less test boilerplate
</blockquote></details>

I'm aware of t two ways to handle this refactor:
1. Passing an iterator of `ThinTransaction`- this would lead to more cloning.
2. Passing references - this would require the use of lifetimes, which might complicate the implementation and usage.

Do you prefer either of these methods or is there a third option I'm not considering?

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445#-:-O1Ww1T60X2xRxB2_hmJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/445#-O1Wk7z_-I2jetN3rvvn:-O1q_-7a4IuTVgz3-Z85:b-5akoiv) ([raw file](https://github.com/starkware-libs/mempool/blob/23b394768725def30c037a5ad16076112b535bc9/crates/mempool/src/mempool_test.rs#L226)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I'm aware of t two ways to handle this refactor:
1. Passing an iterator of `ThinTransaction`- this would lead to more cloning.
2. Passing references - this would require the use of lifetimes, which might complicate the implementation and usage.

Do you prefer either of these methods or is there a third option I'm not considering?
</blockquote></details>

will this work?
```rust
    fn new(
        pool_txs: impl IntoIterator<Item = ThinTransaction>,
        queue_txs: &[&ThinTransaction],
    ) -> Self {
        let tx_pool: TransactionPool = pool_txs.into_iter().collect();
        let tx_queue: TransactionQueue =
            queue_txs.into_iter().map(|tx| TransactionReference::new(tx)).collect();
        MempoolState { tx_pool, tx_queue }
    }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/445#-O1Wk7z_-I2jetN3rvvn:-O1r0vgKCqwsTCu1G5Wh:bkielxa) ([raw file](https://github.com/starkware-libs/mempool/blob/23b394768725def30c037a5ad16076112b535bc9/crates/mempool/src/mempool_test.rs#L226)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

will this work?
```rust
    fn new(
        pool_txs: impl IntoIterator<Item = ThinTransaction>,
        queue_txs: &[&ThinTransaction],
    ) -> Self {
        let tx_pool: TransactionPool = pool_txs.into_iter().collect();
        let tx_queue: TransactionQueue =
            queue_txs.into_iter().map(|tx| TransactionReference::new(tx)).collect();
        MempoolState { tx_pool, tx_queue }
    }
```
</blockquote></details>

can we try in a different PR?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 252 at r2](https://reviewable.io/reviews/starkware-libs/mempool/445#-O1uhGa84q0VFSMk61Tk:-O1uhGa84q0VFSMk61Tl:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f77e3ee6a1a71851dd37ead574aa2d59d9ec88c8/crates/mempool/src/mempool_test.rs#L252)):*
> ```XML
>     add_tx(&mut mempool, &input2);
> 
>     // Assert that both transactions are in the mempool.
> ```





_Suggestion:_
```XML
// Assert: 
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/445#-:-O1v2K3REjD9neMY-F5t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
