### PR TITLE
test(mempool): rename get_txs test to be more specific

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O1vZufMAf7yfGc85xyI:b-6h430b) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
> ```XML
> #[case::test_get_more_than_all_eligible_txs(5)]
> #[case::test_get_less_than_all_eligible_txs(2)]
> fn test_get_txs_fetching_order(#[case] requested_txs: usize) {
> ```

Not sure it adds to readability, since this is checked in every `get_txs` tets, right?



_Code quote:_
```XML
test_get_txs_fetching_order
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O1vg2hP5Go4ydEL5Xa5:b9obnjg) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure it adds to readability, since this is checked in every `get_txs` tets, right?
</blockquote></details>

not really. For example, when we want to fill a hole, we check that no txs are fetched.
Also, it is one of the splits @giladchase asked for, here #254

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O1vjijm8tZHd7DJ7USG:b-fltodq) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

not really. For example, when we want to fill a hole, we check that no txs are fetched.
Also, it is one of the splits @giladchase asked for, here #254
</blockquote></details>

"when we want to fill a hole, we check that no txs are fetched"
Can you explain?

Isn't the case is that in all tests of `get_txs` we check the order of the returned transactions?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O1vlA7x3EkamjkYwZDT:b-6aeugy) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

"when we want to fill a hole, we check that no txs are fetched"
Can you explain?

Isn't the case is that in all tests of `get_txs` we check the order of the returned transactions?
</blockquote></details>

In most tests, we focus on something else, but order. for example, only one tx is returned, so the order is not checked.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O2-ehxbCpMJuqkLgqFu:b-hrl3qp) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

In most tests, we focus on something else, but order. for example, only one tx is returned, so the order is not checked.
</blockquote></details>

Right, it's trivial there. What about rest of `get_txs` tests?

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O2TZFDwAhqc2FgTfC3y:b-1bwhfj) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

* test_get_txs - checks order by the tip.
* test_get_txs_multi_nonce - only one account, so doesn't check order by tip
* test_get_txs_with_holes_multiple_accounts - two txs of two accounts, one with a hole, so only one tx is returned. no order check
* test_get_txs_with_holes_single_account - single account, one tx, with a hole, nothing is returned, no order check. 
* test_flow_filling_holes - flow of add_tx and get_txs.
</blockquote></details>

If we always check order when `>= 2` transactions are returned, this test name might be confusing.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/485#-O1vZufLDIXO32ANwuX3:-O2Y_uN6EoOJMksgH7Uo:bvs49p) ([raw file](https://github.com/starkware-libs/mempool/blob/0aba599f9ea4735e18ab8fb1bad2b37e36f9910d/crates/mempool/src/mempool_test.rs#L143)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If we always check order when `>= 2` transactions are returned, this test name might be confusing.
</blockquote></details>

wdym? we don't check 2+ txs in all the tests

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/mempool/485#-O2ZcRXI2K_kRESx7lc0:-O2ZcRXI2K_kRESx7lc1:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3773163ae1ff3c94e2daa8758da5de55b87246d5/crates/mempool/src/mempool_test.rs#L147)):*
> ```XML
> #[case::test_get_more_than_all_eligible_txs(5)]
> #[case::test_get_less_than_all_eligible_txs(2)]
> fn test_get_txs_fetching_order(#[case] requested_txs: usize) {
> ```





_Suggestion:_
```XML
test_get_txs_returns_by_priority_order
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/485#-:-O2ZeQDB29Zhw6bBnusp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request closed without merging**
