### PR TITLE
test(mempool): add tx multi nonce with holes, single account

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/mempool/451#-O1rEK7c-rQz9DKgEeyg:-O1rEK7d1hCsVyM2MZmB:b-uuws8u) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd0980d94800a1413fa211ff1aef6ff17cd58e/crates/mempool/src/mempool_test.rs#L310)):*
> ```XML
>     add_tx(&mut mempool, &input_nonce_0);
> 
>     // Assert: only eligible transaction appears in the queue.
> ```

grammar



_Suggestion:_
```XML
    // Assert: only the eligible transaction appears in the queue.
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/mempool/451#-O1uYUku2LjLWN3CxHg_:-O1uYUku2LjLWN3CxHga:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd0980d94800a1413fa211ff1aef6ff17cd58e/crates/mempool/src/mempool_test.rs#L292)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_with_holes_single_account(mut mempool: Mempool) {
> ```





_Suggestion:_
```XML
test_add_tx_filling_hole
```
___
*[`crates/mempool/src/mempool_test.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/mempool/451#-O1uYZA6E8t4Jb6GPetM:-O1uYZA6E8t4Jb6GPetN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd0980d94800a1413fa211ff1aef6ff17cd58e/crates/mempool/src/mempool_test.rs#L305)):*
> ```XML
>     let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
> 
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```





_Suggestion:_
```XML
    let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
    expected_mempool_state.assert_eq_mempool_state(&mempool);
```
___
*[`crates/mempool/src/mempool_test.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/mempool/451#-O1uYbZB5RWewkCntBrN:-O1uYbZB5RWewkCntBrO:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd0980d94800a1413fa211ff1aef6ff17cd58e/crates/mempool/src/mempool_test.rs#L315)):*
> ```XML
>     let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
> 
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```





_Suggestion:_
```XML
    let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
    expected_mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451#-:-O1vboysDsHds0HiMKWp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 359 at r5](https://reviewable.io/reviews/starkware-libs/mempool/451#-O2-cVxC551_E4OSIOwZ:-O2-cVxD1qO1jzT0G4mz:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/eab8c3ecb6b136a02fe74260e35568aaf40b71c9/crates/mempool/src/mempool_test.rs#L359)):*
> ```XML
>     add_tx(&mut mempool, &input_nonce_1);
> 
>     // Assert that the second transaction is in the pool and not in the queue.
> ```





_Suggestion:_
```XML
// Assert: the second transaction is in the pool and not in the queue.
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
