### PR TITLE
feat: state reader factory

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
1. added a StateReaderFactory trait that will be able to produce both an TestStateReader and an RpcStateReader
2. the StateReader shoudl implement both BlockifierStateReader trait and and additional get_block_info functionality. These 2 functionalities are united into a new trait called MempoolStateReader
3. Cancelled the separation of validate() and run_validate() and reunited them into only run_validate()

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122#-:-NxfXBOA9ZeD2PjvY4Sv:b-7qnepl)* status: 0 of 7 files reviewed, all discussions resolved

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfcvAX1PA3i4LRJ4En:-NxfcvAX1PA3i4LRJ4Eo:b-6m9dwz) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L29)):*
> ```XML
>     pub config: StatefulTransactionValidatorConfig<T, S>,
>     _marker: PhantomData<S>,
> }
> ```

Do we need to provide the struct both `S` and `T`? Isn't `S` sufficient?



_Code quote:_
```XML
pub struct StatefulTransactionValidator<T, S>
where
    T: StateReaderFactory<S>,
    S: MempoolStateReader,
{
    pub config: StatefulTransactionValidatorConfig<T, S>,
    _marker: PhantomData<S>,
}
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfcgHFE9zIk9TV12LU:-NxfcgHFE9zIk9TV12LV:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L41)):*
> ```XML
>         optional_class_info: Option<ClassInfo>,
>         deploy_account_tx_hash: Option<TransactionHash>,
>     ) -> Result<(), StatefulTransactionValidatorError> {
> ```





_Suggestion:_
```XML
    ) -> StatefulTransactionValidatorResult<()> {
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfdQHnEsb2PrdUgOrf:-NxfdQHnEsb2PrdUgOrg:b-bgwco9) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
> ```XML
>     pub state_reader_factory: T,
>     _marker: PhantomData<S>,
> }
> ```

Does that work?



_Suggestion:_
```XML
pub struct StatefulTransactionValidatorConfig<S>
where
    S: MempoolStateReader,
{
    pub max_nonce_for_validation_skip: Nonce,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub chain_info: ChainInfo,
    pub state_reader_factory: StateReaderFactory<S>,
    _marker: PhantomData<S>,
}
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg0x9fBnSM5_e8OJrx:-Nxg0x9fBnSM5_e8OJry:b-dzelq) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/state_reader_test_utils.rs#L52)):*
> ```XML
> 
> pub struct TestStateReaderFactory {
>     pub state_reader: TestStateReader,
> ```

Can it be `DictStateReader` directly? 



_Code quote:_
```XML
TestStateReader
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg-Fcj8immQaN5ZtaQ:-Nxg-Fcj8immQaN5ZtaR:b-q7v4hu) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L22)):*
> ```XML
> mod stateful_transaction_validator_test;
> 
> pub struct StatefulTransactionValidator<T, S>
> ```

I think the `StatefulTransactionValidator` should hold a `stste_reader_factory` as a member and not the config.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg01uH680wUR73CIpH:-Nxg01uH680wUR73CIpI:b2s2ria) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L28)):*
> ```XML
> {
>     pub config: StatefulTransactionValidatorConfig<T, S>,
>     _marker: PhantomData<S>,
> ```

What is this?



_Code quote:_
```XML
_marker: PhantomData<S>,
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg0x9fBnSM5_e8OJrx:-NxgjLvc1cqySjR9sbq1:b-7b7i7i) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/state_reader_test_utils.rs#L52)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it be `DictStateReader` directly?
</blockquote></details>

it must include both the BlockifierStateReader and the BlockInfo.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg-Fcj8immQaN5ZtaQ:-Nxgfg_V8bgkg51Xcrvt:b-hp1jh1) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L22)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think the `StatefulTransactionValidator` should hold a `stste_reader_factory` as a member and not the config.
</blockquote></details>

but the `StatefulTransactionValidator` is created for each transaction and we don't need a new factory for each transactions, just a new state reader.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg01uH680wUR73CIpH:-Nxgf_HB1h8gxiucFNwx:b-6ki27b) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L28)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

I had to put it since it seems like S is never used. but it is....
This was what the compiler suggested to do in this case., Papyrus is also using this workaround.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfcvAX1PA3i4LRJ4En:-Nxgih4U9wDcz78oMFkb:bpa69h5) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L29)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we need to provide the struct both `S` and `T`? Isn't `S` sufficient?
</blockquote></details>

no , since the config takes 2 generics
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfcgHFE9zIk9TV12LU:-NxgfQbu6HtEe9qZgzS8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L41)):*
> ```XML
>         optional_class_info: Option<ClassInfo>,
>         deploy_account_tx_hash: Option<TransactionHash>,
>     ) -> Result<(), StatefulTransactionValidatorError> {
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxfdQHnEsb2PrdUgOrf:-NxgewCaEGaZJjUR1LrT:b-zcia9) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does that work?
</blockquote></details>

didn't really work. 
first I had to use the dyn keyword to state that this field has a dynamic size and then I couldn't create an instance of this struct in tests since it is not considered stable to not have a size.
Tried to play with this for a bit but couldn't make it work.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg01uH680wUR73CIpH:-Nxgk1yQ7yj3ht_WmcJy:b-etdpqm) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L28)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I had to put it since it seems like S is never used. but it is....
This was what the compiler suggested to do in this case., Papyrus is also using this workaround.
</blockquote></details>

Link to papyrus: https://github.com/starkware-libs/papyrus/blob/edf15ad64ef64a9b9884e350fd86248aba472a60/crates/papyrus_storage/src/db/mod.rs#L276

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxgvzTa2nUqoTz6QU3Y:-NxgvzTa2nUqoTz6QU3Z:bbnlzy1) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
> ```XML
>     pub state_reader_factory: T,
>     _marker: PhantomData<S>,
> }
> ```

The `factory` and the `_marker` should not be a member of the config.
The config should be something that can be translated into a json.



_Code quote:_
```XML
pub struct StatefulTransactionValidatorConfig<T, S>
where
    T: StateReaderFactory<S>,
    S: MempoolStateReader,
{
    pub max_nonce_for_validation_skip: Nonce,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub chain_info: ChainInfo,
    pub state_reader_factory: T,
    _marker: PhantomData<S>,
}
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxvTT093O_38KMJuvYZ:-NxvTT093O_38KMJuvY_:bg5fplo) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/rpc_state_reader.rs#L179)):*
> ```XML
>     fn get_latest_state_reader(&self) -> T;
>     fn get_state_reader(&self, block_number: BlockNumber) -> T;
> }
> ```

Let's put it in a new state_reader.rs file.



_Code quote:_
```XML
pub trait MempoolStateReader: BlockifierStateReader {
    fn get_block_info(&self) -> Result<BlockInfo, StateError>;
}

pub trait StateReaderFactory<T: MempoolStateReader> {
    fn get_latest_state_reader(&self) -> T;
    fn get_state_reader(&self, block_number: BlockNumber) -> T;
}
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxvWycbEywIIIRdFUEF:-NxvWycbEywIIIRdFUEG:bneysrr) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/rpc_state_reader.rs#L186)):*
> ```XML
> 
> impl StateReaderFactory<RpcStateReader> for RpcStateReaderFactory {
>     fn get_latest_state_reader(&self) -> RpcStateReader {
> ```

Consider renaming to get_state_reader_from_latest_block



_Code quote:_
```XML
get_latest_state_reader
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg-Fcj8immQaN5ZtaQ:-Nxv7RHu2Q6eCQsjK1J-:bp6yhfn) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L22)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but the `StatefulTransactionValidator` is created for each transaction and we don't need a new factory for each transactions, just a new state reader.
</blockquote></details>

(discussed f2f)

It won't be a new factory for each transaction. There will be one factory owned by the Gateway, which will be passed to the validator each time we create one.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxvTT093O_38KMJuvYZ:-NxvuFx4ECMzxv20DcNy:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/rpc_state_reader.rs#L179)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Let's put it in a new state_reader.rs file.
</blockquote></details>

Done.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxvWycbEywIIIRdFUEF:-NxvuUQ32KLYqKcZxfTm:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/rpc_state_reader.rs#L186)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider renaming to get_state_reader_from_latest_block
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/122#-Nxg-Fcj8immQaN5ZtaQ:-NxvyvOu1W9roLZDhEYE:bgultg7) ([raw file](https://github.com/starkware-libs/mempool/blob/5907b0f06bd937d14ffc8c2e9682ce752fe60b44/crates/gateway/src/stateful_transaction_validator.rs#L22)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

(discussed f2f)

It won't be a new factory for each transaction. There will be one factory owned by the Gateway, which will be passed to the validator each time we create one.
</blockquote></details>

removed it from the statefulValidator object , will add to the AppState object in the next PR (added a TODO).
Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/mempool/122#-NxgvzTa2nUqoTz6QU3Y:-Nxvz5pT9-imCG2ab8rT:ba1gxni) ([raw file](https://github.com/starkware-libs/mempool/blob/bfcf9843081d81dcf1f1b055e323ee36b1a79ae6/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The `factory` and the `_marker` should not be a member of the config.
The config should be something that can be translated into a json.
</blockquote></details>

was deleted from this struct after discussing f2f. Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122#-:-Nxw3FAT7Vd7kqya_mGo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122#-:-NxwAP-x-U7z6FFH7KAB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/122)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
