### PR TITLE
feat: connect batcher network channels

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPPnf_DAOVo913T0vw:-NyPPnf_DAOVo913T0vx:buyqexj) ([raw file](https://github.com/starkware-libs/mempool/blob/239c34835af93dd4c53618ddcb296fa616f3b4fa/crates/mempool/src/mempool.rs#L144)):*
> ```XML
>             BatcherToMempoolMessage::GetTxs(n_txs) => {
>                 let res = self.get_txs(n_txs)?;
>                 self.batcher_network.tx.send(res).await?;
> ```

Can we encapsulate `network.tx`?



_Suggestion:_
```XML
                let txs = self.get_txs(n_txs)?;
                self.batcher_network.tx.send(txs).await?;
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPPQdb1wkvXTUtqxcM:-NyPPQdb1wkvXTUtqxcN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/239c34835af93dd4c53618ddcb296fa616f3b4fa/crates/mempool_types/src/mempool_types.rs#L46)):*
> ```XML
> 
> pub enum BatcherToMempoolMessage {
>     GetTxs(usize),
> ```





_Suggestion:_
```XML
GetTransactions
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPPnf_DAOVo913T0vw:-NyPRBivDwNys9iZE8F6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/239c34835af93dd4c53618ddcb296fa616f3b4fa/crates/mempool/src/mempool.rs#L144)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we encapsulate `network.tx`?
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPXTJe1Fg9pW2O9cxQ:-NyPXTJe1Fg9pW2O9cxR:b-tgixhr) ([raw file](https://github.com/starkware-libs/mempool/blob/67ce9bee2478743f399bc286604567266f38b26c/crates/mempool/src/mempool.rs#L38)):*
> ```XML
>     ) -> Self {
>         let mut mempool = Mempool {
>             txs_queue: Default::default(),
> ```

Why `Default` and not the struct name explicitly?



_Code quote:_
```XML
Default
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPXmrADstwXReF8s5L:-NyPXmrADstwXReF8s5M:b-g94mub) ([raw file](https://github.com/starkware-libs/mempool/blob/67ce9bee2478743f399bc286604567266f38b26c/crates/mempool_types/src/mempool_types.rs#L46)):*
> ```XML
> 
> pub enum BatcherToMempoolMessage {
>     GetTransactions(usize),
> ```

Why `usize` and not `u16`, for example?



_Code quote:_
```XML
usize
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPXTJe1Fg9pW2O9cxQ:-NyPZ1yjDj5bpgEtrWca:b-e087e5) ([raw file](https://github.com/starkware-libs/mempool/blob/67ce9bee2478743f399bc286604567266f38b26c/crates/mempool/src/mempool.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why `Default` and not the struct name explicitly?
</blockquote></details>

AFAIK, it should be the same.
Anyway, updated.
___
*[`crates/mempool_types/src/mempool_types.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/mempool/153#-NyPXmrADstwXReF8s5L:-NyPYGoWCLVA6HBHJtpc:b5lgnni) ([raw file](https://github.com/starkware-libs/mempool/blob/67ce9bee2478743f399bc286604567266f38b26c/crates/mempool_types/src/mempool_types.rs#L46)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why `usize` and not `u16`, for example?
</blockquote></details>

I used the same type used in Mempool `get_txs` method.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @Itay-Tsabary-Starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/153#-:-NyPf9PGDv7IpakT35si:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @Itay-Tsabary-Starkware)

**Pull request merged**
