### PR TITLE
feat(mempool): remove addresses of reverted transactions from queue in commit block method

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…n commit block method

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TWa7gBkfSmg7sxoKP:-O2TWa7hAvD4GOdLw4t9:b-mh1hkj) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L87)):*
> ```XML
>         state_changes: HashMap<ContractAddress, AccountState>,
>     ) -> MempoolResult<()> {
>         for (&address, AccountState { nonce }) in state_changes.iter() {
> ```

Why is this change needed? Isn't `for x in iterable` sugar for that?



_Code quote:_
```XML
for (&address, AccountState { nonce }) in state_changes.iter()
```
___
*[`crates/mempool/src/mempool.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TX3Zl6Qi5GR0BCdPo:-O2TX3ZmE1dioW7-P53B:b5uh46r) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L104)):*
> ```XML
>         }
>         // TODO: update the tx_queue with the new state changes.
> ```

This is not necessarily true, right? The bouncer might have rejected them, so they're still valid.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TWa7gBkfSmg7sxoKP:-O2TsHVE8pHnBbeJZSMn:brngdz0) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this change needed? Isn't `for x in iterable` sugar for that?
</blockquote></details>

Not sure I get it. What so you suggest? 
My code extracts `address`, and `nonce`.
___
*[`crates/mempool/src/mempool.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TX3Zl6Qi5GR0BCdPo:-O2TsV4w6DEiOYu5KsBU:b-krko8y) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L104)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is not necessarily true, right? The bouncer might have rejected them, so they're still valid.
</blockquote></details>

Correct, I wrote " as they were not included in the block." So it's a generic comment. A TX can be rejected by the bouncer or by the executor.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TWa7gBkfSmg7sxoKP:-O2TveVL0t-xub8bYJ6P:b-zbnof0) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I get it. What so you suggest? 
My code extracts `address`, and `nonce`.
</blockquote></details>

What happens if you remove `.iter()`?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TWa7gBkfSmg7sxoKP:-O2Uyku34dQY0svMPZjr:b-cvyyfy) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What happens if you remove `.iter()`?
</blockquote></details>

`.iter()` returns ref.
if I remove it, so this line:
`if !state_changes.contains_key(address)` 
would fail on borrowing issue

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2TWa7gBkfSmg7sxoKP:-O2VEqXsAamEafYEazIG:b67l268) ([raw file](https://github.com/starkware-libs/mempool/blob/056d4e9694c6d2161f5f6322c419c5cdfa791e06/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`.iter()` returns ref.
if I remove it, so this line:
`if !state_changes.contains_key(address)` 
would fail on borrowing issue
</blockquote></details>

Will looping over `&state_changes` work?

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 116 at r4](https://reviewable.io/reviews/starkware-libs/mempool/508#-O2ZWRKgDsQwR8AVzAQU:-O2ZWRKh9OE1zh620PyY:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/511bc5661a374180d3e1c832471775206cc17f9a/crates/mempool/src/mempool.rs#L116)):*
> ```XML
>         self.mempool_state.clear();
> 
>         Ok(())
> ```





_Suggestion:_
```XML
        // Rewind nonces of addresses that were not included in block.
        let addresses_not_included_in_block =
            self.mempool_state.keys().filter(|&key| !state_changes.contains_key(key));
        for address in addresses_not_included_in_block {
            self.tx_queue.remove(*address);
        }
        
        self.mempool_state.clear();

        Ok(())
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/508#-:-O2ZqRQABry5ir0kFGfg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Pull request closed without merging**
