### PR TITLE
test(mempool): add commit block test invalid argument

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/491)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/491)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/mempool/491#-O2UB4qUDuRMZBNgENk1:-O2UB4qUDuRMZBNgENk2:bclz9x7) ([raw file](https://github.com/starkware-libs/mempool/blob/da557529975f5c7922667a0e2bb4d376e793f1de/crates/mempool/src/mempool_test.rs#L365)):*
> ```XML
>     assert_eq!(txs, &[input_address_0_nonce_0.tx]);
> }
> ```

How can we reduce transaction cloning to once per test?
___
*[`crates/mempool/src/mempool_test.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/mempool/491#-O2UBN-K5xANlGZSTzSF:-O2UBN-K5xANlGZSTzSG:bsgqy15) ([raw file](https://github.com/starkware-libs/mempool/blob/da557529975f5c7922667a0e2bb4d376e793f1de/crates/mempool/src/mempool_test.rs#L388)):*
> ```XML
> 
>     let invalid_commit_state =
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(3_u16)) })]);
> ```

Why is this invalid? Maybe the transaction was rejected/not inserted into the block due to space?



_Code quote:_
```XML
    let invalid_commit_state =
        HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(3_u16)) })]);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/491)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/mempool/491#-O2UBN-K5xANlGZSTzSF:-O2YmakgCVT2mnyQe5nw:bjfr62o) ([raw file](https://github.com/starkware-libs/mempool/blob/da557529975f5c7922667a0e2bb4d376e793f1de/crates/mempool/src/mempool_test.rs#L388)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this invalid? Maybe the transaction was rejected/not inserted into the block due to space?
</blockquote></details>

Note that in the block state, the nonce was decreased, which is illegal.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/491)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/mempool/491#-O2UB4qUDuRMZBNgENk1:-O2YpMeC2oDgwELsLfi4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da557529975f5c7922667a0e2bb4d376e793f1de/crates/mempool/src/mempool_test.rs#L365)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How can we reduce transaction cloning to once per test?
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/491)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 388 at r2](https://reviewable.io/reviews/starkware-libs/mempool/491#-O2UBN-K5xANlGZSTzSF:-O2ZMUxc0M-gb9DFaCkN:b4wxizq) ([raw file](https://github.com/starkware-libs/mempool/blob/da557529975f5c7922667a0e2bb4d376e793f1de/crates/mempool/src/mempool_test.rs#L388)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that in the block state, the nonce was decreased, which is illegal.
</blockquote></details>

I see, then what's our behavior in this case?

**Pull request closed without merging**
