### PR TITLE
feat: run stateful validations in add_tx

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyFSDNjDfzpq-sKTDRm:-NyFSDNk1d9-VBKQ0LZJ:b-7i39zh) ([raw file](https://github.com/starkware-libs/mempool/blob/6cac4f2f09d24275530614fb6cbc2d3c97eaf22c/crates/gateway/src/gateway_test.rs#L56)):*
> ```XML
>         TransactionSignature(vec![StarkFelt::ZERO]),
>     )
> }
> ```

Note @ayeletstarkware is working on this right now.



_Code quote:_
```XML
// TODO(Yael, 19/5/2024): refactor testing infrastructure to genereate a consistent state and
// transaction for all tests in one place
pub fn invoke_tx() -> ExternalTransaction {
    let cairo_version = CairoVersion::Cairo1;
    let account_contract = FeatureContract::AccountWithoutValidations(cairo_version);
    let account_address = account_contract.get_instance_address(0);
    let test_contract = FeatureContract::TestContract(cairo_version);
    let test_contract_address = test_contract.get_instance_address(0);
    let calldata = create_trivial_calldata(test_contract_address);
    let mut nonce_manager = NonceManager::default();
    let nonce = nonce_manager.next(account_address);
    executable_external_invoke_tx_for_testing(
        executable_resource_bounds_mapping(),
        nonce,
        account_address,
        calldata,
        TransactionSignature(vec![StarkFelt::ZERO]),
    )
}
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyFSDNjDfzpq-sKTDRm:-NyFTMI3EqfGQleEzlz6:b-ncfsfh) ([raw file](https://github.com/starkware-libs/mempool/blob/6cac4f2f09d24275530614fb6cbc2d3c97eaf22c/crates/gateway/src/gateway_test.rs#L56)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Note @ayeletstarkware is working on this right now.
</blockquote></details>

I am reffering to #131.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, and @dafnamatsry)

___
*[`crates/gateway/src/gateway_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyFSDNjDfzpq-sKTDRm:-NyFTzzH3qAfqzmKQOdM:b52y4gf) ([raw file](https://github.com/starkware-libs/mempool/blob/6cac4f2f09d24275530614fb6cbc2d3c97eaf22c/crates/gateway/src/gateway_test.rs#L56)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I am reffering to #131.
</blockquote></details>

yes I know , will work with her on this next week when she's back from Fibonacci

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @Yael-Starkware)

___
*[`crates/gateway/tests/routing_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyFcl51CLNIAaJj5Dcm:-NyFcl51CLNIAaJj5Dcn:bf85vgs) ([raw file](https://github.com/starkware-libs/mempool/blob/6cac4f2f09d24275530614fb6cbc2d3c97eaf22c/crates/gateway/tests/routing_test.rs#L57)):*
> ```XML
> }
> 
> pub fn invoke_tx() -> ExternalTransaction {
> ```

Is it the same as in the other test? 
I guess we need a general test_utils.rs file for these kinds of things.

If it will change due to Ayelet's refactor, please add a TODO here as well. 



_Code quote:_
```XML
pub fn invoke_tx() -> ExternalTransaction
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @dafnamatsry)

___
*[`crates/gateway/tests/routing_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyFcl51CLNIAaJj5Dcm:-NyL3GBq2EQdNGF9h8Ix:b-nl2w04) ([raw file](https://github.com/starkware-libs/mempool/blob/6cac4f2f09d24275530614fb6cbc2d3c97eaf22c/crates/gateway/tests/routing_test.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is it the same as in the other test? 
I guess we need a general test_utils.rs file for these kinds of things.

If it will change due to Ayelet's refactor, please add a TODO here as well.
</blockquote></details>

done, I will take it with her next week. seems to me that we need to have a separate file that concentrates the state, transactions and configs for tests.
maybe take the state_reader_test_utils.rs , rename to test_utils.rs and put it all there.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 4 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyPq0gE9DVPPRV1f4eM:-NyPq0gE9DVPPRV1f4eN:b-7ewfcq) ([raw file](https://github.com/starkware-libs/mempool/blob/91594bb77ddcc650d3fde74c31c4929224c7ea56/crates/gateway/src/rpc_state_reader_test.rs#L1)):*
> ```XML
> use assert_matches::assert_matches;
> ```

Related to this PR?
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyPovfDEoB5ZyNCKyi6:-NyPovfDEoB5ZyNCKyi7:brk1ztu) ([raw file](https://github.com/starkware-libs/mempool/blob/91594bb77ddcc650d3fde74c31c4929224c7ea56/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
> ```XML
>     pub fn run_validate(
>         &self,
>         state_reader_factory: Arc<dyn StateReaderFactory>,
> ```

Would this work?
Same in `get_latest_block_info`



_Suggestion:_
```XML
&dyn StateReaderFactory
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyPq0gE9DVPPRV1f4eM:-NyPrECo-J2vj0uVNOpM:b-30rqxl) ([raw file](https://github.com/starkware-libs/mempool/blob/91594bb77ddcc650d3fde74c31c4929224c7ea56/crates/gateway/src/rpc_state_reader_test.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Related to this PR?
</blockquote></details>

oops I did it again
removed now.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyPovfDEoB5ZyNCKyi6:-NyPr_bi5InOSncwJiux:bhgkpcv) ([raw file](https://github.com/starkware-libs/mempool/blob/91594bb77ddcc650d3fde74c31c4929224c7ea56/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Would this work?
Same in `get_latest_block_info`
</blockquote></details>

no , 
mismatched types
expected reference `&std::sync::Arc<(dyn state_reader::StateReaderFactory + 'static)>`
   found reference `&dyn state_reader::StateReaderFactory

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/146#-NyPovfDEoB5ZyNCKyi6:-NyUu14HEl_ntYgsIS-H:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/91594bb77ddcc650d3fde74c31c4929224c7ea56/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

no , 
mismatched types
expected reference `&std::sync::Arc<(dyn state_reader::StateReaderFactory + 'static)>`
   found reference `&dyn state_reader::StateReaderFactory
</blockquote></details>

done

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r4, 3 of 3 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146#-:-NyV-a9jAj-9J03_LNOr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @ayeletstarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 9 files at r3, 3 of 9 files at r4, 1 of 3 files at r5, 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/146)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
