### PR TITLE
feat(felt): support new felt

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/352)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 20 files at r1, 9 of 12 files at r6, 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/352)* status: 21 of 22 files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0si6FpCZNjfJDyTLss:-O0si6FpCZNjfJDyTLst:boj5vrn) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/mempool/src/mempool_test.rs#L17)):*
> ```XML
> /// Creates a valid input for mempool's `add_tx` with optional default values.
> /// Usage:
> /// 1. add_tx_input!(tip: 1, tx_hash: Felt::TWO, sender_address: 3_u8, nonce: 4)
> ```

It can be "0x3", right?



_Code quote:_
```XML
3_u8
```
___
*[`crates/test_utils/src/starknet_api_test_utils.rs` line 266 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0slQtc4RgHxHq640PI:-O0slQtc4RgHxHq640PJ:b3agbsc) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/test_utils/src/starknet_api_test_utils.rs#L266)):*
> ```XML
>     if invoke_args.version != TransactionVersion::THREE {
>         panic!("Unsupported transaction version: {:?}.", invoke_args.version);
>     }
> ```

Why was it changed to an if condition?



_Code quote:_
```XML
    if invoke_args.version != TransactionVersion::THREE {
        panic!("Unsupported transaction version: {:?}.", invoke_args.version);
    }
```
___
*[`crates/test_utils/src/starknet_api_test_utils.rs` line 287 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0slYG95holZ1IL6gJn:-O0slYG95holZ1IL6gJo:bb73xfv) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/test_utils/src/starknet_api_test_utils.rs#L287)):*
> ```XML
>     if deploy_tx_args.version != TransactionVersion::THREE {
>         panic!("Unsupported transaction version: {:?}.", deploy_tx_args.version);
>     }
> ```

Same



_Code quote:_
```XML
    if deploy_tx_args.version != TransactionVersion::THREE {
        panic!("Unsupported transaction version: {:?}.", deploy_tx_args.version);
    }
```
___
*[`crates/test_utils/src/starknet_api_test_utils.rs` line 310 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0sla5z7sVl4y8DI3M4:-O0sla5z7sVl4y8DI3M5:bb73xfv) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/test_utils/src/starknet_api_test_utils.rs#L310)):*
> ```XML
>     if declare_tx_args.version != TransactionVersion::THREE {
>         panic!("Unsupported transaction version: {:?}.", declare_tx_args.version);
>     }
> ```

Same



_Code quote:_
```XML
    if declare_tx_args.version != TransactionVersion::THREE {
        panic!("Unsupported transaction version: {:?}.", declare_tx_args.version);
    }
```
___
*[`crates/tests-integration/src/state_reader.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0slgEaDzQCX1TLVsjz:-O0slgEaDzQCX1TLVsk-:b-z8rwlc) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/tests-integration/src/state_reader.rs#L64)):*
> ```XML
>     let account_contract_cairo1 = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
>     let test_contract_cairo1 = FeatureContract::TestContract(CairoVersion::Cairo1);
>     let erc20_cairo1 = FeatureContract::ERC20(CairoVersion::Cairo1);
> ```

@ArniStarkware, can you approve this change please?



_Code quote:_
```XML
 let erc20_cairo1 = FeatureContract::ERC20(CairoVersion::Cairo1);
```

**Review by giladchase — CHANGES_REQUESTED** [review]
@MohammadNassar1 There seem to be multiple different fixes inside a single commit, this might make the review process take longer.

Can it be split to separate commits? 
Alternatively, is it possible to list the fixes made and how the PR should be reviewed?
Whichever's faster to do, since this is somewhat time-critical

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/352#-:-O0szdyx12r4gKwr5jH6:b-65ol59)* status: 21 of 22 files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`-- commits` line 7 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0sz_Ku6qPhVmk_t7p-):*
This commit message is no longer relevant, plz change to something generic.



_Code quote:_
```
  fix: make add_tx_input! support Felt
```

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/src/state_reader.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0slgEaDzQCX1TLVsjz:-O0wN8QQE-vktGXQGFQi:b-9fb24y) ([raw file](https://github.com/starkware-libs/mempool/blob/2a8e5f74c7590144fdfd2c48621cf886c7ccbf36/crates/tests-integration/src/state_reader.rs#L64)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@ArniStarkware, can you approve this change please?
</blockquote></details>

approved.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/352)* status: 20 of 22 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/352)* status: 15 of 22 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 96 at r9](https://reviewable.io/reviews/starkware-libs/mempool/352#-O0x0IQo7tirx-TB1TPj:-O0x0IQo7tirx-TB1TPk:b-beqa2k) ([raw file](https://github.com/starkware-libs/mempool/blob/3b9d5b0baadcd041c095db675e26e30c5a2c36a9/crates/gateway/src/state_reader_test_utils.rs#L96)):*
> ```XML
>             blockifier_state_reader: state_reader.state,
>         },
>     }
> ```

@elintul , I think this is the only change unrelated to felt.



_Code quote:_
```XML
    let state_reader = test_state(
        block_context.chain_info(),
        account_balance,
        &[(account_contract, 1), (test_contract, 1)],
    );

    TestStateReaderFactory {
        state_reader: TestStateReader {
            block_info: block_context.block_info().clone(),
            blockifier_state_reader: state_reader.state,
        },
    }
```

**Pull request closed without merging**
