### PR TITLE
feat(mempool): implement commit-block first part that removes txs fro…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…m queue

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1ODUQj3JXjs7tNF2LV:-O1ODUQj3JXjs7tNF2LW:b-5w9jcb) ([raw file](https://github.com/starkware-libs/mempool/blob/0d1ff9d4ad332f297f35525c583e606514e74656/crates/mempool/src/mempool.rs#L76)):*
> ```XML
>     ) -> MempoolResult<()> {
>         for (sender_address, AccountState { nonce }) in state_changes {
>             // remove transactions from queue in case of reverted transactions.
> ```

To emphasize that they are _not_ removed from the pool, it took me a moment to realize this wasn't a bug.

We might wanna consider encapsulating the phases into private functions/methods somewhere, but let's leave that for the refactoring phase.



_Suggestion:_
```XML
            // dequeue transactions from queue in case of reverted transactions.
```
___
*[`crates/mempool/src/mempool.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1ODrOuCN61DX2ezGvw:-O1ODrOuCN61DX2ezGvx:b22s3vn) ([raw file](https://github.com/starkware-libs/mempool/blob/0d1ff9d4ad332f297f35525c583e606514e74656/crates/mempool/src/mempool.rs#L76)):*
> ```XML
>     ) -> MempoolResult<()> {
>         for (sender_address, AccountState { nonce }) in state_changes {
>             // remove transactions from queue in case of reverted transactions.
> ```

Should reverted -> rejected?



_Code quote:_
```XML
reverted transactions.
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1Qenuo5EAyqqDSHuTu:-O1Qenuo5EAyqqDSHuTv:b-cj544r) ([raw file](https://github.com/starkware-libs/mempool/blob/0eb6a200461c0ef85cf6cc6c6cd795fbd3ae0292/crates/mempool/src/mempool.rs#L81)):*
> ```XML
>                     self.tx_queue.remove(sender_address);
>                 }
>             }
> ```

not 100% sure, it's one less indentation, but the if condition is now multiline.
@elintul  WDYT? 



_Suggestion:_
```XML
        for (sender_address, AccountState { nonce }) in state_changes {
            // dequeue transactions from the queue if they are no longer ready to be sent.
            if self
                .tx_queue
                .get_nonce(&sender_address)
                .is_some_and(|queue_nonce| *queue_nonce < nonce) {
                    self.tx_queue.remove(sender_address);
                }
            }
```
___
*[`crates/mempool/src/transaction_queue.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1Qf6Xv6hhJMBrZGimg:-O1Qf6Xv6hhJMBrZGimh:b-dbntof) ([raw file](https://github.com/starkware-libs/mempool/blob/0eb6a200461c0ef85cf6cc6c6cd795fbd3ae0292/crates/mempool/src/transaction_queue.rs#L48)):*
> ```XML
>     }
> 
>     pub fn get_nonce(&self, address: &ContractAddress) -> Option<&Nonce> {
> ```

`Copy` types.

Do on a separate PR plz.



_Suggestion:_
```XML
    pub fn get_nonce(&self, address: ContractAddress) -> Option<Nonce> {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1Qf6Xv6hhJMBrZGimg:-O1Qozf24bm2vv27bTmF:b-yi9vp4) ([raw file](https://github.com/starkware-libs/mempool/blob/0eb6a200461c0ef85cf6cc6c6cd795fbd3ae0292/crates/mempool/src/transaction_queue.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`Copy` types.

Do on a separate PR plz.
</blockquote></details>

Done
[PR](https://reviewable.io/reviews/starkware-libs/mempool/433)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1Qenuo5EAyqqDSHuTu:-O1Qq0hr7D8g0gG11MQJ:b3e3kss) ([raw file](https://github.com/starkware-libs/mempool/blob/0eb6a200461c0ef85cf6cc6c6cd795fbd3ae0292/crates/mempool/src/mempool.rs#L81)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

not 100% sure, it's one less indentation, but the if condition is now multiline.
@elintul  WDYT?
</blockquote></details>

I liked your suggestion.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RUz16Ce7FhZFUiZ9h:-O1RUz16Ce7FhZFUiZ9i:bmhah45) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L74)):*
> ```XML
>         &mut self,
>         state_changes: HashMap<ContractAddress, AccountState>,
>     ) -> MempoolResult<()> {
> ```

I think we should 
___
*[`crates/mempool/src/mempool.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RV_tyDuZq5ofn2Fs0:-O1RV_tyDuZq5ofn2Fs1:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L75)):*
> ```XML
>         state_changes: HashMap<ContractAddress, AccountState>,
>     ) -> MempoolResult<()> {
>         for (sender_address, AccountState { nonce }) in state_changes {
> ```





_Suggestion:_
```XML
address
```
___
*[`crates/mempool/src/mempool.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RVcVX0RPhXD60G7Ob:-O1RVcVX0RPhXD60G7Oc:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L80)):*
> ```XML
>                 .tx_queue
>                 .get_nonce(&sender_address)
>                 .is_some_and(|queue_nonce| *queue_nonce < nonce)
> ```





_Suggestion:_
```XML
queued_nonce
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RUz16Ce7FhZFUiZ9h:-O1RjjmQ6qWZ0ihWF33F:bu3n9je) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should
</blockquote></details>

... published prematurely, retracting.
___
*[`crates/mempool/src/mempool.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RjrCp2oVU90StYAn7:-O1RjrCp2oVU90StYAn8:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L76)):*
> ```XML
>     ) -> MempoolResult<()> {
>         for (sender_address, AccountState { nonce }) in state_changes {
>             // dequeue transactions from the queue if they are no longer ready to be sent.
> ```





_Suggestion:_
```XML
            // Remove transactions with nonces older than those that have been committed to the block.
            // This part is relevant when the committed block originates from a different leader.
            
            // Dequeue old transaction from queue.
            for (sender_address, AccountState { nonce }) in state_changes {
```

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/mempool/420#-O1RjrCp2oVU90StYAn7:-O1Vj7UI1GhO32Xrlh39:bzicf5g) ([raw file](https://github.com/starkware-libs/mempool/blob/427cb35eb8bfeaab510fe07fb4efc8b4ede0ed29/crates/mempool/src/mempool.rs#L76)):*
> ```XML
>     ) -> MempoolResult<()> {
>         for (sender_address, AccountState { nonce }) in state_changes {
>             // dequeue transactions from the queue if they are no longer ready to be sent.
> ```

Hmm, note that transactions are removed from the queue not only if there is a different leader. and they are not necessarily old transactions.

We can also remove transactions from the queue if they are from the our own leader when a transaction is reverted, then a transaction with a larger nonce is not in the queue.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420#-:-O1WaSnq2CCi7ZiSoEoo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
