### PR TITLE
chore: rename gateway config to gateway network connection config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@lev-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110#-:-NxMfop1C7RQ4q6oEqvs:bw1gi4r)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxMmJ8s-gtL5BzpZxUs:-NxMmJ8s-gtL5BzpZxUt:bkk6srx) ([raw file](https://github.com/starkware-libs/mempool/blob/75fe266de777040f7d663faba4bc9c79fab3d3f5/crates/gateway/src/config.rs#L11)):*
> ```XML
> /// The gateway network related configuration.
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct GatewayNetworkConnectionConfig {
> ```

I think GatewayNetworkConfig is good enough. The word "Connection" adds nothing to the meaning of this config.



_Code quote:_
```XML
GatewayNetworkConnectionConfig
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/gateway/src/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxMmJ8s-gtL5BzpZxUs:-NxMwXyIAFfHTvirAbMk:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/8a0df87cf32f633da48bcb893da63ab72ab99199/crates/gateway/src/config.rs#L11)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I think GatewayNetworkConfig is good enough. The word "Connection" adds nothing to the meaning of this config.
</blockquote></details>

Done.

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config_test.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxNNRaq3CWM49u8B1cY:-NxNNRarBdz_CboOjy-D:b-k29f6l) ([raw file](https://github.com/starkware-libs/mempool/blob/f1715fa6e6954f82c97f2e34749b05344652aab4/crates/gateway/src/config_test.rs#L11)):*
> ```XML
> 
> const TEST_FILES_FOLDER: &str = "./src/json_files_for_testing";
> const CONFIG_FILE: &str = "gateway_network_connection_config.json";
> ```

gateway_network_config.json



_Code quote:_
```XML
gateway_network_connection_config.json
```
___
*[`crates/gateway/src/json_files_for_testing/gateway_network_connection_config.json` line 0 at r2](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxNNh2I-_LpPVnpDBgu:-NxNNh2I-_LpPVnpDBgv:bwdqa3i) ([raw file](https://github.com/starkware-libs/mempool/blob/f1715fa6e6954f82c97f2e34749b05344652aab4/crates/gateway/src/json_files_for_testing/gateway_network_connection_config.json#L0)):*
rename file to "gateway_network_config.json"

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxNNRaq3CWM49u8B1cY:-NxNPkkZ2d_v_oZ6B89Q:bk45099) ([raw file](https://github.com/starkware-libs/mempool/blob/f1715fa6e6954f82c97f2e34749b05344652aab4/crates/gateway/src/config_test.rs#L11)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

gateway_network_config.json
</blockquote></details>

Done. (Ctrl + F for word connection).
___
*[`crates/gateway/src/json_files_for_testing/gateway_network_connection_config.json` line  at r2](https://reviewable.io/reviews/starkware-libs/mempool/110#-NxNNh2I-_LpPVnpDBgu:-NxNPju15E2l-HtgW7ik:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f1715fa6e6954f82c97f2e34749b05344652aab4/crates/gateway/src/json_files_for_testing/gateway_network_connection_config.json#L)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

rename file to "gateway_network_config.json"
</blockquote></details>

Done.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110#-:-NxNQA5H7TtgAIKkK2zk:bnfp4nl)* status: 0 of 6 files reviewed, 3 unresolved discussions

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110#-:-NxfuXKBEOfNM5J0z2P3:bnfp4nl)* status: 0 of 6 files reviewed, 3 unresolved discussions

**Review by lev-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/110)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **May 12, 4:58 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/110).

**Pull request merged**
