### PR TITLE
test: generalize resource bounds related tests

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/45)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/45)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/mempool/45#-Nv_nZ2UESb1ezQQytl7:-Nv_nZ2UESb1ezQQytl8:b-rj9jvx) ([raw file](https://github.com/starkware-libs/mempool/blob/a9a28ee4beb6b130b07acc0dd549fb52cbeaee6f/crates/gateway/src/starknet_api_test_utils.rs#L66)):*
> ```XML
> }
> 
> pub const NON_EMPTY_RSOURCE_BOUNDS: ResourceBounds = ResourceBounds {
> ```

RESOURCE



_Code quote:_
```XML
RSOURCE
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/45)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/mempool/45#-Nv_nZ2UESb1ezQQytl7:-Nv_qg3T3ZmWrHn6HunQ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a9a28ee4beb6b130b07acc0dd549fb52cbeaee6f/crates/gateway/src/starknet_api_test_utils.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

RESOURCE
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/45#-:-Nv_rHY-ESELT_VkTSw5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/45#-:-Nva1HCAA6CzgFdmTU7Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
