### PR TITLE
feat: check for invalid seirra version in stateless validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#247** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#248** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/248?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_5wd8-X3TY4RfCPvL:-O-_5wd8-X3TY4RfCPvM:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/compiler_version.rs#L13)):*
> ```XML
> 
> impl From<VersionId> for CairoLangVersionId {
>     fn from(version: VersionId) -> Self {
> ```





_Suggestion:_
```XML
fn from(version: &VersionId) -> Self {
```
___
*[`crates/gateway/src/compiler_version.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_66otC7oYHhwaXVi-:-O-_66otC7oYHhwaXVi0:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/compiler_version.rs#L21)):*
> ```XML
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         let version_id: CairoLangVersionId = (*self).into();
>         version_id.fmt(f)
> ```





_Suggestion:_
```XML
        CairoLangVersionId::from(self).fmt(f)
```
___
*[`crates/gateway/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_6W3g2fNovx_R6sC6:-O-_6W3g2fNovx_R6sC7:b14uuie) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/lib.rs#L1)):*
> ```XML
> pub mod compiler_version;
> ```

Consider naming it `compiler_utils.rs` and then you can put there other compiler related code.



_Code quote:_
```XML
pub mod compiler_version;
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_zwGI0hqUa0vM5Ovm:-O-_zwGI0hqUa0vM5Ovn:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator.rs#L119)):*
> ```XML
>         sierra_program: &[StarkFelt],
>     ) -> StatelessTransactionValidatorResult<()> {
>         // TODO(Arni): Validate the sierra version is Supported.
> ```





_Suggestion:_
```XML
supported
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-a2fIo-Up0Q2KvFJYT:-O-a2fIo-Up0Q2KvFJYU:bswdi6j) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator.rs#L159)):*
> ```XML
> 
>     if length_of_version < 3 {
>         return Err(StatelessTransactionValidatorError::InvalidSierraVersion { version });
> ```

Here you return a wrong version in the error message right? if the version is shorter than 3, you complete it with default felts...
Consider making it a String instead if a vector, and if there is some `join` method over a vector to help you convert it to string.



_Code quote:_
```XML
return Err(StatelessTransactionValidatorError::InvalidSierraVersion { version });
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-a3ekuA1r06yQMxjcs:-O-a3ekuA1r06yQMxjct:brelc3i) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator_test.rs#L213)):*
> ```XML
>             stark_felt!(1_u128),
>             stark_felt!(3_u128),
>             stark_felt!(0x10000000000000000_u128), // Does not fit into a usize.
> ```

Can you explain?



_Code quote:_
```XML
stark_felt!(0x10000000000000000_u128)
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_5wd8-X3TY4RfCPvL:-O-aUib1CewZPEmq50SR:bmfxpif) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/compiler_version.rs#L13)):*
> ```XML
> 
> impl From<VersionId> for CairoLangVersionId {
>     fn from(version: VersionId) -> Self {
> ```

Done.
___
*[`crates/gateway/src/compiler_version.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_66otC7oYHhwaXVi-:-O-aV3ecD94gZt6NzlEa:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/compiler_version.rs#L21)):*
> ```XML
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         let version_id: CairoLangVersionId = (*self).into();
>         version_id.fmt(f)
> ```

Done.
___
*[`crates/gateway/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_6W3g2fNovx_R6sC6:-O-aTyiA0VP6HmEnhWzV:b-30lqat) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/lib.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider naming it `compiler_utils.rs` and then you can put there other compiler related code.
</blockquote></details>

I like the fact there is a small file dedicated to that.
It is nice and self-contained. It will get bigger in #247.

It is similar to how `cairo_lang_starknet_classes::compiler_version` is structured.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-_zwGI0hqUa0vM5Ovm:-O-aVEJE7CPEX2sWdOdJ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator.rs#L119)):*
> ```XML
>         sierra_program: &[StarkFelt],
>     ) -> StatelessTransactionValidatorResult<()> {
>         // TODO(Arni): Validate the sierra version is Supported.
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-a2fIo-Up0Q2KvFJYT:-O-euAJLDONysHofp8Ug:bfl408n) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator.rs#L159)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Here you return a wrong version in the error message right? if the version is shorter than 3, you complete it with default felts...
Consider making it a String instead if a vector, and if there is some `join` method over a vector to help you convert it to string.
</blockquote></details>

Done.

Redesigned.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-a3ekuA1r06yQMxjcs:-O-aXWue2FgFBG2t4xPI:b-bg4s4a) ([raw file](https://github.com/starkware-libs/mempool/blob/58327dcde7cdf6b7660e170a56dab81595ce95bf/crates/gateway/src/stateless_transaction_validator_test.rs#L213)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you explain?
</blockquote></details>

Done.
I changed the name of the case.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pFr4I4T485leBzr5u:-O-pFr4I4T485leBzr5v:b8zjvu7) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L7)):*
> ```XML
> #[derive(Debug)]
> pub enum VersionIdError {
>     InvalidVersion { index: usize, felt_status: String },
> ```

The exact formatting can be decided when constructing the error.



_Suggestion:_
```XML
status: String
```
___
*[`crates/gateway/src/compiler_version.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pIJLkEUtVzqK37dVC:-O-pIJLkEUtVzqK37dVD:bkjigeo) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L32)):*
> ```XML
> impl VersionId {
>     pub fn from_sierra_program(sierra_program: &[StarkFelt]) -> Result<Self, VersionIdError> {
>         let length_of_version = sierra_program.len();
> ```

This is the length of the program.



_Code quote:_
```XML
length_of_version
```
___
*[`crates/gateway/src/compiler_version.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pIUTMC4dka-YyCzLB:-O-pIUTMC4dka-YyCzLC:b-qtxkpt) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L41)):*
> ```XML
>         }
> 
>         fn get_version_component_from_sierra_program(
> ```

We are already in the context of the `from_sierra_program` method, plus the input arguments of this function state it as well.



_Suggestion:_
```XML
get_version_component
```
___
*[`crates/gateway/src/errors.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-p9lMg5lD8u7QkekCS:-O-p9lMhC3vYyi1tBvua:bcjh1r9) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/errors.rs#L51)):*
> ```XML
>     )]
>     SignatureTooLong { signature_length: usize, max_signature_length: usize },
>     #[error("Invalid Sierra version: felt at index {index} is {felt_status}.")]
> ```

IIUC, you can define the error message in the VersionIdError, mark this error with `#[error(transparent)]`, and than you won't need the From impl below.



_Code quote:_
```XML
#[error("Invalid Sierra version: felt at index {index} is {felt_status}.")]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pFr4I4T485leBzr5u:-O07P63e19AHHBigsxmF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L7)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The exact formatting can be decided when constructing the error.
</blockquote></details>

Done.
___
*[`crates/gateway/src/compiler_version.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pIJLkEUtVzqK37dVC:-O07PCfp6IYmz3B3_gls:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L32)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This is the length of the program.
</blockquote></details>

Done.
___
*[`crates/gateway/src/compiler_version.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-pIUTMC4dka-YyCzLB:-O07PHs2-tVBI33__mM-:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/compiler_version.rs#L41)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We are already in the context of the `from_sierra_program` method, plus the input arguments of this function state it as well.
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/mempool/248#-O-p9lMg5lD8u7QkekCS:-O07PK57EFGe0J5aWX7W:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e9123c0559372576d9f0c30d224a726bde8e99e6/crates/gateway/src/errors.rs#L51)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

IIUC, you can define the error message in the VersionIdError, mark this error with `#[error(transparent)]`, and than you won't need the From impl below.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/mempool/248#-O0Cv4C26TVSeUEfO5ZN:-O0Cv4C26TVSeUEfO5ZO:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/52da14a04e499428e49baeced239b24c0c7e0fd4/crates/gateway/src/compiler_version.rs#L53)):*
> ```XML
>             let felt = sierra_program[index];
>             felt.try_into().map_err(|_| VersionIdError::InvalidVersion {
>                 message: format!("Felt at index {index} out of range of usize. Got: {}", felt),
> ```





_Suggestion:_
```XML
version contains a value that is out of range: {}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/mempool/248#-O0Cv4C26TVSeUEfO5ZN:-O0DSyfx4uoM4byRDTH7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/52da14a04e499428e49baeced239b24c0c7e0fd4/crates/gateway/src/compiler_version.rs#L53)):*
> ```XML
>             let felt = sierra_program[index];
>             felt.try_into().map_err(|_| VersionIdError::InvalidVersion {
>                 message: format!("Felt at index {index} out of range of usize. Got: {}", felt),
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/248#-:-O0DUA3OA4NXU8J39Kam:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
