### PR TITLE
refactor: return an error in case response deserialization fails

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/377)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/377#-:-O1BMcSp7oMxqtMmPH7a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/377#-O1BMWdv3czEgSzE5yR_:-O1BMWdw1MrmECJSj5kF:biom0jk) ([raw file](https://github.com/starkware-libs/mempool/blob/0fa3cf659501ebc7b820c1463ededc93ffe7f604/crates/mempool_infra/src/component_client.rs#L125)):*
> ```XML
>     #[error("Got an unexpected response type.")]
>     UnexpectedResponse,
>     #[error("Could not deserialize response from server.")]
> ```

Please change to "server response"



_Code quote:_
```XML
response from server
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/377)* status: all files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/377#-O1BMo3w-vw0nl0lz8-y:-O1BMo3w-vw0nl0lz8-z:b-e2wnwg) ([raw file](https://github.com/starkware-libs/mempool/blob/0fa3cf659501ebc7b820c1463ededc93ffe7f604/crates/mempool_infra/src/component_client.rs#L96)):*
> ```XML
>             .await
>             .map_err(ClientError::ResponseParsingFailure)?;
>         deserialize(&body_bytes).map_err(|_e| ClientError::ResponseDeserializationFailure)
> ```

Can the error `_e` be in `ClientError::ResponseDeserializationFailure`?



_Code quote:_
```XML
.map_err(|_e| ClientError::ResponseDeserializationFailure)
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/377)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/377#-O1BMo3w-vw0nl0lz8-y:-O1BN3vJDQYSIyqfqARG:b-9716jw) ([raw file](https://github.com/starkware-libs/mempool/blob/0fa3cf659501ebc7b820c1463ededc93ffe7f604/crates/mempool_infra/src/component_client.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can the error `_e` be in `ClientError::ResponseDeserializationFailure`?
</blockquote></details>

I can convert it to string, is that fine?
___
*[`crates/mempool_infra/src/component_client.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/377#-O1BMWdv3czEgSzE5yR_:-O1BNXg55VzVFOsNPnr8:b32wtd) ([raw file](https://github.com/starkware-libs/mempool/blob/0fa3cf659501ebc7b820c1463ededc93ffe7f604/crates/mempool_infra/src/component_client.rs#L125)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to "server response"
</blockquote></details>

ok

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/377#-:-O1BQhYg8BSRCmPVQWdk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
