### PR TITLE
feat: new infra

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:37fff159

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)

### CODE REVIEW

**Review by uriel-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-Xaaj-dPSq0Hl6jyE:-Ny-Xaaj-dPSq0Hl6jyF:b-sq7ox0) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L14)):*
> ```XML
> }
> 
> // todo remove the static constraints
> ```

I don't see any static constraint. no need for that comment



_Code quote:_
```XML
// todo remove the static constraints
```
___
*[`crates/mempool_infra/src/component_client.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-ZbYkD2kRKlq6IDH8:-Ny-ZbYkD2kRKlq6IDH9:b-9ztedp) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L31)):*
> ```XML
>             tx: res_tx,
>         };
>         self.tx.send(message_and_res_tx).await.unwrap();
> ```

Handle unwrap more gracefully



_Code quote:_
```XML
self.tx.send(message_and_res_tx).await.unwrap();
```
___
*[`crates/mempool_infra/src/component_client.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-ZvRB4xg8fGvaaRKL:-Ny-ZvRB4xg8fGvaaRKM:b-ppv5ut) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L33)):*
> ```XML
>         self.tx.send(message_and_res_tx).await.unwrap();
> 
>         res_rx.recv().await.unwrap()
> ```

Handle unwrap more gracefully.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/mempool_infra/src/component_server.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-a54v8zeX87mO5_J-:-Ny-a54v8zeX87mO5_J0:b-rmeynt) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L6)):*
> ```XML
> #[async_trait]
> pub trait ComponentMessageExecutor<M, R> {
>     async fn execute(&self, message: M) -> R;
> ```

Just a suggestion: change the return type into Result<R, E> with a dedicated error type, and then in the test, if you catch an error, fail.



_Code quote:_
```XML
async fn execute(&self, message: M) -> R;
```
___
*[`crates/mempool_infra/src/component_server.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-YY_hC5NzeDxH1Lp8:-Ny-YY_hC5NzeDxH1Lp9:b-xjum7n) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L40)):*
> ```XML
>     pub async fn start(&mut self) {
>         loop {
>             let message_and_res_tx = self.rx.recv().await.unwrap();
> ```

Change this to while let statement



_Suggestion:_
```XML
        while let Some(message_and_res_tx) = self.rx.recv().await {
```
___
*[`crates/mempool_infra/src/component_server.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-afBwCH9Qlpi8JI4Z:-Ny-afBwCH9Qlpi8JI4_:b-6atdbo) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L45)):*
> ```XML
>             let tx = message_and_res_tx.tx;
> 
>             let res = self.component.execute(message).await;
> ```

If you take my suggestion to modify the return type to Result, then add a ? and change the return type of this function as well and catch the error in the test



_Code quote:_
```XML
let res = self.component.execute(message).await;
```
___
*[`crates/mempool_infra/src/component_server.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-Zyb98kdHYl-5DNA6:-Ny-Zyb98kdHYl-5DNA7:b-ppv5ut) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L47)):*
> ```XML
>             let res = self.component.execute(message).await;
> 
>             tx.send(res).await.unwrap();
> ```

Handle unwrap more gracefully.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-b_fiCLj-LpkYZv4p:-Ny-b_fiCLj-LpkYZv4q:bq1ns9b) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server_client_test.rs#L167)):*
> ```XML
>     task::spawn(async move {
>         component_b_server.start().await;
>     });
> ```

Continuing with my suggestion the test should fail if the start functions return errors



_Code quote:_
```XML
    task::spawn(async move {
        component_a_server.start().await;
    });

    task::spawn(async move {
        component_b_server.start().await;
    });
```

**Review by uriel-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0XZ250apmcAT_Dnny:-Ny0XZ250apmcAT_Dnnz:bfmexa) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L48)):*
> ```XML
> #[derive(Copy, Clone, Debug, PartialEq, Eq)]
> pub enum ComponentAMessages {
>     GetValue,
> ```

I think the enum should be a mirror to the component's functions. So something like FuncA will describe better the message. But FuncA also doesn't sound good to me as it's obviously a function of compA so maybe change func_a function to something like get_value instead and leave this line as is.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0YcX194lZE7h_5UHS:-Ny0YcX194lZE7h_5UHT:bqv4nh2) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L95)):*
> ```XML
> #[derive(Copy, Clone, Debug, PartialEq, Eq)]
> pub enum ComponentBMessages {
>     GetShmalue,
> ```

Same as with GetValue, either change the name of this to relate to func_b or the better option, in my opinion, is to change the func_b name into get_shmalue
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0WFj504LtrNz1M8Hv:-Ny0WFj504LtrNz1M8Hw:b4g79lm) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L135)):*
> ```XML
>     match res {
>         ComponentAResponses::Value(value) => {
>             assert_eq!(value, 30);
> ```

looking at the name of the function, I assume the value you expect should be passed as the expected value from the main function, i.e 30 -> expected_response_value
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0WlUl2oAjwGEBZKgO:-Ny0WlUl2oAjwGEBZKgP:bi55m9r) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L151)):*
> ```XML
> 
>     let component_a = ComponentA::new(Box::new(b_client));
>     let component_b = ComponentB::new(30, Box::new(a_client));
> ```

30 should be in a variable and probably be passed to the verify_response function as the to-be-verified response value

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-Xaaj-dPSq0Hl6jyE:-Ny07x5L8Fwv_2b9HSQD:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L14)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I don't see any static constraint. no need for that comment
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-ZbYkD2kRKlq6IDH8:-Ny07y6kBe5DGY-W1YgJ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L31)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Handle unwrap more gracefully
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-ZvRB4xg8fGvaaRKL:-Ny07yiJ5-yYiAyc3p1z:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_client.rs#L33)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Handle unwrap more gracefully.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-a54v8zeX87mO5_J-:-Ny08LLi25gIoLrL-Kcp:bm97xaa) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L6)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Just a suggestion: change the return type into Result<R, E> with a dedicated error type, and then in the test, if you catch an error, fail.
</blockquote></details>

Not following on the suggestion: 
`R` is the return type of the trait function whose invocation is depicted by `message :M`; it can be of any type, including one that captures potential errors, e.g., `Result<FuncRes,FuncErr>`.

What type of errors do you expect to handle? What would be their handling aside from propagating the panic upwards?
___
*[`crates/mempool_infra/src/component_server.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-YY_hC5NzeDxH1Lp8:-Ny09dSJ7pqh5PXxdvGm:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L40)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Change this to while let statement
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-Zyb98kdHYl-5DNA6:-Ny0A06s3v8WYpeFTewq:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L47)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Handle unwrap more gracefully.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-b_fiCLj-LpkYZv4p:-Ny0ACWGA2S5d4s83TWs:bkisvsl) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server_client_test.rs#L167)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Continuing with my suggestion the test should fail if the start functions return errors
</blockquote></details>

What suggestion? The only one I noticed regards the return type of `execute`, not of `start`. Anyhow, `start` should not fail, and I'd want the code to panic if it does.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-a54v8zeX87mO5_J-:-Ny0e5eCDWbVlWn5mQzX:bwleagi) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server.rs#L6)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not following on the suggestion: 
`R` is the return type of the trait function whose invocation is depicted by `message :M`; it can be of any type, including one that captures potential errors, e.g., `Result<FuncRes,FuncErr>`.

What type of errors do you expect to handle? What would be their handling aside from propagating the panic upwards?
</blockquote></details>

You are right, nothing to gain from this suggestion, I retract it
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny-b_fiCLj-LpkYZv4p:-Ny0dSXlBUwClTiC5jTl:b-9mxa05) ([raw file](https://github.com/starkware-libs/mempool/blob/5ec32ac249b8e8b4e86fbed728c389e145c7bc96/crates/mempool_infra/src/component_server_client_test.rs#L167)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What suggestion? The only one I noticed regards the return type of `execute`, not of `start`. Anyhow, `start` should not fail, and I'd want the code to panic if it does.
</blockquote></details>

I was referring to the suggestion of returning an error in the execute function. But I get it, start should not fail

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0XZ250apmcAT_Dnny:-Ny0dkfbBw4vi2GQRGR3:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L48)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I think the enum should be a mirror to the component's functions. So something like FuncA will describe better the message. But FuncA also doesn't sound good to me as it's obviously a function of compA so maybe change func_a function to something like get_value instead and leave this line as is.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0YcX194lZE7h_5UHS:-Ny0dlYM4Wq8D9rFMIgN:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L95)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Same as with GetValue, either change the name of this to relate to func_b or the better option, in my opinion, is to change the func_b name into get_shmalue
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0WFj504LtrNz1M8Hv:-Ny0eQ2N-7ZvvJ5fMCXq:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L135)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

looking at the name of the function, I assume the value you expect should be passed as the expected value from the main function, i.e 30 -> expected_response_value
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/mempool/136#-Ny0WlUl2oAjwGEBZKgO:-Ny0eRA3-Wj2adbCPNMJ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5bfe842255fda21f52d3a67f30557737eb86e0cf/crates/mempool_infra/src/component_server_client_test.rs#L151)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

30 should be in a variable and probably be passed to the verify_response function as the to-be-verified response value
</blockquote></details>

Done.

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136#-:-Ny0id0vCmi-7u62K8VF:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/136)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
