### PR TITLE
chore: move faulty account sierra file to test utils

### PR DESCRIPTION
**Pull request by ArniStarkware**
chore: move AddressPriorityQueue to pool (#313)

Subsequent commits will use the switch the inner type of txs_by_account
and use it there, also rename.

commit-id:30696bc0

Co-authored-by: Gilad Chase <gilad@starkware.com>

refactor: rename address pq (#314)

New name better implies this being a transaction index, rather than an
address index.

commit-id:ecb46826

Co-authored-by: Gilad Chase <gilad@starkware.com>

refactor(mempool): rename tx_queue (#323)

feat(mempool): implement iter method for mempool (#322)

feat: add out-of-order support to account tx index (#315)

Since this now supports out of order (and holes in particular), no
invariants on the inner type are necessary, and so no API interface is
strictly necessary.

Subsequent commits will extract logic from inside tx pool into methods
again.

commit-id:06539624

Co-authored-by: Gilad Chase <gilad@starkware.com>

feat: add AccountTransactionIndex insert (#316)

Until we support fee escalation, this should always return None.

Subsequent PRs will use this DS, and panic if `Some` is returned.

commit-id:b0eee880

Co-authored-by: Gilad Chase <gilad@starkware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/327)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#327** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/327?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
Sorry about the dirty discription.

All that happens here is that the file used for tests is moved.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/327#-:-O0eMp4-9ZrrGmG-YbhO:bwvj6gl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/test_utils/src/lib.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/mempool/327#-O0eN1Kk1KEbiAP3XtyX:-O0eN1Kk1KEbiAP3XtyY:b-wp31i0) ([raw file](https://github.com/starkware-libs/mempool/blob/a035ee28df505eba628c975b863f78bb23e80fbf/crates/test_utils/src/lib.rs#L6)):*
> ```XML
> pub const TEST_FILES_FOLDER: &str = "crates/test_utils/test_files";
> pub const CONTRACT_CLASS_FILE: &str = "contract_class.json";
> pub const FAULTY_ACCOUNT_CLASS_FILE: &str = "faulty_account.sierra.json";
> ```

We can consider removing one of these files. They do very similar work.
(A job for another PR).



_Code quote:_
```XML
pub const CONTRACT_CLASS_FILE: &str = "contract_class.json";
pub const FAULTY_ACCOUNT_CLASS_FILE: &str = "faulty_account.sierra.json";
```

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/327)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`crates/test_utils/src/lib.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/mempool/327#-O0eN1Kk1KEbiAP3XtyX:-O0hd5X-8RsaCl3sr1JD:b-83ed9l) ([raw file](https://github.com/starkware-libs/mempool/blob/a035ee28df505eba628c975b863f78bb23e80fbf/crates/test_utils/src/lib.rs#L6)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We can consider removing one of these files. They do very similar work.
(A job for another PR).
</blockquote></details>

Agreed, 
btw , it is the same json stored in the blockifier repo , right?
we need to find a way to store it in one place. maybe should do this once we move to the mono-repo.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
