### PR TITLE
refactor(mempool): test that get_txs return an empty vector when no t…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…xs left

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/367#-O1Ha7DK-tztHHS1Innb:-O1Ha7DK-tztHHS1Innc:b-7dxd0m) (no related file):*
Can you explain why we need this test?

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/367#-O1Ha7DK-tztHHS1Innb:-O1KwcUBBisD8ZTZKdFM:b-wlz3ib) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you explain why we need this test?
</blockquote></details>

This test's purpose is to ensure that requesting the mempool for transactions when it is empty does not cause issues or panics. Instead, it should simply return an empty vector.

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/367#-O1Ha7DK-tztHHS1Innb:-O1O6j1kDCPUjpHybqe7:b-f7lgo6) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This test's purpose is to ensure that requesting the mempool for transactions when it is empty does not cause issues or panics. Instead, it should simply return an empty vector.
</blockquote></details>

It was extracted from [this PR](https://reviewable.io/reviews/starkware-libs/mempool/254) IIUC.
See comments about it there plz and implement here.

___

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/367#-O1Ha7DK-tztHHS1Innb:-O1WsRN70KCjDCG3oz4G:bjg3dvk) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It was extracted from [this PR](https://reviewable.io/reviews/starkware-libs/mempool/254) IIUC.
See comments about it there plz and implement here.
</blockquote></details>

I think this test can be separated. Currently, you're running the empty mempool for all cases, which I believe is unnecessary.

___

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/367#-O1Ha7DK-tztHHS1Innb:-O1vj5yE-yXPe4HKAwVk:b-3rygd3) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think this test can be separated. Currently, you're running the empty mempool for all cases, which I believe is unnecessary.
</blockquote></details>

What did you decide? This PR is getting stale.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/mempool/367#-O2TOd7q1PvDyM3axfnD:-O2TOd7q1PvDyM3axfnE:b-5dufv0) ([raw file](https://github.com/starkware-libs/mempool/blob/bc2634c639ee8f2010c78ab3cf95163786fff546/crates/mempool/src/mempool_test.rs#L173)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_clear_mempool() {
> ```

Isn't it [this](https://github.com/starkware-libs/mempool/blob/ab4d6c9700091f82877a71938af938af3d5088fc/crates/mempool/src/mempool_test.rs#L145) case?



_Code quote:_
```XML
test_get_txs_clear_mempool
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/367)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/mempool/367#-O2TOd7q1PvDyM3axfnD:-O2Y_GM88YexLET9XFib:b-prrdc5) ([raw file](https://github.com/starkware-libs/mempool/blob/bc2634c639ee8f2010c78ab3cf95163786fff546/crates/mempool/src/mempool_test.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't it [this](https://github.com/starkware-libs/mempool/blob/ab4d6c9700091f82877a71938af938af3d5088fc/crates/mempool/src/mempool_test.rs#L145) case?
</blockquote></details>

correct. closing the PR.

**Pull request closed without merging**
