### PR TITLE
test: add empty test for client/server rpc implementation

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/lib.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/190#-Nz3XooA0gNmJPdV3c0M:-Nz3XooA0gNmJPdV3c0N:b-v3j495) ([raw file](https://github.com/starkware-libs/mempool/blob/18f03e64c290d521f34c6b43382d9867210dd7e4/crates/mempool_infra/src/lib.rs#L20)):*
> ```XML
> 
> #[cfg(test)]
> mod component_rpc_server_client_test;
> ```

We're transitioning to the common practice test inclusion format: `lib.rs` includes the functionality modules, and each of them includes its relevant test file.
Just merged the pr you LGTMed, please rebase over it for inspiration :-)



_Code quote:_
```XML
#[cfg(test)]
mod component_rpc_server_client_test;
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/lib.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/190#-Nz3XooA0gNmJPdV3c0M:-Nz3bVVz7eYYgNNe9WW7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/18f03e64c290d521f34c6b43382d9867210dd7e4/crates/mempool_infra/src/lib.rs#L20)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We're transitioning to the common practice test inclusion format: `lib.rs` includes the functionality modules, and each of them includes its relevant test file.
Just merged the pr you LGTMed, please rebase over it for inspiration :-)
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client_rpc.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/mempool/190#-NzMRfR13YR-QrNJoay4:-NzMRfR13YR-QrNJoay5:bpzpl7w) ([raw file](https://github.com/starkware-libs/mempool/blob/b2e07cc1d0c016259a0e1d916140da023bef11a1/crates/mempool_infra/src/component_client_rpc.rs#L3)):*
> ```XML
> #[cfg(test)]
> #[path = "component_rpc_server_client_test.rs"]
> mod component_rpc_server_client_test;
> ```

Writing here but it is a general comment: please be consistent with the names.
Either `component_rpc_*` or `component_*_rpc`, but don't mix. I prefer the latter.



_Code quote:_
```XML
mod component_rpc_server_client_test;
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190#-:-NzNhd0RC_NqM6US2yXv:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/190)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
