### PR TITLE
feat(mempool): implement remove method for transaction queue

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1MjHdQB6w0vEO44O0K:-O1MjHdQB6w0vEO44O0L:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/3b579deaaf2b5607d6351b4db16cc892f450ea0d/crates/mempool/src/transaction_queue.rs#L52)):*
> ```XML
>     }
> 
>     /// At most one transaction is associated with a single address in the queue.
> ```





_Suggestion:_
```XML
/// Removes the transaction of the given account address from the queue. 
/// This is well-defined, since there is at most one transaction per address in the queue.
```
___
*[`crates/mempool/src/transaction_queue.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1MjEbaEvo9g5R_w8ZQ:-O1MjEbb1fq1GmYXNGtW:b9r18rj) ([raw file](https://github.com/starkware-libs/mempool/blob/3b579deaaf2b5607d6351b4db16cc892f450ea0d/crates/mempool/src/transaction_queue.rs#L53)):*
> ```XML
> 
>     /// At most one transaction is associated with a single address in the queue.
>     pub fn _remove(mut self, address: &ContractAddress) -> Option<TransactionReference> {
> ```

Temporary name until used?



_Code quote:_
```XML
_remove
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1MlsoF6x6LjjECvjsD:-O1MlsoG5ogOgtOvIor3:b-9a555p) ([raw file](https://github.com/starkware-libs/mempool/blob/3b579deaaf2b5607d6351b4db16cc892f450ea0d/crates/mempool/src/transaction_queue.rs#L53)):*
> ```XML
> 
>     /// At most one transaction is associated with a single address in the queue.
>     pub fn _remove(mut self, address: &ContractAddress) -> Option<TransactionReference> {
> ```

Pass `self` by reference, while `address` is `Copy` so no need.



_Suggestion:_
```XML
&mut self, address: ContractAddress
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1MjEbaEvo9g5R_w8ZQ:-O1MokfP4FbZdSQIp4P3:b-tuik1l) ([raw file](https://github.com/starkware-libs/mempool/blob/3b579deaaf2b5607d6351b4db16cc892f450ea0d/crates/mempool/src/transaction_queue.rs#L53)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Temporary name until used?
</blockquote></details>

Exactly
___
*[`crates/mempool/src/transaction_queue.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1MlsoF6x6LjjECvjsD:-O1MozF3-V8KWK-fV1-X:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3b579deaaf2b5607d6351b4db16cc892f450ea0d/crates/mempool/src/transaction_queue.rs#L53)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass `self` by reference, while `address` is `Copy` so no need.
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1O8Su03BUWjhhgFf1y:-O1O8Su03BUWjhhgFf1z:b-hflwx9) ([raw file](https://github.com/starkware-libs/mempool/blob/c4e5e4b2b1f829679c474078828638f52a100ddf/crates/mempool/src/transaction_queue.rs#L58)):*
> ```XML
>             self.queue.remove(&tx.into());
>             tx
>         })
> ```

I like the chaining attempt, but it's best to keep side-effects away from `map`; it's intended goal is for transformation, rather than side-effects.



_Suggestion:_
```XML
        let tx = self.address_to_tx.remove(&address)?
        
        self.queue.remove(&tx.into());
        tx
        
        /// Technically this will also work, but this feels more complicated.
        // let tx = self.address_to_tx.remove(&address)?;
        // self.queue.take(&tx.into()).map(|tx| tx.0)
        
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1O8Su03BUWjhhgFf1y:-O1QU-BQCz07h5FUMBDO:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c4e5e4b2b1f829679c474078828638f52a100ddf/crates/mempool/src/transaction_queue.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I like the chaining attempt, but it's best to keep side-effects away from `map`; it's intended goal is for transformation, rather than side-effects.
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412#-:-O1Qcx8r1WlWF1triJt-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1RVt-JC4v0PP_v0DnQ:-O1RVt-JC4v0PP_v0DnR:bopku1j) ([raw file](https://github.com/starkware-libs/mempool/blob/7ad772601eaa6fe72b99ec904f3cec76fdebfde9/crates/mempool/src/transaction_queue.rs#L54)):*
> ```XML
>     /// Removes the transaction of the given account address from the queue.
>     /// This is well-defined, since there is at most one transaction per address in the queue.
>     pub fn _remove(&mut self, address: ContractAddress) -> Option<TransactionReference> {
> ```

I don't think we should return the reference, maybe a `bool` is enough?



_Code quote:_
```XML
Option<TransactionReference>
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1RVt-JC4v0PP_v0DnQ:-O1RZi2kEiPIqYHqFQ39:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/7ad772601eaa6fe72b99ec904f3cec76fdebfde9/crates/mempool/src/transaction_queue.rs#L54)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't think we should return the reference, maybe a `bool` is enough?
</blockquote></details>

Done

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1RVt-JC4v0PP_v0DnQ:-O1R_Agu8XQ03qNrYQpz:b-q807l4) ([raw file](https://github.com/starkware-libs/mempool/blob/7ad772601eaa6fe72b99ec904f3cec76fdebfde9/crates/mempool/src/transaction_queue.rs#L54)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done
</blockquote></details>

WDYT about:
```rs
self.address_to_tx.remove(&address).map_or(false, |tx| self.queue.remove(&tx.into()))
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1RVt-JC4v0PP_v0DnQ:-O1RbFIz76jA_DfLc8SA:b-q4v7t4) ([raw file](https://github.com/starkware-libs/mempool/blob/7ad772601eaa6fe72b99ec904f3cec76fdebfde9/crates/mempool/src/transaction_queue.rs#L54)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about:
```rs
self.address_to_tx.remove(&address).map_or(false, |tx| self.queue.remove(&tx.into()))
```
</blockquote></details>

But we said that we dont use `map` in this case, right?
and it's not a simple logic, it has a side effect.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/mempool/412#-O1RVt-JC4v0PP_v0DnQ:-O1RejFD4wMtvtsIpTHR:b-11hayr) ([raw file](https://github.com/starkware-libs/mempool/blob/7ad772601eaa6fe72b99ec904f3cec76fdebfde9/crates/mempool/src/transaction_queue.rs#L54)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But we said that we dont use `map` in this case, right?
and it's not a simple logic, it has a side effect.
</blockquote></details>

It's the `or` branch, the `map` side is pure. @giladchase - WDYT?

**Pull request merged**
