### PR TITLE
feat: add tx_pool checker for mempool test

### PR DESCRIPTION
**Pull request by giladchase**
- Requires adding accessors to the private tx_pools; these should not be
used outside of our own tests.

- Didn't add a standalone tx_pool checker, can't think of a reason to
  test the pool without the queue (but the reverse is sensible
  somewhat).

- New tester will soon be used to test multi-nonce

commit-id:ba871431

---

**Stack**:
- #429
- #428 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1NvsQ65CCj6WuhxE65:-O1NvsQ78IgXym2HEF3Y:b-7t7v4z) ([raw file](https://github.com/starkware-libs/mempool/blob/76655eb11cd3740e07cc138436c4d9618f823096/crates/mempool/src/mempool_test.rs#L59)):*
> ```XML
> // TODO(Ayelet): replace with MempoolState checker.
> #[track_caller]
> fn _check_mempool_state_eq(
> ```

FYI @ayeletstarkware i had to add this in order to properly test multi-nonce, if this is merged the intention is for you to kill it once you have something better.



_Code quote:_
```XML
// TODO(Ayelet): replace with MempoolState checker.
#[track_caller]
fn _check_mempool_state_eq(
```

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcHn16sN_9Nj-6fSk:-O1QcHn16sN_9Nj-6fSl:b9r18rj) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool.rs#L90)):*
> ```XML
> 
>     #[cfg(test)]
>     pub(crate) fn _tx_pool(&self) -> &TransactionPool {
> ```

Temporary name until used?



_Code quote:_
```XML
_tx_pool
```
___
*[`crates/mempool/src/mempool_test.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcO0l-CDy289TXz8E:-O1QcO0l-CDy289TXz8F:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L59)):*
> ```XML
> // TODO(Ayelet): replace with MempoolState checker.
> #[track_caller]
> fn _check_mempool_state_eq(
> ```





_Suggestion:_
```XML
_verify_mempool_state
```
___
*[`crates/mempool/src/mempool_test.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcSTVCcN7IiPduHsm:-O1QcSTVCcN7IiPduHsn:b32wzj) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L61)):*
> ```XML
> fn _check_mempool_state_eq(
>     mempool: &Mempool,
>     expected_txs: &[ThinTransaction],
> ```

x2



_Suggestion:_
```XML
expected_pool
```
___
*[`crates/mempool/src/mempool_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcVPt4fNT5uKcpMW6:-O1QcVPt4fNT5uKcpMW7:bt40k0b) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L66)):*
> ```XML
>     check_mempool_queue_eq(mempool, expected_queue);
> 
>     let expected_txs: HashMap<_, _> =
> ```

Do you think it's better here than a turbofish after `collect`?



_Code quote:_
```XML
: HashMap<_, _>
```
___
*[`crates/mempool/src/mempool_test.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QdPlP5CGDc2BZL7jw:-O1QdPlP5CGDc2BZL7jx:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L69)):*
> ```XML
>         expected_txs.iter().cloned().map(|tx| (tx.tx_hash, tx)).collect();
> 
>     assert_eq!(mempool._tx_pool()._tx_pool(), &expected_txs);
> ```





_Suggestion:_
```XML
        expected_txs.iter().cloned().map(|tx| (tx.tx_hash, tx)).collect();
    assert_eq!(mempool._tx_pool()._tx_pool(), &expected_txs);
```
___
*[`crates/mempool/src/transaction_pool.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QciN6EH0B1pGLBsDP:-O1QciN6EH0B1pGLBsDQ:bcgfe4h) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/transaction_pool.rs#L75)):*
> ```XML
> 
>     #[cfg(test)]
>     pub(crate) fn _tx_pool(&self) -> &HashMap<TransactionHash, ThinTransaction> {
> ```

Consider an alias: `HashToTransaction`, `TransactionMapping`?
BTW, how come no lifetime parameter is needed? Is it because the lifetime is unambiguous and tied to `self`'s lifetime?



_Code quote:_
```XML
HashMap<TransactionHash, ThinTransaction>
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcHn16sN_9Nj-6fSk:-O1RsLRO42X-X2APnt7f:b36b4ck) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Temporary name until used?
</blockquote></details>

yep, used in next PR
___
*[`crates/mempool/src/mempool_test.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcO0l-CDy289TXz8E:-O1RsOHsCXypM0vQE9O-:bcahlmh) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L59)):*
> ```XML
> // TODO(Ayelet): replace with MempoolState checker.
> #[track_caller]
> fn _check_mempool_state_eq(
> ```

changed to assert after offline
___
*[`crates/mempool/src/mempool_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QcVPt4fNT5uKcpMW6:-O1Rsjyg1THwj6Ysc-DN:b-utaehf) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/mempool_test.rs#L66)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think it's better here than a turbofish after `collect`?
</blockquote></details>

Ya i prefer this over the fish, it's somewhat less readable IMO.
Also it's easier to ignore this way, whereas the fish is injected inside the logic itself, and is harder to ignore.
___
*[`crates/mempool/src/transaction_pool.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/mempool/428#-O1QciN6EH0B1pGLBsDP:-O1S2KYuDcKuzaiGjWj2:b-lf907) ([raw file](https://github.com/starkware-libs/mempool/blob/6b28204f00f0f50f10a4fe99378b1879e48cff89/crates/mempool/src/transaction_pool.rs#L75)):*
>Consider an alias: `HashToTransaction`, `TransactionMapping`?

Done

>BTW, how come no lifetime parameter is needed? Is it because the lifetime is unambiguous and tied to `self`'s lifetime?

yep

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/428#-:-O1S4lc73J3eDJmzQUFk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
