### PR TITLE
feat: listen for requests from a network for the mempool

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 26 files at r2, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-NxgIGi35gbuRYbV1iTa:b4rhisr) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
> ```XML
> use std::sync::Arc;
> 
> use mempool_infra::network_component::CommunicationInterface;
> ```

What about error-handling?
___
*[`crates/mempool/src/mempool.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgExrJ9oqDYb5B2Z9m:-NxgExrJ9oqDYb5B2Z9n:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L99)):*
> ```XML
>     }
> 
>     /// Starts an asynchronous task that listens for network messages and processes them.
> ```





_Suggestion:_
```XML
/// Listens asynchronously
```
___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgFEWl78HYaVtmIQ6W:-NxgFEWl78HYaVtmIQ6X:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L100)):*
> ```XML
> 
>     /// Starts an asynchronous task that listens for network messages and processes them.
>     pub async fn start_network_listener(&mut self, notify: Arc<Notify>) {
> ```





_Suggestion:_
```XML
run
```
___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgFGmY8Zn8jxBr5dyg:-NxgFGmY8Zn8jxBr5dyh:b-9na6j7) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L100)):*
> ```XML
> 
>     /// Starts an asynchronous task that listens for network messages and processes them.
>     pub async fn start_network_listener(&mut self, notify: Arc<Notify>) {
> ```

What's this object? Why under an `Arc`?



_Suggestion:_
```XML
Arc<Notify> 
```
___
*[`crates/mempool/src/mempool.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgG-Gd6zPIWOliV8bG:-NxgG-Gd6zPIWOliV8bH:b-4hggge) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L115)):*
> ```XML
>                     // If notified, break the loop regardless of message state
>                     break;
>                 }
> ```

What does `notified` mean?



_Suggestion:_
```XML
                _ = self.network.recv() => {
                    match optional_message {
                        Some(message) => {
                            self.process_network_message(message).await;
                        },
                        // Channel was closed; exit.
                        None => break, 
                    }
                }
                _ = notify.notified() => {
                    // If notified, exit the loop regardless of message state
                    break;
                }
```
___
*[`crates/mempool/src/mempool.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgHlbm3qkLB8CIPYHz:-NxgHlbm3qkLB8CIPYI-:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L129)):*
> ```XML
>                 let _ = self.add_tx(tx, account_state);
>             }
>         }
> ```





_Suggestion:_
```XML
        match message {
            GatewayToMempoolMessage::AddTransaction(tx, account_state) => {
                self.add_tx(tx, account_state);
            }
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 15 of 28 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-NxgThMx3xS36tPHobSS:b-u5y1mu) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about error-handling?
</blockquote></details>

Added error handling for invoking `add_tx`.
___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgFGmY8Zn8jxBr5dyg:-NxgUO3z-Y7162trC6_W:b-5i55x1) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's this object? Why under an `Arc`?
</blockquote></details>

It enables task synchronization. One task can notify other tasks that an event of interest has occurred.
I used it to notify the run method to exit the loop.
I used `Arc` to share data across threads. See the usage in [this](https://reviewable.io/reviews/starkware-libs/mempool/106) PR
___
*[`crates/mempool/src/mempool.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgG-Gd6zPIWOliV8bG:-NxgMCO252G-01x2IuUV:bz8eh3k) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does `notified` mean?
</blockquote></details>

Was explained above.

Why `optional`?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 27 of 28 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-Nxvssh3EA6vh6UGRgJn:-Nxvssh3EA6vh6UGRgJo:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/gateway/tests/end_to_end_test.rs#L43)):*
> ```XML
>         GatewayToMempoolMessage::AddTx(tx, _) => {
>             assert_eq!(tx.tx_hash, tx_hash);
>         }
> ```





_Suggestion:_
```XML
        GatewayToMempoolMessage::AddTx(tx, _) => assert_eq!(tx.tx_hash, tx_hash);
```
___
*[`crates/mempool/src/mempool.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgG-Gd6zPIWOliV8bG:-NxvsDZQ26OvwgfhSSLs:bpwtmw2) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L115)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Was explained above.

Why `optional`?
</blockquote></details>

It's `Option<T>`, right?
___
*[`crates/mempool/src/mempool.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxvsNeU8cbQZey4N_39:-NxvsNeU8cbQZey4N_3A:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/mempool/src/mempool.rs#L122)):*
> ```XML
>     /// Processes a single message received from the network.
>     async fn process_network_message(&mut self, message: GatewayToMempoolMessage) {
>         let GatewayToMempoolMessage::AddTx(tx, account_state) = message;
> ```





_Suggestion:_
```XML
AddTransaction
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-NxvtZC1BRYVihPfe75F:b2q9jtj) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Added error handling for invoking `add_tx`.
</blockquote></details>

Perhaps we should use `anyhow`, since it runs in a level very close to `main`.
___
*[`crates/mempool/src/mempool.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-Nxvt8Wc-F6a3zd49OAt:-Nxvt8Wc-F6a3zd49OAu:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/mempool/src/mempool.rs#L103)):*
> ```XML
>             select! {
> 
>                 optional_message = self.network.recv() => {
> ```





_Suggestion:_
```XML
            select! {
                optional_message = self.network.recv() => {
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxvtHkJ2XfpEqCVk93P:-NxvtHkJ2XfpEqCVk93Q:b-suv37h) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/mempool_types/src/mempool_types.rs#L5)):*
> ```XML
> use starknet_api::transaction::{Tip, TransactionHash};
> 
> #[derive(Clone, Debug, PartialEq, Eq)]
> ```

Alphabetize?



_Code quote:_
```XML
derive
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxvwbRb8SDeRubg1kb4:-NxvwbRb8SDeRubg1kb5:b-6lahob) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/gateway/tests/end_to_end_test.rs#L27)):*
> ```XML
> 
>     let tx_hash = TransactionHash::default();
>     let tx = create_thin_tx_for_testing(Tip(0), tx_hash, ContractAddress::default());
> ```

And add derive(Default) to the struct



_Suggestion:_
```XML
    let tx = ThinTransaction::default()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 20 of 28 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-Ny-R7pe8GY9wYUaxgxY:bthbicm) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps we should use `anyhow`, since it runs in a level very close to `main`.
</blockquote></details>

Can you elaborate please?
___
*[`crates/mempool/src/mempool.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgG-Gd6zPIWOliV8bG:-Ny-PFJ80NpQD5wYTWEB:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's `Option<T>`, right?
</blockquote></details>

Done
___
*[`crates/mempool/src/mempool.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxvsNeU8cbQZey4N_39:-Ny-OcOX4xxGWsVBicw0:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/8ead93b2e641f79abd3ef6b4864b0248f8d04e5d/crates/mempool/src/mempool.rs#L122)):*
> ```XML
>     /// Processes a single message received from the network.
>     async fn process_network_message(&mut self, message: GatewayToMempoolMessage) {
>         let GatewayToMempoolMessage::AddTx(tx, account_state) = message;
> ```

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 6 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny-tPge3hdz0WA7fNxw:-Ny-tPge3hdz0WA7fNxx:bhfqhh6) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/gateway/tests/end_to_end_test.rs#L39)):*
> ```XML
>     match mempool_message {
>         GatewayToMempoolMessage::AddTransaction(tx, _) => {
>             assert_eq!(tx.tx_hash, TransactionHash::default())
> ```

What does this line checks?



_Code quote:_
```XML
assert_eq!(tx.tx_hash, TransactionHash::default())
```
___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-Ny-spsx2uw_pbiec71K:b-li1qvn) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you elaborate please?
</blockquote></details>

TAL [here](https://chat.openai.com/share/e/5e7f3c2c-b7b2-4716-a84b-dd1dbc2dc632).
When we're user-facing, or close to the outremost level of the app. (e.g., `main`, which will face clients of the code) we should use `anyhow` to friendly `panic`s to the CLI.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny-tPge3hdz0WA7fNxw:-Ny-vQ_L4fZc0oJ4pyeL:b-hcpsuq) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/gateway/tests/end_to_end_test.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this line checks?
</blockquote></details>

In one channel, I sent a thin transaction and we need to verify that the receiver channel also receives the same transaction. So, here I am confirming their transaction hashes.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny-tPge3hdz0WA7fNxw:-Ny08Y36BENpReaXAkLN:b4714tu) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/gateway/tests/end_to_end_test.rs#L39)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In one channel, I sent a thin transaction and we need to verify that the receiver channel also receives the same transaction. So, here I am confirming their transaction hashes.
</blockquote></details>

I see that `tx` is `ThinTransaction::default()`; what am I missing?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny-tPge3hdz0WA7fNxw:-Ny09FTvBXKt1AIqc8Bs:b-n4cljz) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/gateway/tests/end_to_end_test.rs#L39)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I see that `tx` is `ThinTransaction::default()`; what am I missing?
</blockquote></details>

Correct, so in the receiver, I check that it receives the default transaction.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 116 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny0D6CwC1IaUxVx8jvV:-Ny0D6CwC1IaUxVx8jvW:b-is5p03) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/mempool/src/mempool.rs#L116)):*
> ```XML
>                 }
>             }
>         }
> ```

Lets add a `BatcherToMempool` and `MempoolToBatcher` network components, and make `self.network` into `self.networks`.
Then in this function we'll `select!` on the rxs from both components, which obviates the need for notify and mutexes.

In the next PR in the test, make the test itself (until we have a batcher mock) the owner of the batcher-side network components.

This should be a simple change considering the existing NetworkCompoenet interface, so let me know if things get more complicated then we thought.



_Code quote:_
```XML
        loop {
            select! {
                optional_message = self.network.recv() => {
                    match optional_message {
                        Some(message) => {
                            self.process_network_message(message).await;
                        },
                        // Channel was closed; exit.
                        None => break,
                    }
                }
                _ = notify.notified() => {
                    // If notified, exit the loop regardless of message state
                    break;
                }
            }
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 21 of 29 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 5 at r3](https://reviewable.io/reviews/starkware-libs/mempool/119#-NxgIGi35gbuRYbV1iT_:-Ny0NuxVEiIm7rLScqP2:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/dbd85ed9c21a71fa764c0cc6764dda545c9a8d68/crates/mempool/src/mempool.rs#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

TAL [here](https://chat.openai.com/share/e/5e7f3c2c-b7b2-4716-a84b-dd1dbc2dc632).
When we're user-facing, or close to the outremost level of the app. (e.g., `main`, which will face clients of the code) we should use `anyhow` to friendly `panic`s to the CLI.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 116 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny0D6CwC1IaUxVx8jvV:-Ny0PstP8VmIe_-7hAjy:bc5hz67) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/mempool/src/mempool.rs#L116)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets add a `BatcherToMempool` and `MempoolToBatcher` network components, and make `self.network` into `self.networks`.
Then in this function we'll `select!` on the rxs from both components, which obviates the need for notify and mutexes.

In the next PR in the test, make the test itself (until we have a batcher mock) the owner of the batcher-side network components.

This should be a simple change considering the existing NetworkCompoenet interface, so let me know if things get more complicated then we thought.
</blockquote></details>

I suggest doing it in a separate PR.
I need to define a new message type, and add network component for that.

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 24 of 29 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/mempool/119#-NyFXlhzEdglJXdunPiS:-NyFXlhzEdglJXdunPiT:b-zhqbc1) ([raw file](https://github.com/starkware-libs/mempool/blob/e7e16f10a1fb817be6cbd3ba14e861996862a6f4/crates/mempool/src/mempool.rs#L118)):*
> ```XML
>             }
>         }
>         Ok("Exiting the loop successfully".to_string())
> ```

I think it's better to log this (and other branches in this function), rather than `return`ing a string.
Same for `process_network_message`.



_Code quote:_
```XML
Ok("Exiting the loop successfully".to_string())
```
___
*[`crates/mempool/src/mempool.rs` line 121 at r7](https://reviewable.io/reviews/starkware-libs/mempool/119#-NyFbrxy0HW3kLGoBjmR:-NyFbrxy0HW3kLGoBjmS:bkyvfe0) ([raw file](https://github.com/starkware-libs/mempool/blob/e7e16f10a1fb817be6cbd3ba14e861996862a6f4/crates/mempool/src/mempool.rs#L121)):*
> ```XML
>     }
> 
>     /// Processes a single message received from the network.
> ```

Can be deleted, doesn't add to readability (function name is good enough).



_Code quote:_
```XML
/// Processes a single message received from the network.
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: 24 of 29 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 116 at r6](https://reviewable.io/reviews/starkware-libs/mempool/119#-Ny0D6CwC1IaUxVx8jvV:-NyJBDciDWlhQBP6xwaB:bejf4qq) ([raw file](https://github.com/starkware-libs/mempool/blob/f29fb3543ed423db761df6ee9f845f82a6d8af84/crates/mempool/src/mempool.rs#L116)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I suggest doing it in a separate PR.
I need to define a new message type, and add network component for that.
</blockquote></details>

I'm not sure, lets talk f2f

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r6, 3 of 8 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119#-:-NyKAc0G-xOyENSL3DzY:bnfp4nl)* status: 25 of 29 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119#-:-NyKAilX9KagFNmyq2VJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
