### PR TITLE
refactor: rename component infra to requests and handlers

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #185
- #167
- #166
- #161
- #160
- #198 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/198)

### CODE REVIEW

**Review by uriel-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/198)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/198#-NzNc43H-PLjxaZpkTN2:-NzNc43H-PLjxaZpkTN3:b-b74l14) ([raw file](https://github.com/starkware-libs/mempool/blob/243b7d44fddcafc8a354c1fb916a64f65e604749/crates/mempool_infra/src/component_server_client_test.rs#L67)):*
> ```XML
> 
> #[async_trait]
> impl ComponentRequestHandler<ComponentAMessages, ComponentAResponses> for ComponentA {
> ```

ComponentARequests -> ComponentAMessage (notice I also changed it from plural to singular)
ComponentAResponses -> ComponentAResponse (from plural to singular)

Is there a reason it's plural?

and do the same for component B.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/198#-NzNc6VG0VL1z0FYFxVN:-NzNc6VG0VL1z0FYFxVO:bnj7hl0) ([raw file](https://github.com/starkware-libs/mempool/blob/243b7d44fddcafc8a354c1fb916a64f65e604749/crates/mempool_infra/src/component_server_client_test.rs#L114)):*
> ```XML
> 
> #[async_trait]
> impl ComponentRequestHandler<ComponentBMessages, ComponentBResponses> for ComponentB {
> ```

same as above

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/198)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/198#-NzNc43H-PLjxaZpkTN2:-NzNhJh91jckGt0Vt7pN:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/243b7d44fddcafc8a354c1fb916a64f65e604749/crates/mempool_infra/src/component_server_client_test.rs#L67)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

ComponentARequests -> ComponentAMessage (notice I also changed it from plural to singular)
ComponentAResponses -> ComponentAResponse (from plural to singular)

Is there a reason it's plural?

and do the same for component B.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/198#-NzNc6VG0VL1z0FYFxVN:-NzNhMEHB6spIsNnv4p_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/243b7d44fddcafc8a354c1fb916a64f65e604749/crates/mempool_infra/src/component_server_client_test.rs#L114)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/198#-:-NzNiP3CEl3rf3Zqu2AT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server_client_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/198#-NzNc43H-PLjxaZpkTN2:-NzNi8ppBYJ7nbubcfbG:b-x8lnv) ([raw file](https://github.com/starkware-libs/mempool/blob/243b7d44fddcafc8a354c1fb916a64f65e604749/crates/mempool_infra/src/component_server_client_test.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now I noticed my edits made the comment nonsensical, but you understood me :)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/198)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
