### PR TITLE
chore: change internal component client http to handle errors in fail…

### PR DESCRIPTION
**Pull request by uriel-starkware**
…ure and propogate it

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m1CO21PQ_DoHU7jA9:-O0m1CO21PQ_DoHU7jAA:bkprqyd) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L83)):*
> ```XML
>                 serialize(&component_request).expect("Request serialization should succeed"),
>             ))
>             .expect("Request builidng should succeed");
> ```

Not part of this pr, but there's a typo here: builidng -> building (swapped "d" with "i")

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m2nTw2Ri1h457j6I5:-O0m2nTw2Ri1h457j6I6:b6mo3lk) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
> ```XML
>             .await
>             .map_err(|_e| ClientError::ConnectionFailure)?;
>         let body_bytes = to_bytes(http_response.into_body()).await.expect("Body should exist");
> ```

Can we use `aggregate` here instead?



_Code quote:_
```XML
.into_body()
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m33HMDxhLejCGo0zL:-O0m33HMDxhLejCGo0zM:bgcmemq) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
> ```XML
>             .await
>             .map_err(|_e| ClientError::ConnectionFailure)?;
>         let body_bytes = to_bytes(http_response.into_body()).await.expect("Body should exist");
> ```

Can we use `aggregate` instead?



_Code quote:_
```XML
to_bytes
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m3qK9-kIrZAqYaFoL:-O0m3qK9-kIrZAqYaFoM:b-uxs97e) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L89)):*
> ```XML
>             .request(http_request)
>             .await
>             .map_err(|_e| ClientError::ConnectionFailure)?;
> ```

This represent a general http error, correct? If so, please:
1. Please rename to `CommunicationFailure`, this name better captures the "we've-successfully-connected-but-got-another-error" potential case.
2. Change the enum to include a presentation of the error (http status code?)



_Code quote:_
```XML
ClientError::ConnectionFailure
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4fqP3QcAEoEKP3_0:-O0m4fqP3QcAEoEKP3_1:b-l6tqb4) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
> ```XML
>             .await
>             .map_err(|_e| ClientError::ConnectionFailure)?;
>         let body_bytes = to_bytes(http_response.into_body()).await.expect("Body should exist");
> ```

When can this fail?



_Code quote:_
```XML
.expect("Body should exist")
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4mhz3vUo3jHKzo9n:-O0m4mhz3vUo3jHKzo9o:bnx5izs) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L105)):*
> ```XML
>         Self { uri: self.uri.clone(), _req: PhantomData, _res: PhantomData }
>     }
> }
> ```

Did you get a compilation error that lead to this code being here?



_Code quote:_
```XML
// Can't derive because derive forces the generics to also be `Clone`, which we prefer not to do
// since it'll require transactions to be cloneable.
impl<Request, Response> Clone for ComponentClientHttp<Request, Response>
where
    Request: Serialize,
    Response: for<'a> Deserialize<'a>,
{
    fn clone(&self) -> Self {
        Self { uri: self.uri.clone(), _req: PhantomData, _res: PhantomData }
    }
}
```
___
*[`crates/mempool_infra/src/component_client.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m5TD47CCmzu1Fhoyq:-O0m5TD47CCmzu1Fhoyr:bb7phvt) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L109)):*
> ```XML
> #[derive(Debug, Error, PartialEq)]
> pub enum ClientError {
>     #[error("Could not conenct to server")]
> ```

typo



_Code quote:_
```XML
conenct
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m68oH0IH8WOWEUvtI:-O0m68oIAOscPrzpnCrV:b152b5) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L96)):*
> ```XML
> 
> // Can't derive because derive forces the generics to also be `Clone`, which we prefer not to do
> // since it'll require transactions to be cloneable.
> ```

Please replace "transactions" with "the generic Requests and Responses".



_Code quote:_
```XML
transactions
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m6o6D7EnKb7Fgy9oM:-O0m6o6E9by3dNyCGKe8:bkytsm3) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L74)):*
> ```XML
> 
> async fn verify_response(
>     a_client: &ComponentClientHttp<ComponentARequest, ComponentAResponse>,
> ```

Please change to ownership (i.e., remove ref), and invoke with a clone of the client.



_Code quote:_
```XML
&ComponentClientHttp<ComponentARequest, ComponentAResponse>,
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m6yP78AfZFbaBLxIy:-O0m6yP78AfZFbaBLxIz:b-89a4l7) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L81)):*
> ```XML
> 
> async fn verify_error(
>     a_client: &ComponentClientHttp<ComponentARequest, ComponentAResponse>,
> ```

Ditto



_Code quote:_
```XML
&ComponentClientHttp<ComponentARequest, ComponentAResponse>,
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m7ApK1f3CU9vYEhau:-O0m7ApK1f3CU9vYEhav:bbs0izv) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L101)):*
> ```XML
>         ComponentClientHttp::<ComponentBRequest, ComponentBResponse>::new(local_ip, b_port);
> 
>     verify_error(&a_client, ClientError::ConnectionFailure).await;
> ```

Please create a separate test for the error scenario. Please see if there is functionality that is required in both tests, and decide if it makes sense to wrap it in a function.



_Code quote:_
```XML
 verify_error(&a_client, ClientError::ConnectionFailure).await;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m7ApK1f3CU9vYEhau:-O0m7VZ-Eg3vZ8I6HvA3:b-j4l0re) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L101)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please create a separate test for the error scenario. Please see if there is functionality that is required in both tests, and decide if it makes sense to wrap it in a function.
</blockquote></details>

Also, after extending the enum to include the error, please consider adding various tests for the different expected errors.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m1CO21PQ_DoHU7jA9:-O0m8LTrDBWOdY-BH4-c:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L83)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not part of this pr, but there's a typo here: builidng -> building (swapped "d" with "i")
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m3qK9-kIrZAqYaFoL:-O0m96T5-bjfQhIsAjb7:b-wr1s6p) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L89)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This represent a general http error, correct? If so, please:
1. Please rename to `CommunicationFailure`, this name better captures the "we've-successfully-connected-but-got-another-error" potential case.
2. Change the enum to include a presentation of the error (http status code?)
</blockquote></details>

regarding 2. I propose to do it in another PR that will expand the various options of failures. This new PR will include a dedicated test
___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4fqP3QcAEoEKP3_0:-O0m6gLt1Tzo0KabHqYZ:bubk53m) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

When can this fail?
</blockquote></details>

Hypothetically or in a real scenario? As far as we control both ends of communications, there should be a body because we send it.
There could be maybe a 
___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m33HMDxhLejCGo0zL:-O0m7Hyp7Vxc6deuKxj1:bltkzhf) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we use `aggregate` instead?
</blockquote></details>

I need an explanation. what is aggregate in this context? I found a function aggregate that returns an "impl buf", I pass to the next function &[u8]
___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m2nTw2Ri1h457j6I5:-O0m7dF78KHJWnV39ES_:bltkzhf) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we use `aggregate` here instead?
</blockquote></details>

I need an explanation. what is aggregate in this context? I found a function aggregate that returns an "impl buf", I pass to the next function &[u8]
___
*[`crates/mempool_infra/src/component_client.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m68oH0IH8WOWEUvtI:-O0m6Yua46Qy22Cr32W3:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please replace "transactions" with "the generic Requests and Responses".
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4mhz3vUo3jHKzo9n:-O0m6C_c2M9FR_1LAbVe:b4tbo61) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L105)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Did you get a compilation error that lead to this code being here?
</blockquote></details>

I made changes to the test and found out that I don't have the ability to clone the client and I needed it be clonable to save unnecessary new creations of a_client
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m6o6D7EnKb7Fgy9oM:-O0m8_Bm5toTPDxm8KHw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L74)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to ownership (i.e., remove ref), and invoke with a clone of the client.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m6yP78AfZFbaBLxIy:-O0m8_RcEoHz1t9ZDZYW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L81)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m7ApK1f3CU9vYEhau:-O0m9QYN8XCS1rOBMqHx:bajhe6w) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L101)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Also, after extending the enum to include the error, please consider adding various tests for the different expected errors.
</blockquote></details>

Note my proposal for a new pr to do this, in the meantime, we will not separate into two tests

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4fqP3QcAEoEKP3_0:-O0mAFJe0GU2e9RKZZj1:bneh1cd) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Hypothetically or in a real scenario? As far as we control both ends of communications, there should be a body because we send it.
There could be maybe a
</blockquote></details>

... corruption to data or unexpected response with no body, I think I will address it with the followup PR

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m68oH0IH8WOWEUvtI:-O0mB_rj5AVnu_spZnY_:b-31r422) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L96)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Apologies for the hassle, another slight change: "the generic Requests and Responses" -> "the generic Request and Response types"
___
*[`crates/mempool_infra/src/component_client.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4mhz3vUo3jHKzo9n:-O0mBV2F3zQISFmX3zDg:bb6sh2i) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L105)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I made changes to the test and found out that I don't have the ability to clone the client and I needed it be clonable to save unnecessary new creations of a_client
</blockquote></details>

Ack.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m7ApK1f3CU9vYEhau:-O0mBM9Y3zu4azoEzyye:bb6sh2i) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/tests/component_server_client_http_test.rs#L101)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Note my proposal for a new pr to do this, in the meantime, we will not separate into two tests
</blockquote></details>

Ack.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m3qK9-kIrZAqYaFoL:-O0mBr94-Siy7BaiJ65_:b-gboqrq) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L89)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

regarding 2. I propose to do it in another PR that will expand the various options of failures. This new PR will include a dedicated test
</blockquote></details>

Ack. Next time please add a todo in the code to indicate this is your intention :pray: 
___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m4fqP3QcAEoEKP3_0:-O0mC2PsCUIkVvcBhUMR:b-amo24d) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

... corruption to data or unexpected response with no body, I think I will address it with the followup PR
</blockquote></details>

I'm worried that this will result in a panic and the process will crash, without reporting the issue. Please change to propagate this error. IMO this is in the scope of this pr.
___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m33HMDxhLejCGo0zL:-O0mCMPw2TnRyjsLTBp7:b-rj29uz) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I need an explanation. what is aggregate in this context? I found a function aggregate that returns an "impl buf", I pass to the next function &[u8]
</blockquote></details>

The `to_bytes` doc suggests that it copies all data into a single continous buffer, and suggests to use `aggregate` instead:
https://docs.rs/hyper/0.14.29/hyper/body/fn.to_bytes.html

AFAIU `aggregate` returns a `impl Buf` object:
https://docs.rs/hyper/0.14.29/hyper/body/fn.aggregate.html

The `buf` doc suggests an optimizied way to receive the required bytes
[https://docs.rs/hyper/0.14.29/hyper/body/trait.Buf.html#method.copy_to_bytes](https://docs.rs/hyper/0.14.29/hyper/body/trait.Buf.html#method.copy_to_bytes)

I'm not sure which of these is better, and if so, what's the performance gain, hence my question from the previous message. 

Is there a *simple* way to measure which one is better?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0m33HMDxhLejCGo0zL:-O0mZDaz4NRivyQISt4d:bb6sh2i) ([raw file](https://github.com/starkware-libs/mempool/blob/f41901b2ebc86c54ac567147ac13313ff151df78/crates/mempool_infra/src/component_client.rs#L90)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

My 2 cents in this case is that to_bytes is simpler, and it is enough for now.

In more detail: aggregate works if I don't need a contiguous buffer which is not the case (I deserialize it into another type). If I will use aggregate, I will use copy_to_bytes anyway and it will use the impl for hyper::body, which I don't control. The only thing I can achieve from using aggregate and copy_to_bytes is to tell it how many bytes I want to copy, which again, I don't want to manage.
Maybe in the future, if we find that this is a bottleneck, we should consider benchmarking it and testing which one is better and if needed, delve into the fine details
</blockquote></details>

Ack.
___
*[`crates/mempool_infra/src/component_client.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0meIVN5UaXXJ14FQeB:-O0meIVN5UaXXJ14FQeC:bgw6pe) ([raw file](https://github.com/starkware-libs/mempool/blob/3ce91ae4182ab17041047d5314ee280498648e20/crates/mempool_infra/src/component_client.rs#L114)):*
> ```XML
>     #[error("Could not connect to server")]
>     CommunicationFailure,
>     #[error("Could not extract body from HTTP response: {0}")]
> ```

Could not parse the response : {0}"



_Code quote:_
```XML
Could not extract body from HTTP response: {0}"
```
___
*[`crates/mempool_infra/src/component_client.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0mcmZdADnvuTJ57S0G:-O0mcmZdADnvuTJ57S0H:bmz5i3n) ([raw file](https://github.com/starkware-libs/mempool/blob/3ce91ae4182ab17041047d5314ee280498648e20/crates/mempool_infra/src/component_client.rs#L115)):*
> ```XML
>     CommunicationFailure,
>     #[error("Could not extract body from HTTP response: {0}")]
>     BodyExtractionFailure(String),
> ```

Please change to "ResponseParsingFailure".



_Code quote:_
```XML
BodyExtractionFailure
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0meIVN5UaXXJ14FQeB:-O0mqpeR7Z94goCXpAGM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3ce91ae4182ab17041047d5314ee280498648e20/crates/mempool_infra/src/component_client.rs#L114)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could not parse the response : {0}"
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/mempool/338#-O0mcmZdADnvuTJ57S0G:-O0mqpyy7KnouGjqAK6Q:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3ce91ae4182ab17041047d5314ee280498648e20/crates/mempool_infra/src/component_client.rs#L115)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to "ResponseParsingFailure".
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/338#-:-O0n7b9qADS28cp6h1Gz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
