### PR TITLE
test(mempool): refactor test_add_tx_with_duplicate_tx to use mempool …

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…state

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1Wiw1HEtzOFtZoTErK:-O1Wiw1HEtzOFtZoTErL:b-owbvmg) ([raw file](https://github.com/starkware-libs/mempool/blob/7a0222a00aec5b388b9a8a5e19c610d05f77dedb/crates/mempool/src/mempool_test.rs#L213)):*
> ```XML
> 
>     // Assert that the original tx remains in Mempool after the failed attempt.
>     let queue_txs = [TransactionReference::new(&input.tx)];
> ```

I don't think asserting the queue is relevant for this test.

If the duplicate tx isn't in the pool then we can assume it's not queued, and whether or not the non-dup tx is in the queue shouldn't matter for a dup-check test.

There should be an easy way of only checking the pool.



_Code quote:_
```XML
    let queue_txs = [TransactionReference::new(&input.tx)];
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1Wiw1HEtzOFtZoTErK:-O1Wpwq5CLuVVxivlk3S:b-giq3ou) ([raw file](https://github.com/starkware-libs/mempool/blob/7a0222a00aec5b388b9a8a5e19c610d05f77dedb/crates/mempool/src/mempool_test.rs#L213)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I don't think asserting the queue is relevant for this test.

If the duplicate tx isn't in the pool then we can assume it's not queued, and whether or not the non-dup tx is in the queue shouldn't matter for a dup-check test.

There should be an easy way of only checking the pool.
</blockquote></details>

I see your point, and it's easy to implement, but what is the issue with checking the entire mempool state?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1Wiw1HEtzOFtZoTErK:-O1qUT8gA9V8ow2i6gbL:bgsq0mj) ([raw file](https://github.com/starkware-libs/mempool/blob/7a0222a00aec5b388b9a8a5e19c610d05f77dedb/crates/mempool/src/mempool_test.rs#L213)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I see your point, and it's easy to implement, but what is the issue with checking the entire mempool state?
</blockquote></details>

Why use a complicated assertion when a simple one suffices?

A more complicated solution to a simple problem can confuse readers, who might think that indeed there is a case in which tx is not in the pool but is in the queue, otherwise, why check both?

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1Wiw1HEtzOFtZoTErK:-O1qWIsx-G0fCrAmOwWL:bepoq3u) ([raw file](https://github.com/starkware-libs/mempool/blob/7a0222a00aec5b388b9a8a5e19c610d05f77dedb/crates/mempool/src/mempool_test.rs#L213)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Why use a complicated assertion when a simple one suffices?

A more complicated solution to a simple problem can confuse readers, who might think that indeed there is a case in which tx is not in the pool but is in the queue, otherwise, why check both?
</blockquote></details>

There is also consistency to consider.
If you do it for a test that doesn't need it, the principle of consistency will encourage future test writers to also assert this.
This might end up costing us with doesn't of extra assertions in our test files that are essentially tautologies.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1Wiw1HEtzOFtZoTErK:-O1qz6h-3ynHD79Qcsjs:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/7a0222a00aec5b388b9a8a5e19c610d05f77dedb/crates/mempool/src/mempool_test.rs#L213)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There is also consistency to consider.
If you do it for a test that doesn't need it, the principle of consistency will encourage future test writers to also assert this.
This might end up costing us with doesn't of extra assertions in our test files that are essentially tautologies.
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1kDniWCwCggDyPX8sN:-O1kDniX7lR7gyKsnIcW:bcadrpc) (no related file):*
Please impl. all my comments from other test( PR)s here.

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/444#-O1vk9ER8kM1hzIUXpHN:-O2-OPCjBl6kVSVnVTaU:b-vt7h60) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please go over all tests that use `MempoolState` and check that they are tight? I.e., do not check already covered cases.
</blockquote></details>

I wrote myself to do as a next task. 

___

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/mempool/444#-O2-7rkc8ZsiQNF_y4pB:-O2-7rkc8ZsiQNF_y4pC:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3bfec92d3df7baf4883137b9e3f3e7d2a427187d/crates/mempool/src/mempool_test.rs#L238)):*
> ```XML
> #[rstest]
> fn test_add_tx_with_duplicate_tx(mut mempool: Mempool) {
>     // Setup
> ```





_Suggestion:_
```XML
// Setup.
```
___
*[`crates/mempool/src/mempool_test.rs` line 305 at r4](https://reviewable.io/reviews/starkware-libs/mempool/444#-O2TY0sM2V3Mmr4i3rPr:-O2TY0sM2V3Mmr4i3rPs:b-aw4rlp) ([raw file](https://github.com/starkware-libs/mempool/blob/c0cfaa7fe89c5e8faaf2ea70286b247f1d539814/crates/mempool/src/mempool_test.rs#L305)):*
> ```XML
>     let duplicate_input = input.clone();
> 
>     // Test: assert that the duplicate tx is not added to the mempool.
> ```

Code is clear enough.



_Suggestion:_
```XML
// Test.
```
___
*[`crates/mempool/src/mempool_test.rs` line 312 at r4](https://reviewable.io/reviews/starkware-libs/mempool/444#-O2TY4Zr9Pi5KkO8oXaR:-O2TY4Zr9Pi5KkO8oXaS:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c0cfaa7fe89c5e8faaf2ea70286b247f1d539814/crates/mempool/src/mempool_test.rs#L312)):*
> ```XML
>     );
> 
>     // Assert: the original tx remains in Mempool after the failed attempt.
> ```





_Suggestion:_
```XML
// Assert: the original tx remains.
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 314 at r5](https://reviewable.io/reviews/starkware-libs/mempool/444#-O2ZKmCJCOMifj7kSBpH:-O2ZKmCJCOMifj7kSBpI:b-anlq06) ([raw file](https://github.com/starkware-libs/mempool/blob/e453351f18da14ef1ab4ae75ba95464bccc9d7ca/crates/mempool/src/mempool_test.rs#L314)):*
> ```XML
>     );
> 
>     // Assert: the original tx remains.
> ```

No abbreviations in documentation.



_Suggestion:_
```XML
transaction
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444#-:-O2ZPbvCB7gopjNyeO6N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/444)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
