### PR TITLE
test(mempool): refactor MempoolState to have Partial and Full states

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O25SmJD9PMqZ3tv_z9L:-O25SmJE1LdfbkKgKn2Z:bn0qtdf) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L50)):*
> ```XML
>         Self { tx_pool: None, tx_queue: None, _phantom: PhantomData }
>     }
> }
> ```

Please move it to the end.
Usually, the struct implementations appear before the trait implementation.



_Code quote:_
```XML
impl Default for MempoolState<PartialState> {
    fn default() -> Self {
        Self { tx_pool: None, tx_queue: None, _phantom: PhantomData }
    }
}
```
___
*[`crates/mempool/src/mempool_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O25T8yn7NHPzWrk1Lju:-O25T8yn7NHPzWrk1Ljv:bm561bw) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L68)):*
> ```XML
> }
> 
> impl<T> MempoolState<T> {
> ```

What's `T`? I dont see it's usage.
Is it Partail Struct of Full Struct?



_Code quote:_
```XML
impl<T> MempoolState<T> {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O25TZVD9Mia8uWIEhz3:-O25TZVD9Mia8uWIEhz4:bxfkowz) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L27)):*
> ```XML
>     tx_queue: Option<TransactionQueue>,
>     _phantom: PhantomData<T>,
> }
> ```

Can you please add a comment that explains the magic here?



_Code quote:_
```XML
struct MempoolState<T> {
    tx_pool: Option<TransactionPool>,
    tx_queue: Option<TransactionQueue>,
    _phantom: PhantomData<T>,
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UEI7X3dO_kCwoxgyU:-O2UEI7X3dO_kCwoxgyV:bsd41hj) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L26)):*
> ```XML
>     tx_pool: Option<TransactionPool>,
>     tx_queue: Option<TransactionQueue>,
>     _phantom: PhantomData<T>,
> ```

Fully-qualified, please; it's not too long.



_Code quote:_
```XML
PhantomData
```
___
*[`crates/mempool/src/mempool_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O25TZVD9Mia8uWIEhz3:-O2UFvX-12kVmfP7fh_S:bf3dt7o) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L27)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please add a comment that explains the magic here?
</blockquote></details>

TAL at the conversation (inc. replies) [here](https://github.com/starkware-libs/mempool/pull/446#pullrequestreview-2179710996).
___
*[`crates/mempool/src/mempool_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UGkOJ38XyUZp-uhdC:-O2UGkOJ38XyUZp-uhdD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L30)):*
> ```XML
> 
> struct FullState;
> struct PartialState;
> ```





_Suggestion:_
```XML
#[derive(Debug)]
struct MempoolState<T> {
    tx_pool: Option<TransactionPool>,
    tx_queue: Option<TransactionQueue>,
    _phantom: PhantomData<T>,
}

#[derive(Debug)]
struct FullState;
#[derive(Debug)]
struct PartialState;
```
___
*[`crates/mempool/src/mempool_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UG9d02asahkQAMKbV:-O2UG9d02asahkQAMKbW:b-c9q04g) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L33)):*
> ```XML
> 
> impl MempoolState<FullState> {
>     fn new<P, Q>(pool_txs: P, queue_txs: Q) -> Self
> ```

I also remember a suggestion to create `TransactionReference` objects in _this_ function. 
Please implement in a separate PR.



_Code quote:_
```XML
new
```
___
*[`crates/mempool/src/mempool_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O25T8yn7NHPzWrk1Lju:-O2UHwav4d5Gy4ZzkfNI:bqm95y6) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L68)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What's `T`? I dont see it's usage.
Is it Partail Struct of Full Struct?
</blockquote></details>

Yup, that's what the state generic of.
___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UHOOwBp1ZFi56Jxm_:-O2UHOOwBp1ZFi56Jxma:b35y42j) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L83)):*
> ```XML
> }
> 
> impl<T> From<MempoolState<T>> for Mempool {
> ```

Doesn't impl. change depending on the type of the state (partial/full)? `unwrap` won't always work.



_Code quote:_
```XML
impl<T> From<MempoolState<T>> for Mempool
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UGkOJ38XyUZp-uhdC:-O2YbE509BqDlf-Irzwa:b-3ktls) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L30)):*
> ```XML
> 
> struct FullState;
> struct PartialState;
> ```

Why add `#[derive(Debug)]` if the structs aren't currently used for debugging? Isn't it better to add it only when we actually need it?
___
*[`crates/mempool/src/mempool_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UG9d02asahkQAMKbV:-O2YerH-CUS1G0HIUEM3:bhnwk7e) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L33)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I also remember a suggestion to create `TransactionReference` objects in _this_ function. 
Please implement in a separate PR.
</blockquote></details>

added a todo
___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UHOOwBp1ZFi56Jxm_:-O2YkjOz9CVX0oryYMg8:b-ltga7z) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't impl. change depending on the type of the state (partial/full)? `unwrap` won't always work.
</blockquote></details>

Correct. How's this solution?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UGkOJ38XyUZp-uhdC:-O2ZO2lD2CK1_C7tClcC:bvxav1a) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why add `#[derive(Debug)]` if the structs aren't currently used for debugging? Isn't it better to add it only when we actually need it?
</blockquote></details>

We know we'll need it, might as well add now.
___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UHOOwBp1ZFi56Jxm_:-O2ZOpnz3LqW6hS_lvK6:b9csjqc) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Correct. How's this solution?
</blockquote></details>

What would be the default? `None` or `[]`?
___
*[`crates/mempool/src/mempool_test.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZNfb9CyB9DmAC4TEi:-O2ZNfb9CyB9DmAC4TEj:b-wufzix) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L20)):*
> ```XML
> use crate::transaction_queue::TransactionQueue;
> 
> /// MempoolState represents the internal state of the mempool.
> ```

State with present tense verb; do not include struct/variable names in doc., it might get outdated.



_Suggestion:_
```XML
/// R
```
___
*[`crates/mempool/src/mempool_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZNyy78Hr0yxVfr7Zw:-O2ZNyy78Hr0yxVfr7Zx:bcjhaqo) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L23)):*
> ```XML
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> /// The `PhantomData` marks the state type (`FullState` or `PartialState`) without storing data of
> /// that type, enabling type-safe operations based on the state.
> ```

Not sure I understand.



_Code quote:_
```XML
/// The `PhantomData` marks the state type (`FullState` or `PartialState`) without storing data of
/// that type, enabling type-safe operations based on the state.
```
___
*[`crates/mempool/src/mempool_test.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZOj3Y84ifM4Znq52N:-O2ZOj3Y84ifM4Znq52O:b-ya42ht) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L88)):*
> ```XML
> impl Default for MempoolState<PartialState> {
>     fn default() -> Self {
>         Self { tx_pool: None, tx_queue: None, _phantom: std::marker::PhantomData }
> ```

Why is that the default implementation?



_Code quote:_
```XML
tx_pool: None, tx_queue: None
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2UHOOwBp1ZFi56Jxm_:-O2_UM044_tOZ1lDpq2k:b-sdlnyo) ([raw file](https://github.com/starkware-libs/mempool/blob/6b707869ad2d40ac1053b97ad21d6725c0fea4a8/crates/mempool/src/mempool_test.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What would be the default? `None` or `[]`?
</blockquote></details>

would be the default of TransactionPool and TransactionQueue
___
*[`crates/mempool/src/mempool_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZNyy78Hr0yxVfr7Zw:-O2_Tw9p2qWxnSq_q-5u:b-7ql1td) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L23)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand.
</blockquote></details>

fixed
___
*[`crates/mempool/src/mempool_test.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZOj3Y84ifM4Znq52N:-O2_9qgL40sVCOwpplV3:bymzvl6) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is that the default implementation?
</blockquote></details>

for the partial state, it's being used in `_with_pool`, `_with_queue`.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZOj3Y84ifM4Znq52N:-O2_V9Ey2aLBaJq5BPZ2:blvrv32) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L88)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

for the partial state, it's being used in `_with_pool`, `_with_queue`.
</blockquote></details>

not used anymore.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2ZNyy78Hr0yxVfr7Zw:-O2aAoRY9zL5ySoDkqsg:b-vzz1bv) ([raw file](https://github.com/starkware-libs/mempool/blob/f5a081ba517252dd3ac617276b4ffc518246dca7/crates/mempool/src/mempool_test.rs#L23)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

"Artificially use generic type, for the compiler."

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2cnM8TDJ7ZM5oQpRya:-O2cnM8UERVp-Lc2VJwU:b-ct31av) ([raw file](https://github.com/starkware-libs/mempool/blob/f1d94c05a32e43e56147d9643bdd65f602030878/crates/mempool/src/mempool_test.rs#L26)):*
> ```XML
>     tx_pool: Option<TransactionPool>,
>     tx_queue: Option<TransactionQueue>,
>     // PhantomData<T> artificially use generic type, for the compiler.
> ```

Try not to quote parts from code (names, etc.) in doc., so it'll be less prone to becoming stale.



_Suggestion:_
```XML
// Artificially use generic type, for the compiler.
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/507)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 320 at r6](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2dB2NB2d_2e5JLdkBb:-O2dB2NB2d_2e5JLdkBc:be7aupk) ([raw file](https://github.com/starkware-libs/mempool/blob/232db3d9db049f6feb94595edc8588fed6c8848e/crates/mempool/src/mempool_test.rs#L320)):*
> ```XML
> 
>     // Assert: the original transaction remains.
>     let expected_mempool_state = MempoolState::with_pool([input.tx]);
> ```

But queue was compared before.



_Code quote:_
```XML
with_pool
```
___
*[`crates/mempool/src/mempool_test.rs` line 365 at r6](https://reviewable.io/reviews/starkware-libs/mempool/507#-O2dB5ZAAmbZIkTgK8cn:-O2dB5ZAAmbZIkTgK8co:btblgbc) ([raw file](https://github.com/starkware-libs/mempool/blob/232db3d9db049f6feb94595edc8588fed6c8848e/crates/mempool/src/mempool_test.rs#L365)):*
> ```XML
>         TransactionReference::new(&input_big_tip_small_hash.tx),
>         TransactionReference::new(&input_small_tip_big_hash.tx),
>     ];
> ```

`map`, please. In all tests.



_Code quote:_
```XML
    let expected_queue_txs = [
        TransactionReference::new(&input_big_tip_small_hash.tx),
        TransactionReference::new(&input_small_tip_big_hash.tx),
    ];
```

**Pull request closed without merging**
