### PR TITLE
test: add test fix infra for gateway network connection config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@lev-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111#-:-NxMfsCL9m76nz36Aw4d:bw1gi4r)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config_test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxMqCeN8gnOVgKq4q14:-NxMqCeN8gnOVgKq4q15:b-thn8s7) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L12)):*
> ```XML
> 
> const TEST_FILES_FOLDER: &str = "./src/json_files_for_testing";
> const CONFIG_FILE: &str = "gateway_network_connection_config.json";
> ```

If you will write tests for the "stateless_transaction_validator_config" in this file, it's better that you have some config files.
So rename it to NETWORK_CONFIG_FILE.



_Code quote:_
```XML
CONFIG_FILE
```
___
*[`crates/gateway/src/config_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxMrovz8Zllg_a6UrwW:-NxMrovz8Zllg_a6UrwX:b1gmkyx) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L14)):*
> ```XML
> const CONFIG_FILE: &str = "gateway_network_connection_config.json";
> 
> fn get_config_file_path() -> PathBuf {
> ```

For the same reason as above, add parameter "file_name" to this function.
___
*[`crates/gateway/src/config_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxN83W5AfCygmVPM-_N:-NxN83W6Et_4pf4Hc2z8:b-qahkck) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L48)):*
> ```XML
>     // To fix the test, set the `fix` parameter to `true`, and run the test.
>     test_valid_config_body(false);
> }
> ```

How are you going to run fix?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxMqCeN8gnOVgKq4q14:-NxN9PeDCNBrn0h3ww9J:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L12)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

If you will write tests for the "stateless_transaction_validator_config" in this file, it's better that you have some config files.
So rename it to NETWORK_CONFIG_FILE.
</blockquote></details>

Done.
___
*[`crates/gateway/src/config_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxMrovz8Zllg_a6UrwW:-NxN9R6K8ITp5kl2fGLr:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L14)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

For the same reason as above, add parameter "file_name" to this function.
</blockquote></details>

Done.
___
*[`crates/gateway/src/config_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxN83W5AfCygmVPM-_N:-NxN9U21EYKeIqtljYfd:b6z4oji) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L48)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

How are you going to run fix?
</blockquote></details>

I had a bad solution in mind when I submitted revision `r2`. I will fix it soon.

I will try doing something similar to the suggestion from [here](https://users.rust-lang.org/t/how-do-i-run-only-a-specific-file-other-than-main-rs/76213/3).
I will try to add a file called `fix_tests.rs` somewhere and call it using `cargo run --bin fix_tests`.
This is a WIP.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/config_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/mempool/111#-NxN83W5AfCygmVPM-_N:-NxNIIqy91rtu-xAUqU9:b-2s1wmn) ([raw file](https://github.com/starkware-libs/mempool/blob/3930a7adde1f65a0a51a89261175d5567aa669f4/crates/gateway/src/config_test.rs#L48)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I had a bad solution in mind when I submitted revision `r2`. I will fix it soon.

I will try doing something similar to the suggestion from [here](https://users.rust-lang.org/t/how-do-i-run-only-a-specific-file-other-than-main-rs/76213/3).
I will try to add a file called `fix_tests.rs` somewhere and call it using `cargo run --bin fix_tests`.
This is a WIP.
</blockquote></details>

It was not as simple as I had hoped. Let us take care of that later.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111#-:-NxNQJgz-XL53R8Uln3v:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111#-:-Nxfun5UCbqp3g8Qs_KE:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by lev-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **May 12, 4:58 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/111).

**Pull request merged**
