### PR TITLE
fix: retrieve txs from account PQ when mempool PQ has fewer txs than asked

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/mempool/254#-O-ffwFq80wFbJzO5u3Z):*
It's fix/fixture



_Code quote:_
```
refactor
```
___
*[`crates/mempool/src/mempool.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/mempool/254#-O-fgjqT5ySDE25VDnUw:-O-fgjqU340sxmq0C4lM:b-7hbprb) ([raw file](https://github.com/starkware-libs/mempool/blob/41b32975363422a10928aaa047796f50b247e3c8/crates/mempool/src/mempool.rs#L102)):*
> ```XML
> 
>     fn get_next_eligible_tx(&mut self, sender_address: ContractAddress) -> Option<ThinTransaction> {
>         // TODO: add staging area. Remove transactions from mempool.
> ```

wdym?



_Code quote:_
```XML
 // TODO: add staging area. Remove transactions from mempool.
```
___
*[`crates/mempool/src/mempool.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/mempool/254#-O-fh1Z579s3KDJ2pe_x:-O-fh1Z579s3KDJ2pe_y:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/41b32975363422a10928aaa047796f50b247e3c8/crates/mempool/src/mempool.rs#L110)):*
> ```XML
>                 self.address_to_queue.remove(&sender_address);
>             // Return next nonce transaction.
>             } else if let Some(_next_tx) = address_queue.top() {
> ```





_Suggestion:_
```XML
 else if address_queue.top().is_some()
```
___
*[`crates/mempool/src/mempool.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/mempool/254#-O-fhJ9j834_nfQGpE8X:-O-fhJ9j834_nfQGpE8Y:b3m3zzc) ([raw file](https://github.com/starkware-libs/mempool/blob/41b32975363422a10928aaa047796f50b247e3c8/crates/mempool/src/mempool.rs#L112)):*
> ```XML
>             } else if let Some(_next_tx) = address_queue.top() {
>                 return address_queue.pop_front();
>             }
> ```

Instead of the if condition code you can return `pop_front`.



_Suggestion:_
```XML
            } else {
                return address_queue.pop_front();
            }
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
Split PR plz, as follows:
1. only change in get_txs, make the get_eligible return [] here (see my comment below on why `[]`). Add a dedicated negative test that will remain relevant without any changes also after the next PR.
2. Add get_eliglbe logic, add a _dedicated_ positive test. 
3. The addition of the 0 edge-case in `test_get_txs` is a good edition and belongs in the test, but let's not include nonce stuff, the test is already sufficiently complex as it is. 
4. rename `test_get_txs` to something that pinpoints what it's testing; this will sway others from adding anything else to it.
5. see if the new algorithm of get_txs can be refactored a bit, note that you have some assumptions on it that might yield better performance or simpler code. For example, you know that if you fetched extra txs and you got less than the remaining txs, you can skip adding them to the queue altogether.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254#-:-O1NyhXZ5kUFYa2T61NC:b-z8k8ad)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/mempool/254#-O1O1OZd9qJ5_Qh4jGNS:-O1O1OZd9qJ5_Qh4jGNT:bc2t8bg) ([raw file](https://github.com/starkware-libs/mempool/blob/d6e9212e11f41f4ea88f8096c5fbde002a419c68/crates/mempool/src/mempool.rs#L53)):*
> ```XML
> 
>             for tx in &chunk {
>                 // TODO: add staging area.
> ```

can remove, it's already in the works
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/254#-O1NzPQe18sVOpFMJ_0p:-O1NzPQe18sVOpFMJ_0q:b-xwxaha) ([raw file](https://github.com/starkware-libs/mempool/blob/d6e9212e11f41f4ea88f8096c5fbde002a419c68/crates/mempool/src/mempool.rs#L106)):*
> ```XML
>     }
> 
>     fn get_next_eligible_tx(&mut self, sender_address: ContractAddress) -> Option<ThinTransaction> {
> ```

This should be in bulk, we'll never need just one unless pop_chunk happens to return [one_result].
Adding to the queue can also be then done in bulk.



_Code quote:_
```XML
fn get_next_eligible_tx(&mut self, sender_address: ContractAddress) 
```
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/254#-O1O3kP19zJx1hyKGfHb:-O1O3kP19zJx1hyKGfHc:b-w2900i) ([raw file](https://github.com/starkware-libs/mempool/blob/d6e9212e11f41f4ea88f8096c5fbde002a419c68/crates/mempool/src/mempool.rs#L106)):*
> ```XML
>     }
> 
>     fn get_next_eligible_tx(&mut self, sender_address: ContractAddress) -> Option<ThinTransaction> {
> ```

`get_` is canonically a read-only op



_Suggestion:_
```XML
 fn remove_next_eligible_tx(&mut self, sender_address: ContractAddress) -> Option<ThinTransaction> {
```
___
*[`crates/mempool/src/mempool.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/mempool/254#-O1O4pkL1tZScM9fScek:-O1O4pkM0OwRJ9Fy725D:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/d6e9212e11f41f4ea88f8096c5fbde002a419c68/crates/mempool/src/mempool.rs#L107)):*
> ```XML
> 
>     fn get_next_eligible_tx(&mut self, sender_address: ContractAddress) -> Option<ThinTransaction> {
>         if let Some(account_txs) = self.address_to_queue.get_mut(&sender_address) {
> ```





_Suggestion:_
```XML
let account_txs = self.address_to_queue.get_mut(&sender_address)?;
```
___
*[`crates/mempool/src/mempool.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/mempool/254#-O1O4nRX4bq7Is_xchZm:-O1O4nRX4bq7Is_xchZn:b5koqky) ([raw file](https://github.com/starkware-libs/mempool/blob/d6e9212e11f41f4ea88f8096c5fbde002a419c68/crates/mempool/src/mempool.rs#L111)):*
> ```XML
>             account_txs.pop_front();
> 
>             match account_txs.top() {
> ```

are both of these needed?



_Code quote:_
```XML
            account_txs.pop_front();

            match account_txs.top() {
```

**Review by giladchase — COMMENTED** [review]
>-   The addition of the 0 edge-case in `test_get_txs` is a good edition and belongs in the test, but let's not include nonce stuff, the test is already sufficiently complex as it is.

On second thought, the 0 case is too degenerate for this test, lets just add a dedicated test for the get_txs(0) case.
Also the part at the end about emptying the mempool, if used inside the parameterized test, it is run once per each parameterization, even though for each run it basically does the same thing.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254#-:-O1O5wXYEhMD0c8ZvQkZ:bhngq0c)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/254)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Pull request closed without merging**
