### PR TITLE
feat: add cairo0 support to rpc_state_reader

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l-y0z82LdbPniO6BJ:-O-l-y0z82LdbPniO6BK:b-nnhnws) ([raw file](https://github.com/starkware-libs/mempool/blob/2085ff5cdd071a9005fd7bc4c68843d03321164a/crates/gateway/src/rpc_state_reader.rs#L135)):*
> ```XML
>             self.send_rpc_request("starknet_getCompiledContractClass", get_compiled_class_params)?;
>         let casm_contract_class: CasmContractClass =
>             serde_json::from_value(result).map_err(serde_err_to_state_err)?;
> ```

How did that work before?



_Code quote:_
```XML
        let casm_contract_class: CasmContractClass =
            serde_json::from_value(result).map_err(serde_err_to_state_err)?;
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l01Qb761QVLhAGf6m:-O-l01Qb761QVLhAGf6n:brh7tkx) ([raw file](https://github.com/starkware-libs/mempool/blob/2085ff5cdd071a9005fd7bc4c68843d03321164a/crates/gateway/src/rpc_state_reader.rs#L136)):*
> ```XML
>         let casm_contract_class: CasmContractClass =
>             serde_json::from_value(result).map_err(serde_err_to_state_err)?;
>         let class_hash = ContractClass::V1(
> ```

That was wrong! 



_Code quote:_
```XML
class_hash
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l0iLO0JEUdCxWWXMx:-O-l0iLO0JEUdCxWWXMy:biuhliw) ([raw file](https://github.com/starkware-libs/mempool/blob/1bd7a3c3d672bf1b8b59d15242476c19f259b11f/crates/gateway/src/rpc_state_reader.rs#L143)):*
> ```XML
>                 ContractClassV0::try_from(contract_class_v0).map_err(StateError::ProgramError)?,
>             )),
>         }
> ```

Does that work?

Can we directly use serde_json to deserialize ContractClass formatted for blockifier?
(Or should I not check PRs at this hour?).



_Suggestion:_
```XML
        let contract_class: ContractClass =
            serde_json::from_value(result).map_err(serde_err_to_state_err)?;
        
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l-y0z82LdbPniO6BJ:-O-oLciH7ouBHj9LIsL_:b-3dke9y) ([raw file](https://github.com/starkware-libs/mempool/blob/2085ff5cdd071a9005fd7bc4c68843d03321164a/crates/gateway/src/rpc_state_reader.rs#L135)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

How did that work before?
</blockquote></details>

The rpc method now returns a different value, it used to return  the CasmContractClass but now it returns CompiledContractClass.
see : https://reviewable.io/reviews/starkware-libs/papyrus/2093#-
___
*[`crates/gateway/src/rpc_state_reader.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l01Qb761QVLhAGf6m:-O-oLOD51En5wklnet56:bx3u6p9) ([raw file](https://github.com/starkware-libs/mempool/blob/2085ff5cdd071a9005fd7bc4c68843d03321164a/crates/gateway/src/rpc_state_reader.rs#L136)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

That was wrong!
</blockquote></details>

:)
wrong terminology but not a bug 
___
*[`crates/gateway/src/rpc_state_reader.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O-l0iLO0JEUdCxWWXMx:-O-oM1W0DCbMkfq7l2OR:b-s976d4) ([raw file](https://github.com/starkware-libs/mempool/blob/1bd7a3c3d672bf1b8b59d15242476c19f259b11f/crates/gateway/src/rpc_state_reader.rs#L143)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does that work?

Can we directly use serde_json to deserialize ContractClass formatted for blockifier?
(Or should I not check PRs at this hour?).
</blockquote></details>

it is not the same structure stored in papyrus storage and defined in blockifier, so in order to do that I need the rpc method to send the blockifier structure. Also currently the blockifier contract class does not implement Deserialize.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O03G7g97ersKx8YmRto:-O03G7g97ersKx8YmRtp:b5olhbu) ([raw file](https://github.com/starkware-libs/mempool/blob/1bd7a3c3d672bf1b8b59d15242476c19f259b11f/crates/gateway/src/rpc_state_reader.rs#L161)):*
> ```XML
> }
> 
> // TODO(yael 19/6/2024): make this object public in papyrus and remove it from here.
> ```

Can you make a PR for it?



_Code quote:_
```XML
// TODO(yael 19/6/2024): make this object public in papyrus and remove it from here.
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/258#-O03G7g97ersKx8YmRto:-O03xe_s5PWdQmHbYpI0:buogmlb) ([raw file](https://github.com/starkware-libs/mempool/blob/1bd7a3c3d672bf1b8b59d15242476c19f259b11f/crates/gateway/src/rpc_state_reader.rs#L161)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you make a PR for it?
</blockquote></details>

will consult with Dan tomorrow, since the object is public already, just the module isn't so it is not straight forward.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258#-:-O04-X4w7IJEm6_ol8wO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
