### PR TITLE
feat(gateway): validate that entry points are sorted by selector

### PR DESCRIPTION
**Pull request by yair-starkware**
After checking with Ilya, the entry points need to be sorted

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`Cargo.toml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BCx014WX-hXly6FRK:-O1BCx014WX-hXly6FRL:bttwo0z) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/Cargo.toml#L52)):*
> ```TOML
> hyper = { version = "0.14", features = ["client", "server", "http1", "http2", "tcp"] }
> indexmap = "2.1.0"
> is_sorted = "0.1.1"
> ```

Is there a security issue with using this crate?



_Code quote:_
```TOML
is_sorted = "0.1.1"
```
___
*[`crates/gateway/src/errors.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BDM3K6zQfG4jwJNIg:-O1BDM3LCZhWgyeV92Wy:bu53y2p) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/crates/gateway/src/errors.rs#L91)):*
> ```XML
>         max_contract_class_object_size: usize,
>     },
>     #[error("Contract class entry points are not sorted by the selector.")]
> ```

Is this the same error from the Python code?



_Code quote:_
```XML
Contract class entry points are not sorted by the selector.
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BELfEBnYe7AnA8JxA:-O1BELfF2_k-mKVgyPpo:brmub0b) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/crates/gateway/src/stateless_transaction_validator_test.rs#L333)):*
> ```XML
> 
> #[test]
> fn test_declare_entry_points_not_sorted_by_selector() {
> ```

Please add a positive flow test.

For the record, the test `fn test_positive_flow` already covers the "empty" case.



_Code quote:_
```XML
#[test]
fn test_declare_entry_points_not_sorted_by_selector() {
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/errors.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BDM3K6zQfG4jwJNIg:-O1CQTSe5IhP2EvdT1Qz:b-wow1lj) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/crates/gateway/src/errors.rs#L91)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this the same error from the Python code?
</blockquote></details>

Now it is.
Also found out that it needs to be unique.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BELfEBnYe7AnA8JxA:-O1CQWtXAYhZvTwAsrbG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/crates/gateway/src/stateless_transaction_validator_test.rs#L333)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please add a positive flow test.

For the record, the test `fn test_positive_flow` already covers the "empty" case.
</blockquote></details>

Done.
___
*[`Cargo.toml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1BCx014WX-hXly6FRK:-O1CK9H3DgOX4oJI4lGN:bn5ntvt) ([raw file](https://github.com/starkware-libs/mempool/blob/521a6777928cc4a0bfe14d9698cde2fc1d4b6a59/Cargo.toml#L52)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is there a security issue with using this crate?
</blockquote></details>

Replaced with own impl

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 340 at r3](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1CwigrAI9dkJA7STLG:-O1CwigrAI9dkJA7STLH:bv8b104) ([raw file](https://github.com/starkware-libs/mempool/blob/9cdcaebbda870e2da45dd30a2681d6098afe571d/crates/gateway/src/stateless_transaction_validator_test.rs#L340)):*
> ```XML
>     ],
>     Ok(())
> )]
> ```

Add a positive case for a list of entry points of length 1 (one of the classic cases for constructor). 


(will `window(2)` work fine with that?)



_Code quote:_
```XML
#[case::valid(
    vec![
        EntryPoint { selector: EntryPointSelector(felt!(1_u128)), ..Default::default() },
        EntryPoint { selector: EntryPointSelector(felt!(2_u128)), ..Default::default() }
    ],
    Ok(())
)]
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 340 at r3](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1CwigrAI9dkJA7STLG:-O1GpqW05zTr7GAqgneQ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9cdcaebbda870e2da45dd30a2681d6098afe571d/crates/gateway/src/stateless_transaction_validator_test.rs#L340)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a positive case for a list of entry points of length 1 (one of the classic cases for constructor). 


(will `window(2)` work fine with that?)
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373#-:-O1Gtiop5Ir-12SASFFT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/errors.rs` line 92 at r4](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1VzVhS7LbfHFqmMh2b:-O1VzVhS7LbfHFqmMh2c:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/026eb9924d11077a619378e736139cf71ad8491a/crates/gateway/src/errors.rs#L92)):*
> ```XML
>     },
>     #[error("Entry points must be unique and sorted.")]
>     EntryPointsNotUniqueSorted,
> ```





_Suggestion:_
```XML
EntryPointsNotUniquelySorted
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 360 at r4](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1VzE-J6MUuQgwfOOLY:-O1VzE-K8Isb0HDqVotP:b-1l1ibq) ([raw file](https://github.com/starkware-libs/mempool/blob/026eb9924d11077a619378e736139cf71ad8491a/crates/gateway/src/stateless_transaction_validator_test.rs#L360)):*
> ```XML
>     ],
>     Err(StatelessTransactionValidatorError::EntryPointsNotUniqueSorted)
> )]
> ```

Can you a case for more than 2 entry points?
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/mempool/373#-O1VzKeVCS42TVZJcEYL:-O1VzKeVCS42TVZJcEYM:b8a6ihh) ([raw file](https://github.com/starkware-libs/mempool/blob/026eb9924d11077a619378e736139cf71ad8491a/crates/gateway/src/stateless_transaction_validator_test.rs#L373)):*
> ```XML
>             constructor: entry_points,
>             external: vec![],
>             l1handler: vec![],
> ```

Please add tests for these as well.



_Code quote:_
```XML
            external: vec![],
            l1handler: vec![],
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373#-:-O1k6rd4C_jW7YSxa7z_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
