### PR TITLE
refactor: refactor integration tests to use mempool_node modules

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:cd2418e0

---

**Stack**:
- #339 ⬅
- #311
- #355

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0nW7f07emmlDfCsQ93:-O0nW7f07emmlDfCsQ94:b-43vvu5) ([raw file](https://github.com/starkware-libs/mempool/blob/725897752e631bea93de496f71ddcf2ea5670120/crates/tests-integration/src/integration_test_utils.rs#L46)):*
> ```XML
> 
> pub fn create_config() -> MempoolNodeConfig {
>     MempoolNodeConfig { gateway_config: create_gateway_config(), ..MempoolNodeConfig::default() }
> ```

What do these two dots mean?



_Code quote:_
```XML
..
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0nWNeIBWGz8txLeuCr:-O0yBJIuCoPs5vctiOkw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/725897752e631bea93de496f71ddcf2ea5670120/crates/tests-integration/src/integration_test_utils.rs#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we avoid using this injection by including in a config (the node config for example) the required state reader factory, and changing the `create_gateway` function to set the correct value to begin with?
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0nW7f07emmlDfCsQ93:-O0yBK_UEzsmIs3YUdWn:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/725897752e631bea93de496f71ddcf2ea5670120/crates/tests-integration/src/integration_test_utils.rs#L46)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What do these two dots mean?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yQCOZ-JjbOE1YtASg:-O0yQCOZ-JjbOE1YtASh:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L23)):*
> ```XML
>     pub gateway_client: GatewayClient,
>     pub batcher: MockBatcher,
> //    pub batcher_mempool_client: SharedMempoolClient,
> ```

Remove.



_Code quote:_
```XML
//    pub batcher_mempool_client: SharedMempoolClient,
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yR9i_-KZzUk70Ea5h:-O0yR9iaD_pdVbq_zLgG:bcs7u6e) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L34)):*
> ```XML
>         let task_executor = TokioExecutor::new(handle);
> 
>         // Build and run gateway; initialize a gateway client.
> ```

Please remove this comment.



_Code quote:_
```XML
// Build and run gateway; initialize a gateway client.
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yRDKK92CqljfELfZf:-O0yRDKK92CqljfELfZg:bb6shms) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L35)):*
> ```XML
> 
>         // Build and run gateway; initialize a gateway client.
>         let config = create_config(n_initialized_account_contracts).await;
> ```

Add 



_Code quote:_
```XML
let config = create_config(n_initialized_account_contracts).await;
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yQapW2Vgg9SuuT36r:-O0yQapW2Vgg9SuuT36s:b517mn6) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L57)):*
> ```XML
> 
>         // Build Batcher.
>         // TODO(MockBatcher)
> ```

Probably a rebase issue, remove.



_Code quote:_
```XML
// TODO(MockBatcher)
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0ySG00D5_USikghd9V:-O0ySG00D5_USikghd9W:bm0zagp) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_utils.rs#L34)):*
> ```XML
> pub async fn create_config(n_initialized_account_contracts: u16) -> MempoolNodeConfig {
>     let gateway_config = create_gateway_config();
>     let rpc_server_addr = spawn_test_rpc_state_reader(n_initialized_account_contracts).await;
> ```

I'd highly prefer that this function, which is about spinning up a rpc server, would not be hidden behind a `create_config` function.
Please:
1. add a call to `spawn_test_rpc_state_reader_config` just before where the call to `create_config` is, and save the resultant return value as `state_reader_rpc_server_addr`.
2. change `create_config` to take `state_reader_rpc_server_addr` as an arg (instead of `n_initialized_account_contracts`).

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yT4jT9ZE_oh-zdbWP:-O0yT4jT9ZE_oh-zdbWQ:b9zsbdv) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L43)):*
> ```XML
>         let components = create_components(&config, &clients);
> 
>         let servers = create_servers(&config, channels, components);
> ```

Please add the following comments before the relevant function calls:

```
// Spawn a papyrus rpc server for a papyrus storage reader.
// Derive the configuration for the mempool node.
// Create the communication network for the mempool node.
// Create the clients for the mempool node.
// Create the components for the mempool node.
// Create the servers for the mempool node.
```



_Code quote:_
```XML
        let config = create_config(n_initialized_account_contracts).await;

        let channels = create_node_channels();

        let clients = create_node_clients(&config, &channels);

        let components = create_components(&config, &clients);

        let servers = create_servers(&config, channels, components);
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yQCOZ-JjbOE1YtASg:-O0ygkrt2QpYx_AuYCVb:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L23)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yR9i_-KZzUk70Ea5h:-O0yiPcn1wP_vUP0prsL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L34)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove this comment.
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yT4jT9ZE_oh-zdbWP:-O0yiYtVEWN4Di1ekRuf:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L43)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add the following comments before the relevant function calls:

```
// Spawn a papyrus rpc server for a papyrus storage reader.
// Derive the configuration for the mempool node.
// Create the communication network for the mempool node.
// Create the clients for the mempool node.
// Create the components for the mempool node.
// Create the servers for the mempool node.
```
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0yQapW2Vgg9SuuT36r:-O0yh2soA6qw93-kvp05:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_setup.rs#L57)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Probably a rebase issue, remove.
</blockquote></details>

Done.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/mempool/339#-O0ySG00D5_USikghd9V:-O1BLizU6aMHX6_XWY0b:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b642a65b8d5b64ea88d2c3e9ce0e5cd30dc4eade/crates/tests-integration/src/integration_test_utils.rs#L34)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd highly prefer that this function, which is about spinning up a rpc server, would not be hidden behind a `create_config` function.
Please:
1. add a call to `spawn_test_rpc_state_reader_config` just before where the call to `create_config` is, and save the resultant return value as `state_reader_rpc_server_addr`.
2. change `create_config` to take `state_reader_rpc_server_addr` as an arg (instead of `n_initialized_account_contracts`).
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/mempool/339#-O1BLNBkDcgFjYLkq1gN:-O1BLNBkDcgFjYLkq1gO:b-wgw1zb) ([raw file](https://github.com/starkware-libs/mempool/blob/714d0c90052d061574785f12e7a4f62d9c80a527/crates/tests-integration/src/integration_test_utils.rs#L33)):*
> ```XML
> pub async fn create_config(rpc_server_addr: SocketAddr) -> MempoolNodeConfig {
>     let gateway_config = create_gateway_config().await;
>     let rpc_state_reader_config = spawn_test_rpc_state_reader_config(rpc_server_addr);
> ```

Although not part of this pr, please change the name of `spawn_test_rpc_state_reader_config` to `test_rpc_state_reader_config`, as it does not spawn anything. Thanks.



_Code quote:_
```XML
spawn_test_rpc_state_reader_config(rpc_server_addr);
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/mempool/339#-O1BLNBkDcgFjYLkq1gN:-O1Bg_gw2O54tDmZDsF5:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/714d0c90052d061574785f12e7a4f62d9c80a527/crates/tests-integration/src/integration_test_utils.rs#L33)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Although not part of this pr, please change the name of `spawn_test_rpc_state_reader_config` to `test_rpc_state_reader_config`, as it does not spawn anything. Thanks.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339#-:-O1BnN8J3jqIPTFlrgOs:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
