### PR TITLE
refactor: extract parameters from external transaction

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/58#-Nvjodyx0Fprs6O0uxPJ:-Nvjodyx0Fprs6O0uxPK:br2ldzw) ([raw file](https://github.com/starkware-libs/mempool/blob/6b1cf4035e7422070e8995ba95661941c9813d45/crates/gateway/src/stateless_transaction_validator.rs#L148)):*
> ```XML
>     fn resource_bounds(&self) -> &ResourceBoundsMapping;
>     fn signature(&self) -> &TransactionSignature;
> }
> ```

very nice!  magic macro.
maybe put this into a utils.rs file?
I opened one in one of my PRs, but not merged yet.



_Code quote:_
```XML
macro_rules! implement_ref_getters {
    ($(($member_name:ident, $member_type:ty));* $(;)?) => {
        $(fn $member_name(&self) -> &$member_type {
            match self {
                ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => {
                    &tx.$member_name
                }
                ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(tx)) => {
                    &tx.$member_name
                }
                ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => &tx.$member_name,
            }
        })*
    };
}

impl ExternalTransactionExt for ExternalTransaction {
    implement_ref_getters!(
        (resource_bounds, ResourceBoundsMapping);
        (signature, TransactionSignature)
    );
}

trait ExternalTransactionExt {
    fn resource_bounds(&self) -> &ResourceBoundsMapping;
    fn signature(&self) -> &TransactionSignature;
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/58#-Nvjodyx0Fprs6O0uxPJ:-NvjwRBnDJpucwXfonOV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6b1cf4035e7422070e8995ba95661941c9813d45/crates/gateway/src/stateless_transaction_validator.rs#L148)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

very nice!  magic macro.
maybe put this into a utils.rs file?
I opened one in one of my PRs, but not merged yet.
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/58#-Nvjodyx0Fprs6O0uxPJ:-NvjwmPq9fLZX1QKrJ1J:b-i1g2dg) ([raw file](https://github.com/starkware-libs/mempool/blob/6b1cf4035e7422070e8995ba95661941c9813d45/crates/gateway/src/stateless_transaction_validator.rs#L148)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the new file

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/58#-Nvjodyx0Fprs6O0uxPJ:-Nvk1YcUCZM7wnLEQQU_:bk78hdq) ([raw file](https://github.com/starkware-libs/mempool/blob/6b1cf4035e7422070e8995ba95661941c9813d45/crates/gateway/src/stateless_transaction_validator.rs#L148)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't see the new file
</blockquote></details>

Now done :) (TY)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/mempool/58#-NvkjDJV6B9GyzatSk9u:-NvkjDJV6B9GyzatSk9v:bwbp0el) ([raw file](https://github.com/starkware-libs/mempool/blob/563f19e256008373aa8e9d72184d69ef491afbe1/crates/gateway/src/utils.rs#L3)):*
> ```XML
> use starknet_api::external_transaction::ExternalTransaction;
> use starknet_api::transaction::{ResourceBoundsMapping, TransactionSignature};
> ```

I think we can add it to the actual ExtrnalTransaction struct in SNAPI.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/mempool/58#-NvkjDJV6B9GyzatSk9u:-Nvl4CpPEYghvZHWW1Hj:b5s090e) ([raw file](https://github.com/starkware-libs/mempool/blob/563f19e256008373aa8e9d72184d69ef491afbe1/crates/gateway/src/utils.rs#L3)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think we can add it to the actual ExtrnalTransaction struct in SNAPI.
</blockquote></details>

Added a TODO. Here is a PR: https://github.com/starkware-libs/starknet-api/pull/234

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58#-:-NvzdZNeCfCLkagzwhOS:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/58)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
