### PR TITLE
chore: refactor the use of tip and nonce ref getters

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/162)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#163** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/163?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#162** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/162?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/162)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/162#-NyUUSUt4UlrA4bRb2kH:-NyUUSUuCQ0zOH5WBl1l:b433zqj) ([raw file](https://github.com/starkware-libs/mempool/blob/9ad5ef6fc4c5b0827122fae89d193b1116cfccb7/crates/gateway/src/starknet_api_test_utils.rs#L24)):*
> ```XML
> }
> 
> // TODO(Mohammad): Use the StarkNet API's get_tip function.
> ```

Please move the TODO to utils file.



_Code quote:_
```XML
// TODO(Mohammad): Use the StarkNet API's get_tip function.
```
___
*[`crates/gateway/src/utils.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/162#-NyUU_XD7ftNcaTVFl-p:-NyUU_XD7ftNcaTVFl-q:b1onxwr) ([raw file](https://github.com/starkware-libs/mempool/blob/51d5efe876014a60f508cc0c5783915e64ddcc0f/crates/gateway/src/utils.rs#L41)):*
> ```XML
> }
> 
> impl ExternalTransactionExt for ExternalTransaction {
> ```

Why it's not part of the starknet_api utils?



_Code quote:_
```XML
impl ExternalTransactionExt for ExternalTransaction {
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/162#-NyUU_XD7ftNcaTVFl-p:-NyUUr1ZEamCzDWQ1ezT:b-r1ikyl) ([raw file](https://github.com/starkware-libs/mempool/blob/51d5efe876014a60f508cc0c5783915e64ddcc0f/crates/gateway/src/utils.rs#L41)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's not part of the starknet_api utils?
</blockquote></details>

It is :) See #163

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/162#-NyUUSUt4UlrA4bRb2kH:-NyUWgdlEFA8l__9srPU:b-7gliyb) ([raw file](https://github.com/starkware-libs/mempool/blob/9ad5ef6fc4c5b0827122fae89d193b1116cfccb7/crates/gateway/src/starknet_api_test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please move the TODO to utils file.
</blockquote></details>

Done in #163

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/162#-:-NyV1b3n5crAeaX0_p61:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **May 22, 7:30 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/162).

**Pull request merged**
