### PR TITLE
fix: avoid rounding in serializations

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1Mf7BnDaBHffZW9Rbe:-O1Mf7BnDaBHffZW9Rbf:b-7oc4d9) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/tests-integration/tests/end_to_end_test.rs#L35)):*
> ```XML
>     let deserialized = serde_json::to_string(&serialized).unwrap();
>     assert_eq!(input, deserialized);
> }
> ```

why duplicate the test?
consider adding a function to test utils with this logic.



_Code quote:_
```XML
fn serialization_precision() {
    let input =
        "{\"value\":244116128358498188146337218061232635775543270890529169229936851982759783745}";
    let serialized = serde_json::from_str::<serde_json::Value>(input).unwrap();
    let deserialized = serde_json::to_string(&serialized).unwrap();
    assert_eq!(input, deserialized);
}
```

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1VqU0c9K4dKoTvDARc:-O1VqU0c9K4dKoTvDARd:b-de3bkg) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/gateway/Cargo.toml#L26)):*
> ```TOML
> reqwest.workspace = true
> serde.workspace = true
> serde_json = { workspace = true, features = ["arbitrary_precision"] }
> ```

Can it added in the workspace level?



_Code quote:_
```TOML
features = ["arbitrary_precision"] }
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1VqU0c9K4dKoTvDARc:-O1VyMOYCVIz8BnbrzNs:b-34ojfk) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/gateway/Cargo.toml#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it added in the workspace level?
</blockquote></details>

Unfortunately no, it is an open issue: https://github.com/rust-lang/cargo/issues/4463
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1Mf7BnDaBHffZW9Rbe:-O1W0JFd1Xg1S4eQCfzh:bs0wlu3) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/tests-integration/tests/end_to_end_test.rs#L35)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why duplicate the test?
consider adding a function to test utils with this logic.
</blockquote></details>

We need this test in each crate that uses serde_json

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1VqU0c9K4dKoTvDARc:-O1WAZnNEg_i_7B19NHd:b-3m68zo) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/gateway/Cargo.toml#L26)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Unfortunately no, it is an open issue: https://github.com/rust-lang/cargo/issues/4463
</blockquote></details>

Not sure I totally understand the issue.
According to the documentation (https://doc.rust-lang.org/cargo/reference/features.html#feature-unification and https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) feature selection is additive.

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1Mf7BnDaBHffZW9Rbe:-O1WPS943gbqI_6Vkfl9:b-g6tuog) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/tests-integration/tests/end_to_end_test.rs#L35)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We need this test in each crate that uses serde_json
</blockquote></details>

yes I undestood that eventually by myself, thought I retracted this comment

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/415#-O1VqU0c9K4dKoTvDARc:-O1WL4JQDaoIPsJj-Ia5:b-ruk542) ([raw file](https://github.com/starkware-libs/mempool/blob/8b2b64f5bc5bb0928cc42344f0d85af7e2dd6811/crates/gateway/Cargo.toml#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure I totally understand the issue.
According to the documentation (https://doc.rust-lang.org/cargo/reference/features.html#feature-unification and https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) feature selection is additive.
</blockquote></details>

Oh I think it's new.
We had a problem with this in Papyrus.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/415#-:-O1k7t7q7dLOahInqmie:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
