### PR TITLE
refactor: replace invoke json file with macro creation

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxvyAGDBXwKfG-j2_O1:-NxznPlo1khyPTrgwql-:b9bo46j) ([raw file](https://github.com/starkware-libs/mempool/blob/3d08f128297cd8de5bf55aaa0ffa419e84f8a073/crates/gateway/src/utils.rs#L157)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

should I find a way to remove unwrap?
</blockquote></details>

Yes, but not too much more than that :) See the comment below.
___
*[`crates/gateway/src/utils.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-Nxzmx6S5qTSHE-uMaiy:-Nxzmx6S5qTSHE-uMaiz:b-ck0uiz) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L145)):*
> ```XML
>     pub account_deployment_data: AccountDeploymentData,
>     pub nonce: Nonce,
> }
> ```

Note `starknet_api_test_utils.rs` exists.
This list of inputs seems quite similar.

I think the code should be in this file, and used in that file.

 https://github.com/starkware-libs/mempool/blob/3001f435dbfe053b15c2e17460fc57ce045111e0/crates/gateway/src/starknet_api_test_utils.rs#L24



_Code quote:_
```XML
#[derive(Clone)]
pub struct InvokeTxArgs {
    pub signature: TransactionSignature,
    pub contract_address: ContractAddress,
    pub calldata: Calldata,
    pub version: TransactionVersion,
    pub resource_bounds: ResourceBoundsMapping,
    pub tip: Tip,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
    pub paymaster_data: PaymasterData,
    pub account_deployment_data: AccountDeploymentData,
    pub nonce: Nonce,
}
```
___
*[`crates/gateway/src/utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxznBr_9OrWveLbqA32:-NxznBr_9OrWveLbqA33:b1qf28b) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L157)):*
> ```XML
>                 (Resource::L2Gas, ResourceBounds { max_amount: 0, max_price_per_unit: 0 }),
>             ])
>             .unwrap(),
> ```

Default should use default values.



_Suggestion:_
```XML
            resource_bounds: ResourceBoundsMapping::try_from(vec![
                (Resource::L1Gas, ResourceBounds::default()),
                (Resource::L2Gas, ResourceBounds::default()),
            ])
            .expect("Resource bounds mapping has unexpected structure."),
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxzngBi0NNC5aukH3D6:-NxzngBi0NNC5aukH3D7:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/gateway_test.rs#L54)):*
> ```XML
>                 max_amount: 0,
>                 max_price_per_unit: 0,
>             },
> ```





_Suggestion:_
```XML
            ResourceBounds::Default(),
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxznBr_9OrWveLbqA32:-Nxzo20J9P6bppITk1iQ:bjpc6ws) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Default should use default values.
</blockquote></details>

Or even use: https://github.com/starkware-libs/mempool/blob/3001f435dbfe053b15c2e17460fc57ce045111e0/crates/gateway/src/starknet_api_test_utils.rs#L161

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxzosFRBH7rldQ_6EM8:-NxzosFRBH7rldQ_6EM9:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/gateway_test.rs#L60)):*
> ```XML
>     }), "INVOKE")]
> #[tokio::test]
> async fn test_add_transaction(
> ```





_Suggestion:_
```XML
test_add_transaction_with_invoke(
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxzngBi0NNC5aukH3D6:-NxzoyknDhTUu195cq4q:b-3q7bdk) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/gateway_test.rs#L54)):*
> ```XML
>                 max_amount: 0,
>                 max_price_per_unit: 0,
>             },
> ```

Use util from `starknet_api_test_utils`.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-Nxzok2u4oKqYVeSFtM0:-Nxzok2v3lQQZi_hrwpN:bbp80qa) ([raw file](https://github.com/starkware-libs/mempool/blob/603a539555794e7c654b286f80efa753d8fb06ef/crates/gateway/src/gateway_test.rs#L22)):*
> ```XML
> };
> 
> const TEST_FILES_FOLDER: &str = "./tests/fixtures";
> ```

Will the files be deleted?
They should, at some point, IIUC.



_Code quote:_
```XML
const TEST_FILES_FOLDER: &str = "./tests/fixtures";
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-Nxzok2u4oKqYVeSFtM0:-Ny-QdUOCeQ2CA6IDXug:be5nmxc) ([raw file](https://github.com/starkware-libs/mempool/blob/603a539555794e7c654b286f80efa753d8fb06ef/crates/gateway/src/gateway_test.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Will the files be deleted?
They should, at some point, IIUC.
</blockquote></details>

I think not. Now that I have removed invoke_tx.json, the next step will be to create functions that create instances for both declaring and deploying an account, and to delete the declare.json and deploy_account.json files.
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxzngBi0NNC5aukH3D6:-Ny-RinBCOL4KAEKvu79:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/gateway_test.rs#L54)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Use util from `starknet_api_test_utils`.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxzosFRBH7rldQ_6EM8:-Ny-RqBF6UD95iRM6JSM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/gateway_test.rs#L60)):*
> ```XML
>     }), "INVOKE")]
> #[tokio::test]
> async fn test_add_transaction(
> ```

Done.
___
*[`crates/gateway/src/utils.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-Nxzmx6S5qTSHE-uMaiy:-Ny-p7vk6f3prtDA73yk:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L145)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Note `starknet_api_test_utils.rs` exists.
This list of inputs seems quite similar.

I think the code should be in this file, and used in that file.

 https://github.com/starkware-libs/mempool/blob/3001f435dbfe053b15c2e17460fc57ce045111e0/crates/gateway/src/starknet_api_test_utils.rs#L24
</blockquote></details>

Done.
___
*[`crates/gateway/src/utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxznBr_9OrWveLbqA32:-Ny-SuJi6Pplt3BYrwQb:bmbuit7) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Or even use: https://github.com/starkware-libs/mempool/blob/3001f435dbfe053b15c2e17460fc57ce045111e0/crates/gateway/src/starknet_api_test_utils.rs#L161
</blockquote></details>

`max_price_per_unit: 1` is not a default value.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-sKQD2dgNkAbl3cT_:-Ny-sKQD2dgNkAbl3cTa:balcv14) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L179)):*
> ```XML
>         }
>     }
> }
> ```

Otherwise this function should not be called `default`.



_Suggestion:_
```XML
impl Default for InvokeTxArgs {
    fn default() -> Self {
        InvokeTxArgs {
            signature: TransactionSignature::default(),
            contract_address: ContractAddress::default(),
            calldata: calldata![],
            version: TransactionVersion::THREE,
            resource_bounds: zero_resource_bounds_mapping(),
            tip: Tip::default(),
            nonce_data_availability_mode: DataAvailabilityMode::L1,
            fee_data_availability_mode: DataAvailabilityMode::L1,
            paymaster_data: PaymasterData::default(),
            account_deployment_data: AccountDeploymentData::default(),
            nonce: Nonce::default(),
        }
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-skiB5mQNgtf32Tkf:-Ny-skiB5mQNgtf32Tkg:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/gateway_test.rs#L53)):*
> ```XML
>         ),
>     ])
>     .unwrap(),
> ```





_Suggestion:_
```XML
    resource_bounds: create_resource_bounds_mapping(
            ResourceBounds {
                max_amount: 5,
                max_price_per_unit: 6,
            },
            ResourceBounds::default(),
        ),
    ])
    .unwrap(),
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 230 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-uOaB65PESVIj5rzl:-Ny-uOaB65PESVIj5rzm:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L230)):*
> ```XML
>     if let Value::Object(ref mut map) = tx_json {
>         map.insert("version".to_string(), Value::String("0x3".to_string()));
>     }
> ```





_Suggestion:_
```XML
    if let Value::Object(ref mut map) = tx_json {
        map.insert("type".to_string(), Value::String("INVOKE_FUNCTION".to_string()));
        map.insert("version".to_string(), Value::String("0x3".to_string()));
    } else {
        panic!("the tx was not serialized to a JSON object {tx_json}");
    }
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/131#-NxznBr_9OrWveLbqA32:-Ny-rRK_63kOBwxtAltB:b-2jgose) ([raw file](https://github.com/starkware-libs/mempool/blob/cad498d46c54366375e6d39bef2a23145a6ccdd1/crates/gateway/src/utils.rs#L157)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`max_price_per_unit: 1` is not a default value.
</blockquote></details>

In that case, this function should not be called `default`.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-skiB5mQNgtf32Tkf:-Ny03juIDZbhmfxNoCmG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/gateway_test.rs#L53)):*
> ```XML
>         ),
>     ])
>     .unwrap(),
> ```

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-sKQD2dgNkAbl3cT_:-Ny06-f4Ew-UsM7QSS7V:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L179)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Otherwise this function should not be called `default`.
</blockquote></details>

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 230 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-uOaB65PESVIj5rzl:-Ny06FkE9IgNdPhdpzgu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L230)):*
> ```XML
>     if let Value::Object(ref mut map) = tx_json {
>         map.insert("version".to_string(), Value::String("0x3".to_string()));
>     }
> ```

Done.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny07Onw7ACbUTAFuN-E:-Ny07Onw7ACbUTAFuN-F:b-iuv3ho) ([raw file](https://github.com/starkware-libs/mempool/blob/3de750d55843932af014cc2051c9ddfbdd61df48/crates/gateway/src/gateway_test.rs#L50)):*
> ```XML
>                 max_amount: 5,
>                 max_price_per_unit: 6,
>             },
> ```

Non-blocking.



_Suggestion:_
```XML
            ResourceBounds {max_amount: 5, max_price_per_unit: 6},
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 230 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-uOaB65PESVIj5rzl:-Ny07jaE5-aOqyaEF51h:b3hel24) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L230)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

there should be only one `if` and one `else`.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 230 at r3](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny-uOaB65PESVIj5rzl:-Ny08Bq67suPIQaSXDxW:bw10jn4) ([raw file](https://github.com/starkware-libs/mempool/blob/b9747b61020c8042496ae2e394923530f84a2a71/crates/gateway/src/starknet_api_test_utils.rs#L230)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

there should be only one `if` and one `else`.
</blockquote></details>

Oops, done.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/tests/routing_test.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny07uKh4SbeW4Q1Chs-:-Ny07uKh4SbeW4Q1Chs0:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3de750d55843932af014cc2051c9ddfbdd61df48/crates/gateway/tests/routing_test.rs#L65)):*
> ```XML
>         ),
>     ])
>     .unwrap(),
> ```





_Suggestion:_
```XML
    resource_bounds: create_resource_bounds_mapping(
        starknet_api::transaction::ResourceBounds { max_amount: 5, max_price_per_unit: 6},
        starknet_api::transaction::ResourceBounds::default()
    ),
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/tests/routing_test.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny07uKh4SbeW4Q1Chs-:-Ny0AxN1EGRJtOS6O5Ha:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3de750d55843932af014cc2051c9ddfbdd61df48/crates/gateway/tests/routing_test.rs#L65)):*
> ```XML
>         ),
>     ])
>     .unwrap(),
> ```

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131#-:-Ny0Bi7h8YLM8s6L9ejz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 6 files at r3, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131#-:-NyGHnjxDj4w-TD_SLYq:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyGE9nlBEuuwQiUAdxu:-NyGE9nmCPsEhYpa7V0x:b-hq0pka) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L1)):*
> ```XML
> use serde_json::{to_string_pretty, Value};
> ```

Arni just  added `testing` feature, let's feature-gate this module (in lib.rs) behind `cfg(feature = testing, test)`
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyFedim2Mguq6MGpxlG:-NyFedim2Mguq6MGpxlH:bncum2m) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L65)):*
> ```XML
>         }
>         TransactionType::Invoke => starknet_api::external_transaction::ExternalTransaction::Invoke(
>             external_invoke_tx(invoke_tx_args!(signature, resource_bounds, calldata,)),
> ```

Do we want `external_invoke_tx` to return by itself `ExternalTransaction::Invoke`?



_Code quote:_
```XML
        TransactionType::Invoke => starknet_api::external_transaction::ExternalTransaction::Invoke(
            external_invoke_tx(invoke_tx_args!(signature, resource_bounds, calldata,)),
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 145 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyFVu7KAlgMmH2xeKcr:-NyFVu7KAlgMmH2xeKcs:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L145)):*
> ```XML
>     .expect("Resource bounds mapping has unexpected structure.")
> }
> #[derive(Clone)]
> ```





_Suggestion:_
```XML
}

#[derive(Clone)]
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 177 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyGHaCQ249BshYJTlpC:-NyGHaCQ249BshYJTlpD:b-kb6g4u) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L177)):*
> ```XML
> }
> 
> // TODO(Ayelet, 15/5/2025): Consider moving this to StarkNet API.
> ```

+1 :grimacing: 



_Code quote:_
```XML
// TODO(Ayelet, 15/5/2025): Consider moving this to StarkNet API.
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 218 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyGEr0B0bIQHq6CCtVv:-NyGEr0B0bIQHq6CCtVw:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L218)):*
> ```XML
> pub fn external_invoke_tx_to_json(tx: ExternalTransaction) -> String {
>     // Serialize to JSON
>     let mut tx_json = serde_json::to_value(&tx).expect("Failed to serialize transaction");
> ```





_Suggestion:_
```XML
.unwrap_or_else(|tx| "Failed to serialize transaction: {tx}");
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 226 at r6](https://reviewable.io/reviews/starkware-libs/mempool/131#-NyGFdht1RsFK4vqc8xJ:-NyGFdht1RsFK4vqc8xK:b-vfokr0) ([raw file](https://github.com/starkware-libs/mempool/blob/572c68aa8d94d47a4bae9acce4fcb5aba2d7cb8b/crates/gateway/src/starknet_api_test_utils.rs#L226)):*
> ```XML
>     } else {
>         panic!("the tx was not serialized to a JSON object {tx_json}");
>     }
> ```

unwrap is ok in a test, also better hide implementation-detail structs behind `into` when possible.



_Suggestion:_
```XML
    tx_json.as_object_mut().unwrap().extend([
        ("type".to_string(), "INVOKE_FUNCTION".into()),
        ("version".to_string(), "0x3".into()),
    ]);
```

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 6 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny_2Cjg3u_4UQ163ZGK:-Ny_2Cjg3u_4UQ163ZGL:bgto7it) ([raw file](https://github.com/starkware-libs/mempool/blob/58ab8145b423b0b14e989da449d53aeff7a5d770/crates/gateway/src/gateway_test.rs#L24)):*
> ```XML
> // TODO(Ayelet): add test cases for declare and deploy account transactions.
> #[rstest]
> #[case::invoke(crate::starknet_api_test_utils::invoke_tx(), "INVOKE")]
> ```

Import this directly. (You already do it in `end_to_end_test.rs`).
(Anyway, be consistent).



_Suggestion:_
```XML
#[case::invoke(invoke_tx(), "INVOKE")]
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 254 at r10](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny_1JXj3nEPw77bpEia:-Ny_1JXj3nEPw77bpEib:bckdxby) ([raw file](https://github.com/starkware-libs/mempool/blob/58ab8145b423b0b14e989da449d53aeff7a5d770/crates/gateway/src/starknet_api_test_utils.rs#L254)):*
> ```XML
>     // Serialize to JSON
>     let mut tx_json = serde_json::to_value(&tx)
>         .unwrap_or_else(|tx| panic!("Failed to serialize transaction: {tx}"));
> ```

With your current code, the type of `tx` in `|tx|` is `Error`.

Try this:



_Suggestion:_
```XML
    let mut tx_json = serde_json::to_value(&tx)
        .unwrap_or_else(|_| panic!("Failed to serialize transaction: {tx:?}"));
```
___
*[`crates/gateway/tests/routing_test.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny_-R6F7g_yTtIfVWR6:-Ny_-R6F7g_yTtIfVWR7:bgto7it) ([raw file](https://github.com/starkware-libs/mempool/blob/58ab8145b423b0b14e989da449d53aeff7a5d770/crates/gateway/tests/routing_test.rs#L24)):*
> ```XML
> // TODO(Ayelet): add test cases for declare and deploy account transactions.
> #[rstest]
> #[case::invoke(starknet_gateway::starknet_api_test_utils::invoke_tx(), "INVOKE")]
> ```

Import this directly. (You already do it in `end_to_end_test.rs`).
(Anyway, be consistent).



_Suggestion:_
```XML
invoke_tx()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny_2Cjg3u_4UQ163ZGK:-Ny_4DJMDLAJB7lYsrdA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/58ab8145b423b0b14e989da449d53aeff7a5d770/crates/gateway/src/gateway_test.rs#L24)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Import this directly. (You already do it in `end_to_end_test.rs`).
(Anyway, be consistent).
</blockquote></details>

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 254 at r10](https://reviewable.io/reviews/starkware-libs/mempool/131#-Ny_1JXj3nEPw77bpEia:-Ny_4hx86Lu86zMegpa5:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/58ab8145b423b0b14e989da449d53aeff7a5d770/crates/gateway/src/starknet_api_test_utils.rs#L254)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

With your current code, the type of `tx` in `|tx|` is `Error`.

Try this:
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/131#-:-Ny_56GUDC1c1WcQGx9D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
