### PR TITLE
test(mempool): remove comments in add_tx_input macro

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/467#-O1p8Hh30wk1HVEQWmj1:-O1p8Hh30wk1HVEQWmj2:b-nuo84r) (no related file):*
The commit message is misleading; this is only a documentation change.

___
___
*[`crates/mempool/src/mempool_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/467#-O1p8MB4CM43eMPZNDK3:-O1p8MB4CM43eMPZNDK4:b26yhn0) ([raw file](https://github.com/starkware-libs/mempool/blob/3fa17b5ca1b6c54f0b9a4d8caeb0742fc2418f10/crates/mempool/src/mempool_test.rs#L76)):*
> ```XML
> /// 3. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8)
> /// 4. add_tx_input!(tip: 1, tx_hash: 2)
> macro_rules! add_tx_input {
> ```

Not sure if it's better, it has high chances of becoming outdated.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/467#-O1p8MB4CM43eMPZNDK3:-O1pGLDb6rRP6xdlrJUF:b-i0ch98) ([raw file](https://github.com/starkware-libs/mempool/blob/3fa17b5ca1b6c54f0b9a4d8caeb0742fc2418f10/crates/mempool/src/mempool_test.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure if it's better, it has high chances of becoming outdated.
</blockquote></details>

Naming the number of arguments is no longer relevant since we have two inputs that each have two arguments: tip and hash, and tx_nonce and account_nonce.
#451

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/mempool/467#-O1p8MB4CM43eMPZNDK3:-O1pUX9a9huvIWC2sOAu:b-baptcx) ([raw file](https://github.com/starkware-libs/mempool/blob/3fa17b5ca1b6c54f0b9a4d8caeb0742fc2418f10/crates/mempool/src/mempool_test.rs#L76)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Naming the number of arguments is no longer relevant since we have two inputs that each have two arguments: tip and hash, and tx_nonce and account_nonce.
#451
</blockquote></details>

Then let's remove these comments altogether.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/467#-O1p8Hh30wk1HVEQWmj1:-O1pcrac01u1CYPoZOzH:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The commit message is misleading; this is only a documentation change.
</blockquote></details>

Done.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467#-:-O1uaFpq9WhARhU2QJIj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
