### PR TITLE
fix: fix e2e test by using tx generator

### PR DESCRIPTION
**Pull request by giladchase**
- Make e2e use tx generator txs, which track nonces.
- As a result, the test now reflects the way the mempool behaves at the moment, and so only nonce-0 txs are returned from get_txs.
- Once get_txs begin replenishing the queue when the queue gets exhausted, this test should be fixed as per the comment below.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1k8NpbEZsNaCBg3gOq:-O1k8NpbEZsNaCBg3gOr:bc0m9oy) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L14)):*
> ```XML
>     let (mock_running_system, mut tx_generator) = setup_with_tx_generation(&accounts).await;
>     let mut expected_tx_hashes = Vec::new();
> ```

I would first create all four transactions, then send them to mempool, then assert; so that we'd have a unified test structure. I also suggested in one of Ayelet PRs to have headers: `// Setup.`, `// Test.` (the actual scenario invocation), `// Assert.`; in case a stage isn't trivial, we'll add to the comment: `// Setup: some non-trivial thing we should document.`.

Also, I didn't understand why you don't collect _all_ transaction hashes.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1pwMxjB9TswKBVp4xQ:-O1pwMxjB9TswKBVp4xR:b-uj9c5e) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L27)):*
> ```XML
> 
>     // FIXME: nonce=0 should always be deploy-account, but this currently goes into the queue.
>     // Figure out why this is currently allowed, fix it or remove this comment.
> ```

If the state has this as a deployed account (mapping address->class_hash) but the nonce of this deployed account is still 0 (read by get_storage_at), then the invoke tx with nonce 0 is accepted.

We can write nonce=1 manually to the storage in the setup phase so it will make more sense here in the test. (but more complex in the storage setup code).



_Code quote:_
```XML
// Figure out why this is currently allowed, fix it or remove this comment.
```

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1k8NpbEZsNaCBg3gOq:-O1q92Zt1hxecMNXe_kN:b-qs3gor) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L14)):*
Done.

> Also, I didn't understand why you don't collect _all_ transaction hashes.

That should be understood from the test, so it's probably not readable enough yet.
I improved readability, can you TAL again plz and let me know if it's clear now?
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1pwMxjB9TswKBVp4xQ:-O1q45YYAoJY-XoY7a2V:b-4xoaoa) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L27)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

If the state has this as a deployed account (mapping address->class_hash) but the nonce of this deployed account is still 0 (read by get_storage_at), then the invoke tx with nonce 0 is accepted.

We can write nonce=1 manually to the storage in the setup phase so it will make more sense here in the test. (but more complex in the storage setup code).
</blockquote></details>

Okay this is probably off scope for this PR, but I think this needs to be discussed soon.
 
Otherwise the same confusion I just had could happen to everyone who looks at our test suite (including our own devs).

For example, for tests that don't care about tx types, we can hide this information from the test (like a`generate_tx()` that hides the type),  but for tests that explicitly care about the tx type, we prevent the user from creating impossible states like deployed accounts with nonce=0.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uQdiGCqWbxwRWjO87:-O1uQdiGCqWbxwRWjO88:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/src/state_reader.rs#L62)):*
> ```XML
>     let block_context = BlockContext::create_for_testing();
> 
>     // map feature contracts to n_instances inside the account array
> ```





_Suggestion:_
```XML
// Map feature contracts to their number of instances inside the account array.
```
___
*[`crates/tests-integration/src/state_reader.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uRJXWB_eLgeX3sHrK:-O1uRJXWB_eLgeX3sHrL:b9ax3pa) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/src/state_reader.rs#L76)):*
> ```XML
>     }
> 
>     let fund_accounts = vec![*deploy_account_tx_contract_address()];
> ```

Confusing name.



_Code quote:_
```XML
fund_accounts
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1k8NpbEZsNaCBg3gOq:-O1uSI5x3NtSsFdJ6bLl:b6wdwn8) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.

> Also, I didn't understand why you don't collect _all_ transaction hashes.

That should be understood from the test, so it's probably not readable enough yet.
I improved readability, can you TAL again plz and let me know if it's clear now?
</blockquote></details>

I think you can delete the unused variables; this line explains it (sorry):
```rs
    let mut expected_tx_hashes_from_get_txs =
        [account0_deploy_nonce0_tx_hash, account1_invoke_nonce0_tx_hash];
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uR_eS7uff1QcVxJs-:-O1uR_eS7uff1QcVxJs0:b-8b7sd3) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/tests/end_to_end_test.rs#L17)):*
> ```XML
>     // Test.
> 
>     let account0_deploy_nonce0 = &tx_generator.account_with_id(0).generate_default_deploy_account();
> ```

I think transaction generation can also move to `Setup` section.



_Suggestion:_
```XML
    // Test.
    let account0_deploy_nonce0 = &tx_generator.account_with_id(0).generate_default_deploy_account();
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uS8kA9sbpe-JbUjKL:-O1uS8kB4vG-gvJmDPhO:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/tests/end_to_end_test.rs#L40)):*
> ```XML
> 
>     // Only the nonce-0 txs should be returned from get_txs, because we haven't merged
>     // queue-replenishment yet.
> ```





_Suggestion:_
```XML
    // Only the transactions with nonce 0 should be returned from mempool, 
    // because we haven't merged queue-replenishment yet.
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uSbnH4gSWEk-pfSg9:-O1uSbnI6weIKxt-6ZGy:bf54oeg) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/tests/end_to_end_test.rs#L50)):*
> ```XML
>         mempool_txs.iter().map(|tx| tx.tx_hash).collect();
>     actual_tx_hashes.sort();
>     expected_tx_hashes_from_get_txs.sort();
> ```

Isn't is better to compare two sets?



_Code quote:_
```XML
    actual_tx_hashes.sort();
    expected_tx_hashes_from_get_txs.sort();
```

**Review by elintul — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1pwMxjB9TswKBVp4xQ:-O1v_Qkq8dO86Qm3ZVjQ:b-d42ahl) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Okay this is probably off scope for this PR, but I think this needs to be discussed soon.
 
Otherwise the same confusion I just had could happen to everyone who looks at our test suite (including our own devs).

For example, for tests that don't care about tx types, we can hide this information from the test (like a`generate_tx()` that hides the type),  but for tests that explicitly care about the tx type, we prevent the user from creating impossible states like deployed accounts with nonce=0.
</blockquote></details>

"but the nonce of this deployed account is still 0"
Not possible, first transaction of a contract that takes nonce 0 is `DeployAccount`.

"then the invoke tx with nonce 0 is accepted"
Shouldn't get to the mempool at all, will fail GW validation.

Q: should the mempool remain agnostic to transaction type given that this can happen if used isolated from GW?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1k8NpbEZsNaCBg3gOq:-O1vmDnm-W83dos00nhj:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think you can delete the unused variables; this line explains it (sorry):
```rs
    let mut expected_tx_hashes_from_get_txs =
        [account0_deploy_nonce0_tx_hash, account1_invoke_nonce0_tx_hash];
```
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1pwMxjB9TswKBVp4xQ:-O1vma7R8XHdlhTTGmcT:b-vffqdo) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L27)):*
>Shouldn't get to the mempool at all, will fail GW validation.

Right, which is why I suggest we don't support this behavior at the state-reader level at all, it should be blocked somehow.

>Q: should the mempool remain agnostic to transaction type given that this can happen if used isolated from GW?

I think it can remain agnostic, it think we're at the test-util level, talking about whether it is being too permissive or not.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uR_eS7uff1QcVxJs-:-O1vmJ1p4TM0rmCe5oLI:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/tests/end_to_end_test.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think transaction generation can also move to `Setup` section.
</blockquote></details>

Done
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uSbnH4gSWEk-pfSg9:-O1vnBkV8BKIQvb7LdRJ:b-c5kvrx) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/tests/end_to_end_test.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't is better to compare two sets?
</blockquote></details>

Theses sorts are a bug in the test, we need to simply define the expected hashes in the correct order, then compare them to the result vector we got from get_txs, no need to sort, and dups are not possible.

Fixed.
___
*[`crates/tests-integration/src/state_reader.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uQdiGCqWbxwRWjO87:-O1vnXdW0v5P4xYnMeHa:bcmr4u1) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/src/state_reader.rs#L62)):*
> ```XML
>     let block_context = BlockContext::create_for_testing();
> 
>     // map feature contracts to n_instances inside the account array
> ```

This is from a different commit due to a rebase, fixing [on a separate PR.](https://github.com/starkware-libs/mempool/pull/488)
___
*[`crates/tests-integration/src/state_reader.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1uRJXWB_eLgeX3sHrK:-O1vncz40XhwMPWPwUiG:bjbz0q3) ([raw file](https://github.com/starkware-libs/mempool/blob/b13b97b80aeebe284c1a1b6035dff226c04502ef/crates/tests-integration/src/state_reader.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Confusing name.
</blockquote></details>

This is from a different commit, rebase issue.

Not sure how to fix rename one though, I don't think I fully understand the reason why this funding command is separate from the rest.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/461)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/461#-O1pwMxjB9TswKBVp4xQ:-O1vvTvc3oh3vErMeMHs:b-936pdc) ([raw file](https://github.com/starkware-libs/mempool/blob/2c1b04c7abb3c199b8342bafb5a4a2e4fdd51818/crates/tests-integration/tests/end_to_end_test.rs#L27)):*
> Shouldn't get to the mempool at all, will fail GW validation.

The gateway fails validation if there is the account doesn't exist, but not for invoke with nonce 0. 
This scenario probably can't happen in a real system, but it is possible in the testing environment.

> we prevent the user from creating impossible states like deployed accounts with nonce=0.
I suggest initiating the test state to a more realistic scenario - initiate all deployed accounts to with nonce 1.

**Pull request merged**
