### PR TITLE
feat: add state_reader_factory to Gateway and AppState

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-_gK35QJl3cj0rU4A:-Ny-_gK49mVytbLq7Avl:b-kh0xj6) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/stateful_transaction_validator.rs#L23)):*
> ```XML
> pub struct StatefulTransactionValidator {
>     pub config: StatefulTransactionValidatorConfig,
> }
> ```

Why would we need a clone of the StatefulTransactionValidator itself?



_Suggestion:_
```XML
pub struct StatefulTransactionValidator {
    pub config: StatefulTransactionValidatorConfig,
}
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-aHVWEEaYh7mlgGhz:-Ny-aHVWEEaYh7mlgGi-:btfn6nn) ([raw file](https://github.com/starkware-libs/mempool/blob/f39ef9515b1dbb52dd6eb088efb470815a3e6f37/crates/gateway/src/lib.rs#L15)):*
> ```XML
> mod config_test;
> #[cfg(test)]
> mod state_reader_test_utils;
> ```

We need to set the "testing" crate feature:
https://github.com/starkware-libs/blockifier/blob/cb464f5ac2ada88f2844d9f7d62bd6732ceb5b2c/crates/blockifier/BUILD#L12

What was the issue addressed here?



_Suggestion:_
```XML
#[cfg(any(feature = "testing", test))]
mod state_reader_test_utils;
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-aHVWEEaYh7mlgGhz:-Ny05AT779JW_wjyYiIQ:b-qm16ia) ([raw file](https://github.com/starkware-libs/mempool/blob/f39ef9515b1dbb52dd6eb088efb470815a3e6f37/crates/gateway/src/lib.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We need to set the "testing" crate feature:
https://github.com/starkware-libs/blockifier/blob/cb464f5ac2ada88f2844d9f7d62bd6732ceb5b2c/crates/blockifier/BUILD#L12

What was the issue addressed here?
</blockquote></details>

the tests in the tests dir won't recognize this module if it is under testing
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-_gK35QJl3cj0rU4A:-Ny-yUK994_DVvfifx8K:bkoz7fp) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/stateful_transaction_validator.rs#L23)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why would we need a clone of the StatefulTransactionValidator itself?
</blockquote></details>

because it's a part of the AppState, which needs clone for 
  

Router::new()

.route("/is\_alive", get(is\_alive))

.route("/add\_transaction", post(async\_add\_transaction))

.with\_state(app\_state)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny0MOMK4yGqHKKObq6f:-Ny0MOMLClE4Y71wQgFO:brxg4fv) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/gateway.rs#L37)):*
> ```XML
>     pub stateful_transaction_validator_config: StatefulTransactionValidatorConfig,
>     pub network_component: GatewayNetworkComponent,
>     pub state_reader_factory: T,
> ```

I think using `dyn StateReaderFactory<...>` would be appropriate here.
Please look into it...

Same for the `AppState` struct.



_Code quote:_
```XML
pub state_reader_factory: T
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny0MOMK4yGqHKKObq6f:-NyEWqd22p_swZ7vlLrT:b-ut9g7t) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/gateway.rs#L37)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think using `dyn StateReaderFactory<...>` would be appropriate here.
Please look into it...

Same for the `AppState` struct.
</blockquote></details>

From reading about the dyn property in the rust book 
(https://doc.rust-lang.org/book/ch17-02-trait-objects.html#using-trait-objects-that-allow-for-values-of-different-types)

I understand that it should be used when you need to allow for multiple concrete types to fill in for the trait object at runtime. This incurs a performance cost  since rust must perform dynamic dispatch, instead of static dispatch which is possible when the type is the trait object is not dynamic.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny0MOMK4yGqHKKObq6f:-NyF5Hc-9HK8MxTazr27:b-qhicdq) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/gateway.rs#L37)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

From reading about the dyn property in the rust book 
(https://doc.rust-lang.org/book/ch17-02-trait-objects.html#using-trait-objects-that-allow-for-values-of-different-types)

I understand that it should be used when you need to allow for multiple concrete types to fill in for the trait object at runtime. This incurs a performance cost  since rust must perform dynamic dispatch, instead of static dispatch which is possible when the type is the trait object is not dynamic.
</blockquote></details>

Right.

But it makes all the code generic, and not so readable. In this case the tradeoff of less efficient code worth the readability and simplicity the code.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-aHVWEEaYh7mlgGhz:-NyFQhaW53mkMLjCCIVF:beigbtb) ([raw file](https://github.com/starkware-libs/mempool/blob/f39ef9515b1dbb52dd6eb088efb470815a3e6f37/crates/gateway/src/lib.rs#L15)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

the tests in the tests dir won't recognize this module if it is under testing
</blockquote></details>

Unblocking, but maybe after this one gets in: #141.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyFVWWN4ExvLawoQ7Xb:-NyFVWWN4ExvLawoQ7Xc:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/43ae467ef7988de50537f4c8ea6f0eb0ca49be00/crates/gateway/src/gateway_test.rs#L67)):*
> ```XML
>         stateful_transaction_validator: StatefulTransactionValidator {
>             config: stateful_transaction_validator_config,
>         },
> ```





_Suggestion:_
```XML

    let mut app_state = AppState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                ..Default::default()
            },
        },
        stateful_transaction_validator: StatefulTransactionValidator {
            config: StatefulTransactionValidatorConfig::create_for_testing(),
        },
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-aHVWEEaYh7mlgGhz:-NyFZVnt8oMYw4cl4SVw:bol5c2e) ([raw file](https://github.com/starkware-libs/mempool/blob/f39ef9515b1dbb52dd6eb088efb470815a3e6f37/crates/gateway/src/lib.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Unblocking, but maybe after this one gets in: #141.
</blockquote></details>

The feature `testing` is now supported. Please rebase and add:

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyFZ93P6OosAnjqoi2F:-NyFZ93P6OosAnjqoi2G:bol5c2e) ([raw file](https://github.com/starkware-libs/mempool/blob/43ae467ef7988de50537f4c8ea6f0eb0ca49be00/crates/gateway/src/stateful_transaction_validator.rs#L93)):*
> ```XML
>         }
>     }
> }
> ```

The feature `testing` is now supported. Please rebase and add:



_Suggestion:_
```XML
#[cfg(any(feature = "testing", test))]
impl StatefulTransactionValidatorConfig {
    pub fn create_for_testing() -> Self {
        StatefulTransactionValidatorConfig {
            max_nonce_for_validation_skip: Default::default(),
            validate_max_n_steps: 1000000,
            max_recursion_depth: 50,
            chain_info: Default::default(),
        }
    }
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny0MOMK4yGqHKKObq6f:-NyKweyhDoq3O7ruNUab:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2e03728018e00f68753e7704a614f5826a4e5e4d/crates/gateway/src/gateway.rs#L37)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Right.

But it makes all the code generic, and not so readable. In this case the tradeoff of less efficient code worth the readability and simplicity the code.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyFVWWN4ExvLawoQ7Xb:-NyKwgBe6BVkE4FrYA0Z:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/43ae467ef7988de50537f4c8ea6f0eb0ca49be00/crates/gateway/src/gateway_test.rs#L67)):*
> ```XML
>         stateful_transaction_validator: StatefulTransactionValidator {
>             config: stateful_transaction_validator_config,
>         },
> ```

done
___
*[`crates/gateway/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/139#-Ny-aHVWEEaYh7mlgGhz:-NyKwhLQ-u8gSrveVLSV:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/f39ef9515b1dbb52dd6eb088efb470815a3e6f37/crates/gateway/src/lib.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The feature `testing` is now supported. Please rebase and add:
</blockquote></details>

done

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 6 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyPZUDs70X-Ga7Q3jhd:-NyPZUDs70X-Ga7Q3jhe:b3wcr6l) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/rpc_state_reader.rs#L23)):*
> ```XML
> use crate::state_reader::{MempoolStateReader, StateReaderFactory};
> 
> #[derive(Clone)]
> ```

Why do we need the`Clone`?



_Code quote:_
```XML
#[derive(Clone)]
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyPbzq68PdRWcqItRmR:-NyPbzq76L8Jh_TSNnma:b-59ndwa) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/rpc_state_reader.rs#L168)):*
> ```XML
> }
> 
> #[derive(Clone)]
> ```

Here as well...
We store the factory within an Arc in the `AppState`, so I don't think it is cloned.



_Code quote:_
```XML
#[derive(Clone)]
```
___
*[`crates/gateway/src/state_reader.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyPV9e8DKiLZ7wkB-tl:-NyPV9e8DKiLZ7wkB-tm:bguf6kn) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/state_reader.rs#L18)):*
> ```XML
>     fn get_state_reader(&self, block_number: BlockNumber) -> Box<dyn MempoolStateReader>;
> }
> ```

Please add a comment explaining the issue:

```
By default, a Box<dyn Trait> does not implement the trait of the object it 
contains. Therefore, creating a generic object Foo<Box<dyn Trait>> will not work. 
We provide a default implementation for the StateReader traits to address this issue.
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyP_tfC8g_vD4ZheDhU:-NyP_tfC8g_vD4ZheDhV:b64b5h6) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/stateful_transaction_validator.rs#L20)):*
> ```XML
> mod stateful_transaction_validator_test;
> 
> #[derive(Clone)]
> ```

Same here, why the clone?
if it is the `AppState`, try adding an Arc to avoid the clone.



_Code quote:_
```XML
#[derive(Clone)]
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139#-:-NyPobna1Xx5tDrEzJ7n:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyP_tfC8g_vD4ZheDhU:-NyPoCND7e2VK5BYaBBJ:bjh97wx) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/stateful_transaction_validator.rs#L20)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.

we may want to add Arc also to the other members of the AppState
</blockquote></details>

Right.But that for another PR, together with changing the Gatway to hold an AppState.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/mempool/139#-NyP_tfC8g_vD4ZheDhU:-NyPorKM6uWi0Hlw3mUX:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d326656b5746add65023eed5e229656484d6f321/crates/gateway/src/stateful_transaction_validator.rs#L20)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Right.But that for another PR, together with changing the Gatway to hold an AppState.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/139#-:-NyQMw1W-H7sGajMhSfd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
