### PR TITLE
feat(mempool): impl remove from nonce for transaction pool

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1WYdmV9bJqRT7X7SOz:-O1WYdmV9bJqRT7X7SP-:b-y39zqa) (no related file):*
This PR implements the `remove_from_nonce` method for the `TransactionPool`. It removes all transactions from tx_pool and from `tx_by_account` with nonces lower than or equal to the specified nonce.

This method is used in mempool's `commit_block` method.

___

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1Wkitc3NUmJiAC_uWW:-O1Wkitc3NUmJiAC_uWX:b7r139r) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L67)):*
> ```XML
>         &mut self,
>         address: ContractAddress,
>         nonce: Nonce,
> ```

OK officially too many of this pattern now :grimacing: 
Think of a abstraction that makes sense and is nice to use for this file.



_Code quote:_
```XML
        address: ContractAddress,
        nonce: Nonce,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kAtBV3xr4SqvAIt_I:-O1kAtBV3xr4SqvAIt_J:b9rng4x) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L69)):*
> ```XML
>         nonce: Nonce,
>     ) -> MempoolResult<()> {
>         let txs = self.txs_by_account.remove_from_nonce(address, nonce);
> ```

Guessing you meant `remove_up_to_nonce`?



_Code quote:_
```XML
remove_from_nonce
```
___
*[`crates/mempool/src/transaction_pool.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kB4IoDU4L014uGJYI:-O1kB4IoDU4L014uGJYJ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L69)):*
> ```XML
>         nonce: Nonce,
>     ) -> MempoolResult<()> {
>         let txs = self.txs_by_account.remove_from_nonce(address, nonce);
> ```





_Suggestion:_
```XML
removed_txs
```
___
*[`crates/mempool/src/transaction_pool.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kB9JO2KwOVuiud1vs:-O1kB9JO2KwOVuiud1vt:b-15xkzm) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L72)):*
> ```XML
>         for TransactionReference { tx_hash, .. } in txs {
>             if self.tx_pool.remove(&tx_hash).is_none() {
>                 return Err(MempoolError::TransactionNotFound { tx_hash });
> ```

Is this an error a user has something to do with, or does it indicate a bug of ours (in which case we should `panic`)?
Same for `remove` above, by hash.



_Code quote:_
```XML
MempoolError::TransactionNotFound
```
___
*[`crates/mempool/src/transaction_pool.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kB7FcEORnzQ5Vrchm:-O1kB7FcEORnzQ5Vrchn:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L75)):*
> ```XML
>             }
>         }
>         Ok(())
> ```





_Suggestion:_
```XML
        
        for TransactionReference { tx_hash, .. } in txs {
            if self.tx_pool.remove(&tx_hash).is_none() {
                return Err(MempoolError::TransactionNotFound { tx_hash });
            }
        }
        
        Ok(())
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kAtBV3xr4SqvAIt_I:-O1kXHez0EMLqY-19SnN:b32dhr2) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Guessing you meant `remove_up_to_nonce`?
</blockquote></details>

Changed to `remove_txs_up_to_nonce`.
___
*[`crates/mempool/src/transaction_pool.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1kB9JO2KwOVuiud1vs:-O1kXl1Q2gLrLvE1jAGk:b-32bwgl) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this an error a user has something to do with, or does it indicate a bug of ours (in which case we should `panic`)?
Same for `remove` above, by hash.
</blockquote></details>

Changed to panic.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1Wkitc3NUmJiAC_uWW:-O1lHMPA5WnKwODF_6fT:b-3ig91k) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L67)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

OK officially too many of this pattern now :grimacing: 
Think of a abstraction that makes sense and is nice to use for this file.
</blockquote></details>

I added a `TransactionIdentifier` struct in a separate [PR](https://github.com/starkware-libs/mempool/pull/468).
WDYT?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448#-:-O1pbXLL48YK-UW2Ph0L:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1Wkitc3NUmJiAC_uWW:-O1qh2oB7y6K3DUzWKHv:b-3j1t5v) ([raw file](https://github.com/starkware-libs/mempool/blob/c19fd6ce1ad33a92f7eb904b7b2ce510291818d4/crates/mempool/src/transaction_pool.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I added a `TransactionIdentifier` struct in a separate [PR](https://github.com/starkware-libs/mempool/pull/468).
WDYT?
</blockquote></details>

U said it was annoying, so let's let this one go for now...

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1vb-_H5sTl7cG4vSfU:-O1vb-_H5sTl7cG4vSfV:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/304bff42966b947ed45e17a22c5de2c60ef416ca/crates/mempool/src/transaction_pool.rs#L64)):*
> ```XML
>     }
> 
>     pub fn remove_txs_up_to_nonce(&mut self, address: ContractAddress, nonce: Nonce) {
> ```





_Suggestion:_
```XML
remove_up_to_nonce
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1vzMwW9He_pkm4z3YE:-O1vzMwW9He_pkm4z3YF:bt2ux05) ([raw file](https://github.com/starkware-libs/mempool/blob/f6e49cfad8cd04c41742ef51608803cd487c03bb/crates/mempool/src/mempool.rs#L85)):*
> ```XML
>             }
> 
>             // remove committed transactions from the pool.
> ```

Inaccurate comment: `// Remove transactions of committed nonces from pool.` and it's optional since flow is clear thanks to good naming. Your call!

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1wSARH2wXhFA4sgUIN:-O1wSARI0mM0RAp9l0NV:bvnmvff) ([raw file](https://github.com/starkware-libs/mempool/blob/f6e49cfad8cd04c41742ef51608803cd487c03bb/crates/mempool/src/transaction_pool.rs#L73)):*
> ```XML
>                      in account mapping, but does not appear in the main mapping"
>                 );
>             }
> ```

better use `unwrap_or_else` here, it's lazy.
Creating `String` is expensive, since it uses the heap.



_Code quote:_
```XML
            if self.tx_pool.remove(&tx_hash).is_none() {
                panic!(
                    "Transaction pool consistency error: transaction with hash {tx_hash} appears \
                     in account mapping, but does not appear in the main mapping"
                );
            }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1vzMwW9He_pkm4z3YE:-O1zuD1j3R0l65XM6txv:bss4a2b) ([raw file](https://github.com/starkware-libs/mempool/blob/f6e49cfad8cd04c41742ef51608803cd487c03bb/crates/mempool/src/mempool.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Inaccurate comment: `// Remove transactions of committed nonces from pool.` and it's optional since flow is clear thanks to good naming. Your call!
</blockquote></details>

Removed.
___
*[`crates/mempool/src/transaction_pool.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/mempool/448#-O1wSARH2wXhFA4sgUIN:-O2-MuO97nKva-GKAzYS:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/f6e49cfad8cd04c41742ef51608803cd487c03bb/crates/mempool/src/transaction_pool.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

better use `unwrap_or_else` here, it's lazy.
Creating `String` is expensive, since it uses the heap.
</blockquote></details>

Done

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/448)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
