### PR TITLE
feat: declare post compilation builtin validation

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/296?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#297** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/297?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#296** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/296?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#246** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/246?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#235** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/234?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0O11mYC2gFg6AwJDAM:b-kp69qk) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
> ```XML
>         "segment_arena".to_string(),
>     ]
> }
> ```

must these be strings? enum would be prettier but I assume the set of builtins is defined as strings by the cairo library so it doesn't make sense to store it differently only for this check.



_Code quote:_
```XML
fn get_supported_builtins() -> Vec<String> {
    vec![
        "pedersen".to_string(),
        "range_check".to_string(),
        "ecdsa".to_string(),
        "bitwise".to_string(),
        "ec_op".to_string(),
        "poseidon".to_string(),
        "segment_arena".to_string(),
    ]
}
```
___
*[`crates/gateway/src/gateway.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O0yQy64DcpXFLkDdk:-O0O0yQy64DcpXFLkDdl:b-b46c42) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L208)):*
> ```XML
>     for entry_point in entry_points_iterator {
>         let builtins = &entry_point.builtins;
>         println!("{builtins:?}");
> ```

left here by mistake?



_Code quote:_
```XML
println!("{builtins:?}");
```
___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0O-ol-92GzPcWp7beb:b-cz7var) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
> ```XML
> 
>     offset == subsequence.len()
> }
> ```

From ChatGPT :)



_Suggestion:_
```XML
/// Checks whether 'subsequence' is a subsequence of 'sequence'.
pub fn is_subsequence(subsequence: &[String], sequence: &[String]) -> bool {
    subsequence.iter().all(|item| sequence.contains(item))
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0OG6tT8dduPVOt3HLb:bwpbma3) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

must these be strings? enum would be prettier but I assume the set of builtins is defined as strings by the cairo library so it doesn't make sense to store it differently only for this check.
</blockquote></details>

Their definition in Cairo-lang is somewhat complicated.
___
*[`crates/gateway/src/gateway.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O0yQy64DcpXFLkDdk:-O0O4ud78Mr4Vqzc8nf-:bss4a2b) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L208)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

left here by mistake?
</blockquote></details>

Removed.
___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0OFnZq565EcOIUMCSD:btaqznx) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

From ChatGPT :)
</blockquote></details>

Done.

I used a different code. I did that, assuming the order matters. I need to get back to you why the order is important. Also added a test.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @ilyalesokhin-starkware, and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0brcpg25O6metc4HOt:b-466f5k) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
According to @ilyalesokhin-starkware, the order is important.
> Yes, the order is important the OS does not support arbitrary order

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0cLtw3-Ny-GNMYrDpe:btr56jy) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Their definition in Cairo-lang is somewhat complicated.
</blockquote></details>

Added this PR on top of this one: #319. It is connected to a PR in the starknet-api repo: see: https://github.com/starkware-libs/starknet-api/pull/288

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @ilyalesokhin-starkware, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0ci0uz06O_stK7eZDa:b-bqnzu5) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Added this PR on top of this one: #319. It is connected to a PR in the starknet-api repo: see: https://github.com/starkware-libs/starknet-api/pull/288
</blockquote></details>

Why not use a static variable?
___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0cid8jCb0-9WzMrxDU:b-85f9b0) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

According to @ilyalesokhin-starkware, the order is important.
> Yes, the order is important the OS does not support arbitrary order
</blockquote></details>

Is the order being checked by the `contains` function, which consumes the iterator up to the found item?
IMO this is very confusing. Consider using nested `for` loops.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0cyYKoE8L54UmL1Cvi:b-un31nm) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is the order being checked by the `contains` function, which consumes the iterator up to the found item?
IMO this is very confusing. Consider using nested `for` loops.
</blockquote></details>

Did you see the version from Revision 1? Is it preferable?

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0h5La-6_sTfFOjlEYr:b-l4c9p) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Did you see the version from Revision 1? Is it preferable?
</blockquote></details>

I think so.
Also, consider making the function generic instead of String type:
```
fn is_subsequence<T: Eq>(subsequence: &[T], sequence: &[T]) -> bool
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @ilyalesokhin-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0hePVKEMAqoIO2sqOK:bzapp2b) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think so.
Also, consider making the function generic instead of String type:
```
fn is_subsequence<T: Eq>(subsequence: &[T], sequence: &[T]) -> bool
```
</blockquote></details>

I agree that this is confusing, not sure I understand how the order is kept here.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O-ol-92GzPcWp7bea:-O0i3o6i4RfAxHW7da6S:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I agree that this is confusing, not sure I understand how the order is kept here.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ilyalesokhin-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/errors.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lyD-fCg1kcTnC22TX:-O0lyD-fCg1kcTnC22TY:bd9thmn) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/errors.rs#L42)):*
> ```XML
>     StatelessTransactionValidatorError(#[from] StatelessTransactionValidatorError),
>     #[error("{builtins:?} is not a subsquence of {supported_builtins:?}")]
>     SupportedBuiltins { builtins: Vec<String>, supported_builtins: Vec<String> },
> ```

UnsupportedBuiltins?



_Code quote:_
```XML
SupportedBuiltins
```
___
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0lu5gIAxXFdHSFb9dG:b-8suyt0) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not use a static variable?
</blockquote></details>

+1 for static variable.
___
*[`crates/gateway/src/gateway.rs` line 200 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lwUGgBiIlEOJ7pCpl:-O0lwUGgBiIlEOJ7pCpm:b2ap498) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/gateway.rs#L200)):*
> ```XML
> fn get_supported_builtins() -> Vec<String> {
>     let builtins =
>         ["pedersen", "range_check", "ecdsa", "bitwise", "ec_op", "poseidon", "segment_arena"];
> ```

Add a comment that the order is important.



_Code quote:_
```XML
    let builtins =
        ["pedersen", "range_check", "ecdsa", "bitwise", "ec_op", "poseidon", "segment_arena"];
```
___
*[`crates/gateway/src/utils_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lzLHODGJQNCH9nuz6:-O0lzLHP8I6z3GuXbMoG:b-3ma4vs) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/utils_test.rs#L32)):*
> ```XML
>     true
> )]
> #[case::subsequence_1(
> ```

I guess that's you meant.



_Suggestion:_
```XML
#[case::subsequence_2(
    &["b"],
    &["a", "b", "c"],
    true
)]
#[case::subsequence_3(
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @ilyalesokhin-starkware)

___
*[`crates/gateway/src/errors.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lyD-fCg1kcTnC22TX:-O0mVRg9DRJrJvVhm4_t:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/errors.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

UnsupportedBuiltins?
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL:-O0cyha1EQGaGVgVe05y:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/332ec2c1f437cf17dab2eed41d9f7075612ebe72/crates/gateway/src/gateway.rs#L197)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

+1 for static variable.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 200 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lwUGgBiIlEOJ7pCpl:-O0mVSvv-F4YuNtyJJwV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/gateway.rs#L200)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Add a comment that the order is important.
</blockquote></details>

Done.
___
*[`crates/gateway/src/utils_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0lzLHODGJQNCH9nuz6:-O0mVK4w0H5OlPwbQnAd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ab76a255e995ad925cad132bc76346adf0d21078/crates/gateway/src/utils_test.rs#L32)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I guess that's you meant.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @ilyalesokhin-starkware)

___
*[`crates/gateway/src/gateway.rs` line 206 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mh9s_6TRoSWFuPHnn:-O0mh9sa1UGF80uchaiQ:b-k0bax) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L206)):*
> ```XML
>             ["pedersen", "range_check", "ecdsa", "bitwise", "ec_op", "poseidon", "segment_arena"];
>         SUPPORTED_BUILTIN_NAMES.iter().map(|builtin| builtin.to_string()).collect::<Vec<String>>()
>     };
> ```

It can be just a static const.



_Suggestion:_
```XML
    // The OS expects this order for the builtins.
    const SUPPORTED_BUILTINS: [&'static str; 7] = [
            "pedersen", "range_check", "ecdsa", "bitwise", "ec_op", "poseidon", "segment_arena"];
    };
```
___
*[`crates/gateway/src/gateway.rs` line 224 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mk3v7BMtetbS9b6TR:-O0mk3v7BMtetbS9b6TS:bmk72lu) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L224)):*
> ```XML
>             });
>         }
>     }
> ```

Please avoid defining variables that are only used once, and are self explanatory.



_Suggestion:_
```XML
    for entry_point in entry_points_iterator {
        let builtins = &entry_point.builtins;
        if !is_subsequence(builtins, supported_builtins) {
            return Err(GatewayError::UnsupportedBuiltins {
                builtins: builtins.clone(),
                supported_builtins: &SUPPORTED_BUILTINS.to_vec(),
            });
        }
    }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @ilyalesokhin-starkware)

___
*[`crates/gateway/src/gateway.rs` line 206 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mh9s_6TRoSWFuPHnn:-O0mvbXy6T9th5v8S6CM:b-avsp6p) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L206)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It can be just a static const.
</blockquote></details>

Done.
```
constants have by default a `'static` lifetime
```

___
*[`crates/gateway/src/gateway.rs` line 224 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mk3v7BMtetbS9b6TR:-O0mvvHS7YSEVIfHdCDq:b-h22zb1) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L224)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please avoid defining variables that are only used once, and are self explanatory.
</blockquote></details>

At least in the current implementation, we need to convert `&str -> String` and save the result to a variable.
See the updated code. (Note taken for upstream PR).

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @ilyalesokhin-starkware)

___
*[`crates/gateway/src/gateway.rs` line 224 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mk3v7BMtetbS9b6TR:-O0n7izI1TiB5UCuv430:b-zg96ts) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L224)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

At least in the current implementation, we need to convert `&str -> String` and save the result to a variable.
See the updated code. (Note taken for upstream PR).
</blockquote></details>

Oh. I missed the conversion to string thing...
In that case let's go back to the lazy static.

Sorry for the confusion.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 224 at r5](https://reviewable.io/reviews/starkware-libs/mempool/296#-O0mk3v7BMtetbS9b6TR:-O0nDlBA3iy-gZeO8ITn:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0c30c7a3a8221a4510b1e3e814962b9039d5e3ca/crates/gateway/src/gateway.rs#L224)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Oh. I missed the conversion to string thing...
In that case let's go back to the lazy static.

Sorry for the confusion.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296#-:-O0nExcxAvugCw8LOfVj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by dafnamatsry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry and @ilyalesokhin-starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 6 files at r5, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/296)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @ilyalesokhin-starkware)

**Pull request merged**
