### PR TITLE
refactor: move app function to gateway method

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxfducG3ApHlczZkkfF:-NxfducG3ApHlczZkkfG:b-yjfl99) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L47)):*
> ```XML
> 
>     // TODO(Arni, 7/5/2024): Change this function to accept GatewayConfig.
>     /// Sets up the router with the specified routes for the server.
> ```

Please delete :) (TY!)
I have a similar todo covering this
`Move the stateless transaction validator config into the gateway config.`
___
*[`crates/gateway/src/gateway.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxfeVfx3GZm7Mz_DPPC:-NxfeVfx3GZm7Mz_DPPD:bfl0rn6) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L63)):*
> ```XML
>         // `with_state`.
>     }
> }
> ```

I know this PR is a shortened version of #106 already.

Consider splitting this PR in two. 
Part 1: Just making `app` from a function into a method of `Gateway`.
Part 2: Adding `network` to the app-state.



_Code quote:_
```XML
    pub fn app(self) -> Router {
        let app_state = AppState {
            stateless_transaction_validator: StatelessTransactionValidator {
                config: self.stateless_transaction_validator_config,
            },
            network: Arc::new(self.network),
        };

        Router::new()
            .route("/is_alive", get(is_alive))
            .route("/add_transaction", post(async_add_transaction))
            .with_state(app_state)
        // TODO: when we need to configure the router, like adding banned ips, add it here via
        // `with_state`.
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxftI5t39GATgcQc3Nk:-NxftI5u0zetYCZAoEo5:b-198usb) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L33)):*
> ```XML
> pub struct AppState {
>     pub stateless_transaction_validator: StatelessTransactionValidator,
>     pub network: Arc<GatewayNetworkComponent>,
> ```

Please document that the `network` variable is shared ownership with the Gateway (Maybe the reason why `GatewayNetworkComponent` does not implement clone).

Delete all mentions of workarounds etc. Document it only here.



_Code quote:_
```XML
    pub network: Arc<GatewayNetworkComponent>,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxftI5t39GATgcQc3Nk:-Nxg2ADd5NsGaX2RsnZY:bw5xnm5) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L33)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please document that the `network` variable is shared ownership with the Gateway (Maybe the reason why `GatewayNetworkComponent` does not implement clone).

Delete all mentions of workarounds etc. Document it only here.
</blockquote></details>

It was resolved in the [following PR](https://reviewable.io/reviews/starkware-libs/mempool/123).
___
*[`crates/gateway/src/gateway.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxfducG3ApHlczZkkfF:-Nxg23jz0kYwzglv2xOB:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L47)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please delete :) (TY!)
I have a similar todo covering this
`Move the stateless transaction validator config into the gateway config.`
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxfeVfx3GZm7Mz_DPPC:-Nxg253a2RpqZ1uqqoo4:bawu5f3) ([raw file](https://github.com/starkware-libs/mempool/blob/d2bc428870491cacd5051933d6376d2e746b2ae6/crates/gateway/src/gateway.rs#L63)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I know this PR is a shortened version of #106 already.

Consider splitting this PR in two. 
Part 1: Just making `app` from a function into a method of `Gateway`.
Part 2: Adding `network` to the app-state.
</blockquote></details>

Done.
New PR:
https://reviewable.io/reviews/starkware-libs/mempool/123

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121#-:-NxgFAHb9rsrl3tIcZ-t:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEFy6-I5aWzojt7vp:-NxgEFy6-I5aWzojt7vq:b-w2qrxv) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/src/gateway.rs#L27)):*
> ```XML
>     pub stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
>     pub network: GatewayNetworkComponent,
> }
> ```

Non-blocking. 
I don't like that there are two `network` things here now (I am also to blame - I just merged #110).

`network_config` is about the "internet connection" (TCP/IP).
`network` is about inter-component connection. 



_Code quote:_
```XML
pub struct Gateway {
    pub network_config: GatewayNetworkConfig,
    // TODO(Arni, 7/5/2024): Move the stateless transaction validator config into the gateway
    // config.
    pub stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
    pub network: GatewayNetworkComponent,
}
```
___
*[`crates/gateway/tests/routing_test.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEhtGE8WlYdQYlXyz:-NxgEhtGE8WlYdQYlXz-:b-8o6rwq) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/tests/routing_test.rs#L0)):*
Nice!
Much cleaner now. 
___
*[`crates/gateway/tests/routing_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEqtj3B6Cq_3HVaii:-NxgEqtj3B6Cq_3HVaij:b-4va43c) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/tests/routing_test.rs#L71)):*
> ```XML
>         stateless_transaction_validator_config,
>         network: gateway_network,
>     };
> ```

non-blocking. Not for now.



_Suggestion:_
```XML
    let gateway = Gateway {
        network_config,
        stateless_transaction_validator_config,
        network: componnet_network, // gateway_network_channel
    };
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEFy6-I5aWzojt7vp:-NxgICiP-lhjrqT9VxJs:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/src/gateway.rs#L27)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Non-blocking. 
I don't like that there are two `network` things here now (I am also to blame - I just merged #110).

`network_config` is about the "internet connection" (TCP/IP).
`network` is about inter-component connection.
</blockquote></details>

Done
___
*[`crates/gateway/tests/routing_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEqtj3B6Cq_3HVaii:-NxgI0YOEu0RNW9dhSNt:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/tests/routing_test.rs#L71)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

non-blocking. Not for now.
</blockquote></details>

done
___
*[`crates/gateway/tests/routing_test.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/mempool/121#-NxgEhtGE8WlYdQYlXyz:-NxgI2K01mzmI1aGcHkr:bswkuk4) ([raw file](https://github.com/starkware-libs/mempool/blob/26772521e527860d443cf13d84f8b5ab54cd199f/crates/gateway/tests/routing_test.rs#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Nice!
Much cleaner now.
</blockquote></details>

Merci :)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Pull request merged**
