### PR TITLE
feat: spawn new thread for each add_transaction request

### PR DESCRIPTION
**Pull request by dafnamatsry**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-NwnjRLU-bCh7r3uSPpF:-NwnjRLU-bCh7r3uSPpG:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/Cargo.toml#L22)):*
> ```TOML
> tower.workspace = true
> validator.workspace = true
> tokio.workspace = true
> ```





_Suggestion:_
```TOML
tokio.workspace = true
tower.workspace = true
validator.workspace = true
```
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-Nwnjmpk7UjIdPntTc6r:-Nwnjmpk7UjIdPntTc6s:bjyrabj) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/src/gateway.rs#L59)):*
> ```XML
>         .await
>         .map_err(|_| GatewayError::InternalServerError)
> }
> ```

If we define the enum this way it'll also show the error message (which will probably point to a line inside add_transaction that panicked the running thread)
```
#[error(Internal server error: {0} ]
InternalServerError(#[from] JoinError)
```
The usage will then be `.await.map_err(GatewayError::InternalServerError)`.

Downside is that this makes InternalServerError be a JoinError wrapper, but this can be changed once/if we ever decide to utilize this variant with a different type of error.



_Code quote:_
```XML
async fn async_add_transaction(Json(transaction): Json<ExternalTransaction>) -> impl IntoResponse {
    tokio::task::spawn_blocking(move || add_transaction(transaction))
        .await
        .map_err(|_| GatewayError::InternalServerError)
}
```
___
*[`crates/gateway/src/gateway_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-NwntrUs7rq_143XnMw4:-NwntrUt70_uqpHwNtLF:b-oq65js) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/src/gateway_test.rs#L40)):*
> ```XML
>     "DEPLOY_ACCOUNT"
> )]
> #[case::invoke(&Path::new(TEST_FILES_FOLDER).join("invoke_v3.json"), "INVOKE")]
> ```

Third time we are using this pattern, twice here and once in `routing_test.rs`.

Just making a mental note here to think about a way of not having this duplication, because we'll likely keep needing this pattern in future test



_Code quote:_
```XML
#[case::declare(&Path::new(TEST_FILES_FOLDER).join("declare_v3.json"), "DECLARE")]
#[case::deploy_account(
    &Path::new(TEST_FILES_FOLDER).join("deploy_account_v3.json"),
    "DEPLOY_ACCOUNT"
)]
#[case::invoke(&Path::new(TEST_FILES_FOLDER).join("invoke_v3.json"), "INVOKE")]
```

**Review by giladchase — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62#-:-NwnuBZ-5uYSCgk3lH2W:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-NwnjRLU-bCh7r3uSPpF:-NwsQZBeAbr6wVIiL4zu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/Cargo.toml#L22)):*
> ```TOML
> tower.workspace = true
> validator.workspace = true
> tokio.workspace = true
> ```

Done.
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-Nwnjmpk7UjIdPntTc6r:-NwsXg-y6CELG1a6_EqB:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If we define the enum this way it'll also show the error message (which will probably point to a line inside add_transaction that panicked the running thread)
```
#[error(Internal server error: {0} ]
InternalServerError(#[from] JoinError)
```
The usage will then be `.await.map_err(GatewayError::InternalServerError)`.

Downside is that this makes InternalServerError be a JoinError wrapper, but this can be changed once/if we ever decide to utilize this variant with a different type of error.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/62#-NwntrUs7rq_143XnMw4:-NxLoeiSEDVin7xsmZ68:bvymiid) ([raw file](https://github.com/starkware-libs/mempool/blob/ef93f8b15e1e2fdfefea3ed227c8827afee7b66e/crates/gateway/src/gateway_test.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Third time we are using this pattern, twice here and once in `routing_test.rs`.

Just making a mental note here to think about a way of not having this duplication, because we'll likely keep needing this pattern in future test
</blockquote></details>

Removed this test and just changed the other one to test only the async version.

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/62#-NxM4Au-6mSy_neI_II_:-NxM4Au05SmTTanuIv2Y:b-ymux3t) ([raw file](https://github.com/starkware-libs/mempool/blob/612e38ea75975853f8f5b0323b3c9ecc015df538/crates/gateway/src/gateway.rs#L73)):*
> ```XML
> fn add_transaction(
>     gateway_state: GatewayState,
>     transaction: ExternalTransaction,
> ```

What's the use case for this one given the async version and given this one's removal from the Routing table?

If it's only for unit tests then consider putting it behind cfg(test)



_Code quote:_
```XML
fn add_transaction(
    gateway_state: GatewayState,
    transaction: ExternalTransaction,
```
___
*[`crates/gateway/src/gateway_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/62#-NxM3ecG4Ii67MtQbRpZ:-NxM3ecG4Ii67MtQbRp_:b-631bqy) ([raw file](https://github.com/starkware-libs/mempool/blob/612e38ea75975853f8f5b0323b3c9ecc015df538/crates/gateway/src/gateway_test.rs#L29)):*
> ```XML
> #[tokio::test]
> async fn test_add_transaction(#[case] json_file_path: &Path, #[case] expected_response: &str) {
>     use crate::gateway::async_add_transaction;
> ```

Happened to me as well, maybe rstest/tokio/rust-analyzer bug?



_Suggestion:_
```XML
};

use crate::gateway::async_add_transaction;
    
const TEST_FILES_FOLDER: &str = "./tests/fixtures";

// TODO(Ayelet): Replace the use of the JSON files with generated instances, then serialize these
// into JSON for testing.
#[rstest]
#[case::declare(&Path::new(TEST_FILES_FOLDER).join("declare_v3.json"), "DECLARE")]
#[case::deploy_account(
    &Path::new(TEST_FILES_FOLDER).join("deploy_account_v3.json"),
    "DEPLOY_ACCOUNT"
)]
#[case::invoke(&Path::new(TEST_FILES_FOLDER).join("invoke_v3.json"), "INVOKE")]
#[tokio::test]
async fn test_add_transaction(#[case] json_file_path: &Path, #[case] expected_response: &str) {
```

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/62#-NxM4Au-6mSy_neI_II_:-NxMJTDFEvKWzwzj-Yxy:b5xv4xr) ([raw file](https://github.com/starkware-libs/mempool/blob/612e38ea75975853f8f5b0323b3c9ecc015df538/crates/gateway/src/gateway.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What's the use case for this one given the async version and given this one's removal from the Routing table?

If it's only for unit tests then consider putting it behind cfg(test)
</blockquote></details>

Not sure I follow.
The async version runs this in a separate thread.
___
*[`crates/gateway/src/gateway_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/62#-NxM3ecG4Ii67MtQbRpZ:-NxMJHVu2YvxAFidnl04:b-gg2kk3) ([raw file](https://github.com/starkware-libs/mempool/blob/612e38ea75975853f8f5b0323b3c9ecc015df538/crates/gateway/src/gateway_test.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Happened to me as well, maybe rstest/tokio/rust-analyzer bug?
</blockquote></details>

It also happened to Yael... maybe a bug

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/62#-:-NxMgWcUEn0Dx0Cnta_9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/62#-NxM4Au-6mSy_neI_II_:-NxMfsjcDMu3H0Yo9RB3:b-9lup1c) ([raw file](https://github.com/starkware-libs/mempool/blob/612e38ea75975853f8f5b0323b3c9ecc015df538/crates/gateway/src/gateway.rs#L73)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure I follow.
The async version runs this in a separate thread.
</blockquote></details>

Oh wait never mind im stupid, i didn't notice that async_add_tx calls add_tx

**Pull request merged**
