### PR TITLE
fix: rpc_state_reader return default for nonce and class_hash

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
bugfix or rpc_state_reader, need to return 0 in case that address was not found for nonce and class_hash
This is consistent with the PapyrusStateReader implemented by the blockifier.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284#-:-O0EbAgl1fnmjruezg-D:b-xbxoze)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

**Review by Yael-Starkware — COMMENTED** [review]
*of

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284#-:-O0EbULP6s7Clc-FS9OJ:bb6e14e)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/rpc_state_reader.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0EclI18u75aogY5gJk:-O0EclI18u75aogY5gJl:b3kre) ([raw file](https://github.com/starkware-libs/mempool/blob/a6f3edad7f643ecefaab200c36922605f552210e/crates/gateway/src/rpc_state_reader.rs#L167)):*
> ```XML
>             Err(StateError::StateReadError(msg)) if msg.contains("Contract address not found") => {
>                 Ok(ClassHash::default())
>             }
> ```

?



_Suggestion:_
```XML
            Err(StateError::StateReadError(msg)) if msg.contains("Class hash not found") => {
                Ok(ClassHash::default())
            }
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0EclI18u75aogY5gJk:-O0IYQmxB2wSQKKhkn9I:b-rkxt2v) ([raw file](https://github.com/starkware-libs/mempool/blob/a6f3edad7f643ecefaab200c36922605f552210e/crates/gateway/src/rpc_state_reader.rs#L167)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

?
</blockquote></details>

The error is contract_address not found, see the spec
https://github.com/starkware-libs/starknet-specs/blob/304b952121dafe47c013ed2c4c39bef4cf4c2823/api/starknet_api_openrpc.json#L479C57-L479C67

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284#-:-O0Idvoi7LunKq5UGQl8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0EclI18u75aogY5gJk:-O0IdkvT5ug-8RbJw--c:b514lf3) ([raw file](https://github.com/starkware-libs/mempool/blob/a6f3edad7f643ecefaab200c36922605f552210e/crates/gateway/src/rpc_state_reader.rs#L167)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The error is contract_address not found, see the spec
https://github.com/starkware-libs/starknet-specs/blob/304b952121dafe47c013ed2c4c39bef4cf4c2823/api/starknet_api_openrpc.json#L479C57-L479C67
</blockquote></details>

Right. The address has no corresponding Class hash. Exactly as in the previous case.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0Nn7-a2eNIfpolGvhn:-O0Nn7-bDVD_HVvF_19e:b-ig4qqg) ([raw file](https://github.com/starkware-libs/mempool/blob/24eae73452a51da4c36757b14eaea4f2f9c28d86/crates/gateway/src/errors.rs#L137)):*
> ```XML
>             }
>             _ => StateError::StateReadError(err.to_string()),
>         }
> ```

At some point, do we want to make this `from` more comprehensive? Is it possible?

If so - please add a todo/ do it.



_Code quote:_
```XML
        match err {
            RPCStateReaderError::ClassHashNotFound(request) => {
                match serde_json::from_value(request["params"]["class_hash"].clone()) {
                    Ok(class_hash) => StateError::UndeclaredClassHash(class_hash),
                    Err(e) => serde_err_to_state_err(e),
                }
            }
            _ => StateError::StateReadError(err.to_string()),
        }
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0NmHS-6bsFaYSSBGD2:-O0NmHS-6bsFaYSSBGD3:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/24eae73452a51da4c36757b14eaea4f2f9c28d86/crates/gateway/src/rpc_state_reader.rs#L80)):*
> ```XML
> 
> impl MempoolStateReader for RpcStateReader {
>     fn get_block_info(&self) -> Result<BlockInfo, StateError> {
> ```





_Suggestion:_
```XML
StateResult<BlockInfo>
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/errors.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0Nn7-a2eNIfpolGvhn:-O0NpOqfAtsF4iu3E9Ec:b3ch5w4) ([raw file](https://github.com/starkware-libs/mempool/blob/24eae73452a51da4c36757b14eaea4f2f9c28d86/crates/gateway/src/errors.rs#L137)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

At some point, do we want to make this `from` more comprehensive? Is it possible?

If so - please add a todo/ do it.
</blockquote></details>

I don't see any reason to do that atm, The only error that can be mapped to StateError is the one I handled.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/mempool/284#-O0NmHS-6bsFaYSSBGD2:-O0NpfH2CzYN-yu2GlgB:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/24eae73452a51da4c36757b14eaea4f2f9c28d86/crates/gateway/src/rpc_state_reader.rs#L80)):*
> ```XML
> 
> impl MempoolStateReader for RpcStateReader {
>     fn get_block_info(&self) -> Result<BlockInfo, StateError> {
> ```

done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284#-:-O0NyVVg6_A_vyKv1ByX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/284)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
