### PR TITLE
fix: minor changes in priority queue

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nwj06J753lwuq22My4d:-Nwj06J753lwuq22My4e:b-fbq90b) ([raw file](https://github.com/starkware-libs/mempool/blob/247b036d0b85657dbb54a277ee2fed14ac5bd7bf/crates/mempool/src/priority_queue.rs#L40)):*
> ```XML
> pub struct PQTransaction(pub InternalTransaction);
> 
> impl PQTransaction {
> ```

In #47 @elintul suggested calling this struct `PrioritisedTransaction`
how's `QueuedTransaction`?
___
*[`crates/mempool/src/priority_queue.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nwj01tTEPy34Z3YaD1o:-Nwj01tTEPy34Z3YaD1p:bnstsrz) ([raw file](https://github.com/starkware-libs/mempool/blob/247b036d0b85657dbb54a277ee2fed14ac5bd7bf/crates/mempool/src/priority_queue.rs#L41)):*
> ```XML
> 
> impl PQTransaction {
>     // TODO(Ayelet): Move to SN API and delete.
> ```

here:
https://reviewable.io/reviews/starkware-libs/starknet-api/239

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`Cargo.toml` line 35 at r2](https://reviewable.io/reviews/starkware-libs/mempool/78#-NwjS83RE-qakKCVQdio:-NwjS83RE-qakKCVQdip:b-oufemp) ([raw file](https://github.com/starkware-libs/mempool/blob/b1fbe8bc7df4f6f63ff961945863ca1c3e61b171/Cargo.toml#L35)):*
> ```TOML
> serde_json = "1.0"
> # TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", rev = "b657844a" }
> ```

https://reviewable.io/reviews/starkware-libs/starknet-api/239

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`Cargo.toml` line 35 at r2](https://reviewable.io/reviews/starkware-libs/mempool/78#-NwjS83RE-qakKCVQdio:-NwmdRo_3L1ha6zkdO_G:b-6splny) ([raw file](https://github.com/starkware-libs/mempool/blob/b1fbe8bc7df4f6f63ff961945863ca1c3e61b171/Cargo.toml#L35)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-libs/starknet-api/239
</blockquote></details>

blocking till you merge this first.
___
*[`crates/mempool/src/priority_queue.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nwj06J753lwuq22My4d:-NwmcqNP72GYV8aNyRsd:b-olr0da) ([raw file](https://github.com/starkware-libs/mempool/blob/247b036d0b85657dbb54a277ee2fed14ac5bd7bf/crates/mempool/src/priority_queue.rs#L40)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

In #47 @elintul suggested calling this struct `PrioritisedTransaction`
how's `QueuedTransaction`?
</blockquote></details>

I would prefer to use `PrioritizedTransaction`.
I believe Queued is used for larger nonces, and currently waiting for lower transactions.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`Cargo.toml` line 35 at r2](https://reviewable.io/reviews/starkware-libs/mempool/78#-NwjS83RE-qakKCVQdio:-Nwnjir65dGX9i2MzEKU:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b1fbe8bc7df4f6f63ff961945863ca1c3e61b171/Cargo.toml#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

blocking till you merge this first.
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78#-:-NwtL1AM9PMk7kr7L_-b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/mempool/78#-NwtKVYl9XodE9C2qk1a:-NwtKVYmEpyAkTlbPyCT:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/eef3ee46a079b74388059d9c7fc429b99d150ebc/crates/mempool/src/priority_queue.rs#L39)):*
> ```XML
> // Compare transactions based on their tip, which is a uint, using the Eq trait. This is because
> // uint types allow for precise and straightforward equality comparisons, ensuring that two tips
> // are either exactly equal or not.
> ```





_Suggestion:_
```XML
/// Compare transactions based only on their tip, a uint, using the Eq trait. It ensures that two tips
/// are either exactly equal or not.
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/mempool/78#-NynyrZyDrkXK3_4fqwP:-NynyrZyDrkXK3_4fqwQ:b-l6mwxj) ([raw file](https://github.com/starkware-libs/mempool/blob/f540ca5dfe8b55c971256834b37bd0d304ce5468/crates/mempool/src/mempool.rs#L15)):*
> ```XML
> use tokio::select;
> 
> use crate::priority_queue::{self, TransactionPriorityQueue};
> ```

remove



_Code quote:_
```XML
self
```
___
*[`crates/mempool/src/mempool.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nyo23Z35jGbf4AOuRGn:-Nyo23Z35jGbf4AOuRGo:bxqo761) ([raw file](https://github.com/starkware-libs/mempool/blob/f540ca5dfe8b55c971256834b37bd0d304ce5468/crates/mempool/src/mempool.rs#L51)):*
> ```XML
>                 // Attempts to insert a key-value pair into the mempool's state. Returns `None` if
>                 // the key was not present, otherwise returns the old value while
>                 // updating the new value.
> ```

Note that this text appears twice.



_Code quote:_
```XML
                // Attempts to insert a key-value pair into the mempool's state. Returns `None` if
                // the key was not present, otherwise returns the old value while
                // updating the new value.
```
___
*[`crates/mempool/src/mempool.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nyo2BAD4WAbTD8XzQhn:-Nyo2BAD4WAbTD8XzQho:b-9s64rz) ([raw file](https://github.com/starkware-libs/mempool/blob/f540ca5dfe8b55c971256834b37bd0d304ce5468/crates/mempool/src/mempool.rs#L63)):*
> ```XML
>             .collect();
> 
>         mempool.txs_queue = priority_queue::TransactionPriorityQueue::from(valid_txs);
> ```

Please use `TransactionPriorityQueue` instead.



_Code quote:_
```XML
priority_queue::TransactionPriorityQueue:
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nyo5Gy9872z9Q3FJntb:-Nyo5Gy9872z9Q3FJntc:b-ryurz) ([raw file](https://github.com/starkware-libs/mempool/blob/a07a316936d550507b28322cb7dcf8ddbc231eb1/crates/mempool/src/mempool.rs#L51)):*
> ```XML
>                 assert!(
>                     prev_value.is_none(),
>                     "Contract address: {:?} already exists in the mempool. Can't add {:?} to the \
> ```

(non-blocking)



_Suggestion:_
```XML
Sender
```
___
*[`crates/mempool/src/mempool.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nyo48LZBe1Dz2GkwO7H:-Nyo48LZBe1Dz2GkwO7I:b-t59y5i) ([raw file](https://github.com/starkware-libs/mempool/blob/a07a316936d550507b28322cb7dcf8ddbc231eb1/crates/mempool/src/mempool.rs#L60)):*
> ```XML
>             .collect();
> 
>         mempool.txs_queue = TransactionPriorityQueue::from(valid_txs);
> ```

Why you are update the txs in two steps?



_Code quote:_
```XML
 mempool.txs_queue = TransactionPriorityQueue::from(valid_txs);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/mempool/78#-Nyo48LZBe1Dz2GkwO7H:-NyoBI2IBGM5tKtSv2OJ:bubl44q) ([raw file](https://github.com/starkware-libs/mempool/blob/a07a316936d550507b28322cb7dcf8ddbc231eb1/crates/mempool/src/mempool.rs#L60)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why you are update the txs in two steps?
</blockquote></details>

I think it's more readable. but changed it.

**Review by MohammadNassar1 — APPROVED** [review]

**Review by MohammadNassar1 — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78#-:-Nyp42YiBdx2B7f4GzsM:bnfp4nl)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @elintul)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/78)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
