### PR TITLE
chore: move the conversion from external tx out of the stateful validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/184#-Nz2-mwdAohdtluw1gpr):*




_Suggestion:_
```
chore: move
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/mempool/184#-Nz26uhB1TU1vNz9DbEt:-Nz26uhB1TU1vNz9DbEu:bahcvbm) ([raw file](https://github.com/starkware-libs/mempool/blob/3f8f35691fc8f35f776c86c2722ac081efaadb3a/crates/gateway/src/gateway.rs#L126)):*
> ```XML
>         &tx,
>         None,
>         &stateful_transaction_validator.config.chain_info.chain_id,
> ```

This is ugly - I am working on fixing it.

It is odd that the config of the stateful validator is used outside of the stateful validator.



_Code quote:_
```XML
        &stateful_transaction_validator.config.chain_info.chain_id,
```

**Comment by ArniStarkware** [comment]
* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/mempool/184#-Nz26uhB1TU1vNz9DbEt:-Nz2ge1l4dFk6_KqqifF:beq8eyo) ([raw file](https://github.com/starkware-libs/mempool/blob/3f8f35691fc8f35f776c86c2722ac081efaadb3a/crates/gateway/src/gateway.rs#L126)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is ugly - I am working on fixing it.

It is odd that the config of the stateful validator is used outside of the stateful validator.
</blockquote></details>

See #188

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/gateway.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/mempool/184#-Nz26uhB1TU1vNz9DbEt:-Nz77wnx1-PXAZH9L3XH:b-7tdf7d) ([raw file](https://github.com/starkware-libs/mempool/blob/3f8f35691fc8f35f776c86c2722ac081efaadb3a/crates/gateway/src/gateway.rs#L126)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See #188
</blockquote></details>

agree

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/184#-:-Nz78gN-CazemtqnJi53:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
Postponed for now.

**Pull request closed without merging**
