### PR TITLE
docs: add documentation for component client

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #222
- #220 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)

### CODE REVIEW

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/220#-O2PLlLT6sXApCyH-fRE:-O2PLlLT6sXApCyH-fRF:balx1fz) ([raw file](https://github.com/starkware-libs/mempool/blob/66593088741366c9700eb8d8745cf37fdc4f362f/crates/mempool_infra/src/component_client.rs#L61)):*
> ```XML
> ///
> ///     // Send the request; typically, the client should await for a response.
> ///     client.send(request);
> ```

I would add the await and assign the return value to a variable of type MyResponse for more clarity



_Suggestion:_
```XML
let _response = client.send(request).await;
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/220#-O2PLlLT6sXApCyH-fRE:-O2PQnVyD8cKlXGzwxEO:b-vf48no) ([raw file](https://github.com/starkware-libs/mempool/blob/66593088741366c9700eb8d8745cf37fdc4f362f/crates/mempool_infra/src/component_client.rs#L61)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I would add the await and assign the return value to a variable of type MyResponse for more clarity
</blockquote></details>

I thought of this, but, there's no server in this setup, so the response doesn't arrive, and the test is deadlocked.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/220#-O2PLlLT6sXApCyH-fRE:-O2PTHpY3I3zM1eqxxhH:bpgtv4u) ([raw file](https://github.com/starkware-libs/mempool/blob/66593088741366c9700eb8d8745cf37fdc4f362f/crates/mempool_infra/src/component_client.rs#L61)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I thought of this, but, there's no server in this setup, so the response doesn't arrive, and the test is deadlocked.
</blockquote></details>

Do you want the example to be run and end?

**Review by uriel-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Itay-Tsabary-Starkware)

**Review by ItayTsabary — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @Itay-Tsabary-Starkware, and @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/220#-O2PLlLT6sXApCyH-fRE:-O2TEZFjCWjeVHxTWEbu:b-c45hct) ([raw file](https://github.com/starkware-libs/mempool/blob/66593088741366c9700eb8d8745cf37fdc4f362f/crates/mempool_infra/src/component_client.rs#L61)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Do you want the example to be run and end?
</blockquote></details>

I'd like the doc test to run and complete successfully, yes. Timeout-ing a test is undesired. See the comment above.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/220)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#222](https://github.com/starkware-libs/mempool/pull/222)

**Pull request closed without merging**
