### PR TITLE
feat: add remove to account tx index

### PR DESCRIPTION
**Pull request by giladchase**
Subsequent PRs will integrate this remove into the tx_pool

commit-id:ef407f33

---

**Stack**:
- #320
- #318
- #317 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/317)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/317)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/317#-O0cLv4O8VPKPUy14IRs:-O0cLv4O8VPKPUy14IRt:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/462112ad745f75c0cd1b47799d238bcedbb53a36/crates/mempool/src/transaction_pool.rs#L96)):*
> ```XML
>         let removed = account_txs.remove(&nonce);
> 
>         if removed.is_some() && account_txs.is_empty() {
> ```





_Suggestion:_
```XML
        let removed_tx = account_txs.remove(&nonce);
        if removed_tx.is_some() && account_txs.is_empty() {
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/317)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/317#-:-O0cbSLu3nrwVo-3DKC8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/317)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
