### PR TITLE
refactor: add thin transaction and implement in mempool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103#-:-NxID5Gm5cR7qtbOycNx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxICtIi9V83PM9--0tJ:-NxICtIj6ZqPE-OcUuAp:b-ln65pj) ([raw file](https://github.com/starkware-libs/mempool/blob/bd2a037695cc0f98053dfbab3f5981aad9e74a44/crates/mempool/src/mempool_test.rs#L11)):*
> ```XML
> use starknet_mempool_types::mempool_types::ThinTransaction;
> 
> pub fn create_thin_tx_for_testing(
> ```

Can you move it to `utils`?



_Code quote:_
```XML
pub fn create_thin_tx_for_testing(
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxIGspi3X6fF0PGA4Dz:-NxIGspj0zspp8BdGZbo:b6cg4ah) ([raw file](https://github.com/starkware-libs/mempool/blob/bd2a037695cc0f98053dfbab3f5981aad9e74a44/crates/mempool/src/mempool_test.rs#L14)):*
> ```XML
>     tip: Tip,
>     tx_hash: TransactionHash,
>     sender_address: ContractAddress,
> ```

use `contract_address` instead



_Code quote:_
```XML
sender_address: ContractAddress,
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxIGyVG-LtSVjfiwa9t:-NxIGyVG-LtSVjfiwa9u:b-h840g8) ([raw file](https://github.com/starkware-libs/mempool/blob/bd2a037695cc0f98053dfbab3f5981aad9e74a44/crates/mempool_types/src/mempool_types.rs#L10)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct ThinTransaction {
>     pub contract_address: ContractAddress,
> ```

Why it's needed?
AFAIK, the GW->Mempool IF already includes the address.



_Code quote:_
```XML
pub contract_address: ContractAddress,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxIGspi3X6fF0PGA4Dz:-NxIPxZX5pJkXm9yx1U4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/bd2a037695cc0f98053dfbab3f5981aad9e74a44/crates/mempool/src/mempool_test.rs#L14)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

use `contract_address` instead
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @ayeletstarkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxIGyVG-LtSVjfiwa9t:-Nxg8GK24P-Zy1wWShEB:bkdqiju) ([raw file](https://github.com/starkware-libs/mempool/blob/bd2a037695cc0f98053dfbab3f5981aad9e74a44/crates/mempool_types/src/mempool_types.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's needed?
AFAIK, the GW->Mempool IF already includes the address.
</blockquote></details>

Added a todo

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/mempool/103#-NxgF_HS3QqNR1MZoqXL:-NxgF_HS3QqNR1MZoqXM:bv8603s) ([raw file](https://github.com/starkware-libs/mempool/blob/8bc3f73d0d2a1345743c0acc343843de015268db/crates/mempool_types/src/mempool_types.rs#L8)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct ThinTransaction {
>     // TODO(Ayelet): Consider removing this field as it is duplicated in Account.
> ```

I think you need to remove it from `Account`.
Please move the TODO.



_Code quote:_
```XML
// TODO(Ayelet): Consider removing this field as it is duplicated in Account.
```

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/103#-:-NxgQJU321ia2HC_VCFX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
