### PR TITLE
feat: add network to gateway app method

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/123)

### CODE REVIEW

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/123#-:-Nxgp35F6EM8ln70TUqE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/123#-NxgoitgCKR4vcuNsMoR:-Nxgoith4JOfBGR2GOhE:bhqtadt) ([raw file](https://github.com/starkware-libs/mempool/blob/1738915dea6a0482e1e132e7041e78f9326265ee/crates/gateway/src/gateway_test.rs#L30)):*
> ```XML
> 
>     GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway)
> }
> ```

Can this technology be used in other tests? 
(like `crates/gateway/tests/routing_test.rs`)?



_Code quote:_
```XML
#[fixture]
pub fn network_component() -> GatewayNetworkComponent {
    let (tx_gateway_to_mempool, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
    let (_, rx_mempool_to_gateway) = channel::<MempoolToGatewayMessage>(1);

    GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway)
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/123)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/123#-NxgoitgCKR4vcuNsMoR:-NxgrHBY1YfLSugyKEyR:b-qp47fk) ([raw file](https://github.com/starkware-libs/mempool/blob/1738915dea6a0482e1e132e7041e78f9326265ee/crates/gateway/src/gateway_test.rs#L30)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Can this technology be used in other tests? 
(like `crates/gateway/tests/routing_test.rs`)?
</blockquote></details>

Good idea!
Done

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/123)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/123)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Pull request merged**
