### PR TITLE
feat: add serialize for rpc_state_reader_config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/130?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#130** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/130?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#129** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/129?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#126** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#127](https://github.com/starkware-libs/mempool/pull/127) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#114](https://github.com/starkware-libs/mempool/pull/114) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-NxuloddBGaLB7PlxpED:-NxuloddBGaLB7PlxpEE:b8tf1b4) ([raw file](https://github.com/starkware-libs/mempool/blob/71c7ad0d3f2692a1f33c1f6e61510f5ada0e7f12/crates/gateway/src/config_test.rs#L39)):*
> ```XML
>         expected_config.dump_to_file(&vec![], config_file_path.to_str().unwrap()).unwrap();
>     }
> ```

can you explain what is this empty vector?



_Code quote:_
```XML
&vec![]
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-NxuoR355teeaYJYfQ60:-NxuoR367V2hBsY4KX-z:be8fwty) ([raw file](https://github.com/starkware-libs/mempool/blob/feaa5c3032df9252340bf5ef38374a58ef9a99e6/crates/gateway/src/rpc_state_reader.rs#L174)):*
> ```XML
>                 ParamPrivacyInput::Public,
>             ),
>         ])
> ```

can you explain a bit about how this config crate works? and what is happening with nested configs?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-NxuloddBGaLB7PlxpED:-Nxv36xd9SCr4ItIQBEy:b-2vs4k6) ([raw file](https://github.com/starkware-libs/mempool/blob/adc6afff094f01036bb119d9c7b782571cda5b29/crates/gateway/src/config_test.rs#L39)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you explain what is this empty vector?
</blockquote></details>

Using an empty vector for this value seems like a common practice ([See documentation](https://github.com/starkware-libs/papyrus/blob/bc8f2e54a3a4950553631d11a7b78facdb2111b7/crates/papyrus_config/src/dumping.rs#L99)).
___
*[`crates/gateway/src/rpc_state_reader.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-NxuoR355teeaYJYfQ60:-Nxv6mOU5hkHQB2L59xg:b-jqo2h3) ([raw file](https://github.com/starkware-libs/mempool/blob/c2d3711ccac51228a41e76bbd6b7eb84ab628a67/crates/gateway/src/rpc_state_reader.rs#L174)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you explain a bit about how this config crate works? and what is happening with nested configs?
</blockquote></details>

There is a slight difference between the method `dump_to_file`, which is a trait of `SerializeConfig`, and `dump`, which is an abstract trait.
The way this is set is used to create the json file (see example in this PR - this file was created using `fix_test_valid_rpc_state_reader_config`). 

About nested configs:
[The dump method with sub-configs](https://github.com/starkware-libs/mempool/blob/52595b84f938b03b8de574530f044299c8aaad9f/crates/mempool_node/src/config/mod.rs#L87)
[The result config file](https://github.com/starkware-libs/mempool/blob/4921945413813d0491d8cfcca54a9c0ebb62ad61/crates/mempool_node/src/test_files/mempool_node_config.json#L2)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-Nxvm33Q0UAz0UFaruPE:-Nxvm33Q0UAz0UFaruPF:bffqq1i) ([raw file](https://github.com/starkware-libs/mempool/blob/c2d3711ccac51228a41e76bbd6b7eb84ab628a67/crates/gateway/src/config_test.rs#L112)):*
> ```XML
> #[test]
> #[ignore]
> /// Read the rpc state reader config file and validate its content.
> ```

/// Fix the....
/// Run with 'cargo test -- --ignored'.



_Code quote:_
```XML
// Read the rpc state reader config file and validate its content.
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/config_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/130#-Nxvm33Q0UAz0UFaruPE:-NxwHMQYC9PMjFJ7Hnv_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e313d7626fcabf6f8364d33bfb2f3ed9c10a714e/crates/gateway/src/config_test.rs#L112)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

/// Fix the....
/// Run with 'cargo test -- --ignored'.
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130#-:-Ny05rBM-fqj-tVSmaag:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArniStarkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
