### PR TITLE
feat(mempool): add from_iter func to TransactionQueue

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/413)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/413)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/mempool/413#-O1QdElp9m3kZgaCi46J:-O1QdElp9m3kZgaCi46K:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/068f596649860458402e41e2e95e179945db0eb3/crates/mempool/src/mempool_test.rs#L33)):*
> ```XML
>         for tx in txs {
>             queue.insert(TransactionReference::new(&tx));
>         }
> ```





_Suggestion:_
```XML
        txs.iter().for_each(|tx| queue.insert(TransactionReference::new(tx)));
```

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/413)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/mempool/413#-O1QgEflEmDkmCj3O66e:-O1QgEflEmDkmCj3O66f:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/068f596649860458402e41e2e95e179945db0eb3/crates/mempool/src/mempool_test.rs#L30)):*
> ```XML
> impl FromIterator<ThinTransaction> for TransactionQueue {
>     fn from_iter<T: IntoIterator<Item = ThinTransaction>>(txs: T) -> TransactionQueue {
>         let mut queue = TransactionQueue::default();
> ```





_Suggestion:_
```XML
Self
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/413)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/mempool/413#-O1R2MVB7MK-eY3qdlL_:-O1R2MVB7MK-eY3qdlLa:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/068f596649860458402e41e2e95e179945db0eb3/crates/mempool/src/mempool_test.rs#L28)):*
> ```XML
> 
> // TODO(Ayelet): Consider using an iterator of references to ThinTransaction to avoid cloning.
> impl FromIterator<ThinTransaction> for TransactionQueue {
> ```





_Suggestion:_
```XML
TransactionReference
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/413#-:-O1RIsON1DJQ8U4hX_D6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
