### PR TITLE
test: make the stateless tx validator a more correct unit test

### PR DESCRIPTION
**Pull request by ArniStarkware**
The previous way the test was organized was a bad design.
The "validate non-zero fee" should not be a part of every other scenario of the tests for stateless tx validator.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/232)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#232** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/232?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/232)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/232#-O-FZ1bN8CYZmxFBF-BH:-O-FZ1bN8CYZmxFBF-BI:bopfh5q) ([raw file](https://github.com/starkware-libs/mempool/blob/6c13da6b0d6555be2fb55577c4a312040bb4e081/crates/gateway/src/stateless_transaction_validator_test.rs#L30)):*
> ```XML
>     StatelessTransactionValidatorConfig{
>         validate_non_zero_l1_gas_fee: false,
>         validate_non_zero_l2_gas_fee: false,
> ```

I would remove all the "false" assignments,  but it is a matter of taste so you can ignore this comment.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/232)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/232#-O-FZ1bN8CYZmxFBF-BH:-O-FbDmU6kJXjQM_jIIA:bvih1mz) ([raw file](https://github.com/starkware-libs/mempool/blob/6c13da6b0d6555be2fb55577c4a312040bb4e081/crates/gateway/src/stateless_transaction_validator_test.rs#L30)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I would remove all the "false" assignments,  but it is a matter of taste so you can ignore this comment.
</blockquote></details>

I like the fact it is explicit here.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
