### PR TITLE
refactor(mempool): change address-to-tx value type to TransactionReference

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/410#-O1LwKj55ddGxVf6mKJJ:-O1LwKj55ddGxVf6mKJK:b-4ctigd) (no related file):*
To implement the `commit_block` method and efficiently remove transactions from the `transaction_queue`, I updated the mapping from `account_to_nonce` to `account_to_tx`. This change allows transactions to be removed in O(1) time complexity.

This PR only changes the `HashMap` value to `QueuedTransaction`.

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/410#-O1LwKj55ddGxVf6mKJJ:-O1MiZagEUdugq8cmi0L:bbwxvx3) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

To implement the `commit_block` method and efficiently remove transactions from the `transaction_queue`, I updated the mapping from `account_to_nonce` to `account_to_tx`. This change allows transactions to be removed in O(1) time complexity.

This PR only changes the `HashMap` value to `QueuedTransaction`.
</blockquote></details>

Refresh commit message?

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/410#-O1LwKj55ddGxVf6mKJJ:-O1MoX8oBoxW18GfrrOL:bb7f2mf) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Refresh commit message?
</blockquote></details>

done

___

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410#-:-O1O82Tp7RhLdGPjqw9D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/mempool/410#-O1O7ykV1ZEJE5sBDZRk:-O1O7ykV1ZEJE5sBDZRl:bs8dhuq) ([raw file](https://github.com/starkware-libs/mempool/blob/4fd12e9199aab055aa21892e8432dfd1d32a190d/crates/mempool/src/transaction_queue.rs#L48)):*
> ```XML
>     }
> 
>     pub fn _get_nonce(&self, address: &ContractAddress) -> Option<&Nonce> {
> ```

nit What are our plans on starting to use this one?



_Code quote:_
```XML
 pub fn _get_nonce(&self, address: &ContractAddress) -> Option<&Nonce> {
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410#-:-O1QhagJ9x7a_Qb4jojx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/mempool/410#-O1O7ykV1ZEJE5sBDZRk:-O1QlvjkCtw3r64N7d3q:bvzwbh9) ([raw file](https://github.com/starkware-libs/mempool/blob/4fd12e9199aab055aa21892e8432dfd1d32a190d/crates/mempool/src/transaction_queue.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nit What are our plans on starting to use this one?
</blockquote></details>

I used it in the next PR:
https://reviewable.io/reviews/starkware-libs/mempool/420

**Pull request merged**
