### PR TITLE
feat: changing component runner and adding tests

### PR DESCRIPTION
**Pull request by lev-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/99)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/99)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @lev-starkware and @uriel-starkware)

___
*[`Cargo.lock` line 2002 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC7SkH3I5ZJoylOK31:-NxC7SkH3I5ZJoylOK32:beuxkuv) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/Cargo.lock#L2002)):*
> ```TOML
>  "thiserror",
>  "tokio",
>  "validator",
> ```

What leads to this dependency?
___
*[`Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC1a7E-v01kJgBXon9:-NxC1a7FAnxXlFw8mJWS:b-yrvoer) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/Cargo.toml#L22)):*
> ```TOML
> 
> [workspace.dependencies]
> anyhow = "1.0.44"
> ```

Still needed?
___
*[`crates/mempool_infra/src/component_runner.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8Rj_CmtL28MtimQN:-NxC8Rj_CmtL28MtimQO:b20f28m) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner.rs#L15)):*
> ```XML
> /// Interface to start memepool components.
> #[async_trait]
> pub trait ComponentRunner<T: SerializeConfig + Sync + Send> {
> ```

After potentially removing the `clone`s (see below), are these required?



_Code quote:_
```XML
 + Sync + Send>
```
___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC55teBNsZrU-sal8o:-NxC55teBNsZrU-sal8p:b-ujwuzw) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner.rs#L18)):*
> ```XML
>     /// Start the component. Normally this function should never return.
>     async fn start(config: T) -> Result<(), ComponentStartError>;
> }
> ```

Please separate this trait into two:
1. `ComponentRunner` with `async fn start() ->  Result<(), ComponentStartError>;`
2. `ComponentCreator` with `fn new<T: SerializeConfig>(config: T) ->  Self;`



_Code quote:_
```XML
#[async_trait]
pub trait ComponentRunner<T: SerializeConfig + Sync + Send> {
    /// Start the component. Normally this function should never return.
    async fn start(config: T) -> Result<(), ComponentStartError>;
}
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC5qAN7m_UuIVXt6Tz:-NxC5qAN7m_UuIVXt6U-:bf8b7o3) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L12)):*
> ```XML
> use papyrus_config::{ParamPath, SerializedParam};
> 
> mod test_component1 {
> ```

AFAIK the naming convention for arbitrary values is a,b,c and not 1,2,3, please change (modules, configs, components).



_Code quote:_
```XML
test_component1 
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC6bF820iJJq9j69Ba:-NxC6bF94sHASPssY-uq:b-dmyaj7) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L17)):*
> ```XML
>     #[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
>     pub struct TestConfig1 {
>         pub config1: bool,
> ```

Please rename `config1` to `field` or `config_field`.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8sO5-gprCtC8zxLi:-NxC8sO5-gprCtC8zxLj:bnjgyrs) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L41)):*
> ```XML
>         }
>         async fn local_start(&self) -> Result<(), tokio::io::Error> {
>             println!("TestComponent1::local_start(), config: {:#?}", self.config);
> ```

Print required?
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC7eva2MxCXWzl9dz9:-NxC7eva2MxCXWzl9dzA:b-hlpto3) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L50)):*
> ```XML
>         async fn start(config: TestConfig1) -> Result<(), ComponentStartError> {
>             let component = TestComponent1::new(config);
>             println!("TestComponent1::start(), component: {:#?}", component);
> ```

Is the print required?
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC6vcr6dCQszQV2Orw:-NxC6vcr6dCQszQV2Orx:bo5e9e4) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L64)):*
> ```XML
>     #[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
>     pub struct TestConfig2 {
>         pub config2: u32,
> ```

Please rename `config2` to `field` or `config_field`.



_Code quote:_
```XML
pub config2: u32,
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8Mur7-HRP9RzTWHs:-NxC8Mur7-HRP9RzTWHt:bwaf9oy) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L87)):*
> ```XML
>         async fn start(config: TestConfig2) -> Result<(), ComponentStartError> {
>             let component = TestComponent2 {
>                 config: config.clone(),
> ```

Is this `clone` required?



_Code quote:_
```XML
.clone()
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8q7cAH5mnBarpWuK:-NxC8q7cAH5mnBarpWuL:bnjgyrs) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L89)):*
> ```XML
>                 config: config.clone(),
>             };
>             println!("TestComponent2::start(): component: {:#?}", component);
> ```

Print required?



_Code quote:_
```XML
println!("TestComponent2::start(): component: {:#?}", component);
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8huU5KJQzCODWkBp:-NxC8huU5KJQzCODWkBq:b3eoucd) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L96)):*
> ```XML
>             } else {
>                 Ok(())
>             }
> ```

Please use `match`.



_Code quote:_
```XML
            if config.config2 == 43 {
                Err(ComponentStartError::InternalComponentError)
            } else if config.config2 == 44 {
                Err(ComponentStartError::ComponentConfigError)
            } else {
                Ok(())
            }
```
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC79VRDm6WPDcnAdx2:-NxC79VS29g1YPXPU2dr:bwaf9oy) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L106)):*
> ```XML
> async fn test_testruner1() {
>     let test_config = TestConfig1 { config1: true };
>     assert_matches!(TestComponent1::start(test_config.clone()).await, Ok(()));
> ```

Is this `clone` required?



_Code quote:_
```XML
.clone()
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/99)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @lev-starkware and @uriel-starkware)

___
*[`Cargo.lock` line 2002 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC7SkH3I5ZJoylOK31:-NxC9T3M1CVA904N9SEl:bkkjdt5) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/Cargo.lock#L2002)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What leads to this dependency?
</blockquote></details>

(the validator)

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/99)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @uriel-starkware)

___
*[`Cargo.lock` line 2002 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC7SkH3I5ZJoylOK31:-NxCUOHj-9jh_buN2kfL:bybojvj) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/Cargo.lock#L2002)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

(the validator)
</blockquote></details>

Done. Deleted from mempool_infra/Cargo.toml.
___
*[`Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC1a7E-v01kJgBXon9:-NxCUWjU1O0u-gosrhEW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/Cargo.toml#L22)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Still needed?
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_runner.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8Rj_CmtL28MtimQN:-NxCgK3H6brqQ46AqWmi:b-wnfmk9) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

After potentially removing the `clone`s (see below), are these required?
</blockquote></details>

Done. Removed.
___
*[`crates/mempool_infra/src/component_runner.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC55teBNsZrU-sal8o:-NxDDyzn2i9HVApBG_ZT:b2sccp4) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please separate this trait into two:
1. `ComponentRunner` with `async fn start() ->  Result<(), ComponentStartError>;`
2. `ComponentCreator` with `fn new<T: SerializeConfig>(config: T) ->  Self;`
</blockquote></details>

Done. But instead of "new" - "create".
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC5qAN7m_UuIVXt6Tz:-NxCTwzi8zDaQ1Ec4svY:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L12)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

AFAIK the naming convention for arbitrary values is a,b,c and not 1,2,3, please change (modules, configs, components).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC6bF820iJJq9j69Ba:-NxCX3Vd0tHr6h18GOPW:bb11e7r) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L17)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename `config1` to `field` or `config_field`.
</blockquote></details>

Done. Renamed to bool_field.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8sO5-gprCtC8zxLi:-NxCXDza0P6rytA0hZMD:bnaw497) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Print required?
</blockquote></details>

It's a debug print. I used it to check things when debugging. It is printed only in case of test is failing. 
I can remove it if you really hate it.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC7eva2MxCXWzl9dz9:-NxCZ4Yx46l0it-WWVtZ:b3y7hqd) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L50)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is the print required?
</blockquote></details>

See previous.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC6vcr6dCQszQV2Orw:-NxCYiJT3zsLSN4Ki-lg:b1v0gs1) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L64)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename `config2` to `field` or `config_field`.
</blockquote></details>

Done. Renamed to u32_field.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8Mur7-HRP9RzTWHs:-NxCYu59-L_U3WE-LHU-:bb51cu2) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this `clone` required?
</blockquote></details>

Was required, but after changing trates not anymore.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8q7cAH5mnBarpWuK:-NxCZ8E54WGTcdvC5Tbu:b3y7hqd) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L89)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Print required?
</blockquote></details>

See previous.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC8huU5KJQzCODWkBp:-NxCZIW326GKqi_mzIGK:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use `match`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_runner_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/mempool/99#-NxC79VRDm6WPDcnAdx2:-NxCb4T848ihTV8BJKCp:b-wnfmk9) ([raw file](https://github.com/starkware-libs/mempool/blob/d9afc65a1a12f5720996aed277e62cfcb1a9e44d/crates/mempool_infra/src/component_runner_test.rs#L106)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this `clone` required?
</blockquote></details>

Done. Removed.

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/99)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
