### PR TITLE
chore: use sn-api feature branch

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8ApfQ5TzYl7aL5ia3:-Nz8ApfQ5TzYl7aL5ia4:b-mmyx7s) (no related file):*
can you add an explanation of what changed in the sn API branch?

___

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8ApfQ5TzYl7aL5ia3:-Nz8B-Oe98ObQF9SLQlk:b-pucudd) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

can you add an explanation of what changed in the sn API branch?
</blockquote></details>

or add the relevant PR

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8ApfQ5TzYl7aL5ia3:-Nz8Glm19xlx5VJCnvY7:b5g18hd) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

or add the relevant PR
</blockquote></details>

I have changed the `ExternalTransaction` to RPC transaction.
SN_API PR:
https://github.com/starkware-libs/starknet-api/pull/236

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/errors.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8PtWY6wjd3JpAqY2S:-Nz8PtWY6wjd3JpAqY2T:b-99gc96) ([raw file](https://github.com/starkware-libs/mempool/blob/41cf4a79879df22ddd1dc45c477b3ca63e99179b/crates/gateway/src/errors.rs#L37)):*
> ```XML
> pub enum StatelessTransactionValidatorError {
>     #[error("Expected a positive amount of {resource:?}. Got {resource_bounds:?}.")]
>     ZeroResourceBounds { resource: Resource, resource_bounds: ResourceBounds },
> ```

What's the origin of this change?
___
*[`crates/gateway/src/utils.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8QB116gTvRIk7-BMI:-Nz8QB1270qA5Z2Q3c6l:brcyh6) ([raw file](https://github.com/starkware-libs/mempool/blob/9e10509349ae4c179f7ac28fda31a7508e0fa88b/crates/gateway/src/utils.rs#L61)):*
> ```XML
> }
> 
> fn from(mapping: ResourceBoundsMapping) -> starknet_api::transaction::ResourceBoundsMapping {
> ```

`impl From`?
Or alternatively, comply with the type change.



_Code quote:_
```XML
from
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/errors.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8PtWY6wjd3JpAqY2S:-Nz92rbG3rhjnGlADyUy:b-c56prl) ([raw file](https://github.com/starkware-libs/mempool/blob/41cf4a79879df22ddd1dc45c477b3ca63e99179b/crates/gateway/src/errors.rs#L37)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's the origin of this change?
</blockquote></details>

ResourceBound is not a BTreeMap anymore; it's a struct.
Thus, we don't have a scenario where a resource is missing.
___
*[`crates/gateway/src/utils.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8QB116gTvRIk7-BMI:-Nz95WQX5uyfowH2ar0l:b-ptzzhg) ([raw file](https://github.com/starkware-libs/mempool/blob/9e10509349ae4c179f7ac28fda31a7508e0fa88b/crates/gateway/src/utils.rs#L61)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`impl From`?
Or alternatively, comply with the type change.
</blockquote></details>

I've opened a PR that implements it:
https://github.com/starkware-libs/starknet-api/pull/264

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/gateway/src/errors.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/mempool/192#-Nz8PtWY6wjd3JpAqY2S:-NzMnlp2916ck5Uoray5:b-9ik0o9) ([raw file](https://github.com/starkware-libs/mempool/blob/41cf4a79879df22ddd1dc45c477b3ca63e99179b/crates/gateway/src/errors.rs#L37)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

ResourceBound is not a BTreeMap anymore; it's a struct.
Thus, we don't have a scenario where a resource is missing.
</blockquote></details>

Thanks! For future PRs: mention non-trivial changes in a PR comment so (1) review is quicker; (2) it documents the PR for future readers.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192#-:-NzTSDhX1YZiXYFDsoaz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/utils.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/mempool/192#-NzX0gxADOklvT55U8NI:-NzX0gxADOklvT55U8NJ:b-ilrcn8) ([raw file](https://github.com/starkware-libs/mempool/blob/4f869a0e8b7c0ded2177f94aa36577a54af4075c/crates/gateway/src/utils.rs#L132)):*
> ```XML
>         ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => {
>             let invoke_tx = InvokeTransaction::V3(InvokeTransactionV3 {
>                 resource_bounds: from(tx.resource_bounds.clone()),
> ```

Is this clone necessary? 



_Code quote:_
```XML
.clone()
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/mempool/192#-NzX0gxADOklvT55U8NI:-NzX9QwK-hfasHLha91B:b-etd2y2) ([raw file](https://github.com/starkware-libs/mempool/blob/4f869a0e8b7c0ded2177f94aa36577a54af4075c/crates/gateway/src/utils.rs#L132)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this clone necessary?
</blockquote></details>

Yes, since it doesn't implement `Copy`.
Note that resource_bounds is a small struct, so there is no problem with cloning it.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192#-:-NzXAebQAtroJ2CmYkfj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192#-:-NzXBI8U-21cMpEDlhOc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
