### PR TITLE
chore: upgrade papyrus commit to ca83fd42 and blockifier to 0.8.0-dev.1

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/tests-integration/src/state_reader.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7QNCEqCWnnZ-Ck6v:-O1G7QNCEqCWnnZ-Ck6w:byjn2lp) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/tests-integration/src/state_reader.rs#L61)):*
> ```XML
>     let account_contract_cairo1 = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
>     let test_contract_cairo1 = FeatureContract::TestContract(CairoVersion::Cairo1);
>     let erc20_cairo1 = FeatureContract::ERC20(CairoVersion::Cairo1);
> ```

@ArniStarkware/@Yael-Starkware , can you please approve the change I made in this file?



_Code quote:_
```XML
let erc20_cairo1 = FeatureContract::ERC20(CairoVersion::Cairo1);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7iAOEFyNLR-2VlVi:-O1G7iAOEFyNLR-2VlVj:bxw4dl5) (no related file):*
I have bumped both Papyrus and Blockifier versions.
Blockifier: `0.8.0-dev.1`.
Papyrus: `ca83fd42`.

The main changes in Mempool are related to the Blockifier code.

___

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GA04DDfSJJLqR_CA0:-O1GA04E6ykiELiI7tvz:b-rbzs51) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/gateway/src/stateful_transaction_validator_test.rs#L61)):*
> ```XML
>                     max_amount: VALID_L1_GAS_MAX_AMOUNT,
>                     max_price: VALID_L1_GAS_MAX_PRICE_PER_UNIT,
>                     balance: num_bigint::BigUint::default(),
> ```

This is zero - right?
Please make it explicitly zero.



_Code quote:_
```XML
balance: num_bigint::BigUint::default(),
```
___
*[`crates/tests-integration/src/state_reader.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7QNCEqCWnnZ-Ck6v:-O1G9dYn7PJLuMFMZyka:bg7igkv) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/tests-integration/src/state_reader.rs#L61)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@ArniStarkware/@Yael-Starkware , can you please approve the change I made in this file?
</blockquote></details>

:lgtm:

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7iAOEFyNLR-2VlVi:-O1G9fpuACNF5d9DXCyq:b-yv1uzr) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I have bumped both Papyrus and Blockifier versions.
Blockifier: `0.8.0-dev.1`.
Papyrus: `ca83fd42`.

The main changes in Mempool are related to the Blockifier code.
</blockquote></details>

Please change the commit message to also include the Blockifier bump (so it's clear in `git tree`).

___
___
*[`crates/gateway/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G9sJ-9J15oOQt_bFV:-O1G9sJ03gmleZ7QKHrU:bxa59vp) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/gateway/Cargo.toml#L21)):*
> ```TOML
> cairo-vm.workspace = true
> hyper.workspace = true
> num-bigint.workspace = true
> ```

If only used in tests, please move to `[dev-dependencies]` section.



_Code quote:_
```TOML
num-bigint.workspace = true
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G9zR2BLSl-hTo53gN:-O1G9zR2BLSl-hTo53gO:b-s4cuk) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/gateway/src/stateful_transaction_validator_test.rs#L61)):*
> ```XML
>                     max_amount: VALID_L1_GAS_MAX_AMOUNT,
>                     max_price: VALID_L1_GAS_MAX_PRICE_PER_UNIT,
>                     balance: num_bigint::BigUint::default(),
> ```

I think the convention is not to use the fuily-qualified name; please make sure?



_Code quote:_
```XML
num_bigint::BigUint
```
___
*[`crates/tests-integration/src/state_reader.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GAGGb8Gyi1vVaaMHc:-O1GAGGb8Gyi1vVaaMHd:bmzoyeb) ([raw file](https://github.com/starkware-libs/mempool/blob/2c7b230bbe57fd3e7fc4f96d928fd52b75303cdf/crates/tests-integration/src/state_reader.rs#L220)):*
> ```XML
>         | FeatureContract::FaultyAccount(version)
>         | FeatureContract::TestContract(version) => *version,
>         FeatureContract::ERC20 => CairoVersion::Cairo0,
> ```

Looks like the ERC20 was Cairo 0 until now? What's the version we have in the repo.?



_Code quote:_
```XML
FeatureContract::ERC20 => CairoVersion::Cairo0
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/tests-integration/src/state_reader.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GAGGb8Gyi1vVaaMHc:-O1GAhef-UqdkMYokZpK:b-yzznos) ([raw file](https://github.com/starkware-libs/mempool/blob/2c7b230bbe57fd3e7fc4f96d928fd52b75303cdf/crates/tests-integration/src/state_reader.rs#L220)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Looks like the ERC20 was Cairo 0 until now? What's the version we have in the repo.?
</blockquote></details>

It was, but:
1. this specific function is correct (`fn cairo_version(contract: &FeatureContract)`).
2. The logic indeed changed in this PR - it made it so `prepare_state_diff` used to use `FeatureContract::ERC20(CairoVersion::Cairo0)` and now uses: `FeatureContract::ERC20(CairoVersion::Cairo1)`.

This is fine from the test's perspective.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/src/state_reader.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GBS-y-TkEkED9PV_F:-O1GBS-y-TkEkED9PV_G:b-y4ywil) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/tests-integration/src/state_reader.rs#L104)):*
> ```XML
>     fund_accounts: Vec<ContractAddress>,
> ) -> ThinStateDiff {
>     let erc20 = FeatureContract::ERC20(CairoVersion::Cairo1);
> ```

This changes the logic of the test (Used to use the `Cairo0` contract).
This is fine by us. 



_Code quote:_
```XML
let erc20 = FeatureContract::ERC20(CairoVersion::Cairo1);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7iAOEFyNLR-2VlVi:-O1GHrYZB_vM3jNUUlyO:bb6un1j) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please change the commit message to also include the Blockifier bump (so it's clear in `git tree`).
</blockquote></details>

Done

___
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GA04DDfSJJLqR_CA0:-O1GBMNI9TNIAjMiChGD:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/gateway/src/stateful_transaction_validator_test.rs#L61)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is zero - right?
Please make it explicitly zero.
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/state_reader.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1G7QNCEqCWnnZ-Ck6v:-O1GHzCm4yRQZWFVLTBc:b-ucfknh) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/tests-integration/src/state_reader.rs#L61)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

:lgtm:
</blockquote></details>

Thanks!
___
*[`crates/tests-integration/src/state_reader.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GBS-y-TkEkED9PV_F:-O1GHdT_7g3Q2NpQt6Bv:b-ufjcef) ([raw file](https://github.com/starkware-libs/mempool/blob/93e467fff773f8a53fbb345016760609b1bca76a/crates/tests-integration/src/state_reader.rs#L104)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How would it work?
</blockquote></details>

Changed back to `Cairo0`.
___
*[`crates/tests-integration/src/state_reader.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GAGGb8Gyi1vVaaMHc:-O1GHmUY7tEphF7xEJml:b-ufjcef) ([raw file](https://github.com/starkware-libs/mempool/blob/2c7b230bbe57fd3e7fc4f96d928fd52b75303cdf/crates/tests-integration/src/state_reader.rs#L220)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we need it? Doesn't it exist in Blockifier?
</blockquote></details>

Changed back to `Cairo0`.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/src/state_reader.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GI-439wki1vqqwIci:-O1GI-439wki1vqqwIcj:b-ww7xxp) ([raw file](https://github.com/starkware-libs/mempool/blob/771179953a860945824f69cdf1212c873568e6dd/crates/tests-integration/src/state_reader.rs#L212)):*
> ```XML
> }
> 
> // TODO (Yael 19/6/2024): make this function public in Blockifier and remove it from here.
> ```

As discussed - this function can be deleted (This PR allows it).



_Code quote:_
```XML
// TODO (Yael 19/6/2024): make this function public in Blockifier and remove it from here.
```

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, @giladchase, and @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/tests-integration/src/state_reader.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GIa8R1W36-8R6-fC2:-O1GIa8R1W36-8R6-fC3:b-ww7xxp) ([raw file](https://github.com/starkware-libs/mempool/blob/771179953a860945824f69cdf1212c873568e6dd/crates/tests-integration/src/state_reader.rs#L212)):*
> ```XML
> }
> 
> // TODO (Yael 19/6/2024): make this function public in Blockifier and remove it from here.
> ```

As discussed - this function can be deleted (This PR allows it).



_Code quote:_
```XML
// TODO (Yael 19/6/2024): make this function public in Blockifier and remove it from here.
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393#-:-O1GJ6sI2dbOWqLsiVu_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/tests-integration/src/state_reader.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/mempool/393#-O1GI-439wki1vqqwIci:-O1GK4-9E_-ExVpq46Fb:b-172obd) ([raw file](https://github.com/starkware-libs/mempool/blob/771179953a860945824f69cdf1212c873568e6dd/crates/tests-integration/src/state_reader.rs#L212)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As discussed - this function can be deleted (This PR allows it).
</blockquote></details>

Correct.
@Yael-Starkware , can you delete it please?

**Pull request merged**
