### PR TITLE
refactor: make rpc reader use account map

### PR DESCRIPTION
**Pull request by giladchase**
This finishes the refactor started at #454, plz view that PR for context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/455)

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/455)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/455#-:-O1kyJPcAykEsgxBN4Ie:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/455)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/455)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
