### PR TITLE
feat: add gateway response to gateway result

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/70)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/70)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/70#-Nwn1Ol7CP7T7kxEuk3d:-Nwn1Ol84vV3OGtKR0bp:b-8zsflc) ([raw file](https://github.com/starkware-libs/mempool/blob/1ecd0108241b1bc94a286252927a725dc4d39007/crates/gateway/src/gateway.rs#L37)):*
> ```XML
> 
> impl Gateway {
>     pub async fn build_server(self) -> GatewayResult {
> ```

`build_server` shouldn't return a result that implements IntoRespone, as it is not an HTTP endpoint.



_Code quote:_
```XML
GatewayResult
```
___
*[`crates/gateway/src/gateway.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/mempool/70#-Nwn1noX--kWVZJzx8Dv:-Nwn1noX--kWVZJzx8Dw:beknaxb) ([raw file](https://github.com/starkware-libs/mempool/blob/1ecd0108241b1bc94a286252927a725dc4d39007/crates/gateway/src/gateway.rs#L65)):*
> ```XML
> }
> 
> async fn add_transaction(Json(transaction): Json<ExternalTransaction>) -> GatewayResult {
> ```

I think for now it will be enough to just return `Ok` with "success" or even an empty string, and we can remove the `GatewayResult` enum



_Code quote:_
```XML
GatewayResult
```

**Comment by ArniStarkware** [comment]
* **#71** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/71?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#70** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/70?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/70)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/mempool/70#-Nwn1Ol7CP7T7kxEuk3d:-NwnG4_I0jKn67GSaw88:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fe5623b26af7bbfac39e6b675c65f5ed9459dd69/crates/gateway/src/gateway.rs#L37)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`build_server` shouldn't return a result that implements IntoRespone, as it is not an HTTP endpoint.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/mempool/70#-Nwn1noX--kWVZJzx8Dv:-NwnHVJz8AZiaBl0FV3y:b-rx8sup) ([raw file](https://github.com/starkware-libs/mempool/blob/fe5623b26af7bbfac39e6b675c65f5ed9459dd69/crates/gateway/src/gateway.rs#L65)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think for now it will be enough to just return `Ok` with "success" or even an empty string, and we can remove the `GatewayResult` enum
</blockquote></details>

Done.
Removed the `GatewayResponse` enum. 
I keep the current return value to not mess with many tests.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/70)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/mempool/70#-NwsEvkK16NvwnfGTVZX:-NwsEvkK16NvwnfGTVZY:bgv7sm7) ([raw file](https://github.com/starkware-libs/mempool/blob/68db4f18d83bdb10b06ae2ad53639c1bf00892be/crates/gateway/src/gateway.rs#L48)):*
> ```XML
> async fn add_transaction(
>     Json(transaction): Json<ExternalTransaction>,
> ) -> GatewayResult<&'static str> {
> ```

I think that if you will return a `String` you won't need `'static` lifetime.



_Code quote:_
```XML
&'static
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/70#-:-Nwsr6P2CgwQN_EaLojM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
