### PR TITLE
feat: feat: adding main module

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #339
- #311 ⬅
- #355

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iO97cDbrAGtFky0Le:-O0iO97cDbrAGtFky0Lf:b-8dr4ko) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/gateway/src/gateway.rs#L85)):*
> ```XML
>             .with_state(self.app_state.clone())
>     }
> }
> ```

Please create a different pr solely for these changes.



_Code quote:_
```XML
    pub async fn run(&mut self) -> Result<(), GatewayRunError> {
        // Parses the bind address from GatewayConfig, returning an error for invalid addresses.
        let GatewayNetworkConfig { ip, port } = self.config.network_config;
        let addr = SocketAddr::new(ip, port);
        let app = self.app();

        // Create a server that runs forever.
        Ok(axum::Server::bind(&addr).serve(app.into_make_service()).await?)
    }

    pub fn app(&self) -> Router {
        Router::new()
            .route("/is_alive", get(is_alive))
            .route("/add_tx", post(add_tx))
            .with_state(self.app_state.clone())
    }
}
```
___
*[`crates/gateway/src/gateway.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iOQvCEKycVTvAIHbx:-O0iOQvCEKycVTvAIHby:b-g0hf15) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/gateway/src/gateway.rs#L208)):*
> ```XML
>             Ok(_) => Ok(()),
>             Err(_) => Err(ComponentStartError::InternalComponentError),
>         }
> ```

Please check out the `map_err` syntax, should be useful here.



_Code quote:_
```XML
        match self.run().await {
            Ok(_) => Ok(()),
            Err(_) => Err(ComponentStartError::InternalComponentError),
        }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/main.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iOz7X9ZhwCynWUs95:-O0iOz7X9ZhwCynWUs96:bfv5dcr) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L12)):*
> ```XML
> 
> #[tokio::main]
> async fn main() -> anyhow::Result<()> {
> ```

Why is `anyhow` required here?

ChatGPT suggested the following, does this remove the need for the `anyhow` dependency?

```
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    // Your async code here

    Ok(())
}
```



_Code quote:_
```XML
anyhow::Result<()>
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPAAV04zENyY79NcW:-O0iPAAV04zENyY79NcX:b-z5itpq) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L14)):*
> ```XML
> async fn main() -> anyhow::Result<()> {
>     let config = MempoolNodeConfig::load_and_process(args().collect());
>     if let Err(ConfigError::CommandInput(clap_err)) = config {
> ```

What does this stand for?



_Code quote:_
```XML
clap_err
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPGH111597Dfm7EVs:-O0iPGH111597Dfm7EVt:bwi8dz4) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L21)):*
> ```XML
>     if let Err(error) = config_validate(&config) {
>         println!("Error: {}", error);
>         exit(1);
> ```

Where does this error code originates from? Or was it an arbitrary choice?



_Code quote:_
```XML
exit(1);
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/main.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPPyi4WjFDfm_Wqdw:-O0iPPyi4WjFDfm_Wqdx:budo11n) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L32)):*
> ```XML
>     run_server_components(&config, servers).await?;
> 
>     Ok(())
> ```

This should never return, right?

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/main.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iOz7X9ZhwCynWUs95:-O0nHkzuEBK3_i57WWFA:b-g91qlw) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L12)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why is `anyhow` required here?

ChatGPT suggested the following, does this remove the need for the `anyhow` dependency?

```
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    // Your async code here

    Ok(())
}
```
</blockquote></details>

This is how its done in the papyrus main.
___
*[`crates/mempool_node/src/main.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPAAV04zENyY79NcW:-O0nHcZPCHl3VtTwURCZ:b-qv3u5e) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What does this stand for?
</blockquote></details>

I command line argument parsing error.
___
*[`crates/mempool_node/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPGH111597Dfm7EVs:-O0nIIaM8ALX2_-w4GpN:b-j94sjg) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Where does this error code originates from? Or was it an arbitrary choice?
</blockquote></details>

In case config validation returns error we cannot continue.
___
*[`crates/mempool_node/src/main.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPPyi4WjFDfm_Wqdw:-O0nIUVd3mP39g3PVeJM:b2bw0s9) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L32)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This should never return, right?
</blockquote></details>

Right, but once more, went after papyrus main.
___
*[`crates/gateway/src/gateway.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iO97cDbrAGtFky0Le:-O0sqxg94kD9WdOBhRr7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/gateway/src/gateway.rs#L85)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please create a different pr solely for these changes.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iOQvCEKycVTvAIHbx:-O0nK3QD7o0TnV2NG4Eg:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/gateway/src/gateway.rs#L208)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please check out the `map_err` syntax, should be useful here.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311#-:-O0wm7EHEdFIQJ9ixhEh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by uriel-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/main.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/311#-O0iPPyi4WjFDfm_Wqdw:-O0wqVjs97Rhldv3w5ur:bgd617h) ([raw file](https://github.com/starkware-libs/mempool/blob/72c85079120d8767b7ded336a6cc32afde731fa7/crates/mempool_node/src/main.rs#L32)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Right, but once more, went after papyrus main.
</blockquote></details>

if `run\_server\_components(&config, servers).await` returns the same result as main then no need for `?;` and then `Ok(())`. Change to:



_Code snippet:_
```XML
run_server_components(&config, servers).await
```

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311#-:-O0ws9l9CbNeU8BvPltk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#339](https://github.com/starkware-libs/mempool/pull/339)

**Pull request closed without merging**
