### PR TITLE
feat: add function to create all clients

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #311
- #310
- #309
- #308
- #307
- #262 ⬅
- #261

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pF-7HB4ty-nvhkByo:-O-pF-7IA_ZHMjNNn4Br:bqou600) ([raw file](https://github.com/starkware-libs/mempool/blob/5bd54ba0b44fe2fcedaf808e3ed1a0884edd4639/crates/mempool_node/src/com_clients.rs#L9)):*
> ```XML
> 
> pub struct CommClients {
>     pub mempool_client: Option<Arc<MempoolClientImpl>>,
> ```

There's a (new) type alias for this type, `SharedMempoolClient` iirc.



_Code quote:_
```XML
Arc<MempoolClientImpl>
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pFZjs52Q6lo_RMKLE:-O-pFZjs52Q6lo_RMKLF:b-40g28g) ([raw file](https://github.com/starkware-libs/mempool/blob/169befd92ef39553ca4f9f953b3522e77a42f571/crates/mempool_node/src/com_clients.rs#L12)):*
> ```XML
> }
> 
> pub fn create_clients(config: &MempoolNodeConfig, channels: &CommChannels) -> CommClients {
> ```

Please rename to `create_node_clients`.



_Code quote:_
```XML
 create_clients
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGIyUELh9qJEacUSj:-O-pGIyUELh9qJEacUSk:b-p9zp39) ([raw file](https://github.com/starkware-libs/mempool/blob/169befd92ef39553ca4f9f953b3522e77a42f571/crates/mempool_node/src/com_clients.rs#L14)):*
> ```XML
> pub fn create_clients(config: &MempoolNodeConfig, channels: &CommChannels) -> CommClients {
>     let mempool_client = match config.components.gateway_component.execute {
>         true => Some(Arc::new(MempoolClientImpl::new(channels.mempool_channel.tx.clone()))),
> ```

I know the tx channel is clonable, and hence this code successfully compiles, but it makes more sense to me to pass ownership of this channel to the client -- who else would use it other than the client?

Note the client is also clonable.



_Code quote:_
```XML
channels.mempool_channel.tx.clone()
```
___
*[`crates/mempool_node/src/com_clients.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGFdh3ggDfgeVW3qL:-O-pGFdh3ggDfgeVW3qM:b27kq1z) ([raw file](https://github.com/starkware-libs/mempool/blob/169befd92ef39553ca4f9f953b3522e77a42f571/crates/mempool_node/src/com_clients.rs#L15)):*
> ```XML
>     let mempool_client = match config.components.gateway_component.execute {
>         true => Some(Arc::new(MempoolClientImpl::new(channels.mempool_channel.tx.clone()))),
>         false => None,
> ```

Why / when wouldn't there be a mempool client?



_Code quote:_
```XML
false => None,
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pF-7HB4ty-nvhkByo:-O-pegp67hg231FPc1iZ:b-6ue1ra) ([raw file](https://github.com/starkware-libs/mempool/blob/5bd54ba0b44fe2fcedaf808e3ed1a0884edd4639/crates/mempool_node/src/com_clients.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There's a (new) type alias for this type, `SharedMempoolClient` iirc.
</blockquote></details>

I can't because of the definition of the ComponenCreate trait.
but this is not a problem because Arc<MempoolClientImpl> is recognized as SharedMempoolClient for all consequent function calls.
___
*[`crates/mempool_node/src/com_clients.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pFZjs52Q6lo_RMKLE:-O-q8S6c6sS15rg94jcw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L12)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename to `create_node_clients`.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_clients.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGIyUELh9qJEacUSj:-O-pjTex6rMz3LZ-LzxE:b4wp10t) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I know the tx channel is clonable, and hence this code successfully compiles, but it makes more sense to me to pass ownership of this channel to the client -- who else would use it other than the client?

Note the client is also clonable.
</blockquote></details>

For example, as for today, a mock batcher is using it in a test. And anyway, it's changed to channels.get_mempool_tx()
___
*[`crates/mempool_node/src/com_clients.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGFdh3ggDfgeVW3qL:-O-q7Tp_CuDP0_1iDhBb:b-pq6uy7) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why / when wouldn't there be a mempool client?
</blockquote></details>

If we don't want to execute Gateway, we don't want to create it ( the Gateway), and then why would we create a Mempool client for it?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_UinBpf3kCTAxr9J:-O03_UinBpf3kCTAxr9K:bbeou4) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_client.rs#L14)):*
> ```XML
> }
> 
> pub type DummyClient = ComponentClient<(), ()>;
> ```

The convention is to call such objects `mock`, i.e., please change to `MockClient` (can be a todo)
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_FuAEekx0Xt601Hm:-O03_FuB-vvbN6UpSbOG:b-esrrhw) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
> ```XML
>     Response: Send + Sync,
> {
>     fn create(config: Config, comm_client: Option<Arc<ComponentClient<Request, Response>>>)
> ```

please change arg name to `client` or to `component_client` (can be a todo)



_Code quote:_
```XML
comm_client
```
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_KF_59zsrXUf-C15:-O03_KF_59zsrXUf-C16:bbe86bu) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
> ```XML
>     Response: Send + Sync,
> {
>     fn create(config: Config, comm_client: Option<Arc<ComponentClient<Request, Response>>>)
> ```

Why do we need `Arc` here? ComponentClient is cloneable as is.



_Code quote:_
```XML
Option<Arc<ComponentClient<Request, Response>>>
```
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03d9fW1-RBKVLisFvb:-O03d9fW1-RBKVLisFvc:beae4vj) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
> ```XML
>     Response: Send + Sync,
> {
>     fn create(config: Config, comm_client: Option<Arc<ComponentClient<Request, Response>>>)
> ```

f2f discussion regarding traits
___
*[`crates/mempool_infra/src/component_runner.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03ZrF2D8ceHyJ3tQOh:-O03ZrF2D8ceHyJ3tQOi:beg56dh) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L31)):*
> ```XML
> }
> 
> /// Interface to start memepool components.
> ```

Not in this pr, but:
1. memepool is a typo, should be mempool
2. I think it's even better just to drop this word entirely



_Code quote:_
```XML
memepool
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_UinBpf3kCTAxr9J:-O08EOECAZ3KaVpNRY0x:bdpf74s) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_client.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The convention is to call such objects `mock`, i.e., please change to `MockClient` (can be a todo)
</blockquote></details>

Deleted.
Done.
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_FuAEekx0Xt601Hm:-O08ESp5DR9OG-hryy-1:boj78ka) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

please change arg name to `client` or to `component_client` (can be a todo)
</blockquote></details>

As per the discussion, not in use currently.
Done.
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03_KF_59zsrXUf-C15:-O08Ecs8B6jcjFsn2sbS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why do we need `Arc` here? ComponentClient is cloneable as is.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_runner.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03d9fW1-RBKVLisFvb:-O08EdB21a0ji0KMX7hM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L27)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

f2f discussion regarding traits
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_runner.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O03ZrF2D8ceHyJ3tQOh:-O08EeAQDRwoRVqvatVx:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_infra/src/component_runner.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not in this pr, but:
1. memepool is a typo, should be mempool
2. I think it's even better just to drop this word entirely
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pF-7HB4ty-nvhkByo:-O08LxfRAmIbJ6-upIv7:b8fsete) ([raw file](https://github.com/starkware-libs/mempool/blob/5bd54ba0b44fe2fcedaf808e3ed1a0884edd4639/crates/mempool_node/src/com_clients.rs#L9)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I can't because of the definition of the ComponenCreate trait.
but this is not a problem because Arc<MempoolClientImpl> is recognized as SharedMempoolClient for all consequent function calls.
</blockquote></details>

Now using SharedMempoolClient.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pF-7HB4ty-nvhkByo:-O08LC0jBO8UTygau0so:bkbjkyt) ([raw file](https://github.com/starkware-libs/mempool/blob/5bd54ba0b44fe2fcedaf808e3ed1a0884edd4639/crates/mempool_node/src/com_clients.rs#L9)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I can't because of the definition of the ComponenCreate trait.
but this is not a problem because Arc<MempoolClientImpl> is recognized as SharedMempoolClient for all consequent function calls.
</blockquote></details>

My bad; the inner arc type should be `dyn MempoolClient` instead of `MempoolClientImpl`, or put together, `SharedMempoolClient`. Please change accordingly. The motivation is having any object that implements the client trait there, not just this specific one.
___
*[`crates/mempool_node/src/com_clients.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGFdh3ggDfgeVW3qL:-O08JYAiDGAg09obPugS:bb6sh2i) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L15)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

If we don't want to execute Gateway, we don't want to create it ( the Gateway), and then why would we create a Mempool client for it?
</blockquote></details>

Ack.
___
*[`crates/mempool_node/src/com_clients.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08LwVG3xlq5rYfjZiO:-O08LwVG3xlq5rYfjZiP:b-nexamn) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_node/src/com_clients.rs#L8)):*
> ```XML
> use crate::config::MempoolNodeConfig;
> 
> pub struct CommClients {
> ```

Please rename to `MempoolNodeClients`, or to `Clients`.



_Code quote:_
```XML
CommClients
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08MLy4D1-0ClOndhLn:-O08MLy4D1-0ClOndhLo:b-u9wrd3) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_node/src/com_clients.rs#L2)):*
> ```XML
> use std::sync::Arc;
> ```

Please move the content of this file to `communication.rs`.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_runner.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08QnVlDhhls8AmF1BL:-O08QnVlDhhls8AmF1BM:b-vd7x3q) ([raw file](https://github.com/starkware-libs/mempool/blob/e4eff05e9711396d3fa50ce3feadb5f8200fe6b5/crates/mempool_infra/src/component_runner.rs#L17)):*
> ```XML
> 
> /// Interface to create memepool components.
> pub trait ComponentCreator<T: SerializeConfig> {
> ```

Can this trait be entirely deleted?



_Code quote:_
```XML
pub trait ComponentCreator<T: SerializeConfig> {
```
___
*[`crates/mempool_node/src/com_clients.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGIyUELh9qJEacUSj:-O08R1WG18NnAXmx2oAb:b-i2tv4m) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L14)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

For example, as for today, a mock batcher is using it in a test. And anyway, it's changed to channels.get_mempool_tx()
</blockquote></details>

I'd like the following (can be in a different pr, if so, add a todo):

1. Change `get_mempool_tx()` to `take_mempool_tx()`, such that the ownership of the tx part is moved from the channels struct to the client c'tor (much like the rx part is moved to the server). Note this will require changing the mutability of the fn.

2. The field in the struct should be of type `Option<Box<dyn MempoolClient>>` (`Box` instead of `Arc`).

3. The `get_mempool_client()` fn (see comment above) should return a clone of the existing value (assuming it is not None).
___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08SJN99PevzLZiM5cW:-O08SJNA-AVoYXu-Fpwm:b-5bskak) ([raw file](https://github.com/starkware-libs/mempool/blob/682e7c188f6e28de374722df46b5b9f23c2fd3cf/crates/mempool_node/src/com_clients.rs#L9)):*
> ```XML
> 
> pub struct CommClients {
>     pub mempool_client: Option<SharedMempoolClient>,
> ```

Remove the pub visibility, and add the `new` and `get_mempool_client` functions. Can be in a different pr (if so, add a todo).



_Code quote:_
```XML
pub mempool_client: Option<SharedMempoolClient>,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGIyUELh9qJEacUSj:-O08T51Q40YWR8idUcdU:bjztvg4) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd like the following (can be in a different pr, if so, add a todo):

1. Change `get_mempool_tx()` to `take_mempool_tx()`, such that the ownership of the tx part is moved from the channels struct to the client c'tor (much like the rx part is moved to the server). Note this will require changing the mutability of the fn.

2. The field in the struct should be of type `Option<Box<dyn MempoolClient>>` (`Box` instead of `Arc`).

3. The `get_mempool_client()` fn (see comment above) should return a clone of the existing value (assuming it is not None).
</blockquote></details>

As for the mock batcher, iiuc, you can invoke the `get_mempool_client()` once again to get another mempool client.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08SJN99PevzLZiM5cW:-O0DN5UI9hdcSUQdZJcA:bgx4urd) ([raw file](https://github.com/starkware-libs/mempool/blob/682e7c188f6e28de374722df46b5b9f23c2fd3cf/crates/mempool_node/src/com_clients.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Remove the pub visibility, and add the `new` and `get_mempool_client` functions. Can be in a different pr (if so, add a todo).
</blockquote></details>

Specifically here, since this struct can be used by multiple components, please do add the getters as described ^

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_runner.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08QnVlDhhls8AmF1BL:-O08_JsqE947zHzik9ut:blroa71) ([raw file](https://github.com/starkware-libs/mempool/blob/e4eff05e9711396d3fa50ce3feadb5f8200fe6b5/crates/mempool_infra/src/component_runner.rs#L17)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can this trait be entirely deleted?
</blockquote></details>

Its not a new one and deleting it will make me rewrite component_runner_test. Lets leave by now. I will do it in another PR.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/com_clients.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/mempool/262#-O-pGIyUELh9qJEacUSj:-O0EKNlr49LRtUcMvG6i:b-y49nf8) ([raw file](https://github.com/starkware-libs/mempool/blob/25ca4abc84b93cdf106b05eb6612d143b632edef/crates/mempool_node/src/com_clients.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

As for the mock batcher, iiuc, you can invoke the `get_mempool_client()` once again to get another mempool client.
</blockquote></details>

1 and 3 are Done.
2 Will implement latter.  Adding TODO.
___
*[`crates/mempool_node/src/com_clients.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08MLy4D1-0ClOndhLn:-O0DUOmxBWge5y4JxFTw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_node/src/com_clients.rs#L2)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please move the content of this file to `communication.rs`.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_clients.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08LwVG3xlq5rYfjZiO:-O0DUNid94dhZ1lAMKBZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4e33568fc74f7afe9d073b2367df0e48667c3052/crates/mempool_node/src/com_clients.rs#L8)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename to `MempoolNodeClients`, or to `Clients`.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_clients.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/mempool/262#-O08SJN99PevzLZiM5cW:-O0EK7PE5SMJUHOX7D53:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/682e7c188f6e28de374722df46b5b9f23c2fd3cf/crates/mempool_node/src/com_clients.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Specifically here, since this struct can be used by multiple components, please do add the getters as described ^
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/mempool/262#-O0O9bq18YOnYAzN1RD0:-O0O9bq18YOnYAzN1RD1:b-byq9w3) ([raw file](https://github.com/starkware-libs/mempool/blob/3a1782e60ab3767098db96b5536aa70f2b7d1c2a/crates/mempool_node/src/communication.rs#L1)):*
> ```XML
> // use std::sync::Arc;
> ```

Please delete this comment.



_Code quote:_
```XML
// use std::sync::Arc;
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/communication.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/mempool/262#-O0O9bq18YOnYAzN1RD0:-O0PIedSCz-jD4IjabcK:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/378d94d59426730d04115df87dcd5f62c02bf3ca/crates/mempool_node/src/communication.rs#L1)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please delete this comment.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/262#-:-O0PpwM01HxgOaG0Gdab:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#308](https://github.com/starkware-libs/mempool/pull/308)

**Pull request closed without merging**
