### PR TITLE
feat: stateless validator add non zero fee check

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/29)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/29)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/transaction_validator.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/29#-NuwycN61SB91ssL8Aw2:-NuwycN61SB91ssL8Aw3:b-iham7x) ([raw file](https://github.com/starkware-libs/mempool/blob/adc7bc2451532f89cd6fba3128565716d8d5fa63/crates/gateway/src/transaction_validator.rs#L20)):*
> ```XML
>     fn default() -> Self {
>         Self {
>             fee_resource: Resource::L1Gas,
> ```

Please document, and consider making it a boolean.
___
*[`crates/gateway/src/transaction_validator.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/29#-Nux-GwU0eAF0UxxiCY9:-Nux-GwU0eAF0UxxiCYA:bnyx2k8) ([raw file](https://github.com/starkware-libs/mempool/blob/adc7bc2451532f89cd6fba3128565716d8d5fa63/crates/gateway/src/transaction_validator.rs#L53)):*
> ```XML
>             },
>         };
>         let resource_bounds = resource_bounds_mapping.0[&resource];
> ```

Can it panic?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/29)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/transaction_validator.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/29#-NuwycN61SB91ssL8Aw2:-Nuxls7PAagai6GIjBL_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/adc7bc2451532f89cd6fba3128565716d8d5fa63/crates/gateway/src/transaction_validator.rs#L20)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please document, and consider making it a boolean.
</blockquote></details>

Done.
___
*[`crates/gateway/src/transaction_validator.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/29#-Nux-GwU0eAF0UxxiCY9:-NuxkIylAhokKGOTc7a6:bndssk) ([raw file](https://github.com/starkware-libs/mempool/blob/adc7bc2451532f89cd6fba3128565716d8d5fa63/crates/gateway/src/transaction_validator.rs#L53)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it panic?
</blockquote></details>

Yes, it can panic. Now, we are handling this case (Which we need to validate). 

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/29)* status: 0 of 7 files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/gateway/src/transaction_validator.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/mempool/29#-Nv1HVOI-Q7DPiC6uI_N:-Nv61_yv3mr02w28zvrz:bvaiw95) ([raw file](https://github.com/starkware-libs/mempool/blob/2837a04a0ec9ba596768c9c964db389b42e698b6/crates/gateway/src/transaction_validator.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please ask Elin, so we can remove this TODO.
</blockquote></details>

@noaov1 agrees. It is planned that, in the near future, most txs will have both an L1 and L2 gas-cost component.

We would like to have both fields in that case.
Removed the TODO.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 3 of 5 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/29#-:-Nv62j124qN8p-f-jC0h:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yael-Starkware)

**Pull request merged**
