### PR TITLE
chore: create struct for gateway compiler

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#384** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/384?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#298** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/383?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/config.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1G9c5H775aRAK0mNOY:-O1G9c5ICjS9wy08M1MJ:b-4q0pf8) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/config.rs#L19)):*
> ```XML
>     pub stateless_tx_validator_config: StatelessTransactionValidatorConfig,
>     pub stateful_tx_validator_config: StatefulTransactionValidatorConfig,
>     pub gateway_compiler_config: GatewayCompilerConfig,
> ```

Consider renaming to just `compiler_config`



_Code quote:_
```XML
gateway_
```
___
*[`crates/gateway/src/gateway.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1G9s_L9fDSgYy_PPFT:-O1G9s_L9fDSgYy_PPFU:b7olxok) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway.rs#L123)):*
> ```XML
>     let optional_class_info = match &tx {
>         RPCTransaction::Declare(declare_tx) => {
>             let gateway_compiler = GatewayCompiler { config: Default::default() };
> ```

GatewayCompiler::default()



_Code quote:_
```XML
GatewayCompiler { config: Default::default() };
```
___
*[`crates/gateway/src/gateway_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1GAS0S4wbGjAp05Pjc:-O1GAS0S4wbGjAp05Pjd:b7olxok) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway_test.rs#L114)):*
> ```XML
>     let optional_class_info = match &external_tx {
>         RPCTransaction::Declare(declare_tx) => Some(
>             GatewayCompiler { config: Default::default() }
> ```

GatewayCompiler::default()



_Code quote:_
```XML
GatewayCompiler { config: Default::default() }
```
___
*[`crates/gateway/src/gateway_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1GAE1j7Zs1a8w-Nwdc:-O1GAE1j7Zs1a8w-Nwdd:b-ufogg) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway_test.rs#L116)):*
> ```XML
>             GatewayCompiler { config: Default::default() }
>                 .compile_contract_class(declare_tx)
>                 .unwrap(),
> ```

Shouldn't this return a result instead of unwrapping?
If not, I would still use expect instead of unwrap



_Code quote:_
```XML
.unwrap(),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1G9c5H775aRAK0mNOY:-O1GC0rX1SzzdCDeWGIb:b-cee4c9) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/config.rs#L19)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider renaming to just `compiler_config`
</blockquote></details>

I like the name you suggested.
Done.
___
*[`crates/gateway/src/gateway.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1G9s_L9fDSgYy_PPFT:-O1GCjTp64xKbR9HNxYY:b16ddcj) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway.rs#L123)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

GatewayCompiler::default()
</blockquote></details>

It is odd. I see this struct as corresponding to `StatelessTransactionValidator`/ `StatefulTransactionValidator`.

These structs do not implement `Default`.
Very soon, this config is going to be non-empty. For actual cases - it is going to be loaded from the `node-config`. For tests it should be manually set.
___
*[`crates/gateway/src/gateway_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1GAS0S4wbGjAp05Pjc:-O1GR2330_woWtaMY-uN:bja5ylj) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway_test.rs#L114)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

GatewayCompiler::default()
</blockquote></details>

As discussed in the previous point.
___
*[`crates/gateway/src/gateway_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1GAE1j7Zs1a8w-Nwdc:-O1GKINE9iazsAbyUnjU:b8nn5vi) ([raw file](https://github.com/starkware-libs/mempool/blob/9622e9a4ed8bee47333aeb5112321a30857a0018/crates/gateway/src/gateway_test.rs#L116)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't this return a result instead of unwrapping?
If not, I would still use expect instead of unwrap
</blockquote></details>

This is a test util, so there is no need to be type-safe here.

Indeed, we might want to be more careful and rename this function accordingly.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1R9eLU0JCJTlI3HOB1:-O1R9eLU0JCJTlI3HOB2:blmwlk8) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation.rs#L25)):*
> ```XML
>     #[allow(dead_code)]
>     pub config: GatewayCompilerConfig,
> }
> ```

Maybe we want to give this file a better name?
Maybe we want to rename the struct?



_Code quote:_
```XML
pub struct GatewayCompiler {
    #[allow(dead_code)]
    pub config: GatewayCompilerConfig,
}
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 6 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RSeGU9LShUSo-t1PX:-O1RSeGU9LShUSo-t1PY:b-cdj5ct) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation.rs#L95)):*
> ```XML
> // or unsupported so that the compiler would alert us on new builtins.
> fn supported_builtins() -> &'static Vec<String> {
>     static SUPPORTED_BUILTINS: OnceLock<Vec<String>> = OnceLock::new();
> ```

Wasn't it defined with lazy static? Why did it changed?
___
*[`crates/gateway/src/compilation_config.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RRnw_7jOuNY869MxL:-O1RRnw_7jOuNY869MxM:b2i7otn) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation_config.rs#L1)):*
> ```XML
> use std::collections::BTreeMap;
> ```

The rest of the config structs are in the `config.rs` right?
Lets be consistent.
___
*[`crates/gateway/src/compilation_test.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RSxu0B6HnJeci23dC:-O1RSxu0B6HnJeci23dD:b-mkf6t3) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation_test.rs#L24)):*
> ```XML
>     let declare_tx = RPCDeclareTransaction::V3(tx);
> 
>     let result = GatewayCompiler { config: Default::default() }.compile_contract_class(&declare_tx);
> ```

Can you define it with a fixture?



_Code quote:_
```XML
GatewayCompiler { config: Default::default() }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RSeGU9LShUSo-t1PX:-O1RZMi75kqEFh5UpUgL:bee6vnk) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation.rs#L95)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Wasn't it defined with lazy static? Why did it changed?
</blockquote></details>

It was changed Per Gilad's request.
See PR: #353.
Lazy static [is deprecated](https://starkwareindustries.slack.com/archives/C048GKX8056/p1711548068469199).
___
*[`crates/gateway/src/compilation_test.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RSxu0B6HnJeci23dC:-O1RaUrb8ZH7cdLY5SiH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation_test.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you define it with a fixture?
</blockquote></details>

Done.
___
*[`crates/gateway/src/compilation_config.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RRnw_7jOuNY869MxL:-O1RaXKH-rNNiqTzplm-:brpmqc3) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation_config.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The rest of the config structs are in the `config.rs` right?
Lets be consistent.
</blockquote></details>

removed.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383#-:-O1VmKjdA0SAWQOEwOVd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/mempool/383#-O1RSeGU9LShUSo-t1PX:-O1Vm2-FD_zDLA-0Gs7Y:b-ucfknh) ([raw file](https://github.com/starkware-libs/mempool/blob/fdf9ddd72397e68fa2e5cc3b5513fabe240bc93d/crates/gateway/src/compilation.rs#L95)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It was changed Per Gilad's request.
See PR: #353.
Lazy static [is deprecated](https://starkwareindustries.slack.com/archives/C048GKX8056/p1711548068469199).
</blockquote></details>

Thanks!

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Jul 14, 7:12 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/mempool/383).

**Pull request merged**
