### PR TITLE
test: use assert matches for more informative error message

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/203)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#203** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/203?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/203)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/203#-NzS2CAcBEKWc62BByr6):*
what is the difference between the error message when using assert and assert_matches?

**Comment by ArniStarkware** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/mempool/203#-NzS2CAcBEKWc62BByr6):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what is the difference between the error message when using assert and assert_matches?
</blockquote></details>

Great question!

With `assert`:
```

---- stateless_transaction_validator::stateless_transaction_validator_test::test_positive_flow::case_5_valid_tx::tx_type_1_TransactionType__Declare stdout ----
thread 'stateless_transaction_validator::stateless_transaction_validator_test::test_positive_flow::case_5_valid_tx::tx_type_1_TransactionType__Declare' panicked at crates/gateway/src/stateless_transaction_validator_test.rs:78:5:
assertion failed: tx_validator.validate(&tx).is_ok()
```

With `assert_matches`: (From a different project).
```
---- stateless_transaction_validator::stateless_transaction_validator_test::test_positive_flow::case_5_valid_tx::tx_type_1_TransactionType__Declare stdout ----
thread 'stateless_transaction_validator::stateless_transaction_validator_test::test_positive_flow::case_5_valid_tx::tx_type_1_TransactionType__Declare' panicked at crates/gateway/src/stateless_transaction_validator_test.rs:79:5:
assertion failed: `Err(DeclareTransactionError(SierraProgramTooShort { length: 0, program_prefix: [StarkFelt("0x0000000000000000000000000000000000000000000000000000000000000000"), StarkFelt("0x0000000000000000000000000000000000000000000000000000000000000000")] }))` does not match `Ok(())`
```

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
