### PR TITLE
test(mempool): get_txs multi nonce

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481#-:-O1uMV3q0TToMQdcNJu6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vSyDY1OzUhwO_l5fZ:-O1vSyDY1OzUhwO_l5f_:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L179)):*
> ```XML
>     // Setup.
>     let input_address_0_nonce_0 =
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
> ```





_Suggestion:_
```XML
    let tx_address_0_nonce_0 =
        add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8)0tx;
```
___
*[`crates/mempool/src/mempool_test.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vT2E57IvV2-rXmeb-:-O1vT2E57IvV2-rXmeb0:b-pzmcz2) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L181)):*
> ```XML
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
>     let input_address_0_nonce_1 =
>         add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
> ```

Please add a tip, where the tx with lower nonce has a lower tip," and then the test checks that `get_txs` returns the lower nonce, although it has a lower tip.



_Code quote:_
```XML
    let input_address_0_nonce_0 =
        add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
    let input_address_0_nonce_1 =
        add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vSyDY1OzUhwO_l5fZ:-O1vdz5e9xOEY8_SXSwu:b90y2ek) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L179)):*
> ```XML
>     // Setup.
>     let input_address_0_nonce_0 =
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
> ```

Let's decide on a convention for all tests.
___
*[`crates/mempool/src/mempool_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1veUu84TAn54LLo36R:-O1veUu84TAn54LLo36S:b-f6w9pw) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L190)):*
> ```XML
>     let txs = mempool.get_txs(1).unwrap();
> 
>     // Assert that the account's next tx was added the queue.
> ```

This will change, right?
Comment should be resilient.



_Code quote:_
```XML
// Assert that the account's next tx was added the queue.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vSyDY1OzUhwO_l5fZ:-O1vn-qp9Zn49IsBB01t:b-srtqdt) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L179)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's decide on a convention for all tests.
</blockquote></details>

It depends on whether it's a get_txs test (tx input is enough) or an add_tx test (we need the entire input). Here tx is better, so I fixed it.
___
*[`crates/mempool/src/mempool_test.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vT2E57IvV2-rXmeb-:-O1vnY4YC1uqY1JJiqcQ:b-i15m4r) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L181)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add a tip, where the tx with lower nonce has a lower tip," and then the test checks that `get_txs` returns the lower nonce, although it has a lower tip.
</blockquote></details>

I don't understand. How is the tip relevant here? The order is according to the nonce when speaking of the same account.
___
*[`crates/mempool/src/mempool_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1veUu84TAn54LLo36R:-O1vo6UZEHUQ8x1WX4d-:b3v4mvb) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L190)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This will change, right?
Comment should be resilient.
</blockquote></details>

nope. this test doesn't pass since replenishing is not implemented. Added an ignore tag and todo.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1vSyDY1OzUhwO_l5fZ:-O1yqux3DaZyovzvXjc1:b-mes2a2) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L179)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It depends on whether it's a get_txs test (tx input is enough) or an add_tx test (we need the entire input). Here tx is better, so I fixed it.
</blockquote></details>

Okay, can you please make sure what you described applies to all tests?
Also, we sometimes have `tip0` and sometimes `tip_0`; let's decide on one of them and align all tests.
___
*[`crates/mempool/src/mempool_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1veUu84TAn54LLo36R:-O2-FeRx5ti45s2DBMd3:b-r7h4a3) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L190)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

nope. this test doesn't pass since replenishing is not implemented. Added an ignore tag and todo.
</blockquote></details>

Why are you asking only for one transaction here?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/481)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/mempool/481#-O1veUu84TAn54LLo36R:-O2-MZc8BuxSGwsNU2gc:b-y3c0ch) ([raw file](https://github.com/starkware-libs/mempool/blob/5d1bb08bfb862b578835f5a44f6c781b9710d052/crates/mempool/src/mempool_test.rs#L190)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why are you asking only for one transaction here?
</blockquote></details>

It doesn't matter whether I ask `get_txs` to fetch two transactions and check that it returned both transactions or ask `get_txs` for one transaction and check that the second transaction was added to the queue. I agree that it makes more sense to fetch two transactions, so I changed it.

**Pull request merged**
