### PR TITLE
test: add faulty server tests

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HWsja99Q4HlkjaDxx:-O1HWsjb9dkKvGtA6cQ0:bm70a2l) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L93)):*
> ```XML
> 
>     let a_port = 10000;
>     let b_port = 10001;
> ```

Please define ports as constants as well, with indicative names. Do the same for the error ports (e.g., 10004).



_Code quote:_
```XML
    let a_port = 10000;
    let b_port = 10001;
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HWVWcCcFNSh68APx2:-O1HWVWcCcFNSh68APx3:b-gdph8v) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L135)):*
> ```XML
>             panic!("Expected keyword: '{expected_keyword}' is not in error: '{error}'.")
>         }
>     }
> ```

Please wrap in a fn.



_Code quote:_
```XML
    for expected_keyword in expected_error_contained_keywords {
        if !error.to_string().contains(expected_keyword) {
            panic!("Expected keyword: '{expected_keyword}' is not in error: '{error}'.")
        }
    }
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HXBnQ9_lyh3oHGz1m:-O1HXBnQ9_lyh3oHGz1n:b-uxp14o) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L148)):*
> ```XML
> 
> #[tokio::test]
> async fn test_faulty_server_1() {
> ```

please change `1` to indicate the expected error -- deser issue?



_Code quote:_
```XML
test_faulty_server_1(
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HXKoT3MwCT0a_iKbF:-O1HXKoT3MwCT0a_iKbG:b-7ropln) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L177)):*
> ```XML
> 
> #[tokio::test]
> async fn test_faulty_server_2() {
> ```

ditto



_Code quote:_
```XML
test_faulty_server_2
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HWsja99Q4HlkjaDxx:-O1H_0PRBPizS9WWdBj7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L93)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please define ports as constants as well, with indicative names. Do the same for the error ports (e.g., 10004).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HWVWcCcFNSh68APx2:-O1HYZIT4Vv6rRhDGJ_U:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L135)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please wrap in a fn.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HXBnQ9_lyh3oHGz1m:-O1HYhItDa4Q_eAOUY1N:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L148)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

please change `1` to indicate the expected error -- deser issue?
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1HXKoT3MwCT0a_iKbF:-O1HYewKDp8YNiUcPdWZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1692290bfe129fe7565b88cc7eb8a13eba4080eb/crates/mempool_infra/tests/component_server_client_http_test.rs#L177)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LaQsJ8RM-lHRWJSi-:-O1LaQsK7Mfd3JXwyuk1:b-amo4nk) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
> ```XML
> 
> #[tokio::test]
> async fn test_faulty_server_request_deseralization_failure_mock_error() {
> ```

Please remove this suffix, making the test names consistent



_Code quote:_
```XML
_mock_error
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbNl3BkZhAqTDKC5X:-O1LbNl3BkZhAqTDKC5Y:b-wcsw0h) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L168)):*
> ```XML
>         let make_svc =
>             make_service_fn(|_conn| async { Ok::<_, hyper::Error>(service_fn(handler)) });
>         Server::bind(&socket).serve(make_svc).await.unwrap();
> ```

Please wrap as a function that takes `error_str, port` and use in both tests.



_Code quote:_
```XML
            Ok(Response::builder()
                .status(StatusCode::BAD_REQUEST)
                .body(Body::from(serialize(&server_error).unwrap()))
                .unwrap())
        }

        let socket = SocketAddr::new(LOCAL_IP, FAULTY_SERVER_REQ_DESER_PORT);
        let make_svc =
            make_service_fn(|_conn| async { Ok::<_, hyper::Error>(service_fn(handler)) });
        Server::bind(&socket).serve(make_svc).await.unwrap();
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbSjJ8Cja-czuDif1:-O1LbSjJ8Cja-czuDif2:bgf4lvc) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L184)):*
> ```XML
>             Ok(Response::builder()
>                 .status(StatusCode::BAD_REQUEST)
>                 .body(Body::from(serialize("garbage").unwrap()))
> ```

Define as a const, similar to `MOCK_SERVER_ERROR` in the previous test



_Code quote:_
```XML
"garbage"
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbimSEL1qZcxawD0-:-O1LbimT2Wre1_iD2xVk:b-rizhdb) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L196)):*
> ```XML
> 
>     let client = ComponentAClient::new(LOCAL_IP, FAULTY_SERVER_RES_DESER_PORT);
>     let expected_error_contained_keywords = vec!["Could not deserialize server response"];
> ```

Do we expect to see `garbage` here as well?



_Code quote:_
```XML
"Could not deserialize server response"
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LaQsJ8RM-lHRWJSi-:-O1Lck0e5TOcfnXbs8Ez:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove this suffix, making the test names consistent
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbNl3BkZhAqTDKC5X:-O1MEXXk8gWEpcQ8XEK4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L168)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please wrap as a function that takes `error_str, port` and use in both tests.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbSjJ8Cja-czuDif1:-O1ME_s_84BItwSNYOrG:btt8nxl) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L184)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Define as a const, similar to `MOCK_SERVER_ERROR` in the previous test
</blockquote></details>

This is called garbage because it's unimportant. I could've put the number 3 here as far as I care. There is no other place in the code that I need to refer to it. Is defining it as a const make sense in this case?
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbimSEL1qZcxawD0-:-O1LeOER3TTS1SM087OY:b-p3qz3i) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L196)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we expect to see `garbage` here as well?
</blockquote></details>

No, the garbage str is just my input to the body, client expects a ComponentAResponse struct, not a string. Thus I called it "garbage"

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbSjJ8Cja-czuDif1:-O1MGA4S23HG2wVrbF61:bima7hq) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L184)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

This is called garbage because it's unimportant. I could've put the number 3 here as far as I care. There is no other place in the code that I need to refer to it. Is defining it as a const make sense in this case?
</blockquote></details>

Further more, if I would have hided it under a const CAPSLOCK word called GARBAGE, then the reader would wonder what is that? and why is it considered garbage and then the reader would go to the definition of GARBAGE just to see its type. Currently you can just see that we pass a str variable which is obviously not what the client expects

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbSjJ8Cja-czuDif1:-O1MYHQTCIRT75Y42C8K:b-nxllbl) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L184)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Further more, if I would have hided it under a const CAPSLOCK word called GARBAGE, then the reader would wonder what is that? and why is it considered garbage and then the reader would go to the definition of GARBAGE just to see its type. Currently you can just see that we pass a str variable which is obviously not what the client expects
</blockquote></details>

I see. 
Please indicate this is an arbitrary string then, either by a comment or by changing the string to "arbitrary message"; I prefer the latter.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1MYoVb7iQqc9PlbahQ:-O1MYoVb7iQqc9PlbahR:bx67ec2) ([raw file](https://github.com/starkware-libs/mempool/blob/436aa89480b1107e49e2dce544f2fc63a520df7b/crates/mempool_infra/tests/component_server_client_http_test.rs#L173)):*
> ```XML
>         Server::bind(&socket).serve(make_svc).await.unwrap();
>     });
>     task::yield_now().await;
> ```

Please add a comment explaining why this is required: "Ensure the server starts running.".



_Code quote:_
```XML
task::yield_now().await;
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1LbSjJ8Cja-czuDif1:-O1MaZ_g91KN-DPmec4j:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9c93d54f1b96a8f97aa8becc4b3f4d408cc237a2/crates/mempool_infra/tests/component_server_client_http_test.rs#L184)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I see. 
Please indicate this is an arbitrary string then, either by a comment or by changing the string to "arbitrary message"; I prefer the latter.
</blockquote></details>

Done.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/mempool/400#-O1MYoVb7iQqc9PlbahQ:-O1Map5JDro_LIQIB-cw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/436aa89480b1107e49e2dce544f2fc63a520df7b/crates/mempool_infra/tests/component_server_client_http_test.rs#L173)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a comment explaining why this is required: "Ensure the server starts running.".
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400#-:-O1McKT-81b7fG34sOhn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/400)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
