### PR TITLE
feat: add functionality to create all servers

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:0f64f96b

---

**Stack**:
- #339
- #311
- #355
- #310 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iGwpHBkk0PT17kRV0:-O0iGwpHBkk0PT17kRV1:b-yx5440) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L4)):*
> ```XML
> // use std::pin::Pin;
> 
> // use futures::{Future, FutureExt};
> ```

Remove these please.



_Code quote:_
```XML
// use std::future::pending;
// use std::pin::Pin;

// use futures::{Future, FutureExt};
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iH6AR4AaeUvjLFcAt:-O0iH6AR4AaeUvjLFcAu:b-9753rw) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L36)):*
> ```XML
>             channels.take_mempool_rx(),
>         )));
>     }
> ```

Please use the pattern we discussed: initalize each component as either `Some(...)` or `None`, and then init the `servers` struct with their values.



_Code quote:_
```XML
    let mut servers = Servers { gateway: None, mempool: None };

    if config.components.gateway_component.execute {
        servers.gateway = Some(Box::new(create_gateway_server(
            components.gateway.expect("Gateway component is not initialized."),
        )));
    }

    if config.components.mempool_component.execute {
        servers.mempool = Some(Box::new(create_mempool_server(
            components.mempool.expect("Mempool component is not initialized."),
            channels.take_mempool_rx(),
        )));
    }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iHrngAKfItO4uhMCf:-O0iHrngAKfItO4uhMCg:b-1vjzvs) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L15)):*
> ```XML
> pub struct Servers {
>     pub gateway: Option<Box<dyn ComponentServerStarter>>,
>     pub mempool: Option<Box<dyn ComponentServerStarter>>,
> ```

These types should be the concrete types of the servers, no?



_Code quote:_
```XML
    pub gateway: Option<Box<dyn ComponentServerStarter>>,
    pub mempool: Option<Box<dyn ComponentServerStarter>>,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iMyzyD1sApW4SAxkO:-O0iMyzyD1sApW4SAxkP:buijdoh) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L20)):*
> ```XML
> pub fn create_servers(
>     config: &MempoolNodeConfig,
>     mut channels: MempoolNodeCommunication,
> ```

Please rename and avoid using `channels`, this is confusing. Non-abiding suggestion: `communication`.



_Code quote:_
```XML
channels
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNMPJEx0284ETm5N7:-O0iNMPJEx0284ETm5N8:b-ipywue) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L25)):*
> ```XML
>     let mut servers = Servers { gateway: None, mempool: None };
> 
>     if config.components.gateway_component.execute {
> ```

I think we should rename this to `gateway`; add a todo?



_Code quote:_
```XML
gateway_component
```
___
*[`crates/mempool_node/src/servers.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNVii35QyrEIlNDpA:-O0iNVii35QyrEIlNDpB:b-867xyf) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L27)):*
> ```XML
>     if config.components.gateway_component.execute {
>         servers.gateway = Some(Box::new(create_gateway_server(
>             components.gateway.expect("Gateway component is not initialized."),
> ```

Please remove.



_Code quote:_
```XML
component
```
___
*[`crates/mempool_node/src/servers.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNTJUCBOQpS-8qz1o:-O0iNTJUCBOQpS-8qz1p:bs4q9op) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L31)):*
> ```XML
>     }
> 
>     if config.components.mempool_component.execute {
> ```

Ditto.
___
*[`crates/mempool_node/src/servers.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNZ7h2afJxHxj4Cyn:-O0iNZ7h2afJxHxj4Cyo:b-867xyf) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L33)):*
> ```XML
>     if config.components.mempool_component.execute {
>         servers.mempool = Some(Box::new(create_mempool_server(
>             components.mempool.expect("Mempool component is not initialized."),
> ```

Please remove.



_Code quote:_
```XML
component
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/servers.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iGwpHBkk0PT17kRV0:-O0iuAds6a0q3XL4rYmX:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Remove these please.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/servers.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iHrngAKfItO4uhMCf:-O0iuFVZ8p-q9qFP72oP:b-tocmx1) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These types should be the concrete types of the servers, no?
</blockquote></details>

We don't need concrete types here.  All we are using are the servers start function.
___
*[`crates/mempool_node/src/servers.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNMPJEx0284ETm5N7:-O0ivoRp9flv20qkbPB-:b-a2khg0) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L25)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I think we should rename this to `gateway`; add a todo?
</blockquote></details>

We decided not to do it in this PR
___
*[`crates/mempool_node/src/servers.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNVii35QyrEIlNDpA:-O0ivlB--gQ_IZOA1GXR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L27)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/servers.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNTJUCBOQpS-8qz1o:-O0iw0snEoY-aubHAYAi:b-a2khg0) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

We decided not to do it in this PR
___
*[`crates/mempool_node/src/servers.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iNZ7h2afJxHxj4Cyn:-O0ivmH4E3GP1xCQOFtl:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L33)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/servers.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iH6AR4AaeUvjLFcAt:-O0ivmrNCF-u4Qj5yy9v:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L36)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use the pattern we discussed: initalize each component as either `Some(...)` or `None`, and then init the `servers` struct with their values.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iHrngAKfItO4uhMCf:-O0mjBQ4Dt7vYuMWGnmZ:b-qphzw9) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L15)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

We don't need concrete types here.  All we are using are the servers start function.
</blockquote></details>

Yea, I understand why this works as is, but imo the readability will be significantly improved if we state the specific type of each server, not just the fact that it implements the `ComponentServerStarter` trait.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/servers.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/310#-O0iHrngAKfItO4uhMCf:-O0nS2FH5RrSyfrJhm5U:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/ba88c86353366bd52a2d8089bdcb47c6423c12ba/crates/mempool_node/src/servers.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yea, I understand why this works as is, but imo the readability will be significantly improved if we state the specific type of each server, not just the fact that it implements the `ComponentServerStarter` trait.
</blockquote></details>

Done

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/310#-:-O0wlRvs3Pc9dNGKgeKf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
