### PR TITLE
feat: add get_block_info to rpc reader

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_objects.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/mempool/96#-Nx6s9GxBGOEF34etasM:-Nx6s9GxBGOEF34etasN:bkuwlnl) ([raw file](https://github.com/starkware-libs/mempool/blob/4b6b34be2a090b4507a79280b5fb9eeada073329/crates/gateway/src/rpc_objects.rs#L115)):*
> ```XML
>     pub status: BlockStatus,
>     #[serde(flatten)]
>     pub header: BlockHeader,
> ```

Do we need only this for the result?
If so, can we remove the other 2 and only parse the header?



_Code quote:_
```XML
pub header: BlockHeader,
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/mempool/96#-NxC_3Bk6yHNHaSEEkBg:-NxC_3Bk6yHNHaSEEkBh:b-6zzrgg) ([raw file](https://github.com/starkware-libs/mempool/blob/fca9b76daad4b8fa4125b2ee3568c8d84e6a2977/crates/gateway/src/rpc_state_reader.rs#L18)):*
> ```XML
> };
> 
> pub struct RpcStateReader {
> ```

Why the change of the name?

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 6 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/rpc_objects.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/mempool/96#-NxHBCp45W4tWtbIwJWh:-NxHBCp55GzPoCBwkS5a:bw8aqye) ([raw file](https://github.com/starkware-libs/mempool/blob/45442caeb24382deacca01341c5c9bcad860c15e/crates/gateway/src/rpc_objects.rs#L70)):*
> ```XML
> 
> #[derive(Debug, Deserialize, Serialize)]
> pub enum BlockStatus {
> ```

Can this be deleted?



_Code quote:_
```XML
pub enum BlockStatus
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/mempool/96#-NxC_3Bk6yHNHaSEEkBg:-NxHBSrP4W3qUNp9n7B5:bqczjyo) ([raw file](https://github.com/starkware-libs/mempool/blob/fca9b76daad4b8fa4125b2ee3568c8d84e6a2977/crates/gateway/src/rpc_state_reader.rs#L18)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Once I added the get_block_info, it is not a stateReader anymore. It is not reading only the state but a more general object that reading other stuff as well.
</blockquote></details>

But the block info is still considered part of the state no?
`RpcReader` is too general. I think either changing back to `RpcStateReader`, or to name it `PapyrusRpcReader`

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/mempool/96#-NxC_3Bk6yHNHaSEEkBg:-NxHE_dC5uA8goBqVuA_:bm4hblr) ([raw file](https://github.com/starkware-libs/mempool/blob/fca9b76daad4b8fa4125b2ee3568c8d84e6a2977/crates/gateway/src/rpc_state_reader.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

But the block info is still considered part of the state no?
`RpcReader` is too general. I think either changing back to `RpcStateReader`, or to name it `PapyrusRpcReader`
</blockquote></details>

the block_info is not part of the state, but thinking about it, the compiled_class is also not part of the state and we still read it. so I'm ok with RpcStateReader.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/96#-:-NxHJfbA41YxR9wtoV6M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
