### PR TITLE
feat: add more meat to e2e test

### PR DESCRIPTION
**Pull request by giladchase**
TODO: add more e2e scenarios.

---

**Stack**:
- #253 ⬅
- #252

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/253)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/253)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/253#-O-po0bt2K3A0r4D5ghz:-O-po0bt2K3A0r4D5gi-:b-imy05m) ([raw file](https://github.com/starkware-libs/mempool/blob/488d43ec8d9416b1f78562b4e604c2fdbc465e6b/crates/tests-integration/src/integration_test_setup.rs#L34)):*
> ```XML
> }
> 
> impl IntegrationTestSetup {
> ```

How about the following naming convention (also for `GatewayClient`): `[add_tx/get_txs]_and_verify_[success/error]`?



_Code quote:_
```XML
IntegrationTestSetup
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/mempool/253#-O-poRkUCjJzzbD9pdus:-O-poRkUCjJzzbD9pdut:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/488d43ec8d9416b1f78562b4e604c2fdbc465e6b/crates/tests-integration/src/integration_test_setup.rs#L108)):*
> ```XML
>         expected_tx_hashes: &[TransactionHash],
>     ) {
>         let mempool_txs = self.get_txs(n_txs).await;
> ```





_Suggestion:_
```XML
txs_hashes
```

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 4 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/253)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/mempool/253#-O0DbKctEo18yz87mjY9:-O0DbKcu3RdTWG4rxv88:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/50b2a0e35e5668ffc8f5ca4abf640ef681226a75/crates/gateway/src/starknet_api_test_utils.rs#L184)):*
> ```XML
>     }
> 
>     /// Generates a valid transaction, allowing overrides only for fields that don't
> ```





_Suggestion:_
```XML
do not
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/mempool/253#-O0DbNT6DBgZyinrVnMv:-O0DbNT6DBgZyinrVnMw:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/50b2a0e35e5668ffc8f5ca4abf640ef681226a75/crates/gateway/src/starknet_api_test_utils.rs#L188)):*
> ```XML
>     ///
>     /// To overrides the remaining fields use [AccountTransactionGenerator::generate_raw].
>     pub fn generate_valid_with_overrides(
> ```





_Suggestion:_
```XML
generate_valid_tx_with_overrides
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/mempool/253#-O0JFl8J50JS-qKzeFce:-O0JFl8J50JS-qKzeFcf:b72f17y) ([raw file](https://github.com/starkware-libs/mempool/blob/0211b09409dd2be01d0c90edf569d668de8a7978/crates/tests-integration/tests/end_to_end_test.rs#L12)):*
> ```XML
>     let (mut mock_running_system, mut tx_generator) = setup_with_tx_generation(n_accounts).await;
> 
>     // asking for more txs than the number stored should return all the stored txs.
> ```

Also, "transaction(s)" in docs.
Also, I like the numbers 1-10 to be written in words in docs.



_Suggestion:_
```XML
// Ask 
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/mempool/253#-O0JFx_g1wjGlWt5zwtk:-O0JFx_g1wjGlWt5zwtl:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0211b09409dd2be01d0c90edf569d668de8a7978/crates/tests-integration/tests/end_to_end_test.rs#L24)):*
> ```XML
>     mock_running_system.assert_get_txs_eq(0, &[]).await;
> 
>     // Gen new tx from the first contract and add a second account with a a new tx, check that
> ```





_Suggestion:_
```XML
// Generate
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/253)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/mempool/253#-O0JGDX_CGrjwXx3nn3B:-O0JGDX_CGrjwXx3nn3C:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0211b09409dd2be01d0c90edf569d668de8a7978/crates/tests-integration/tests/end_to_end_test.rs#L10)):*
> ```XML
> async fn test_mempool_emptying_scenarios() {
>     let n_accounts = 2;
>     let (mut mock_running_system, mut tx_generator) = setup_with_tx_generation(n_accounts).await;
> ```





_Suggestion:_
```XML
mock_system
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/253)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase)

**Comment by giladchase** [comment]
@elintul Closing this, rebase changes too much stuff, will recreate with your comments implemented in recreated solutoin.

**Pull request closed without merging**
