### PR TITLE
test(mempool): flow test a commit block closes a nonce gap

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/518)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/518)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2PRLyrBdN9VH_DqkZ9:-O2PRLyrBdN9VH_DqkZA:b-rd66o4) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L426)):*
> ```XML
> 
> #[rstest]
> #[ignore]
> ```

This test waits for commit PRs to be merged.



_Code quote:_
```XML
#[ignore]
```
___
*[`crates/mempool/src/mempool_test.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2PRWSI0b-mI7w5utmJ:-O2PRWSI0b-mI7w5utmK:b-fjt8l2) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L445)):*
> ```XML
>     assert!(mempool.commit_block(commit_state).is_ok());
> 
>     mempool.add_tx(tx_input_nonce4).unwrap(); // BUG! It should fail on DuplicateTransaction.
> ```

Is it a real bug?



_Code quote:_
```XML
mempool.add_tx(tx_input_nonce4).unwrap(); // BUG! It should fail on DuplicateTransaction.
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/518)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 426 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UZ-T92P2qhlECRDau:-O2UZ-T92P2qhlECRDav:b-lx82wr) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L426)):*
> ```XML
> 
> #[rstest]
> #[ignore]
> ```

Should we add the case in which a hole is closed without the mempool ever seeing this transaction?
___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UYnOnCHd6-f2Kg7_-:-O2UYnOnCHd6-f2Kg7_0:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L430)):*
> ```XML
>     let tx_nonce3 =
>         add_tx_input!(tip: 10, tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8, account_nonce: 3_u8).tx;
>     let tx_input_nonce4 = add_tx_input!(tip: 11, tx_hash: 2, sender_address: "0x0", tx_nonce: 4_u8, account_nonce: 5_u8);
> ```





_Suggestion:_
```XML
fn test_flow_commit_block_closes_hole() {
    // Setup.
    let tx_nonce3 =
        add_tx_input!(tip: 10, tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8, account_nonce: 3_u8).tx;
    let tx_nonce4 = add_tx_input!(tip: 11, tx_hash: 2, sender_address: "0x0", tx_nonce: 4_u8, account_nonce: 5_u8);
```
___
*[`crates/mempool/src/mempool_test.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UYixq14fhq_Q_I8m6:-O2UYixq14fhq_Q_I8m7:b-j1u6nn) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L440)):*
> ```XML
>     let txs_iterator = pool_txs.iter().cloned();
>     let mut mempool: Mempool = MempoolState::new(txs_iterator, tx_references_iterator).into();
> ```

One `clone()`, please.
___
*[`crates/mempool/src/mempool_test.rs` line 441 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UYt4_4QXobuxVRXLu:-O2UYt4_4QXobuxVRXLv:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L441)):*
> ```XML
>     let mut mempool: Mempool = MempoolState::new(txs_iterator, tx_references_iterator).into();
> 
>     let commit_state =
> ```





_Suggestion:_
```XML
// Test.
let state_changes =
```
___
*[`crates/mempool/src/mempool_test.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2PRWSI0b-mI7w5utmJ:-O2UZAoHBMaYw6J9JwWT:b-s40pse) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L445)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it a real bug?
</blockquote></details>

Why do you invoke `add_tx` here? Should be a `commit_block` unit test.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/518)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UYnOnCHd6-f2Kg7_-:-O2dLpveAK96aSSxpM2y:b8kv16y) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L430)):*
> ```XML
>     let tx_nonce3 =
>         add_tx_input!(tip: 10, tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8, account_nonce: 3_u8).tx;
>     let tx_input_nonce4 = add_tx_input!(tip: 11, tx_hash: 2, sender_address: "0x0", tx_nonce: 4_u8, account_nonce: 5_u8);
> ```

Note that this is a tx_input, which contains the the account state as well.
___
*[`crates/mempool/src/mempool_test.rs` line 440 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2UYixq14fhq_Q_I8m6:-O2dNtt41niU8vlla2gZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L440)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

One `clone()`, please.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/mempool/518#-O2PRWSI0b-mI7w5utmJ:-O2dNwqf3U7oVFV-lmfM:b-ax7wzo) ([raw file](https://github.com/starkware-libs/mempool/blob/c8589c99b8ac265a9505b14672aa8d0f7b29306b/crates/mempool/src/mempool_test.rs#L445)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do you invoke `add_tx` here? Should be a `commit_block` unit test.
</blockquote></details>

We have a commit block test that closes holes.
This test verifies that adding a transaction that wasn't added before will be rejected by duplicateTx due to a closed hole.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/518)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Pull request closed without merging**
