### PR TITLE
feat(mempool): impl mempool state

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/497#-O23bC9qBSLFa49ozkY6:-O23bC9qBSLFa49ozkY7:b8e15r0) (no related file):*
This PR implements the Mempool state, representing the state that the mempool is aware of during batch processing.
The Mempool state is updated in `get_txs`, used in `add_tx` and `commit_block`, and reset after `commit_block`.

___

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/mempool/497#-O25Qklg6mVPYKRzW9qm:-O25Qklg6mVPYKRzW9qn:b50znxo) ([raw file](https://github.com/starkware-libs/mempool/blob/3dac360ffe25ed27457103c372ba920e707c179e/crates/mempool/src/mempool.rs#L69)):*
> ```XML
>         for tx in &eligible_txs {
>             self.mempool_state.entry(tx.sender_address).or_default().nonce = tx.nonce;
>         }
> ```

Can you explain these loops?



_Code quote:_
```XML
        for tx in &eligible_txs {
            self.mempool_state.entry(tx.sender_address).and_modify(|account| {
                account.nonce = tx.nonce;
            });
        }

        for tx in &eligible_txs {
            self.mempool_state.entry(tx.sender_address).or_default().nonce = tx.nonce;
        }
```
___
*[`crates/mempool/src/mempool.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/mempool/497#-O25RGdA2AGn0UbhH-fi:-O25RGdA2AGn0UbhH-fj:bjhxlce) ([raw file](https://github.com/starkware-libs/mempool/blob/3dac360ffe25ed27457103c372ba920e707c179e/crates/mempool/src/mempool.rs#L127)):*
> ```XML
>     fn is_duplicated_tx(&self, tx: &ThinTransaction) -> MempoolResult<()> {
>         if let Some(AccountState { nonce }) = self.mempool_state.get(&tx.sender_address) {
>             if *nonce >= tx.nonce {
> ```

Will this work?
`if nonce >= &tx.nonce {` 



_Code quote:_
```XML
*nonce >= tx.nonce
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/mempool/497#-O25Qklg6mVPYKRzW9qm:-O25VvY4DpanLlh2q6xB:bgbem63) ([raw file](https://github.com/starkware-libs/mempool/blob/3dac360ffe25ed27457103c372ba920e707c179e/crates/mempool/src/mempool.rs#L69)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Can you explain these loops?
</blockquote></details>

My bad. I deleted the first loop.

The second one that I kept goes over the popped transactions and updates the mempool state for these addresses. I used 'or_default' so if it didn't have the address, it would generate the default 'AccountState'.
___
*[`crates/mempool/src/mempool.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/mempool/497#-O25RGdA2AGn0UbhH-fi:-O25XJL45LfPCDTRapdo:b-sg6xz0) ([raw file](https://github.com/starkware-libs/mempool/blob/3dac360ffe25ed27457103c372ba920e707c179e/crates/mempool/src/mempool.rs#L127)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Will this work?
`if nonce >= &tx.nonce {`
</blockquote></details>

Both are okay,
I used your suggestion, as using references is preferred.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2PaDQtDt_zvnyYjdP4:-O2PaDQtDt_zvnyYjdP5:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L25)):*
> ```XML
>     // Transactions eligible for sequencing.
>     tx_queue: TransactionQueue,
>     // Represents the current state of the mempool during batch processing.
> ```





_Suggestion:_
```XML
block creation.
```
___
*[`crates/mempool/src/mempool.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2PaS6E43OqKFGOwBoV:-O2PaS6E43OqKFGOwBoW:bdhrm2m) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L62)):*
> ```XML
> 
>         // Update the mempool state with the new nonces.
>         for tx in eligible_txs.iter() {
> ```

Isn't `for x in iterable` sugar for this?



_Code quote:_
```XML
.iter()
```
___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2Pca5I-Ggvtv7Du1HJ:bxk3fui) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
> ```XML
>     }
> 
>     fn is_duplicated_tx(&self, tx: &ThinTransaction) -> MempoolResult<()> {
> ```

Is this related to this PR?



_Code quote:_
```XML
is_duplicated_tx
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2PaDQtDt_zvnyYjdP4:-O2PgXbK135woh22ozub:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L25)):*
> ```XML
>     // Transactions eligible for sequencing.
>     tx_queue: TransactionQueue,
>     // Represents the current state of the mempool during batch processing.
> ```

Done
___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2TWE8aB5c7F6AP7xij:b-tzd0t1) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this related to this PR?
</blockquote></details>

Yes, this PR adds the mempool_state and in `is_duplicate_tx` function it verifies that the transaction is valid using the mempool_state.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2TYlC98eKlxd9BoXm-:b-v95swt) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yes, this PR adds the mempool_state and in `is_duplicate_tx` function it verifies that the transaction is valid using the mempool_state.
</blockquote></details>

Doesn't this fall into the case we discussed, where `add_tx` input goes back?
Should we check the Q as well?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2U3w_QDUIN8_aGiOYn:bnwrl1w) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't this fall into the case we discussed, where `add_tx` input goes back?
Should we check the Q as well?
</blockquote></details>

This was added to prevent adding a transaction that was sent to the batcher using `get_txs` but not yet committed.

Check with whom?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2U5kjoB5JdvoRAPrF0:b-afy8z3) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This was added to prevent adding a transaction that was sent to the batcher using `get_txs` but not yet committed.

Check with whom?
</blockquote></details>

Check the queue. Okay, I understand it's not necessarily the same case. 
Let's add the other checks to this method as well.
___
*[`crates/mempool/src/mempool.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2U76bADGKXz721P9Ux:-O2U76bADGKXz721P9Uy:b6n5cdh) ([raw file](https://github.com/starkware-libs/mempool/blob/c67cc0afa435c3a7322d951778bbaf3713bfc97e/crates/mempool/src/mempool.rs#L126)):*
> ```XML
>         }
>         Ok(())
>     }
> ```

Would that work?



_Suggestion:_
```XML
fn should_insert(&self, tx: &ThinTransaction) -> bool {
    self.mempool_state
        .get(&tx.sender_address)
        .map_or(true, |AccountState { nonce }| nonce < &tx.nonce)
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2Uh7_Q8_3Fu6sAIxsr:bby6js9) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Check the queue. Okay, I understand it's not necessarily the same case. 
Let's add the other checks to this method as well.
</blockquote></details>

Sorry, I didn't get it :(
Which another check?
___
*[`crates/mempool/src/mempool.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2U76bADGKXz721P9Ux:-O2UKonW53T4gV1Eh4YP:bu8isp3) ([raw file](https://github.com/starkware-libs/mempool/blob/c67cc0afa435c3a7322d951778bbaf3713bfc97e/crates/mempool/src/mempool.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Would that work?
</blockquote></details>

Following our discussion, we decided to add another Error DuplicateNonce.
The code was updated.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2UiXRV6ZMz496O4xce:bq3k1uy) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sorry, I didn't get it :(
Which another check?
</blockquote></details>

There's #510, maybe we should add this check to `should_insert`.
___
*[`crates/mempool/src/mempool.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2U76bADGKXz721P9Ux:-O2UifEg-elSgiGA0NZg:bqq9xpw) ([raw file](https://github.com/starkware-libs/mempool/blob/c67cc0afa435c3a7322d951778bbaf3713bfc97e/crates/mempool/src/mempool.rs#L126)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Following our discussion, we decided to add another Error DuplicateNonce.
The code was updated.
</blockquote></details>

Given that we'll add more checks to this method, perhaps: `validate_input`?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497#-:-O2UtpQk12zXF2BCJ_u4:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2UsooH3qgxNDQtXiy6:b-6u7q88) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

There's #510, maybe we should add this check to `should_insert`.
</blockquote></details>

This is the same check :).
I added a TODO in that PR to use this method.
___
*[`crates/mempool/src/mempool.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2U76bADGKXz721P9Ux:-O2Ur7VJAwLbmj8jlEl4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c67cc0afa435c3a7322d951778bbaf3713bfc97e/crates/mempool/src/mempool.rs#L126)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Given that we'll add more checks to this method, perhaps: `validate_input`?
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/mempool/497#-O25RGdA2AGn0UbhH-fi:-O2V-ch1D-f1pN7YShjL:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/3dac360ffe25ed27457103c372ba920e707c179e/crates/mempool/src/mempool.rs#L127)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Both are okay,
I used your suggestion, as using references is preferred.
</blockquote></details>

Done

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2ZKdcJ9oepgz6cTJD4:b-ess0v7) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This is the same check :).
I added a TODO in that PR to use this method.
</blockquote></details>

Why do we need both PRs?
___
*[`crates/mempool/src/mempool.rs` line 122 at r9](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2ZKQ0s5snmoq5Q3tlg:-O2ZKQ0tDd4naoA9IFsq:b-9fzngj) ([raw file](https://github.com/starkware-libs/mempool/blob/44e4e3509cd8f6bfb51102b0f997c1f0fbdffe57/crates/mempool/src/mempool.rs#L122)):*
> ```XML
>     }
> 
>     fn validate_input(&self, tx: &ThinTransaction, account: Account) -> MempoolResult<()> {
> ```

Pass `MempoolInput`.



_Code quote:_
```XML
validate_input
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/mempool/497#-O2Pca5I-Ggvtv7Du1HI:-O2Zk_On4lRxVB0APLUI:b-omfnlo) ([raw file](https://github.com/starkware-libs/mempool/blob/071bd79560e054c0c9e6de7f6e141bdac567d0c6/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we need both PRs?
</blockquote></details>

Talked F2F.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/497)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request closed without merging**
