### PR TITLE
feat: post compilation size limit validation

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#298** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#348](https://github.com/starkware-libs/mempool/pull/348) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/348?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#384](https://github.com/starkware-libs/mempool/pull/384) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/384?utm_source=stack-comment-icon" target="_blank">Graphite</a>) 👈
* **#515** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/515?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/compilation.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GNGh24cHxQ7862uEq:-O1GNGh24cHxQ7862uEr:bxjrh6d) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L70)):*
> ```XML
>             starknet_api_contract_class.abi.len(),
>         )?;
>         Ok(class_info)
> ```

Consider moving this code outside the function, IMO validations and extra processing shouldn't be part of the compilation



_Code quote:_
```XML
        self.validate_casm_class(&casm_contract_class)?;
        self.validate_casm_class_size(&casm_contract_class)?;

        let hash_result = CompiledClassHash(casm_contract_class.compiled_class_hash());
        if hash_result != tx.compiled_class_hash {
            return Err(GatewayError::CompiledClassHashMismatch {
                supplied: tx.compiled_class_hash,
                hash_result,
            });
        }

        // Convert Casm contract class to Starknet contract class directly.
        let blockifier_contract_class =
            ContractClass::V1(ContractClassV1::try_from(casm_contract_class)?);
        let class_info = ClassInfo::new(
            &blockifier_contract_class,
            starknet_api_contract_class.sierra_program.len(),
            starknet_api_contract_class.abi.len(),
        )?;
        Ok(class_info)
```
___
*[`crates/gateway/src/compilation.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GLHDA1Cygk4t8ppZl:-O1GLHDA1Cygk4t8ppZm:b-brmbw7) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L119)):*
> ```XML
>                 max_bytecode_size: self.config.max_bytecode_size,
>             });
>         }
> ```

Move this check to before the raw class size (cheaper check)



_Code quote:_
```XML
        let bytecode_size = casm_contract_class.bytecode.len();
        if bytecode_size > self.config.max_bytecode_size {
            return Err(GatewayError::CasmBytecodeSizeTooLarge {
                bytecode_size,
                max_bytecode_size: self.config.max_bytecode_size,
            });
        }
```
___
*[`crates/gateway/src/compilation.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GL2715L3NExnt6UeR:-O1GL2715L3NExnt6UeS:b-s145qc) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L128)):*
> ```XML
>                 max_contract_class_object_size: self.config.max_raw_class_size,
>             });
>         }
> ```

Why do you repeat this code?



_Code quote:_
```XML
        let contract_class_object_size = serde_json::to_string(&casm_contract_class)
            .expect("Unexpected error serializing Casm contract class.")
            .len();
        if contract_class_object_size > self.config.max_raw_class_size {
            return Err(GatewayError::CasmContractClassObjectSizeTooLarge {
                contract_class_object_size,
                max_contract_class_object_size: self.config.max_raw_class_size,
            });
        }
```
___
*[`crates/gateway/src/compilation_config.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GLZzf6xu5NLyu_eTM:-O1GLZzf6xu5NLyu_eTN:bw5ncg9) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation_config.rs#L8)):*
> ```XML
> use validator::Validate;
> 
> #[derive(Clone, Debug, Default, Serialize, Deserialize, Validate, PartialEq)]
> ```

Set the correct default values



_Code quote:_
```XML
Default
```
___
*[`crates/gateway/src/compilation_test.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GMrlQ8P2nsyGN57xU:-O1GMrlQ8P2nsyGN57xV:b-4j19y1) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation_test.rs#L58)):*
> ```XML
> 
>     let gateway_compiler = GatewayCompiler { config: sierra_to_casm_compilation_config };
>     let result = gateway_compiler.compile_contract_class(&declare_tx);
> ```

Once you move the validations outside, you can save the casm instead of compiling as part of the test



_Code quote:_
```XML
    let declare_tx = match declare_tx() {
        RPCTransaction::Declare(declare_tx) => declare_tx,
        _ => panic!("Invalid transaction type"),
    };

    let gateway_compiler = GatewayCompiler { config: sierra_to_casm_compilation_config };
    let result = gateway_compiler.compile_contract_class(&declare_tx);
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GLHDA1Cygk4t8ppZl:-O1GVM8J4MswOyTvAf3P:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L119)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move this check to before the raw class size (cheaper check)
</blockquote></details>

Done.
___
*[`crates/gateway/src/compilation.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GL2715L3NExnt6UeR:-O1GUZqe88I3_WU31fP5:b-27v91l) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L128)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do you repeat this code?
</blockquote></details>

Bad merge conflict resolution. Sorry.
Done.
___
*[`crates/gateway/src/compilation_config.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GLZzf6xu5NLyu_eTM:-O1GWf2d8oDN2Lw3QvU_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation_config.rs#L8)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Set the correct default values
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`config/default_config.json` line 76 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Hh6W41BDC8Zt4EJ8s:-O1Hh6W41BDC8Zt4EJ8t:b-l9hdqo) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/config/default_config.json#L76)):*
> ```JSON
>     "privacy": "Public",
>     "value": 0
>   },
> ```

Why are these added in this PR?



_Code quote:_
```JSON
  "gateway_config.stateless_tx_validator_config.max_bytecode_size": {
    "description": "The maximum bytecode size allowed for a contract.",
    "privacy": "Public",
    "value": 0
  },
  "gateway_config.stateless_tx_validator_config.max_calldata_length": {
    "description": "Validates that a transaction has calldata length less than or equal to this value.",
    "privacy": "Public",
    "value": 0
  },
  "gateway_config.stateless_tx_validator_config.max_raw_class_size": {
    "description": "The maximum raw class size allowed for a contract.",
    "privacy": "Public",
    "value": 0
  },
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`config/default_config.json` line 21 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KwhVs62RlhWrFpEgf:-O1KwhVs62RlhWrFpEgg:bd625we) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/config/default_config.json#L21)):*
> ```JSON
>     "privacy": "Public",
>     "value": 4089446
>   },
> ```

why are these configs duplicated for both gateway_config and stateless_tx_validator_config ?



_Code quote:_
```JSON
  "gateway_config.compiler_config.max_bytecode_size": {
    "description": "The maximum bytecode size allowed for a contract.",
    "privacy": "Public",
    "value": 81920
  },
  "gateway_config.compiler_config.max_raw_class_size": {
    "description": "The maximum raw class size allowed for a contract.",
    "privacy": "Public",
    "value": 4089446
  },
```
___
*[`crates/gateway/src/compilation_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Kv09ZAbZLekKD2K-h:-O1Kv09ZAbZLekKD2K-i:brn3l3f) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/compilation_test.rs#L110)):*
> ```XML
> 
>     let class_info = GatewayCompiler {
>         config: GatewayCompilerConfig { max_bytecode_size: 4800, max_raw_class_size: 111037 },
> ```

why did you choose these numbers? consider defining a const (same below)



_Code quote:_
```XML
max_bytecode_size: 4800, max_raw_class_size: 111037
```
___
*[`crates/gateway/src/gateway_test.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Kudb8Bwt7dwqfrdh2:-O1Kudb97tpHaUEug96C:b-jmii05) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/gateway_test.rs#L57)):*
> ```XML
>         }),
>         gateway_compiler: GatewayCompiler {
>             config: GatewayCompilerConfig { max_bytecode_size: 10000, max_raw_class_size: 1000000 },
> ```

why these exact numbers? do they have a meaning?
maybe define a const



_Code quote:_
```XML
max_bytecode_size: 10000, max_raw_class_size: 1000000
```
___
*[`crates/gateway/src/gateway_test.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KumDD4sHhRmkx8GwG:-O1KumDE7GQzuL0pAM5F:b-l8l7r9) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/gateway_test.rs#L121)):*
> ```XML
>                 config: GatewayCompilerConfig {
>                     max_bytecode_size: 4800,
>                     max_raw_class_size: 111037,
> ```

same question



_Code quote:_
```XML
                    max_bytecode_size: 4800,
                    max_raw_class_size: 111037,
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KurFdBYB59eQQhfoJ:-O1KurFdBYB59eQQhfoK:bb7od0r) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/stateful_transaction_validator_test.rs#L88)):*
> ```XML
>                 config: GatewayCompilerConfig {
>                     max_bytecode_size: 4800,
>                     max_raw_class_size: 111037,
> ```

same



_Code quote:_
```XML
                    max_bytecode_size: 4800,
                    max_raw_class_size: 111037,
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 6 of 9 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`config/default_config.json` line 21 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KwhVs62RlhWrFpEgf:-O1Lhn2B1poE_9DuAqOf:bufox53) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/config/default_config.json#L21)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why are these configs duplicated for both gateway_config and stateless_tx_validator_config ?
</blockquote></details>

If these are different config , I think they should have different names.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 2 of 9 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`config/default_config.json` line 21 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KwhVs62RlhWrFpEgf:-O1WdZei6osWwWBPpncF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/config/default_config.json#L21)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

If these are different config , I think they should have different names.
</blockquote></details>

Done.
___
*[`config/default_config.json` line 76 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Hh6W41BDC8Zt4EJ8s:-O1Wdaf53Lra_vWKcwT3:b-a1j74n) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/config/default_config.json#L76)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why are these added in this PR?
</blockquote></details>

No longer relevant. (This is already merged).
___
*[`crates/gateway/src/compilation.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GNGh24cHxQ7862uEq:-O1GVT1V3NByw2AZc_w_:b-jk74jf) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation.rs#L70)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider moving this code outside the function, IMO validations and extra processing shouldn't be part of the compilation
</blockquote></details>

Handled in #439.
___
*[`crates/gateway/src/compilation_test.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1GMrlQ8P2nsyGN57xU:-O1Wd-4v3Ix-FM6eiLgS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/47964cf0fd837df1cabb7c168aeae60f6afd2f39/crates/gateway/src/compilation_test.rs#L58)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Once you move the validations outside, you can save the casm instead of compiling as part of the test
</blockquote></details>

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Kv09ZAbZLekKD2K-h:-O1Wbw3kDe14DIHWmXsE:b-cxchxo) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/compilation_test.rs#L110)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why did you choose these numbers? consider defining a const (same below)
</blockquote></details>

No longer relevant.
___
*[`crates/gateway/src/gateway_test.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1Kudb8Bwt7dwqfrdh2:-O1WbO5w4cbgfuucwrsC:b747wln) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/gateway_test.rs#L57)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why these exact numbers? do they have a meaning?
maybe define a const
</blockquote></details>

Done. The config is simplified now.

(I would have simplified `StatefulTransactionValidatorConfig`, but here, `create_for_testing` has a meaning). 
___
*[`crates/gateway/src/gateway_test.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KumDD4sHhRmkx8GwG:-O1WacX94dDAAxDh1jJ3:b-cxchxo) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/gateway_test.rs#L121)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same question
</blockquote></details>

No longer relevant.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1KurFdBYB59eQQhfoJ:-O1WaYq862pg17tg34NV:b-cxchxo) ([raw file](https://github.com/starkware-libs/mempool/blob/05f794a61ba0a4fdc1da6def69ee6e7a762f3553/crates/gateway/src/stateful_transaction_validator_test.rs#L88)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same
</blockquote></details>

No longer relevant.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r4, 1 of 7 files at r9, 2 of 5 files at r11, 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/compilation_test.rs` line 79 at r12](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1lACiM1RHdg7JDvBXN:-O1lACiM1RHdg7JDvBXO:b-von3ie) ([raw file](https://github.com/starkware-libs/mempool/blob/7c25dc3edf30239bfe8c200ada352535eca4a193/crates/gateway/src/compilation_test.rs#L79)):*
> ```XML
>         )
>     }
> }
> ```

these two cases has only 2 shared lines of code and a lot of code to distinguish between the different cases.
I think it will be more readable to separate to 2 different tests.



_Code quote:_
```XML
#[rstest]
#[case::bytecode_size(
    GatewayCompilerConfig { max_casm_bytecode_size: 1, ..Default::default() },
    GatewayError::CasmBytecodeSizeTooLarge { bytecode_size: 4800, max_bytecode_size: 1 }
)]
#[case::raw_class_size(
    GatewayCompilerConfig { max_raw_casm_class_size: 1, ..Default::default() },
    GatewayError::CasmContractClassObjectSizeTooLarge {
        contract_class_object_size: 111037, max_contract_class_object_size: 1
    }
)]
fn test_compile_contract_class_size_validation(
    casm_contract_class: CasmContractClass,
    #[case] sierra_to_casm_compilation_config: GatewayCompilerConfig,
    #[case] expected_error: GatewayError,
) {
    let gateway_compiler = GatewayCompiler { config: sierra_to_casm_compilation_config };
    let result = gateway_compiler.validate_casm_class_size(&casm_contract_class);
    if let GatewayError::CasmBytecodeSizeTooLarge {
        bytecode_size: expected_bytecode_size, ..
    } = expected_error
    {
        assert_matches!(
            result.unwrap_err(),
            GatewayError::CasmBytecodeSizeTooLarge { bytecode_size, .. }
            if bytecode_size == expected_bytecode_size
        )
    } else if let GatewayError::CasmContractClassObjectSizeTooLarge {
        contract_class_object_size: expected_contract_class_object_size,
        ..
    } = expected_error
    {
        assert_matches!(
            result.unwrap_err(),
            GatewayError::CasmContractClassObjectSizeTooLarge { contract_class_object_size, .. }
            if contract_class_object_size == expected_contract_class_object_size
        )
    }
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation_test.rs` line 79 at r12](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1lACiM1RHdg7JDvBXN:-O1liG-61VIMoBtrTWuq:bb2mlta) ([raw file](https://github.com/starkware-libs/mempool/blob/7c25dc3edf30239bfe8c200ada352535eca4a193/crates/gateway/src/compilation_test.rs#L79)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

these two cases has only 2 shared lines of code and a lot of code to distinguish between the different cases.
I think it will be more readable to separate to 2 different tests.
</blockquote></details>

Done. (The exact numbers are not relevant for the test).

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r9, 1 of 5 files at r11, 1 of 4 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r4, 1 of 7 files at r9, 1 of 5 files at r11, 1 of 4 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298#-:-O1zV43c8_wghSyFhGwZ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware)

___
*[`config/mempool_default_config.json` line 13 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zOWTN-w_5TJYGAYaw:-O1zOWTO3jMn4trBxwEb:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/config/mempool_default_config.json#L13)):*
> ```JSON
>   },
>   "gateway_config.compiler_config.max_casm_bytecode_size": {
>     "description": "Limitation of contract bytecode size",
> ```





_Suggestion:_
```JSON
"Limitation of contract bytecode size."
```
___
*[`config/mempool_default_config.json` line 18 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zOYFg7Obi3ATdrEDw:-O1zOYFg7Obi3ATdrEDx:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/config/mempool_default_config.json#L18)):*
> ```JSON
>   },
>   "gateway_config.compiler_config.max_raw_casm_class_size": {
>     "description": "Limitation of contract class object size",
> ```





_Suggestion:_
```JSON
"Limitation of contract class object size."
```
___
*[`crates/gateway/src/compilation.rs` line 76 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zQGOxCOzk3UAo5U5p:-O1zQGOyAG-LfkF57GVX:bs9l037) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/compilation.rs#L76)):*
> ```XML
> 
>     // TODO(Arni): Add test.
>     fn validate_casm_class(&self, contract_class: &CasmContractClass) -> Result<(), GatewayError> {
> ```

Please add documentation for this function. 
Now with the addition of `validate_casm_class_size` it can be confusing.



_Code quote:_
```XML
fn validate_casm_class
```
___
*[`crates/gateway/src/config.rs` line 322 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zUMpfCpAtdYNF-RsC:-O1zUMpfCpAtdYNF-RsD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/config.rs#L322)):*
> ```XML
>                 "max_casm_bytecode_size",
>                 &self.max_casm_bytecode_size,
>                 "Limitation of contract bytecode size",
> ```





_Suggestion:_
```XML
"Limitation of contract bytecode size."
```
___
*[`crates/gateway/src/config.rs` line 328 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zUOQ-DiKxhkiCHvuv:-O1zUOQ-DiKxhkiCHvuw:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/config.rs#L328)):*
> ```XML
>                 "max_raw_casm_class_size",
>                 &self.max_raw_casm_class_size,
>                 "Limitation of contract class object size",
> ```





_Suggestion:_
```XML
"Limitation of contract class object size."
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`config/mempool_default_config.json` line 13 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zOWTN-w_5TJYGAYaw:-O1zbh3DEhZ5UTcDJ-UG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/config/mempool_default_config.json#L13)):*
> ```JSON
>   },
>   "gateway_config.compiler_config.max_casm_bytecode_size": {
>     "description": "Limitation of contract bytecode size",
> ```

Done.
___
*[`config/mempool_default_config.json` line 18 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zOYFg7Obi3ATdrEDw:-O1zbhTZDOSk0ERaB2C-:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/config/mempool_default_config.json#L18)):*
> ```JSON
>   },
>   "gateway_config.compiler_config.max_raw_casm_class_size": {
>     "description": "Limitation of contract class object size",
> ```

Done.
___
*[`crates/gateway/src/compilation.rs` line 76 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zQGOxCOzk3UAo5U5p:-O1zdIBZ3ryGNiH2tLXE:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/compilation.rs#L76)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add documentation for this function. 
Now with the addition of `validate_casm_class_size` it can be confusing.
</blockquote></details>

Done.
___
*[`crates/gateway/src/config.rs` line 322 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zUMpfCpAtdYNF-RsC:-O1zdyE9D9fbCvcL70Bv:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/config.rs#L322)):*
> ```XML
>                 "max_casm_bytecode_size",
>                 &self.max_casm_bytecode_size,
>                 "Limitation of contract bytecode size",
> ```

Done.
___
*[`crates/gateway/src/config.rs` line 328 at r13](https://reviewable.io/reviews/starkware-libs/mempool/298#-O1zUOQ-DiKxhkiCHvuv:-O1zdytrE5hJuLWQcXxS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b705b7eb8bc726f5c5a66a47331f171f13978693/crates/gateway/src/config.rs#L328)):*
> ```XML
>                 "max_raw_casm_class_size",
>                 &self.max_raw_casm_class_size,
>                 "Limitation of contract class object size",
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298#-:-O2TBKzY5c56XckfNzLz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r14, 2 of 3 files at r15, 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/298#-:-O2cmWmQ1xB-nRluhfuY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request closed without merging**
