### PR TITLE
feat: serialize config for stateless transaction validator config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#126** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#114](https://github.com/starkware-libs/mempool/pull/114) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/mempool/126#-NxufLYi0hMBDZCscZyS:-NxufLYi0hMBDZCscZyT:b34p0mk) ([raw file](https://github.com/starkware-libs/mempool/blob/6699b9662b38a60a020d112dcb5ed4ca4cefbf83/crates/gateway/src/stateless_transaction_validator.rs#L57)):*
> ```XML
>         ])
>     }
> }
> ```

If we reorganized the folders, I would put this code in a separate file called `config.rs` under the folder `stateless transaction validator`.



_Code quote:_
```XML
#[derive(Clone, Debug, Default, Serialize, Deserialize, Validate, PartialEq)]
pub struct StatelessTransactionValidatorConfig {
    // If true, validates that the resource bounds are not zero.
    pub validate_non_zero_l1_gas_fee: bool,
    pub validate_non_zero_l2_gas_fee: bool,

    pub max_calldata_length: usize,
    pub max_signature_length: usize,
}

impl SerializeConfig for StatelessTransactionValidatorConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        BTreeMap::from_iter([
            ser_param(
                "validate_non_zero_l1_gas_fee",
                &self.validate_non_zero_l1_gas_fee,
                "If true, validates transactions have non zero L1 resource bounds.",
                ParamPrivacyInput::Public,
            ),
            ser_param(
                "validate_non_zero_l2_gas_fee",
                &self.validate_non_zero_l2_gas_fee,
                "If true, validates transactions have non zero L2 resource bounds.",
                ParamPrivacyInput::Public,
            ),
            ser_param(
                "max_signature_length",
                &self.max_signature_length,
                "Validates transactions have calldata length less than or equal to this value.",
                ParamPrivacyInput::Public,
            ),
            ser_param(
                "max_calldata_length",
                &self.max_calldata_length,
                "Validates transactions have signature length less than or equal to this value.",
                ParamPrivacyInput::Public,
            ),
        ])
    }
}
```

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@lev-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126#-:-NxugM8YAARN8EFlAar5:bw1gi4r)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware and @lev-starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/mempool/126#-NxunxjM80IGPbjPN8dW:-NxunxjM80IGPbjPN8dX:bz71w0e) ([raw file](https://github.com/starkware-libs/mempool/blob/6699b9662b38a60a020d112dcb5ed4ca4cefbf83/crates/gateway/src/stateless_transaction_validator.rs#L34)):*
> ```XML
>                 "validate_non_zero_l1_gas_fee",
>                 &self.validate_non_zero_l1_gas_fee,
>                 "If true, validates transactions have non zero L1 resource bounds.",
> ```

validates that a transaction has

same for the the other descriptions



_Code quote:_
```XML
validates transactions
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @lev-starkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/mempool/126#-NxunxjM80IGPbjPN8dW:-Nxv1yzoAulfE1eJ9xyK:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6699b9662b38a60a020d112dcb5ed4ca4cefbf83/crates/gateway/src/stateless_transaction_validator.rs#L34)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

validates that a transaction has

same for the the other descriptions
</blockquote></details>

Done.

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/mempool/126#-NxwPA23Aa56t412x6Uk:-NxwPA23Aa56t412x6Ul:bwt74l5) ([raw file](https://github.com/starkware-libs/mempool/blob/6d035a0a61b99484280f0a83765a0a1ac174edb3/crates/gateway/src/config_test.rs#L93)):*
> ```XML
>     let fix = true;
>     test_valid_config_body(expected_config, file_path, fix);
> }
> ```

I think it will be better:

fn test_or_fix_valid_stateless_transaction_validator_config(bool fix) {
    let expected_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: false,
        max_calldata_length: 10,
        max_signature_length: 0,
    };
    let file_path = get_config_file_path(STATELESS_TRANSACTION_VALIDATOR_CONFIG);
    test_valid_config_body(expected_config, file_path, fix);
}

#[test]
/// Read the stateless transaction validator config file and validate its content.
fn test_valid_stateless_transaction_validator_config() {
    test_or_fix_valid_stateless_transaction_validator_config(false);
}

#[test]
#[ignore]
/// Fix the config file for test_valid_stateless_transaction_validator_config.
/// Run with 'cargo test -- --ignored'.
fn fix_test_valid_stateless_transaction_validator_config() {
     test_or_fix_valid_stateless_transaction_validator_config(true);
}



_Code quote:_
```XML
#[test]
/// Read the stateless transaction validator config file and validate its content.
fn test_valid_stateless_transaction_validator_config() {
    let expected_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: false,
        max_calldata_length: 10,
        max_signature_length: 0,
    };
    let file_path = get_config_file_path(STATELESS_TRANSACTION_VALIDATOR_CONFIG);
    let fix = false;
    test_valid_config_body(expected_config, file_path, fix);
}

#[test]
#[ignore]
/// Fix the config file for test_valid_stateless_transaction_validator_config.
/// Run with 'cargo test -- --ignored'.
fn fix_test_valid_stateless_transaction_validator_config() {
    let expected_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: false,
        max_calldata_length: 10,
        max_signature_length: 0,
    };
    let file_path = get_config_file_path(STATELESS_TRANSACTION_VALIDATOR_CONFIG);
    let fix = true;
    test_valid_config_body(expected_config, file_path, fix);
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @lev-starkware and @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/mempool/126#-NxwPA23Aa56t412x6Uk:-NxwTmDq3ZuOP56bacT2:b7rymp0) ([raw file](https://github.com/starkware-libs/mempool/blob/6d035a0a61b99484280f0a83765a0a1ac174edb3/crates/gateway/src/config_test.rs#L93)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I think it will be better:

fn test_or_fix_valid_stateless_transaction_validator_config(bool fix) {
    let expected_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: false,
        max_calldata_length: 10,
        max_signature_length: 0,
    };
    let file_path = get_config_file_path(STATELESS_TRANSACTION_VALIDATOR_CONFIG);
    test_valid_config_body(expected_config, file_path, fix);
}

#[test]
/// Read the stateless transaction validator config file and validate its content.
fn test_valid_stateless_transaction_validator_config() {
    test_or_fix_valid_stateless_transaction_validator_config(false);
}

#[test]
#[ignore]
/// Fix the config file for test_valid_stateless_transaction_validator_config.
/// Run with 'cargo test -- --ignored'.
fn fix_test_valid_stateless_transaction_validator_config() {
     test_or_fix_valid_stateless_transaction_validator_config(true);
}
</blockquote></details>

I have another PR that refactors around that area: #127.
Let us not block on it here. (the same is true for `test_valid_network_config`).

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126#-:-NxwWCOh8nhj1EXk1_0s:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by lev-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/126)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
