### PR TITLE
feat: use config for stateless validator config sierra version

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/244)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/244?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#244** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/244?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#226** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/226?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#225** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/225?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/244)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`config/default_config.json` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhM0f3DaBfGeu3WVl:-O-VhM0f3DaBfGeu3WVm:bxcgavh) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L53)):*
> ```JSON
>   },
>   "gateway_config.stateless_tx_validator_config.max_calldata_length": {
>     "description": "Validates that a transaction has signature length less than or equal to this value.",
> ```

calldata



_Code quote:_
```JSON
signature
```
___
*[`config/default_config.json` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhXCP4Y9dEjdpWe3K:-O-VhXCQ6AqRlbqHDPBj:b-nqctr3) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L60)):*
> ```JSON
>     "description": "The major version of the configuration.",
>     "privacy": "Public",
>     "value": 18446744073709551615
> ```

can you explain how this field is set?
and the other fields as well.



_Code quote:_
```JSON
18446744073709551615
```
___
*[`config/default_config.json` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhOnGCf6fZJaNaTzE:-O-VhOnGCf6fZJaNaTzF:b38wv2r) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L72)):*
> ```JSON
>     "value": 18446744073709551615
>   },
>   "gateway_config.stateless_tx_validator_config.max_signature_length": {
> ```

signature



_Code quote:_
```JSON
signature
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VniiP3-WhriUBfIKX:-O-VniiQAYNEg2eSMwY2:bjrfdc0) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/crates/gateway/src/stateless_transaction_validator_test.rs#L242)):*
> ```XML
>     StatelessTransactionValidatorError::UnsupportedSierraVersion {
>             version: VersionId { major: 1, minor: 6, patch: 0 },
>             min_version: MIN_SIERRA_VERSION.into(),
> ```

Can we work with only one type of VersionId, either the cairo-lang one or our own defined one?



_Code quote:_
```XML
into()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/244)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`config/default_config.json` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhM0f3DaBfGeu3WVl:-O-VxHoO9H1V8Qh8eyIm:b778xrv) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L53)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

calldata
</blockquote></details>

Covered in #245. Good catch!
___
*[`config/default_config.json` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhXCP4Y9dEjdpWe3K:-O-VuRJZ41ShCqnHDx-x:b22ljpj) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L60)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you explain how this field is set?
and the other fields as well.
</blockquote></details>

Are you asking about `usize::MAX` from the file `config.rs`.

Or about the command: `cargo run --bin dump_config -q`? (See the fix file: `crates/mempool_node/src/bin/dump_config.rs`).
___
*[`config/default_config.json` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VhOnGCf6fZJaNaTzE:-O-VxLDT64Ny4W-nhjj8:b778xrv) ([raw file](https://github.com/starkware-libs/mempool/blob/968676114da53f9feded7bcfb09decaeb6f888e4/config/default_config.json#L72)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

signature
</blockquote></details>

Covered in #245. Good catch!

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/mempool/244#-O-VniiP3-WhriUBfIKX:-O-WR8oO7IIuM3B2ttX6:b-yxflnh) ([raw file](https://github.com/starkware-libs/mempool/blob/ba89a8047d6e846794db12c675bf5d3c484cb0c0/crates/gateway/src/stateless_transaction_validator_test.rs#L242)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can we work with only one type of VersionId, either the cairo-lang one or our own defined one?
</blockquote></details>

Done. Now in #226.

**Comment by ArniStarkware** [comment]
This PR is closed and replaced with a new PR. Now #226 has parts of this PR. This is thanks to @Yael-Starkware's excellent comment.

**Pull request closed without merging**
