### PR TITLE
feat: add Mempool and its API

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/mempool/43#-NvByeNd1L8h01GxmkBY:-NvByeNd1L8h01GxmkBZ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/62b8414cd7da3bbe3e0d8b25dc9c8bd79c81bee7/crates/mempool/src/mempool.rs#L24)):*
> ```XML
> 
>     /// Update the mempool's internal state according to the committed block's transactions.
>     /// This method also resolves nonce gaps and updates account balances.
> ```





_Suggestion:_
```XML
/// This method also updates internal state (resolves nonce gaps, updates account balances).
```

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43#-:-NveYe7oCEhvMUNv9Dyz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
