### PR TITLE
refactor: return an error from server in case request deserialization…

### PR DESCRIPTION
**Pull request by uriel-starkware**
… fails

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BhrolBDQEFJZifrgy:-O1BhrolBDQEFJZifrgz:b-8kioda) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L101)):*
> ```XML
> 
>         match http_response.status() {
>             StatusCode::OK => {
> ```

I assume the server code adds defaults to using `StatusCode::OK` in its response messages. Please make it explicit.



_Code quote:_
```XML
StatusCode::OK => {
```
___
*[`crates/mempool_infra/src/component_client.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BiAcS4Ce0vJnEjjp4:-O1BiAcS4Ce0vJnEjjp5:btl5b45) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L132)):*
> ```XML
>     async fn consume_http_body_bytes(response: HyperResponse<Body>) -> ClientResult<Bytes> {
>         to_bytes(response.into_body()).await.map_err(|_| ClientError::HttpBodyConsumptionFailure)
>     }
> ```

These functions should be defined outside the scope of the client code. Then you wouldn't have to use `Self::` to call them.



_Code quote:_
```XML
    async fn handle_bad_request(response: HyperResponse<Body>) -> ClientError {
        if let Some(value) = response.headers().get(X_INTERNAL_ERROR_REASON_HEADER) {
            match value.to_str() {
                Ok(DESERIALIZAION_FAILED_REASON) => {
                    let body_bytes = match Self::consume_http_body_bytes(response).await {
                        Ok(body_bytes) => body_bytes,
                        Err(e) => return ClientError::RequestDeserializationFailure(e.to_string()),
                    };
                    ClientError::RequestDeserializationFailure(
                        String::from_utf8(body_bytes.into()).unwrap_or("".to_string()),
                    )
                }
                Ok(reason) => ClientError::BadRequestUnexpectedReason(reason.to_string()),
                Err(e) => ClientError::BadRequestParseReasonFailure(e),
            }
        } else {
            ClientError::BadRequestReasonNotFound
        }
    }

    async fn consume_http_body_bytes(response: HyperResponse<Body>) -> ClientResult<Bytes> {
        to_bytes(response.into_body()).await.map_err(|_| ClientError::HttpBodyConsumptionFailure)
    }
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BglJwDZTaFO9Dfon9:-O1BglJx7sP153sx9w0F:b58csha) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_definitions.rs#L20)):*
> ```XML
> pub const APPLICATION_OCTET_STREAM: &str = "application/octet-stream";
> pub const X_INTERNAL_ERROR_REASON_HEADER: &str = "x-internal-error-reason";
> pub const DESERIALIZAION_FAILED_REASON: &str = "Deserialization failed";
> ```

Please change to `DESERIALIZAION_FAILURE`



_Code quote:_
```XML
DESERIALIZAION_FAILED_REASON
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BlR5J8q6KrQss_X9m:-O1BlR5J8q6KrQss_X9n:bubq1j0) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L107)):*
> ```XML
>             StatusCode::BAD_REQUEST => Err(Self::handle_bad_request(http_response).await),
>             status_code => Err(ClientError::UnexpectedStatusCode(status_code)),
>         }
> ```

The current structure has two levels of "indentation": check the status code, and then per status code, check the deser. This results in multiple different potential errors, which I'd like to reduce.

Please consider the following suggestion: 
1. extract status code
2. try deser

If status code is `OK` + deser success then return success
Otherwise return a ClientError::ResponseError(StatusCode,deser_result)



_Code quote:_
```XML
        match http_response.status() {
            StatusCode::OK => {
                let body_bytes = Self::consume_http_body_bytes(http_response).await?;
                deserialize(&body_bytes).map_err(ClientError::ResponseDeserializationFailure)
            }
            StatusCode::BAD_REQUEST => Err(Self::handle_bad_request(http_response).await),
            status_code => Err(ClientError::UnexpectedStatusCode(status_code)),
        }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BiAcS4Ce0vJnEjjp4:-O1BmtTMB7P9CJB7taob:b-peynbh) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L132)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These functions should be defined outside the scope of the client code. Then you wouldn't have to use `Self::` to call them.
</blockquote></details>

Also, can these two functions have more similar names and signatures (i.e., return types)?

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BhrolBDQEFJZifrgy:-O1BtVEkEimSTnrutb64:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L101)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I assume the server code adds defaults to using `StatusCode::OK` in its response messages. Please make it explicit.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BlR5J8q6KrQss_X9m:-O1C1ptI0Ml54YfMMIT3:b-fjrmnl) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L107)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The current structure has two levels of "indentation": check the status code, and then per status code, check the deser. This results in multiple different potential errors, which I'd like to reduce.

Please consider the following suggestion: 
1. extract status code
2. try deser

If status code is `OK` + deser success then return success
Otherwise return a ClientError::ResponseError(StatusCode,deser_result)
</blockquote></details>

Done (more or less)
___
*[`crates/mempool_infra/src/component_client.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BiAcS4Ce0vJnEjjp4:-O1BmQ7k9i5xC7FiqJhF:b-t5py8d) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_client.rs#L132)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Also, can these two functions have more similar names and signatures (i.e., return types)?
</blockquote></details>

I removed the second func and changed the first one to return just the reason
___
*[`crates/mempool_infra/src/component_definitions.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1BglJwDZTaFO9Dfon9:-O1Bu--04ttdQBOCq99q:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5c10a83ab8a97f41149785fb41f5cf35f5ad6f21/crates/mempool_infra/src/component_definitions.rs#L20)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `DESERIALIZAION_FAILURE`
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CMdA39evu09p8GMwt:-O1CMdA39evu09p8GMwu:b-fop4gq) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L130)):*
> ```XML
>             Err(error) => HyperResponse::builder()
>                 .status(StatusCode::BAD_REQUEST)
>                 .header(X_INTERNAL_ERROR_REASON_HEADER, DESERIALIZAION_FAILURE)
> ```

Thinking about this again, it seems sending this data as presented adds unnecessary redundancy: the header key `X_INTERNAL_ERROR_REASON_HEADER` has only one possible value `DESERIALIZAION_FAILURE`, which laters makes matching against its value to be cumbersome.

Can we drop the value entirely, just send the key, and later only check if the key exists?



_Code quote:_
```XML
.header(X_INTERNAL_ERROR_REASON_HEADER, DESERIALIZAION_FAILURE)
```
___
*[`crates/mempool_infra/src/component_server.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CHAoA6smCr3ccyXIK:-O1CHAoA6smCr3ccyXIL:b66qefl) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L133)):*
> ```XML
>                 .body(Body::from(error.to_string())),
>         }
>         .expect("Response builidng should succeed");
> ```

Please fix the typo 



_Code quote:_
```XML
builidng
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CNH1H-mn1KfTZoLBm:-O1CNH1H-mn1KfTZoLBn:b-d3gsql) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L130)):*
> ```XML
>                 format!("Reason: {}", reason)
>             }
>             Ok(reason) => format!("Unexpected reason found: {}", reason),
> ```

My suggestion below should enable removing this line



_Code quote:_
```XML
Ok(reason) => format!("Unexpected reason found: {}", reason),
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CNRcrCVUuy5nl2RBD:-O1CNRcrCVUuy5nl2RBE:b7pqzc4) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L119)):*
> ```XML
> 
> async fn get_bad_request_reason(response: HyperResponse<Body>) -> String {
>     if let Some(value) = response.headers().get(X_INTERNAL_ERROR_REASON_HEADER) {
> ```

According to the suggestion below: this will be a simpler check of seeing if the `get` returns `Some` or `None`. 



_Code quote:_
```XML
if let Some(value) = response.headers().get(X_INTERNAL_ERROR_REASON_HEADER) {
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CMdA39evu09p8GMwt:-O1CNoh_AJcKF7dptcaz:b-4dk0lp) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L130)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Thinking about this again, it seems sending this data as presented adds unnecessary redundancy: the header key `X_INTERNAL_ERROR_REASON_HEADER` has only one possible value `DESERIALIZAION_FAILURE`, which laters makes matching against its value to be cumbersome.

Can we drop the value entirely, just send the key, and later only check if the key exists?
</blockquote></details>

Even more thought into this: wouldn't just the `status code` be sufficient here?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 5 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CO5REDCIu2Dlhhegk:-O1CO5REDCIu2Dlhhegl:bmrih3g) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L99)):*
> ```XML
>         let http_response =
>             self.client.request(http_request).await.map_err(ClientError::CommunicationFailure)?;
> ```

Here's my finalized suggestion:
1. for server deser errors, send solely the `bad_request` status code and the error returned in the message body (convert the error to string, as the code already does).
2. add a generic fn in type T that takes a body and tries deserializing it into type T. This should return a ClientResult type.
3. in the client code match the status code -- 
    3.1 if its `ok` call the aforementioned function with type `Response`, and return `Ok(...)`
    3.2 else call the aforementioned function with type `String`, and return `Err(ClientError::ResponseError(status code, string)`

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: all files reviewed, 6 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CPqrR8WyMdvcf_R-d:-O1CPqrR8WyMdvcf_R-e:b-bqiar7) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L168)):*
> ```XML
>     ResponseDeserializationFailure(Box<ErrorKind>),
>     #[error("Got status code: {0}, with error: {1}")]
>     ResponseError(StatusCode, String),
> ```

Please alphabetize these :pray: 



_Code quote:_
```XML
    #[error("Communication error: {0}")]
    CommunicationFailure(HyperError),
    #[error("Could not parse the response: {0}")]
    ResponseParsingFailure(HyperError),
    #[error("Got an unexpected response type.")]
    UnexpectedResponse,
    #[error("Could not deserialize server response: {0}")]
    ResponseDeserializationFailure(Box<ErrorKind>),
    #[error("Got status code: {0}, with error: {1}")]
    ResponseError(StatusCode, String),
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CO5REDCIu2Dlhhegk:-O1CYjhE0shio9w_b_5m:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L99)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Here's my finalized suggestion:
1. for server deser errors, send solely the `bad_request` status code and the error returned in the message body (convert the error to string, as the code already does).
2. add a generic fn in type T that takes a body and tries deserializing it into type T. This should return a ClientResult type.
3. in the client code match the status code -- 
    3.1 if its `ok` call the aforementioned function with type `Response`, and return `Ok(...)`
    3.2 else call the aforementioned function with type `String`, and return `Err(ClientError::ResponseError(status code, string)`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CNRcrCVUuy5nl2RBD:-O1CYl5W4BlooOpbyovI:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L119)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

According to the suggestion below: this will be a simpler check of seeing if the `get` returns `Some` or `None`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CNH1H-mn1KfTZoLBm:-O1CYmSs5UN6zyvS6EwJ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L130)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

My suggestion below should enable removing this line
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CPqrR8WyMdvcf_R-d:-O1CZn473v0GhCpUxAU2:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_client.rs#L168)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please alphabetize these :pray:
</blockquote></details>

Done.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CHAoA6smCr3ccyXIK:-O1G5pCU4XkGyONhrhjm:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L133)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please fix the typo
</blockquote></details>

Done.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CMdA39evu09p8GMwt:-O1G5vaC36aWJgbVcX7L:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L130)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Even more thought into this: wouldn't just the `status code` be sufficient here?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 142 at r3](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1G5cWP2L3EaRBIzRn2:-O1G5cWP2L3EaRBIzRn3:b-v1wkn9) ([raw file](https://github.com/starkware-libs/mempool/blob/174274cf79881ad178c4343013ffbf1c785894a5/crates/mempool_infra/src/component_client.rs#L142)):*
> ```XML
>     ResponseParsingFailure(HyperError),
>     #[error("Got status code: {0}, with server error: {1}")]
>     ServerError(StatusCode, ServerError),
> ```

Is there a way to use the `#[from]` syntax here to create the `ServerError` variant?

Example from the gateway code:

```
#[error(transparent)]

CompilationError(#\[from\] CompilationUtilError),
```



_Code quote:_
```XML
    #[error("Got status code: {0}, with server error: {1}")]
    ServerError(StatusCode, ServerError),
```
___
*[`crates/mempool_infra/src/component_server.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1CHAoA6smCr3ccyXIK:-O1FyeqdBtr3TyBJ3uX1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9bb00d9c17fd3fe18d30f7dce3f00475dce3e443/crates/mempool_infra/src/component_server.rs#L133)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please fix the typo
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 145 at r3](https://reviewable.io/reviews/starkware-libs/mempool/379#-O1G6B6d6_xgT5LkCXn7:-O1G6B6d6_xgT5LkCXn8:b5ax0se) ([raw file](https://github.com/starkware-libs/mempool/blob/174274cf79881ad178c4343013ffbf1c785894a5/crates/mempool_infra/src/component_server.rs#L145)):*
> ```XML
>     #[error("Could not deserialize client request: {0}")]
>     RequestDeserializationFailure(String),
> }
> ```

Although generated by the server, this struct is used by the client as well. Please move it to a common place, e.g., `component_definitions`



_Code quote:_
```XML
#[derive(Debug, Error, Deserialize, Serialize)]
pub enum ServerError {
    #[error("Could not deserialize client request: {0}")]
    RequestDeserializationFailure(String),
}
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379#-:-O1GHNQDA64qv_bPjlCZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
