### PR TITLE
feat: implement thin transaction converter

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkBTC2-NZyGAn533R:-NyEkBTC2-NZyGAn533S:b-udr0l5) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L38)):*
> ```XML
>         ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.nonce,
>     }
> }
> ```

Consider defining this in starknet API similar to [#234](https://github.com/starkware-libs/starknet-api/pull/234)

(Note - I did not include `sender_address` here as it does not work for deploy account). 



_Code quote:_
```XML
pub fn get_tip(tx: &ExternalTransaction) -> Tip {
    match tx {
        ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => tx.tip,
        ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(tx)) => tx.tip,
        ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.tip,
    }
}

pub fn get_nonce(tx: &ExternalTransaction) -> Nonce {
    match tx {
        ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => tx.nonce,
        ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(tx)) => tx.nonce,
        ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.nonce,
    }
}
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkc19Aeg2AzOohB1V:-NyEkc19Aeg2AzOohB1W:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L49)):*
> ```XML
>         ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.sender_address,
>     }
> }
> ```





_Suggestion:_
```XML
pub fn get_sender_address(tx: &ExternalTransaction) -> ContractAddress {
    match tx {
        ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => tx.sender_address,
        // TODO(Mohammad): Add support for deploy account.
        ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(_)) => {
            ContractAddress::default()
        }
        ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.sender_address,
    }
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkc19Aeg2AzOohB1V:-NyEv0pv5noxtYpWh_AX:b-569216) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L49)):*
> ```XML
>         ExternalTransaction::Invoke(ExternalInvokeTransaction::V3(tx)) => tx.sender_address,
>     }
> }
> ```

Why `sender_address`? In Mempool we tend to use `contract_address`.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkBTC2-NZyGAn533R:-NyEzPbr3AnPve3HAJ_e:bflkaa5) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L38)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Consider defining this in starknet API similar to [#234](https://github.com/starkware-libs/starknet-api/pull/234)

(Note - I did not include `sender_address` here as it does not work for deploy account).
</blockquote></details>

As discussed in DMs. This is nonblocking.

I do suggest we conform to the same design.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkc19Aeg2AzOohB1V:-NyEziSIDy6BGEG61-vy:b3nu3ri) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L49)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why `sender_address`? In Mempool we tend to use `contract_address`.
</blockquote></details>

1. I did not know that about Mempool, so I am willing to concede it. 
2. This field is called `sender_address` in external transactions. This is a property of external transactions.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkBTC2-NZyGAn533R:-NyF-UPQ7WB8RQx4k2yL:bw7oe4u) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L38)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As discussed in DMs. This is nonblocking.

I do suggest we conform to the same design.
</blockquote></details>

Opened a PR, please take a look:
https://github.com/starkware-libs/starknet-api/pull/255

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkBTC2-NZyGAn533R:-NyF7rfdCe8Wrb9SD40V:bkvqp2j) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L38)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Opened a PR, please take a look:
https://github.com/starkware-libs/starknet-api/pull/255
</blockquote></details>

Integrating the new SN_API commit is a bit more complicated as it includes some breaking changes made by other teams.
Currently, I added a TODO to use it from the SN_API once the blockier supports the new SN_API version.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/145#-NyEkc19Aeg2AzOohB1V:-NyF7lorB7XyyUw88C-t:b7xxdqc) ([raw file](https://github.com/starkware-libs/mempool/blob/f48aaa5a36d22f2d570fb28335321022926ab917/crates/gateway/src/starknet_api_test_utils.rs#L49)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. I did not know that about Mempool, so I am willing to concede it. 
2. This field is called `sender_address` in external transactions. This is a property of external transactions.
</blockquote></details>

Changed to `sender_address`.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/145#-:-NyFRYsN4Wu1voV_SzuK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @Yael-Starkware)

**Pull request merged**
