### PR TITLE
refactor: add nonce to add_tx_input macro in mempool test

### PR DESCRIPTION
**Pull request by ayeletstarkware**
Prepration for multiple nonces per account

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/218)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/218)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool_types/src/utils.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/218#-Nzg16kp9btD_AltrJ8B:-Nzg16kp9btD_AltrJ8C:bcqi4mm) ([raw file](https://github.com/starkware-libs/mempool/blob/042877571c58cc61475ff27217c58d571e2aef73/crates/mempool_types/src/utils.rs#L12)):*
> ```XML
>     nonce: Nonce,
> ) -> ThinTransaction {
>     ThinTransaction { sender_address, tx_hash, tip, nonce }
> ```

Sure we need this util? 
It seems to just wrap the default constructor :thinking: 



_Code quote:_
```XML
pub fn create_thin_tx_for_testing(
    tip: Tip,
    tx_hash: TransactionHash,
    sender_address: ContractAddress,
    nonce: Nonce,
) -> ThinTransaction {
    ThinTransaction { sender_address, tx_hash, tip, nonce }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/218)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool_types/src/utils.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/218#-Nzg16kp9btD_AltrJ8B:-Nzg6OI42KvWoZogWMZ_:b-exaw7h) ([raw file](https://github.com/starkware-libs/mempool/blob/042877571c58cc61475ff27217c58d571e2aef73/crates/mempool_types/src/utils.rs#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sure we need this util? 
It seems to just wrap the default constructor :thinking:
</blockquote></details>

removed
I also changed the account's address field to "sender address" so it fits the macro.

**Review by giladchase — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/218#-:-NzgAhAf1bIbe1__wkMq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
