### PR TITLE
feat(mempool): replenishing queue in get_txs

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496#-:-O243ZZl8K4Z3e0hlxNU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/496#-O24FcIR6rcVWpRBXAge:-O24FcIR6rcVWpRBXAgf:b-cfzhgl) (no related file):*
Bad rebase?

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2TZ_Iy7pRqJx5X4mXL:-O2TZ_Iy7pRqJx5X4mXM:bhb8zjk) ([raw file](https://github.com/starkware-libs/mempool/blob/2d407eb1f8e2d875967e3b36a55645a8d8a7e858/crates/mempool/src/mempool.rs#L110)):*
> ```XML
>             let nonce = tx.nonce.try_increment().unwrap();
>             if let Some(next_tx_reference) =
>                 self.tx_pool.get_by_address_and_nonce(tx.sender_address, nonce)
> ```

This is an API we're going to need in more locations; please add: 
```rs
get_next_eligible_tx(account: Account) -> TransactionReference
```



_Code quote:_
```XML
self.tx_pool.get_by_address_and_nonce(tx.sender_address, nonce)
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Ta1CMBik-WDUiO_N3:-O2Ta1CMBik-WDUiO_N4:b-xbw1n0) ([raw file](https://github.com/starkware-libs/mempool/blob/df1cff6520090c543f9992fbc24a27ade7ab361a/crates/mempool/src/mempool_test.rs#L195)):*
> ```XML
> 
>     // Assert that the account's next tx was added the queue.
>     assert_eq!(txs, &[tx_address_0_nonce_0, tx_address_0_nonce_1]);
> ```

How come this PR caused this change? I'd imagine fixing `add_tx` would make `get_txs` not return both transactions.



_Code quote:_
```XML
    assert_eq!(txs, &[tx_address_0_nonce_0, tx_address_0_nonce_1]);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2TZ_Iy7pRqJx5X4mXL:-O2YtRZ_0ib02RniHwM-:b9g3aum) ([raw file](https://github.com/starkware-libs/mempool/blob/2d407eb1f8e2d875967e3b36a55645a8d8a7e858/crates/mempool/src/mempool.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is an API we're going to need in more locations; please add: 
```rs
get_next_eligible_tx(account: Account) -> TransactionReference
```
</blockquote></details>

1 - Should this function be in `Mempool` or `TransactionPool`?
2 - The `get_by_address_and_nonce` function returns `Option<&TransactionReference>`, not TransactionReference
3- `ThinTransaction` doesn’t include `Account`. Should I create one when calling this function, or should I receive the sender address and nonce instead?
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Ta1CMBik-WDUiO_N3:-O2Z8BSY3L9XmCEdA4n2:byyufii) ([raw file](https://github.com/starkware-libs/mempool/blob/df1cff6520090c543f9992fbc24a27ade7ab361a/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come this PR caused this change? I'd imagine fixing `add_tx` would make `get_txs` not return both transactions.
</blockquote></details>

correct. this PR makes get_txs to return only the first tx.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2TZ_Iy7pRqJx5X4mXL:-O2ZTjbNBgEH0qtGLEj8:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/2d407eb1f8e2d875967e3b36a55645a8d8a7e858/crates/mempool/src/mempool.rs#L110)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

1 - Should this function be in `Mempool` or `TransactionPool`?
2 - The `get_by_address_and_nonce` function returns `Option<&TransactionReference>`, not TransactionReference
3- `ThinTransaction` doesn’t include `Account`. Should I create one when calling this function, or should I receive the sender address and nonce instead?
</blockquote></details>

done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Zb7Dd6D0iszN2HXkX:-O2Zb7Dd6D0iszN2HXkY:blu399p) ([raw file](https://github.com/starkware-libs/mempool/blob/4b93c2d031a4441f37704cd74590618b0d88cac2/crates/mempool/src/mempool.rs#L114)):*
> ```XML
>         Ok(())
>     }
> ```

See my comment [here](https://reviewable.io/reviews/starkware-libs/mempool/499): taking into account Mohammad's suggestion, I think we should loop over transaction references until we collect all eligible.
Also, not sure we need a function, it's not too long.
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Ta1CMBik-WDUiO_N3:-O2ZbZhv4tkvrzhwEZv4:b-c7jqf0) ([raw file](https://github.com/starkware-libs/mempool/blob/df1cff6520090c543f9992fbc24a27ade7ab361a/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

correct. this PR makes get_txs to return only the first tx.
</blockquote></details>

It's temporary, right?
___
*[`crates/mempool/src/transaction_pool.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2ZaQGBDihQeoVL98GY:-O2ZaQGBDihQeoVL98GZ:b-xcn913) ([raw file](https://github.com/starkware-libs/mempool/blob/4b93c2d031a4441f37704cd74590618b0d88cac2/crates/mempool/src/transaction_pool.rs#L96)):*
> ```XML
>     ) -> MempoolResult<Option<&TransactionReference>> {
>         let Account { sender_address, state: AccountState { nonce } } = current_account_state;
>         let next_nonce = nonce.try_increment().map_err(|_| MempoolError::FeltOutOfRange)?;
> ```

TODO to change once SN API's errors impl. `PartialEq` (after mono-repo).



_Code quote:_
```XML
let next_nonce = nonce.try_increment().map_err(|_| MempoolError::FeltOutOfRange)?;
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/496#-O24FcIR6rcVWpRBXAge:-O2ZcJBh4VAkWzbFpLdG:b-896fix) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Bad rebase?
</blockquote></details>

Done.

___
___
*[`crates/mempool/src/mempool.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Zb7Dd6D0iszN2HXkX:-O2ZelnUC17juDAI18iB:b-roc0my) ([raw file](https://github.com/starkware-libs/mempool/blob/4b93c2d031a4441f37704cd74590618b0d88cac2/crates/mempool/src/mempool.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

See my comment [here](https://reviewable.io/reviews/starkware-libs/mempool/499): taking into account Mohammad's suggestion, I think we should loop over transaction references until we collect all eligible.
Also, not sure we need a function, it's not too long.
</blockquote></details>

Your suggestion is done on the next PR. the changes here take into consideration your comment. 
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/496#-O2Ta1CMBik-WDUiO_N3:-O2ZezmbASN55iF8ot8K:b-e7mitq) ([raw file](https://github.com/starkware-libs/mempool/blob/df1cff6520090c543f9992fbc24a27ade7ab361a/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's temporary, right?
</blockquote></details>

Yes. It's changing in the following PR according to the support of each PR.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496#-:-O2ZoSG576gtRoFvY5Nq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496#-:-O2_0kiP9nmef-GREle7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request closed without merging**
