### PR TITLE
test: streamline the fix infra for config tests

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#127** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#126** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#114](https://github.com/starkware-libs/mempool/pull/114) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@giladchase 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127#-:-NxugVClA9E2lPecGeAZ:b-uvtt1u)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/src/config_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxugYiFAGYDrQo5ygWS:-NxugYiFAGYDrQo5ygWT:b-46w7fb) ([raw file](https://github.com/starkware-libs/mempool/blob/5a766d6191c323116f72dc72e28ec525fd460658/crates/gateway/src/config_test.rs#L15)):*
> ```XML
> use crate::stateless_transaction_validator::StatelessTransactionValidatorConfig;
> 
> const FIX_CONFIG_TESTS: &str = "FIX_CONFIG_TESTS";
> ```

Maybe just? @giladchase 



_Suggestion:_
```XML
const FIX_CONFIG_TESTS: &str = "FIX";
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/config_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxugYiFAGYDrQo5ygWS:-Nxw2AI49uk5xufYqbDB:b-cxchxo) ([raw file](https://github.com/starkware-libs/mempool/blob/b59d0dbe4674c8b90409f949495d4c96cad7e949/crates/gateway/src/config_test.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Maybe just? @giladchase
</blockquote></details>

No longer relevant.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/config_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwUCiTEXvzGCmGj6uw:-NxwUCiTEXvzGCmGj6ux:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L32)):*
> ```XML
> ) {
>     let path = Path::new(TEST_FILES_FOLDER).join(serialized_config_file_name);
>     // Test seralize.
> ```





_Suggestion:_
```XML
serealize.
```
___
*[`crates/gateway/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwP-CABH15Xu9tO9MX:-NxwP-CB1ZMKOXzZrB42:b7vvpyu) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L35)):*
> ```XML
>     let expected_serialized_struct = expect_file![path.to_str().unwrap()];
>     let serialized_struct = serde_json::to_string_pretty(&config_struct.dump()).unwrap();
>     expected_serialized_struct.assert_eq(&serialized_struct);
> ```

explain with a comment about fix



_Code quote:_
```XML
expected_serialized_struct.assert_eq(&serialized_struct);
```
___
*[`crates/gateway/src/config_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwVR0T4tohu2xjXYlp:-NxwVR0T4tohu2xjXYlq:bfs5np3) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L38)):*
> ```XML
> 
>     // Test deserialize.
>     let path = Path::new(GATEWAY_SOURCE_FOLDER).join(path);
> ```

// The path when using get_config_from_file() needs to contain the src/ prefix as well.



_Code quote:_
```XML
let path = Path::new(GATEWAY_SOURCE_FOLDER).join(path);
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwUCiTEXvzGCmGj6uw:-NxwburY6Jb7yRf_W_Dt:bchq5ds) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L32)):*
> ```XML
> ) {
>     let path = Path::new(TEST_FILES_FOLDER).join(serialized_config_file_name);
>     // Test seralize.
> ```

Done. (used Google Translate).
___
*[`crates/gateway/src/config_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwP-CABH15Xu9tO9MX:-NxwdmVD69B92q4TDqcC:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L35)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

explain with a comment about fix
</blockquote></details>

Done.
___
*[`crates/gateway/src/config_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxwVR0T4tohu2xjXYlp:-NxwdnBJ7M1e8DcJgHB6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/bef1aee996974c9c5c5be9b4d25e4c246437e0b8/crates/gateway/src/config_test.rs#L38)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

// The path when using get_config_from_file() needs to contain the src/ prefix as well.
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/127)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/config_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/127#-NxugYiFAGYDrQo5ygWS:-Ny05spa5_ilmlIuTSAw:baid8b1) ([raw file](https://github.com/starkware-libs/mempool/blob/b59d0dbe4674c8b90409f949495d4c96cad7e949/crates/gateway/src/config_test.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No longer relevant.
</blockquote></details>

I like the nostalgia though :pleading_face: 
___
*[`crates/gateway/src/config_test.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/mempool/127#-Ny0AlejAQ9fhZmYC9e3:-Ny0AlejAQ9fhZmYC9e4:bl8qhb3) ([raw file](https://github.com/starkware-libs/mempool/blob/da4394007f7647199801c404b0aece4fd57cce76/crates/gateway/src/config_test.rs#L14)):*
> ```XML
> use crate::config::{GatewayNetworkConfig, StatelessTransactionValidatorConfig};
> 
> const TEST_FILES_FOLDER: &str = "json_files_for_testing";
> ```

Can you move this into gateway/tests/fixtures please? (either transfer the files or the whole directory, yr call).
These files shouldn't be compiled in production.



_Code quote:_
```XML
const TEST_FILES_FOLDER: &str = "json_files_for_testing";
```
___
*[`crates/gateway/src/config_test.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/mempool/127#-Ny075uUDG6Xt6Vw0Lmb:-Ny075uV05j6ubh270_w:b-ozggaq) ([raw file](https://github.com/starkware-libs/mempool/blob/da4394007f7647199801c404b0aece4fd57cce76/crates/gateway/src/config_test.rs#L56)):*
> ```XML
> #[test]
> /// Read the stateless transaction validator config file and validate its content.
> /// fix with "env UPDATE_EXPECT=1 cargo test"
> ```

I think the `env` is unnecessary, in fact I didn't even know about using it with `env`, only `UPDATE_EXPECT=1 cargo test`, what does adding `env` do?



_Code quote:_
```XML
/// fix with "env UPDATE_EXPECT=1 cargo test"
```
___
*[`crates/gateway/src/json_files_for_testing/stateless_transaction_validator_config.json` line 4 at r5](https://reviewable.io/reviews/starkware-libs/mempool/127#-Ny0cgkcEGKEbg1wc7X2:-Ny0cgkcEGKEbg1wc7X3:b-jfdcah) ([raw file](https://github.com/starkware-libs/mempool/blob/da4394007f7647199801c404b0aece4fd57cce76/crates/gateway/src/json_files_for_testing/stateless_transaction_validator_config.json#L4)):*
> ```JSON
>   "max_calldata_length": {
>     "description": "Validates that a transaction has signature length less than or equal to this value.",
>     "value": 10,
> ```

Why did the order change here?
It was alphabetized preivously.

**Pull request closed without merging**
