### PR TITLE
test(mempool): get txs multi nonce multi account validate replenishin…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…g queue

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyb0sAiCACn003Mm5:-O2Nyb0sAiCACn003Mm6:b-5dtayd) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L225)):*
> ```XML
>     // and processed after the transaction from account 1, even though it has a higher tip.
>     assert_eq!(txs, &[tx_address_0_nonce_0, tx_address_1_nonce_0, tx_address_0_nonce_1]);
>     let expected_mempool_state = MempoolState::new([], []);
> ```

Use Default.



_Code quote:_
```XML
MempoolState::new([], []);
```
___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyg6BCHzjUO7KC28v:-O2Nyg6BCHzjUO7KC28w:buhenuf) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L226)):*
> ```XML
>     assert_eq!(txs, &[tx_address_0_nonce_0, tx_address_1_nonce_0, tx_address_0_nonce_1]);
>     let expected_mempool_state = MempoolState::new([], []);
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```

Should we consider adding an `is_empty` method?



_Code quote:_
```XML
    let expected_mempool_state = MempoolState::new([], []);
    expected_mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2UC_q39zK2oqkniEG9:-O2UC_q39zK2oqkniEGA:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L202)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_multi_nonce_multi_account_validate_replenishing_queue() {
> ```





_Suggestion:_
```XML
test_get_txs_replenishes_queue_only_between_chunks
```
___
*[`crates/mempool/src/mempool_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2UCmiVBlMzVkgokWwG:-O2UCmiVBlMzVkgokWwH:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L223)):*
> ```XML
> 
>     // Assert: all transactions are returned. The second transaction from account 0 is replenished
>     // and processed after the transaction from account 1, even though it has a higher tip.
> ```





_Suggestion:_
```XML
    // Assert: all transactions returned.
    // Replenishment done in chunks: account 1 transaction is returned before the one of 
    // account 0, although its priority is higher.
```
___
*[`crates/mempool/src/mempool_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyb0sAiCACn003Mm5:-O2UE2y9Eo3DzaP6Xvfs:buk8p43) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L225)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Use Default.
</blockquote></details>

Do we have `empty()`?
___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyg6BCHzjUO7KC28v:-O2UDmqx51hdwYUTdyos:b-x8f04i) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L226)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Should we consider adding an `is_empty` method?
</blockquote></details>

The following line should be readable enough:
```rs
MempoolState::empty().assert_eq_mempool_state(&mempool);
```
Although if repeated a lot, we can consider it (let's have a higher level overview after all tests are merged).

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyb0sAiCACn003Mm5:-O2Zn72A1UTl2TPnQZpT:b8l739s) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L225)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we have `empty()`?
</blockquote></details>

in a different PR.
___
*[`crates/mempool/src/mempool_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/mempool/502#-O2Nyg6BCHzjUO7KC28v:-O2ZnE_t9ixkiQ2aiJ_v:b32w1t) ([raw file](https://github.com/starkware-libs/mempool/blob/74f25f443d99f0b0050aee473f7e4080b93247dd/crates/mempool/src/mempool_test.rs#L226)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The following line should be readable enough:
```rs
MempoolState::empty().assert_eq_mempool_state(&mempool);
```
Although if repeated a lot, we can consider it (let's have a higher level overview after all tests are merged).
</blockquote></details>

Ok

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502#-:-O2ZqLtrBusLu--NGSHk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request closed without merging**
