### PR TITLE
test: add cairo0 support to initialize_rpc_test_state

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259)

### CODE REVIEW

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259#-:-O03JIbz5kBRzV_o6LSj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/mempool/259#-O03IFsU6ViumnDgwm9V:-O03IFsU6ViumnDgwm9W:b-ihmb54) ([raw file](https://github.com/starkware-libs/mempool/blob/6680dc298302fae86bbe94639d42b8c24e2395ab/crates/tests-integration/src/state_reader.rs#L130)):*
> ```XML
>     cairo0_contract_classes: &mut Vec<(ClassHash, DeprecatedContractClass)>,
>     cairo1_contract_classes: &mut Vec<(ClassHash, CasmContractClass)>,
> ) {
> ```

Consider constructing the vectors inside this function and return them in the return value.



_Suggestion:_
```XML
fn prepare_compiled_contract_classes(
    contract_instances: &[(FeatureContract, u16)],
) -> (Vec<(ClassHash, DeprecatedContractClass)>, Vec<(ClassHash, CasmContractClass)>) {
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/tests-integration/src/state_reader.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/mempool/259#-O03IFsU6ViumnDgwm9V:-O03xRgzEaJx3Vy6DUBS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6680dc298302fae86bbe94639d42b8c24e2395ab/crates/tests-integration/src/state_reader.rs#L130)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider constructing the vectors inside this function and return them in the return value.
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/tests-integration/src/state_reader.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/mempool/259#-O03zNOo-h6tLCF7ub24:-O03zNOpDI9pwcLdHVvx:b-o3ba5q) ([raw file](https://github.com/starkware-libs/mempool/blob/9f946d17237caa95f8cd27ff107a39e3827aa49f/crates/tests-integration/src/state_reader.rs#L39)):*
> ```XML
> 
> type ContractClassesMap =
>     (Vec<(ClassHash, DeprecatedContractClass)>, Vec<(ClassHash, CasmContractClass)>);
> ```

Clippy made me add this.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259#-:-O03z_Dw8xd4r0xlF3Lr:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
