### PR TITLE
feat: add functionality to create all components

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #292
- #291
- #290
- #289
- #265 ⬅
- #262
- #261

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/265)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/265)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/gateway/src/gateway.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/mempool/265#-O093znq-Ke7Zvz86VC0:-O093znr1jJF5ywEoSXJ:b-sbf7fu) ([raw file](https://github.com/starkware-libs/mempool/blob/4702767a5904eda7f9948ae05fb9cbd697409502/crates/gateway/src/gateway.rs#L132)):*
> ```XML
>     config: GatewayConfig,
>     rpc_state_reader_config: RpcStateReaderConfig,
>     client: Option<SharedMempoolClient>,
> ```

When will this function be invoked with a None value for the client?
If never, please drop the `Optional` part, and change the type to `Box<dyn MempoolClient` -- we'd like to pass ownership of the client to this struct, not to share an atomic reference with all the other components that need a mempool-client.



_Code quote:_
```XML
Option<SharedMempoolClient>
```
___
*[`crates/mempool_node/src/components.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/265#-O094WWH7CkZD5-6Cl1m:-O094WWH7CkZD5-6Cl1n:b1nob35) ([raw file](https://github.com/starkware-libs/mempool/blob/4702767a5904eda7f9948ae05fb9cbd697409502/crates/mempool_node/src/components.rs#L9)):*
> ```XML
> pub struct Components {
>     pub gateway: Option<Gateway>,
>     pub mempool: Option<Mempool>,
> ```

Please don't use pub visibility on fields unless there's an absolute must; that's not the case here imo.



_Code quote:_
```XML
    pub gateway: Option<Gateway>,
    pub mempool: Option<Mempool>,
```
___
*[`crates/mempool_node/src/components.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/265#-O095gF1Aq0Vxu3CXpqj:-O095gF2-hqK6mtS6iur:b-5zhcco) ([raw file](https://github.com/starkware-libs/mempool/blob/4702767a5904eda7f9948ae05fb9cbd697409502/crates/mempool_node/src/components.rs#L23)):*
> ```XML
>     if config.components.mempool_component.execute {
>         components.mempool = Some(Mempool::empty());
>     }
> ```

Please create each component as `Some` or `None`, and then bundle them together in the struct. That is, please do not create the struct with `None` values to begin with.



_Code quote:_
```XML
    let mut components = Components { gateway: None, mempool: None };
    if config.components.gateway_component.execute {
        components.gateway = Some(create_gateway(
            config.gateway_config.clone(),
            config.rpc_state_reader_config.clone(),
            clients.mempool_client.clone(),
        ));
    }
    if config.components.mempool_component.execute {
        components.mempool = Some(Mempool::empty());
    }
```
___
*[`crates/mempool_node/src/lib.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/mempool/265#-O093MJ9-z0_JP6RDYEW:-O093MJ9-z0_JP6RDYEX:bby11t6) ([raw file](https://github.com/starkware-libs/mempool/blob/4702767a5904eda7f9948ae05fb9cbd697409502/crates/mempool_node/src/lib.rs#L3)):*
> ```XML
> pub mod com_clients;
> pub mod communication;
> pub mod components;
> ```

Next time, please add these with at the relevant pr that introduces the new file.



_Code quote:_
```XML
pub mod com_clients;
pub mod communication;
pub mod components;
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/265)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/components.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/265#-O095gF1Aq0Vxu3CXpqj:-O0EMKGwD261NA_NgUc_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4702767a5904eda7f9948ae05fb9cbd697409502/crates/mempool_node/src/components.rs#L23)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please create each component as `Some` or `None`, and then bundle them together in the struct. That is, please do not create the struct with `None` values to begin with.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/265)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/components.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/265#-O0OAVF64eqQ-dtYuzwE:-O0OAVF64eqQ-dtYuzwF:byllxvd) ([raw file](https://github.com/starkware-libs/mempool/blob/3d734de24a4b63210ae3b9b966f7632719b4ea50/crates/mempool_node/src/components.rs#L14)):*
> ```XML
> pub fn create_components(config: &MempoolNodeConfig, clients: &MempoolNodeClients) -> Components {
>     let gateway_component = if config.components.gateway_component.execute {
>         let mempool_clent =
> ```

Typo (missing "i")



_Code quote:_
```XML
mempool_clent
```

**Comment by lev-starkware** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
