### PR TITLE
feat: use starknet_api builtin for name trait

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)

The TODO is addressed here: https://github.com/starkware-libs/starknet-api/pull/288

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/319?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#319** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/319?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#296** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/296?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#297](https://github.com/starkware-libs/mempool/pull/297) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/297?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#246** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/246?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#298](https://github.com/starkware-libs/mempool/pull/298) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#312](https://github.com/starkware-libs/mempool/pull/312) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/312?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#235** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/234?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0dP-RVElxRtB-Xwi2d:-O0dP-RVElxRtB-Xwi2e:bfgv26k) ([raw file](https://github.com/starkware-libs/mempool/blob/fd9e01ea157defb57673f1506ad8a0898f216779/crates/gateway/src/gateway.rs#L187)):*
> ```XML
> 
> // TODO(Arni): Add to a config.
> fn get_supported_builtins() -> Vec<String> {
> ```

Please use https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html
___
*[`crates/gateway/src/gateway.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0dQfSM82y-CzMbpSck:-O0dQfSM82y-CzMbpScl:b-tciqt1) ([raw file](https://github.com/starkware-libs/mempool/blob/fd9e01ea157defb57673f1506ad8a0898f216779/crates/gateway/src/gateway.rs#L187)):*
> ```XML
> 
> // TODO(Arni): Add to a config.
> fn get_supported_builtins() -> Vec<String> {
> ```

Consider adding `is_supported` method to `Builtin` together with using https://docs.rs/strum/latest/strum/derive.EnumIter.html

This way whenever a new builtin is created it won't be forgotten in this function

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0hbv7g77x7Cxw1hmiz:b-7mqb1g) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
> ```XML
>     true
> }
> ```

I think this whole code should move the starknet-api , it is relevant for all repos (mempool and blockifier for sure).

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0hdh4q7CptycmGbphK:bkfrrps) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think this whole code should move the starknet-api , it is relevant for all repos (mempool and blockifier for sure).
</blockquote></details>

I agree :)
Here it is in Starknet API: https://reviewable.io/reviews/starkware-libs/starknet-api/288#- (in `main-mempool` branch).

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0dP-RVElxRtB-Xwi2d:-O0idqQ-EyrcrZ18BN9E:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/gateway.rs#L187)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0dQfSM82y-CzMbpSck:-O0idqlF63Brp4T3PhoW:b-tqvabk) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/gateway.rs#L187)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding `is_supported` method to `Builtin` together with using https://docs.rs/strum/latest/strum/derive.EnumIter.html

This way whenever a new builtin is created it won't be forgotten in this function
</blockquote></details>

Done. See related Starknet API PR: https://reviewable.io/reviews/starkware-libs/starknet-api/290#-

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0mgY7o1tLzy5tAKWi8:bs7wujv) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I agree :)
Here it is in Starknet API: https://reviewable.io/reviews/starkware-libs/starknet-api/288#- (in `main-mempool` branch).
</blockquote></details>

Done*.
___
*[`crates/gateway/src/utils.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0mgLE_AZpHi2afH3b3:-O0mgLE_AZpHi2afH3b4:bvm5dft) ([raw file](https://github.com/starkware-libs/mempool/blob/a3ddc4661c91db88a21d497a3a79030c87b29fbd/crates/gateway/src/utils.rs#L195)):*
> ```XML
>         }
>     }
> }
> ```

The `name` method is taken from `starknet-api` (The code supporting it is already merged).



_Code quote:_
```XML
impl NameExt for Builtin {
    fn name(&self) -> &'static str {
        match self {
            Builtin::RangeCheck => RANGE_CHACK_BUILTIN_NAME,
            Builtin::Pedersen => PEDERSEN_BUILTIN_NAME,
            Builtin::Poseidon => POSEIDON_BUILTIN_NAME,
            Builtin::EcOp => EC_OP_BUILTIN_NAME,
            Builtin::Ecdsa => ECDSA_BUILTIN_NAME,
            Builtin::Bitwise => BITWISE_BUILTIN_NAME,
            Builtin::Keccak => KECCAK_BUILTIN_NAME,
            Builtin::SegmentArena => SEGMENT_ARENA_BUILTIN_NAME,
        }
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0mhfLL8dAmgNtqkElM:b-fk1qeq) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done*.
</blockquote></details>

See another related PR in SN-API: https://github.com/starkware-libs/starknet-api/pull/290

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0nOqzVAe9fK888o4Xk:b9qnsz2) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See another related PR in SN-API: https://github.com/starkware-libs/starknet-api/pull/290
</blockquote></details>

thats great!
what about is_supported_builtin and the static variable? shouldnt they also be in starknet-api?

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0rhv8p-iBz3k2sHdau:b-3kczhf) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No - They are a property of the gateway.

is_supported_builtin - is a property of the gateway, which is going to be used to create the replacement of the static variable - a config variable.
</blockquote></details>

lets add a todo to consider moving it to starknet-api.
I think it is a property of the whole system and should be in a central place

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0ryBB6BL0jEqX_vD6j:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets add a todo to consider moving it to starknet-api.
I think it is a property of the whole system and should be in a central place
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0hbv7g77x7Cxw1hmiy:-O0s2c6E1A2ydeiuCqFs:b-vnpv4b) ([raw file](https://github.com/starkware-libs/mempool/blob/d4dbe2028c26a44157102388d4babdd3340c6fd9/crates/gateway/src/utils.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See todo: `TODO(Arni): Consider moving into Starknet-api.`

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 66 at r8](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0wKzz29HeCVgCoM-HG:-O0wKzz29HeCVgCoM-HH:b-phm3jb) ([raw file](https://github.com/starkware-libs/mempool/blob/65d2d277c4ced5fa70811d8a0627ab485ee8c1a9/crates/gateway/src/compilation.rs#L66)):*
> ```XML
> // TODO(Arni): Consider moving into Starknet-api.
> // List of supported builtins.
> // This is an explicit function so that it is explicitly desiced which builtins are supported.
> ```

decides?



_Code quote:_
```XML
desiced
```
___
*[`crates/gateway/src/compilation.rs` line 68 at r8](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0wMYZJ8zzoTyOYyrg_:-O0wMYZKDFLfivKSknz4:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/65d2d277c4ced5fa70811d8a0627ab485ee8c1a9/crates/gateway/src/compilation.rs#L68)):*
> ```XML
> // This is an explicit function so that it is explicitly desiced which builtins are supported.
> // If new builtins are added, they should be added here.
> fn is_supported_builtin(builtin: &Builtin) -> bool {
> ```





_Suggestion:_
```XML
is_os_supported_builtin
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 66 at r8](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0wKzz29HeCVgCoM-HG:-O0wOwnd4TT9yPQ8K1e-:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/65d2d277c4ced5fa70811d8a0627ab485ee8c1a9/crates/gateway/src/compilation.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

decides?
</blockquote></details>

Done
___
*[`crates/gateway/src/compilation.rs` line 68 at r8](https://reviewable.io/reviews/starkware-libs/mempool/319#-O0wMYZJ8zzoTyOYyrg_:-O0wPX_I0L3YqvulJQfX:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/65d2d277c4ced5fa70811d8a0627ab485ee8c1a9/crates/gateway/src/compilation.rs#L68)):*
> ```XML
> // This is an explicit function so that it is explicitly desiced which builtins are supported.
> // If new builtins are added, they should be added here.
> fn is_supported_builtin(builtin: &Builtin) -> bool {
> ```

Done

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/319#-:-O1Byrn294My4GsnIH6g:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request closed without merging**
