### PR TITLE
feat(mempool): implement remove from nonce for account transaction index

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1Wbaqg524GEF_xh8un:-O1Wbaqg524GEF_xh8uo:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L108)):*
> ```XML
>     }
> 
>     fn _remove_from_nonce(
> ```





_Suggestion:_
```XML
_remove_txs_up_to_nonce(
```
___
*[`crates/mempool/src/transaction_pool.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WblT93Mh_naPQ6bEO:-O1WblT93Mh_naPQ6bEP:b3j28ep) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L112)):*
> ```XML
>         address: ContractAddress,
>         nonce: Nonce,
>     ) -> Vec<TransactionReference> {
> ```

Second API having to pass both a contract and a nonce, which is somewhat awkward.
We'll probably have number 3 soon? Plz start thinking about an extra abstraction here by the time we get to number 3.



_Code quote:_
```XML
    fn get(&self, address: ContractAddress, nonce: Nonce) -> Option<&TransactionReference> {
        self.0.get(&address)?.get(&nonce)
    }

    fn _remove_from_nonce(
        &mut self,
        address: ContractAddress,
        nonce: Nonce,
    ) -> Vec<TransactionReference> {
```
___
*[`crates/mempool/src/transaction_pool.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WhqJf97RWfkN0My6c:-O1WhqJf97RWfkN0My6d:b-a0dna8) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L115)):*
> ```XML
>         if let Some(btree_map) = self.0.get_mut(&address) {
>             let nonces_to_remove: Vec<_> = btree_map.range(..=nonce).map(|(&n, _)| n).collect();
>             let txs: Vec<_> = nonces_to_remove.iter().filter_map(|n| btree_map.remove(n)).collect();
> ```

no side effects in map.



_Code quote:_
```XML
filter_map(|n| btree_map.remove(n)).c
```
___
*[`crates/mempool/src/transaction_pool.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WhzoC70nNkcJUZt3_:-O1WhzoC70nNkcJUZt3a:b-wjgyco) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L115)):*
> ```XML
>         if let Some(btree_map) = self.0.get_mut(&address) {
>             let nonces_to_remove: Vec<_> = btree_map.range(..=nonce).map(|(&n, _)| n).collect();
>             let txs: Vec<_> = nonces_to_remove.iter().filter_map(|n| btree_map.remove(n)).collect();
> ```

Are two allocations necessary here? (it also iterates the whole list twice, rather than once)



_Code quote:_
```XML
            let nonces_to_remove: Vec<_> = btree_map.range(..=nonce).map(|(&n, _)| n).collect();
            let txs: Vec<_> = nonces_to_remove.iter().filter_map(|n| btree_map.remove(n)).collect();
```
___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1Wc5qdCcC5UAIrK9w-:-O1Wc5qdCcC5UAIrK9w0:b944mv5) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
> ```XML
>         } else {
>             Vec::new()
>         }
> ```

no if-let-else



_Code quote:_
```XML
        if let Some(btree_map) = self.0.get_mut(&address) {
            let nonces_to_remove: Vec<_> = btree_map.range(..=nonce).map(|(&n, _)| n).collect();
            let txs: Vec<_> = nonces_to_remove.iter().filter_map(|n| btree_map.remove(n)).collect();

            // Remove the entry from the HashMap if the BTreeMap is empty
            if btree_map.is_empty() {
                self.0.remove(&address);
            }

            txs
        } else {
            Vec::new()
        }
```
___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WiJNb7g9wEiCS0mJu:-O1WiJNb7g9wEiCS0mJv:b-uxw4cl) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
> ```XML
>         } else {
>             Vec::new()
>         }
> ```

smells like or_default



_Code quote:_
```XML
        } else {
            Vec::new()
        }
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1Wbaqg524GEF_xh8un:-O1X-8bp-W2qfrpL39fl:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L108)):*
> ```XML
>     }
> 
>     fn _remove_from_nonce(
> ```

Done.
___
*[`crates/mempool/src/transaction_pool.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WhqJf97RWfkN0My6c:-O1kL_KR4_amJhqTV42V:brpmqc3) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L115)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

no side effects in map.
</blockquote></details>

removed.
___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1Wc5qdCcC5UAIrK9w-:-O1kEtEp9H81C4hwXjvu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

no if-let-else
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WiJNb7g9wEiCS0mJu:-O1kEu2A-fqo3hmglEbL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

smells like or_default
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WhzoC70nNkcJUZt3_:-O1kN7Ii9jNEKUtKauRL:bvyyq0v) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L115)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are two allocations necessary here? (it also iterates the whole list twice, rather than once)
</blockquote></details>

I think we should use separate iterators because removing elements from a BTreeMap while iterating over it is not allowed.
Error:
"cannot borrow as mutable because it is also borrowed as immutable"

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WblT93Mh_naPQ6bEO:-O1kUokp8iHi_OWwduW3:b-qyu8k5) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L112)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Second API having to pass both a contract and a nonce, which is somewhat awkward.
We'll probably have number 3 soon? Plz start thinking about an extra abstraction here by the time we get to number 3.
</blockquote></details>

That's a good point. The naive solution is to add a structure. I'll think about a different and more efficient solution.
I think it's unrelated to this PR, so I'll do it in a separate PR. wdyt?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qRvlB5bBqIWqA59VP:-O1qRvlB5bBqIWqA59VQ:beajldr) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L114)):*
> ```XML
>     ) -> Vec<TransactionReference> {
>         match self.0.get_mut(&address) {
>             Some(btree_map) => {
> ```

short-circuit with let-else pattern, less nesting



_Code quote:_
```XML
        match self.0.get_mut(&address) {
            Some(btree_map) => {
```
___
*[`crates/mempool/src/transaction_pool.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qTm4e2GldjivqOB2Q:-O1qTm4e2GldjivqOB2R:b-l2dow4) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L121)):*
> ```XML
>                 for n in nonces_to_remove {
>                     txs.push(btree_map.remove(&n).expect("Failed to remove nonce from BTreeMap"));
>                 }
> ```

that's possibly`k*log(n)`, use `split_off` for a `log(n)` solution



_Code quote:_
```XML
                for n in nonces_to_remove {
                    txs.push(btree_map.remove(&n).expect("Failed to remove nonce from BTreeMap"));
                }
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WiJNb7g9wEiCS0mJu:-O1qU7A429sLUA8_GlNb:b6h5w17) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's no way to use or_default here? (there might not be, just making sure)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_pool.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1WiJNb7g9wEiCS0mJu:-O1uHUga7FJkmdbTPlpO:b9nw8pf) ([raw file](https://github.com/starkware-libs/mempool/blob/2b907ba9780883c7d030379c5ee118e968fa26db/crates/mempool/src/transaction_pool.rs#L125)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There's no way to use or_default here? (there might not be, just making sure)
</blockquote></details>

Now I use let-else. and return if `btreemap` is empty.
___
*[`crates/mempool/src/transaction_pool.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qRvlB5bBqIWqA59VP:-O1uG2xc42po_gaSi6Q1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L114)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

short-circuit with let-else pattern, less nesting
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 108 at r4](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vf66DC5RXtbE6jnlP:-O1vf66DC5RXtbE6jnlQ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/7c8631d0e7468704649f9493fdeb1db4177a3893/crates/mempool/src/transaction_pool.rs#L108)):*
> ```XML
>     }
> 
>     fn _remove_txs_up_to_nonce(
> ```





_Suggestion:_
```XML
_remove_up_to_nonce
```
___
*[`crates/mempool/src/transaction_pool.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vf9urECfp709ynbDC:-O1vf9urECfp709ynbDD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/7c8631d0e7468704649f9493fdeb1db4177a3893/crates/mempool/src/transaction_pool.rs#L113)):*
> ```XML
>         nonce: Nonce,
>     ) -> Vec<TransactionReference> {
>         let Some(btree_map) = self.0.get_mut(&address) else {
> ```





_Suggestion:_
```XML
account_txs
```
___
*[`crates/mempool/src/transaction_pool.rs` line 129 at r4](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vgEEm3k1eDpLSkoFc:-O1vgEEm3k1eDpLSkoFd:bugw633) ([raw file](https://github.com/starkware-libs/mempool/blob/7c8631d0e7468704649f9493fdeb1db4177a3893/crates/mempool/src/transaction_pool.rs#L129)):*
> ```XML
>         }
> 
>         txs
> ```

Your comments are repeating the code, note that good variable names make then redundant.



_Suggestion:_
```XML
        let txs_with_higher_or_equal_nonce = account_txs.split_off(&nonce);
        let txs_with_lower_nonce: Vec<TransactionReference> = account_txs.values().cloned().collect();

        *account_txs = txs_with_higher_or_equal_nonce;
        if account_txs.is_empty() {
            self.0.remove(&address);
        }

        txs_with_lower_nonce
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vkwnv1n6dO3tHlNxa:-O1vkwnv1n6dO3tHlNxb:b-lpk80e) ([raw file](https://github.com/starkware-libs/mempool/blob/146b459b6eb636f18048c5d7338ab038a9fc3a7d/crates/mempool/src/transaction_pool.rs#L119)):*
> ```XML
>         let txs_with_higher_or_equal_nonce = account_txs.split_off(&nonce);
>         let txs_with_lower_nonce: Vec<TransactionReference> =
>             account_txs.values().cloned().collect();
> ```

What exactly is `cloned` here? Making sure we don't do expensive work.



_Code quote:_
```XML
.cloned()
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qTm4e2GldjivqOB2Q:-O1wNkSO9cmVpCPNWQoL:b8mlqzt) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice! 
I think you need to +1 the nonce though, cause split-off(k) is, somewhat unintuitively, breaking it up into [,..,k) and [k,..]
___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vkwnv1n6dO3tHlNxa:-O1wPMNNCbzqWuz0BTIg:bhbcpcp) ([raw file](https://github.com/starkware-libs/mempool/blob/146b459b6eb636f18048c5d7338ab038a9fc3a7d/crates/mempool/src/transaction_pool.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What exactly is `cloned` here? Making sure we don't do expensive work.
</blockquote></details>

I think he cloned the txs because he couldn't consume account_txs due to the *account_txs below.

You can avoid the clone by using a "swap" operation, which swaps account_txs with what you want and yields the ousted contents, freeing you up to take ownership of them without clone.

(but `std::mem::swap` is for variables, for an operation on an object you need `std::mem::replace`)
```rust
        let txs_with_higher_or_equal_nonce = account_txs.split_off(&nonce);

        let txs_with_lower_nonce = std::mem::replace(account_txs, txs_with_higher_or_equal_nonce);

        if account_txs.is_empty() {
            self.0.remove(&address);
        }

        txs_with_lower_nonce.into_values().collect()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qTm4e2GldjivqOB2Q:-O1z6BOfDUKbTBiBLCW4:bsmhjht) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L121)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nice! 
I think you need to +1 the nonce though, cause split-off(k) is, somewhat unintuitively, breaking it up into [,..,k) and [k,..]
</blockquote></details>

Correct, but I think removing the lower nonces is enough, as the `commit_block` sends the next_nonce.
___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1vkwnv1n6dO3tHlNxa:-O1z5Bco83TRiSybi01d:b1fb071) ([raw file](https://github.com/starkware-libs/mempool/blob/146b459b6eb636f18048c5d7338ab038a9fc3a7d/crates/mempool/src/transaction_pool.rs#L119)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think he cloned the txs because he couldn't consume account_txs due to the *account_txs below.

You can avoid the clone by using a "swap" operation, which swaps account_txs with what you want and yields the ousted contents, freeing you up to take ownership of them without clone.

(but `std::mem::swap` is for variables, for an operation on an object you need `std::mem::replace`)
```rust
        let txs_with_higher_or_equal_nonce = account_txs.split_off(&nonce);

        let txs_with_lower_nonce = std::mem::replace(account_txs, txs_with_higher_or_equal_nonce);

        if account_txs.is_empty() {
            self.0.remove(&address);
        }

        txs_with_lower_nonce.into_values().collect()
```
</blockquote></details>

Nice!
But, as `TransactionReference` implements `Copy` I can replace it with the following code, which is simpler I think:



_Code snippet:_
```XML
        let txs_with_lower_nonce: Vec<TransactionReference> =
            account_txs.iter().map(|(_, tx)| *tx).collect();
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qTm4e2GldjivqOB2Q:-O1vfYAJ4GLXrHawxa9I:b-kjry58) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L121)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct, but I think removing the lower nonces is enough, as the `commit_block` sends the next_nonce.
</blockquote></details>

So I think it should send the current nonce of the changes accounts (i.e., a subset of the state diff.).

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/mempool/443#-O1qTm4e2GldjivqOB2Q:-O23pIvD9wcBNRHkC5Hu:ba574zq) ([raw file](https://github.com/starkware-libs/mempool/blob/166ac876c71927f1e88e4b7eb753cf086d559499/crates/mempool/src/transaction_pool.rs#L121)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So I think it should send the current nonce of the changes accounts (i.e., a subset of the state diff.).
</blockquote></details>

Note that in commit_block, I already calculate the next nonce, to modify the tx_queue.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r7](https://reviewable.io/reviews/starkware-libs/mempool/443#-O2Pdak4CxoHsRmiCwbh:-O2Pdak4CxoHsRmiCwbi:bbol576) ([raw file](https://github.com/starkware-libs/mempool/blob/c17108a5c089397279fcc4d819de9bc6238c5e9e/crates/mempool/src/transaction_pool.rs#L119)):*
> ```XML
> 
>         // Split the transactions at the given nonce.
>         // After the split, `account_txs` will contain the transactions with lower nonces,
> ```

Isn't Gilad's suggestion a bit more elegant? It allows us to keep the names and save on documentation.
___
*[`crates/mempool/src/transaction_pool.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/mempool/443#-O2PcwEv6jaTQTojB9xd:-O2PcwEw4skOXK0_9a3K:bt1lgz7) ([raw file](https://github.com/starkware-libs/mempool/blob/c17108a5c089397279fcc4d819de9bc6238c5e9e/crates/mempool/src/transaction_pool.rs#L123)):*
> ```XML
>         let mut split_txs = account_txs.split_off(&nonce);
>         // After the swap `split_txs` will contain transactions with lower nonces.
>         swap(account_txs, &mut split_txs);
> ```

Fully-qualified name, please. It's not clear where it's coming from.



_Code quote:_
```XML
swap
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r7](https://reviewable.io/reviews/starkware-libs/mempool/443#-O2Pdak4CxoHsRmiCwbh:-O2Td24aCR7Q6prSMtwx:b-9x12rd) ([raw file](https://github.com/starkware-libs/mempool/blob/c17108a5c089397279fcc4d819de9bc6238c5e9e/crates/mempool/src/transaction_pool.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't Gilad's suggestion a bit more elegant? It allows us to keep the names and save on documentation.
</blockquote></details>

[replace](https://doc.rust-lang.org/stable/std/mem/fn.replace.html#:~:text=Function%20std%3A%3Amem%3A%3Areplace&text=Moves%20src%20into%20the%20referenced,of%20two%20variables%2C%20see%20swap%20.) doesn't solve the borrowing issue, as it doesn't take two `&mut` vectors.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 119 at r7](https://reviewable.io/reviews/starkware-libs/mempool/443#-O2Pdak4CxoHsRmiCwbh:-O2Tz-7s-vwl5YUcA5_O:b-l0c2ha) ([raw file](https://github.com/starkware-libs/mempool/blob/c17108a5c089397279fcc4d819de9bc6238c5e9e/crates/mempool/src/transaction_pool.rs#L119)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

[replace](https://doc.rust-lang.org/stable/std/mem/fn.replace.html#:~:text=Function%20std%3A%3Amem%3A%3Areplace&text=Moves%20src%20into%20the%20referenced,of%20two%20variables%2C%20see%20swap%20.) doesn't solve the borrowing issue, as it doesn't take two `&mut` vectors.
</blockquote></details>

The code was updated.
It uses replace now.
Thanks!

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/443#-:-O2TzZRK7hcIzidR3JaB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Pull request merged**
