### PR TITLE
chore: add transaction getter to mempool

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/402#-O1LOQto6jAznvE_q4Cu:-O1LOQto6jAznvE_q4Cv:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/871ad401d0e7db0a13ac8fae520ac898ec1f0cac/crates/mempool/src/transaction_pool.rs#L62)):*
> ```XML
>     }
> 
>     pub fn get(&self, tx_hash: TransactionHash) -> MempoolResult<&ThinTransaction> {
> ```





_Suggestion:_
```XML
get_by_tx_hash
```
___
*[`crates/mempool/src/transaction_pool.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/mempool/402#-O1LOTvX4diHEz8YvDRy:-O1LOTvY6v_RyJAzLOhC:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/871ad401d0e7db0a13ac8fae520ac898ec1f0cac/crates/mempool/src/transaction_pool.rs#L66)):*
> ```XML
>     }
> 
>     pub fn get_by_account(
> ```





_Suggestion:_
```XML
get_by_address_and_nonce
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/402#-O1LOQto6jAznvE_q4Cu:-O1Lct-6-vdM0cZ3JXSI:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/871ad401d0e7db0a13ac8fae520ac898ec1f0cac/crates/mempool/src/transaction_pool.rs#L62)):*
> ```XML
>     }
> 
>     pub fn get(&self, tx_hash: TransactionHash) -> MempoolResult<&ThinTransaction> {
> ```

done
___
*[`crates/mempool/src/transaction_pool.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/mempool/402#-O1LOTvX4diHEz8YvDRy:-O1LctZmBLYTO39XvnPz:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/871ad401d0e7db0a13ac8fae520ac898ec1f0cac/crates/mempool/src/transaction_pool.rs#L66)):*
> ```XML
>     }
> 
>     pub fn get_by_account(
> ```

done

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/402#-O1Ld2hg6KeE7Wq0ZrOR:-O1Ld2hg6KeE7Wq0ZrOS:b-s31rme) (no related file):*
Please change the commit message: "add getter by address and nonce to TransactionPool".

___

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/402#-:-O1LnUiDD6HJEZbdI-30:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
