### PR TITLE
feat(mempool): implement priority queue data structure

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
:zap: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34#-:-Nv65BZUA0TfTU13H8q2:bnnaau2)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: 1 of 6 files reviewed, all discussions resolved

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvC8o5lBb4eGOuYlFJD:-NvC8o5lBb4eGOuYlFJE:bny9e14) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L32)):*
> ```XML
> 
> #[derive(Clone, Debug, derive_more::Deref)]
> pub struct Transaction(pub InternalTransaction);
> ```

 Consider changing the name of `Transaction` to make its job in the priority queue clearer or moving it to a better spot?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/priority_queue.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvC8o5lBb4eGOuYlFJD:-NvRHBtR5tKs_0jbgJvP:b-54o2mt) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L32)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider changing the name of `Transaction` to make its job in the priority queue clearer or moving it to a better spot?
</blockquote></details>

What do you have in mind?
I initially thought about calling it PriorityQueueTransaction, but then it felt redundant given the location of its definition.
I was thinking, if users of the queue have a clash, they can import it `as PriorityQueueTransaction`.
Not sure though.

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvC8o5lBb4eGOuYlFJD:-NvWVZ7p9t22hf8sVvyv:b-up13u1) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What do you have in mind?
I initially thought about calling it PriorityQueueTransaction, but then it felt redundant given the location of its definition.
I was thinking, if users of the queue have a clash, they can import it `as PriorityQueueTransaction`.
Not sure though.
</blockquote></details>

That's exactly what I was thinking too. I was concerned about having too many "Transaction"s in our structs, which could make things confusing, but maybe it's unnecessary.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvC8o5lBb4eGOuYlFJD:-NvWdHOsCxJo6GJ-F3IV:b-7tp2p3) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L32)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

That's exactly what I was thinking too. I was concerned about having too many "Transaction"s in our structs, which could make things confusing, but maybe it's unnecessary.
</blockquote></details>

Mohammad is taking over so his call now :P
___
*[`crates/mempool/src/priority_queue.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvWb_Vz-b9j3MLb1Xvz:-NvWb_Vz-b9j3MLb1Xw-:bi6urh9) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L39)):*
> ```XML
>             InternalTransaction::Declare(declare_tx) => match &declare_tx.tx {
>                 DeclareTransaction::V3(tx_v3) => tx_v3.tip,
>                 _ => unimplemented!(),
> ```

return error



_Code quote:_
```XML
                _ => unimplemented!(),
```
___
*[`crates/mempool/src/priority_queue_test.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvWd3ze9EGdFY61zsVV:-NvWd3ze9EGdFY61zsVW:b-i0kckp) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue_test.rs#L59)):*
> ```XML
>     pq.push(tx3.clone());
> 
>     assert_eq!(pq.pop().unwrap(), tx1);
> ```

change back to numbers (no hash)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvXKmpt-o9h4m80cnaJ):*
@giladchase, how do you add this to the commit msg?



_Code quote:_
```
New commits in r3 on 11/04/2024 at 09:21 by Gilad Chase:
```
___
*[`crates/mempool/src/priority_queue.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvC8o5lBb4eGOuYlFJD:-NvXIvJO20jLacjCAdSp:b-kzu3xd) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Mohammad is taking over so his call now :P
</blockquote></details>

Changed to `PQTransaction`.
___
*[`crates/mempool/src/priority_queue.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvWb_Vz-b9j3MLb1Xvz:-NvXKOMvAyLTFJ77lg8W:btl5p17) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

return error
</blockquote></details>

I think we can keep `unimplemented`, and in the mempool, we need to check that we get only V3 transactions.
WDYT?
___
*[`crates/mempool/src/priority_queue_test.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvWd3ze9EGdFY61zsVV:-NvXJESIAs34ejcVUyc6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue_test.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

change back to numbers (no hash)
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvXKmpt-o9h4m80cnaJ):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@giladchase, how do you add this to the commit msg?
</blockquote></details>

not sure i follow what you mean.
I push-forced into this PR while you were gone, do you mean that?
___
*[`crates/mempool/src/priority_queue.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/mempool/34#-NvWb_Vz-b9j3MLb1Xvz:-NvjyCZx-lKd5RzDNT8M:b-hfghm4) ([raw file](https://github.com/starkware-libs/mempool/blob/7d8faf1fd492a8e38b0b5802fb04a4d07904c93f/crates/mempool/src/priority_queue.rs#L39)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think we can keep `unimplemented`, and in the mempool, we need to check that we get only V3 transactions.
WDYT?
</blockquote></details>

Sounds good

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34#-:-Nvjybv55Jb3NnDS5XQF:bnfp4nl)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/34)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Pull request merged**
