### PR TITLE
test(mempool): test_add_tx_fills_nonce_gap

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2UZe8u6pJz97YqRiG6:bbzukwe) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
> ```XML
>     add_tx(&mut mempool, &tx_input_nonce_2);
>     assert_eq_mempool_queue(&mempool, &[tx_input_nonce_1.tx]);
> }
> ```

Make sure Ayelet haven't written this case already.



_Suggestion:_
```XML
fn test_add_tx_fills_hole(mut mempool: Mempool) {
    // Setup.
    let tx_input_nonce_1 = add_tx_input!(tx_hash: 1, tx_nonce: 1_u8, account_nonce: 0_u8);
    // Input that increments the account state.
    let tx_input_nonce_2 = add_tx_input!(tx_hash: 2, tx_nonce: 2_u8, account_nonce: 1_u8);
    let tx_input_nonce_3 = add_tx_input!(tx_hash: 3, tx_nonce: 3_u8, account_nonce: 0_u8);

    // Test and assert.
    
    // First, with gap.
    add_tx(&mut mempool, &tx_input_nonce_1);
    add_tx(&mut mempool, &tx_input_nonce_3);
    assert_eq_mempool_queue(&mempool, &[]);

    // Then, fill it.
    add_tx(&mut mempool, &tx_input_nonce_2);
    assert_eq_mempool_queue(&mempool, &[tx_input_nonce_1.tx]);
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2Y7S4h21g77otBgFFH:bpp00y) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Make sure Ayelet haven't written this case already.
</blockquote></details>

Done.
I don't see a similar test.
@ayeletstarkware, can you please approve?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2Yc_325ul3i_jiSzVJ:-O2Yc_325ul3i_jiSzVK:bqmfufv) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L322)):*
> ```XML
>     add_tx(&mut mempool, &tx_input_nonce_3);
>     // Queue is empty due to a nonce gap.
>     assert_eq_mempool_queue(&mempool, &[]);
> ```

add a todo to use mempool state
___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2Ycj3_725tEExgX379:b-8l2yy3) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
I don't see a similar test.
@ayeletstarkware, can you please approve?
</blockquote></details>

I haven't written this case. But I think the test's name could be more informative by indicating that the hole is filled from a transaction carrying a more recent account state.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2Yc_325ul3i_jiSzVJ:-O2YkSkw2y-A8qNHddIw:b-lprukb) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L322)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

add a todo to use mempool state
</blockquote></details>

Why I need to use mempool state?
___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2YkNiLDUzq17m6km0f:b-hjnh6v) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I haven't written this case. But I think the test's name could be more informative by indicating that the hole is filled from a transaction carrying a more recent account state.
</blockquote></details>

Changed to `test_add_tx_account_state_fills_hole`.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2Z5jwd710l2vQAiN1T:b74pcb7) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Changed to `test_add_tx_account_state_fills_hole`.
</blockquote></details>

That's the only way `add_tx` can close a hole, so seems redundant to me. Your call.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2Yc_325ul3i_jiSzVJ:-O2Z9TxaDB4uzojxyjcN:b-3tn9oq) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L322)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why I need to use mempool state?
</blockquote></details>

assert_eq_mempool_queue will be deleted soon. we will use mempool partial state to check mempool queue instead.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2ZCvGt2c_3uIYwNqRq:b-tek0is) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's the only way `add_tx` can close a hole, so seems redundant to me. Your call.
</blockquote></details>

This scenario can close a hole:
1. AddTx(Tx(nonce=1), State(0))
2. AddTx(Tx(nonce=0), State(0))

The first tx would create a hole.
The second tx would close it.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511#-:-O2ZPqJvC-fcQcQ5qFQM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2UZe8u6pJz97YqRiG5:-O2ZPlSS6Q4MNz4R232m:b-xqnq0q) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L327)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This scenario can close a hole:
1. AddTx(Tx(nonce=1), State(0))
2. AddTx(Tx(nonce=0), State(0))

The first tx would create a hole.
The second tx would close it.
</blockquote></details>

Right. :facepalm:

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2Yc_325ul3i_jiSzVJ:-O2Zn2zDEDJ0MuwP_qRS:b-8b11j9) ([raw file](https://github.com/starkware-libs/mempool/blob/df4b1a13bf4daea38e2dd3a768ca16b7a6e939e9/crates/mempool/src/mempool_test.rs#L322)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

assert_eq_mempool_queue will be deleted soon. we will use mempool partial state to check mempool queue instead.
</blockquote></details>

Added

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2ZsdjpBUyZ2qbdrUSV:-O2ZsdjpBUyZ2qbdrUSW:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/ad1226d2fc1b1ffb2309b9b2692e6d7187cfef0f/crates/mempool/src/mempool.rs#L109)):*
> ```XML
>         if tx.nonce < nonce {
>             return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
>         }
> ```

Remove.



_Code quote:_
```XML
        // Invalid input.
        // TODO(Mohammad): use `should_insert` method.
        if tx.nonce < nonce {
            return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/mempool/511#-O2ZsdjpBUyZ2qbdrUSV:-O2ZtRYIEji7fPH7wdPG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ad1226d2fc1b1ffb2309b9b2692e6d7187cfef0f/crates/mempool/src/mempool.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/511)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
