### PR TITLE
chore: add missing deploy_tx to get_sender_address and make run_validate return the mempool_input

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/527)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/527)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/527#-O2Zpwku4sEx0ZJtUg3q:-O2Zpwku4sEx0ZJtUg3r:b-4rcvme) ([raw file](https://github.com/starkware-libs/mempool/blob/fb2cf30984ead071b4052b3528adebb9f92a89e6/crates/gateway/src/gateway.rs#L136)):*
> ```XML
> 
>     let validator = stateful_tx_validator.instantiate_validator(state_reader_factory)?;
>     let mempool_input = stateful_tx_validator.run_validate(&tx, optional_class_info, validator)?;
> ```

The second part of my suggestion.



_Suggestion:_
```XML
    let validator = stateful_tx_validator.instantiate_validator(state_reader_factory)?;
    let account_tx = external_tx_to_account_tx(
            external_tx,
            optional_class_info,
            &self.config.chain_info.chain_id, // Requires another step for this refactor. As this implies, the chain_info is no longer a property of the validator (it never really was...)
        )?;
    
    stateful_tx_validator.run_validate(&account_tx, validator)?;
    
    let tx_hash = get_tx_hash(&account_tx);
    let sender_address = get_sender_address(&account_tx);
    let mempool_input = MempoolInput {
            tx: external_tx_to_thin_tx(external_tx, tx_hash, sender_address),
            account: Account { sender_address, state: AccountState { nonce: account_nonce } },
        }
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/527#-O2ZpYe04-RVBV7_4A39:-O2ZpYe04-RVBV7_4A3A:bgpi36t) ([raw file](https://github.com/starkware-libs/mempool/blob/fb2cf30984ead071b4052b3528adebb9f92a89e6/crates/gateway/src/stateful_transaction_validator.rs#L80)):*
> ```XML
>             account: Account { sender_address, state: AccountState { nonce: account_nonce } },
>         })
>     }
> ```

I think it is odd that the validator returns all of these things.
In my opinion, the correct thing to do is to change the input of the stateful validator so it returns nothing.

Move the creation of account transactions out - into `process_tx`.



_Suggestion:_
```XML
impl StatefulTransactionValidator {
    pub fn run_validate<V: StatefulTransactionValidatorTrait>(
        &self,
        account_tx: ...,
        mut validator: V,
    ) -> StatefulTransactionValidatorResult<()> {


        let account_nonce = validator.get_nonce(sender_address)?;
        let skip_validate = skip_stateful_validations(external_tx, account_nonce); // fix me.
        validator.validate(account_tx, skip_validate)?;
        Ok(())
    }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/527)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/527#-O2Zpwku4sEx0ZJtUg3q:-O2ctJzC-CwmwPpIw6gt:banxkvj) ([raw file](https://github.com/starkware-libs/mempool/blob/fb2cf30984ead071b4052b3528adebb9f92a89e6/crates/gateway/src/gateway.rs#L136)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The second part of my suggestion.
</blockquote></details>

yeah I fully agree, I actually already implemented it like that, but then it also requires changing the tests to get the account_tx instead of rpc_tx. 
Since the ThinTransaction and AccountTransaction should eventually become InternalTransaction, and after consulting with @dafnamatsry about it, we decided to do the full refactor when we'll start using the Internal Transaction.

but indeed getting the mempool_input from the run_validate is odd.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/527#-O2Zpwku4sEx0ZJtUg3q:-O2d3SZ4AlgO86Idj8LZ:bnw0q8e) ([raw file](https://github.com/starkware-libs/mempool/blob/fb2cf30984ead071b4052b3528adebb9f92a89e6/crates/gateway/src/gateway.rs#L136)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yeah I fully agree, I actually already implemented it like that, but then it also requires changing the tests to get the account_tx instead of rpc_tx. 
Since the ThinTransaction and AccountTransaction should eventually become InternalTransaction, and after consulting with @dafnamatsry about it, we decided to do the full refactor when we'll start using the Internal Transaction.

but indeed getting the mempool_input from the run_validate is odd.
</blockquote></details>

Do we want to abandon this PR or merge it with a TODO?

**Comment by ArniStarkware** [comment]
PRs should be migrated to the `sequencer` repo.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/527)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/mempool/527#-O2Zpwku4sEx0ZJtUg3q:-O2cuUSU5Cx3OU6OBkxs:bi8x2lr) ([raw file](https://github.com/starkware-libs/mempool/blob/fb2cf30984ead071b4052b3528adebb9f92a89e6/crates/gateway/src/gateway.rs#L136)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we want to abandon this PR or merge it with a TODO?
</blockquote></details>

not to abandon for sure, maybe modify, I will talk with @dafnamatsry

**Pull request closed without merging**
