### PR TITLE
test: test components communication using tonic rpcs

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvPYAR8Uk_cD74iRMc:-NzvPYAR8Uk_cD74iRMd:b-vd1r7w) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L1)):*
> ```XML
> pub mod component_a_service {
> ```

Why is `pub` needed?
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvP_bR9KxDDMRML4nF:-NzvP_bR9KxDDMRML4nG:b-hug2qy) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L4)):*
> ```XML
>     tonic::include_proto!("component_a_service");
> }
> ```

Please remove blank lines if possible between the different `mod` statements.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvPZGD2HRsIjN5L_s3:-NzvPZGD2HRsIjN5L_s4:bs4q9np) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L5)):*
> ```XML
> }
> 
> pub mod component_b_service {
> ```

Ditto



_Code quote:_
```XML
pub
```
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvQRsYEqbcUxZBHkBb:-NzvQRsYEqbcUxZBHkBc:b3u0wr3) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L49)):*
> ```XML
> impl ComponentATrait for ComponentAClientRpc {
>     async fn a_get_value(&self) -> ValueA {
>         let Ok(mut client) = RemoteAClient::connect(self.dst.clone()).await else {
> ```

Is there a version of `connect` that takes ip and port instead of a string?



_Code quote:_
```XML
self.dst.clone()
```
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvR6fADksRpZqOFH2M:-NzvR6fADksRpZqOFH2N:b-i1wxyk) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L87)):*
> ```XML
> 
> #[async_trait]
> impl RemoteA for Arc<Mutex<ComponentA>> {
> ```

This is confusing IMO.
Why can't the impl be for `ComponentA`, let the server handle concurrency concerns?



_Code quote:_
```XML
Arc<Mutex<ComponentA>>
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvPYAR8Uk_cD74iRMc:-NzvgQR457XGyin0SCwH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L1)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why is `pub` needed?
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvP_bR9KxDDMRML4nF:-NzvgQtr9w7wQ7SLcwoy:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove blank lines if possible between the different `mod` statements.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvPZGD2HRsIjN5L_s3:-NzvgRVG5_IBh_enTom9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L5)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvQRsYEqbcUxZBHkBb:-NzvgW8Z3RhONYJONVDq:b-p5468s) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is there a version of `connect` that takes ip and port instead of a string?
</blockquote></details>

No, dst is a URL destination. Notice it is constructed using the construct_url util function that returns a string that starts with 'http://'
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvR6fADksRpZqOFH2M:-Nzvh2_f5j2pmITTiSzQ:b-18snut) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is confusing IMO.
Why can't the impl be for `ComponentA`, let the server handle concurrency concerns?
</blockquote></details>

It's a bit confusing indeed, let me explain in person (zoom)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvQRsYEqbcUxZBHkBb:-Nzwcqpx0BzsBPQPaEKL:b-1yg6jl) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L49)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

No, dst is a URL destination. Notice it is constructed using the construct_url util function that returns a string that starts with 'http://'
</blockquote></details>

OK. Will this work with dns names as well? That is, have you seen an example? 
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvR6fADksRpZqOFH2M:-NzwdEgv4Axs24spxWHE:b-4edhvw) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L87)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

It's a bit confusing indeed, let me explain in person (zoom)
</blockquote></details>

Waiting for the new version :pray: 
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzwdLWy9IRAQalIdsaG:-NzwdLWy9IRAQalIdsaH:b-5n67uj) ([raw file](https://github.com/starkware-libs/mempool/blob/51b46c0dd463e3121266fcc65c620869c6317926/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L157)):*
> ```XML
>     let expected_value: ValueA = setup_value.into();
> 
>     let local_ip = "::1".parse().unwrap();
> ```

Can this be a dns name, e.g., `localhost` or `loopback`? Eventually we'd need to use these, I'd like to verify these are indeed supported.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvQRsYEqbcUxZBHkBb:-NzwgcQLB8AlNlPhSD67:bazjulw) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

OK. Will this work with dns names as well? That is, have you seen an example?
</blockquote></details>

I did not see an example of DNS name usage but it is implied to work with DNS names as it's a URL
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzvR6fADksRpZqOFH2M:-NzwgGO192JeeVPPVZIr:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/54bb9cf8540267482614f13c1979a92985b4a511/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Waiting for the new version :pray:
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzwdLWy9IRAQalIdsaG:-NzwgIaS5dJw6SwDDQ7s:bepal43) ([raw file](https://github.com/starkware-libs/mempool/blob/51b46c0dd463e3121266fcc65c620869c6317926/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L157)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can this be a dns name, e.g., `localhost` or `loopback`? Eventually we'd need to use these, I'd like to verify these are indeed supported.
</blockquote></details>

I'm pretty sure it's possible

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzwdLWy9IRAQalIdsaG:-Nzx0EDq1FCIsstg3cUf:bnbbdi0) ([raw file](https://github.com/starkware-libs/mempool/blob/51b46c0dd463e3121266fcc65c620869c6317926/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L157)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I'm pretty sure it's possible
</blockquote></details>

Please change to `localhost` then.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx-vAj8EHb0KbyW7ZN:-Nzx-vAj8EHb0KbyW7ZO:bpin6lx) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L90)):*
> ```XML
>     ) -> Result<Response<AGetValueReturnMessage>, Status> {
>         Ok(Response::new(AGetValueReturnMessage {
>             value: ComponentATrait::a_get_value(self).await,
> ```

Please change to `self.a_get_value().await`



_Code quote:_
```XML
ComponentATrait::a_get_value(self).await
```
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx08A81pmhHLADwAfZ:-Nzx08A93YfMFY_Muoz2:b-7ropln) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L118)):*
> ```XML
>     ) -> Result<Response<BGetValueReturnMessage>, Status> {
>         Ok(Response::new(BGetValueReturnMessage {
>             value: ComponentBTrait::b_get_value(self).await.into(),
> ```

ditto



_Code quote:_
```XML
ComponentBTrait::b_get_value(self).await.into()
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx124S0rTmFantPLlf:-Nzx124S0rTmFantPLlg:bciwk01) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L148)):*
> ```XML
>     };
> 
>     let value = response.get_ref().value;
> ```

I'm confused; why isn't this returned value already the expected one? I expect the client to return `ValueA` object when being invoked with `client.a_get_value`



_Code quote:_
```XML
let value = response.get_ref().value;
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzwdLWy9IRAQalIdsaG:-NzxLxTyAXj2EXhCjcVj:bcbtria) ([raw file](https://github.com/starkware-libs/mempool/blob/51b46c0dd463e3121266fcc65c620869c6317926/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L157)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `localhost` then.
</blockquote></details>

scrapped for now
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx-vAj8EHb0KbyW7ZN:-NzxM-WW9pEFnvGu1_Gd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `self.a_get_value().await`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx08A81pmhHLADwAfZ:-NzxM-8n8V1fp8hcVrir:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L118)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/mempool/229#-Nzx124S0rTmFantPLlf:-NzxGiEiAC2ZzlpOuU5e:b-vnw7lz) ([raw file](https://github.com/starkware-libs/mempool/blob/69ba9c70e4c7541ffc773317687d6179e14f1525/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L148)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'm confused; why isn't this returned value already the expected one? I expect the client to return `ValueA` object when being invoked with `client.a_get_value`
</blockquote></details>

changed to use a client_a

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229#-:-NzxPOPS7IoT2n_oTxAS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzxP7Me9_ibVzEQrBV6:-NzxP7Me9_ibVzEQrBV7:b577oy1) ([raw file](https://github.com/starkware-libs/mempool/blob/34ed6705bba4f26cfecb2cdba8f82e1b7b57502f/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L7)):*
> ```XML
>     tonic::include_proto!("component_b_service");
> }
> ```

redundant blank line (non blocking, please fix though)

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_rpc_test.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/mempool/229#-NzxP7Me9_ibVzEQrBV6:-NzxPbjZ9eTW9qpm_Oza:b-8fx2u7) ([raw file](https://github.com/starkware-libs/mempool/blob/34ed6705bba4f26cfecb2cdba8f82e1b7b57502f/crates/mempool_infra/tests/component_server_client_rpc_test.rs#L7)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

redundant blank line (non blocking, please fix though)
</blockquote></details>

:+1:

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
