### PR TITLE
refactor: gateway test

### PR DESCRIPTION
**Pull request by ayeletstarkware**
Move negative and positive flows to be in case parameters.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nxzu5O-0nqqZhXWOD3D:-Nxzu5O-0nqqZhXWOD3E:b-th9z03) ([raw file](https://github.com/starkware-libs/mempool/blob/dd4c7c4664adbd490bf39a22346744c9825412d4/crates/gateway/src/gateway_test.rs#L33)):*
> ```XML
> 
>     GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway)
> }
> ```

It is no longer used as a fixture.



_Suggestion:_
```XML
pub fn network_component() -> GatewayNetworkComponent {
    let (tx_gateway_to_mempool, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
    let (_, rx_mempool_to_gateway) = channel::<MempoolToGatewayMessage>(1);

    GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway)
}
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nxzu5O-0nqqZhXWOD3D:-NxzwhMU9U64HdwHsBzq:b-bryly6) ([raw file](https://github.com/starkware-libs/mempool/blob/dd4c7c4664adbd490bf39a22346744c9825412d4/crates/gateway/src/gateway_test.rs#L33)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is no longer used as a fixture.
</blockquote></details>

Not relevant. Please keep it as a fixture - see the comment below.
___
*[`crates/gateway/src/gateway_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/135#-NxzuKsl3bNzpRy2zCVS:-NxzuKsm1mlVpPgWreNl:b-ta0gnp) ([raw file](https://github.com/starkware-libs/mempool/blob/dd4c7c4664adbd490bf39a22346744c9825412d4/crates/gateway/src/gateway_test.rs#L68)):*
> ```XML
>             },
>         network_component: Arc::new(network_component())
>         },
> ```

(No longer relevant - As I suggest a different attitude - see below)

Extract to a function:
"Create state app for testing" or something. 



_Code quote:_
```XML
    AppState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                max_signature_length: 2,
                ..Default::default()
               },
            },
        network_component: Arc::new(network_component())
        },
```
___
*[`crates/gateway/src/gateway_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/135#-NxzvAMpEYaxEDq0iwEh:-NxzvAMpEYaxEDq0iwEi:bdae16s) ([raw file](https://github.com/starkware-libs/mempool/blob/dd4c7c4664adbd490bf39a22346744c9825412d4/crates/gateway/src/gateway_test.rs#L96)):*
> ```XML
>         ),
>     ])
>     .unwrap()});
> ```

I think we should change the attitude.

Use the same app state etc (It should not be a part of the parametrization).
But add a `signature` parameter to the parametrization. Once of length 2 and once of length ~4.



_Suggestion:_
```XML
    let external_invoke_tx = external_invoke_tx(invoke_tx_args! {
    signature: signature,
    contract_address: ContractAddress(patricia_key!(stark_felt!("0x1b34d819720bd84c89bdfb476bc2c4d0de9a41b766efabd20fa292280e4c6d9"))),
    resource_bounds: ResourceBoundsMapping::try_from(vec![
        (
            Resource::L1Gas,
            ResourceBounds {
                max_amount: 5,
                max_price_per_unit: 6,
            },
        ),
        (
            Resource::L2Gas,
            ResourceBounds {
                max_amount: 0,
                max_price_per_unit: 0,
            },
        ),
    ])
    .unwrap()});
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny-6_sf0SqNywuUHIIW:-Ny-6_sf0SqNywuUHIIX:bl2u7rb) ([raw file](https://github.com/starkware-libs/mempool/blob/dd4c7c4664adbd490bf39a22346744c9825412d4/crates/gateway/src/gateway_test.rs#L56)):*
> ```XML
>         },
>     StatusCode::INTERNAL_SERVER_ERROR,
>     "Signature length exceeded maximum:")]
> ```

This test should not have a negative flow.
Please simplify it accordingly.

We can (but it is not a must) redesign the code to include a unit test for the fact that "the add transaction function runs the validator." Please write a TODO on my name.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny09fBN0yduZFdd-8nk:-Ny09fBN0yduZFdd-8nl:bjitzqr) ([raw file](https://github.com/starkware-libs/mempool/blob/94efe01f4d6ceacbc77c4d3ce0a9d0b9219f5080/crates/gateway/src/gateway_test.rs#L53)):*
> ```XML
>                     max_amount: 0,
>                     max_price_per_unit: 0,
>                 },
> ```

waiting for rebase



_Code quote:_
```XML
        resource_bounds: ResourceBoundsMapping::try_from(vec![
            (
                Resource::L1Gas,
                ResourceBounds {
                    max_amount: 5,
                    max_price_per_unit: 6,
                },
            ),
            (
                Resource::L2Gas,
                ResourceBounds {
                    max_amount: 0,
                    max_price_per_unit: 0,
                },
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny09pmv4whGus1ecESM:-Ny09pmv4whGus1ecESN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/94efe01f4d6ceacbc77c4d3ce0a9d0b9219f5080/crates/gateway/src/gateway_test.rs#L80)):*
> ```XML
> 
> // TODO(Ayelet): add test cases for declare and deploy account transactions.
> // TODO(Arni): add uni test for negative flow in validation.
> ```





_Suggestion:_
```XML
// TODO(Arni): add unit test for negative flow in validation.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny09fBN0yduZFdd-8nk:-Ny0CBlSDvH_VGIdM7bG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/94efe01f4d6ceacbc77c4d3ce0a9d0b9219f5080/crates/gateway/src/gateway_test.rs#L53)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

waiting for rebase
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny09pmv4whGus1ecESM:-Ny0C-KV9A34fvl8vkSV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/94efe01f4d6ceacbc77c4d3ce0a9d0b9219f5080/crates/gateway/src/gateway_test.rs#L80)):*
> ```XML
> 
> // TODO(Ayelet): add test cases for declare and deploy account transactions.
> // TODO(Arni): add uni test for negative flow in validation.
> ```

Done.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny0CrQK2jl0WMsLMDHc:-Ny0CrQK2jl0WMsLMDHd:b-p6dzvv) ([raw file](https://github.com/starkware-libs/mempool/blob/1c9e6d95acf3fcb5cdcbcb03195635eb907c29bd/crates/gateway/src/gateway_test.rs#L85)):*
> ```XML
>     let response_bytes = &to_bytes(response).await;
>     assert!(String::from_utf8_lossy(response_bytes).starts_with(expected_response));
> }
> ```

We don't need statuses and tx types.



_Suggestion:_
```XML
#[rstest]
#[tokio::test]
async fn test_add_transaction_with_invoke_tx() {
    let json_string = external_invoke_tx_to_json(invoke_tx());
    let tx: ExternalTransaction = serde_json::from_str(&json_string).unwrap();

    let response = async_add_tx(State(app_state()), tx.clone().into()).await.into_response();

    let status_code = response.status();
    assert_eq!(status_code, StatusCode::OK);

    let response_bytes = &to_bytes(response).await;
    assert!(String::from_utf8_lossy(response_bytes).starts_with("INVOKE"));
}
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/mempool/135#-NyVAX6r9fJ6lZWnxdYi:-NyVAX6r9fJ6lZWnxdYj:b36u8he) ([raw file](https://github.com/starkware-libs/mempool/blob/ce8e928310488cf1cb72521e2fc2ad81943eba95/crates/gateway/src/gateway_test.rs#L33)):*
> ```XML
> 
> #[fixture]
> pub fn invoke_tx() -> ExternalTransaction {
> ```

please rebase, I moved this function to starknet_api_test_utils
___
*[`crates/gateway/src/gateway_test.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/mempool/135#-NyVAonz30w4g7cuAsdz:-NyVAonz30w4g7cuAse-:bvr3ely) ([raw file](https://github.com/starkware-libs/mempool/blob/ce8e928310488cf1cb72521e2fc2ad81943eba95/crates/gateway/src/gateway_test.rs#L90)):*
> ```XML
>     let app_state = app_state(network_component, max_signature_length);
> 
>     let json_string = external_invoke_tx_to_json(invoke_tx());
> ```

why do we need the json_string?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny_DgzyBvzjWNPPlwDz:-Ny_DgzzBS5hczt3kvEZ:b-nkgwi) ([raw file](https://github.com/starkware-libs/mempool/blob/73072903d507cdb707a24285e105ed3f52ab0daf/crates/gateway/src/gateway_test.rs#L57)):*
> ```XML
>     // TODO: Add fixture.
>     let gateway_component =
>         GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway);
> ```

maybe this code is also better inside app_state() ?



_Code quote:_
```XML
    // The  `_rx_gateway_to_mempool`   is retained to keep the channel open, as dropping it would
    // prevent the sender from transmitting messages.
    let (tx_gateway_to_mempool, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
    let (_, rx_mempool_to_gateway) = channel::<MempoolToGatewayMessage>(1);
    // TODO: Add fixture.
    let gateway_component =
        GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway);
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny_Jlz9547L1AoVp-5C:-Ny_Jlz9547L1AoVp-5D:bmixj27) ([raw file](https://github.com/starkware-libs/mempool/blob/73072903d507cdb707a24285e105ed3f52ab0daf/crates/gateway/src/gateway_test.rs#L62)):*
> ```XML
> 
>     let response =
>         add_tx(State(app_state.clone()), invoke_tx().clone().into()).await.into_response();
> ```

Why clone?



_Suggestion:_
```XML
    let response =
        add_tx(State(app_state), invoke_tx().clone().into()).await.into_response();
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny_Jlz9547L1AoVp-5C:-NypC4_I7_e6JD2srRdq:b-dxh8xp) ([raw file](https://github.com/starkware-libs/mempool/blob/73072903d507cdb707a24285e105ed3f52ab0daf/crates/gateway/src/gateway_test.rs#L62)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see the `clone`. Can it be deleted?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/mempool/135#-Ny_Jlz9547L1AoVp-5C:-NypDlVn9W1kewNIRPTi:b2nign3) ([raw file](https://github.com/starkware-libs/mempool/blob/73072903d507cdb707a24285e105ed3f52ab0daf/crates/gateway/src/gateway_test.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I still see the `clone`. Can it be deleted?
</blockquote></details>

yep

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 175 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nytzs0u06Q5Rxpprw3E:-Nytzs0u06Q5Rxpprw3F:b-izo9id) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/starknet_api_test_utils.rs#L175)):*
> ```XML
>      nonce,
>      calldata,
>      tip: Tip(0)
> ```

isn't this the default?

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-NytzhIV-_0QR5RtLEHo:-NytzhIV-_0QR5RtLEHp:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L39)):*
> ```XML
>         state_reader_factory: Arc::new(test_state_reader_factory()),
>     }
> }
> ```





_Suggestion:_
```XML
pub fn create_app_state_for_test(
    gateway_component: GatewayNetworkComponent,
    max_signature_length: usize,
) -> AppState {
    AppState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                max_signature_length,
                ..Default::default()
            },
        },
        network_component: Arc::new(gateway_component),
        stateful_transaction_validator: Arc::new(StatefulTransactionValidator {
            config: StatefulTransactionValidatorConfig::create_for_testing(),
        }),
        state_reader_factory: Arc::new(test_state_reader_factory()),
    }
}
```
___
*[`crates/gateway/src/gateway_test.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nytlij31S5oF1Mxli_8:-Nytlij31S5oF1Mxli_9:busx7to) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L44)):*
> ```XML
> #[rstest]
> #[case::positive(2, StatusCode::OK, "INVOKE")]
> #[case::negative(0, StatusCode::INTERNAL_SERVER_ERROR, "Signature length exceeded maximum:")]
> ```

Document this case.



_Suggestion:_
```XML
// Tests that the function add transaction calls the stateless transaction validator.
#[case::negative_flow_call_the_stateless_transaction_validator(0, StatusCode::INTERNAL_SERVER_ERROR, "Signature length exceeded maximum:")]
```
___
*[`crates/gateway/src/gateway_test.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nyu-03uA3Zz2omqrcFF:-Nyu-03uA3Zz2omqrcFG:b-lvyeqa) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L59)):*
> ```XML
>         GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway);
> 
>     let app_state = app_state(gateway_component, max_signature_length);
> ```

This is exactly the line I do not like. I see it is minimal (only one line). It hides its complexity behind the function `app_state`.

Let us talk F2f.
My agenda - we should delete this case. It is irrelevant here.



_Code quote:_
```XML
    let app_state = app_state(gateway_component, max_signature_length);
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nyu-03uA3Zz2omqrcFF:-Nyu2nfi5P_ffJQOX33o:bbyjsu) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is exactly the line I do not like. I see it is minimal (only one line). It hides its complexity behind the function `app_state`.

Let us talk F2f.
My agenda - we should delete this case. It is irrelevant here.
</blockquote></details>

@ayeletstarkware @Yael-Starkware 
Now on monday: https://starkware.monday.com/boards/6678575467/pulses/6713180662 (As a subtask of a bigger task).

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-NytzhIV-_0QR5RtLEHo:-Nyu30dN2Khs2LDnKT_O:b7sxcgu) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L39)):*
> ```XML
>         state_reader_factory: Arc::new(test_state_reader_factory()),
>     }
> }
> ```

Irrelevant.
Please rethink.
___
*[`crates/gateway/src/gateway_test.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/mempool/135#-Nytlij31S5oF1Mxli_8:-Nyu2xyAAVXGGc0sCCqC:bq2arys) ([raw file](https://github.com/starkware-libs/mempool/blob/31236754a916f7a65e9817c729d4aa683ee352a3/crates/gateway/src/gateway_test.rs#L44)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Document this case.
</blockquote></details>

Irrelevant.
Please delete.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135#-:-NyuM36JBDRAbx-zPmU8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 44 at r9](https://reviewable.io/reviews/starkware-libs/mempool/135#-NyxnhyB9hYWdJh7i6sP:-NyxnhyB9hYWdJh7i6sQ:bnvdbln) ([raw file](https://github.com/starkware-libs/mempool/blob/076303dc45f8dff4b62b6ac3bd865099450f9725/crates/gateway/src/gateway_test.rs#L44)):*
> ```XML
>         }),
>         state_reader_factory: Arc::new(test_state_reader_factory()),
>     };
> ```

why not use  a function for this? I think it makes the test more reader friendly.



_Code quote:_
```XML
    let app_state = AppState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                max_signature_length: 2,
                ..Default::default()
            },
        },
        network_component: Arc::new(gateway_component),
        stateful_transaction_validator: Arc::new(StatefulTransactionValidator {
            config: StatefulTransactionValidatorConfig::create_for_testing(),
        }),
        state_reader_factory: Arc::new(test_state_reader_factory()),
    };
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 44 at r9](https://reviewable.io/reviews/starkware-libs/mempool/135#-NyxnhyB9hYWdJh7i6sP:-NyxtsZP1IBlRov6aCjf:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/076303dc45f8dff4b62b6ac3bd865099450f9725/crates/gateway/src/gateway_test.rs#L44)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not use  a function for this? I think it makes the test more reader friendly.
</blockquote></details>

Done

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/135)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
