### PR TITLE
feat(mempool): get txs return requested txs after replenishing queue

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/499#-O24BTx4CS4hUiRc0CBl:-O24BTx4CS4hUiRc0CBm:b-1u5chv) ([raw file](https://github.com/starkware-libs/mempool/blob/e63abfd74736824ccc53276ebf3026d3696988c9/crates/mempool/src/mempool.rs#L50)):*
> ```XML
>     // back. TODO: Consider renaming to `pop_txs` to be more consistent with the standard
>     // library.
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
> ```

The method's code is getting longer, so I'm trying to think of a way to split it into functions.

What do you think about separating the queue and pool removal processes?

The recursive part is only relevant for the queue, not the pool. 
Therefore, it can be implemented in the queue, and the output would be a list of transaction hashes. Then, in another loop, we can remove transactions from the pool.



_Code quote:_
```XML
 get_txs(&mut self, n_txs: usize)
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/499#-O24AkOD5Cj_HXRDiRKg:-O250iR6Cu9ObxKlbh9E:b-l5vx54) ([raw file](https://github.com/starkware-libs/mempool/blob/e63abfd74736824ccc53276ebf3026d3696988c9/crates/mempool/src/mempool.rs#L67)):*
> ```XML
> 
>             eligible_txs.extend(popped_txs);
>         }
> ```

why these gaps?

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/499#-O24AkOD5Cj_HXRDiRKg:-O25TpkR6EUp9W56SCdI:bhj1d1x) ([raw file](https://github.com/starkware-libs/mempool/blob/e63abfd74736824ccc53276ebf3026d3696988c9/crates/mempool/src/mempool.rs#L67)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why these gaps?
</blockquote></details>

I don't think we need to add a gap between two logically related lines.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/499#-O24BTx4CS4hUiRc0CBl:-O2UO3nzBVPBeuNhOreQ:b-ul45go) ([raw file](https://github.com/starkware-libs/mempool/blob/e63abfd74736824ccc53276ebf3026d3696988c9/crates/mempool/src/mempool.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The method's code is getting longer, so I'm trying to think of a way to split it into functions.

What do you think about separating the queue and pool removal processes?

The recursive part is only relevant for the queue, not the pool. 
Therefore, it can be implemented in the queue, and the output would be a list of transaction hashes. Then, in another loop, we can remove transactions from the pool.
</blockquote></details>

WDYT:

```rs
pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
    let mut eligible_tx_refs: Vec<TransactionReference> = Vec::with_capacity(n_txs);
    let mut n_remaining_txs = n_txs;

    while n_remaining_txs > 0 && !self.tx_queue.is_empty() {
        let chunk = self.tx_queue.pop_chunk(n_remaining_txs);

        for tx_ref in &chunk {
            let current_account_state = Account {
                sender_address: tx_ref.sender_address,
                state: AccountState { nonce: tx_ref.nonce },
            };

            if let Some(next_eligible_tx_ref) = self.tx_pool.get_next_eligible_tx(current_account_state)? {
                self.tx_queue.insert(next_eligible_tx_ref);
            }
        }

        n_remaining_txs -= chunk.len();
        eligible_tx_refs.extend(chunk);
    }

    let mut eligible_txs: Vec<ThinTransaction> = Vec::with_capacity(n_txs);
    for tx_ref in eligible_tx_refs {
        let tx = self.tx_pool.remove(tx_ref.tx_hash)?;
        eligible_txs.push(tx);
    }

    Ok(eligible_txs)
}
```
Would need to change the return value of `pop_chunk`.
___
*[`crates/mempool/src/mempool_test.rs` line 197 at r2](https://reviewable.io/reviews/starkware-libs/mempool/499#-O2UOlsn-NgRaHv-y3pn:-O2UOlsn-NgRaHv-y3po:b-3wbn72) ([raw file](https://github.com/starkware-libs/mempool/blob/4aa3fe59eb6c7d698f7c5fc1ef2f9b5709a80ddc/crates/mempool/src/mempool_test.rs#L197)):*
> ```XML
>     // Assert: all transactions are returned.
>     assert_eq!(txs, &[tx_nonce_0, tx_nonce_1, tx_nonce_2]);
>     let expected_mempool_state = MempoolState::new([], []);
> ```

`empty()`?



_Code quote:_
```XML
MempoolState::new([], []);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/499#-O24BTx4CS4hUiRc0CBl:-O2ZfyEj1NWdL2LEO8A1:bhakoet) ([raw file](https://github.com/starkware-libs/mempool/blob/e63abfd74736824ccc53276ebf3026d3696988c9/crates/mempool/src/mempool.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT:

```rs
pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
    let mut eligible_tx_refs: Vec<TransactionReference> = Vec::with_capacity(n_txs);
    let mut n_remaining_txs = n_txs;

    while n_remaining_txs > 0 && !self.tx_queue.is_empty() {
        let chunk = self.tx_queue.pop_chunk(n_remaining_txs);

        for tx_ref in &chunk {
            let current_account_state = Account {
                sender_address: tx_ref.sender_address,
                state: AccountState { nonce: tx_ref.nonce },
            };

            if let Some(next_eligible_tx_ref) = self.tx_pool.get_next_eligible_tx(current_account_state)? {
                self.tx_queue.insert(next_eligible_tx_ref);
            }
        }

        n_remaining_txs -= chunk.len();
        eligible_tx_refs.extend(chunk);
    }

    let mut eligible_txs: Vec<ThinTransaction> = Vec::with_capacity(n_txs);
    for tx_ref in eligible_tx_refs {
        let tx = self.tx_pool.remove(tx_ref.tx_hash)?;
        eligible_txs.push(tx);
    }

    Ok(eligible_txs)
}
```
Would need to change the return value of `pop_chunk`.
</blockquote></details>

done. I made some small changes.
___
*[`crates/mempool/src/mempool_test.rs` line 197 at r2](https://reviewable.io/reviews/starkware-libs/mempool/499#-O2UOlsn-NgRaHv-y3pn:-O2Zg5Ge0nqa8fvyy9ak:b8l739s) ([raw file](https://github.com/starkware-libs/mempool/blob/4aa3fe59eb6c7d698f7c5fc1ef2f9b5709a80ddc/crates/mempool/src/mempool_test.rs#L197)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`empty()`?
</blockquote></details>

in a different PR.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/499#-O2Zopt72Qprhr-vQYqz:-O2ZwiJ3-OKLuWy_y5iy:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/94e38d5e11c8ffe36ecf1e81a2faad2e1c9d5f60/crates/mempool/src/mempool.rs#L66)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No external effects in `map`, please.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/499#-:-O2ZxAm0AGiqQuUBtHYk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request closed without merging**
