### PR TITLE
test(mempool): refactor test_add_tx to use mempool state

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbB3HEow97hX5go3A:-O1WbB3IABoH-YON-_CK:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L193)):*
> ```XML
> 
>     let pool_txs = inputs_add_tx.iter().map(|input| input.tx.clone());
>     let queue_txs = expected_queue.iter().map(|tx| TransactionReference::new(tx));
> ```





_Suggestion:_
```XML
    let pool_txs = inputs_add_tx.iter().cloned()
    let queue_txs = expected_queue.iter().map(TransactionReference::new());
```
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbHD-69eVCrguxl6l:-O1WbHD-69eVCrguxl6m:b-mba1cb) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L195)):*
> ```XML
>     let queue_txs = expected_queue.iter().map(|tx| TransactionReference::new(tx));
>     let mempool_state = MempoolState::new(pool_txs, queue_txs);
>     mempool_state.assert_eq_mempool_state(&mempool);
> ```

can this be oneline?



_Code quote:_
```XML
    let mempool_state = MempoolState::new(pool_txs, queue_txs);
    mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1g7Cc-7JEBo8-Sabi9:-O1g7Cc-7JEBo8-SabiA:b-nzihxf) (no related file):*
I noticed some new comments here that could be relevant to other test( PR)s; please see if you can apply them there as well.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1g7eT07YgeMuQe6hlW:-O1g7eT19U1QKmaDMo8g:bkessur) (no related file):*
Let's make all these tests have the same structure so they are quite easy to skim through. 

___
___
*[`crates/mempool/src/mempool_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1g6nAQAqEBnuVG4BWF:-O1g6nAR5YP9bdp41qYr:b-bevsbh) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L176)):*
> ```XML
> #[rstest]
> fn test_add_tx(mut mempool: Mempool) {
>     let inputs_add_tx = [
> ```

In all test( PR)s.



_Suggestion:_
```XML
add_tx_inputs
```
___
*[`crates/mempool/src/mempool_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1g7u7o3UKHKhOM4Brn:-O1g7u7o3UKHKhOM4Bro:b-7rbd0g) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L190)):*
> ```XML
>         &inputs_add_tx[2].tx, // tip 80
>         &inputs_add_tx[0].tx, // tip 50
>     ];
> ```

Can we sort in-place, maybe with `sort_by_key`? Would it make code more elegant?



_Code quote:_
```XML
    let expected_queue = [
        &inputs_add_tx[1].tx, // tip 100
        &inputs_add_tx[2].tx, // tip 80
        &inputs_add_tx[0].tx, // tip 50
    ];
```
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbHD-69eVCrguxl6l:-O1g6yiV8pLRWar_5KUp:b-kahwrn) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

can this be oneline?
</blockquote></details>

Do you think it'll be more readable? I don't have a solid opinion here.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbB3HEow97hX5go3A:-O1kY0V5Ep90lKUkCflu:b-s95mzx) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L193)):*
> ```XML
> 
>     let pool_txs = inputs_add_tx.iter().map(|input| input.tx.clone());
>     let queue_txs = expected_queue.iter().map(|tx| TransactionReference::new(tx));
> ```

Things have changed since we used `add_tx_input` instead of `expected_queue`. Is there a better way to write it now?
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbHD-69eVCrguxl6l:-O1Wnu5S9tUS_vitgLMr:b5busbk) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think it'll be more readable? I don't have a solid opinion here.
</blockquote></details>

i think it more readable in two lines

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1WbB3HEow97hX5go3A:-O1qOnpRDgnnNkfbUDRh:b-7j964s) ([raw file](https://github.com/starkware-libs/mempool/blob/d6bcc2360132e3c7e9ae0eb073f9ec0de791f8ff/crates/mempool/src/mempool_test.rs#L193)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Things have changed since we used `add_tx_input` instead of `expected_queue`. Is there a better way to write it now?
</blockquote></details>

stale
___
*[`crates/mempool/src/mempool_test.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1qQu0MBuKFMlMy5yQU:-O1qQu0N040gQjHiVjTx:b-gmogyl) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L194)):*
> ```XML
>     let expected_pool_txs = add_tx_inputs.iter().map(|input| input.tx.clone());
>     let expected_queue_txs = add_tx_inputs.iter().map(|input| TransactionReference::new(&input.tx));
>     let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
> ```

I think we can lose the tx clone now, which we should consider as an expensive op, even for a test.
You can collect the ref vector and move it up (collecting a vec of references is less taxing than cloning an array of txs).



_Code quote:_
```XML
    let expected_pool_txs = add_tx_inputs.iter().map(|input| input.tx.clone());
    let expected_queue_txs = add_tx_inputs.iter().map(|input| TransactionReference::new(&input.tx));
    let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1pcA4J1Oq_EGUKbt7g:-O1pcA4KDhD1_SJ-RHGz:bdc66m) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L179)):*
> ```XML
>     // Setup.
>     let mut add_tx_inputs = [
>         add_tx_input!(tip: 50, tx_hash: 1),
> ```

Who's the sender here?



_Code quote:_
```XML
add_tx_input!(tip: 50, tx_hash: 1),
```
___
*[`crates/mempool/src/mempool_test.rs` line 189 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1pcOte4ywOFiMG72Be:-O1pcOte4ywOFiMG72Bf:bcpjqx7) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L189)):*
> ```XML
>     }
> 
>     add_tx_inputs.sort_by_key(|input| Reverse(input.tx.tip));
> ```

- A(lmost a)lways fully-qualified module name when using `std` API.
- Add a short comment here: `// Sort in an ascending priority order.`.
- Wondering if there's some way to share this code (can be a TODO for now). Was thinking of a short method that both `cmp` and the tests will call.



_Code quote:_
```XML
Reverse
```
___
*[`crates/mempool/src/mempool_test.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1uiiDJCuKYy_uypB43:-O1uiiDJCuKYy_uypB44:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L191)):*
> ```XML
>     add_tx_inputs.sort_by_key(|input| Reverse(input.tx.tip));
> 
>     // Assert the transactions are in the correct order, with the highest priority first.
> ```





_Suggestion:_
```XML
 // Assert: transactions are ordered by priority.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1pcA4J1Oq_EGUKbt7g:-O1unJ5s8df0ZMcggrJc:b8c73aj) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L179)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Who's the sender here?
</blockquote></details>

account 0, default. I agree it's not clear. Fixed. 
___
*[`crates/mempool/src/mempool_test.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1qQu0MBuKFMlMy5yQU:-O1upt1N4v2AA1zp3PBU:b-imjzax) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L194)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we can lose the tx clone now, which we should consider as an expensive op, even for a test.
You can collect the ref vector and move it up (collecting a vec of references is less taxing than cloning an array of txs).
</blockquote></details>

Done (I hope)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 200 at r4](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1vc6xS4bk0BNpvZnQz:-O1vc6xS4bk0BNpvZnR-:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c9e558b0f0406a61c3229f839b39a65c956b14da/crates/mempool/src/mempool_test.rs#L200)):*
> ```XML
>     let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
> 
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```





_Suggestion:_
```XML
    let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
    expected_mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442#-:-O1vkg5I-GY04bIzfYH5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1qQu0MBuKFMlMy5yQU:-O1vyNybEtDOW9a__jDe:b-c42n03) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L194)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why does the other one do? We're passing two iterables.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/mempool/442#-O1qQu0MBuKFMlMy5yQU:-O1wJzZV6oKyIcCpuCJu:bc3w1j8) ([raw file](https://github.com/starkware-libs/mempool/blob/f61102b354f0cdf46023eeddfec24c10c69430bd/crates/mempool/src/mempool_test.rs#L194)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why does the other one do? We're passing two iterables.
</blockquote></details>

It's an ownership issue during the creation of the second iterator.

The second iterator consumes add_tx_inputs (because of into_iter() which is needed so that we won't need to clone the txs).

This means that whatever the first iterators wants to do with add_tx_inputs has to end before it is consumed, in the line afterwards.
Collect does this, by concluding the `iter()` action, which implicitly keeps immutables references to all of `add_tx_inputs`'s entries until the iterator is run through (which is what collect does).

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/442#-:-O1wL3gt70SltQTK_weO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
