### PR TITLE
test(mempool): test get_txs with holes, single account

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/mempool/474#-O1ub7m6C672EOwpnaZL:-O1ub7m6C672EOwpnaZM:b-ag8lrv) ([raw file](https://github.com/starkware-libs/mempool/blob/1a69d909c3f4f21afaf51b62526b32054a7b62d1/crates/mempool/src/mempool_test.rs#L290)):*
> ```XML
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> }
> ```

We have such a test already, in which we also fill the hole afterwards.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/mempool/474#-O1ub7m6C672EOwpnaZL:-O1vBEda06bFLuvMZsQI:bfsbgqp) ([raw file](https://github.com/starkware-libs/mempool/blob/1a69d909c3f4f21afaf51b62526b32054a7b62d1/crates/mempool/src/mempool_test.rs#L290)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We have such a test already, in which we also fill the hole afterwards.
</blockquote></details>

which one?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/mempool/474#-O1ub7m6C672EOwpnaZL:-O1vGE2J76OPddovi7w4:b-egkiya) ([raw file](https://github.com/starkware-libs/mempool/blob/1a69d909c3f4f21afaf51b62526b32054a7b62d1/crates/mempool/src/mempool_test.rs#L290)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

which one?
</blockquote></details>

when using get_txs maybe?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/mempool/474#-O1ub7m6C672EOwpnaZL:-O1vJcbXEcXnPncP1WSa:bbnxzht) ([raw file](https://github.com/starkware-libs/mempool/blob/1a69d909c3f4f21afaf51b62526b32054a7b62d1/crates/mempool/src/mempool_test.rs#L290)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

when using get_txs maybe?
</blockquote></details>

#451 ?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
