### PR TITLE
chore: change component trait to component client trait and return re…

### PR DESCRIPTION
**Pull request by uriel-starkware**
…sult instead of value

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/278)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/278)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWl1QD9dsHXNIq6W1:-O0EWl1QD9dsHXNIq6W2:b26nx79) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L8)):*
> ```XML
> 
> pub type ResultA = ClientResult<ValueA>;
> pub type ResultB = ClientResult<ValueB>;
> ```

Please use `pub(crate)`.



_Code quote:_
```XML
pub type ResultA = ClientResult<ValueA>;
pub type ResultB = ClientResult<ValueB>;
```
___
*[`crates/mempool_infra/tests/common/mod.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWpAXC2bDogXEkMy6:-O0EWpAXC2bDogXEkMy7:brc6d6h) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L13)):*
> ```XML
> 
> #[async_trait]
> #[allow(dead_code)] // Due to clippy flipping out for unknown reason
> ```

Please rephrase in a formal manner, specifically, address the issue that each integration test is compiled as a different crate.



_Code quote:_
```XML
// Due to clippy flipping out for unknown reason
```
___
*[`crates/mempool_infra/tests/common/mod.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWgIWBB3dSZAYaI2o:-O0EWgIWBB3dSZAYaI2p:b26nx79) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L14)):*
> ```XML
> #[async_trait]
> #[allow(dead_code)] // Due to clippy flipping out for unknown reason
> pub trait ComponentAClientTrait: Send + Sync {
> ```

Please use `pub(crate)`.



_Code quote:_
```XML
pub
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/278)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWl1QD9dsHXNIq6W1:-O0Ebgd8Ab3lW88xgK8F:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L8)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use `pub(crate)`.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWpAXC2bDogXEkMy6:-O0Ebh619VEkQDyTRkfp:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rephrase in a formal manner, specifically, address the issue that each integration test is compiled as a different crate.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/common/mod.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/278#-O0EWgIWBB3dSZAYaI2o:-O0Ebir48ZX_IrG9ozPV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f04e01a8fa3324ad870a3b93fe514d6029ac020b/crates/mempool_infra/tests/common/mod.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use `pub(crate)`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/278#-:-O0EcFmHD-E2jRqXaghV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/278)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
