### PR TITLE
chore: add stateful transaction validator test

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 9 of 15 files at r3, 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: 3 of 15 files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`Cargo.toml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/56#-NvfhWrm3TbfnWsbZ8Jx:-NvfhWrm3TbfnWsbZ8Jy:b-89q77x) ([raw file](https://github.com/starkware-libs/mempool/blob/4c1b230e6d82e47d9db4596029383d1d84422ffa/Cargo.toml#L25)):*
> ```TOML
> axum = "0.6.12"
> # TODO(YaelD, 1/5/2024): Use a fixed version once the StarkNet API is stable.
> blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "d6bafcbb", features = ["testing"] }
> ```

Cool!



_Code quote:_
```TOML
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "d6bafcbb", features = ["testing"] }
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r3, 8 of 8 files at r4, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/mempool/56#-Nw-FgV3BmDft5SSVTox:-Nw-FgV3BmDft5SSVToy:bnavklm) ([raw file](https://github.com/starkware-libs/mempool/blob/1904043246ad4ac717b448850a5dce9e28320340/crates/gateway/src/starknet_api_test_utils.rs#L114)):*
> ```XML
> 
> pub const VALID_L1_GAS_MAX_AMOUNT: u64 = 1662;
> pub const VALID_L1_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> ```

Please move up to the beginning of the file.



_Code quote:_
```XML
pub const VALID_L1_GAS_MAX_AMOUNT: u64 = 1662;
pub const VALID_L1_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/mempool/56#-Nw-H-0g1G-uqnO1ytpg:-Nw-H-0g1G-uqnO1ytph:b-d8i8yt) ([raw file](https://github.com/starkware-libs/mempool/blob/1904043246ad4ac717b448850a5dce9e28320340/crates/gateway/src/stateful_transaction_validator_test.rs#L44)):*
> ```XML
>     #[case] expected_result: StatefulTransactionValidatorResult<()>,
> ) {
>     use blockifier::test_utils::initial_test_state::test_state_reader;
> ```

Why inside the test and not with the rest of the use statements?



_Code quote:_
```XML
use blockifier::test_utils::initial_test_state::test_state_reader;
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 85 at r6](https://reviewable.io/reviews/starkware-libs/mempool/56#-NwDqXlWC1m8tQvFUY5_:-NwDqXlWC1m8tQvFUY5a:bxat2y2) ([raw file](https://github.com/starkware-libs/mempool/blob/cf6eacaa65c0ff848dc9ae27c9b8388992118acb/crates/gateway/src/stateful_transaction_validator_test.rs#L85)):*
> ```XML
>         None,
>     );
>     assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
> ```

Try using `assert_matches!(...)`



_Code quote:_
```XML
assert_eq!
```

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 75 at r6](https://reviewable.io/reviews/starkware-libs/mempool/56#-NwDtQgx6BwwW5gsKO-D:-NwDtQgx6BwwW5gsKO-E:b-cjplfr) ([raw file](https://github.com/starkware-libs/mempool/blob/cf6eacaa65c0ff848dc9ae27c9b8388992118acb/crates/gateway/src/starknet_api_test_utils.rs#L75)):*
> ```XML
>     calldata: Calldata,
>     signature: TransactionSignature,
> ) -> ExternalTransaction {
> ```

a. Rebase (There is no `external_tx_for_testing` in this revision).

b. In another PR, please ensure there is just one `create_for_testing` method (both for each tx type and extend the generalized `external_tx_for_testing`). The more robust one should be what we use.
b.1. define a struct `ExteranlTransactionArgs`. Define default values for it (Use the default values whenever the function is called, and this makes sense). [Maybe: `ExteranlTransactionForTestingArgs`] 



_Code quote:_
```XML
pub fn external_invoke_tx_for_testing(
    resource_bounds: ResourceBoundsMapping,
    calldata: Calldata,
    signature: TransactionSignature,
) -> ExternalTransaction {
    executable_external_invoke_tx_for_testing(
        resource_bounds,
        Nonce::default(),
        ContractAddress::default(),
        calldata,
        signature,
    )
}

pub fn executable_external_invoke_tx_for_testing(
    resource_bounds: ResourceBoundsMapping,
    nonce: Nonce,
    sender_address: ContractAddress,
    calldata: Calldata,
    signature: TransactionSignature,
) -> ExternalTransaction {
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/mempool/56#-Nw-FgV3BmDft5SSVTox:-NwEkxdw1WUlmJ7Cn7q_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/1904043246ad4ac717b448850a5dce9e28320340/crates/gateway/src/starknet_api_test_utils.rs#L114)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move up to the beginning of the file.
</blockquote></details>

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 75 at r6](https://reviewable.io/reviews/starkware-libs/mempool/56#-NwDtQgx6BwwW5gsKO-D:-NwEpV7fDBDcEt1HBBgf:bucex1y) ([raw file](https://github.com/starkware-libs/mempool/blob/cf6eacaa65c0ff848dc9ae27c9b8388992118acb/crates/gateway/src/starknet_api_test_utils.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

a. Rebase (There is no `external_tx_for_testing` in this revision).

b. In another PR, please ensure there is just one `create_for_testing` method (both for each tx type and extend the generalized `external_tx_for_testing`). The more robust one should be what we use.
b.1. define a struct `ExteranlTransactionArgs`. Define default values for it (Use the default values whenever the function is called, and this makes sense). [Maybe: `ExteranlTransactionForTestingArgs`]
</blockquote></details>

added a TODO , will do in a separate PR
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/mempool/56#-Nw-H-0g1G-uqnO1ytpg:-NwEjm8A6vS1zsLq6XVW:b-ft9xf8) ([raw file](https://github.com/starkware-libs/mempool/blob/1904043246ad4ac717b448850a5dce9e28320340/crates/gateway/src/stateful_transaction_validator_test.rs#L44)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why inside the test and not with the rest of the use statements?
</blockquote></details>

I have no idea how this happened. fixing, done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 85 at r6](https://reviewable.io/reviews/starkware-libs/mempool/56#-NwDqXlWC1m8tQvFUY5_:-NwEou0a7f3piTzPjx4W:b9uxh03) ([raw file](https://github.com/starkware-libs/mempool/blob/cf6eacaa65c0ff848dc9ae27c9b8388992118acb/crates/gateway/src/stateful_transaction_validator_test.rs#L85)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Try using `assert_matches!(...)`
</blockquote></details>

it doesn't work with variables, only with patterns.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56#-:-NwhaPIs92b7gZJVVXgG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/56)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Pull request merged**
