### PR TITLE
docs: add documentation for component server

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:a2509b74

---

**Stack**:
- #222 ⬅
- #220

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/222)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/222#-O2PMSHR-SwWO8c1vG3y:-O2PRpXF6xzCy3lOW458:bpfblj) ([raw file](https://github.com/starkware-libs/mempool/blob/aa231df99170cac4d39ec5021b37b96cc76f9d3a/crates/mempool_infra/src/component_server.rs#L25)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I would change it to just saying that 'start' is blocking and not suggesting where/how to invoke it
</blockquote></details>

Slightly changed to address the concern.
___
*[`crates/mempool_infra/src/component_server.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/mempool/222#-O2PN4LbBHwHuNrCehqo:-O2PRvx7ABFbQhaJawX2:b5653of) ([raw file](https://github.com/starkware-libs/mempool/blob/aa231df99170cac4d39ec5021b37b96cc76f9d3a/crates/mempool_infra/src/component_server.rs#L68)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

This could be confusing, as having a start function is not a requirement for a component. I would prefer to see an example API function, such as `do_something(&mut self)`, instead, and that the `handle_request` will call or remove it entirely
</blockquote></details>

It actually is a requirement.

I added a usage example with a request and a response nonetheless.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/222)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/mempool/222#-O2PN4LbBHwHuNrCehqo:-O2PakGFADegnJN4lajP:b-82q4si) ([raw file](https://github.com/starkware-libs/mempool/blob/aa231df99170cac4d39ec5021b37b96cc76f9d3a/crates/mempool_infra/src/component_server.rs#L68)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

It actually is a requirement.

I added a usage example with a request and a response nonetheless.
</blockquote></details>

oh oops I missed it

**Review by uriel-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/222)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
