### PR TITLE
feat: remove deprecated network component from mempool

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #167
- #166 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/166#-Ny_GHJDC0qdQO_V7yA8:-Ny_GHJE3rtoYFAkTSq_:btru75m) (no related file):*
What about GW network component?

___

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/166#-Ny_GHJDC0qdQO_V7yA8:-Ny_L-UU9sukmk-y0H3w:b-30levd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about GW network component?
</blockquote></details>

Removed in the next pr, tried to keep them small
https://reviewable.io/reviews/starkware-libs/mempool/167

___

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/mempool/166#-Nyxfgn4A6MBNdBeDShx):*




_Suggestion:_
```
chore
```
___
*[`crates/mempool/src/mempool.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/mempool/166#-NyxhnQd3vveThEqISLt:-NyxhnQd3vveThEqISLu:b-3ckjj1) ([raw file](https://github.com/starkware-libs/mempool/blob/c5631b17ca42e130bec7df9384d1ac5edbb70a40/crates/mempool/src/mempool.rs#L108)):*
> ```XML
>     // potentially-concurrent operations is performed at a time. Therefore, the lock does not
>     // hinder the mempool's performance.
>     pub mempool: Mutex<Mempool>,
> ```

I see you have added a constructor.
Does it still need to be public?



_Code quote:_
```XML
pub
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/mempool/166#-NyxhnQd3vveThEqISLt:-NyzMwuf8ujeZ33RoV_3:b-uqjicd) ([raw file](https://github.com/starkware-libs/mempool/blob/c5631b17ca42e130bec7df9384d1ac5edbb70a40/crates/mempool/src/mempool.rs#L108)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I see you have added a constructor.
Does it still need to be public?
</blockquote></details>

For the time being yes, but this will change in the following prs.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r6, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool_test.rs` line 31 at r8](https://reviewable.io/reviews/starkware-libs/mempool/166#-NzX48iLEvJAJ5xqAYq9:-NzX48iLEvJAJ5xqAYqA:b-hi9too) ([raw file](https://github.com/starkware-libs/mempool/blob/1422c1aa3f513bfa480a705dff9af42f694d08ad/crates/mempool/src/mempool_test.rs#L31)):*
> ```XML
> }
> 
> fn create_for_testing(inputs: impl IntoIterator<Item = MempoolInput>) -> Mempool {
> ```

How is this different from [`Mempool::new`](https://github.com/starkware-libs/mempool/blob/1e291f71fbfed7da85cdcda8d2271620f951fa5a/crates/mempool/src/mempool.rs#L33)?



_Code quote:_
```XML
create_for_testing
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r6, 2 of 6 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#167](https://github.com/starkware-libs/mempool/pull/167)

**Pull request closed without merging**
