### PR TITLE
feat: create a macro for deploy account tx

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyxxwul3A7cXvsmPyKg:-NyxxwumC7IkgXuQqVoE:b-b03bzb) ([raw file](https://github.com/starkware-libs/mempool/blob/af655eb1bbcb87068690a8973f0cfd293da6bc24/crates/gateway/src/starknet_api_test_utils.rs#L305)):*
> ```XML
>             )
>         }
>         _ => panic!("Unsupported transaction version: {:?}.", deploy_tx_args.version),
> ```

perhaps I should create an error for this?



_Code quote:_
```XML
"Unsupported transaction version: {:?}.", deploy_tx_args.version
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/tests/routing_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyKDkv82L00n_Y9ti4:-NyyKDkv82L00n_Y9ti5:b-bbwnut) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/tests/routing_test.rs#L22)):*
> ```XML
> use tower::ServiceExt;
> 
> // TODO(Ayelet): add test cases for declare transaction.
> ```

Is the deploy account tx handled here?



_Code quote:_
```XML
// TODO(Ayelet): add test cases for declare transaction.
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_client.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyLAo38l-flAsfsIFj:-NyyLAo38l-flAsfsIFk:b-rt1ois) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/gateway_client.rs#L47)):*
> ```XML
>     // tests are boilerplate and implementation-detail free.
>     pub async fn add_tx(&self, tx: &ExternalTransaction) -> Response {
>         let tx_json = external_tx_to_json(tx.clone());
> ```

Can we change this function so that it does not take ownership?



_Suggestion:_
```XML
        let tx_json = external_tx_to_json(&tx);
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyxxwul3A7cXvsmPyKg:-NyyKjF-089PG6EIey1S:b-fvy1td) ([raw file](https://github.com/starkware-libs/mempool/blob/af655eb1bbcb87068690a8973f0cfd293da6bc24/crates/gateway/src/starknet_api_test_utils.rs#L305)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

perhaps I should create an error for this?
</blockquote></details>

If this is only a test util - there is no need.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 309 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyKUVf2O_apRWc3KMw:-NyyKUVf2O_apRWc3KMx:b-t3fptx) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L309)):*
> ```XML
> }
> 
> pub fn external_tx_to_json(tx: ExternalTransaction) -> String {
> ```

Can we rewrite the function such that it will not take ownership?



_Suggestion:_
```XML
pub fn external_tx_to_json(tx: &ExternalTransaction) -> String {
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyz9BNj2doG9hKqLFQ3:-Nyz9BNj2doG9hKqLFQ4:b-kz5am5) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L75)):*
> ```XML
>     version: Option<TransactionVersion>,
> ) -> ExternalTransaction {
>     let version = version.unwrap_or(TransactionVersion::THREE);
> ```

Please remove the version parameter from this function. Use only V3. 
See later comment as well.



_Suggestion:_
```XML
) -> ExternalTransaction {
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 247 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyz8FHR7t3hh7fGldQa:-Nyz8FHR7t3hh7fGldQb:b-9pvbs8) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L247)):*
> ```XML
>             signature: TransactionSignature::default(),
>             deployer_address: ContractAddress::default(),
>             version: TransactionVersion::ONE,
> ```

This is the default for this repo.



_Suggestion:_
```XML
            version: TransactionVersion::THREE,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_client.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyLAo38l-flAsfsIFj:-Nz3Gv4yCcxvIpFrpl1d:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/gateway_client.rs#L47)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Can we change this function so that it does not take ownership?
</blockquote></details>

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyz9BNj2doG9hKqLFQ3:-Nz3JPk36R7OXlWdYNlT:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please remove the version parameter from this function. Use only V3. 
See later comment as well.
</blockquote></details>

Done.
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 247 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-Nyz8FHR7t3hh7fGldQa:-Nz3FHqr4uQ8xalALOmZ:b-jg6ewz) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L247)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is the default for this repo.
</blockquote></details>

nice catch
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 309 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyKUVf2O_apRWc3KMw:-Nz3Fuoi6H7aIqIEnemK:b-tfgnfx) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/src/starknet_api_test_utils.rs#L309)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Can we rewrite the function such that it will not take ownership?
</blockquote></details>

apparently yes! Nice!
___
*[`crates/gateway/tests/routing_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/mempool/179#-NyyKDkv82L00n_Y9ti4:-Nz3Glvf0LzBYzGlFgRW:b-x5yuxr) ([raw file](https://github.com/starkware-libs/mempool/blob/20cd6c3af2ae07b7b3fc7c4373d818ef0bb9c1a3/crates/gateway/tests/routing_test.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is the deploy account tx handled here?
</blockquote></details>

nope. will do in a different PR.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/179#-:-Nz3PybQ9QvUVm-ChxqV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
