### PR TITLE
refactor: rename test util

### PR DESCRIPTION
**Pull request by giladchase**
It was a misnomer, we're asserting the queue, not the entire pool.

commit-id:181fcd98

---

**Stack**:
- #429
- #428
- #427
- #426 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1QYNtW4K-RIqgJguvK:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
> ```XML
> // transactions.
> #[track_caller]
> fn check_mempool_queue_eq(mempool: &Mempool, expected_queue: &[ThinTransaction]) {
> ```





_Suggestion:_
```XML
verify_mempool_queue
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1QawmzBTWphssz7kho:b8oqsjz) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
> ```XML
> // transactions.
> #[track_caller]
> fn check_mempool_queue_eq(mempool: &Mempool, expected_queue: &[ThinTransaction]) {
> ```

Do you want us to use verify_ as a consistent naming in such test utils?

I think we should have a consistent naming scheme for test_utils that only assert things, for readability. 
So readers will feel about them something similar to how they feel when they see assert_eq.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1QgaRt82qV_kdy7te2:byg431p) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do you want us to use verify_ as a consistent naming in such test utils?

I think we should have a consistent naming scheme for test_utils that only assert things, for readability. 
So readers will feel about them something similar to how they feel when they see assert_eq.
</blockquote></details>

Don't you think passing the expected argument makes it clear we're comparing?
I'm okay with a convention, but let's go with Rust conventions (something like `assert_eq_mempool_queue`).

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1R1E7P-iMEwPp4fMdx:b-pi89pb) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> Don't you think passing the expected argument makes it clear we're comparing?

Here yes, but in [PR 3 in the stack](https://reviewable.io/reviews/starkware-libs/mempool/428) I want to check two things, then assert_eq will look like i'm comparing them to each other :thinking:?
</blockquote></details>

Let's go with my suggestion, which sticks to Rust naming.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426#-:-O1R1LxV1r5NfP-hbZ7I:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1R5PLzCsdwZwUoGQA2:b-sc2zui) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's go with my suggestion, which sticks to Rust naming.
</blockquote></details>

You mean change this and PR 3 to `assert_*`?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1RC2oXCPk57gefoB_E:b-myib8o) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You mean change this and PR 3 to `assert_*`?
</blockquote></details>

Yes, `assert_eq_the_thing_we_assert_on`.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1RCAc0A5QQHf9WKnd9:b-xsudii) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, `assert_eq_the_thing_we_assert_on`.
</blockquote></details>

Also, let's write this convention down in #elinpool. :grimacing:

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/426)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/426#-O1QYNtVBAPz_6Xo-xqQ:-O1RsCJLA2OBVjAMbRlX:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/2af4855b7519830f6fccbc046adedede426cf325/crates/mempool/src/mempool_test.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also, let's write this convention down in #elinpool. :grimacing:
</blockquote></details>

Done

**Pull request merged**
