### PR TITLE
refactor: refactor AccountTransactionGenerator

### PR DESCRIPTION
**Pull request by giladchase**
Simplify usage.

commit-id:1b334549

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uUyQ_6UPtG_lqmaWv:-O1uUyQ_6UPtG_lqmaWw:bzbfq17) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L162)):*
> ```XML
>     // generator.
>     // Only used by the account transaction genreator, but owning it here is preferable over
>     // only distributing the ownership among the account generators.
> ```

Can you explain more?



_Code quote:_
```XML
    // Only used by the account transaction genreator, but owning it here is preferable over
    // only distributing the ownership among the account generators.
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uV5417YwVkoyJSNBM:-O1uV5417YwVkoyJSNBN:b-5cy31) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
> ```XML
>     // Only used by the account transaction genreator, but owning it here is preferable over
>     // only distributing the ownership among the account generators.
>     _nonce_manager: Rc<RefCell<NonceManager>>,
> ```

Consider aliasing: `SharedNonceManager`.
Q: why not fully-qualified names? Since those are two known `std` structs?



_Code quote:_
```XML
Rc<RefCell<NonceManager>>
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uUaPU0ZgI8Y8vTrm9:-O1uUaPV7cOpg05U8cbM:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L177)):*
> ```XML
>         let mut account_contracts = HashMap::new();
>         let nonce_manager = Rc::new(RefCell::new(NonceManager::default()));
>         for (account_id, contract) in accounts.into_iter().enumerate() {
> ```





_Suggestion:_
```XML
account
```

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uUyQ_6UPtG_lqmaWv:-O1u_zwyB980fFJawf2w:b-e8g2jo) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L162)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain more?
</blockquote></details>

nonce_manager is only used by `AccountTransactionGenerator`, and not used directly by `MultiAccountTransactionGenerator`.

Despite this, it seemed appropriate to own it here, since `NonceManager` managed nonces for multiple accounts by design, and owning it in a central location seemed to made sense, despite it not using it explicitly.

The alternative is to make only the `AccountTransactionGenerator` own the nonce_manager, which would still work, but would be a bit less intuitive that nonce_manager is really shared by all.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uV5417YwVkoyJSNBM:-O1uayfA3NTsM7eR7tBV:b-731t29) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
Done. 

> Q: why not fully-qualified names? Since those are two known `std` structs?

You mean you'd prefer `std::rc::Rc<std::cell::RefCell<NonceManager>>`?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1uV5417YwVkoyJSNBM:-O1ubQuY3tmuCD3Ro-1x:bu26gw5) ([raw file](https://github.com/starkware-libs/mempool/blob/46cded1cde8476b0f08d7bf018cdf87f8b8d8ba9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done. 

> Q: why not fully-qualified names? Since those are two known `std` structs?

You mean you'd prefer `std::rc::Rc<std::cell::RefCell<NonceManager>>`?
</blockquote></details>

jjjjjjjjjjjjjjjj
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1ubbfR-ukSOqPnOfLf:-O1ubbfR-ukSOqPnOfLg:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f4090d34182e2ce904c0471431ede33e6e5b8c34/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
> ```XML
>     // Invariant: nonces managed internally thorugh `generate` API of the account transaction
>     // generator.
>     // Only used by the account transaction genreator, but owning it here is preferable over
> ```





_Suggestion:_
```XML
 single account transaction generators
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1ubbfR-ukSOqPnOfLf:-O1ud2l-1u4KLbRvN8q3:bsxcns) ([raw file](https://github.com/starkware-libs/mempool/blob/f4090d34182e2ce904c0471431ede33e6e5b8c34/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
> ```XML
>     // Invariant: nonces managed internally thorugh `generate` API of the account transaction
>     // generator.
>     // Only used by the account transaction genreator, but owning it here is preferable over
> ```

OK that i removed the `single`? It might be confusing

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1ubbfR-ukSOqPnOfLf:-O1ueLwm8-Ikzyp1TvNO:b-jd2vz3) ([raw file](https://github.com/starkware-libs/mempool/blob/f4090d34182e2ce904c0471431ede33e6e5b8c34/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

OK that i removed the `single`? It might be confusing
</blockquote></details>

I added it so the difference from "multi" is clear; your call.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477#-:-O1ueYFj--msTKPH8x-_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/mempool/477#-O1ubbfR-ukSOqPnOfLf:-O1uerk5B3VQEfJnYQKM:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/f4090d34182e2ce904c0471431ede33e6e5b8c34/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L163)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I added it so the difference from "multi" is clear; your call.
</blockquote></details>

Done

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/477)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
