### PR TITLE
refactor: use axum instead of hyper

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
Nice!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17#-:-NuXvn8-DePllGkFNOLs:b-83sjoh)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuXq4eE8QA5wnpp7mND):*
Please squash.



_Code quote:_
```
- b8a41a2: Implement add_transaction in Gateway

- ca6fa8f: refactor(gateway): use axum instead of hyper
```
___
*[`crates/gateway/src/gateway_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuXvtmy4ZBF2jMMmjp2:-NuXvtmz4w02u6H1DyLM:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L18)):*
> ```XML
> async fn test_add_transaction(#[case] json_file_path: &str, #[case] expected_response: &str) {
>     let json_str = std::fs::read_to_string(json_file_path).expect("Failed to read JSON file");
>     let json: ExternalTransaction = serde_json::from_str(&json_str).expect("Failed to parse JSON");
> ```





_Suggestion:_
```XML
transaction
```
___
*[`crates/gateway/src/gateway_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuXw-dg-IvgKTNV_GTR:-NuXw-dg-IvgKTNV_GTS:b-o4bccm) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L19)):*
> ```XML
>     let json_str = std::fs::read_to_string(json_file_path).expect("Failed to read JSON file");
>     let json: ExternalTransaction = serde_json::from_str(&json_str).expect("Failed to parse JSON");
>     let response = add_transaction(json.clone().into()).await.into_response();
> ```

Why clone is needed here?



_Code quote:_
```XML
json.clone()
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuY2lfd0-L2Y2gQeTl-:-NuY2lfd0-L2Y2gQeTl0:b-8xuvot) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway.rs#L29)):*
> ```XML
>             .route("/add_transaction", post(add_transaction));
> 
>         let _ = axum::Server::bind(&addr)
> ```

Plz add comment on what this does and how it behaves
___
*[`crates/gateway/src/gateway.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuY2qI0BRA-SSzxYNNi:-NuY2qI1EEgja7XfNrBa:b-dc7ash) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway.rs#L32)):*
> ```XML
>             .serve(app.into_make_service())
>             .await
>             .map_err(|_| GatewayError::ServerStartError);
> ```

This should be a `?`, and also I'm not sure how this works because the actual error is suppressed (with `_`).

Let's adhere to the docs and `unwrap` here, but add a TODO to check this out, could this fail with network error? if it can then it should be returned as an error to the user (so they'll fix their network issue)



_Code quote:_
```XML
            .map_err(|_| GatewayError::ServerStartError);
```
___
*[`crates/gateway/src/gateway_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuYdeX85q6pJKepXRav:-NuYdeX85q6pJKepXRaw:bhpsek) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L16)):*
> ```XML
> #[case("./src/json_files_for_testing/invoke_v3.json", "INVOKE")]
> #[tokio::test]
> async fn test_add_transaction(#[case] json_file_path: &str, #[case] expected_response: &str) {
> ```

add negative test, separate test.
___
*[`crates/gateway/src/gateway_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuYcmM106uePlAGnYpQ:-NuYcmM106uePlAGnYpR:b-h5cirs) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L18)):*
> ```XML
> async fn test_add_transaction(#[case] json_file_path: &str, #[case] expected_response: &str) {
>     let json_str = std::fs::read_to_string(json_file_path).expect("Failed to read JSON file");
>     let json: ExternalTransaction = serde_json::from_str(&json_str).expect("Failed to parse JSON");
> ```

Always prefer [from_reader](https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html) over from_string if all you want it so parse a json _file_



_Code quote:_
```XML
    let json_str = std::fs::read_to_string(json_file_path).expect("Failed to read JSON file");
    let json: ExternalTransaction = serde_json::from_str(&json_str).expect("Failed to parse JSON");
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuY2lfd0-L2Y2gQeTl-:-NuYiseWAnbhR-RKudgX:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz add comment on what this does and how it behaves
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuY2qI0BRA-SSzxYNNi:-NuYgB_z7xltZ3pdZcXt:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This should be a `?`, and also I'm not sure how this works because the actual error is suppressed (with `_`).

Let's adhere to the docs and `unwrap` here, but add a TODO to check this out, could this fail with network error? if it can then it should be returned as an error to the user (so they'll fix their network issue)
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuYcmM106uePlAGnYpQ:-NuYhFr87e8SUWd8mOH1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Always prefer [from_reader](https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html) over from_string if all you want it so parse a json _file_
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/mempool/17#-NuYdeX85q6pJKepXRav:-NuYkx9r8sqeGfFjY1cR:b-afbhlz) ([raw file](https://github.com/starkware-libs/mempool/blob/ca6fa8f39992c7e93118d32bfe12abc08936653c/crates/gateway/src/gateway_test.rs#L16)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

will be done in next PR
</blockquote></details>

when checking build_server

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/17#-:-NuYl_hf45eJVXFl1j51:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
