### PR TITLE
feat: add mock batcher and implement as a wrapper in integration test

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/tests-integration/src/mock_batcher.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0i4rSMBsEYvRigsGki:-O0i4rSN6dEWcCm_CdKH:bkycx5s) ([raw file](https://github.com/starkware-libs/mempool/blob/ebb3d3ff87773ee92b7cfe4866f8972952663bab/crates/tests-integration/src/mock_batcher.rs#L10)):*
> ```XML
> #[derive(Clone)]
> pub struct MockBatcher {
>     mempool_client: MempoolClientImpl,
> ```

Why does it implement `add_tx`?
Maybe we should have a trait for Mempool <-> Batcher communication?



_Code quote:_
```XML
mempool_client: MempoolClientImpl,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/tests-integration/src/mock_batcher.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0i8b9i9HS7sgVjSAqW:-O0i8b9i9HS7sgVjSAqX:bzeg1ax) ([raw file](https://github.com/starkware-libs/mempool/blob/ebb3d3ff87773ee92b7cfe4866f8972952663bab/crates/tests-integration/src/mock_batcher.rs#L15)):*
> ```XML
> impl MockBatcher {
>     pub fn new(
>         mempool: Sender<ComponentRequestAndResponseSender<MempoolRequest, MempoolResponse>>,
> ```

Should it be renamed to `sender`?



_Code quote:_
```XML
mempool
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332#-:-O0nYepPDPY_tEU9Yg-2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/tests-integration/src/mock_batcher.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0i4rSMBsEYvRigsGki:-O0nY4XnDoKlGnHxFqnm:b-klgmc7) ([raw file](https://github.com/starkware-libs/mempool/blob/ebb3d3ff87773ee92b7cfe4866f8972952663bab/crates/tests-integration/src/mock_batcher.rs#L10)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>Why does it implement `add_tx`?

This was the requirement.

The requirement was to have a trait that represents the mempool fully, so that it can either be represented by the infra communication layer, or by the mempool itself.

> Maybe we should have a trait for Mempool <-> Batcher communication?

I see why you're referring this, but it'd contradict the above requirement.
</blockquote></details>

The requirement is a bit weird, as we now have a Batcher that can send a transaction!

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/tests-integration/Cargo.toml` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0t1HNY3cg8_f9cUIO6:-O0wXTsx-SAwxATGEGpO:bm1r00q) ([raw file](https://github.com/starkware-libs/mempool/blob/9e57a3ef4304de4df575c8783307ba9bcfc39d21/crates/tests-integration/Cargo.toml#L25)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Out of curiosity, what's the difference between them?
</blockquote></details>

i have no idea

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/tests-integration/src/mock_batcher.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0i4rSMBsEYvRigsGki:-O0wbkFJ0LAJaUSjbot0:bz9vpno) ([raw file](https://github.com/starkware-libs/mempool/blob/ebb3d3ff87773ee92b7cfe4866f8972952663bab/crates/tests-integration/src/mock_batcher.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The requirement is a bit weird, as we now have a Batcher that can send a transaction!
</blockquote></details>

That you're describing, i think, is an authentication scheme, with users and roles.

This needs to be added separately at some point, perhaps even into the mempool itself, but it could also be added at the infra level.

In any case, this is a separate abstraction.
One which is independent from the infra itself, and the mempol's API.

The alternative, of warding things off _at the API level_, would probably make our type system more convoluted than it needs to be.
It can be done, and it'd work, but since we're gonna have to do some kind of user roles at some point, we might as well put that behavior there, which is a more natural location for it.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/332#-:-O0wg_ty28_naXDmGvW6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/tests-integration/Cargo.toml` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/332#-O0t1HNY3cg8_f9cUIO6:-O0wg2Je4a_irtWd3gVd:bkru6dh) ([raw file](https://github.com/starkware-libs/mempool/blob/9e57a3ef4304de4df575c8783307ba9bcfc39d21/crates/tests-integration/Cargo.toml#L25)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

i have no idea
</blockquote></details>

The version thing isn't really necessary for us yet, it is basically to appease crates.io, which doesn't support `path` dependencies.

So when we do publish, which we haven't thus far, we'll need to assign the current version in addition to the path, for every path dependency we have.

**Pull request merged**
