### PR TITLE
feat: improve mempool_test debug print

### PR DESCRIPTION
**Pull request by giladchase**
Previous assertion wasn't informative enough on fail.

commit-id:4b2c49c7

---

**Stack**:
- #429
- #428
- #427 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/mempool/427#-O1QYoNs9OibFHqd7dSW:-O1QYoNs9OibFHqd7dSX:b-tuotpi) ([raw file](https://github.com/starkware-libs/mempool/blob/af91bffc9ff015f05f4d8d4ad0ff885a6b3e3ea4/crates/mempool/src/mempool_test.rs#L63)):*
> ```XML
> 
>     for (i, (expected_tx, mempool_tx)) in enumerate(zip_eq(expected_queue, mempool_txs)) {
>         assert_eq!(expected_tx, *mempool_tx, "{i}'th tx in the queue doesn't equal the expected");
> ```

Are both transactions formatted into the error mesasge?



_Suggestion:_
```XML
Transaction {i} in the queue is not as expected
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427#-:-O1Qbty_Amje8McdqmxT:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
