### PR TITLE
chore: change the type of chain info member of stateful transaction validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#132** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/132?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#142** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/142?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyJROstEuAh8A2kVu57:-NyJROstEuAh8A2kVu58:b-aahoxp) ([raw file](https://github.com/starkware-libs/mempool/blob/ddc2fb063970bf2193b8b0ab80e49d31c2500124/crates/gateway/src/stateful_transaction_validator.rs#L83)):*
> ```XML
>     pub strk_fee_token_address: ContractAddress,
>     pub eth_fee_token_address: ContractAddress,
> }
> ```

why not use the same ChainInfo struct and move is to SNAPI?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyJROstEuAh8A2kVu57:-NyKWOb3BrTER5uKYOwb:b4r2zxq) ([raw file](https://github.com/starkware-libs/mempool/blob/ddc2fb063970bf2193b8b0ab80e49d31c2500124/crates/gateway/src/stateful_transaction_validator.rs#L83)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not use the same ChainInfo struct and move is to SNAPI?
</blockquote></details>

I created a PR in Blockifier to add the required implementations for `ChainInfo`: https://reviewable.io/reviews/starkware-libs/blockifier/1896#-

I added it here as a temporary measure - to avoid conflicts with Blockifier. This can be deleted if it is addressed in blockifier.

I added a todo.

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142#-:-NyLIaeU61oOdxPk28lY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPhIGiEgvJfPQRiGKF:-NyPhIGjAMC8dyDdERow:b-u1jnzv) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator.rs#L80)):*
> ```XML
> // TODO(Arni): Remove this struct once Chain info supports Papyrus serialization.
> #[derive(Clone, Debug)]
> pub struct ChainInfoConfig {
> ```

Please move it to `config.rs`
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPhfdh2gwmMWbD-wI4:-NyPhfdh2gwmMWbD-wI5:bighsx2) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator.rs#L88)):*
> ```XML
> impl From<ChainInfoConfig> for ChainInfo {
>     fn from(chain_info: ChainInfoConfig) -> Self {
>         ChainInfo {
> ```

Please use `Self` here as you did in the other From impl below. Mainly for consistency.



_Code quote:_
```XML
ChainInfo
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPiJHP-BNJAJasmIOI:-NyPiJHP-BNJAJasmIOJ:b-u3neng) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
> ```XML
>             validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
>             max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
>             chain_info: block_context.chain_info().clone().into(),
> ```

Do we still need this clone?



_Code quote:_
```XML
.clone()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPhIGiEgvJfPQRiGKF:-NyPjjHD7-oNGeyeCQwM:b-ygdyi8) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move it to `config.rs`
</blockquote></details>

Done in the next PR. #144.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPhfdh2gwmMWbD-wI4:-NyPkXMx3Hr60TXqIeib:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator.rs#L88)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please use `Self` here as you did in the other From impl below. Mainly for consistency.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/mempool/142#-NyPiJHP-BNJAJasmIOI:-NyPkonQBxySiYHn1dXc:b-zc7cup) ([raw file](https://github.com/starkware-libs/mempool/blob/3391f248c41ad5faeeafee1890739e6bbea7ea99/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we still need this clone?
</blockquote></details>

Yes. Into takes ownership. :(

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142#-:-NyUAtKy9sMKKoGVc74a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/142)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
