### PR TITLE
fix: fix compilation by fixing crates structure

### PR DESCRIPTION
**Pull request by giladchase**
Also add lints and metadata

---

**Stack**:
- #11
- #10
- #9
- #8
- #7 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/7)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/7#-NtMNINP5gKSuNGDOEPN:-NtMNINP5gKSuNGDOEPO:b-58vfk0) ([raw file](https://github.com/starkware-libs/mempool/blob/84aee895145b5825b9f43b9b805db9af0d617c89/Cargo.toml#L9)):*
> ```TOML
> edition = "2021"
> repository = "https://github.com/starkware-libs/mempool/"
> license = "Apache-2.0"
> ```

Why you didnt add:
license-file = "LICENSE"



_Code snippet:_
```TOML
license-file = "LICENSE"
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/7)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`Cargo.toml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/7#-NtMNINP5gKSuNGDOEPN:-NtPmiIX8e4haFmCIiO-:b-zfb4fu) ([raw file](https://github.com/starkware-libs/mempool/blob/84aee895145b5825b9f43b9b805db9af0d617c89/Cargo.toml#L9)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why you didnt add:
license-file = "LICENSE"
</blockquote></details>

Not necessary if we're using a standard `license` like Apache-2.0 --- if you remember, when you publish the blockifier it whined about having both a standard license and license-file.

However, we should still have a LICENSE file i think, for github, which AFAICS requires it, so i added it on top of the stack.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/7#-:-NtQ0tMY2HpL6FlF59wC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by giladchase — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
