### PR TITLE
feat: add multi-nonce support

### PR DESCRIPTION
**Pull request by giladchase**
commit-id:c822f343

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1QoyzW1CDVkJ2Br_bL:-O1QoyzW1CDVkJ2Br_bM:bi4m20v) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool.rs#L120)):*
> ```XML
> }
> 
> fn is_queuable(tx_reference: TransactionReference, account: Account) -> bool {
> ```

why not name it something that is nonce-related?



_Code quote:_
```XML
is_queuable
```
___
*[`crates/mempool/src/mempool_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq3dO7gSBSBXJGObb:-O1Qq3dO7gSBSBXJGObc:b-ghnuzi) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L23)):*
> ```XML
> 
> /// Creates a valid input for mempool's `add_tx` with optional default values.
> /// Usage:
> ```

Add the new usage here
___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1Qq-7q047pK645xwtN:bsh63au) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
> ```XML
>         MempoolInput { tx, account }
>     }};
>     // Pattern for four arguments.
> ```

I think those lines are confusing

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1R0UiX0uYwChu5g8aQ:-O1R0UiX0uYwChu5g8aR:bycixhp) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool.rs#L120)):*
> ```XML
> }
> 
> fn is_queuable(tx_reference: TransactionReference, account: Account) -> bool {
> ```

WDYT of a short method of `TranasctionReference`?



_Suggestion:_
```XML
is_eligible_for_sequencing
```
___
*[`crates/mempool/src/mempool_test.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1R13jGCs_qajeXyk6B:-O1R13jGCs_qajeXyk6C:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L146)):*
> ```XML
>         add_tx_input!(tx_hash: 2, sender_address: "0x1", tx_nonce: 0_u8,account_nonce: 0_u8);
> 
>     let input_address_0_nonce_1 =
> ```





_Suggestion:_
```XML
        add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
    let input_address_1 =
        add_tx_input!(tx_hash: 2, sender_address: "0x1", tx_nonce: 0_u8,account_nonce: 0_u8);
    let input_address_0_nonce_1 =
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1QoyzW1CDVkJ2Br_bL:-O1Rp1wn7BGINP5C5GYj:b-3pwusz) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not name it something that is nonce-related?
</blockquote></details>

Cause it's an implementation detail --- if we decide too add anything to the queueability check, we'll have to change the function name? this is too fragile.

Also, is_queueable communicates the behavior, if it were something-with-nonce, the reader will have to translate it themselves into "this is a queuability check? because according to it they decide to insert or not", so might as well do that for them.

if they want to know the queueability internals they can step-in, but they might not, so no need to force it on them.
___
*[`crates/mempool/src/mempool.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1R0UiX0uYwChu5g8aQ:-O1RpcreC9sWhpPBC0X7:bixl9t7) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of a short method of `TranasctionReference`?
</blockquote></details>

That means TransactionReference will have to be aware of Account? is that legit?
___
*[`crates/mempool/src/mempool_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq3dO7gSBSBXJGObb:-O1RqH3ACDLXjwuQNRtk:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L23)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Add the new usage here
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1RqIqW4EaByXl5VthK:b-v5r2ew) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think those lines are confusing
</blockquote></details>

which lines?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429#-:-O1RrEcaDj73FD5IaLrI:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1R0UiX0uYwChu5g8aQ:-O1Rr6lvAPCEsQwdVc2B:bdogdhe) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That means TransactionReference will have to be aware of Account? is that legit?
</blockquote></details>

Not sure, maybe later. :grimacing:

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1VFKTv3GXMGSILP3MX:b-335c02) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

which lines?
</blockquote></details>

"Pattern for x arguments."
___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1VFWjW1ZNQPJbNPCCS:b-j7sc5q) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
> ```XML
> /// Usage:
> /// 1. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)
> /// 1. add_tx_input!(tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)
> ```

fix the counting



_Code quote:_
```XML
1
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1VV3GL6byeuVKC8Dx1:b-y7if0b) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

"Pattern for x arguments."
</blockquote></details>

@elintul asked for them :grimacing: 
Do you have a suggestion for something else? 
I'd rather have _some_ documentation over none, since macros are hard to read.
___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1VUl8l-I2EiSff89CX:b-kepimm) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fix the counting
</blockquote></details>

Just to be sure, you think it'd be more readable than keeping the numbering form the other cases?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1VdZdv8DRdcfhDQU6-:b-27s8cc) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@elintul asked for them :grimacing: 
Do you have a suggestion for something else? 
I'd rather have _some_ documentation over none, since macros are hard to read.
</blockquote></details>

maybe "Pattern for tx_hash, sender_address... etc"?
___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1VhCmCBr3spdC2biH7:b-skf1fd) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just to be sure, you think it'd be more readable than keeping the numbering form the other cases?
</blockquote></details>

fix to 1,2,3,4 instead of 1,1,2,3

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1WZEnB5BQ1tqdMsrNu:b-p0h4fe) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

maybe "Pattern for tx_hash, sender_address... etc"?
</blockquote></details>

That's what i originally put there, but elin preferred the `x arguments`, can you talk to her about it plz so you can reach an agreement? 
___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1WZf3sDmWkkxYVM3ha:b1jem5b) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fix to 1,2,3,4 instead of 1,1,2,3
</blockquote></details>

I don't follow :thinking:  where is there a 1,1,2,3?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1W_3om3tN8-s4qvvVy:b-491jdt) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I don't follow :thinking:  where is there a 1,1,2,3?
</blockquote></details>

/// 1. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)
/// 1. add_tx_input!(tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1VFWjVDMTqdblzsPTC:-O1W_dHhBf1ut-vOvvx6:bnm0f7l) ([raw file](https://github.com/starkware-libs/mempool/blob/06e107aa9c6c739e0d8b4b151ffae291750de7d8/crates/mempool/src/mempool_test.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

/// 1. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)
/// 1. add_tx_input!(tx_hash: 2, sender_address: 3_u8, tx_nonce: 4, account_nonce: 3)
</blockquote></details>

:facepalm: oh tnx

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1Wa8YZ4DtCwajYpdN-:bb7oryy) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That's what i originally put there, but elin preferred the `x arguments`, can you talk to her about it plz so you can reach an agreement?
</blockquote></details>

sure

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/mempool/429#-O1Qq-7q047pK645xwtM:-O1WjemX00kKGQ-CxadG:b-2xcd1z) ([raw file](https://github.com/starkware-libs/mempool/blob/205665e44e8965a1381cf57d243d6d52f9556331/crates/mempool/src/mempool_test.rs#L42)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

sure
</blockquote></details>

Let's not block on this though. :grimacing:

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
