### PR TITLE
test(mempool): add mempool state struct and new function

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1He18H7mudZ9nv2ndM:-O1He18H7mudZ9nv2ndN:b-y4pz3m) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L20)):*
> ```XML
>     tx_pool: TransactionPool,
>     tx_queue: TransactionQueue,
> }
> ```

Is it only used in `mempool_test`? Do we have scenarios to use this util in E2E or in other files?



_Code quote:_
```XML
struct MempoolState {
    tx_pool: TransactionPool,
    tx_queue: TransactionQueue,
}
```
___
*[`crates/mempool/src/mempool_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HdZcX-6jWwnoZRSoc:-O1HdZcX-6jWwnoZRSod:b-pmkq20) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L27)):*
> ```XML
>         for tx in pool_txs {
>             tx_pool.insert(tx).unwrap();
>         }
> ```

Please implement `from([ThinTx])` method.
It can be done in a separate PR.



_Suggestion:_
```XML
        let mut tx_pool = TransactionPool::from(pool_txs);
```
___
*[`crates/mempool/src/mempool_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HdwPoALYTqVUs5B-w:-O1HdwPoALYTqVUs5B-x:b-hbcorw) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L32)):*
> ```XML
>         for tx in queue_txs {
>             tx_queue.insert(TransactionReference::new(&tx));
>         }
> ```

The same.



_Code quote:_
```XML
        let mut tx_queue = TransactionQueue::default();
        for tx in queue_txs {
            tx_queue.insert(TransactionReference::new(&tx));
        }
```
___
*[`crates/mempool/src/mempool_test.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HeSF82gwtJf2nT-BY:-O1HeSF82gwtJf2nT-BZ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L113)):*
> ```XML
>     let n_txs = txs.len();
> 
>     let mempool_state = MempoolState::new(txs.clone(), txs);
> ```





_Suggestion:_
```XML
    let txs = [
        input_tip_50_address_0.clone().tx,
        input_tip_100_address_1.clone().tx,
        input_tip_10_address_2.clone().tx,
    ];
    let n_txs = txs.len();

    let mempool_state = MempoolState::new(txs.clone(), txs.to_vec());
```
___
*[`crates/mempool/src/mempool_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1He_iL4VdidZ5GM9mj:-O1He_iL4VdidZ5GM9mk:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L114)):*
> ```XML
> 
>     let mempool_state = MempoolState::new(txs.clone(), txs);
>     let mut mempool: Mempool = mempool_state.into();
> ```





_Suggestion:_
```XML
        let mut mempool: Mempool = MempoolState::new(txs.clone(), txs).into();
```

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1H8JdO68HeS061VMY_:-O1H8JdPCa0cJdHHk_e5:b-t06s89) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L17)):*
> ```XML
> use crate::transaction_queue::TransactionQueue;
> 
> struct MempoolState {
> ```

Shortly document.



_Code quote:_
```XML
MempoolState
```
___
*[`crates/mempool/src/mempool_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1LUbyaAewQVyxNnhGL:-O1LUbyaAewQVyxNnhGM:b6lktpm) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L39)):*
> ```XML
> 
> impl From<MempoolState> for Mempool {
>     fn from(state: MempoolState) -> Mempool {
> ```

`state` by itself is confusing, since we use it in many other locations.



_Suggestion:_
```XML
mempool_state: MempoolState
```
___
*[`crates/mempool/src/mempool_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1LUXsKAFb8mX_Ue5Fm:-O1LUXsKAFb8mX_Ue5Fn:b-micl48) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L40)):*
> ```XML
> impl From<MempoolState> for Mempool {
>     fn from(state: MempoolState) -> Mempool {
>         Mempool { tx_pool: state.tx_pool, tx_queue: state.tx_queue }
> ```

Unpack `state` first.



_Code quote:_
```XML
tx_pool: state.tx_pool, tx_queue: state.tx_queue
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1He18H7mudZ9nv2ndM:-O1Mx4yQEC56RpcYbCCA:bvbkozz) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L20)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it only used in `mempool_test`? Do we have scenarios to use this util in E2E or in other files?
</blockquote></details>

IDK yet. For now, it's for unit test cases.
___
*[`crates/mempool/src/mempool_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HdZcX-6jWwnoZRSoc:-O1MudqaCKSISCyS-VMu:b-eqvbnd) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L27)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please implement `from([ThinTx])` method.
It can be done in a separate PR.
</blockquote></details>

Done + #419
___
*[`crates/mempool/src/mempool_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HdwPoALYTqVUs5B-w:-O1Muk0X27plsPAcJzjM:b-eqvbnj) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The same.
</blockquote></details>

Done + #413
___
*[`crates/mempool/src/mempool_test.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1HeSF82gwtJf2nT-BY:-O1Mvjfu09Ia0SahhzgO:big2y56) ([raw file](https://github.com/starkware-libs/mempool/blob/588263000b11cbaeb1c4c19110d468eeacbef997/crates/mempool/src/mempool_test.rs#L113)):*
> ```XML
>     let n_txs = txs.len();
> 
>     let mempool_state = MempoolState::new(txs.clone(), txs);
> ```

Done, but why is that better?

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1RUZwd2_OHSFblVmzX:-O1RUZweElELxjgpgqyq:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f38b0b77158eb831ef8772fc6ed62c9a1938bac3/crates/mempool/src/mempool_test.rs#L18)):*
> ```XML
> 
> /// `MempoolState` is a utility struct for testing mempool scenarios. It allows the creation of
> /// different mempool states, without following the regular mempool behavior.
> ```





_Suggestion:_
```XML
/// Represents the internal state of the mempool.
/// Enables customized (and potentially inconsistent) creation for unit testing.
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1Ra7fd8ckqGh6hFcd8:-O1Ra7fd8ckqGh6hFcd9:b-otckqr) ([raw file](https://github.com/starkware-libs/mempool/blob/c8548e1fb9072f8c1a2f24ddb5b42406f4e59c88/crates/mempool/src/mempool_test.rs#L31)):*
> ```XML
>     {
>         let tx_pool = pool_txs.into_iter().collect();
>         let tx_queue = queue_txs.into_iter().collect();
> ```

Add type annotations?



_Code quote:_
```XML
        let tx_pool = pool_txs.into_iter().collect();
        let tx_queue = queue_txs.into_iter().collect();
```
___
*[`crates/mempool/src/mempool_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1R_YpxCkMk-eKYiN-Z:-O1R_YpxCkMk-eKYiN-_:bls5ctv) ([raw file](https://github.com/starkware-libs/mempool/blob/c8548e1fb9072f8c1a2f24ddb5b42406f4e59c88/crates/mempool/src/mempool_test.rs#L141)):*
> ```XML
> 
>     // This ensures we do not exceed the number of transactions available in the mempool.
>     let max_requested_txs = requested_txs.min(txs_input.len());
> ```

Maybe use `MempoolState` for the assertions in the end as well?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1RgzzjBCn_KqdHO4U5:-O1RgzzjBCn_KqdHO4U6:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/371fdd0550595ce9f151dab2935176025ad4f938/crates/mempool/src/mempool_test.rs#L136)):*
> ```XML
>         txs_input[0].clone(), // tip 50
>         txs_input[2].clone(), // tip 10
>     ];
> ```





_Suggestion:_
```XML
    let add_tx_inputs = [
        add_tx_input!(tip: 50, tx_hash: 1),
        add_tx_input!(tip: 100, tx_hash: 2, sender_address: "0x1"),
        add_tx_input!(tip: 10, tx_hash: 3, sender_address: "0x2"),
    ];
    let txs_iterator = txs_input.iter().map(|input| &input.tx);
    let tx_references_iterator = txs_iter.map(TransactionReference::new);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1RgzzjBCn_KqdHO4U5:-O1VkR0R3RF5sU8mBJkY:b7nleax) ([raw file](https://github.com/starkware-libs/mempool/blob/371fdd0550595ce9f151dab2935176025ad4f938/crates/mempool/src/mempool_test.rs#L136)):*
> ```XML
>         txs_input[0].clone(), // tip 50
>         txs_input[2].clone(), // tip 10
>     ];
> ```

It doesn't work. I'm leaving a TODO and will get back to it later.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1RgzzjBCn_KqdHO4U5:-O1WZyR43WIGRuoszU3A:boajdde) ([raw file](https://github.com/starkware-libs/mempool/blob/371fdd0550595ce9f151dab2935176025ad4f938/crates/mempool/src/mempool_test.rs#L136)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It doesn't work. I'm leaving a TODO and will get back to it later.
</blockquote></details>

"It doesn't work"
Please explain why / add compilation errors (can be in Slack), so we'd understand why.
Also, note the variable names I suggested.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 138 at r6](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1WoaMkBMrzdvw0S53x:-O1WoaMkBMrzdvw0S53y:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/1a213142ea071725ae6213fd6238eb87fbc5b495/crates/mempool/src/mempool_test.rs#L138)):*
> ```XML
> fn test_get_txs(#[case] requested_txs: usize) {
>     // TODO(Ayelet): Avoid cloning the transactions in the test.
>     let add_tx_input = [
> ```





_Suggestion:_
```XML
add_tx_inputs
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1RgzzjBCn_KqdHO4U5:-O1X3YySC4jQiyz-G6PD:b-vn34nj) ([raw file](https://github.com/starkware-libs/mempool/blob/371fdd0550595ce9f151dab2935176025ad4f938/crates/mempool/src/mempool_test.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

"It doesn't work"
Please explain why / add compilation errors (can be in Slack), so we'd understand why.
Also, note the variable names I suggested.
</blockquote></details>

I'm working on reducing cloning in the following PR (when `MempoolState`'s `assert_eq_mempool_state` replaces `assert_eq_mempool_queue`) #431 (not ready yet).
Also, I fixed the names.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 155 at r7](https://reviewable.io/reviews/starkware-libs/mempool/399#-O1g0tMz5JEsfNZ11Dsu:-O1g0tMz5JEsfNZ11Dsv:bdbjpc3) ([raw file](https://github.com/starkware-libs/mempool/blob/6b7b20a480ba8c9238c7053540a5fc7c6322fb9a/crates/mempool/src/mempool_test.rs#L155)):*
> ```XML
>         add_tx_inputs[0].tx.clone(), // tip 50
>         add_tx_inputs[2].tx.clone(), // tip 10
>     ];
> ```

Let's sort in-place, as discussed offline.



_Code quote:_
```XML
    let sorted_txs = [
        add_tx_inputs[1].tx.clone(), // tip 100
        add_tx_inputs[0].tx.clone(), // tip 50
        add_tx_inputs[2].tx.clone(), // tip 10
    ];
```

**Pull request merged**
