### PR TITLE
chore: upgrade sn-api dependency

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343)

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/343#-O0x2yNk9I7lxtuj-HzK:-O0x2mTb8VtEgtw1bZOl:b9i60zd) (no related file):*
Only `RPC -> Rpc`? Add a hint for the reviewer. 

___

**Review by giladchase — COMMENTED** [review]
is this PR still relevant?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343#-:-O1WaDYS0iBzaT8_GVO6:bg9nxod)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
Yes, we are waiting for @elintul to merge `main-mempool` -> `main` in `sn_api` repo.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343#-:-O1WaSKLDM2w1H-OFGVG:b-u6xseg)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/343#-O0x2yNk9I7lxtuj-HzK:-O1WaRN8C8opaEaKZVjr:btqqu5l) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Only `RPC -> Rpc`? Add a hint for the reviewer.
</blockquote></details>

Correct.

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
Not sure we should keep refactoring outside the monorepo...?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343#-:-O1fxHgvEgf19NTICisV:bm2kbxv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
I will close this PR and implement it once the mono-repo is ready.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/343#-:-O1kY1LNEiIyJ9NL_LqM:bgtqjk8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Comment by MohammadNassar1** [comment]
Implement it in mono-repo once it's ready.

**Pull request closed without merging**
