### PR TITLE
refactor: reduce allocations in tests

### PR DESCRIPTION
**Pull request by giladchase**
**Stack**:
- #276
- #270 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/270)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/mempool/270#-O099BY5DjxdKDrI9xYr:-O099BY5DjxdKDrI9xYs:bucyff2) ([raw file](https://github.com/starkware-libs/mempool/blob/8122bbdfaff65e7f6a1964379e5f7d4a24048aae/crates/mempool/src/mempool_test.rs#L130)):*
> ```XML
>     assert!(mempool.add_tx(tx_tip_50_address_0.clone(), account1).is_ok());
>     assert!(mempool.add_tx(tx_tip_100_address_1.clone(), account2).is_ok());
>     assert!(mempool.add_tx(tx_tip_80_address_2.clone(), account3).is_ok());
> ```

This is less readable.

Try making this test fail and see the error message in each case.



_Code quote:_
```XML
    assert!(mempool.add_tx(tx_tip_50_address_0.clone(), account1).is_ok());
    assert!(mempool.add_tx(tx_tip_100_address_1.clone(), account2).is_ok());
    assert!(mempool.add_tx(tx_tip_80_address_2.clone(), account3).is_ok());
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/270)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/mempool/270#-O099BY5DjxdKDrI9xYr:-O09GBCTAy54HZpv9_Va:b3cqe11) ([raw file](https://github.com/starkware-libs/mempool/blob/8122bbdfaff65e7f6a1964379e5f7d4a24048aae/crates/mempool/src/mempool_test.rs#L130)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is less readable.

Try making this test fail and see the error message in each case.
</blockquote></details>

Good point, reverted.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/270)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/mempool/270#-O09N0UbEqfk1kSGr2q6):*
It can be removed.



_Code quote:_
```
  Also simplify assertions
```
___
*[`crates/mempool/src/mempool_test.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/270#-O09Mu2zCcX1iN3O_B9h:-O09Mu2zCcX1iN3O_B9i:bd2udwp) ([raw file](https://github.com/starkware-libs/mempool/blob/76ae0a1beea043b3c4c6885ae26f1dc7f9ec7864/crates/mempool/src/mempool_test.rs#L148)):*
> ```XML
>     let same_tx = tx.clone();
> 
>     assert!(mempool.add_tx(tx.clone(), account).is_ok());
> ```

Please revert this as well.



_Code quote:_
```XML
  assert!(mempool.add_tx(tx.clone(), account).is_ok());
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/270)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/mempool/270#-O09Mu2zCcX1iN3O_B9h:-O0DZra-B3kJMYB2zVuC:bm4116i) ([raw file](https://github.com/starkware-libs/mempool/blob/76ae0a1beea043b3c4c6885ae26f1dc7f9ec7864/crates/mempool/src/mempool_test.rs#L148)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please revert this as well.
</blockquote></details>

Removed, and doubled down by removing all is_ok from the file :sunglasses: https://github.com/starkware-libs/mempool/pull/276

I'm using pretty_assertions::assert_eq instead of matches for the Ok values though, it has an even nicer output.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/270#-:-O0Dkya0EF0bO3NpjLPW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
