### PR TITLE
chore: add simple tokio executor tests

### PR DESCRIPTION
**Pull request by giladchase**
commit-id:19e51778

---

**Stack**:
- #174
- #173
- #172
- #51 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVr6Op4Mcd8l_G_tRx:-NvVr6Op4Mcd8l_G_tRy:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/8a8b563523e9e4d04c2919b8a383f7f4301a532b/crates/task_executor/src/bounded_tokio_executor_test.rs#L3)):*
> ```XML
> use crate::{bounded_tokio_executor::BoundedTokioExecutor, executor::TaskExecutor};
> 
> // use rstest::rstest;
> ```

Remove.



_Code quote:_
```XML
// use rstest::rstest;
```
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVy00rByQPRJ3ttvme:-NvVy00rByQPRJ3ttvmf:b-e5rzl3) ([raw file](https://github.com/starkware-libs/mempool/blob/8a8b563523e9e4d04c2919b8a383f7f4301a532b/crates/task_executor/src/bounded_tokio_executor_test.rs#L93)):*
> ```XML
> 
> #[tokio::test]
> async fn test_spawn_regular_task_error() {
> ```

What should this test check?



_Code quote:_
```XML
async fn test_spawn_regular_task_error() {
```
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVxd9XDTfhpdQ4wp1d:-NvVxd9XDTfhpdQ4wp1e:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8a8b563523e9e4d04c2919b8a383f7f4301a532b/crates/task_executor/src/bounded_tokio_executor_test.rs#L118)):*
> ```XML
> 
> fn safe_atomic_decrement(counter: &Arc<AtomicUsize>) {
>     counter.fetch_sub(1, Ordering::SeqCst);
> ```





_Suggestion:_
```XML
 counter.fetch_sub(1, Ordering::SeqCst) - 1;
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVr6Op4Mcd8l_G_tRx:-Nvb-HbJB1Sowp5lpQEx:b-rl0p20) ([raw file](https://github.com/starkware-libs/mempool/blob/8deb0083f11364db71633c69f51e5e12ca355268/crates/task_executor/src/bounded_tokio_executor_test.rs#L3)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

:facepalm:  tnx
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVy00rByQPRJ3ttvme:-Nvb-Prj7tSu1U0Pm0DW:bpr2zty) ([raw file](https://github.com/starkware-libs/mempool/blob/8deb0083f11364db71633c69f51e5e12ca355268/crates/task_executor/src/bounded_tokio_executor_test.rs#L93)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What should this test check?
</blockquote></details>

That panics are caught, but it might be a case of a "testing tokio" code smell, should I remove?
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVxd9XDTfhpdQ4wp1d:-Nvb-p7z6ke5edswDpo1:b-8zw9l4) ([raw file](https://github.com/starkware-libs/mempool/blob/8deb0083f11364db71633c69f51e5e12ca355268/crates/task_executor/src/bounded_tokio_executor_test.rs#L118)):*
> ```XML
> 
> fn safe_atomic_decrement(counter: &Arc<AtomicUsize>) {
>     counter.fetch_sub(1, Ordering::SeqCst);
> ```

You're right in general, but note that no one is currently using this return value.

Do you think I should make this return the value now anyway to make the function more useful in the future? or should future users worry about that?

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`Cargo.toml` line 40 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz27xCM4ggse31tGZQi:-Nz27xCM4ggse31tGZQj:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/Cargo.toml#L40)):*
> ```TOML
> hyper = { version = "0.14", features = ["client", "http1"] }
> derive_more = "0.99"
> futures = "0.3.30"
> ```





_Suggestion:_
```TOML
derive_more = "0.99"
futures = "0.3.30"
hyper = { version = "0.14", features = ["client", "http1"] }
```
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVy00rByQPRJ3ttvme:-Nz2OHD19v1RllD5z0TS:bmj97dw) ([raw file](https://github.com/starkware-libs/mempool/blob/8deb0083f11364db71633c69f51e5e12ca355268/crates/task_executor/src/bounded_tokio_executor_test.rs#L93)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That panics are caught, but it might be a case of a "testing tokio" code smell, should I remove?
</blockquote></details>

I liked your new test that checks the executor is still stable after panic.
___
*[`crates/task_executor/src/bounded_tokio_executor_test.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/mempool/51#-NvVxd9XDTfhpdQ4wp1d:-Nz2OOysCXatu1cgheDY:btwzuf) ([raw file](https://github.com/starkware-libs/mempool/blob/8deb0083f11364db71633c69f51e5e12ca355268/crates/task_executor/src/bounded_tokio_executor_test.rs#L118)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You're right in general, but note that no one is currently using this return value.

Do you think I should make this return the value now anyway to make the function more useful in the future? or should future users worry about that?
</blockquote></details>

I see. I don't think you need to modify it.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2NRs-EoOe7B0biM56:-Nz2NRs-EoOe7B0biM57:b3uazav) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L18)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_spawn_cpu_task_concurrency(executor: TokioExecutor) {
> ```

Why are you not limiting the number of concurrent tasks?



_Code quote:_
```XML
test_spawn_cpu_task_concurrency
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2Obe7-Sk2z24YP3Yf:-Nz2Obe7-Sk2z24YP3Yg:b-dmzidg) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L88)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_spawn_async_task_error(executor: TokioExecutor) {
> ```

Please add a test for positive flow for async tasks.



_Code quote:_
```XML
test_spawn_async_task_error
```

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/task_executor/src/tokio_executor_test.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2NRs-EoOe7B0biM56:-Nz2q0GL8ckRDqqLrEgo:b-i6wuds) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L18)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why are you not limiting the number of concurrent tasks?
</blockquote></details>

The feature of limiting the number of concurrent tasks was rolled back, we'll add it only when we have an actual need for throttling.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2Obe7-Sk2z24YP3Yf:-Nz2qMt4E3Tb_V_K9-vG:b-44bm1m) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add a test for positive flow for async tasks.
</blockquote></details>

Already added in the doc-test inside tokio_executor.rs :smirk: 

I started out by having them here, then realized that the tests were so simple they could fit in a docstring, so the test is run as part of the doc-tests suite.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/task_executor/src/tokio_executor.rs` line 121 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz7zncv3x_xWK3Tq8nO:-Nz7zncv3x_xWK3Tq8nP:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor.rs#L121)):*
> ```XML
>     ///     let result = executor.spawn(future).await;
>     ///     assert_eq!(result.unwrap(), "HOPALA");
>     /// });
> ```





_Suggestion:_
```XML
 /// });
 /// ```
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2Obe7-Sk2z24YP3Yf:-Nz7zLmjETnrOklAVmxe:beuxg4u) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L88)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Already added in the doc-test inside tokio_executor.rs :smirk: 

I started out by having them here, then realized that the tests were so simple they could fit in a docstring, so the test is run as part of the doc-tests suite.
</blockquote></details>

How can we confirm that it functions as expected without actually running it?

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 11 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/task_executor/src/tokio_executor_test.rs` line 89 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8Z9RAEszGnK0OaQCS:-Nz8Z9RAEszGnK0OaQCT:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L89)):*
> ```XML
> #[tokio::test]
> async fn test_spawn_async_task_error(executor: TokioExecutor) {
>     let future = async {
> ```





_Suggestion:_
```XML
panic_future
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8ZNp_0lpBfl5JGoAr:-Nz8ZNp_0lpBfl5JGoAs:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L93)):*
> ```XML
>     };
> 
>     // Ensure the executor remained usable after the worker thread panicked..
> ```





_Suggestion:_
```XML
panicked.
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 11 unresolved discussions (waiting on @dafnamatsry and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 13 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/task_executor/src/tokio_executor_test.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8cS1U-qrmkJp0AQ4n:-Nz8cS1U-qrmkJp0AQ4o:bxatkpm) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L18)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_spawn_cpu_task_concurrency(executor: TokioExecutor) {
> ```

Is this test required? It might be testing `tokio` implementation.



_Code quote:_
```XML
test_spawn_cpu_task_concurrency
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8cZdoCv9dkypMWaQ_:-Nz8cZdoCv9dkypMWaQa:b-bjts1h) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L57)):*
> ```XML
>     );
> }
> ```

Can both tests below be consolidated? To check that a thread has `panic`ked using `spawn[_blocking]`.
Also, please doc. (maybe in the `trait` itself?) the fact that the only error that propagates out of the future's `Result` is the thread `panic`king.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: 2 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/task_executor/src/tokio_executor_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz2Obe7-Sk2z24YP3Yf:-Nz8jaJ81zVR1oLiuYSy:bam2v5d) ([raw file](https://github.com/starkware-libs/mempool/blob/331fb317dcc1c742ae65007ec4cc3b851a295e6d/crates/task_executor/src/tokio_executor_test.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

How can we confirm that it functions as expected without actually running it?
</blockquote></details>

WDYM?
Note that the doc-tests (the tests inside the docstrings of tokio_executor.rs in this example) are regular tests: they are run as part of the suite. You can run `cargo test` and see them executed as part of the "doc-test" part of the suite.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8cS1U-qrmkJp0AQ4n:-NzMqUsB69fPuV8FqReS:bicr4md) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this test required? It might be testing `tokio` implementation.
</blockquote></details>

Yr right, it's testing tokio.
Removed.
:pray: 
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 23 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8WoReBv3TzIvL4oJE:-NzMqZfMA62K3IM17tvQ:b-7i692h) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L23)):*
> ```XML
>     let max_n_concurrent_tasks = Arc::new(AtomicUsize::new(0));
> 
>     let tasks = (0..n_tasks).map(|_| {
> ```

Test removed.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YC1t7XBVfduxtxqg:-NzMqbTnDh9dRe5JtKWF:b-rax7u4) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L32)):*
> ```XML
>         tokio::spawn(async move {
>             executor
>                 // Spawn a CPU-bound task that increments the running counter of running tasks and
> ```

Test no longer present.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YJoZ0zyGNH1VlRuh:-NzMqcuiCutw-MWp9PBx:b-nhxopt) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L39)):*
> ```XML
>                     // simulate CPU-bound task;
>                     std::thread::sleep(Duration::from_millis(100));
>                     // Update the maximum number of concurrent tasks
> ```

Test went out to buy a pack of smokes.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YP6ODGDSEJ6KM89T:-NzN9164D_psPXXqJgIC:b-gdznlk) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L54)):*
> ```XML
>     assert!(
>         safe_atomic_get_value(&max_n_concurrent_tasks) == n_tasks,
>         "less than {n_tasks} tasks ran concurrently.",
> ```

Test was sent to a farm
running and playing in the open fields
they have a rainbow made of dreams
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8cZdoCv9dkypMWaQ_:-NzNC54e0DJEOd2KU8LV:b-ij93eu) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can both tests below be consolidated? To check that a thread has `panic`ked using `spawn[_blocking]`.
Also, please doc. (maybe in the `trait` itself?) the fact that the only error that propagates out of the future's `Result` is the thread `panic`king.
</blockquote></details>

Good point.
Consolidated, i also decluttered so it now fits succinctly in a single test.

RE docs: Done (added in tokio_executor.rs).

Note: Running it in rstest's cases is probably tricky and probably unnecessary given how simple this ended up being.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 89 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8Z9RAEszGnK0OaQCS:-NzNDLmn0wGIIj-CZO_X:b-t4sf2w) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L89)):*
> ```XML
> #[tokio::test]
> async fn test_spawn_async_task_error(executor: TokioExecutor) {
>     let future = async {
> ```

inlined.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8ZNp_0lpBfl5JGoAr:-NzNDMZaEvINQfEJqaze:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L93)):*
> ```XML
>     };
> 
>     // Ensure the executor remained usable after the worker thread panicked..
> ```

Done.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 104 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YzAv7bhxfwTUumIu:-NzNDRc59jJOWk8iBSGY:b-7s9d0) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L104)):*
> ```XML
> // results in a multi-threaded environment.
> 
> // Increment the counter and return the new value.
> ```

No longer used, removed.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YtmiDpaEc9zElfkf:-NzNDT3WEvMSS-rcbtVm:b7qhb04) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

No longer used, removed.

For future reference: fetch_add is a += op that returns the _previous_ value, before the increment. 
Therefore, since this func wanted to do `+= 1 and return <the increment value>`, we have to add + 1 at the end.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8Z0G36VZLZzhjymOM:-NzNDrsZ9R7LBI5xfZjL:b-sq7d92) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L113)):*
> ```XML
> }
> 
> // Update the current max with the maximum of its current value and the new value.
> ```

Removed, no longer used.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/task_executor/src/tokio_executor_test.rs` line 39 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YJoZ0zyGNH1VlRuh:-NzWjE2m9k4xTKUkds5Q:bb6z2cq) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Test went out to buy a pack of smokes.
</blockquote></details>

LOL.
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/mempool/51#-Nz8YP6ODGDSEJ6KM89T:-NzWjJ8i0ZEq6lwIIh5x:b7rn3id) ([raw file](https://github.com/starkware-libs/mempool/blob/9dcde28a81362ea0c718ccbe89c4b9804a66de8b/crates/task_executor/src/tokio_executor_test.rs#L54)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Test was sent to a farm
running and playing in the open fields
they have a rainbow made of dreams
</blockquote></details>

חחחחחחחחחחחחחחחחחחחחחחחח

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/task_executor/src/tokio_executor.rs` line 66 at r8](https://reviewable.io/reviews/starkware-libs/mempool/51#-NzWjyPW1QWYuu-wdheF:-NzWjyPW1QWYuu-wdheG:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e8cbb59a5b44bcffc938c6a986a5741aba9c4379/crates/task_executor/src/tokio_executor.rs#L66)):*
> ```XML
> 
> impl TaskExecutor for TokioExecutor {
>     /// Note: `Tokio`` catches task panics that returns them as errors, this is a `Tokio`-specific
> ```





_Suggestion:_
```XML
tokio
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/mempool/51#-NzWkFc20AcneObvE_sU:-NzWkFc20AcneObvE_sV:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e8cbb59a5b44bcffc938c6a986a5741aba9c4379/crates/task_executor/src/tokio_executor_test.rs#L15)):*
> ```XML
> #[tokio::test]
> async fn test_panic_catching(executor: TokioExecutor) {
>     // assert that panic in a task is caught and wrapped in an error.
> ```





_Suggestion:_
```XML
// Assert
```
___
*[`crates/task_executor/src/tokio_executor_test.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/mempool/51#-NzWkScU70tl-wvRHtzf:-NzWkScU70tl-wvRHtzg:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e8cbb59a5b44bcffc938c6a986a5741aba9c4379/crates/task_executor/src/tokio_executor_test.rs#L22)):*
> ```XML
>     // Ditto for async tasks.
> 
>     assert!(executor.spawn(async { panic!() }).await.is_err());
> ```





_Suggestion:_
```XML
    // Ditto for async tasks.
    assert!(executor.spawn(async { panic!() }).await.is_err());
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, 1 of 5 files at r5, 2 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51#-:-NzXBhJG1FYN2_b_tpnd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/51)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
