### PR TITLE
test: remove redundent mempool node config tests

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/165)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/165?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#165** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/165?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#164** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/164?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#156** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/156?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#155** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/155?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#137** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#138](https://github.com/starkware-libs/mempool/pull/138) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/165#-:-Nyy6iKMBFPiVhyfPqyY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @lev-starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/165#-Nyy5vsR9y1E9Dtz6DuB:-Nyy5vsR9y1E9Dtz6DuC:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/828c4b24bf0e50282539b17643877cf92a7836bf/crates/mempool_node/src/config/config_test.rs#L19)):*
> ```XML
> 
>     assert_matches!(component_config.validate().unwrap_err(), validation_errors => {
>         let parse_err = ParsedValidationErrors::from(validation_errors);
> ```





_Suggestion:_
```XML
parsed_errors
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/165)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @lev-starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/165#-Nyy5vsR9y1E9Dtz6DuB:-Nyy72Wm9UaPYdDGFEWq:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/828c4b24bf0e50282539b17643877cf92a7836bf/crates/mempool_node/src/config/config_test.rs#L19)):*
> ```XML
> 
>     assert_matches!(component_config.validate().unwrap_err(), validation_errors => {
>         let parse_err = ParsedValidationErrors::from(validation_errors);
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/165#-:-Nyy7S2jAFQYv3a-5tmn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
