### PR TITLE
test: add tests for add tx on declare tx

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#235** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/235?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#234** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/234?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-VfPyV94iUeaIwM619:-O-VfPyV94iUeaIwM61A:b-iwfr2o) ([raw file](https://github.com/starkware-libs/mempool/blob/818e19fe3f92a3f8b066da9951ae92f168023463/crates/gateway/src/starknet_api_test_utils.rs#L96)):*
> ```XML
> pub fn declare_tx() -> ExternalTransaction {
>     env::set_current_dir(get_absolute_path(TEST_FILES_FOLDER)).expect("Couldn't set working dir.");
>     let json_file_path = Path::new(DECLARE_V3_TX_FILE);
> ```

I don't think we should take the transaction from a json file, we should create it in the code as we do with invoke.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-VfPyV94iUeaIwM619:-O-Vg6si4aYsnAXjaVXa:b-ob6s57) ([raw file](https://github.com/starkware-libs/mempool/blob/818e19fe3f92a3f8b066da9951ae92f168023463/crates/gateway/src/starknet_api_test_utils.rs#L96)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't think we should take the transaction from a json file, we should create it in the code as we do with invoke.
</blockquote></details>

(and also as in deploy_account - PR https://reviewable.io/reviews/starkware-libs/mempool/239#-)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/starknet_api_test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-VfPyV94iUeaIwM619:-O-VvFXX0FtI06oL95do:bc0v5br) ([raw file](https://github.com/starkware-libs/mempool/blob/818e19fe3f92a3f8b066da9951ae92f168023463/crates/gateway/src/starknet_api_test_utils.rs#L96)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

(and also as in deploy_account - PR https://reviewable.io/reviews/starkware-libs/mempool/239#-)
</blockquote></details>

The difference between `Invoke`/`DeployAccount` and `Declare` is that the declare tx is much bigger. The Sierra program is long.

I agree - this is also bad for consistency.
I think the solution is to load from a json only the `contract_class` / only the `sierra_program`.
WDYT?

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-VfPyV94iUeaIwM619:-O-_hwZTAn1B3Cs1bzlb:b-d34lwe) ([raw file](https://github.com/starkware-libs/mempool/blob/818e19fe3f92a3f8b066da9951ae92f168023463/crates/gateway/src/starknet_api_test_utils.rs#L96)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The difference between `Invoke`/`DeployAccount` and `Declare` is that the declare tx is much bigger. The Sierra program is long.

I agree - this is also bad for consistency.
I think the solution is to load from a json only the `contract_class` / only the `sierra_program`.
WDYT?
</blockquote></details>

I agree.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-VfPyV94iUeaIwM619:-O-kCyJS9xF3gDOw3g4y:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/818e19fe3f92a3f8b066da9951ae92f168023463/crates/gateway/src/starknet_api_test_utils.rs#L96)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-kOjUvCfEpl9fyDYfz:-O-kOjUvCfEpl9fyDYg-:bqbtgpq) ([raw file](https://github.com/starkware-libs/mempool/blob/61e94d8d30a77577d03c2c54c2e89d91f7d8cf8c/crates/gateway/src/starknet_api_test_utils.rs#L94)):*
> ```XML
> 
> pub fn declare_tx() -> RPCTransaction {
>     env::set_current_dir(get_absolute_path(TEST_FILES_FOLDER)).expect("Couldn't set working dir.");
> ```

why do you need to set the working dir?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/mempool/235#-O-kOjUvCfEpl9fyDYfz:-O-kVLmmBM-RhlOEUiEd:b-aizvud) ([raw file](https://github.com/starkware-libs/mempool/blob/61e94d8d30a77577d03c2c54c2e89d91f7d8cf8c/crates/gateway/src/starknet_api_test_utils.rs#L94)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why do you need to set the working dir?
</blockquote></details>

This is how they do it in Papyrus. This way - the absolute path of the file is set in a consistent way - independent of the path of this file: (`crates/gateway/src/starknet_api_test_utils.rs`).

The other option is: 
```
    let json_file_path: &Path = Path::new("../test_utils/test_files/contract_class.json");
```

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 28 at r7](https://reviewable.io/reviews/starkware-libs/mempool/235#-O0E3Za-5IPShLm9erPj:-O0E3Za-5IPShLm9erPk:b-3r3c1l) ([raw file](https://github.com/starkware-libs/mempool/blob/4fad704443ad8edece74400c2ed4ba0988747cab/crates/gateway/src/stateful_transaction_validator_test.rs#L28)):*
> ```XML
>     local_test_state_reader_factory(CairoVersion::Cairo1, false),
>     Ok(TransactionHash(StarkFelt::try_from(
>         "0x007d70505b4487a4e1c1a4b4e4342cb5aa9e73b86d031891170c45a57ad8b4e6"
> ```

why was this hash affected?



_Code quote:_
```XML
       "0x007d70505b4487a4e1c1a4b4e4342cb5aa9e73b86d031891170c45a57ad8b4e6"
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 28 at r7](https://reviewable.io/reviews/starkware-libs/mempool/235#-O0E3Za-5IPShLm9erPj:-O0E3sKS79BBYsSHSgrw:b-qgvo1s) ([raw file](https://github.com/starkware-libs/mempool/blob/4fad704443ad8edece74400c2ed4ba0988747cab/crates/gateway/src/stateful_transaction_validator_test.rs#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

why was this hash affected?
</blockquote></details>

Because I changed `VALID_L1_GAS_MAX_AMOUNT`.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 7 files at r5, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r5, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/gateway_test.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/mempool/235#-O0OL2_t9BiEWFnW91s-:-O0OL2_t9BiEWFnW91s0:bvo5j2p) ([raw file](https://github.com/starkware-libs/mempool/blob/5419863e3bd7e55cc20ecbdaa95eff0781646e9f/crates/gateway/src/gateway_test.rs#L74)):*
> ```XML
>     local_test_state_reader_factory_for_deploy_account(&tx)
> )]
> #[case::declare_tx(declare_tx(), local_test_state_reader_factory(CairoVersion::Cairo1, false))]
> ```

to be consistent with the other test cases.



_Suggestion:_
```XML
valid_declare_tx
```
___
*[`crates/gateway/src/gateway_test.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/mempool/235#-O0OPqey0KgioRc3t8HU:-O0OPqey0KgioRc3t8HV:b-aysbdj) ([raw file](https://github.com/starkware-libs/mempool/blob/5419863e3bd7e55cc20ecbdaa95eff0781646e9f/crates/gateway/src/gateway_test.rs#L102)):*
> ```XML
>     assert_eq!(tx_hash, serde_json::from_slice(response_bytes).unwrap());
> }
> ```

Please add a test for bad declare tx (bad sierra program).
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/mempool/235#-O0OONmtCWd91SjKpIu0:-O0OONmuBtAChSs_XBdG:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/5419863e3bd7e55cc20ecbdaa95eff0781646e9f/crates/gateway/src/starknet_api_test_utils.rs#L102)):*
> ```XML
> 
>     let cairo_version = CairoVersion::Cairo1;
>     let account_contract = FeatureContract::AccountWithoutValidations(cairo_version);
> ```





_Suggestion:_
```XML
    let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/235#-:-O0cGNz8D7IloiRhoh3y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
