### PR TITLE
test: add simple test that communicates through network component

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1 and @uriel-starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCacdI2896m4tkW10U:-NxCacdI2896m4tkW10V:b-9kweal) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L17)):*
> ```XML
> };
> 
> pub fn create_tx_for_testing() -> InternalTransaction {
> ```

add "_internal" ?
___
*[`crates/gateway/tests/end_to_end_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCaUS-3YZ3Hxs5OJGK:-NxCaUS0AlhFWfI5dpQH:b72o8vu) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L53)):*
> ```XML
>     let (tx_mempool_2_gateway, rx_mempool_2_gateway) = channel::<MempoolMessage>(1);
> 
>     let network_gateway = GatewayNetworkComponent::new(tx_gateway_2_mempool, rx_mempool_2_gateway);
> ```

Change to `gateway_network` for consistency with the type name.



_Code quote:_
```XML
network_gateway
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCa_LsDMnBFZ559VBl:-NxCa_LsDMnBFZ559VBm:bs4q9op) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L54)):*
> ```XML
> 
>     let network_gateway = GatewayNetworkComponent::new(tx_gateway_2_mempool, rx_mempool_2_gateway);
>     let mut network_mempool =
> ```

Ditto.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCb-B1CoLYq8nh2b5E:-NxCb-B1CoLYq8nh2b5F:b-c99j6p) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L59)):*
> ```XML
>     let internal_tx = create_tx_for_testing();
>     task::spawn(async move {
>         let state: AccountState = AccountState {};
> ```

Please be consistent with the var definitions: ` internal_tx` is defined outside of the `spawn` clause but `state` is within.
(I prefer both to be within)



_Code quote:_
```XML
    let internal_tx = create_tx_for_testing();
    task::spawn(async move {
        let state: AccountState = AccountState {};
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbxqDBzgRK4JXeJeP:-NxCbxqDBzgRK4JXeJeQ:b-ljqlgq) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L78)):*
> ```XML
>                 if invoke_tx.tx_hash != TransactionHash::default() {
>                     panic!("Unexpected transaction hash: {:?}", invoke_tx.tx_hash);
>                 }
> ```

Replace with assert that the hashes match.



_Code quote:_
```XML
                if invoke_tx.tx_hash != TransactionHash::default() {
                    panic!("Unexpected transaction hash: {:?}", invoke_tx.tx_hash);
                }
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbncV699VV6BVLjrx:-NxCbncV699VV6BVLjry:b5z3ywn) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L79)):*
> ```XML
>                     panic!("Unexpected transaction hash: {:?}", invoke_tx.tx_hash);
>                 }
>                 println!("Transaction: {:?}, state: {:?}", invoke_tx, state);
> ```

Is the print needed?



_Code quote:_
```XML
println!("Transaction: {:?}, state: {:?}", invoke_tx, state);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @uriel-starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCaUS-3YZ3Hxs5OJGK:-NxCrjWR1vK0s3V7Gexi:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L53)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Change to `gateway_network` for consistency with the type name.
</blockquote></details>

Done.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCa_LsDMnBFZ559VBl:-NxCrjxB38k7aEOMS6eO:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCb-B1CoLYq8nh2b5E:-NxCsgG38WZbRSl2tl-P:b-ohej70) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please be consistent with the var definitions: ` internal_tx` is defined outside of the `spawn` clause but `state` is within.
(I prefer both to be within)
</blockquote></details>

Now, both are outside the clause, as I want to use the internal_tx var in the assertion.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbxqDBzgRK4JXeJeP:-NxCvXXQAFKm5Y1iXJzk:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L78)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Replace with assert that the hashes match.
</blockquote></details>

Done.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbncV699VV6BVLjrx:-NxCswlw447DXExrWAje:bss4a2b) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is the print needed?
</blockquote></details>

Removed.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @uriel-starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbxqDBzgRK4JXeJeP:-NxCy-Nl-wDCu-cPxM-L:b-hyfubk) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L78)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still an `if x != y { panic() } ` code. Please change to`assert_eq!(x,y)`.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCxccI3ljNZLAQaVae:-NxCxccI3ljNZLAQaVaf:blmo412) ([raw file](https://github.com/starkware-libs/mempool/blob/1aa524a642f4fed3759fbd016cd1c6307e56bd3a/crates/gateway/tests/end_to_end_test.rs#L60)):*
> ```XML
>     }
>     .unwrap();
> ```

Blank line seems out of line (hehe) here (non-blocking, but please fix).

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @uriel-starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/98#-NxCbxqDBzgRK4JXeJeP:-NxD1Sjb1S6JlJVqEOQF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/12a6226a755c1ed571d137016efff36e006699cf/crates/gateway/tests/end_to_end_test.rs#L78)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is still an `if x != y { panic() } ` code. Please change to`assert_eq!(x,y)`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98#-:-NxD8KFeDiaQlHI0ae_K:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/98#-:-NxN6pVgEIbR9MjGp-o4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
