### PR TITLE
fix: change inner AddressPrioQueue

### PR DESCRIPTION
**Pull request by giladchase**
- pop_front in Vec is O(n).
- should be private to protect invariant.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/240#-O-Fxm2-7vvzZYVZi-7s:-O-Fxm2080qgADkb0FHt:btcrip2) ([raw file](https://github.com/starkware-libs/mempool/blob/e2cc2616e11f32ac32ed5b97f5fec18ccb28f4a5/crates/mempool/src/priority_queue.rs#L67)):*
> ```XML
> // Assumption: Transactions are provided in the correct order.
> #[derive(Default)]
> pub struct AddressPriorityQueue(VecDeque<ThinTransaction>);
> ```

I believe we should use a `HashMap<Nonce, ThinTransaction>`, as @elintul also suggested. This will support nonce gaps, which will be added soon



_Code quote:_
```XML
VecDeque
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/240#-O-FzS2I-YmJApZP1hJN:-O-FzS2I-YmJApZP1hJO:b-mahprv) ([raw file](https://github.com/starkware-libs/mempool/blob/e2cc2616e11f32ac32ed5b97f5fec18ccb28f4a5/crates/mempool/src/priority_queue.rs#L67)):*
> ```XML
> // Assumption: Transactions are provided in the correct order.
> #[derive(Default)]
> pub struct AddressPriorityQueue(VecDeque<ThinTransaction>);
> ```

I think it's not a good name.
These transactions are not priority transactions.



_Code quote:_
```XML
 AddressPriorityQueue
```

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/240#-O-Fxm2-7vvzZYVZi-7s:-O-GC-X96IBdhva06qxX:b-qmoay) ([raw file](https://github.com/starkware-libs/mempool/blob/e2cc2616e11f32ac32ed5b97f5fec18ccb28f4a5/crates/mempool/src/priority_queue.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I believe we should use a `HashMap<Nonce, ThinTransaction>`, as @elintul also suggested. This will support nonce gaps, which will be added soon
</blockquote></details>

Why not implement this in the future or the next version?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/240#-O-Fxm2-7vvzZYVZi-7s:-O-K6M-G7yxsMB8Ssdak:b-lvxv36) ([raw file](https://github.com/starkware-libs/mempool/blob/e2cc2616e11f32ac32ed5b97f5fec18ccb28f4a5/crates/mempool/src/priority_queue.rs#L67)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why not implement this in the future or the next version?
</blockquote></details>

Already fixed on Ayelet's PR, if i change it here as well she'll hit a conflict
___
*[`crates/mempool/src/priority_queue.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/240#-O-FzS2I-YmJApZP1hJN:-O-K6MLQ7WadjR3kojjv:b-lvxv36) ([raw file](https://github.com/starkware-libs/mempool/blob/e2cc2616e11f32ac32ed5b97f5fec18ccb28f4a5/crates/mempool/src/priority_queue.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it's not a good name.
These transactions are not priority transactions.
</blockquote></details>

Already fixed on Ayelet's PR, if i change it here as well she'll hit a conflict

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/240)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
