### PR TITLE
feat: stateless validations in add transaction

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
This PR sits on top of: #70.
Replaces: #48.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71#-:-Nwi3Bmy9H3TAV-6JOth:b-kpkba3)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/71?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#71** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/71?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#70** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/70?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnFpyJ-NbfEgeEwlR5:-NwnFpyJ-NbfEgeEwlR6:b-1ew0ue) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway.rs#L77)):*
> ```XML
> 
>     // Perform stateless validations.
>     let stateless_validator = StatelessTransactionValidator {
> ```

Can we have a single `stateless_validator` that is shared across requests? we can create in the `app` function, and it can be part of a `GatewayState` struct.
___
*[`crates/gateway/src/gateway.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnFDwE5cnyP0yfyol3:-NwnFDwE5cnyP0yfyol4:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway.rs#L83)):*
> ```XML
>     stateless_validator.validate(&transaction)?;
> 
>     // TODO(Arni, 1/5/2024): Descard duplications.
> ```

Remove.



_Code quote:_
```XML
// TODO(Arni, 1/5/2024): Descard duplications.
```
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnI0WNEifC4Wahd5i0:-NwnI0WNEifC4Wahd5i1:b-en3klm) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway_test.rs#L54)):*
> ```XML
>         &String::from_utf8_lossy(response_bytes),
>         negative_flow_expected_response
>     );
> ```

Can you check something like "assert response string contains..." instead of equality?
Just to avoid having the `ResourceBounds` struct be tested here...



_Code quote:_
```XML
    let response_bytes = &to_bytes(response).await;
    let negative_flow_expected_response = "Expected a positive amount of L2Gas. \
        Got ResourceBounds { max_amount: 0, max_price_per_unit: 0 }.";
    assert_str_eq!(
        &String::from_utf8_lossy(response_bytes),
        negative_flow_expected_response
    );
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnFpyJ-NbfEgeEwlR5:-Nwo24P47KJtSccvGReT:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway.rs#L77)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can we have a single `stateless_validator` that is shared across requests? we can create in the `app` function, and it can be part of a `GatewayState` struct.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnFDwE5cnyP0yfyol3:-Nwo-xakDkWgAO55AVag:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway.rs#L83)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/mempool/71#-NwnI0WNEifC4Wahd5i0:-NwoBGxe2MApWa_6tAVs:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/114ace2a9936df2dd2099de546133baf0e7896a9/crates/gateway/src/gateway_test.rs#L54)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you check something like "assert response string contains..." instead of equality?
Just to avoid having the `ResourceBounds` struct be tested here...
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71#-:-NwsPdoD6_ZJ1Yvxmyxc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/config_test.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx6qBTSBCH1NrzCnxlW:-Nx6qBTSBCH1NrzCnxlX:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/ea9d817445fcf877656d3e0aadb87159259c55b6/crates/gateway/src/config_test.rs#L6)):*
> ```XML
> 
> use papyrus_config::loading::load_and_process_config;
> // use serde_json::{Map, Value};
> ```

Remove.



_Code quote:_
```XML
// use serde_json::{Map, Value};
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 6 of 9 files at r5, 2 of 6 files at r6, 4 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71#-:-Nx7ne6i6ATKKLxlaB21:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/src/config.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7MvLT52LI_jkg1CN7:-Nx7MvLU7mmoSUJjxMmO:b-byqr6w) ([raw file](https://github.com/starkware-libs/mempool/blob/ea9d817445fcf877656d3e0aadb87159259c55b6/crates/gateway/src/config.rs#L38)):*
> ```XML
>                 "The stateless validator configuration.",
>                 ParamPrivacyInput::Public,
>             ),
> ```

What's `ser_param`?



_Code quote:_
```XML
            ser_param(
                "stateless_transaction_validator_config",
                &self.stateless_transaction_validator_config,
                "The stateless validator configuration.",
                ParamPrivacyInput::Public,
            ),
```
___
*[`crates/gateway/src/gateway_test.rs` line 67 at r8](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7m4ePDknyCH7Q9RUH:-Nx7m4ePDknyCH7Q9RUI:bpqyoa2) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc374ad28ab3ec15d04e264204d78671be2c21/crates/gateway/src/gateway_test.rs#L67)):*
> ```XML
>     let response = add_transaction(State(gateway_state), tx.into())
>         .await
>         .into_response();
> ```

very nit picky (it's a test), so only if you feel like it:
1) I think instead of default() the sig len should be explicitly set to 0, maybe even as a variable called too_small_sig = 0, cause its the crux of the negative test.
2) maybe instead of recreating the state you can clone it when passing it to add_transaction then before the positive flow just set state.validator.signature_len = 2 



_Code quote:_
```XML
    // Negative flow.
    let gateway_state = GatewayState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                ..Default::default()
            },
        },
    };

    let response = add_transaction(State(gateway_state), tx.clone().into())
        .await
        .into_response();

    let status_code = response.status();
    assert_eq!(status_code, StatusCode::INTERNAL_SERVER_ERROR);

    let response_bytes = &to_bytes(response).await;
    let negative_flow_expected_response = "Signature length exceeded maximum:";
    assert!(String::from_utf8_lossy(response_bytes).starts_with(negative_flow_expected_response));

    // Positive flow.
    let gateway_state = GatewayState {
        stateless_transaction_validator: StatelessTransactionValidator {
            config: StatelessTransactionValidatorConfig {
                validate_non_zero_l1_gas_fee: true,
                max_calldata_length: 10,
                max_signature_length: 2,
                ..Default::default()
            },
        },
    };

    let response = add_transaction(State(gateway_state), tx.into())
        .await
        .into_response();
```
___
*[`crates/mempool_node/src/test_files/mempool_node_config.json` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7h__o2hDLucCi2K68:-Nx7h__o2hDLucCi2K69:b-us7p6) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc374ad28ab3ec15d04e264204d78671be2c21/crates/mempool_node/src/test_files/mempool_node_config.json#L20)):*
> ```JSON
>         "description": "The gateway server port.",
>         "value": 8080,
>         "privacy": "Public"
> ```

FYI Not related to this PR, but this file is a test fixture and should probably not be inside production code (it should be either inside `tests/` or feature-gated behind 'any(feature=testing,test)`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)* status: 5 of 14 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 67 at r8](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7m4ePDknyCH7Q9RUH:-NxBcf-7COMhonJwdFxj:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc374ad28ab3ec15d04e264204d78671be2c21/crates/gateway/src/gateway_test.rs#L67)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

very nit picky (it's a test), so only if you feel like it:
1) I think instead of default() the sig len should be explicitly set to 0, maybe even as a variable called too_small_sig = 0, cause its the crux of the negative test.
2) maybe instead of recreating the state you can clone it when passing it to add_transaction then before the positive flow just set state.validator.signature_len = 2
</blockquote></details>

Done.
___
*[`crates/gateway/src/config.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7MvLT52LI_jkg1CN7:-NxBaaLx6g8q1FV5mXzF:b-kh5526) ([raw file](https://github.com/starkware-libs/mempool/blob/ea9d817445fcf877656d3e0aadb87159259c55b6/crates/gateway/src/config.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What's `ser_param`?
</blockquote></details>

Something related to `papyrus_config`. Out of scope for this PR.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/config.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/mempool/71#-Nx7MvLT52LI_jkg1CN7:-NxBspm27by6VbQ3YoNQ:bca65fx) ([raw file](https://github.com/starkware-libs/mempool/blob/ea9d817445fcf877656d3e0aadb87159259c55b6/crates/gateway/src/config.rs#L38)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Something related to `papyrus_config`. Out of scope for this PR.
</blockquote></details>

Now covered in: #101

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 4 of 5 files at r7, 1 of 1 files at r8, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/71)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
