### PR TITLE
feat: add get_storage_at to rpc_state_reader

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7M5KrDNbFhajetP88:-Nx7M5KrDNbFhajetP89:b-f4j0ta) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L29)):*
> ```XML
>         &self,
>         method: &str,
>         params: serde_json::Value,
> ```

Would `impl serde::Serialize` work? And then you can pass `*_params` directly...



_Code quote:_
```XML
serde_json::Value
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7MqNr7iIhyMz0NCA6:-Nx7MqNr7iIhyMz0NCA7:bmaamhx) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L93)):*
> ```XML
>         let result =
>             self.send_rpc_request("starknet_getStorageAt", json!(get_storage_at_params))?;
>         let value: StarkFelt = serde_json::from_value(json!(result))
> ```

Needed?



_Code quote:_
```XML
json!
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7M5KrDNbFhajetP88:-Nx7OKKDDxJWpPoOvDIQ:b703s8c) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L29)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Would `impl serde::Serialize` work? And then you can pass `*_params` directly...
</blockquote></details>

can you elaborate? not sure I follow 
___
*[`crates/gateway/src/rpc_state_reader.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7MqNr7iIhyMz0NCA6:-Nx7OPXa38pSN7eBR9bc:b-cos5r3) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L93)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Needed?
</blockquote></details>

right, done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7M5KrDNbFhajetP88:-Nx7Qb5f4BASL_wEFKmq:bcvrmn9) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L29)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you elaborate? not sure I follow
</blockquote></details>

If you change the type of the argument to `impl serde::Serialize` then when you call this function you can pass a `GetStorageAtParams` and serialize it with `json!` here inside `send_rpc_request`.

Not a big deal, you can also leave it as is.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/mempool/81#-Nx7M5KrDNbFhajetP88:-NxBJWeIBp515UVdpvG3:b-1r9wjs) ([raw file](https://github.com/starkware-libs/mempool/blob/2731e3f3ebcb4f8897b05bcaef1f0a44dbe7124d/crates/gateway/src/rpc_state_reader.rs#L29)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If you change the type of the argument to `impl serde::Serialize` then when you call this function you can pass a `GetStorageAtParams` and serialize it with `json!` here inside `send_rpc_request`.

Not a big deal, you can also leave it as is.
</blockquote></details>

oh , right, nice! 
done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/81#-:-NxC4p0WEI0-4QRLgbA9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
