### PR TITLE
refactor(gateway): prepare run_validate for mocking

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1BqvHU1DgQqLpd_Cv3:-O1BqvHV2a1dfb_czusG:bkfuvu9) ([raw file](https://github.com/starkware-libs/mempool/blob/8d7b8bb72cd35630370ab4daec41e8acee72410a/crates/gateway/src/stateful_transaction_validator.rs#L52)):*
> ```XML
>         optional_class_info: Option<ClassInfo>,
>         deploy_account_tx_hash: Option<TransactionHash>,
>         mut validator: TStatefulTransactionValidator,
> ```

Now the blockifier validator is created outside the function so it can be mocked



_Code quote:_
```XML
mut validator: TStatefulTransactionValidator,
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1C3BVT4GUU4VlmIXAW:-O1C3BVT4GUU4VlmIXAX:b-5h6725) (no related file):*
Trait is unrelated to this PR, right?

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Trait is unrelated to this PR, right?
</blockquote></details>

Moved to the following PR

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GImwv8IvSmTNOzfJa:-O1GImwv8IvSmTNOzfJb:bb6d0xn) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/gateway.rs#L127)):*
> ```XML
> 
>     // TODO(Yael, 19/5/2024): pass the relevant deploy_account_hash.
>     let blockifier_validator = stateful_tx_validator.prepare_validate(state_reader_factory)?;
> ```

Keep names behavioral and future-proved (type of validator might change and the name will become outdated).



_Suggestion:_
```XML
validator
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GG8GO-SjmY7XZ0o_f:-O1GG8GO-SjmY7XZ0o_g:b-1ou7qs) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L25)):*
> ```XML
> 
> type ConcreteBlockifierStatefulValidator =
>     BlockifierStatefulValidator<CachedState<Box<dyn MempoolStateReader>>>;
> ```

Out of curiosity: where did the type `Box<dyn MempoolStateReader>>` come from?



_Suggestion:_
```XML
type BlockifierStatefulValidator =
    BlockifierStatefulValidator<CachedState<Box<dyn MempoolStateReader>>>;
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1GFzxREwq82xvGMR0Y:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
> ```XML
>     }
> 
>     pub fn prepare_validate(
> ```





_Suggestion:_
```XML
fn instantiate_validator(
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICZb66zuyzXpsYJ8:-O1GICZb66zuyzXpsYJ9:bj7g1nw) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L73)):*
> ```XML
> 
>         Ok(BlockifierStatefulValidator::create(
>             state.into(),
> ```

What changed here?



_Code quote:_
```XML
.into()
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1GIS9VCiEGOiF9SrsG:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
> ```XML
> 
>     let result =
>         stateful_validator.run_validate(&external_tx, optional_class_info, None, validator);
> ```





_Suggestion:_
```XML
    let validator = stateful_validator.prepare_validate(&state_reader_factory).unwrap();
    let deploy_account_tx_hash = None;
    let result =
        stateful_validator.run_validate(&external_tx, optional_class_info, deploy_account_tx_hash, validator);
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIg754D2JV1H-nXs8:-O1GIg754D2JV1H-nXs9:b-6e19pt) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L96)):*
> ```XML
> 
> #[test]
> fn test_prepare_validate() {
> ```

We're using this function in the test above, not sure a separate one is needed.



_Code quote:_
```XML
test_prepare_validate
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICblB-u8rbFCa6PL:-O1GICbm0ShxeUxJJhnD:b35x9ep) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L107)):*
> ```XML
>         },
>     };
>     let blockifier_validator = stateful_validator.prepare_validate(&state_reader_factory);
> ```

I think maybe we can mock the factory as well. That way we can assert we create the state reader from the latest block.
Can be done in a separate PR.



_Code quote:_
```XML
&state_reader_factory
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381#-:-O1GK4H43Tdh3So1WBXI:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICblB-u8rbFCa6PL:-O1GRy68026DtJY14Kkx:b32v57) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L107)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think maybe we can mock the factory as well. That way we can assert we create the state reader from the latest block.
Can be done in a separate PR.
</blockquote></details>

+1

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/gateway.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GImwv8IvSmTNOzfJa:-O1GQOt59dbkd7Kdty2A:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/gateway.rs#L127)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep names behavioral and future-proved (type of validator might change and the name will become outdated).
</blockquote></details>

done
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GG8GO-SjmY7XZ0o_f:-O1GQZzWABei0CgNRTcR:b-ul9ars) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Out of curiosity: where did the type `Box<dyn MempoolStateReader>>` come from?
</blockquote></details>

Renamed.
This is the return type of the StateReaderFactory
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1GTaYS1Q9WFF4AR_h_:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
> ```XML
>     }
> 
>     pub fn prepare_validate(
> ```

done
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICZb66zuyzXpsYJ8:-O1Gfdse83M0QvVMH1HL:bvi1iob) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What changed here?
</blockquote></details>

Had a mistake in the alias, good thing you noticed
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1GgXLw5iR3pcgATstE:bntmd19) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
> ```XML
> 
>     let result =
>         stateful_validator.run_validate(&external_tx, optional_class_info, None, validator);
> ```

In the next PR I remove the test case of deploy account
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIg754D2JV1H-nXs8:-O1GhXiL2otNn7sGxXq-:bb54bon) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L96)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We're using this function in the test above, not sure a separate one is needed.
</blockquote></details>

I don't think it hurts, but I can remove
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICblB-u8rbFCa6PL:-O1GhCHt4T3PlIlmXEcs:b6msihd) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

There's already a factory for testing, I will think about what should be done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1GpmxwCQRz6gqrgCe1:bxzoaop) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done
</blockquote></details>

Can it be private?
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1GzIT82wNCS5YJu5EV:b-7zi8tj) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In the next PR I remove the test case of deploy account
</blockquote></details>

WDYM?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1GzuPN-EKjItB5OD2J:bza3qjd) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can it be private?
</blockquote></details>

No, it is called from process_tx which is in and outer scope.
I think some modules in the gateway crate can be private.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1H-nE84ueiSK93sUZ-:bhfmtf5) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

Actually I am not sure what this field does, but I don't think it is in the scope of this task to change it

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1H0yeNCBIwatZLbO12:b2nhz08) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No, it is called from process_tx which is in and outer scope.
I think some modules in the gateway crate can be private.
</blockquote></details>

an*

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GG8GO-SjmY7XZ0o_f:-O1H70Ng7sCIDL9qPCY6:b-2od2zs) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Renamed.
This is the return type of the StateReaderFactory
</blockquote></details>

Why do we alias `GenericBlockifierStatefulValidator`?
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1H775xEb8nEDgQW1Y3:b-yx335g) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Actually I am not sure what this field does, but I don't think it is in the scope of this task to change it
</blockquote></details>

I agree, but it's a small change (that increases readability) and this line has already changed.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1H7MBN9JoPr-_IY14t:bau4r7o) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

an*
</blockquote></details>

Perhaps `pub(crate)`?

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICblB-u8rbFCa6PL:-O1HRj-n73Z03lQmP0Ys:b-l18l7u) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There's already a factory for testing, I will think about what should be done
</blockquote></details>

done: https://github.com/starkware-libs/mempool/pull/401

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GFzxREwq82xvGMR0X:-O1HZHTD1pEAL7HvjI7X:beeqebr) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps `pub(crate)`?
</blockquote></details>

I will change the module scope in another PR
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GIS9UDnfr34Ek1E8S:-O1HZB1eBwbYIIP9uvif:b32vqui) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I agree, but it's a small change (that increases readability) and this line has already changed.
</blockquote></details>

@Yael-Starkware is deleting this argument in another PR

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GG8GO-SjmY7XZ0o_f:-O1HZwKIDHoNWeZpBgnk:b-jyyr25) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we alias `GenericBlockifierStatefulValidator`?
</blockquote></details>

So the function argument will be simpler to read

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381#-:-O1Lg80W2EfG5QzbWni2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GICblB-u8rbFCa6PL:-O1Lg2C9-3qeiaf3in3Z:bvtk9y9) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator_test.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done: https://github.com/starkware-libs/mempool/pull/401
</blockquote></details>

Thanks :)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/381)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/mempool/381#-O1GG8GO-SjmY7XZ0o_f:-O1LkYsz74yNGolXNMcR:ba3dfob) ([raw file](https://github.com/starkware-libs/mempool/blob/02d32cafc4356274b6e74bec8dc72b275063d7e4/crates/gateway/src/stateful_transaction_validator.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant the other alias, of `GenericBlockifierStatefulValidator`; seems unnecessary
</blockquote></details>

Removed

**Pull request merged**
