### PR TITLE
feat: make generic component client http

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/334)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/334)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/334#-O0iSw7QAdz7MVPhTHRr:-O0iSw7QAdz7MVPhTHRs:bjfskm4) ([raw file](https://github.com/starkware-libs/mempool/blob/5e8ff058a2d909e32af3ca74c35245692b31e724/crates/mempool_infra/src/component_client.rs#L62)):*
> ```XML
> where
>     Request: Serialize,
>     Response: for<'a> Deserialize<'a>,
> ```

Please add the bounds to the struct definition as well.



_Code quote:_
```XML
where
    Request: Serialize,
    Response: for<'a> Deserialize<'a>,
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/334)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/mempool_infra/src/component_client.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/mempool/334#-O0iSw7QAdz7MVPhTHRr:-O0iTuqb8XN_HU3nnCRT:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5e8ff058a2d909e32af3ca74c35245692b31e724/crates/mempool_infra/src/component_client.rs#L62)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add the bounds to the struct definition as well.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/334#-O0iTno1ChjuVRFxlm6g:-O0iVdc152GvBrT8638b:bpukr3e) ([raw file](https://github.com/starkware-libs/mempool/blob/5e8ff058a2d909e32af3ca74c35245692b31e724/crates/mempool_infra/tests/component_server_client_http_test.rs#L197)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is there a way to explicitly mention the types of these two? Currently they are implicilty inferred from the initation of the components.

Something in the sorts of
```
    let a_client = ComponentClientHttp<RequestA,ResponseA>::new(local_ip, a_port);
```
</blockquote></details>

there is always the option to write them as `ComponentClientHttp<ComponentARequest, ComponentAResponse>`. Tell me if this is what you want. I will do it to server as well

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/334)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/mempool/334#-O0iTno1ChjuVRFxlm6g:-O0iX054BTaNE_BPyPLs:b-78o1z8) ([raw file](https://github.com/starkware-libs/mempool/blob/5e8ff058a2d909e32af3ca74c35245692b31e724/crates/mempool_infra/tests/component_server_client_http_test.rs#L197)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

there is always the option to write them as `ComponentClientHttp<ComponentARequest, ComponentAResponse>`. Tell me if this is what you want. I will do it to server as well
</blockquote></details>

Ok, I did it as I described

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/334#-:-O0iYKav08kT2M6VpNqY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
