### PR TITLE
test(mempool): add function to assert equality and implement Eq,Parti…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…alEq for related structs

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431#-:-O1Qu-PuCOzYJ8-yOj-G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/mempool/431#-O1WtbxQ4nVYsKE-Lu4q:-O1WtbxQ4nVYsKE-Lu4r:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/ba6056d3ef5b394ca6475decaeb9a59cdef1e3d4/crates/mempool/src/mempool_test.rs#L169)):*
> ```XML
> 
>     // Check that the transactions that were not returned are still in the mempool.
>     let remaining_ref_txs = remaining_txs.iter().map(TransactionReference::new);
> ```





_Suggestion:_
```XML
remaining_tx_references
```
___
*[`crates/mempool/src/transaction_queue.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/mempool/431#-O1WtscDAiInTCZlS5un:-O1WtscDAiInTCZlS5uo:b-gvumyt) ([raw file](https://github.com/starkware-libs/mempool/blob/ba6056d3ef5b394ca6475decaeb9a59cdef1e3d4/crates/mempool/src/transaction_queue.rs#L10)):*
> ```XML
> 
> // Note: PartialEq and Eq for TransactionQueue are derived, ensuring that
> // equality checks take into account the sorted nature of the BTreeSet.
> ```

Suggesting a behavioral description, with lower chances of getting old.



_Suggestion:_
```XML
// Note: the derived comparison functionality considers the order guaranteed by the data structures used.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/mempool/431#-O1kLqvS39k2IxOTSmNO:-O1kLqvS39k2IxOTSmNP:b-xsroua) ([raw file](https://github.com/starkware-libs/mempool/blob/7479fd6791a8c62e2ebb2b5f8477deadbd887676/crates/mempool/src/mempool_test.rs#L148)):*
> ```XML
> #[case::test_get_less_than_all_eligible_txs(2)]
> fn test_get_txs(#[case] requested_txs: usize) {
>     let tx1 = add_tx_input!(tip: 50, tx_hash: 1).tx;
> ```

renaming here #463

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431#-:-O1lSDjLEL9Kp9NOsSuf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/431)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Pull request merged**
