### PR TITLE
test: integration test with rpc state reader

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217)

### CODE REVIEW

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`Cargo.toml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-Nzg_MCVBFiMtqeAy9Km:-Nzh4Ay_DfZPvwJPXpIF:b-ighwau) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/Cargo.toml#L56)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We use a git dependency because the crate has not been published, right? The other papyrus crates here are also not published? Or do they have to be the same version?

Please document it.
</blockquote></details>

all of them must be the same version, otherwise will probably not compile due to struct definition mismatch.
we use this specific version because it must have the same starknet-api version as mempool.
if it were just the publishing problem , I could have taken origin/main or the latest version.


the whole thing will be solved once we have mono-repo

tried to improve the TODO msg here.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-Nzgde7b0ZKPauCpN-pO:-Nzh5RDqBXSRRevhA6cj:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L147)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move below right before the iteration over `contract_instances`.
</blockquote></details>

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgeoAs86FM_S3Yg8f6:-Nzh5d3A88WWSRAisymx:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L157)):*
> ```XML
>     };
> 
>     contract_instances.iter().for_each(|(contract, n_instances)| {
> ```

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgfZxw26jaYFPKZRot:-Nzh7HAC3zyoq-Gm6L22:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L178)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider extracting it to a separate function (to make this whole function shorter, and to hide the nested match in the already nested for loops)
</blockquote></details>

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-Nzgidxv0ai9rpvZHsGz:-Nzh7OTh74GS6ug_tcU4:bhkw86q) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L206)):*
> ```XML
>     let mut storage_config = StorageConfig::default();
>     let tempdir = tempdir().unwrap();
>     storage_config.db_config.path_prefix = tempdir.path().to_path_buf();
> ```

If I don't use a variable to hold tempdir then it goes out of scope and dropped immediately. 
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgiqmrEA4e9RFG6ZUm:-Nzh7VJW7qL2P8UnQbhp:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L219)):*
> ```XML
>         .unwrap();
>     // Write the compiled classes to the storage.
>     for (contract, _) in contract_instances.iter() {
> ```

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-Nzgi0MjCm2megE5GJN3:-Nzh8Izf3ISaL0QVEjFg:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L223)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Move to a separate function:
```
storage_reader = open_and_write_to_storage(contract_instances, state_diff);
```
</blockquote></details>

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-Nzgk7DsCA5odN_kN_Pv:-Nzh8Y4p1QOoCl_30a4E:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L258)):*
> ```XML
>         storage_reader,
>         "NODE VERSION",
>     )
> ```

Done.
___
*[`crates/gateway/src/state_reader_test_utils.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgknrK8GpRKchUcUIp:-Nzh4oOL1xh6lb0QIOhU:b-9szdlj) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L261)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

this makes the rpc_server keep running, otherwise it is aborted once the handler is out of scope.
(was one of the issue that took me a while to understand.... )

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217#-:-NzhIZ5d6DKPEIsi59BI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgknrK8GpRKchUcUIp:-NzhIEsh5Rw55Vt116Mk:b-964xi9) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L261)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this makes the rpc_server keep running, otherwise it is aborted once the handler is out of scope.
(was one of the issue that took me a while to understand.... )
</blockquote></details>

Oh. Maybe add a short explanation.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/state_reader_test_utils.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/mempool/217#-NzgknrK8GpRKchUcUIp:-NzhWSxc5kAzg2-l9Tay:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/35f0e238c4fdb30e060ed9f03062905b3fd91144/crates/gateway/src/state_reader_test_utils.rs#L261)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Oh. Maybe add a short explanation.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217#-:-NzvrA6IAqsI-crK0NXf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
