### PR TITLE
test(mempool): flow test with holes

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1uOYlC3soLk0ae3Ms1:-O1uOYlC3soLk0ae3Ms2:b-fl5byr) ([raw file](https://github.com/starkware-libs/mempool/blob/94e099af478cb6156d2d05c9ddc17755eecc027a/crates/mempool/src/mempool_test.rs#L273)):*
> ```XML
>     let input_address_0_nonce_0 = add_tx_input!(tip: 20, tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
>     let input_address_0_nonce_1 = add_tx_input!(tip: 20, tx_hash: 2, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
>     let input_address_1_nonce_0 = add_tx_input!(tip: 10, tx_hash: 3, sender_address: "0x1", tx_nonce: 0_u8, account_nonce: 0_u8);
> ```

Can you lost the tips plz? they aren't relevant here (add a macro variant if you need to)



_Code quote:_
```XML
    let input_address_0_nonce_0 = add_tx_input!(tip: 20, tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
    let input_address_0_nonce_1 = add_tx_input!(tip: 20, tx_hash: 2, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
    let input_address_1_nonce_0 = add_tx_input!(tip: 10, tx_hash: 3, sender_address: "0x1", tx_nonce: 0_u8, account_nonce: 0_u8);
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480#-:-O1vUWys7N3OtaVLpNJE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 282 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vUMFVCc2E2lZvqe3g:-O1vUMFVCc2E2lZvqe3h:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L282)):*
> ```XML
>         add_tx_input!(tx_hash: 3, sender_address: "0x1", tx_nonce: 0_u8, account_nonce: 0_u8);
> 
>     // Test
> ```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vdnPEDaROw3gQLr8y:-O1vdnPEDaROw3gQLr8z:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L273)):*
> ```XML
> 
> #[rstest]
> fn test_flow_with_holes(mut mempool: Mempool) {
> ```





_Suggestion:_
```XML
test_flow_filling_holes
```
___
*[`crates/mempool/src/mempool_test.rs` line 282 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vdT7f8P8-zVWYw6Sh:-O1vdT7g88YTNARrKv1X:b32wzj) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L282)):*
> ```XML
>         add_tx_input!(tx_hash: 3, sender_address: "0x1", tx_nonce: 0_u8, account_nonce: 0_u8);
> 
>     // Test
> ```

x2



_Suggestion:_
```XML
    // Test.
```
___
*[`crates/mempool/src/mempool_test.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vdZVhACfMUvRhsvvB:-O1vdZVhACfMUvRhsvvC:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L287)):*
> ```XML
>     let txs = mempool.get_txs(2).unwrap();
> 
>     // Assert that the tx of account 1 nonce 0 is returned and the tx of account 0 nonce 0 is not.
> ```





_Suggestion:_
```XML
// Assert: only the eligible transaction is returned.
```
___
*[`crates/mempool/src/mempool_test.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vdgOwCFtHzr4RYvM-:-O1vdgOwCFtHzr4RYvM0:bk6bw92) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L294)):*
> ```XML
>     let txs = mempool.get_txs(2).unwrap();
> 
>     // Assert that all remaining txs are returned.
> ```

This should change after replenishing, a TODO?



_Suggestion:_
```XML
// Assert: that all remaining transactions are returned.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 294 at r2](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vdgOwCFtHzr4RYvM-:-O1viwh2AvBy01yUDBfK:bby1qgi) ([raw file](https://github.com/starkware-libs/mempool/blob/e2fa37a7767bd1f49ce827f3ff7eaed18145cf22/crates/mempool/src/mempool_test.rs#L294)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This should change after replenishing, a TODO?
</blockquote></details>

correct. Adjusted the test to work and added a todo.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 278 at r3](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vlK7M2is8CutvKbSP:-O1vlK7M2is8CutvKbSQ:bwsiazb) ([raw file](https://github.com/starkware-libs/mempool/blob/9066f39d910cd62ebbc5f7d6b6b4ba1cf8307901/crates/mempool/src/mempool_test.rs#L278)):*
> ```XML
> }
> 
> #[rstest]
> ```

Do the first two tests belong in this PR?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 278 at r3](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vlK7M2is8CutvKbSP:-O1vm02fDiJKi_xk1zyU:balhocz) ([raw file](https://github.com/starkware-libs/mempool/blob/9066f39d910cd62ebbc5f7d6b6b4ba1cf8307901/crates/mempool/src/mempool_test.rs#L278)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do the first two tests belong in this PR?
</blockquote></details>

so weird. I just rebased over the main. Only one commit is in this PR.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 278 at r3](https://reviewable.io/reviews/starkware-libs/mempool/480#-O1vlK7M2is8CutvKbSP:-O1vmNHy2Y3kFf8i1YGE:bj0z9j4) ([raw file](https://github.com/starkware-libs/mempool/blob/9066f39d910cd62ebbc5f7d6b6b4ba1cf8307901/crates/mempool/src/mempool_test.rs#L278)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

so weird. I just rebased over the main. Only one commit is in this PR.
</blockquote></details>

ok, rebased again. seems okay now.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/480#-:-O1vmTXd4IrElaH-99rq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
