### PR TITLE
chore: add error to gateway runner and rename

### PR DESCRIPTION
**Pull request by giladchase**
commit-id:9cd8bcdd

---

**Stack**:
- #174
- #173 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Added an error for the axum server startup.

Made this into an error because axum's `bind` command can return an error when the TCP connection cannot be established, and this can be caused by incorrect configuration of the server (which the user can do something about, therefore an error is returned).

For example, if the gateway attempts to use port `80`, which is typically reserved, then this error will be returned.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173#-:-NyoPbro-5u528MaLXSv:b2g5oti)* status: 0 of 5 files reviewed, all discussions resolved

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/gateway/src/errors.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/mempool/173#-Nz8M1tyEu56xk-HSo0R:-Nz8M1tzBQFXaVKpfMg4:buoy1xl) ([raw file](https://github.com/starkware-libs/mempool/blob/a0731b3d045f339b846ef5de02430224c4c73bcc/crates/gateway/src/errors.rs#L15)):*
> ```XML
> pub enum GatewayError {
>     #[error(transparent)]
>     ServerStartupError(#[from] hyper::Error),
> ```

Not sure this is the appropriate place for this kind of error.
Note that this is returned from the add_tx endpoint (and then is parsed to a user error).



_Code quote:_
```XML
    #[error(transparent)]
    ServerStartupError(#[from] hyper::Error),
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @dafnamatsry)

___
*[`crates/gateway/src/errors.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/mempool/173#-Nz8M1tyEu56xk-HSo0R:-NzNeUoF-xFCDuy7lepp:b24l7i3) ([raw file](https://github.com/starkware-libs/mempool/blob/a0731b3d045f339b846ef5de02430224c4c73bcc/crates/gateway/src/errors.rs#L15)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure this is the appropriate place for this kind of error.
Note that this is returned from the add_tx endpoint (and then is parsed to a user error).
</blockquote></details>

I see yr point, though this particular variant will never reach the user in the current flow, but still it doesn't belong in this enum.
In particular, it shouldn't be part of an enum that implements `IntoResponse` if it is never included in a flow that needs it.

Added a new enum specifically for the `run` command, with errors now returned to the "admin user" (infra), rather than the add_tx user (customer).
+docs to difference between the two

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173#-:-NzRpGKy30EP05_Y407l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173#-:-NzXOtRO8M-W5rNlxQKP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
