### PR TITLE
chore: add declare_tx fixture to compilation tests

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/515)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#298** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#348](https://github.com/starkware-libs/mempool/pull/348) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/348?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#384](https://github.com/starkware-libs/mempool/pull/384) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/384?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#515** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/515?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/515)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/515#-:-O2cq711A2DquJc0EWyu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/515#-:-O2xEna04twjoPp8X9pw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
Another branch was merged into sequencer repo.

**Pull request closed without merging**
