### PR TITLE
chore: change url type url to string in rpc state reader config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/129?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#130** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/130?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#129** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/129?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#126** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/126?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#127](https://github.com/starkware-libs/mempool/pull/127) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/127?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#113** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#114](https://github.com/starkware-libs/mempool/pull/114) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#111** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`crates/gateway/src/rpc_state_reader.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/mempool/129#-NxhfaNl371hWdn9XPJV:-NxhfaNl371hWdn9XPJW:b-dmjwv1) ([raw file](https://github.com/starkware-libs/mempool/blob/71c7ad0d3f2692a1f33c1f6e61510f5ada0e7f12/crates/gateway/src/rpc_state_reader.rs#L157)):*
> ```XML
>     pub url: String,
>     pub json_rpc_version: String,
> }
> ```

See other use case:
https://github.com/starkware-libs/papyrus/blob/08aac67b7cf7dc8a829e404a93fe413f35e4ff99/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L41



_Code quote:_
```XML
#[derive(Clone, Default)]
pub struct RpcStateReaderConfig {
    pub url: String,
    pub json_rpc_version: String,
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`crates/gateway/src/rpc_state_reader.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/mempool/129#-NxhfaNl371hWdn9XPJV:-NxuhyMs9l_xKgooVUNQ:be71nlu) ([raw file](https://github.com/starkware-libs/mempool/blob/71c7ad0d3f2692a1f33c1f6e61510f5ada0e7f12/crates/gateway/src/rpc_state_reader.rs#L157)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See other use case:
https://github.com/starkware-libs/papyrus/blob/08aac67b7cf7dc8a829e404a93fe413f35e4ff99/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L41
</blockquote></details>

Can you explain what is the motivation to delete it?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/mempool/129#-NxhfaNl371hWdn9XPJV:-Nxv2GOMBE79a9mrXWOg:b-qkuwbz) ([raw file](https://github.com/starkware-libs/mempool/blob/adc6afff094f01036bb119d9c7b782571cda5b29/crates/gateway/src/rpc_state_reader.rs#L157)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you explain what is the motivation to delete it?
</blockquote></details>

PR #130 is the motivation for this PR.
The issue is that `URL` does not implement `Serialize`.

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129#-:-NxvlUIgDuol7NRDIxgj:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129#-:-Ny-XCec3p41zLtrKhvE:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/129)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
