### PR TITLE
test(gateway): use mock mempool client

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1kRgChBRZXlD6IKHZM:-O1kRgChBRZXlD6IKHZN:b3ltlyk) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L47)):*
> ```XML
> async fn test_add_tx() {
>     let mut mock_mempool_client = MockMempoolClient::new();
>     mock_mempool_client.expect_add_tx().once().return_once(|_| Ok(()));
> ```

Please validate the `mempool_input` here (the account address, nonce, and tx_hash).



_Code quote:_
```XML
.expect_add_tx().
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l2aleBajLQSskdheQ:-O1l2aleBajLQSskdheR:b-axx7i4) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L47)):*
> ```XML
> async fn test_add_tx() {
>     let mut mock_mempool_client = MockMempoolClient::new();
>     mock_mempool_client.expect_add_tx().once().return_once(|_| Ok(()));
> ```

Consider having the mempool client created as a fixure.



_Code quote:_
```XML
    let mut mock_mempool_client = MockMempoolClient::new();
    mock_mempool_client.expect_add_tx().once().return_once(|_| Ok(()));
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l3qk85-4IlBYIYo6w:-O1l3qk85-4IlBYIYo6x:b-24vcgo) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L51)):*
> ```XML
>     let app_state = app_state(Arc::new(mock_mempool_client), state_reader_factory);
> 
>     let tx = invoke_tx(CairoVersion::Cairo1);
> ```

Please add a comment / rename the var to indicate this is an arbitrary tx.



_Code quote:_
```XML
let tx = invoke_tx(CairoVersion::Cairo1);
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l4bCN4EaVrJdq5FX-:-O1l4bCO16WOfhCdzFyn:brmt32w) ([raw file](https://github.com/starkware-libs/mempool/blob/33cc1d3d1c69c5a6edcfbeed29f8c2b603d043bc/crates/gateway/src/gateway_test.rs#L78)):*
> ```XML
>     declare_tx(),
>     local_test_state_reader_factory(CairoVersion::Cairo1, false)
> )]
> ```

For f2f discussion: Decide whether we need these variants as a unit test for the mempool.



_Code quote:_
```XML
#[case::valid_invoke_tx_cairo1(
    invoke_tx(CairoVersion::Cairo1),
    local_test_state_reader_factory(CairoVersion::Cairo1, false)
)]
#[case::valid_invoke_tx_cairo0(
    invoke_tx(CairoVersion::Cairo0),
    local_test_state_reader_factory(CairoVersion::Cairo0, false)
)]
#[case::valid_deploy_account_tx(
    deploy_account_tx(),
    local_test_state_reader_factory_for_deploy_account(&tx)
)]
#[case::valid_declare_tx(
    declare_tx(),
    local_test_state_reader_factory(CairoVersion::Cairo1, false)
)]
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1kRgChBRZXlD6IKHZM:-O1lDWfQ6qdn97tE9IBN:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L47)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please validate the `mempool_input` here (the account address, nonce, and tx_hash).
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l2aleBajLQSskdheQ:-O1lDc18-iReXToZPndp:b-tr2kse) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Consider having the mempool client created as a fixure.
</blockquote></details>

What is the advantage?
___
*[`crates/gateway/src/gateway_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l3qk85-4IlBYIYo6w:-O1lEwnT9W9FhYFSSq9m:b-xrurdw) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a comment / rename the var to indicate this is an arbitrary tx.
</blockquote></details>

Done (extracted to a function)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l2aleBajLQSskdheQ:-O1pAP1S8gxlM1ONcnVP:bu1e7yi) ([raw file](https://github.com/starkware-libs/mempool/blob/10f9f75fce77b009836ec17946d6ebb479bdf183/crates/gateway/src/gateway_test.rs#L47)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What is the advantage?
</blockquote></details>

1. This is just a suggestion, hence the non-blocking comment
2. My intuition is that this improves the readability: the test "setup" is performed elsewhere and the focus is on the tested functionality

Up to you.
___
*[`crates/gateway/src/gateway_test.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1pB8Aq6fSKQ1jEgA1N:-O1pB8Aq6fSKQ1jEgA1O:bhji1zc) ([raw file](https://github.com/starkware-libs/mempool/blob/13b1ada46a7fa5af8535225bc41f46cd9fddec23/crates/gateway/src/gateway_test.rs#L52)):*
> ```XML
> 
> type SenderAddress = ContractAddress;
> fn create_tx() -> (RPCTransaction, SenderAddress) {
> ```

Please add a blank line between these two.



_Code quote:_
```XML
type SenderAddress = ContractAddress;
fn create_tx() -> (RPCTransaction, SenderAddress) {
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/src/gateway_test.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1l4bCN4EaVrJdq5FX-:-O1uEeOZ1u8_5-U27vA6:b-5r9df4) ([raw file](https://github.com/starkware-libs/mempool/blob/33cc1d3d1c69c5a6edcfbeed29f8c2b603d043bc/crates/gateway/src/gateway_test.rs#L78)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

For f2f discussion: Decide whether we need these variants as a unit test for the mempool.
</blockquote></details>

Checked with @dafnamatsry, and we don't need the other cases - the mempool is indifferent to transaction types
___
*[`crates/gateway/src/gateway_test.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/mempool/385#-O1pB8Aq6fSKQ1jEgA1N:-O1uC4KU8Opu8SfvrwIV:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/13b1ada46a7fa5af8535225bc41f46cd9fddec23/crates/gateway/src/gateway_test.rs#L52)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a blank line between these two.
</blockquote></details>

done

**Review by ItayTsabary — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385#-:-O1uLRAQ4g6A7w188mt-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385#-:-O1uThN77tSIkw-uWZdj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/385#-:-O1uqqKS2qDk7pYruFpq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
