### PR TITLE
fix(mempool): fix add-tx method by updating the queue according to in…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…put state

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/510#-O25FOA-6zl0zXGNTRzc:-O25FOA04-fzZD7EmjaQ:b-1aj1pq) (no related file):*
The AddTx method now takes into account the input account state.
It updates the queue accordingly, e.g. a transaction hole can be closed by the accountState.

___

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/mempool/510#-O25IYmH0ezd_pkTxxiZ:-O25IYmH0ezd_pkTxxi_:bwhn6qn) ([raw file](https://github.com/starkware-libs/mempool/blob/134076e4ab76465bde63fe07c889b406e844a1a6/crates/mempool/src/mempool.rs#L109)):*
> ```XML
>         self.tx_pool.insert(tx)?;
> 
>         if self.tx_queue.get_nonce(sender_address).is_none() {
> ```

out of scope but I think get_address_nonce is better



_Code quote:_
```XML
get_nonce
```
___
*[`crates/mempool/src/mempool.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/mempool/510#-O25J5tf4g1lYNixWPaK:-O25J5tf4g1lYNixWPaL:b-vibfy6) ([raw file](https://github.com/starkware-libs/mempool/blob/134076e4ab76465bde63fe07c889b406e844a1a6/crates/mempool/src/mempool.rs#L109)):*
> ```XML
>         self.tx_pool.insert(tx)?;
> 
>         if self.tx_queue.get_nonce(sender_address).is_none() {
> ```

Consider adding a comment about the meaning of this if. I think get_nonce.none is not trivial for checking whether the account is in the queue already

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/mempool/510#-O25UabSE_sRSVfNv0Eu:-O25UabSE_sRSVfNv0Ev:b-mfbmay) ([raw file](https://github.com/starkware-libs/mempool/blob/e3c7906efaff5b3abb2c203c7c24c3e5cffadbe9/crates/mempool/src/mempool.rs#L113)):*
> ```XML
>         // 1. If the input transaction can be added to the queue, this can happen when the input
>         //    transaction's nonce equals the next nonce.
>         // 2. If the input state fills a gap in the transaction queue, insert it into the queue.
> ```

`// If no account transaction is in the queue, insert if nonce matches account's.`



_Code quote:_
```XML
        // If the queue is empty, check if a transaction can be inserted into the transaction queue:
        // 1. If the input transaction can be added to the queue, this can happen when the input
        //    transaction's nonce equals the next nonce.
        // 2. If the input state fills a gap in the transaction queue, insert it into the queue.
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/mempool/510#-O2U_l891kaMgNQCYmiU:-O2U_l8A4vLtc09xYl7q:b3j75ga) ([raw file](https://github.com/starkware-libs/mempool/blob/e3c7906efaff5b3abb2c203c7c24c3e5cffadbe9/crates/mempool/src/mempool.rs#L106)):*
> ```XML
>         if tx.nonce < nonce {
>             return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
>         }
> ```

Okay, but error is inaccurate, and also should be moved to `should_insert` method from the other PR.



_Code quote:_
```XML
        // Invalid input.
        if tx.nonce < nonce {
            return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/mempool/510#-O2U_l891kaMgNQCYmiU:-O2UlIK45AlnaY2rBRDT:b-7yd1q4) ([raw file](https://github.com/starkware-libs/mempool/blob/e3c7906efaff5b3abb2c203c7c24c3e5cffadbe9/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, but error is inaccurate, and also should be moved to `should_insert` method from the other PR.
</blockquote></details>

Added a TODO.
___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/mempool/510#-O25UabSE_sRSVfNv0Eu:-O2Un8sG4JgVYy0o2XDo:btjmhhg) ([raw file](https://github.com/starkware-libs/mempool/blob/e3c7906efaff5b3abb2c203c7c24c3e5cffadbe9/crates/mempool/src/mempool.rs#L113)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`// If no account transaction is in the queue, insert if nonce matches account's.`
</blockquote></details>

Note that another tx may be added to the queue, not only the specific one.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 116 at r6](https://reviewable.io/reviews/starkware-libs/mempool/510#-O2Zw8TxDJco90VUyvkD:-O2Zw8TxDJco90VUyvkE:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/88c9d2e46e88f6fdbf61696881e1f02ec46a8788/crates/mempool/src/mempool.rs#L116)):*
> ```XML
>                 self.tx_queue.insert(*tx_reference);
>             }
>         }
> ```





_Suggestion:_
```XML
        // Maybe close nonce gap.
        if self.tx_queue.get_nonce(sender_address).is_none() {
            if let Some(tx_reference) = self.tx_pool.get_by_address_and_nonce(sender_address, nonce)
            {
                self.tx_queue.insert(*tx_reference);
            }
        }
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/510#-:-O2_1iAi3c_xVk8rlAeA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Pull request closed without merging**
