### PR TITLE
feat: add state reader creation and block info read to stateful validations

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDC1u078nHfX303OmL:-NxDC1u078nHfX303OmM:b6ak9li) (no related file):*
We do not want to create a test for the function `validate` - right? This will be in the integration test.

___
___
*[`crates/gateway/src/rpc_state_reader.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDB5y0C-R1RClIJgMj:-NxDB5y0C-R1RClIJgMk:bljgrjs) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/rpc_state_reader.rs#L44)):*
> ```XML
>             block_id: BlockId::Tag(crate::rpc_objects::Tag::Latest),
>         }
>     }
> ```

Keep just the `new` method.

There is no need for `new_latest`.



_Suggestion:_
```XML
    pub fn new(url: Url, json_rpc_version: String, block_number: BlockNumber) -> Self {
        RpcReader {
            url,
            json_rpc_version,
            block_id: BlockId::HashOrNumber(BlockHashOrNumber::Number(block_number)),
        }
    }
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDATkAC89EfGvpypIo:-NxDATkAC89EfGvpypIp:b-jefk2v) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L43)):*
> ```XML
>             self.config.json_rpc_version.clone(),
>             latest_block_info.block_number,
>         );
> ```

An option - but I actually like the use of `new` here. 



_Suggestion:_
```XML
        let state_reader = RpcReader{
            self.config.rpc_url.clone(),
            self.config.json_rpc_version.clone(),
            BlockId::HashOrNumber(BlockHashOrNumber::Number(latest_block_info.block_number)),
    };
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxD8Mk_7oaT5EpenL0a:-NxD8Mk_7oaT5EpenL0b:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L60)):*
> ```XML
>         optional_class_info: Option<ClassInfo>,
>         deploy_account_tx_hash: Option<TransactionHash>,
>     ) -> Result<(), StatefulTransactionValidatorError> {
> ```





_Suggestion:_
```XML
    fn run_validate(
        &self,
        state_reader: impl StateReader,
        latest_block_info: BlockInfo,
        external_tx: &ExternalTransaction,
        optional_class_info: Option<ClassInfo>,
        deploy_account_tx_hash: Option<TransactionHash>,
    ) -> Result<(), StatefulTransactionValidatorError> {
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDAcrKEEG61GH8Dfxd:-NxDAcrL7IYZ1yIo14Us:b-xjd149) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L96)):*
> ```XML
>             self.config.rpc_url.clone(),
>             self.config.json_rpc_version.clone(),
>         );
> ```

I don't like `new_latest`.



_Suggestion:_
```XML
        let rpc_reader = RpcReader{
            self.config.rpc_url.clone(),
            self.config.json_rpc_version.clone(),
            BlockId::Tag(crate::rpc_objects::Tag::Latest),
    };
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDBrii5mmGRHj5224E:-NxDBrii5mmGRHj5224F:b8uvdfu) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator_test.rs#L68)):*
> ```XML
>             json_rpc_version: Default::default(),
>         },
>     };
> ```

is it possible?



_Suggestion:_
```XML
    let stateful_validator = StatefulTransactionValidator {
        config: StatefulTransactionValidatorConfig {
            max_nonce_for_validation_skip: Default::default(),
            validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
            max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
            chain_info: block_context.chain_info().clone(),
            rpc_url: Url::default(),
            json_rpc_version: Default::default(),
        },
    };
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDBgOP0kNGp0h678k4:-NxDBgOP0kNGp0h678k5:b-ds50sx) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator_test.rs#L87)):*
> ```XML
>         None,
>         None,
>     );
> ```

It is odd the function `run_validate` is agnostic to some of the members of the config....
Maybe we can rename the function `run_validate`.



_Code quote:_
```XML
    let result = stateful_validator.run_validate(
        state_reader,
        block_context.block_info().clone(),
        &external_tx,
        None,
        None,
    );
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDC1u078nHfX303OmL:-NxH0v8DAbB9UnhUL1Gy:b-7oa46l) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We do not want to create a test for the function `validate` - right? This will be in the integration test.
</blockquote></details>

right, since it requires to use the real state_reader, which is a remote server

___
___
*[`crates/gateway/src/rpc_state_reader.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDB5y0C-R1RClIJgMj:-NxH11vN-75wvb68wXTj:bh2dcob) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/rpc_state_reader.rs#L44)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Keep just the `new` method.

There is no need for `new_latest`.
</blockquote></details>

as we discussed, removed both
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxD8Mk_7oaT5EpenL0a:-NxDPjFJChWWfmoGlJp7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L60)):*
> ```XML
>         optional_class_info: Option<ClassInfo>,
>         deploy_account_tx_hash: Option<TransactionHash>,
>     ) -> Result<(), StatefulTransactionValidatorError> {
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDAcrKEEG61GH8Dfxd:-NxH160r4MCb2o9DE9BG:bez06oa) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L96)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't like `new_latest`.
</blockquote></details>

removed it. done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDBrii5mmGRHj5224E:-NxDPCFqDUPvStMBej46:bkesmm2) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator_test.rs#L68)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

is it possible?
</blockquote></details>

code was deleted.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDBgOP0kNGp0h678k4:-NxDP5ye5FfI0wQDsR_S:b-dco52r) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator_test.rs#L87)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is odd the function `run_validate` is agnostic to some of the members of the config....
Maybe we can rename the function `run_validate`.
</blockquote></details>

moved the rpcConfig out of the validatorConfig as we discussed.
done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/rpc_objects.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxH1U_o0dqDw0JmIOz9:-NxH1U_o0dqDw0JmIOzA:ba7najl) ([raw file](https://github.com/starkware-libs/mempool/blob/b1a0be39b547f3b79946a1492939a45d73d68428/crates/gateway/src/rpc_objects.rs#L22)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Deserialize, Serialize)]
> pub enum BlockId {
> ```

@ArniStarkware Eventually it just works like this :)

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/102?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#102** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/102?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#96** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/96?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/rpc_objects.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxH1U_o0dqDw0JmIOz9:-NxH2mQt6_zvpvKxOkQG:bo5cptr) ([raw file](https://github.com/starkware-libs/mempool/blob/b1a0be39b547f3b79946a1492939a45d73d68428/crates/gateway/src/rpc_objects.rs#L22)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

@ArniStarkware Eventually it just works like this :)
</blockquote></details>

Nice!!!

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDAcrKEEG61GH8Dfxd:-NxHNlJaCja7MsKQaP0c:bhwmr9s) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L96)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

removed it. done.
</blockquote></details>

I actually like the idea. Maybe we can have `from_latest`, and `from_block_number` constructors in `RpcStateReader`
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxHQdsLAb9r4QiN8ack:-NxHQdsM7IJ1-clNRtO_:b36vxm7) ([raw file](https://github.com/starkware-libs/mempool/blob/8e0b549e97f22aeb6b3be7a9a7f71511a1d7b054/crates/gateway/src/stateful_transaction_validator.rs#L33)):*
> ```XML
>     pub fn validate(
>         &self,
>         rpc_config: &RpcStateReaderConfig,
> ```

Since the config is not going to change between calls to validate, I think it can be a member of the `StatefulTransactionValidator` class.
Maybe even a member of the `StatefulTransactionValidatorConfig`.



_Code quote:_
```XML
rpc_config: &RpcStateReaderConfig,
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDAcrKEEG61GH8Dfxd:-NxHUoyN1LtXot-QnC6D:b-ok8k84) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L96)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I actually like the idea. Maybe we can have `from_latest`, and `from_block_number` constructors in `RpcStateReader`
</blockquote></details>

I am fine either way. I like the suggested names better.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxDAcrKEEG61GH8Dfxd:-NxHgFQNBYhg1jZyDGkZ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/887e1b88355eb3eda590df4143338b58b6489c43/crates/gateway/src/stateful_transaction_validator.rs#L96)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I am fine either way. I like the suggested names better.
</blockquote></details>

done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxHQdsLAb9r4QiN8ack:-NxHcPNj5nMthLEPWu-g:b1pyfu4) ([raw file](https://github.com/starkware-libs/mempool/blob/8e0b549e97f22aeb6b3be7a9a7f71511a1d7b054/crates/gateway/src/stateful_transaction_validator.rs#L33)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Since the config is not going to change between calls to validate, I think it can be a member of the `StatefulTransactionValidator` class.
Maybe even a member of the `StatefulTransactionValidatorConfig`.
</blockquote></details>

Makes sense,  it was kind of what I did at the beginning  but then following a discussion with @ArniStarkware , I separated it.
It made the difference between validate() and run_validate() somehow confusing.

But I think it does make sense to put it inside the `StatefulTransactionValidatorConfig`, since it is the only object that uses it.
@ArniStarkware wdyt?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/mempool/102#-NxHQdsLAb9r4QiN8ack:-NxHmwCt4-T2WmKrcWk0:bwsywll) ([raw file](https://github.com/starkware-libs/mempool/blob/8e0b549e97f22aeb6b3be7a9a7f71511a1d7b054/crates/gateway/src/stateful_transaction_validator.rs#L33)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Makes sense,  it was kind of what I did at the beginning  but then following a discussion with @ArniStarkware , I separated it.
It made the difference between validate() and run_validate() somehow confusing.

But I think it does make sense to put it inside the `StatefulTransactionValidatorConfig`, since it is the only object that uses it.
@ArniStarkware wdyt?
</blockquote></details>

I am fine with it.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102#-:-NxHqkEhAPijguPBOSNv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/102)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
