### PR TITLE
feat: add network component types and update const…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…ructors

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, @MohammadNassar1, and @uriel-starkware)

___
*[`crates/mempool/src/mempool.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7JTdm7aqOBZ0AbpEl:-Nx7JTdn15c46g5CHDVO:bujv9z) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool/src/mempool.rs#L15)):*
> ```XML
> 
> pub struct Mempool {
>     pub network: MempoolNetworkComponent,
> ```

The mempool does not have a config?



_Code quote:_
```XML
pub network: MempoolNetworkComponent,
```
___
*[`crates/mempool_common/src/mempool_common.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7JhGPDx2xN2ROIlVP:-Nx7JhGPDx2xN2ROIlVQ:b-d4ttd6) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool_common/src/mempool_common.rs#L9)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum GatewayIO {
> ```

I'd prefer `GatewayMessage` (and `MempoolMessage`), but your call.



_Code quote:_
```XML
IO
```
___
*[`crates/mempool_common/src/mempool_common.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7LEnw17r7qupI-nwJ:-Nx7LEnw17r7qupI-nwK:b-hn84ag) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool_common/src/mempool_common.rs#L18)):*
> ```XML
>     GetTxs(u8),                               // Output.
> }
> ```

Missing: a function that converts `GatewayIO::AddTx(InternalTransaction, AccountState)` to `MempoolwayIO::AddTx(InternalTransaction, AccountState)`

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, @MohammadNassar1, and @uriel-starkware)

___
*[`crates/mempool_common/src/mempool_common.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7LEnw17r7qupI-nwJ:-Nx7MTYe4lFY2VB1kXAn:b-ndftyo) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool_common/src/mempool_common.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Missing: a function that converts `GatewayIO::AddTx(InternalTransaction, AccountState)` to `MempoolwayIO::AddTx(InternalTransaction, AccountState)`
</blockquote></details>

Suggestion, consider something like:
```
impl From<GatewayIO> for MempoolwayIO {
    fn from(item: GatewayIO) -> Self {
        match item {
            GatewayIO::AddTx(...) => MempoolwayIO::AddTx(...)
            _ => unreachable!("Conversion not possible."),
        }
    }
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @giladchase, and @uriel-starkware)

___
*[`crates/mempool/src/mempool.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7JTdm7aqOBZ0AbpEl:-Nx7kuR4D0qQK0gk5cP6:b-8nlap4) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool/src/mempool.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The mempool does not have a config?
</blockquote></details>

Not yet.
___
*[`crates/mempool_common/src/mempool_common.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7JhGPDx2xN2ROIlVP:-Nx7nNwt6FBQJVdBcmWZ:b-83sjoh) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool_common/src/mempool_common.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd prefer `GatewayMessage` (and `MempoolMessage`), but your call.
</blockquote></details>

Nice!
___
*[`crates/mempool_common/src/mempool_common.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/mempool/97#-Nx7LEnw17r7qupI-nwJ:-Nx7roJi4W35r-sGVTeX:b-qeumu) ([raw file](https://github.com/starkware-libs/mempool/blob/86c499688b91838258c0031db232dad3a9a1a15c/crates/mempool_common/src/mempool_common.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Suggestion, consider something like:
```
impl From<GatewayIO> for MempoolwayIO {
    fn from(item: GatewayIO) -> Self {
        match item {
            GatewayIO::AddTx(...) => MempoolwayIO::AddTx(...)
            _ => unreachable!("Conversion not possible."),
        }
    }
}
```
</blockquote></details>

Let's wait until we have a test that requires this conversion before adding it.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 1 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97#-:-Nx7yvpiBfTj-U0vlaj2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @giladchase, and @uriel-starkware)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, @Itay-Tsabary-Starkware, @MohammadNassar1, and @uriel-starkware)

___
*[`Cargo.toml` line 42 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxChoU1CWOypUTjDYpZ:-NxChoU1CWOypUTjDYp_:bsentj) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/Cargo.toml#L42)):*
> ```TOML
> tower = "0.4.13"
> validator = "0.12"
> url = "2.5.0"
> ```

Why did you change the order?
It should match the lexicographic order. 



_Suggestion:_
```TOML
tower = "0.4.13"
url = "2.5.0"
validator = "0.12"
```
___
*[`crates/gateway/Cargo.toml` line 25 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCi67ZAHVmmPdQgrWI:-NxCi67ZAHVmmPdQgrWJ:b-99u9yl) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/gateway/Cargo.toml#L25)):*
> ```TOML
> tower.workspace = true
> url.workspace = true
> validator.workspace = true
> ```

Lexicographic order.



_Suggestion:_
```TOML
[dependencies]
axum.workspace = true
blockifier.workspace = true
clap.workspace = true
mempool_infra = { path = "../mempool_infra", version = "0.0" }
papyrus_config.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
thiserror.workspace = true
tower.workspace = true
url.workspace = true
validator.workspace = true
```
___
*[`crates/mempool_types/Cargo.toml` line 13 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCiMsZ-ggB85PRrY4U:-NxCiMsZ-ggB85PRrY4V:b-99u9yl) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/mempool_types/Cargo.toml#L13)):*
> ```TOML
> [dependencies]
> starknet_api.workspace = true
> mempool_infra = { path = "../mempool_infra"}
> ```

Lexicographic order.



_Suggestion:_
```TOML
[package]
name = "starknet_mempool_types"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
mempool_infra = { path = "../mempool_infra"}
starknet_api.workspace = true
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCimygArx15mcy0uUb:-NxCimygArx15mcy0uUc:bajioy9) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/mempool_types/src/mempool_types.rs#L12)):*
> ```XML
>     None,                                     // Input.
>     AddTx(InternalTransaction, AccountState), // Output.
> }
> ```

Are the words `input` and `output` meanings clear in this context?
Does `Output` mean a message `Gateway -> mempool`?



_Code quote:_
```XML
#[derive(Debug)]
pub enum GatewayMessage {
    None,                                     // Input.
    AddTx(InternalTransaction, AccountState), // Output.
}
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, @MohammadNassar1, and @uriel-starkware)

___
*[`crates/mempool/src/mempool.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCvV92Aufe8f-mE_5Z:-NxCvV92Aufe8f-mE_5_:b-ys98i3) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/mempool/src/mempool.rs#L10)):*
> ```XML
> 
> use starknet_mempool_types::mempool_types::AccountState;
> use starknet_mempool_types::mempool_types::MempoolNetworkComponent;
> ```

I wonder why rustfmt didn't whine about these, they should be bundled together.



_Code quote:_
```XML
use starknet_mempool_types::mempool_types::AccountState;
use starknet_mempool_types::mempool_types::MempoolNetworkComponent;
```
___
*[`crates/mempool/src/mempool.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCw6pW0dIB95wQ2MC3:-NxCw6pW0dIB95wQ2MC4:bhdhntf) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/mempool/src/mempool.rs#L21)):*
> ```XML
>     pub fn new(network: MempoolNetworkComponent) -> Self {
>         Self { network }
>     }
> ```

You have the struct literal constructor (all fields are public)

**Comment by ArniStarkware** [comment]
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxGytxb8c3AlYRUj_3D:-NxGytxb8c3AlYRUj_3E:b-ji1xxl) ([raw file](https://github.com/starkware-libs/mempool/blob/91beff9f8ad98d1b78a89ce6f7e8d006348aedcf/crates/mempool_types/src/mempool_types.rs#L30)):*
> ```XML
>     None,                                     // Input.
>     AddTx(InternalTransaction, AccountState), // Output.
> }
> ```

Is the type `None` really used somewhere? Is it needed?



_Suggestion:_
```XML
#[derive(Debug)]
pub enum GatewayMessage {
    AddTx(InternalTransaction, AccountState), // Output.
}
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 2 of 11 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @Itay-Tsabary-Starkware, @MohammadNassar1, and @uriel-starkware)

___
*[`crates/mempool/src/mempool.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxCw6pW0dIB95wQ2MC3:-NxGtePO02X3i131JVzT:b32viz) ([raw file](https://github.com/starkware-libs/mempool/blob/5fefcd45814f831942be2a9042d9bf858a6f02e7/crates/mempool/src/mempool.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not anymore :).
</blockquote></details>

:P
___
*[`crates/mempool/src/mempool.rs` line 25 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH1FpQB0C4f_GqD7au:-NxH1FpQB0C4f_GqD7av:b-v5gprg) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L25)):*
> ```XML
>     txs_queue: PriorityQueue,
>     state: HashMap<ContractAddress, AccountState>,
>     pub network: MempoolNetworkComponent,
> ```

public before private



_Suggestion:_
```XML
    pub network: MempoolNetworkComponent,
    txs_queue: PriorityQueue,
    state: HashMap<ContractAddress, AccountState>,
```
___
*[`crates/mempool/src/mempool.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH3Hvv9AWsxZeEC0WY:-NxH3Hvv9AWsxZeEC0WZ:bwvfw2t) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L59)):*
> ```XML
>     }
> 
>     pub fn create_empty_mempool() -> Self {
> ```

Canonical naming, for example [here](https://doc.rust-lang.org/std/iter/fn.empty.html) and [here](https://docs.rs/tokio/latest/tokio/io/fn.empty.html#:~:text=Function%20tokio%3A%3Aio%3A%3Aempty&text=Creates%20a%20value%20that%20is,Ready(Ok(0))%20.) 
(BTW look at the captions for the code blocks in the second example, lol)



_Suggestion:_
```XML
    pub fn empty() -> Self {
```
___
*[`crates/mempool/src/mempool.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH09NuDJnnvS4JKG7V:-NxH09NuDJnnvS4JKG7W:bjvybm9) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L90)):*
> ```XML
> 
>         mempool
>     }
> ```

These shouldn't be compiled in production, I think.

Should probably be behind cfg(test).
Would have preferred a test fixture, because it's single-use for now and might remain so, but since the test in question is not mempool_test.rs specifically it might hit a visibility issue, and making the fields `pub(crate)` is probably asking for trouble given the coupling between them.



_Code quote:_
```XML
    pub fn create_empty_mempool() -> Self {
        Self::create_for_testing(vec![])
    }

    pub fn create_for_testing(inputs: impl IntoIterator<Item = MempoolInput>) -> Self {
        let (_, rx_gateway_2_mempool) = channel::<GatewayMessage>(1);
        let (tx_mempool_2_gateway, _) = channel::<MempoolMessage>(1);

        let network = MempoolNetworkComponent::new(tx_mempool_2_gateway, rx_gateway_2_mempool);

        let mut mempool = Mempool {
            txs_queue: Default::default(),
            state: Default::default(),
            network,
        };

        mempool.txs_queue = PriorityQueue::from_iter(inputs.into_iter().map(|input| {
            let prev_value = mempool.state.insert(
                input.account.address, input.account.state
            );
            // Assert that the contract address does not exist in the mempool's state to ensure that
            // there is only one transaction per contract address.
            assert!(
                prev_value.is_none(),
                "Contract address: {:?} already exists in the mempool. Can't add {:?} to the mempool.",
                input.account.address, input.tx
            );
            input.tx
        }));

        mempool
    }
```
___
*[`crates/mempool/src/mempool_test.rs` line 86 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH2bYX6oLkQFAxifCs:-NxH2bYX6oLkQFAxifCt:b-qjej15) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L86)):*
> ```XML
>     );
> 
>     let mut mempool = Mempool::create_for_testing(vec![
> ```

while we're here, no need to allocate on the heap



_Suggestion:_
```XML
    let mut mempool = Mempool::create_for_testing([
```
___
*[`crates/mempool/src/mempool_test.rs` line 158 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH2iyj8AvWJxs4o2fG:-NxH2iyj8AvWJxs4o2fH:b6x2qg9) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L158)):*
> ```XML
> 
>     // This call should panic because of duplicate contract addresses
>     let _mempool = Mempool::create_for_testing(inputs.into_iter());
> ```

While we're here, no need to explicitly create an iterator, the constructor just needs a type that implements into_iter, not necessarily be an IntoIterator itself.



_Suggestion:_
```XML
    let _mempool = Mempool::create_for_testing(inputs);
```
___
*[`crates/mempool/src/mempool_test.rs` line 188 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH1sTh4O_tyPfTQP3L:-NxH1sTh4O_tyPfTQP3M:bi4vfwi) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L188)):*
> ```XML
>     );
> 
>     let mut mempool = Mempool::create_empty_mempool();
> ```

inject through fixture plz



_Code quote:_
```XML
    let mut mempool = Mempool::create_empty_mempool();
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 10 files at r5, 4 of 9 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, @MohammadNassar1, and @uriel-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH7x8jCXlP54U6ysIw:-NxH7x8jCXlP54U6ysIx:b-d4x4bw) ([raw file](https://github.com/starkware-libs/mempool/blob/91beff9f8ad98d1b78a89ce6f7e8d006348aedcf/crates/gateway/src/gateway.rs#L45)):*
> ```XML
>             network,
>         }
>     }
> ```

All members of `Gateway` are public so there is no need for a constructor.



_Code quote:_
```XML
    pub fn new(
        config: GatewayConfig,
        stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
        network: GatewayNetworkComponent,
    ) -> Self {
        Self {
            config,
            stateless_transaction_validator_config,
            network,
        }
    }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: 7 of 11 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, @Itay-Tsabary-Starkware, and @uriel-starkware)

___
*[`crates/gateway/src/gateway.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH7x8jCXlP54U6ysIw:-NxMMNMF0hHSo8Zmj1hu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/91beff9f8ad98d1b78a89ce6f7e8d006348aedcf/crates/gateway/src/gateway.rs#L45)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

All members of `Gateway` are public so there is no need for a constructor.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 25 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH1FpQB0C4f_GqD7au:-NxMN8vTA7VKDcJ2RqVW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

public before private
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH3Hvv9AWsxZeEC0WY:-NxMNNpFER2CrfQo8EBd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Canonical naming, for example [here](https://doc.rust-lang.org/std/iter/fn.empty.html) and [here](https://docs.rs/tokio/latest/tokio/io/fn.empty.html#:~:text=Function%20tokio%3A%3Aio%3A%3Aempty&text=Creates%20a%20value%20that%20is,Ready(Ok(0))%20.) 
(BTW look at the captions for the code blocks in the second example, lol)
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 90 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH09NuDJnnvS4JKG7V:-NxMPZkuAAzOLdpQS9Qo:bi7v2d9) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool.rs#L90)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

These shouldn't be compiled in production, I think.

Should probably be behind cfg(test).
Would have preferred a test fixture, because it's single-use for now and might remain so, but since the test in question is not mempool_test.rs specifically it might hit a visibility issue, and making the fields `pub(crate)` is probably asking for trouble given the coupling between them.
</blockquote></details>

Makes sense.
updated.
___
*[`crates/mempool/src/mempool_test.rs` line 86 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH2bYX6oLkQFAxifCs:-NxMOHjJ2eiA7yFtjsww:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

while we're here, no need to allocate on the heap
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 158 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH2iyj8AvWJxs4o2fG:-NxMNXIU1Lgx5IUvkSsm:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L158)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

While we're here, no need to explicitly create an iterator, the constructor just needs a type that implements into_iter, not necessarily be an IntoIterator itself.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 188 at r6](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxH1sTh4O_tyPfTQP3L:-NxMOEkm1cC7vh85MD7W:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a8a037c5e24ed4955d902b1cae593621783a5dc5/crates/mempool/src/mempool_test.rs#L188)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

inject through fixture plz
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxGytxb8c3AlYRUj_3D:-NxMgzJFBX3i4eE2o3Ie:b-z9q03z) ([raw file](https://github.com/starkware-libs/mempool/blob/91beff9f8ad98d1b78a89ce6f7e8d006348aedcf/crates/mempool_types/src/mempool_types.rs#L30)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is the type `None` really used somewhere? Is it needed?
</blockquote></details>

After discussing with @uriel-starkware, he suggests using directed message types. This means defining one message type for communication from Gateway to Mempool and another from Mempool to Gateway.

There are no messages passed from GW to Mempool, so I used ().

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, @Itay-Tsabary-Starkware, and @uriel-starkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r6, 1 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97#-:-NxMnHbc1-5G4krwWo_F:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @uriel-starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @uriel-starkware)

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/97)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/97#-NxGytxb8c3AlYRUj_3D:-NxMk7no6txqxv9nPftd:b-kdbt8c) ([raw file](https://github.com/starkware-libs/mempool/blob/91beff9f8ad98d1b78a89ce6f7e8d006348aedcf/crates/mempool_types/src/mempool_types.rs#L30)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

After discussing with @uriel-starkware, he suggests using directed message types. This means defining one message type for communication from Gateway to Mempool and another from Mempool to Gateway.

There are no messages passed from GW to Mempool, so I used ().
</blockquote></details>

looks good to me :)

**Pull request merged**
