### PR TITLE
feat(gateway): mock blockifier validator

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/369#-O0y9uU_9S4BZU5shCmr:-O0y9uU_9S4BZU5shCms:bg5caij) (no related file):*
This PR is quite large. Please break it down into smaller PRs.
Perhaps:
-   Trait definition
-   Breakdown of `run_validate`
-   Generalization of `run_validate`

And so on.

___

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1B9JKGBUNvx4Gn4ogt:-O1B9JKGBUNvx4Gn4ogu:bthkv5x) ([raw file](https://github.com/starkware-libs/mempool/blob/b6b9da6ab30b3592ad5488bbe19e097bf7f0f750/crates/gateway/src/stateful_transaction_validator.rs#L67)):*
> ```XML
>     }
> 
>     pub fn prepare_validate(
> ```

What about tests for this function?



_Code quote:_
```XML
pub fn prepare_validate(
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1B7MH23aTFbfJ68z3P:-O1B7MH23aTFbfJ68z3Q:b-4psygs) ([raw file](https://github.com/starkware-libs/mempool/blob/b6b9da6ab30b3592ad5488bbe19e097bf7f0f750/crates/gateway/src/stateful_transaction_validator_test.rs#L23)):*
> ```XML
> 
> #[rstest]
> #[case::valid_invoke_tx_cairo1(
> ```

There is no meaning in having all these test cases anymore. The different `external_tx` has really no affect on the test.
I guess we only need 2 cases, one in which `mock_validator.validate()` returns ok, and another in which it returns an error.

We should add tests to check we properly convert to an eccount tx, but that should be in a test file for `utils` where the conversion is implemented.

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This PR is quite large. Please break it down into smaller PRs.
Perhaps:
-   Trait definition
-   Breakdown of `run_validate`
-   Generalization of `run_validate`

And so on.
</blockquote></details>

Note that it is separated by commits.
Do you still prefer separated PRs?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1B9JKGBUNvx4Gn4ogt:-O1BaBJe6qwgHTROn1ks:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b6b9da6ab30b3592ad5488bbe19e097bf7f0f750/crates/gateway/src/stateful_transaction_validator.rs#L67)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What about tests for this function?
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1B7MH23aTFbfJ68z3P:-O1BbwuE9huwQmXOhere:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b6b9da6ab30b3592ad5488bbe19e097bf7f0f750/crates/gateway/src/stateful_transaction_validator_test.rs#L23)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

There is no meaning in having all these test cases anymore. The different `external_tx` has really no affect on the test.
I guess we only need 2 cases, one in which `mock_validator.validate()` returns ok, and another in which it returns an error.

We should add tests to check we properly convert to an eccount tx, but that should be in a test file for `utils` where the conversion is implemented.
</blockquote></details>

Done.

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note that it is separated by commits.
Do you still prefer separated PRs?
</blockquote></details>

Opened preliminary PR: https://github.com/starkware-libs/mempool/pull/381

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/369#-O0y9uU_9S4BZU5shCmr:-O1BYq178OKXokNq5S9s:b-7xt2lm) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Note that it is separated by commits.
Do you still prefer separated PRs?
</blockquote></details>

Yes, 

___
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1H7bjF8LA0IlBUTIvD:-O1H7bjF8LA0IlBUTIvE:b-vvtdi6) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc6dc9e930d41881a1e81b2a2edd9f8568e3a4/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
> ```XML
> 
> #[automock]
> pub trait StatefulTransactionValidatorTrait {
> ```

Can also be separated to another PR.



_Code quote:_
```XML
pub trait StatefulTransactionValidatorTrait
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1H7bjF8LA0IlBUTIvD:-O1Hi70v6ckol9msK2Q2:bl7w8yd) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc6dc9e930d41881a1e81b2a2edd9f8568e3a4/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can also be separated to another PR.
</blockquote></details>

I don't think it is correct to separate it. The only reason to add this trait is for the mock.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369#-:-O1LwDI6AonEaYjSBhB1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1RTpWbCb1gsChfO3G2:-O1RTpWbCb1gsChfO3G3:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator.rs#L31)):*
> ```XML
> #[cfg_attr(test, automock)]
> pub trait StatefulTransactionValidatorTrait {
>     fn perform_validations(
> ```





_Suggestion:_
```XML
validate
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1RTreH98GPT4oSX2A5:-O1RTreI-JbhQ7_PyZN1:b-k9cxd6) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator.rs#L38)):*
> ```XML
> }
> 
> impl StatefulTransactionValidatorTrait for BlockifierStatefulValidator {
> ```

WDYT about moving this trait to Blockifier?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1RTpWbCb1gsChfO3G2:-O1WkWwFC3LH094Y905f:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator.rs#L31)):*
> ```XML
> #[cfg_attr(test, automock)]
> pub trait StatefulTransactionValidatorTrait {
>     fn perform_validations(
> ```

done
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1RTreH98GPT4oSX2A5:-O1WhVdE8g5oAiClp32e:blitcbo) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about moving this trait to Blockifier?
</blockquote></details>

Added TODO (will do this when we move to mono repo)
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1WhwDS69CeDzKmZnco:-O1WhwDS69CeDzKmZncp:bcyj48t) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
> ```XML
>         Ok(..) => Ok(()),
>         Err(e) => Err(e),
>     });
> ```

@elintul - this code is possible thanks to the `mockall` attribute.
Notice I didn't have to create any new struct in order to mock the trait.



_Code quote:_
```XML
    let mut mock_validator = MockStatefulTransactionValidatorTrait::new();
    mock_validator.expect_perform_validations().return_once(|_, _| match expected_result {
        Ok(..) => Ok(()),
        Err(e) => Err(e),
    });
```

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 4 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1H7bjF8LA0IlBUTIvD:-O1qJeLE2e9SSwiKXEvW:b3vm4p4) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc6dc9e930d41881a1e81b2a2edd9f8568e3a4/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think it is correct to separate it. The only reason to add this trait is for the mock.
</blockquote></details>

If the only usage of a trait is by a testing framework then I'm not sure the trait should be added to production.
If, for example, we suspect we'd want to "switch a backend" or implementation for a validator, then the trait might be justified.

Also, if indeed the trait cannot be justified on it's own, without mockall, then I think mockall can be applied directly onto a struct, without a trait ([second code block here](https://docs.rs/mockall/latest/mockall/attr.automock.html#examples))

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1H7bjF8LA0IlBUTIvD:-O1qh7G_6Zr9SVTwerHQ:bta9j7w) ([raw file](https://github.com/starkware-libs/mempool/blob/72dc6dc9e930d41881a1e81b2a2edd9f8568e3a4/crates/gateway/src/stateful_transaction_validator.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If the only usage of a trait is by a testing framework then I'm not sure the trait should be added to production.
If, for example, we suspect we'd want to "switch a backend" or implementation for a validator, then the trait might be justified.

Also, if indeed the trait cannot be justified on it's own, without mockall, then I think mockall can be applied directly onto a struct, without a trait ([second code block here](https://docs.rs/mockall/latest/mockall/attr.automock.html#examples))
</blockquote></details>

I agree in theory that the trait is not required, but:
1. What you suggest requires changing the type in blockifier, and it is pretty hard to update dependencies right now
2. Not sure the blockifier should provide the ability to mock itself
3. [You can't derive `automock` in structs that implement traits](https://docs.rs/mockall/latest/mockall/attr.automock.html#examples:~:text=Mocking%20a%20struct%20that%20has%20multiple%20impl%20blocks%2C%20including%20structs%20that%20implement%20traits.) so I don't want to get frustrated in the future because of the derive

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 6 files at r6, 3 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r9](https://reviewable.io/reviews/starkware-libs/mempool/369#-O2Tsrko8ba4oPdF3oCp:-O2TsrkpBIm2fKJsBSFI:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/bebadbacb341561433e5a177e8f387555d0cbff8/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
> ```XML
> 
> impl StatefulTransactionValidator {
>     pub fn run_validate<TStatefulTransactionValidator: StatefulTransactionValidatorTrait>(
> ```





_Suggestion:_
```XML
V
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1WhwDS69CeDzKmZnco:-O2TtmcB1KEs78BtUb3u:b-q4x7vc) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

@elintul - this code is possible thanks to the `mockall` attribute.
Notice I didn't have to create any new struct in order to mock the trait.
</blockquote></details>

Can't we use idiomatic combinators here? `Err(e) -> Err(e)` looks bad. What's the behavior you want here?
Why not:
```rs
mock_validator.expect_validate().return_once(|_, _| {
    expected_result.map_err(|e| e)
});
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1WhwDS69CeDzKmZnco:-O2UIlPmAjpdRvNk78lf:bcm83h4) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't we use idiomatic combinators here? `Err(e) -> Err(e)` looks bad. What's the behavior you want here?
Why not:
```rs
mock_validator.expect_validate().return_once(|_, _| {
    expected_result.map_err(|e| e)
});
```
</blockquote></details>

It also maps Ok(something( to Ok(()), I think match looks better than `expected_result.map(...).map_err(...)`

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r9](https://reviewable.io/reviews/starkware-libs/mempool/369#-O2Tsrko8ba4oPdF3oCp:-O2ULPQYDsnLpaxBNHo9:bg8uyzq) ([raw file](https://github.com/starkware-libs/mempool/blob/bebadbacb341561433e5a177e8f387555d0cbff8/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
> ```XML
> 
> impl StatefulTransactionValidator {
>     pub fn run_validate<TStatefulTransactionValidator: StatefulTransactionValidatorTrait>(
> ```

mistake?

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/mempool/369#-O1WhwDS69CeDzKmZnco:-O2UMr5P85yI_m9JaEI_:bez2dfa) ([raw file](https://github.com/starkware-libs/mempool/blob/85af312f9e8435f3e07ae66ed57e7930237d4cc0/crates/gateway/src/stateful_transaction_validator_test.rs#L67)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It also maps Ok(something( to Ok(()), I think match looks better than `expected_result.map(...).map_err(...)`
</blockquote></details>

nvm, done

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r9](https://reviewable.io/reviews/starkware-libs/mempool/369#-O2Tsrko8ba4oPdF3oCp:-O2UOx4w7T-XcKaDrKPQ:b-texc0v) ([raw file](https://github.com/starkware-libs/mempool/blob/bebadbacb341561433e5a177e8f387555d0cbff8/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

mistake?
</blockquote></details>

Nope, I think usually generic types can be of 1-2 letters, less cognitive load.

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r9](https://reviewable.io/reviews/starkware-libs/mempool/369#-O2Tsrko8ba4oPdF3oCp:-O2UR0dcEEBrXFlYZRAy:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/bebadbacb341561433e5a177e8f387555d0cbff8/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nope, I think usually generic types can be of 1-2 letters, less cognitive load.
</blockquote></details>

done

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369#-:-O2URIllELG3G4zPLWRK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
