### PR TITLE
fix: change n_accounts to usize

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/372#-O1B-ZJFCBSdYW7071gW:-O1B-ZJFCBSdYW7071gX:b-v0duql) ([raw file](https://github.com/starkware-libs/mempool/blob/b373ac8e97344fc9e758948453a6a39830814a01/crates/tests-integration/src/integration_test_setup.rs#L33)):*
> ```XML
> 
> impl IntegrationTestSetup {
>     pub async fn new(n_initialized_account_contracts: usize) -> Self {
> ```

Why did you change it?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372#-:-O1B6_aj6z3gUs3aZrLj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/372#-O1B-ZJFCBSdYW7071gW:-O1B84eQ206LY5nJbIIA:bb08lcm) ([raw file](https://github.com/starkware-libs/mempool/blob/b373ac8e97344fc9e758948453a6a39830814a01/crates/tests-integration/src/integration_test_setup.rs#L33)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why did you change it?
</blockquote></details>

`n_<thing>` is usize by convention, the representation size for the number is an implementation detail.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
