### PR TITLE
feat: add functionality to create all components

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #311
- #310
- #309
- #308
- #307 ⬅
- #262
- #261

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/307)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/307#-:-O0PqH7k2N8SvtzT75rg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/307)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/307)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#308](https://github.com/starkware-libs/mempool/pull/308)

**Pull request closed without merging**
