### PR TITLE
chore: move chain info config out of stateful validator config

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/188)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/188?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#188** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/188?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/188)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`config/default_config.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/188#-Nz8-VhkBfdcYX2s89uN:-Nz8-VhkBfdcYX2s89uO:b-ca8mai) ([raw file](https://github.com/starkware-libs/mempool/blob/91be52a359567f45fc15a497e3ce9ed662b7d4ce/config/default_config.json#L12)):*
> ```JSON
>     "value": true
>   },
>   "gateway_config.chain_info_config.chain_id": {
> ```

Can you please explain the change in this file?



_Code quote:_
```JSON
gateway_config.chain_info_config.chain_id": {
```
___
*[`crates/gateway/src/config.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/188#-NzRbRcE8GTJHPmGNP3o:-NzRbRcE8GTJHPmGNP3p:b-g0nab2) ([raw file](https://github.com/starkware-libs/mempool/blob/91be52a359567f45fc15a497e3ce9ed662b7d4ce/crates/gateway/src/config.rs#L31)):*
> ```XML
>                 "stateful_transaction_validator_config",
>             ),
>             append_sub_config_name(self.chain_info_config.dump(), "chain_info_config"),
> ```

You can use `chain` instead



_Suggestion:_
```XML
append_sub_config_name(self.chain_info_config.dump(), "chain_info_config"),
members.into_iter().chain(sub_configs).collect()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/188)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

**Comment by ArniStarkware** [comment]
Postponed - for now.

**Pull request closed without merging**
