### PR TITLE
test(mempool): add sequential nonces txs

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441#-:-O1Wau1t8QxAnebjoisV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1Wapy4DTLBjAnQPuHR:-O1Wapy4DTLBjAnQPuHS:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/25954f5b75b4a03226e23ff01fa7cc341fc65810/crates/mempool/src/mempool_test.rs#L254)):*
> ```XML
>     let queue_txs = [TransactionReference::new(&input_nonce_0.tx)];
>     let pool_txs = [input_nonce_0.tx, input_nonce_1.tx];
>     let mempool_state = MempoolState::new(pool_txs, queue_txs);
> ```





_Suggestion:_
```XML
    let expected_queue_txs = [TransactionReference::new(&input_nonce_0.tx)];
    let expected_pool_txs = [input_nonce_0.tx, input_nonce_1.tx];
    let mempool_state = MempoolState::new(pool_txs, queue_txs);
```

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1Wapy4DTLBjAnQPuHR:-O1Wb2Ql641-2RL4bz40:b340go6) ([raw file](https://github.com/starkware-libs/mempool/blob/25954f5b75b4a03226e23ff01fa7cc341fc65810/crates/mempool/src/mempool_test.rs#L254)):*
> ```XML
>     let queue_txs = [TransactionReference::new(&input_nonce_0.tx)];
>     let pool_txs = [input_nonce_0.tx, input_nonce_1.tx];
>     let mempool_state = MempoolState::new(pool_txs, queue_txs);
> ```

Also in the rest of the stack

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1g1RGO4qeH5aNAPk8T:-O1g1RGP3yORN4dicT4j:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c0e574f86001446a08a195a04051ba72552c80b6/crates/mempool/src/mempool_test.rs#L245)):*
> ```XML
> 
> #[rstest]
> fn test_adding_sequential_nonce_txs(mut mempool: Mempool) {
> ```





_Suggestion:_
```XML
test_add_tx_sequential_nonces
```
___
*[`crates/mempool/src/mempool_test.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1g5CydEOhbinvtnaah:-O1g5CydEOhbinvtnaai:bcw4apk) ([raw file](https://github.com/starkware-libs/mempool/blob/c0e574f86001446a08a195a04051ba72552c80b6/crates/mempool/src/mempool_test.rs#L245)):*
> ```XML
> 
> #[rstest]
> fn test_adding_sequential_nonce_txs(mut mempool: Mempool) {
> ```

Let's include some mild commenting throughout the test code, especially for visual structuring:
```rs
// Setup..
// Test.
// Assert.
```
For complex scenarios, we can add more detailed comments, such as `// Setup: do this and that, which aren't trivial.`, etc.
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1g1_kEBlVv5DcQOokS:-O1g1_kEBlVv5DcQOokT:b-uncxoe) ([raw file](https://github.com/starkware-libs/mempool/blob/c0e574f86001446a08a195a04051ba72552c80b6/crates/mempool/src/mempool_test.rs#L247)):*
> ```XML
> fn test_adding_sequential_nonce_txs(mut mempool: Mempool) {
>     let input_nonce_0 = add_tx_input!(tip: 1, tx_hash: Felt::ZERO, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
>     let input_nonce_1 = add_tx_input!(tip: 1, tx_hash: Felt::ONE, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
> ```

To help the reader quickly notice the differences between transactions when skimming through the test code, consider adding another case to the macro. Since it's meant to serve our tests, we should tailor it to our needs.

Another faster option is to fully define one input and provide a shorter definition for the other to emphasize the differences.
```rs
    let input_nonce_1 = MempoolInput {
        tx: ThinTransaction { nonce: Nonce(felt!(1_u8)), ..input_nonce_0.tx },
        ..input_nonce_0
    };
```
Seems cumbersome due to nesting; I would recommend going with the first option.



_Code quote:_
```XML
    let input_nonce_0 = add_tx_input!(tip: 1, tx_hash: Felt::ZERO, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
    let input_nonce_1 = add_tx_input!(tip: 1, tx_hash: Felt::ONE, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 0_u8);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1g6bupDlHp50_s9kmg:-O1g6bupDlHp50_s9kmh:b-809n6s) (no related file):*
Please implement my comments below to all test PRs.

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1p90yb6qxDRsnbaE5U:-O1p90yb6qxDRsnbaE5V:by2uy6u) ([raw file](https://github.com/starkware-libs/mempool/blob/6e3ff43f343a04b7bc8bf402926dc8f4d180c9af/crates/mempool/src/mempool_test.rs#L275)):*
> ```XML
> #[rstest]
> fn test_add_tx_sequential_nonces(mut mempool: Mempool) {
>     // Setup: add two transactions of the same account with sequential nonces.
> ```

Code is quite self-explanatory.



_Suggestion:_
```XML
// Setup.
```
___
*[`crates/mempool/src/mempool_test.rs` line 279 at r3](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1p96Bq3bGRmXQKZxxc:-O1p96Bq3bGRmXQKZxxd:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6e3ff43f343a04b7bc8bf402926dc8f4d180c9af/crates/mempool/src/mempool_test.rs#L279)):*
> ```XML
>     let input_nonce_1 = add_tx_input!(tx_nonce: 1_u8, account_nonce: 0_u8);
> 
>     add_tx(&mut mempool, &input_nonce_0);
> ```





_Suggestion:_
```XML
// Test.
add_tx(&mut mempool, &input_nonce_0);
```
___
*[`crates/mempool/src/mempool_test.rs` line 287 at r3](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1p99WT-z5qz3YiIeAh:-O1p99WT-z5qz3YiIeAi:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6e3ff43f343a04b7bc8bf402926dc8f4d180c9af/crates/mempool/src/mempool_test.rs#L287)):*
> ```XML
> 
>     // Ensure that the first transaction is in the queue and both transactions are in the pool.
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```





_Suggestion:_
```XML
    // Assert: only eligible transaction appears in the queue.
    let expected_queue_txs = [TransactionReference::new(&input_nonce_0.tx)];
    let expected_pool_txs = [input_nonce_0.tx, input_nonce_1.tx];
    let expected_mempool_state = MempoolState::new(expected_pool_txs, expected_queue_txs);
    expected_mempool_state.assert_eq_mempool_state(&mempool);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/mempool/441#-O1g1_kEBlVv5DcQOokS:-O1l8Z3T3Wo9TEGhEO74:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c0e574f86001446a08a195a04051ba72552c80b6/crates/mempool/src/mempool_test.rs#L247)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

To help the reader quickly notice the differences between transactions when skimming through the test code, consider adding another case to the macro. Since it's meant to serve our tests, we should tailor it to our needs.

Another faster option is to fully define one input and provide a shorter definition for the other to emphasize the differences.
```rs
    let input_nonce_1 = MempoolInput {
        tx: ThinTransaction { nonce: Nonce(felt!(1_u8)), ..input_nonce_0.tx },
        ..input_nonce_0
    };
```
Seems cumbersome due to nesting; I would recommend going with the first option.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441#-:-O1pUhCnEvPgJuKkGoqc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
