### PR TITLE
feat: make generiv component server http

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iU_HvEK8knpP7rw89:-O0iU_HvEK8knpP7rw8A:b-ktpa9d) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/src/component_server.rs#L64)):*
> ```XML
>     Component: ComponentRequestHandler<Request, Response> + Send + 'static,
>     Request: for<'a> Deserialize<'a> + Send + 'static,
>     Response: Serialize + 'static,
> ```

Please state bounds in the struct definition.



_Code quote:_
```XML
where
    Component: ComponentRequestHandler<Request, Response> + Send + 'static,
    Request: for<'a> Deserialize<'a> + Send + 'static,
    Response: Serialize + 'static,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iUv4XD1cl8RuKbW5q:-O0iUv4XD1cl8RuKbW5r:b-qzh7ji) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/src/component_server.rs#L96)):*
> ```XML
>             deserialize(&body_bytes).expect("Request deserialization should succeed");
> 
>         // Acquire the lock for component computation, release afterwards
> ```

Add "."



_Code quote:_
```XML
, release afterwards
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iW8zH2im6WS3PI4lh:-O0iW8zICFam3oHIS02N:b-tqoh2w) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/tests/component_server_client_http_test.rs#L96)):*
> ```XML
> 
>     let mut component_a_server = ComponentServerHttp::new(component_a, local_ip, a_port);
>     let mut component_b_server = ComponentServerHttp::new(component_b, local_ip, b_port);
> ```

Same as regarding the clients: please make the type explicit.



_Code quote:_
```XML
    let mut component_a_server = ComponentServerHttp::new(component_a, local_ip, a_port);
    let mut component_b_server = ComponentServerHttp::new(component_b, local_ip, b_port);
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iU_HvEK8knpP7rw89:-O0iWOGf3UDeF72JLEKR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/src/component_server.rs#L64)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please state bounds in the struct definition.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iUv4XD1cl8RuKbW5q:-O0iWOgSCApPXkVIjhA6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/src/component_server.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add "."
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/336#-O0iW8zH2im6WS3PI4lh:-O0iWRmC03SjZm8c2SZ0:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/db6feefa1a48436780e8bb495a9caf9e6f9041a9/crates/mempool_infra/tests/component_server_client_http_test.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Same as regarding the clients: please make the type explicit.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336#-:-O0iY_7c0YsaWoB4WdWZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request closed without merging**
