### PR TITLE
feat(mempool): add from_iter func to TransactionPool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419#-:-O1Qd6vA-rvly2SF-22C:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/419#-O1QcjdiEnQwyK35Z49U:-O1QcjdiEnQwyK35Z49V:b-oimgwj) (no related file):*
Can it be part of `test_utils` crate?
It may be used in end-to-end tests.
WDTY?

___
___
*[`crates/mempool/src/mempool_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/419#-O1Qcu8xBCKAap0oC2lu:-O1Qcu8xBCKAap0oC2lv:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/255c53e1ae6cf234fb3933ffe8682c9561d7262b/crates/mempool/src/mempool_test.rs#L22)):*
> ```XML
>             pool.insert(tx).unwrap();
>         }
>         pool
> ```





_Suggestion:_
```XML
        let mut pool = TransactionPool::default();
        txs.iter().for_each(|tx| pool.insert(tx));
        pool
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/419#-O1QcjdiEnQwyK35Z49U:-O1QhW1G71aZQzCrwme5:bhgh5r3) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can it be part of `test_utils` crate?
It may be used in end-to-end tests.
WDTY?
</blockquote></details>

I think it should be moved only when being used in end-to-end tests.

___
___
*[`crates/mempool/src/mempool_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/mempool/419#-O1Qcu8xBCKAap0oC2lu:-O1QgCbmBEry20mvUYTz:b-p4hvgj) ([raw file](https://github.com/starkware-libs/mempool/blob/255c53e1ae6cf234fb3933ffe8682c9561d7262b/crates/mempool/src/mempool_test.rs#L22)):*
> ```XML
>             pool.insert(tx).unwrap();
>         }
>         pool
> ```

I think the `for` loop is more readable. In terms of runtime performance, they're supposed to be the same 
https://doc.rust-lang.org/book/ch13-04-performance.html

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/419)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/mempool/419#-O1R1uAH9zh-C8z6xD_G:-O1R1uAH9zh-C8z6xD_H:bsclka4) ([raw file](https://github.com/starkware-libs/mempool/blob/90acb6eafeb551b6a33afab7158c65d3596682ce/crates/mempool/src/mempool_test.rs#L15)):*
> ```XML
> use crate::mempool::{Mempool, MempoolInput, TransactionReference};
> use crate::transaction_pool::TransactionPool;
> ```

Make the two `from_iter` impl. consistent (either `for` or `for_each` in both).

**Pull request merged**
