### PR TITLE
feat: add function to create all channels

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #311
- #310
- #309
- #308
- #307
- #262
- #261 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_channels.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pCFjY6TPMc9JMV9mI:-O-pCFjY6TPMc9JMV9mJ:b-d4wq5y) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L4)):*
> ```XML
> use tokio::sync::mpsc::{channel, Receiver, Sender};
> 
> pub struct SingleChannel<T: Send + Sync> {
> ```

Please change this to ComponentCommunication. 
Either in this pr, or in a refactoring pr in the end, and if the latter, please add a "todo" to address this issue here.



_Code quote:_
```XML
SingleChannel
```
___
*[`crates/mempool_node/src/com_channels.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pCPZ85Ehp2JxYGayb:-O-pCPZ85Ehp2JxYGayc:b-40nm0c) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L5)):*
> ```XML
> 
> pub struct SingleChannel<T: Send + Sync> {
>     pub tx: Sender<T>,
> ```

Please change these to be private members, and have a `get_tx` and `get_rx` functions.

Also, not for this pr, but I suspect eventually we'll need to _move_ ownership of the `rx` part to the server. It might make sense to change the definition here to `Optional` and use the `take()` function.



_Code quote:_
```XML
pub
```
___
*[`crates/mempool_node/src/com_channels.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pDmPgAmVN76Jwdq5K:-O-pDmPgAmVN76Jwdq5L:b-sh0bjr) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L9)):*
> ```XML
> }
> 
> pub struct CommChannels {
> ```

Please change this name to MempoolNodeCommunication. 
Same comment regarding in which pr to do that (here / later -- add a todo).



_Code quote:_
```XML
CommChannels
```
___
*[`crates/mempool_node/src/com_channels.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pDpiZCBC_68bJWl1T:-O-pDpiZCBC_68bJWl1U:bcf6gb5) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L10)):*
> ```XML
> 
> pub struct CommChannels {
>     pub mempool_channel: SingleChannel<MempoolRequestAndResponseSender>,
> ```

Ditto regarding visibility (pub) and getters.



_Code quote:_
```XML
pub
```
___
*[`crates/mempool_node/src/com_channels.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pENHSAdVZ3DjPceR3:-O-pENHSAdVZ3DjPceR4:b-hk2dsv) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L13)):*
> ```XML
> }
> 
> pub fn create_channels() -> CommChannels {
> ```

create_mempool_node_channels



_Code quote:_
```XML
create_channels
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
Please rename the file to `communication.rs`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261#-:-O-pEd4z3w-x-HL2D8tx:b-kecwl4)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pEkce5QGOYQcW_RKU):*
Please rename the file to `communication.rs`

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pEkce5QGOYQcW_RKU):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename the file to `communication.rs`
</blockquote></details>

Can be in a refactoring pr, if so, add a todo.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/com_channels.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pENHSAdVZ3DjPceR3:-O-pFNZV1HgHRkru7W3d:b-2hig53) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

create_mempool_node_channels
</blockquote></details>

Ignore the previous message, please rename to `create_node_channels`.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pEkce5QGOYQcW_RKU):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can be in a refactoring pr, if so, add a todo.
</blockquote></details>

I don't like that name but Done.
___
*[`crates/mempool_node/src/com_channels.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pCFjY6TPMc9JMV9mI:-O-pdaKp2-EcvQg9-xzO:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change this to ComponentCommunication. 
Either in this pr, or in a refactoring pr in the end, and if the latter, please add a "todo" to address this issue here.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_channels.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pCPZ85Ehp2JxYGayb:-O-pTDhZEDsEm0aqtJY9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L5)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change these to be private members, and have a `get_tx` and `get_rx` functions.

Also, not for this pr, but I suspect eventually we'll need to _move_ ownership of the `rx` part to the server. It might make sense to change the definition here to `Optional` and use the `take()` function.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_channels.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pDmPgAmVN76Jwdq5K:-O-pml0Y1mvaANjjmYpS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change this name to MempoolNodeCommunication. 
Same comment regarding in which pr to do that (here / later -- add a todo).
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_channels.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pDpiZCBC_68bJWl1T:-O-pTG9q9bOQcbWZom-a:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L10)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto regarding visibility (pub) and getters.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/com_channels.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/mempool/261#-O-pENHSAdVZ3DjPceR3:-O-pTHt32EYJG39Ty9zA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/da5398cac9ae1ebbb340e1f1536a2f11a075df2a/crates/mempool_node/src/com_channels.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ignore the previous message, please rename to `create_node_channels`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261#-:-O08Id8u4Y9g7mDuAl0u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/mempool/261#-O08IjmlDFFzW8ofVQFx:-O08IjmlDFFzW8ofVQFy:b-q4itt3) ([raw file](https://github.com/starkware-libs/mempool/blob/7547018b35324564b4a9be400857cf85f6cdeb8c/crates/mempool_node/src/communication.rs#L14)):*
> ```XML
>     }
>     fn get_rx(&mut self) -> Receiver<T> {
>         self.rx.take().expect("Receiver already taken")
> ```

Please change to the conventional expect format: "X should be Y".
For example, "Receiver should be available".



_Code quote:_
```XML
self.rx.take().expect("Receiver already taken")
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#308](https://github.com/starkware-libs/mempool/pull/308)

**Pull request closed without merging**
